### ISSUE TITLE
Hanging docker images

### ISSUE THREAD

**Issue by opahopa** [aerokube/selenoid#1003]
Hi!

my selenoid `docker-compose` config:

```
version: '3'
networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created
services:
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD/config/:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
        "-conf", "/etc/selenoid/browsers.json",
        "-container-network", "selenoid",
        "-max-timeout", "20m",
        "-timeout", "5m",
        "-session-delete-timeout", "2m",
        "-limit", "120",
      ]
    ports:
      - "14888:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      selenoid: null
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

The server seems to be doing ok with the load. CPU is at 100% at the time of starting 80+ containers at once, but the tests are completed successfully.

However, after n hours of processing the tasks,  there seems to appear hanging lost containers - `Up `N` hours`, while the tests run for no longer than 20 min and the main inactivity timeout set to 5 minutes ` "-timeout", "5m"`

What could be the reason? is it possible to solve it at the side of selenoid?

**Comment by vania-pooh** [comment]
@opahopa if you overload your server Docker starts to skip containers. So this seems to be Docker-specific issue.
