### ISSUE TITLE
[Feature] add option to limit queue

### ISSUE THREAD

**Issue by opahopa** [aerokube/selenoid#1006]
Hi!

Since i don't see that in the doc.
Would be nice to have a feature to limit queue, such as `-queue-limit int`

**Comment by vania-pooh** [comment]
@opahopa what's the use case for this option? How should Selenoid behave when queue is full?

**Comment by opahopa** [comment]
@vania-pooh 
the use case is to have a better control over hubs load. fo example during some periods i have a queue 4-5x the size of the hub capacity. apparently most of those waiting sessions will get canceled after the timeout. limiting queue to 0.5-1x of the total capacity would improve overall performance.
then the queue is full - send the response equal to the one sent in case of no slots available: `Queue Is Full`

**Comment by vania-pooh** [comment]
Closing in favor to #1009.
