### ISSUE TITLE
[Question] Is it possible to manually operate browser in a container?

### ISSUE THREAD

**Issue by 7artur7** [aerokube/selenoid#1007]
Hey. 

Is there a way to operate browsers manually? It would be useful for the manual QA team if they can interact with browsers that are currently running in a container (since it could be installed and maintained so easily). I see that it is an option to create a session manually from UI. But it only shows the current browser's state in the container and the user can't interact with it (for example input URL with a keyboard and browse through the website).

Also, manual interaction is useful for automation purposes too. For example, if I'm debugging tests and want to inspect web elements of a particular screen with help of the browser's dev tools.

**Comment by vania-pooh** [comment]
@7artur7 yes, Selenoid UI has a feature to create manual sessions.

**Comment by 7artur7** [comment]
@vania-pooh yep. But it doesn't allow me to interact with a browser. It is just like an image of what is going on inside of the container. Check the video https://monosnap.com/file/YFOsOAIqJJhh7h6btYm6yKRGctC9jg right click proposes to save an image and if inspect browser screen it is an image/png data. While my question how I can interact with this browser manually - input URL from keyboard, click on elements, inspect the shown elements with google dev tools.

**Comment by vania-pooh** [comment]
@7artur7 it does - simply click on violet button after creating a manual session. By default VNC is read-only to not break running automated tests.

**Comment by 7artur7** [comment]
@vania-pooh thanks, it works.

**Comment by aandryashin** [comment]
Hello, there is purple "lock" button (middle), you can unlock and interact
with browser.

ср, 14 окт. 2020 г., 21:11 7artur7 <notifications@github.com>:
