### ISSUE TITLE
Running Android test on VirtualBox 6.1.6

### ISSUE THREAD

**Issue by shj941013** [aerokube/selenoid#1012]
Hey guys,

I have been testing what platforms selenoid could work on and within lot of threads I saw that it could work on VMWare Fusion but not on VirtualBox for Android tests. 

With VirtualBox 6.0+ enabling nested virtualization is possible and when I try to run an Android test I see in the logs 

"emulator: CPU Acceleration: working
emulator: CPU Acceleration status: KVM (version 12) is installed and usable."

but still get the following errors

"Segmentation fault      (core dumped) ANDROID_AVD_HOME=/root/.android/avd DISPLAY="$DISPLAY" /opt/android-sdk-linux/emulator/emulator ${EMULATOR_ARGS} -writable-system -no-boot-anim -no-audio -no-jni -avd android7.0-1 -sdcard /sdcard.img -skin "$SKIN" -skindir /opt/android-sdk-linux/platforms/android-24/skins/ -verbose -gpu swiftshader_indirect -ranchu -qemu -enable-kvm
error: no devices/emulators found
error: no devices/emulators found"

I saw that in one of the post that with Segmentation fault was to try rebuilding the image which I have tried to do, but, with that approach the VirtualBox Machine just restarts completely. 

Do you know why this would be the case? Is running Android tests on VirtualBox just not possible, even with nested virtualization options?

Thank you.

**Comment by vania-pooh** [comment]
@shj941013 have no experience running Android inside VirtualBox.

**Comment by shj941013** [comment]
@vania-pooh Thank you for the response!

I actually tested it on VMware as well but getting the same issue. Do you By chance know if I have to run a specific ISO to make it work on VMWare then? I see on the other thread that it can work on VMware Fusion. (I have tried Ubuntu 18.04)
