### ISSUE TITLE
Are you planning to create new Microsoft Edge docker image with VNC support?

### ISSUE THREAD

**Issue by lepantella** [aerokube/selenoid#1015]

**Comment by vania-pooh** [comment]
@lepantella it's already with VNC support.

**Comment by lepantella** [comment]
What do I put in browsers.json then?

I tried edge and MicrosoftEdge and it says: 

> unsupported browser: MicrosoftEdge (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 637 milliseconds Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '432b96ea40e7', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.76-linuxkit', java.version: '11.0.9' Driver info: driver.version: RemoteWebDriver

My configuration is like the one below.
```
{
    "MicrosoftEdge": {
        "default": "88.0",
        "versions": {
            "88.0": {
                "image": "browsers/edge:88.0",
                "port": "4444",
            "path": "/wd/hub",
        "cpu" : "1.0",
        "mem" : "512m"
            }
        }
    }
}
```

**Comment by vania-pooh** [comment]
@lepantella should be:
```
      "MicrosoftEdge": {
        "default": "88.0",
        "versions": {
          "88.0": {
            "image": "browsers/edge:88.0",
            "port": "4444",
            "path": "/"
          }
        }
      }
```

**Comment by NetanelMosheCohen** [comment]
@vania-pooh Sorry for the poor knowledge in Docker, but I tried to run on Edge too without success. 
I added Edge capabilities to browsers.json file as you wrote, but I guess that it is not enough... Do I need get Linux based Docker image for Edge from somewhere? I tried to but I found only Windows based container for Edge. 
Please can you guide me how to make it work?
Thanks

**Comment by aandryashin** [comment]
You have to pull image manually:

docker pull browsers/edge:88.0

ср, 4 нояб. 2020 г., 09:09 Netanel Cohen <notifications@github.com>:

**Comment by NetanelMosheCohen** [comment]
@aandryashin Thanks for the quick reply.

I pulled the image successfully, restarted the containers and now it's displayed in Selenoid-UI. However, when I'm trying to run the tests, I get this error:

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found

This my python code:
driver = webdriver.Remote(
            command_executor="http://localhost:4444/wd/hub",
            desired_capabilities={"browserName": "edge", "selenoid:options": {"enableVNC": True}}
        )

Is something missing? it's looks the same as:
#1013

**Comment by aandryashin** [comment]
browserName should be exactly MicrosoftEdge and not edge, in capabilities
and in browser.json.

ср, 4 нояб. 2020 г., 14:36 Netanel Cohen <notifications@github.com>:

**Comment by NetanelMosheCohen** [comment]
@aandryashin After changing browserName to MicrosoftEdge it's working! Thanks a lot!
