### ISSUE TITLE
container-network "container:name" hostname conflict and no bindings

### ISSUE THREAD

**Issue by axkmedia** [aerokube/selenoid#1016]
Hi there,

I am trying to link browsers containers to a vpn container the way "--net=container:vpn" works:
I add -container-network "container:vpn" to docker run.
 
However I get the error that Hostname is in conflict. You can not add Hostname when referencing to container-network "container:vpn".

Looking at the code, there is always a hostname set. If it is not specfied, it will set Hostname "localhost".

So I have tried to remove it Hostname from the code, which bypasses this conflict.
But then the next error gets into play: there are no bindings for 4444.

I suspect its is looking for bindings at the wrong place.

The bindings are on the VPN container. Which selenoid and the browser containers are connected to.

Any idea how to solve this binding issue?

What additional info can I present to you if needed?

**Comment by vania-pooh** [comment]
@axkmedia have no idea how to fix this. Couldn't it be simpler to configure VPN to a custom Docker network and then simply launch browser containers in this network?

**Comment by axkmedia** [comment]
Yes, it probably would, but I was not succesful so far. 
Somehow every attempt I did, the browsers did not go through vpn tunnel. So I figured I had to use the method explained above. At first I used the image dperson. But that only works by linking with "--net=container:name". 
Then I made my own Dockerfile for a simple VPN exec. Which worked, but the browsers still didn't go through the vpn container.
Usually I can figure it out myself, but I'm lost this time.

Could you refer me to a source on how to set this up properly working with selenoid browsers containers? Or perhaps do you have a openvpn image, or, code for this? I have been banging my head on this issue for weeks now. I have googled, and tried most examples. But to no avail. I am probably just missing something simple.

Thanks for answering my question btw ;)

**Comment by axkmedia** [comment]
btw, what I want to accomplish is the following:

Start several selenoid containers, each in their own custom network, which their own vpn connection to a vpn membership (nordvpn, expressvpn, ipvanish etc.) So I am not using my own vpn server. Just openvpn client.
