### ISSUE TITLE
[SERVICE_STARTUP_FAILED] [wait: http://172.18.0.4:4444/wd/hub does not respond in 30s]

### ISSUE THREAD

**Issue by rajesh9383** [aerokube/selenoid#1021]
I am trying to execute a test on chrome-mobile browser and we are getting below error.

2020/11/23 13:23:56 [-] [NEW_REQUEST] [unknown] [10.72.86.31]
2020/11/23 13:23:56 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.72.86.31]
2020/11/23 13:23:56 [13473] [LOCATING_SERVICE] [chrome] [mobile-86.0]
2020/11/23 13:23:56 [13473] [USING_DOCKER] [chrome] [mobile-86.0]
2020/11/23 13:23:56 [13473] [CREATING_CONTAINER] [selenoid/chrome-mobile:86.0]
2020/11/23 13:23:56 [13473] [STARTING_CONTAINER] [selenoid/chrome-mobile:86.0] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c]
2020/11/23 13:23:56 [13473] [CONTAINER_STARTED] [selenoid/chrome-mobile:86.0] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c] [0.32s]
2020/11/23 13:23:56 [13473] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2020/11/23 13:23:56 [13473] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a]
2020/11/23 13:23:57 [13473] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a] [0.35s]
2020/11/23 13:24:27 [13473] [STOPPING_VIDEO_CONTAINER] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a]
2020/11/23 13:24:27 [13473] [REMOVING_CONTAINER] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a]
2020/11/23 13:24:27 [13473] [FAILED_TO_REMOVE_CONTAINER] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a] [Error response from daemon: removal of container 60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a is already in progress]
2020/11/23 13:24:27 [13473] [REMOVING_CONTAINER] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c]
2020/11/23 13:24:27 [13473] [CONTAINER_REMOVED] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c]
2020/11/23 13:24:27 [13473] [SERVICE_STARTUP_FAILED] [wait: http://172.18.0.4:4444/wd/hub does not respond in 30s]
2020/11/23 13:25:44 [-] [NEW_REQUEST] [unknown] [10.72.86.31]
2020/11/23 13:25:44 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.72.86.31]
2020/11/23 13:25:44 [13496] [LOCATING_SERVICE] [chrome] [mobile-86.0]
2020/11/23 13:25:44 [13496] [USING_DOCKER] [chrome] [mobile-86.0]
2020/11/23 13:25:44 [13496] [CREATING_CONTAINER] [selenoid/chrome-mobile:86.0]
2020/11/23 13:25:44 [13496] [STARTING_CONTAINER] [selenoid/chrome-mobile:86.0] [ad638a1639b279fe7f5653a16f97bf2f3ae0cfa352443b3192e4740be10db85e]
2020/11/23 13:25:44 [13496] [CONTAINER_STARTED] [selenoid/chrome-mobile:86.0] [ad638a1639b279fe7f5653a16f97bf2f3ae0cfa352443b3192e4740be10db85e] [0.32s]

**Comment by rajesh9383** [comment]
My browser.json file
{
    "android": {
        "default": "10.0",
        "versions": {
            "10.0": {
                "image": "selenoid/android:10.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },
    "chrome": {
        "default": "mobile-86.0",
        "versions": {
            "mobile-86.0": {
                "image": "selenoid/chrome-mobile:86.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}

**Comment by vania-pooh** [comment]
@rajesh9383 need to increase timeouts in Selenoid with these flags: `-service-startup-timeout 2m -session-attempt-timeout 2m`

**Comment by rajesh9383** [comment]
> @rajesh9383 need to increase timeouts in Selenoid with these flags: `-service-startup-timeout 2m -session-attempt-timeout 2m`

@vania-pooh Thanks for your quick reply. I already tried that but still I am getting same error. I am using below command to pass the flag.  Let me know if its correct way to send flag. 

./cm selenoid start -service-startup-timeout 2m -session-attempt-timeout 2m

**Comment by MikeDabb** [comment]
@rajesh9383 try ./cm selenoid start --args "-session-attempt-timeout 2m -service-startup-timeout 2m"

**Comment by rajesh9383** [comment]
> @rajesh9383 try ./cm selenoid start --args "-session-attempt-timeout 2m -service-startup-timeout 2m"

Thanks Mike. I am still getting same error for Chrome-mobile image. I am not getting error when I create session for regular chrome browser 

2020/11/26 02:52:27 [-] [NEW_REQUEST] [unknown] [172.22.86.6]
2020/11/26 02:52:27 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.22.86.6]
2020/11/26 02:52:27 [46] [LOCATING_SERVICE] [chromeMobile] [mobile-86.0]
2020/11/26 02:52:27 [46] [USING_DOCKER] [chromeMobile] [mobile-86.0]
2020/11/26 02:52:27 [46] [CREATING_CONTAINER] [selenoid/chrome-mobile:86.0]
2020/11/26 02:52:27 [46] [STARTING_CONTAINER] [selenoid/chrome-mobile:86.0] [d202b0d1442a8d672518d308d20e26f885713edde294895e748b944091a88ff4]
2020/11/26 02:52:28 [46] [CONTAINER_STARTED] [selenoid/chrome-mobile:86.0] [d202b0d1442a8d672518d308d20e26f885713edde294895e748b944091a88ff4] [0.29s]
2020/11/26 02:54:28 [46] [REMOVING_CONTAINER] [d202b0d1442a8d672518d308d20e26f885713edde294895e748b944091a88ff4]
2020/11/26 02:54:28 [46] [CONTAINER_REMOVED] [d202b0d1442a8d672518d308d20e26f885713edde294895e748b944091a88ff4]
2020/11/26 02:54:28 [46] [SERVICE_STARTUP_FAILED] [wait: http://172.18.0.4:4444/wd/hub does not respond in 2m0s]

**Comment by vania-pooh** [comment]
@rajesh9383 take a look at browser container logs when it's running. Also you can try to start this image manually and take a look at VNC.

**Comment by rajesh9383** [comment]
> @rajesh9383 take a look at browser container logs when it's running. Also you can try to start this image manually and take a look at VNC.

 docker logs d4bf51545419
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...

 --- x11vnc loop: 1 ---

* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: no devices/emulators found
emulator: WARNING: System image is writable
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/em                                                       ulator-acceleration.

 --- x11vnc loop: waiting for: 82

PORT=5900
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
[consvrkw3@nc2dldock01 ~]$

**Comment by dutchview-harsha** [comment]
@vania-pooh any updates on the above error even i am getting same error i am running in my local and laptop i am using is mac

**Comment by vania-pooh** [comment]
```
emulator: WARNING: System image is writable
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
```
Android images run either on hadrware Linux servers or on a Linux VM with nested virtualization enabled. Will not work under Windows \ Mac because of Docker limitations.

**Comment by vania-pooh** [comment]
@Tyson1986 I would recommend to rebuild Android images from source code. https://aerokube.com/images/latest/#_building_procedure Probably you have different Linux kernel and memory snapshot in the image is not compatible with it.
