### ISSUE TITLE
Selenoid fails to resize browser(Chrome) window horizontally only

### ISSUE THREAD

**Issue by AmitKumar83i** [aerokube/selenoid#1029]
HI All, I am using Selenoid latest version, when I am running my automation script to resize the browser window only from horizontally then, it compresses from both ways horizontally and vertically and my script is failing.
And when I am running locally without using selenoid, it works fine. please guide on this.

Here is sample code:
//Change browser size in percentage
// E.g. If you want a 70 percentage browser height then put .7 in heightInPercentage parameter
public void changeBrowserSizeInPercentage(WebDriver driver, double heightInPercentage, double widthInPercentage){
Dimension initial_size = driver.manage().window().getSize();
int height = initial_size.getHeight();
int width = initial_size.getWidth();
int heightAfterPer =(int) (height*(heightInPercentage));
int widthAfterPer = (int) (width*(widthInPercentage));
//Resize current window to the set dimension
driver.manage().window().setSize(new Dimension(heightAfterPer,widthAfterPer));

**Comment by vania-pooh** [comment]
@AmitKumar83i need Selenoid and browser versions.

**Comment by AmitKumar83i** [comment]
> @AmitKumar83i need Selenoid and browser versions.

/aerokube/selenoid:1.10.0 and Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by vania-pooh** [comment]
@AmitKumar83i is it possible to output actual window size and new window size being set? Currently seems to be code issue.

**Comment by AmitKumar83i** [comment]
@vania-pooh  
Values supplied: changeBrowserSizeInPercentage(getSettings().getDriverInstance(),1,    .65);
Here is without using Selenoid
Actual Size(1552, 840)
After changing dimension(842, 883)

Using Selenoid
Actual Size(1920, 1080)
After changing dimension(1080, 1248)

**Comment by vania-pooh** [comment]
@AmitKumar83i you are setting values incorrectly:
```java
driver.manage().window().setSize(new Dimension(heightAfterPer,widthAfterPer));
```
whereas should be:
```java
driver.manage().window().setSize(new Dimension(widthAfterPer, heightAfterPer));
```

**Comment by AmitKumar83i** [comment]
Thanks @vania-pooh , it is now resizing properly.
