### ISSUE TITLE
unable to session log

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/selenoid#1030]
I am using Selenoid 1.10.0. I have set capabilities:
 enableLog: true,
logName: "test.log"

started selenoid with
./cm selenoid start -log-output-dir /home/njagadeesh/selenoid-logs

it is not creating a log file in /home/njagadeesh/selenoid-logs . also checked ~/aerokube/selenoid/logs

http://localhost:4444/logs showing - 'not websocket protocol'

Am I missing something?

**Comment by vania-pooh** [comment]
@mnjagadeesh you are passing Selenoid flag to CM binary which is not correct. Correct command would be:
```
$ ./cm selenoid start --config-dir /home/jagadeesh/selenoid
```
Then Selenoid logs will be stored in `/home/jagadeesh/selenoid/logs` directory.

**Comment by mnjagadeesh** [comment]
@vania-pooh but I want to store logs somewhere else? Is there any otherway other than mounting some other folder to /home/jagadeesh/selenoid/logs?

Thanks

**Comment by mnjagadeesh** [comment]
I used 
`$ ./cm selenoid start --config-dir /opt/selenoid`  

Still it is not storing logs on /opt/selenoid/logs

and getting  'not websocket protocol'

**Comment by vania-pooh** [comment]
@mnjagadeesh should use `/logs/` instead of `/logs`.

**Comment by mnjagadeesh** [comment]
@vania-pooh tried /logs/ still getting 'not websocket protocol'

**Comment by vania-pooh** [comment]
@mnjagadeesh should be `http://localhost:4444/logs/` and will work when `-log-output-dir` flag is set (CM does this).
