### ISSUE TITLE
Invalid Session Id once in a while

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#1034]
Hi,

we switched our tests to not test IE11 anymore to test new MS Edge. We test in parallel with three VMs (each 10CPUs and 18GB mem) using selenoid each with `-limit 10 -cpu 1.0 -mem 1g` and video recording enabled. Now, we have test runs, where we get many of theses errors:

```
Caused by: org.openqa.selenium.NoSuchSessionException: invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'svlap020ps', ip: '10.0.44.14', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-111-generic', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 88.0.673.0, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:34381}, msedge: {msedgedriverVersion: 88.0.673.0 (7ad956de7daecab..., userDataDir: /tmp/.org.chromium.Chromium...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 8b3f0c8ab53adb24df1e11db246b40a9354bc87719bf3ba874e6380c1fbe3a87
```

This never occuered when we ran out tests using selenoid with IE11. Also the tests are not always the same and we have ensured, that no driver close ist called in between.

This is the edge part of our browsers.json:
```
  "MicrosoftEdge": {
    "default": "88.0",
    "versions": {
      "88.0": {
        "image": "browsers/edge:88.0",
        "path": "/",
        "port": "4444"
      }
    }
  },
```

I tried to reproduce the error locally using selenoid, but I never hit the error.

Do you have any ideas where to look at or what to do or to try?

**Comment by vania-pooh** [comment]
@benzman81 this seems to be Chromedriver code bug / particularity. Because we have seen the same stuff with Chromedriver and Edgedriver is just the same code.

**Comment by benzman81** [comment]
@vania-pooh so from infrastructure point of view a cpu or memory resource problem can be not be a problem, correct? I tries to force low mem and could never get this error. Just want to make sure that we dont have an issue there as I will for now add the error "invalid session id" to our retry mechanism.

**Comment by vania-pooh** [comment]
@benzman81 you are not the first reporting such error message, so I don't think this is your issue.

**Comment by benzman81** [comment]
@vania-pooh ok, thank you very much.

**Comment by Sree9120** [comment]
I also see this issue of invalid session id (it mainly happens in higher envs /non dev). Any solution to this?

**Comment by Andruschakevich** [comment]
+1 I struggle a lot with "invalid session id" issue. Any solution/suggestion?

**Comment by vania-pooh** [comment]
@Andruschakevich make sure you have sufficient memory. Usually this occurs when browser just crashes.
