### ISSUE TITLE
improvement/change request

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/selenoid#1035]
In one of the configuration [browsers.json]  someone configured [misconfigured]  version 'ANY' pointing to firefox:44.0
Just thinking if there is any possibility to restrict keywords to version? OR derive image name using keywords. Just to avoid cases like 44.0 pointing to 83.0 somthing like that?  Or is there any better way to avoid such configurations? May be this is a corner case but wanted to check with you if there is any better way of handling it.

**Comment by vania-pooh** [comment]
@mnjagadeesh is Selenium protocol `version` (or `browserVersion`) capability is just a string. So restricting only to numbers will make Selenoid not respecting Selenium protocol. I would leave as is.

**Comment by mnjagadeesh** [comment]
Thanks for the note.
