### ISSUE TITLE
Question: firefox 83 driver issue?

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/selenoid#1037]
For firefox 83, I am getting 
 E/launcher - Unable to parse new session response: 

I am using 1.10.0 selenoid and selenoid/firefox:83.0

**Comment by vania-pooh** [comment]
@mnjagadeesh need detailed request and response body.

**Comment by mnjagadeesh** [comment]
@vania-pooh   Here is a resonse body:

Failed: Unable to parse new session response: {"value":{"sessionId":"45e6c468-cc00-4f04-a9cc-1f994bf542a8","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"83.0","count":1,"moz:accessibilityChecks":false,"moz:buildID":"20201112153044","moz:geckodriverVersion":"0.28.0","moz:headless":false,"moz:processID":112,"moz:profile":"/tmp/rust_mozprofile6UuCqP","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platform":"ANY","platformName":"linux","platformVersion":"5.5.7-1.el7.elrepo.x86_64","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}

Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

**Comment by vania-pooh** [comment]
@mnjagadeesh this is a correct Selenium protocol response when session is created. So there is an issue in your Selenium library. I would try to update it.

**Comment by mnjagadeesh** [comment]
@vania-pooh Thanks. will try it and let you know.
