### ISSUE TITLE
Chrome 87 debugger randomly disconencts, but the driver keeps running as if nothing happened.

### ISSUE THREAD

**Issue by AgentRG** [aerokube/selenoid#1039]
Nothing much to go with. While a test is running locally, at one point the debugger would disconnect and cause the test to just keep running without returning any more logs. No apparent pattern regarding to what might cause it to disconnect - sometimes it finishes the test without disconnecting. The capabilities used (Python):

```
capabilities = {
    "browserName": "chrome",
    "browserVersion": "87.0",
    "env": ["VERBOSE=true", "no-sandbox"],
    "selenoid:options": {
        "enableVNC": True,
        "enableVideo": True,
        "enableLog": True,
    }
}
```

![Screen Shot 2021-01-04 at 4 13 07 PM](https://user-images.githubusercontent.com/23729455/103592574-3c6a3e00-4ea8-11eb-94c1-b0c4c67a400e.png)

**Comment by vania-pooh** [comment]
@AgentRG couldn't it be Chrome crash? Check for OOM entries in `dmesg` first.

**Comment by AgentRG** [comment]
@vania-pooh Watching live trail, this is the most eye-catching error that pops up when the disconnect error appears.

Note: The driver itself doesn't crash. The driver keeps running the test and will even finish, but the logs themselves stop being collected.

``macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50728): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50727): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50726): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50725): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50724): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50723): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50722): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50721): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger
macOSTaskPolicy: (<unknown>) may not get the taskport of (mdworker_shared) (pid: 50720): (mdworker_shared) is hardened, (mdworker_shared) doesn't have get-task-allow, (<unkn
own>) is not a declared debugger```
