### ISSUE TITLE
Question: Chrome container is not killed after testcase completion

### ISSUE THREAD

**Issue by mnjagadeesh** [aerokube/selenoid#1040]
It is noticed docker/chrome is not terminated by selenoid when testcase run is completed.
Env: centos 7 with  5.5.7-1.el7.elrepo.x86_64 kernel

$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 13
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.5.7-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.79GiB
 Name: POCSelenoid01
 ID: H3XU:EDE3:2ZH2:SL4O:OIDR:OZAL:OTCA:65NJ:DIUP:C5ZG:MNZ3:A7XO
 Docker Root Dir: /apps/jnm/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by vania-pooh** [comment]
@mnjagadeesh need respective Selenoid logs related to frozen containers. Usually this happens because of overloaded Docker instance.
