### ISSUE TITLE
Session id invalid when running tests in more than 16 containers

### ISSUE THREAD

**Issue by success-stha** [aerokube/selenoid#1041]
We are getting invalid session id while running tests in more than 16 containers. The tests run fine when there are less than 16 containers. 

**Error:**
`org.openqa.selenium.NoSuchSessionException: invalid session id`

**Machine Specification:**

- RAM : 64 gb
- CPU:  56 core
- Model: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz 
- OS: Red Hat Enterprise Linux Server 7.7

Here is out _Browser.json_
```
{
 "MicrosoftEdge": {
        "default": "88.0",
        "versions": {
          "88.0": {
            "image": "browsers/edge:88.0",
            "port": "4444",
            "volumes": ["/opt/docker/fileDownloadLocation:/home/selenium/Downloads","/opt/docker/selenoid/logs/:/opt/selenoid/logs/"],
            "path": "/",
            "shmSize": 2147483648,
            "tmpfs": {"/tmp": "size=2048m", "/var": "size=1024m"},
            "mem" : "2048m"
          }
        }
      }
}
```

**Comment by vania-pooh** [comment]
@success-stha seems to be Chromedriver issue. E.g. https://stackoverflow.com/questions/56002701/selenium-webdriver-error-invalid-session-id

**Comment by Dor-bl** [comment]
while we didnt saw this issue with Chrome 98.0 , we start seeing it again with 99.0+ .
anything we can check further?

**Comment by vania-pooh** [comment]
@Dor-bl probably could be also related to increased `/dev/shm` consumption. Try to increase `shmSize` parameter in `browsers.json`.
