### ISSUE TITLE
Degration in hub performance

### ISSUE THREAD

**Issue by shj941013** [aerokube/selenoid#1042]
Hello, In RHEL 7.7 I see a significant degration in performance. 

In hub, when trying to run 50 sessions of bringing chrome browsers in RHEL 7.7 it took ~2-3 seconds but now in RHEL 7.7+ to bring them up it takes more than a minute or two. The more session there is the longer it takes. does anyone know what the cause could be? I thought it could be the linux security feature that was added to RHEL 7.7 so tried disabling but that didn't seem to help. 

Update:
when looking into the docker container of the browser i'm getting the following: 

```
[Listening on :7070]
Logging to: /dev/null
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...

```

**Comment by vania-pooh** [comment]
@shj941013 take a look at host system metrics. Usually this means you overloaded the server.

**Comment by shj941013** [comment]
@vania-pooh Thank you for the response! 

I'm running this on AWS EC2 and it doesn't seem like there is a problem within the CPU nor memory. hmm..

When it's Waiting X server, What exact server is it waiting for? is it VNC server? or the hub to response back to the container?

**Comment by vania-pooh** [comment]
@shj941013 these messages mean that we are waiting for X server (used to render graphics under Linux) to start. In case of Selenoid images we are using XVFB as X server.
