### ISSUE TITLE
How to connect selenoid browser with proxy when the tests are executed on CI instance I don't control

### ISSUE THREAD

**Issue by AnatoliiHanziuk** [aerokube/selenoid#1044]
It's not an issue but a question on how to connect Selenoid and Selenide and proxy running on remote hosts.  

I have the setup where the tests are executed as a part of AWS CodePipeline during the CodeBuild stage. It means that I don't control the instances where the execution on CodeBuild step happens and I cannot adjust the network settings there. Tests are executed inside the Docker container.  
I use Selenide to start the proxy server and specify these properties
```
Configuration.proxyEnabled = true;
// GGR and multiple Selenoid instances are inside of the same AWS account in the same region as the CodePipeline is executed in.
Configuration.remote = <ggrHost>;
Configuration.proxyHost = ???;
```
I want the responses sent by the server of my application to be intercepted and overridden by the proxy to see the same pre-defined data in the browser during each execution of the test.  
The browser should be able to access the host with the proxy to receive stubbed responses.  

Which value do I need to specify for the `Configuration.proxyHost` in this setup?  

If I specify, for example, `InetAddress.getLocalHost().getHostAddress();` or `new NetweorkUtils().getNotLoopbackAddressOfThisMachine()` I receive `The site cannot be reached. ERR_TIMED_OUT` error in the browser. So it looks like the browser is trying to connect the proxy server to pass the command through it but it doesn't have access to proxy.

**Comment by vania-pooh** [comment]
@AnatoliiHanziuk I would suggest using Chrome Developer Tools Protocol to mock responses inside the browser. https://github.com/aerokube/chrome-developer-tools-protocol-java-example/blob/master/src/test/java/com/aerokube/selenoid/ChromeDevtoolsTest.java#L171

**Comment by AnatoliiHanziuk** [comment]
@vania-pooh , it's a good idea I also had in my mind but in this case I'm limiting the selection of the browsers. At least until Firefox adds the suport of CDP.  
I thought that the problem I have should be quite common (people execute their tests on CircleCI, TravicCI, GitlabCI, etc) and there should be an easy way to establish visibility between the place of the test execution, proxy and browser in Selenoid container started on the different host.

**Comment by vania-pooh** [comment]
@AnatoliiHanziuk I would ask in Selenide support then.
