### ISSUE TITLE
Selenoind does not start session and tests return some connection/timout issues like "DevToolsActivePort file doesn't exist" or other

### ISSUE THREAD

**Issue by magdalenadn** [aerokube/selenoid#1045]
Hello, 
My tests have to start failing with no significant changes. By tests failing, I mean that the Solenoid session does not start at all (it appears in QUOTA, but not in queue nor new session appears). 
My tests are set to run suite by suite, running parallel 10-12 browser instances. Now I'm able to run only one suite, cause when I more of them, most tests finishes with fail:
`Message: OpenQA.Selenium.WebDriverException : unknown error: DevToolsActivePort file doesn't exist`
or:
`Message: OpenQA.Selenium.WebDriverException : wait: http://172.17.0.170:4444/ does not respond in 1m0s`
or:
`Message: OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL `

I've tried adding the `"--no-sandbox"` option on some other just googled fixes - without a success. 
Anyway, I don't think it's browser related - on Firefox I've got the same issues. **Like the root cause is that session can not be started at all when trying to create more than one instance**

Here is the code which - till yesterday - was creating a new instance:

`        public void BeforeWebScenario()
        {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability(CapabilityType.BrowserName, "chrome");
            capabilities.SetCapability("enableVNC", true);
            capabilities.SetCapability("screenResolution", "1920x1080");
            capabilities.SetCapability("cpu", "3.0");
            capabilities.SetCapability("mem", "4096m");

            InternalWebDriver = new RemoteWebDriver(new Uri("http://172.16.37.108:4444/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
            InternalWebDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);
            InternalWebDriver.Manage().Timeouts().PageLoad.Add(TimeSpan.FromSeconds(120));
            InternalWebDriver.Manage().Window.Size = new Size(1920, 1080);
            InternalWebDriver.Manage().Window.Maximize();

            UserManager = new TestUserManager();

            IsException = false;
        }`
        
       I've also tried with Chrome options, like below - with the same effect:
       
       `        public void BeforeWebScenario()
        {           
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("disable-infobars");
            options.AddArgument("enable-automation");
            options.AddArgument("disable-popup-blocking");
            options.AddArgument("ignore-certificate-errors");
            options.AddArgument("start-maximized"); 
            options.AddArgument("disable-infobars"); 
            options.AddArgument("--disable-extensions"); 
            options.AddArgument("--disable-gpu");
            options.AddArgument("--disable-dev-shm-usage"); 
            options.AddArgument("--no-sandbox");
            options.AddArgument("window-size=1920,1080");

            InternalWebDriver = new RemoteWebDriver(new Uri("http://172.16.37.108:4444/wd/hub"), options.ToCapabilities(), TimeSpan.FromSeconds(180));
            InternalWebDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);
            InternalWebDriver.Manage().Timeouts().PageLoad.Add(TimeSpan.FromSeconds(120));
            InternalWebDriver.Manage().Window.Size = new Size(1920, 1080);
            InternalWebDriver.Manage().Window.Maximize();

            UserManager = new TestUserManager();

            IsException = false;
        }`
        
        I'll be glad for any suggestion what more I can do.

**Comment by vania-pooh** [comment]
@magdalenadn you could simply overload your Selenoid with browser session requests.
