### ISSUE TITLE
Added authentication to webdriver

### ISSUE THREAD

**Issue by aprilahijriyan** [aerokube/selenoid#1046]
Maybe it would be very safe to add security to the webdriver url. Like this feature https://github.com/aerokube/selenoid-ui/issues/151

**Comment by vania-pooh** [comment]
@aprilahijriyan already implemented in [Ggr](https://github.com/aerokube/ggr).

**Comment by aprilahijriyan** [comment]
@vania-pooh Hmm, I think it's better to apply it to "selenoid". rather than creating another library.

**Comment by vania-pooh** [comment]
@aprilahijriyan this does not scale. Everything more than 50 parallel Selenium sessions will require 2 or more hosts.
