### ISSUE TITLE
selenoid/android - Google Play service is not installed

### ISSUE THREAD

**Issue by TimurNurlygayanov** [aerokube/selenoid#1047]
Hi everyone,

I'm trying to play with Android emulators with solenoid and it works nice, but I have one big issue: all android emulators don't have installed Google Play service, and my test application is showing the error on start:

This app won't run without Google Play services, which are missing from your phone.
<img width="464" alt="Снимок экрана 2021-01-23 в 10 53 43" src="https://user-images.githubusercontent.com/3113460/105573910-7329ca80-5d69-11eb-9dc7-8afb4a50de9d.png">

Is there an option to automatically install Google Play services on my emulator? Is there any options/workaround for the issue?

Similar issue with other android emulators in docker https://github.com/budtmo/docker-android/issues/130

**Comment by vania-pooh** [comment]
@TimurNurlygayanov there is such option in automation script we are using to build these images. However with Google Play services installed images for some reason do not start automatically (they block on the screen requiring to confirm some permission).

**Comment by TimurNurlygayanov** [comment]
@vania-pooh could you please describe which option do you mean or share some examples?
Thank you!

**Comment by vania-pooh** [comment]
@TimurNurlygayanov take a look at this script: https://github.com/aerokube/images/blob/master/selenium/automate_android.sh#L91-L101

**Comment by TimurNurlygayanov** [comment]
Ok I will try )

**Comment by TimurNurlygayanov** [comment]
It works! @vania-pooh Thank you!

Just create a short description of how to build these images https://github.com/TimurNurlygayanov/test-tasks-example/blob/master/selenoid-android/README.md
