### ISSUE TITLE
Add ability to suppress host/origin header for incoming requests

### ISSUE THREAD

**Issue by ZhyliaievD** [aerokube/selenoid#1049]
Hi,
Please add the ability to start selenoid in mode which would suppress incoming host/origin headers, and force it to have 'localhost' value

Reason:
safaridriver since Safari v14 throws an error on any request from remote machine: 
"'Host' header or 'Origin' header is specified and is not localhost"

Steps to reproduce:
machineA
machineB
Setup selenoid for safari on a remote machineA
Run tests from machineB (e.g create new driver instance and interact with it in any way like getCurrentUrl)
Standard Java selenium library automatically adds host/origin header which causes safaridriver to throw exceptions as it only allows localhost value

**Comment by kornel-filep** [comment]
Hi!
Seems like this issue is still present. Any workarounds for this?

**Comment by vania-pooh** [comment]
@kornel-filep try with `aerokube/selenoid:latest`. This was fixed in https://github.com/aerokube/selenoid/pull/1106 but not yet released.
