### ISSUE TITLE
How to run browser tests on a specific network interface on the host ?

### ISSUE THREAD

**Issue by AlexGrs** [aerokube/selenoid#1050]
So i have a machine with 4 different network interfaces:
1 - High Speed Internet Box --> route to internet
2 - Low Speed Internet  --> route to internet
3 - 3G Internet Box --> route to internet
4 - LAN --> Private LAN

I am trying to find a solution to be able to run a selenoid browser container and bind it's traffic to one of those interfaces.

I was successfully able to use MACVLAN to bind the traffic for some containers but unfortunately, Selenoid browser container can't be run on a MACVLAN as it gives the following error:

`no bindings available for 4444/tcp`

If you have some ideas regarding the way forward that you can share that would be great.

I am stuck on this particular issue for a long time now and running short in terms of ideas.

**Comment by vania-pooh** [comment]
@AlexGrs I would try to connect `docker0` bridge interface to one of network interfaces in your list.

**Comment by AlexGrs** [comment]
As i would like to test all 4 interfaces in // this is sadly not really possible.

**Comment by vania-pooh** [comment]
@AlexGrs it does the same as `docker network connect` command.

**Comment by AlexGrs** [comment]
After manipulatin of network conf on ht ehost machine I was able to do what I wanted. thank you
