### ISSUE TITLE
Is it possible to keep Chrome or firefox browser cache ?

### ISSUE THREAD

**Issue by AlexGrs** [aerokube/selenoid#1052]
As of now when each container is deleted, the browser cache is lost.

Is there a way for specific test scenarios to keep the cache and not delete it after the test is finished ?

**Comment by vania-pooh** [comment]
@AlexGrs you can probably mount respective directory with browser cache to a volume. But starting a clean container is a feature allowing to have predictable test execution. So we do not recommend doing this.

**Comment by AlexGrs** [comment]
I totally understand and that's why we are using selenoid. but sometimes there are some use cases where it is needed.
