### ISSUE TITLE
Starting selenoid in a CI/CD agent with the "-disable-privileged" flags

### ISSUE THREAD

**Issue by VickoValch** [aerokube/selenoid#1053]
I have a build on a CI/CD agent(linux) which starts selenoid via the CM with this command:
`./cm_linux selenoid start --vnc --browsers chrome --config-dir /src/test/resources/selenoid --args "-disable-privileged" "-mem 2g" "-cpu 1.2"`

The whole job is ran by a user called bamboo, however in the --config-dir the /video and /logs folder are created as owned by root and not by the build agent(bamboo). This leads to the agent not being able to delete them before the next build starts.
Am I misunderstanding what disable-privileged does or am I simply using it incorrect?
Also if I set the browsers.json in the  /src/test/resources/selenoid i.e. in the --config-dir will selenoid be able to read the config from there?
Thanks in advance for the answer.

**Comment by vania-pooh** [comment]
@VickoValch this flag (`-disable-privileged`) switches starting Docker containers from using `--privileged` flag to `--cap-add SYS_ADMIN` flag. This requires less privileges.

**Comment by VickoValch** [comment]
@vania-pooh ok, thanks, obviously I misunderstood what the flag does. Then about the mem and cpu flags after the args, is this the correct way to pass it, I mean this part of my command : `--args "-mem 2g" "-cpu 1.2" ` ?

**Comment by vania-pooh** [comment]
@VickoValch should be `--args "-mem 2g -cpu 1.2"`

**Comment by VickoValch** [comment]
@VickoValch ok, I knew I was making some type of mistake there, thanks, I'll close this ticket.
