### ISSUE TITLE
Limit Resources for Video Container

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#1057]
It would be nice to make it possible to set resource limits for video container, too. Currently we are facing some  performance issues on our selenoid system. Using `docker stats`, we noticed, that the video container is not respecting the resource limit flags passed to selenoid. Only the browser image does. So to make sure the video container does not use more resources than we want, it would be nice to set some limits. Also it would be nice to get some advice for some good default values ;-)

**Comment by aandryashin** [comment]
Hello, Markus!

Could you please consider to migrate to our new product called Moon:
https://aerokube.com/moon/

It developed with resource consumption in mind, all resources are
configurable and taken into account in the scheduling process.  Also it has
such features as High Availability and Auto scaling.
Here is short comparison Moon vs Selenoid:
https://aerokube.com/moon/latest/#_moon_vs_selenoid

Alexander Andryashin.

**Comment by benzman81** [comment]
@aandryashin I would, but I do not get a budget. We currently use 50 parallel sessions.
