### ISSUE TITLE
Way to close open file dialog

### ISSUE THREAD

**Issue by Lihasha** [aerokube/selenoid#1059]
Hi! 
Is there any way to close "open file" dialog at selenium?
my locator for input is available only after clicking at button for uploading file. I can control browser while this dialog on top, and make input by send keys, but my video and screenshots are not usefull while it's on top.
Maybe there is any possibility to send it to background or do not open at all? or close by any command at selenoid?

![image](https://user-images.githubusercontent.com/16048084/107677645-8e726080-6cab-11eb-86a6-252a5c5ecaea.png)

**Comment by vania-pooh** [comment]
@Lihasha correct approach is filling file input field without opening this dialog using sendKeys command.

**Comment by Lihasha** [comment]
@vania-pooh. I understand that.as I wrote ‘ **my locator for input is available  only after clicking at button for uploading file**. . **I can** control browser while this dialog on top, and **make input by send keys**‘

**Comment by Lihasha** [comment]
The problem is that I have no choice ‘not to open upload file’ because my locator for input appear on page only after clicking on upload. It’s not just hidden somewhere at the end of the page.

So I hoped someone could tell me if there is some setting in selenoid,or anything else.

**Comment by Lihasha** [comment]
and I can't ask developers to add duplicate input because 'it's not secure, we're ultra super security'🥲

**Comment by carl-pki** [comment]
l has same question too.@ Lihasha

**Comment by carl-pki** [comment]
> and I can't ask developers to add duplicate input because 'it's not secure, we're ultra super security'🥲

l has same question too

**Comment by carl-pki** [comment]
> and I can't ask developers to add duplicate input because 'it's not secure, we're ultra super security'🥲

Have you found a solution?

**Comment by carl-pki** [comment]
I tried to use SikuliX to close the system pop-up window but I also encountered an error：
org.sikuli.script.SikuliXception: SikuliX: Init: running in headless environment

**Comment by 1109471432** [comment]
> @Lihasha correct approach is filling file input field without opening this dialog using sendKeys command.

I has same question, too.  The input tag is only visible when the system pop-up window pops up
