### ISSUE TITLE
Run Selenoid in container from non-root user

### ISSUE THREAD

**Issue by v-byte-cpu** [aerokube/selenoid#1060]
It would be great to have [Podman](https://github.com/containers/podman) support to run rootless containers without exposing docker socket.

**Comment by vania-pooh** [comment]
@v-byte-cpu Selenoid is using Docker socket to start browser containers.

**Comment by v-byte-cpu** [comment]
@v-byte-cpu I understand it, and having access to docker socket actually means root access on host system. Adding support for podman would allow unprivileged users to run Selenoid without compromising security.

**Comment by vania-pooh** [comment]
@v-byte-cpu nothing prevents you from using `DOCKER_HOST` environment variable:

```
$ docker run -e DOCKER_HOST=tcp://<api-ip>:2375
```

**Comment by v-byte-cpu** [comment]
ok, but it will not prevent to run something like this:

```
docker run -it -v /:/mnt alpine sh
$ chroot /mnt
# now you have root access on remote host (wherever docker daemon is running)
```

**Comment by v-byte-cpu** [comment]
@vania-pooh I just noticed your commit. I believe you have misunderstood the underlying security problem. Selenoid process still need access to host docker socket. Even when the containers are running as non-root users, when the runtime is still running as the root, it is not rootless containers.

Rootless containers mean running the entire container runtime as well as the containers without the root privileges. 

Adding **rootless containers support** in Selenoid would allow **multiple unprivileged** users to run containers on the same machine in separated container runtimes.

**Comment by vania-pooh** [comment]
@v-byte-cpu in that case e.g. Chrome browser will simply not run without privileged \ CAP_SYS_ADMIN if `--no-sandbox` flag is not passed. Selenoid is using official Docker API client and thus allows to use `DOCKER_HOST=tcp://my-host:1234` variable to point to any Docker API you wish.

**Comment by v-byte-cpu** [comment]
@vania-pooh ok, got it. Apparently there is no way to run chrome browser without CAP_SYS_ADMIN at the moment.
