### ISSUE TITLE
error read browsers.json when setup selenoid from windows

### ISSUE THREAD

**Issue by Mary1210** [aerokube/selenoid#1061]
Hello,
I setup selenoid before then I deleted all images from docker and I tried to download it on powershell but I can't download it agian. I gained this error when I tried to setup it again
![errorse](https://user-images.githubusercontent.com/45977095/107873320-58ef9200-6eba-11eb-86c2-e94e81fdd101.PNG)

**Comment by vania-pooh** [comment]
@Mary1210 you downloaded **Selenoid** binary and trying to use it as CM binary. Should download CM from [here](https://github.com/aerokube/cm/releases).

**Comment by Mary1210** [comment]
it worked thanks
