### ISSUE TITLE
WebDriver protocol compatibility "Get named cookie"

### ISSUE THREAD

**Issue by cyberflohr** [aerokube/selenoid#1062]
Getting a none existing cookie returns HTTP status code 200

Expected behaviour:

According to your [OpenAPI specification](https://github.com/aerokube/selenium-openapi/blob/master/selenium.yaml)  a HTTP status code 404 should be returned for "GET /session/{sessionId}/cookie/{name}" (none existing cookie)
Selenium Grid & Standalone will return 404 in this situation.

Infrastructure:

For the test I used curl and your latest [aerokube image](https://hub.docker.com/layers/aerokube/selenoid/latest/images/sha256-bd4c2f1c67975b08d8a9491805fdefdcdd423cf4db43daefc8b933732bf9dfb6?context=explore)

create file req-new-session.json with the following content:
```
{
  "desiredCapabilities": {
    "browserName": "chrome",
    "timeouts": {
      "pageLoad": 25000
    },
    "pageLoadStrategy": "eager",
    "platformName": "ANY",
    "goog:chromeOptions": {
      "args": [
        "window-size=1920x1080",
        "no-sandbox",
        "aggressive-cache-discard",
        "disable-cache",
        "disable-application-cache",
        "disable-offline-load-stale-cache",
        "disk-cache-size=0",
        "disable-gpu",
        "dns-prefetch-disable",
        "no-proxy-server",
        "disable-browser-side-navigation"
      ],
      "extensions": []
    },
    "platform": "ANY"
  }
}
```
curl -v -DPOST --data @req-new-session.json http://localhost:4444/wd/hub/session

Use the returned session id (e.g. 6e5af4a5c3f1e457f95c63f7c05afcdf) for the next command.

curl -v http://localhost:4444/wd/hub/session/6e5af4a5c3f1e457f95c63f7c05afcdf/cookie/myname

HTTP/1.1 200 OK
```
{
  "sessionId": "6e5af4a5c3f1e457f95c63f7c05afcdf",
  "status": 62,
  "value": {
    "message": "no such cookie\n  (Session info: chrome=88.0.4324.96)\n  (Driver info: chromedriver=88.0.4324.27 (6347fe8bf1e48bd0c54d07dc55ca011cf40861c9-refs/branch-heads/4324@{#450}),platform=Linux 4.19.121-linuxkit x86_64)"
  }
}
```

**Comment by vania-pooh** [comment]
@cyberflohr our images are exposing Chromedriver directly. So this seems to be Chromedriver incompatibility with the protocol. Btw, our spec is based on W3C standard. https://www.w3.org/TR/webdriver/#errors

**Comment by cyberflohr** [comment]
@vania-pooh thanks for the chromedriver hint. I checked it and YES, it comes from the chromedriver. 

My application operates directly on the WebDriver protocol and everything worked well with Selenium Grid, but after switching to Selenoid this little glitches comes up. 

IMO selenium will do some type of filtering before returning the chromedriver result.

Anyway I must find some workaround for this issue.

**Comment by vania-pooh** [comment]
@cyberflohr we intentionally do not do any filtering for performance reasons as it requires decoding and encoding JSON on the fly which is an expensive operation.

**Comment by cyberflohr** [comment]
Finally I found the root cause why chromedriver behaved so strange. It all depends on how the session is created. If the request does not contain a "capabilities" attribute like in my case, the session is non W3C compliant (old chrome driver protocol).

Using a request with "desiredCapabilities" and "capabilities" chromedriver will switch to W3C compliant mode.
Like in my case with the "Get cookie by name" will return HTTP 404 if the cookie is not found.

Now I can finally try out Selenoid :-)
 
```
{
  "desiredCapabilities": {
    "browserName": "chrome",
    "pageLoadStrategy": "normal",
    "platformName": "ANY",
    "goog:chromeOptions": {
      "args": [
        "window-size=1920x1080"
      ],
      "extensions": [
      ]
    },
    "platform": "ANY"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "args": [
            "window-size=1920x1080"
          ],
          "extensions": [
          ]
        },
        "pageLoadStrategy": "normal"
      }
    ]
  }
}
```
