### ISSUE TITLE
Add Selenium-like websocket endpoint for CDP proxy

### ISSUE THREAD

**Issue by L0tso** [aerokube/selenoid#1063]
Starting from 4.06a Selenium supports CDP proxy and allows connecting websocket to `ws://hub:port/session/${sessionId}/se/cdp`. 
It would be great to have the same interface for Selenoid in addition/instead of existed `ws://selenoid.example.com:4444/devtools/<session-id>/<method>`. The unified interface simplifies writing client libraries.

**Comment by vania-pooh** [comment]
@L0tso client libraries usually have `ws://` URL as constructor parameter. Don't get how renaming our API would simplify things.

**Comment by L0tso** [comment]
@vania-pooh Not all client libraries ready to give full control for client. Libraries which use default Selenium 4 endpoint, will automatically work with Selenoid. These issues based on this issue https://github.com/webdriverio/webdriverio/issues/6470

**Comment by link89** [comment]
Actually the way `webdriverio` use is not reliable. `selenoid` doesn't provide a way for the client to know it is using `selenoid` or other tools. IMHO it would be better for `selenoid` to declare those extra endpoints in the session create response, for example:

```json
{
  "browserName": "chrome",
  ...
  "selenoid:endpoints": {
    "cdp": "ws://selenoid.example.com:4444/devtools/<session-id>/",
    "vnc": "ws://selenoid.example.com:4444/vnc/<session-id>/",
     "download": "http://selenoid.example.com:4444/download/<session-id>/"
  }
}
```
So that the client can just check the response to know what resource it can use instead of guessing.

**Comment by vania-pooh** [comment]
@link89 you can't pass `session_id` in capabilities because it only known when session is created.

**Comment by link89** [comment]
@vania-pooh session-id is already in the response of session create request. I guess you were confused with the request.

**Comment by link89** [comment]
And back to the original question, I don't think it need to change the url of cdp, but just add `"se:cdp": "ws://selenoid.example.com:4444/devtools/f3cb3a08eb481980ed0b53cd446e6b84/"` to the response, that's enough.

**Comment by vania-pooh** [comment]
Let's do this.
