### ISSUE TITLE
Enable only authorised access to Selenoid

### ISSUE THREAD

**Issue by ohld** [aerokube/selenoid#1067]
Hey 👋

I just installed Selenoid on DigitalOcean from its marketplace. Everything works fine but I couldn't find the way how to add any authentication to Selenoid service.

Now everyone who knows the IP address of my deployed droplet can access Selenoid but I want to have at least simple http auth to restrict access. I couldn't find anything regard this question in documentation. Anyone can help?

**Comment by vania-pooh** [comment]
@ohld http://aerokube.com/selenoid-ui/latest/#_restricting_access

**Comment by ohld** [comment]
@vania-pooh Thanks for the links. But it is soo strange that Selenoid doesn't have any build-it authentication. Someone can sniff :4444 ports across all IPv4 addresses and find out some unhidden Selenoids. 

Will this feature be implemented soon? Is it in Selenoid roadmap? I believe this is an important security issue.

**Comment by vania-pooh** [comment]
@ohld no, this is not in our roadmap. We try to not overcomplicate things. If you need authentication - you can e.g. install Nginx in reverse proxy mode with basic authentication enabled.

**Comment by ohld** [comment]
Isn't it a security issue?

**Comment by vania-pooh** [comment]
@ohld no, using Nginx ahead of application server is a common practice.
