### ISSUE TITLE
Chrome renames files to download without any file format

### ISSUE THREAD

**Issue by kovacsdongo** [aerokube/selenoid#1068]
Hello
I found a problem. When i download a file with selenium on local the filename is good "Épület.pdf" but when i run on selenoid, the dowloaded file's name change to "download"
So it is renamed and the extension disappear.
I use chrome 86
Are there any solution for this problem?
Thanks is advance

**Comment by kovacsdongo** [comment]
@vania-pooh sorry, I made upt:
I download with:
Click Element                       locator
after that just simple check the file:
File Should Exist               ${OUTPUT_DIR}${/}downloads${/}${filename}

**Comment by vania-pooh** [comment]
@kovacsdongo are you doing HTTP requests like this to download the file from container to the directory where test is actually running?
```
http://example.com:4444/download/<session-id>/filename.txt
```

**Comment by kovacsdongo** [comment]
dear @vania-pooh 
Yes I use http request, but the rename is happen before download, so the downloaded file have already renamed

attached a screen shoot from selenoid:
![image](https://user-images.githubusercontent.com/30658352/110089756-c3e40880-7d96-11eb-8f7d-4417c2317b0e.png)

and the same test in local: you see the downloaded pdf's name: Épület riport.pdf
![image](https://user-images.githubusercontent.com/30658352/110090104-3228cb00-7d97-11eb-904e-012d2a0befa2.png)

**Comment by mitrofanov-in** [comment]
We have the same problem.

Please tell me is there a solution?

**Comment by vania-pooh** [comment]
@mitrofanov-in probably you have to set correct locale using LANG environment variable.

**Comment by mitrofanov-in** [comment]
@vania-pooh  thank you.
This solves the problem in our case.
