### ISSUE TITLE
How to prevent popping-up xdg-open dialog from Ubuntu chrome while opening specific link?

### ISSUE THREAD

**Issue by dadi680** [aerokube/selenoid#1069]
Is there a way to dismiss the dialogue using python selenium or using some configuration file changes in chrome installation ?
![1](https://user-images.githubusercontent.com/34637139/109891731-8e6eea80-7cc4-11eb-89d6-3cc0c071dce0.png)

**Comment by vania-pooh** [comment]
So far as I know you need to add missing schema to xdg config.

**Comment by cjmme** [comment]
Hi @vania-pooh I am using the chrome image which create by Selenoid, could I know how to add the missing schema?

**Comment by vania-pooh** [comment]
@cjmme should use `xdg-mime` command so far as I know.
