### ISSUE TITLE
Safari service start up failed

### ISSUE THREAD

**Issue by jacorgaz** [aerokube/selenoid#1070]
Morning,

When running tests against Safari I encountered the following error after following https://aandryashin.medium.com/selenium-an-apple-story-ab0c0b68cd35:
**
> 2021/03/08 12:54:22 [0] [LOCATING_SERVICE] [safari-latest]
> 2021/03/08 12:54:22 [0] [USING_DRIVER] [safari-latest]
> 2021/03/08 12:54:22 [0] [ALLOCATING_PORT]
> 2021/03/08 12:54:22 [0] [ALLOCATED_PORT] [58275]
> 2021/03/08 12:54:22 [0] [STARTING_PROCESS] [[/usr/bin/safaridriver --whitelisted-ips= --port=58275]]
> 2021/03/08 12:54:52 [0] [TERMINATING_PROCESS] [4570]
> 2021/03/08 12:54:52 [0] [TERMINATED_PROCESS] [4570]
> 2021/03/08 12:54:52 [0] [SERVICE_STARTUP_FAILED] [unknown] [http://127.0.0.1:58275 does not respond in 30s
**

The json I am using are either one of these two:

### {
    "safari": {
        "default": "14.0.3",
        "versions": {
            "14.0.3": {
                    "image": ["/usr/bin/safaridriver", "--whitelisted-ips="]
            }
        }
    }
}

### {
    "safari": {
        "default": "latest",
        "versions": {
            "latest": {
                    "image": ["/usr/bin/safaridriver", "--whitelisted-ips="]
            }
        }
    }
}

Machine selenoid runs as process : Big Sur 
Selenoid version: 1.9.3

**Comment by vania-pooh** [comment]
@jacorgaz add `-capture-driver-logs` flag to Selenoid and you will see driver output in the same log.

**Comment by jacorgaz** [comment]
@vania-pooh changed as you mentioned but still facing the same problem. 
### Log:

2021/03/08 13:33:23 [-] [INIT] [Loading configuration files...]
2021/03/08 13:33:23 [-] [INIT] [Loaded configuration from /Users/qa/browsers.json]
2021/03/08 13:33:23 [-] [INIT] [Timezone: Local]
2021/03/08 13:33:23 [-] [INIT] [Listening on :4444]
2021/03/08 13:33:31 [-] [NEW_REQUEST] [unknown] [10.1.101.21]
2021/03/08 13:33:31 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.1.101.21]
2021/03/08 13:33:31 [0] [LOCATING_SERVICE] [safari] [latest]
2021/03/08 13:33:31 [0] [USING_DRIVER] [safari] [latest]
2021/03/08 13:33:31 [0] [ALLOCATING_PORT]
2021/03/08 13:33:31 [0] [ALLOCATED_PORT] [61801]
2021/03/08 13:33:31 [0] [STARTING_PROCESS] [[/usr/bin/safaridriver --whitelisted-ips= --port=61801]]
safaridriver: unrecognized option `--whitelisted-ips='
Usage: safaridriver [options]
	-h, --help                Prints out this usage information.
	--version                 Prints out version information and exits.
	-p, --port                Port number the driver should use. If the server
	                          is already running, the port cannot be changed.
	                          If port 0 is specified, a default port will be used.
	--enable                  Applies configuration changes so that subsequent WebDriver
	                          sessions will run without further authentication.
	--diagnose                Causes safaridriver to log diagnostic information for
	                          all sessions hosted by this instance. See the safaridriver(1)
	                          man page for more details about diagnostic logging.
2021/03/08 13:34:01 [0] [TERMINATING_PROCESS] [4667]
2021/03/08 13:34:01 [0] [TERMINATED_PROCESS] [4667] [0.00s]
2021/03/08 13:34:01 [0] [SERVICE_STARTUP_FAILED] [http://127.0.0.1:61801 does not respond in 30s]

**Comment by aandryashin** [comment]
Safari driver does not have --whitelist-ips option, please remove it.

пн, 8 мар. 2021 г., 15:40 Javier Corroto <notifications@github.com>:

**Comment by jacorgaz** [comment]
Hi @aandryashin , after removing it I got:

### org.openqa.selenium.InvalidArgumentException: 'Host' header or 'Origin' header is specified and is not localhost.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'MacBook-Pro', ip: '***.***.1.113', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 14.0.3, javascriptEnabled: true, platform: MAC, platformName: MAC, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, safari:platformBuildVersion: 20D80, safari:platformVersion: 11.2.2, safari:useSimulator: false, setWindowRect: true, strictFileInteractability: false, webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}}

**Comment by aandryashin** [comment]
Looks like Apple restricts non local safari usage in newer versions of
safaridriver, please ask Apple support team if it is possible.

пн, 8 мар. 2021 г., 23:21 Javier Corroto <notifications@github.com>:

**Comment by aandryashin** [comment]
Also there is linux build of webkit with webdriver you can try it instead:

docker pull browsers/safari:13.0

пн, 8 мар. 2021 г., 23:21 Javier Corroto <notifications@github.com>:

**Comment by aandryashin** [comment]
You can use it with selenoid.

вт, 9 мар. 2021 г., 00:00 Alexander Andryashin <aandryashin@gmail.com>:

**Comment by jacorgaz** [comment]
@aandryashin I´ll try to contact them Apple as you mentioned. I got working the webkit solution.

Thank you for your help :)
