### ISSUE TITLE
[Question] - Selenoid container access to application running on localhost:port

### ISSUE THREAD

**Issue by GSasu** [aerokube/selenoid#1075]
Hey all,

I'm working on an application that is currently being developed. I am using selenoid and have been using it successfully for the past few years. Now however I've hit an issue I don't know (or understand) how to precisely fix.
The application under test is an angluar app that after being built is being served on http://localhost:port/ - it is not a container.
How can I have selenoid able to talk to the host machine localhost:port (I.e: `http://localhost:4502`) to have the tests running there?

I've tried the following so far:
 - setting `host.docker.internal` to my machine's local IP address
   - I tried setting this on the `docker run` command using `--add-host` with value `example.com:localIp`
   - I tried setting this on the `hostsEntries` using same approach `example.com:localIp`
   - I tried setting this on the `browsers.json` chrome object like this:
 ```
    "chrome": {
        "default": "87.0",
        "versions": {
            "87.0": {
                "image": "selenoid/vnc:chrome_87.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {"/tmp":"size=2048m"},
                "volumes": ["/dev/shm:/dev/shm"],
                "hosts": [
                    "example.com:localIpAddress"
                ],
                "mem": "2048m",
                "cpu": "2.0"
            }
        }
    }
```
   - I tried setting all of the above together as well
   - Additionally I also tried all of the above but rather than using my localIpAddress I use the container Ip (Both selenoid IP and browser container IP)
   - Moreover I tried adding this to the `environment` flag `XDEBUG_CONFIG: client_host=host.docker.internal`
   - Also tried `DOCKER_HOST=tcp://my-host:1234`

In terms of the baseURL to use for the tests I tried with my IP, key used in hosts, container IP.

I am out of ideas. What am I missing and doing wrong?

Anticipated thanks, I really appreciate any help on this.
I am aware that this was asked in the past and tried the solutions there as well without luck.
Firewall is not blocking the connection so the only option left in my head is me being stupid and not realizing what I'm doing wrong.

As additional info I don't know if it's relevant
- I am using CodeceptJS
- To automatically spin up the containers I'm using WebDriverIO Docker Service

Docker service setup:
```
dockerOptions: {
        image: 'aerokube/selenoid:1.10.0',
        healthCheck: {
            url: 'http://localhost:4454',
            maxRetries: 5,
            inspectInterval: 3000,
            startDelay: 3000,
        },
        options: {
            name: 'selenoid',
            e: [
                'OVERRIDE_VIDEO_OUTPUT_DIR=`pwd`/output/video/',
            ],
            p: [
                '4454:4444',
            ],
            v: [
                `${_ROOT_DIR}`,
                `${_ROOT_DIR}/docker:/etc/selenoid/`,
                '/var/run/docker.sock:/var/run/docker.sock',
                `${_ROOT_DIR}/docker/video:/opt/selenoid/video`,
                `${_ROOT_DIR}/data/`,
            ],
            addHost: [
                'example.com:localIpAddress',
                'ad.doubleclick.net:127.0.0.1',
                'doubleclick.net:127.0.0.1',
                'track.strikead.com:127.0.0.1',
                'js-agent.newrelic.com:127.0.0.1',
                'adservice.google.com:127.0.0.1',
                'googleadservices.com:127.0.0.1',
                'uip.semasio.net:127.0.0.1',
                'sp.analytics.yahoo.com:127.0.0.1',
            ],
        },
    },
```

browsers.json
```
{
    "firefox": {
        "default": "83.0",
        "versions": {
            "83.0": {
                "image": "selenoid/vnc:firefox_83.0",
                "port": "4444",
                "path": "/wd/hub",
                "volumes": ["/dev/shm:/dev/shm"],
                "tmpfs": {"/tmp":"size=4096m"},
                "mem": "4096m",
                "cpu": "2.0",
                "shmSize": 1073741824
            }
        }
    },
    "chrome": {
        "default": "87.0",
        "versions": {
            "87.0": {
                "image": "selenoid/vnc:chrome_87.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {"/tmp":"size=2048m"},
                "volumes": ["/dev/shm:/dev/shm"],
                "hosts": [
                    "example.com:localIPAddress"
                ],
                "mem": "2048m",
                "cpu": "2.0"
            }
        }
    }
}
```

selenoidOptions json
```   
selenoidOptions: {
        enableVNC: true,
        enableLog: true,
        logName: 'session-log.log',
        sessionTimeout: '10m',
        hostsEntries: [
            'example.com:localIPAddress',
       ],
}
```

**Comment by vania-pooh** [comment]
@GSasu 
No Selenoid config modification is needed.
1) Under Linux use IP address of `docker0` network interface (see `ifconfig` output).
2) Under Mac something like `docker.for.mac.localhost`.
3) Under Windows something like `docker.for.win.localhost`.

**Comment by GSasu** [comment]
Hey @vania-pooh, thank you kindly for the quick reply.
I apologize in advance for this silly question but:
- Where would I pass in the `docker0` or `docker.for.mac.localhost`?
- What do I need to set into the docker image to have this running?

I am asking this because I tried so many things I don't understand anymore what do I have to set and where.

Thank you in advance for this

**Comment by vania-pooh** [comment]
@GSasu just use this value as host, e.g. `http://docker.for.mac.localhost:8080/some/path`.

**Comment by GSasu** [comment]
Thank you for this.

I tried with `docker.for.mac.localhost` and I'm getting `site can't be reached` - `refused to connect`
I tried `host.docker.internal` as well as `docker.for.mac.host.internal` and using this I'm getting `Invalid Host header`

I'm assuming at this point it's on me to investigate but I still wanted to post this question in case you have any ideas.

Much appreciated, thank you

**Comment by GSasu** [comment]
Nevermind the problem is definitely on the app running and having incorrect setup. I'll fix this on my end and will return if after that it still doesn't work. It's an Angluar app issue

**Comment by GSasu** [comment]
Done, fixed, thank you kindly for all your help and answers. The issue was on how the application was running locally. It required an extra flag to allow connections incoming from containers.
For an angluar app, using `--disableHostCheck` allowed the containers to connect to the local env.
