### ISSUE TITLE
Chrome & FF options not working in version 1.10.2

### ISSUE THREAD

**Issue by dtuchs** [aerokube/selenoid#1077]
Chrome caps:
```
ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("enableVNC", true);
        chromeOptions.setCapability("screenResolution", 1440 + "x" + 900 + "x24");
        chromeOptions.addArguments("user-agent=" + CUSTOM_UA)
```
FF caps:
```
        FirefoxOptions firefoxOptions = new FirefoxOptions().addPreference("general.useragent.override", CUSTOM_UA);
        firefoxOptions.setCapability("enableVNC", true);
```

test (both for chrome / ff. Selenide 5.18.1):
```
WebDriverRunner.setWebDriver(new RemoteWebDriver(new URL({SELENOID_URL}), firefoxOptions / chromeOptions));
        Selenide.open("ya.ru");
        assertThat((String) Selenide.executeJavaScript("return navigator.userAgent")).isEqualTo(CUSTOM_UA);
```
for selenoid 1.10.1 this test passed, but for 1.10.2 - failed

checked with browsers, result is same
selenoid/vnc:chrome_88.0
selenoid/vnc:chrome_89.0
selenoid/vnc:firefox_86.0
selenoid/vnc:firefox:77.0

**Comment by vania-pooh** [comment]
All non standard capabilities are being removed by Selenoid.

**Comment by benzman81** [comment]
same here, all of the sudden a lot of our tests start failing :-/ 

@vania-pooh since this is considered a bug, do I guess correctly that all capabilities will work as before after this gets fixed?

**Comment by vania-pooh** [comment]
@benzman81 correct. For now you can simply downgrade to 1.10.1.

**Comment by benzman81** [comment]
same issue for edge

**Comment by StanislavKharchenko** [comment]
Faced today on chrome and edge after upgrade to 1.10.2
[09:29:15] E/launcher - Error: InvalidArgumentError: invalid argument: 'firstMatch' must be a JSON list

Downgrade to 1.10.1 works for now

@vania-pooh What do you mean "non-standard capabilities" ?
This issue is a bug or we need to enhance capabilities for success run on 1.10.2?

**Comment by vania-pooh** [comment]
@StanislavKharchenko this is a bug and it's clearly marked.
