### ISSUE TITLE
Selenoid/chromedriver displays insecure connection while in https

### ISSUE THREAD

**Issue by StanislavKharchenko** [aerokube/selenoid#1080]
Good day!
Trying to resolve the issue appeared while using Selenoid.
I've connected to UI using selenoid-ui and see that by uknknown reason chromedriver displays page as insecure, however page opened with https protocol.
There are no such issue if application opened manually or using selenium-grid, but only on chromedriver under selenoid.
Is it possible to resolve this?

![image](https://user-images.githubusercontent.com/19797017/113331353-88524500-9328-11eb-960f-cd43f1ab3047.png)

Thank you!

**Comment by aandryashin** [comment]
Hello!

You can provide browser with your CA certificate, please check this:
https://aerokube.com/images/latest/#_adding_custom_root_certification_authority

чт, 1 апр. 2021 г. в 20:29, StanislavKharchenko ***@***.***>:

**Comment by vania-pooh** [comment]
@StanislavKharchenko this is because Selenoid containers are always clean, i.e. only contain a usual set of CA certificates being present. In case of using self-signed root CA, you have to add configure adding them manually as shown above.

**Comment by StanislavKharchenko** [comment]
@vania-pooh Thanks.
Can we also add some configuration for containers to use corporate proxy server?
I'm starting selenoid instance using cm script and setting env variables HTTP_PROXY, HTTPS_PROXY as described in doc:

![image](https://user-images.githubusercontent.com/19797017/114394920-708a8480-9ba4-11eb-972f-3b93cab3cdfe.png)

But on opened browser session I can't reach to external resources (like google.com)

**Comment by StanislavKharchenko** [comment]
Found that env variable should be directly set for needed browser image.
Closing this issue.

**Comment by miki676** [comment]
Good day!
I 've encountered nearly the same issue but mine is https,  - Checking your browser before accessing (url).
The point is it's the normal check which are encounter everytime in my any browser and after 5 seoncds (countdown goes to 0) I enter into my url. 
Unfortuntely,  none of the selenoid browser pass the check, the countdown remain5 seconds and after a while the selenoid driver closes.

> Good day!
> Trying to resolve the issue appeared while using Selenoid.
> I've connected to UI using selenoid-ui and see that by uknknown reason chromedriver displays page as insecure, however page opened with https protocol.
> There are no such issue if application opened manually or using selenium-grid, but only on chromedriver under selenoid.
> Is it possible to resolve this?
> 
> ![image](https://user-images.githubusercontent.com/19797017/113331353-88524500-9328-11eb-960f-cd43f1ab3047.png)
> 
> Thank you!

Hello.
Did you solve your problem, if yes could you please share how did you do that with step by step?
I am new on dockers. My issue is nearly the same but my connection is secure. I would like to test your solution.
I appreciate your help.
Kind Regards.
P.S. - my issue - https://github.com/aerokube/selenoid/issues/1093
