### ISSUE TITLE
Getting chrome logs from selenoid

### ISSUE THREAD

**Issue by kornel-filep** [aerokube/selenoid#1082]
Hi all!

I need some help with browser log gathering.

I know about the VERBOSE env variable that we can pass, and we get the webdriver logs in the selenoid logs.
What I would like to have are the browser debug logs of chrome, like described here: https://superuser.com/questions/1286937/how-can-i-find-my-browser-web-log-file
What essentially needs to be done, is to pass chrome in command line '--enable-logging --v=1', and it will create a logfile.

This logfile provides more info about the browser, than the --verbose flag of the webdriver flag does.

Any ideas how this could be done?
Maybe this is simple, I am just overlooking something.
Do you need any additional info about this question?

Thank you in advance for replying to this thread!

**Comment by vania-pooh** [comment]
@kornel-filep e.g.:
```
LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.BROWSER, Level.ALL);
logPrefs.enable(LogType.PERFORMANCE, Level.INFO);
caps.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);

LogEntries logEntries = driver.manage().logs().get(LogType.BROWSER);
logEntries.getAll().stream().forEach(
    le -> System.out.printf("%s %s", le.getLevel(), le.getMessage())
);


```

**Comment by kornel-filep** [comment]
Thanks @vania-pooh, but this does not seem to output anything for me😔. Maybe I am just doing something wrong.

Btw, I managed to find the browser debug logs that I need inside the container created by Selenoid.
It basically contains what I need, really detailed logs about what happens with the browser.
![Screenshot 2021-04-08 at 16 39 41](https://user-images.githubusercontent.com/28757957/114046295-06629e80-9889-11eb-9856-b0665dd8dc91.png)

Is there an easy way that I could grab the contents of this logfile out of a container created by selenoid?

**Comment by vania-pooh** [comment]
@kornel-filep no, debug logs are only accessible from the file system. Probably you could modify browser image and create a symling from `/tmp` to `/home/selenium/Downloads` and then use this feature: https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser

**Comment by kornel-filep** [comment]
@vania-pooh perfection.
Adding `RUN ln -sf /tmp /home/selenium/Downloads` to the dockerfile works like magic. 

As my question is answered, closing this comment. Thanks for the help!

**Comment by kornel-filep** [comment]
@vania-pooh Found an easier solution.
Checked out it for chrome. If setting the CHROME_LOG_FILE environment variable to /home/selenium/Downloads you can grab it through the downloads API. Or even better, if setting the env variable to /dev/stdout you will get the logs automatically saved by Selenoid.
