### ISSUE TITLE
parse error: invalid character 'ï' looking for beginning of value]

### ISSUE THREAD

**Issue by evalalos** [aerokube/selenoid#1083]
Hi, sorry if this was already asked, tried to find the answer but nothing.
I'm getting this error when trying to start selenoid through the sh script - macOS big sur.

2021/04/08 12:37:54 [-] [INIT] [Loading configuration files...]

2021/04/08 12:37:54 [-] [INIT] [/usr/bin/selenoid: browsers config: parse error: invalid character 'ï' looking for beginning of value]

Here is the browsers.json file, please unzip it before opening:

[browsers.json.zip](https://github.com/aerokube/selenoid/files/6278011/browsers.json.zip)

Any help?

Please feel free to ask for more info if needed.

Thanks in advance!

**Comment by vania-pooh** [comment]
@evalalos your file seems to be valid. I think you are mounting volumes incorrectly.

**Comment by evalalos** [comment]
@vania-pooh ok, I will double check mounts. Thanks

**Comment by evalalos** [comment]
@vania-pooh should I add something like this _**"volumes": ["/home/selenium/Downloads:/opt/docker/fileDownloadLocation"]**_ into browsers.json? I don't have this parameter.

Attaching the mounts section under docker desktop for selenoid.

<img width="1051" alt="selenoid" src="https://user-images.githubusercontent.com/47383413/114018077-22f0dd80-986d-11eb-9d03-c1ad56c0dc6b.png">

**Comment by evalalos** [comment]
@vania-pooh yes, adding "volumes": ["/opt/docker/fileDownloadLocation:/home/selenium/Downloads"] solved my problem.
