### ISSUE TITLE
Getting an error message, Duplicate mount point: /tmp, when mounting to the tmp folder inside the container

### ISSUE THREAD

**Issue by dizhar** [aerokube/selenoid#1084]
**Problem:** 
Cannot mount to the tmp folder inside the container. 

**Steps:**
1. setup the volumes  for the container in the browser.json file
2. Run the container with the same browserName and browserVersion 

**Getting error message:**
[SERVICE_STARTUP_FAILED] [create container: Error response from daemon: Duplicate mount point: /tmp]

My browser.json is as follows:

{
"chrome": {
        "default": "88.0",
        "versions": {
        "88.0": {
                "image": "selenoid/vnc:chrome_88.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {"/tmp": "size=512m", "/var": "size=128m"},
                "volumes" :["temporary:/tmp"],
                "shmSize": 268435456
            }
        }
    },
}

**Comment by vania-pooh** [comment]
@dizhar error message is self-explaining. In `tmpfs` you trying to mount `/tmp` into memory. In `volumes` you are trying to mount the same `/tmp` to disk volume. This is ambiguous for Docker what to do. Simply remove one of them.

**Comment by dizhar** [comment]
I understand thank you. I am closing the issue
