### ISSUE TITLE
Can't retrieve the browser logs file from the mounted folder inside the container.    

### ISSUE THREAD

**Issue by dizhar** [aerokube/selenoid#1085]
**Problem:**
Can't retrieve the browser logs file from the mounted folder inside the container.    The folder is always empty. 

**Steps:**
1. make a To  directory in the host  root of the host machine
2. Steps up browser capabilities
3. setup up browser.json file 
4. Run test

**Actual**
 Go inside the container view the From directory is empty. 

Browser capabilities
{
  "browserName": "chrome",
  "browserVersion": "88.0",
  "goog:chromeOptions": {
    "args": [
      "--log-file=./from/example.log",
      "--log-level=2",
Safari/537.36"
    ]
  },
  "selenoid:options": {
    "enableVNC": true,
    "enableVideo": false,
    "screenResolution": "1280x1024x24"
  },
  "acceptInsecureCerts": true
}

Browser.json File
{
"chrome": {
        "default": "88.0",
        "versions": {
        "88.0": {
                "image": "selenoid/vnc:chrome_88.0",
                "port": "4444",
                "path": "/",
                "volumes": ["/to:/from"], 
                "shmSize": 268435456
            }
        }
    },
}

**Comment by vania-pooh** [comment]
Related issue: https://github.com/aerokube/selenoid/issues/1082
