### ISSUE TITLE
1.10.3 - Random session closure during test execution

### ISSUE THREAD

**Issue by DmitryGalych** [aerokube/selenoid#1086]
We faced with random session closure during test execution on selenoid 1.10.3.
There is no such problem on the 1.10.0/1.10.1
Default timeout we use - 5 minutes.

` 2021/04/09 08:12:58 [-] [INIT] [Loading configuration files...]
 2021/04/09 08:12:58 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
 2021/04/09 08:12:58 [-] [INIT] [Video Dir: /opt/selenoid/video]
 2021/04/09 08:12:58 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
 2021/04/09 08:12:58 [-] [INIT] [Using Docker API version: 1.41]
 2021/04/09 08:12:58 [-] [INIT] [Timezone: UTC]
 2021/04/09 08:12:58 [-] [INIT] [Listening on :4444]
 2021/04/09 08:13:34 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
 2021/04/09 08:13:34 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
 2021/04/09 08:13:34 [0] [LOCATING_SERVICE] [chrome] []
 2021/04/09 08:13:34 [-] [DEFAULT_VERSION] [Using default version: 89.0]
 2021/04/09 08:13:34 [0] [USING_DOCKER] [chrome] [89.0]
 2021/04/09 08:13:34 [0] [CREATING_CONTAINER] [selenoid/chrome:89.0]
 2021/04/09 08:13:34 [0] [STARTING_CONTAINER] [selenoid/chrome:89.0] [49db71997744cd92daa2350580ec4bf581cddb2a62232b586f826d10d27ce075]
 2021/04/09 08:13:35 [0] [CONTAINER_STARTED] [selenoid/chrome:89.0] [49db71997744cd92daa2350580ec4bf581cddb2a62232b586f826d10d27ce075] [0.66s]
 2021/04/09 08:13:36 [0] [SERVICE_STARTED] [selenoid/chrome:89.0] [49db71997744cd92daa2350580ec4bf581cddb2a62232b586f826d10d27ce075] [0.51s]
 2021/04/09 08:13:36 [0] [PROXY_TO] [49db71997744cd92daa2350580ec4bf581cddb2a62232b586f826d10d27ce075] [http://172.18.0.4:4444/]
 2021/04/09 08:13:36 [0] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/] [1]
 2021/04/09 08:13:36 [0] [SESSION_CREATED] [3e829de6c4a61928b6941476b9394204] [1] [1.69s]
 2021/04/09 08:15:27 [1043] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:15:30 [1044] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:15:30 [1047] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit.xls]
 2021/04/09 08:16:38 [1637] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:16:38 [1640] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit (1).xls]
 2021/04/09 08:18:28 [2284] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:18:28 [2287] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit (2).xls]
 2021/04/09 08:19:46 [2884] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:19:46 [2887] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit (3).xls]
 2021/04/09 08:21:34 [3468] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:21:34 [3471] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit (4).xls]
 2021/04/09 08:22:42 [4062] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:22:42 [4065] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit (5).xls]
 2021/04/09 08:24:17 [4646] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/]
 2021/04/09 08:24:17 [4649] [DOWNLOADING_FILE] [3e829de6c4a61928b6941476b9394204] [/_c_tpl_s_Edit (6).xls]
 2021/04/09 08:25:24 [1042] [SESSION_TIMED_OUT] [3e829de6c4a61928b6941476b9394204]
 2021/04/09 08:25:24 [5172] [SESSION_DELETED] [3e829de6c4a61928b6941476b9394204]`

**Comment by andytrofimov** [comment]
I'm facing the same issue on 1.10.4

**Comment by vania-pooh** [comment]
This was fixed in 1.10.5.
