### ISSUE TITLE
Change User Agent in safari browser image

### ISSUE THREAD

**Issue by dibyaranjan-pg** [aerokube/selenoid#1089]
Hi, am using safari browser image which is built by selenoid team to test our application. Not able to figure out how to set custom user-agent. Please help.

**Comment by vania-pooh** [comment]
@dibyaranjan-pg we are currently investigating this question. A short answer is that it can be set with `--user-agent` flag, however not sure where respective webdriver supports passing flags to browser.

**Comment by dibyaranjan-pg** [comment]
@vania-pooh thanks for the response.. I tried as capability it seems, it does not honour.. will try to set this using `SafariOption` I am not sure if it is passing this to browser as well, will try that and post it here.

**Comment by dsoprea** [comment]
Bump. Please clarify how to set user-agent.

**Comment by vania-pooh** [comment]
@dsoprea according to [source code](https://github.com/WebKit/WebKit/blob/main/Source/WebDriver/Capabilities.h#L80) should be set using `browserArguments` capability.

**Comment by alex-harmaza** [comment]
Hi, I have the same problem with user-agent option for safari browser image. Is there a solution now to change the option and run browser session with updated user-agent value?
