### ISSUE TITLE
SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0

### ISSUE THREAD

**Issue by GiriReddy10** [aerokube/selenoid#1090]
I have referred to this link below and few other issues before raising this issue.
https://github.com/aerokube/selenoid/issues/456

The issue I am having is an intermittent issue. I run the same docker setup with selenoid in multiple pipeline steps of buildkite and run respective tests in those buildkite pipeline steps.

Some of these pipeline steps run through without any issues but some fail with above mentioned error.

I also perform docker pull selenoid/vnc_chrome:86.0 before getting the containers up. 

Here are the logs:

Logs during Setup : 

Set up the environment | 46s
-- | --
  | latest-release: Pulling from selenoid/video-recorder
  | 89d9c30c1d48: Pull complete
  | cf624a2c1c08: Pull complete
  | 9e41a5b73974: Pull complete
  | 25c489f5925e: Pull complete
  | Digest: sha256:7c8804c5567bb24e76e952bc752c911105a3cccc9003c85dceed1bc3cad99b34
  | Status: Downloaded newer image for selenoid/video-recorder:latest-release
  | docker.io/selenoid/video-recorder:latest-release
  | 86.0: Pulling from selenoid/vnc_chrome
  | 7595c8c21622: Pull complete
  | d13af8ca898f: Pull complete
  | 70799171ddba: Pull complete
  | b6c12202c5ef: Pull complete
  | f379101a4bec: Pull complete
  | 0737f1313e86: Pull complete
  | 0a73680ce893: Pull complete
  | 5671c717bacd: Pull complete
  | a28729393224: Pull complete
  | 4dfbc92ae15e: Pull complete
  | ba7dfb858f4e: Pull complete
  | c0d67d33151f: Pull complete
  | a9c51f8ff3e6: Pull complete
  | eb78b135fafc: Pull complete
  | fe3bff0c25ab: Pull complete
  | 72c806d50fdc: Pull complete
  | Digest: sha256:2ce176b9d950ccf240708ee9c7dbf7cf297d0cfec9bef0b24e54aeeaec48b9be
  | Status: Downloaded newer image for selenoid/vnc_chrome:86.0
  | docker.io/selenoid/vnc_chrome:86.0

Selenoid container logs: 

Attaching to end-to-end_selenoid_1
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Loading configuration files...]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Video Dir: /opt/selenoid/video]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Saving all logs]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Your Docker API version is 1.40]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Timezone: UTC]
selenoid_1         | 2021/04/16 01:48:58 [-] [INIT] [Listening on :4444]
selenoid_1         | 2021/04/16 01:50:49 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:49 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:49 [0] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:49 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:49 [0] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:49 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:49 [0] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:51 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:51 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:51 [1] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:51 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:51 [1] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:51 [1] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:51 [1] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:52 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:52 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:52 [2] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:52 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:52 [2] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:52 [2] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:52 [2] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:53 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:53 [3] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:53 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:53 [3] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:53 [3] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:53 [3] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:53 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:53 [4] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:53 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:53 [4] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:53 [4] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:53 [4] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:53 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:53 [5] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:53 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:53 [5] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:53 [5] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:53 [5] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:54 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:54 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:54 [6] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:54 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:54 [6] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:54 [6] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:54 [6] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:54 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:54 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:54 [7] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:54 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:54 [7] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:54 [7] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:54 [7] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:54 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:54 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:54 [8] [LOCATING_SERVICE] [chrome] []
selenoid_1         | 2021/04/16 01:50:54 [-] [DEFAULT_VERSION] [Using default version: 86.0]
selenoid_1         | 2021/04/16 01:50:54 [8] [USING_DOCKER] [chrome] [86.0]
selenoid_1         | 2021/04/16 01:50:54 [8] [CREATING_CONTAINER] [selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:54 [8] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc:chrome_86.0]
selenoid_1         | 2021/04/16 01:50:55 [-] [NEW_REQUEST] [unknown] [172.27.0.6]
selenoid_1         | 2021/04/16 01:50:55 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.27.0.6]

My Docker compose file :

version: "3"
networks:
  selenoid:
    external:
      name: selenoid
services:
  e2e-test-runner:
    networks:
      selenoid: null
    depends_on:
      - selenoid
      - nginx-proxy
    image: abcddfdfdfdfgf
    working_dir: /app
    environment:
      - GRADLE_USER_HOME=/.gradle
      - BUILD_CACHE_URL
      - GRADLE_BUILD_CACHE_USERNAME
      - GRADLE_BUILD_CACHE_PASSWORD
      - CHROME_PROFILE_DIR=/tmp/chrome_profile
      - SEL_JUP_SELENIUM_SERVER_URL=http://selenoid:4444/wd/hub/
    volumes:
      - ./../:/app:delegated
      - /tmp/gradle-cache:/.gradle:delegated
      - /var/run/docker.sock:/var/run/docker.sock
  selenoid:
    networks:
      selenoid: null
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD/end-to-end/selenoid:/etc/selenoid:delegated"
      - "$PWD/end-to-end/build/reports/video:/opt/selenoid/video:delegated"
      - "$PWD/end-to-end/build/reports/selenoid-logs:/opt/selenoid/logs:delegated"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://selenoid:4444/status" ]
      interval: 60s
      timeout: 20s
      retries: 5
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/end-to-end/build/reports/video
    # TODO: Fix hardcoded network name using env var for project file name or explicitly named network for this set of services.
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid","-save-all-logs","-disable-privileged", "-limit", "200"]
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    networks:
      selenoid: null
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTPS_METHOD: noredirect
  entrypoint:
    environment:
      - BUILDKITE
      - GRADLE_USER_HOME=/.gradle
      - BUILD_CACHE_URL
      - TZ="UTC"
    image: fsdfsdfsdfdsfs
    working_dir: $PWD
    volumes:
      - $PWD:$PWD:delegated
      - /tmp/gradle-cache:/.gradle:delegated
      - /var/run/docker.sock:/var/run/docker.sock
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      selenoid: null
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

```
Browser.json

{
    "chrome": {
      "default": "86.0",
      "versions": {
        "86.0": {
          "image": "selenoid/vnc:chrome_86.0",
          "port": "4444",
          "tmpfs": {"/tmp": "size=512m"}
        }
      }
    }
}

**Comment by vania-pooh** [comment]
@GiriReddy10 check whether browser image is actually downloaded. This error is self-explaining - you don't have the image downloaded.

**Comment by GiriReddy10** [comment]
![image](https://user-images.githubusercontent.com/67033789/114971447-ab9bf900-9ebf-11eb-8d14-fe6f14560dd6.png)
Ensured that image is actually available.

**Comment by aandryashin** [comment]
Please check difference between

vnc_chrome:86.0 and
vnc:chrome_86.0

For computers it is two different images... Humans may think that they are
the same.

пт, 16 апр. 2021 г., 07:26 Giri Reddy ***@***.***>:

**Comment by GiriReddy10** [comment]
It seems to working with this change. Thanks a lot for your quick response.

**Comment by GiriReddy10** [comment]
> Please check difference between vnc_chrome:86.0 and vnc:chrome_86.0 For computers it is two different images... Humans may think that they are the same. пт, 16 апр. 2021 г., 07:26 Giri Reddy ***@***.***>:
> 

It seems to be working with this change. Thanks a lot for your quick response.

**Comment by Bhaskar215** [comment]
@GiriReddy10  i have facing same issue. can u please the update what changes you made
