### ISSUE TITLE
Chrome 89 doesn't store clipboard content during browser's session

### ISSUE THREAD

**Issue by SmileySpb** [aerokube/selenoid#1092]
**Steps to reproduce:**
1) Add  Chrome 89  version to browsers.json
2) Pull d0cker image (89) and reload config **docker kill -s HUP selenoid**
3) Go to Selenoid UI and create new 89 session
4) Navigate to **yandex.ru/internet** and make sure the version has been applied. Copy URL  **yandex.ru/internet** and paste it to the next browser tab -> Copied URL was pasted successfully
5) Open accessing clipboard URL: <YOUR_IP>:4444/clipboard/<BROWSER_SESSION>
6) Copied URL is displayed
7) Refresh current tab nad pay attention at the result
**Actual result:** nothing is displayed (clipboard is empty)
**Expected result:** copied URL is displayed

**Comment by vania-pooh** [comment]
@SmileySpb clipboard feature works using `xsel` which works on X-server level and is not interacting with the browsers at all.

**Comment by SmileySpb** [comment]
> @SmileySpb clipboard feature works using `xsel` which works on X-server level and is not interacting with the browsers at all.

Hi, thank you for your answer. How to fix this problem if X-server works different for 87 and 89 chrome images?
