### ISSUE TITLE
Selenoid/"browsers"  can't pass the browser check even with secure connection!

### ISSUE THREAD

**Issue by miki676** [aerokube/selenoid#1093]
Good day!
I 've encountered nearly the same issue but mine is https,  - Checking your browser before accessing (url).
The point is it's the normal check which are encounter everytime in my any browser and after 5 seoncds (countdown goes to 0) I enter into my url. and next time I can enter without the browser check.
Unfortuntely,  none of the selenoid browsers pass the check, the countdown remain 5 seconds and after a while the selenoid driver closes.
![Selenoid](https://user-images.githubusercontent.com/76637616/115318393-79301b80-a19f-11eb-9714-bb1c707fd910.jpg)

In selenoid/chrome there is also a message :
Chrome is being controlled by automated test software.

And the rest message as in firefox picture.

How can I solve this?
Have been mention a solution here https://github.com/aerokube/selenoid/issues/1080, but I didn't understand how to add certificates.  My case is secure connection but with addidion with robot icon near the lock. 
I am so sorry but I new on programming, I appreciate your help, it would be kind of if you to tell me the solution with codes and commands.
Once more thank you.

**Comment by miki676** [comment]
Sorry, for such many questions.
How can I add in (python) capabilities:
"plugins": "Disabled",
I tried False instead of Disabled and also:
"enbalePlugins: False.
They didn't work
I got error:
Message: requested environment is not available
I am testing to get passed by check
Thank you for the help

**Comment by vania-pooh** [comment]
@miki676 
1) We don't know how Cloudflare checks browsers. Need more details on what's being checked.
2) At least Selenoid has no capabilities called `enablePlugins` and `plugins`.

**Comment by miki676** [comment]
@vania-pooh 
1 - after debuging with chromedriver (last release 90)  I saw console logs as follows:
          - [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
          - [Deprecation] chrome.loadTimes() is deprecated, instead use standardized API: Navigation Timing 2. <URL>.
  After using java script in console I received alert:
       - Site wants to:
            Store files on this device: - BLOCK   ALLOW
 Clicking allow didn't solve the problem because cloudflare was reloading and changing Ray ID fast ( RAY ID identification ID of the new user) and again saw the same logs.
 - Java script which gave me alert is:
 - 
 var requestedBytes = 1024*1024*280; 
navigator.webkitPersistentStorage.requestQuota (
    requestedBytes, function(grantedBytes) {  
        window.webkitRequestFileSystem(PERSISTENT, grantedBytes, onInitFs, errorHandler); 
    }, function(e) { console.log('Error', e); }
);

2 - I added in capabilities both options of plugins, I didn't receive error, the code ran well. :)

More about Cloudfare's browser check:
It uses java script to store Ray ID to identify users in the future.

**Comment by NekVik** [comment]
[miki676](https://github.com/miki676) Have you solved this problem?
