### ISSUE TITLE
Passing env variables in capabilities when using firefox

### ISSUE THREAD

**Issue by kornel-filep** [aerokube/selenoid#1098]
Hi!

I am trying to gather browser logs from inside the Selenoid browser instance.
For that, I route the firefox logs into /dev/stdout, so it gets inserted into the container logs of selenoid.
To get the browser logs from firefox, I use the special capabilities of Selenoid like so:
`
'selenoid:options': {
                enableLog: true,
                logName: 'firefoxlogs.log',
                env: [
                    'MOZ_LOG=webrtc_trace:5,signaling:5,mtransport:5,MediaManager:4,GetUserMedia:4,timestamp',
                    'MOZ_LOG_FILE=/dev/stdout',
                    'R_LOG_DESTINATION=/dev/stdout',
                    'R_LOG_LEVEL=9',
                    'R_LOG_VERBOSE=1',
                ],
            },
`
**Similar config works for the Chrome browser, but fails for Firefox.**
What I noticed is that if I set a random string for the environment variable like: env: ['key=value'], then the execution automatically crashes.

**Here is the error:**
`SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`

Could you please help, how could I fix this error? It seems that maybe all environment variables get overridden when setting the env variable.

Thank you in advance!

**Comment by BorisOsipov** [comment]
@kornel-filep please share full capabilities from config and log file with info level.

**Comment by kornel-filep** [comment]
Found the issue. I was using selenoid 1.10.1.
With Selenoid 1.10.3 there is no such issue. Closing this issue.
