### ISSUE TITLE
cannot create session chrome-latest on any hosts after 14 attempt(s)

### ISSUE THREAD

**Issue by Gladiatorz143** [aerokube/selenoid#1099]
Hi,

I am getting the following issue -

`  ----> OpenQA.Selenium.WebDriverException : cannot create session chrome-latest on any hosts after 14 attempt(s), last host error was: start container: Error response from daemon: symlink /var/lib/desktop-containerd/daemon/io.containerd.runtime.v2.task/moby/8b53804f65cee347872c03bd4c0b427d7a564f2033b32a1a5a2d3285fc25f2f1 /var/run/desktop-containerd/daemon/io.containerd.runtime.v2.task/moby/8b53804f65cee347872c03bd4c0b427d7a564f2033b32a1a5a2d3285fc25f2f1/work: no space left on device: unknown`

Not for all test cases but getting this as an issue for many test cases. We are running selenoid over teamcity pipeline.
Why this issue is appearing suddenly, any help will be helpful.

Please let me know if you need any other information.

**Comment by vania-pooh** [comment]
@Gladiatorz143 the error is self-explaining. Simply add more disk space.

**Comment by Gladiatorz143** [comment]
Thank you @vania-pooh 
We are actually using windows machine, WSL2 for running docker. And where its mounted or even all the drive has more than 48% disk space.
Can you help me to locate where is the issue related to disckspace?

I am novice. :)

Thanks..

**Comment by aandryashin** [comment]
Please check how many disk space allocated to docker.

пн, 3 мая 2021 г., 12:19 Gladiatorz143 ***@***.***>:
