### ISSUE TITLE
Request for CDP access for Webkit image

### ISSUE THREAD

**Issue by james-k-mathew** [aerokube/selenoid#1103]
Currently I am using Chrome using CDP in Selenoid

I took a look at the page
https://aerokube.com/images/latest/#_browser_image_information

I understand CDP is available for Chrome 85 .. Chrome 90

Will it be possible to access WebKit mentioned in
https://aerokube.com/images/latest/#_safari

using the CDP

**Comment by vania-pooh** [comment]
@james-k-mathew currently we never did such research.
