### ISSUE TITLE
move_by_offset().click() doesn't click

### ISSUE THREAD

**Issue by TheUnity** [aerokube/selenoid#1104]
`ActionChains(driver).move_by_offset(x, y).click().perform()`
`ActionChains(driver).move_by_offset(-x, -y).click().perform()`
Have this code in Python. Without Selenoid, in simple selenium window, everything works fine, but when I switch to Selenoid it doesn't work. I know exact coordinates, tried to find them with OpenCV. Both methods don't work.
There isn’t any error, code continue to work but click wasn’t performed.

**Comment by vania-pooh** [comment]
@TheUnity Selenoid actually proxies your call to respective webdriver binary. So this could be webdriver issue and depending on browser I would ask to create an issue in respective repository.
