### ISSUE TITLE
Internet Explorer with out docker | Protected Mode settings are not the same for all zones

### ISSUE THREAD

**Issue by arunganesh-a** [aerokube/selenoid#1105]
Hi,

When we run internet explorer directly with out container, with the following capabilities.

`DesiredCapabilities cap = DesiredCapabilities.internetExplorer();
cap.setBrowserName("internet explorer");
cap.setVersion("11");
cap.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);`

Getting the following error:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.

Generally when we are using cap.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);  the protected mode settings are ignored in selenium. Need help to sort this out

Thanks in advance,

**Comment by vania-pooh** [comment]
@arunganesh-a you need to go to IE settings and set Protected mode to the same value for all zones. This prerequisite is described in IEDriver documentation.
