### ISSUE TITLE
enable VNC not working in Robot framework with selenoid

### ISSUE THREAD

**Issue by kiruparkuma** [aerokube/selenoid#1108]
we were using Protractor for test automation and we have setup Selenoid for remote execution. Everything is working perfectly fine.
Now we are switching to Robot framework (Java version). I have setup the desired capabilities and remote url in "Open browser keyword"

Code in robot framework for launching tests on remote with desired capabilities
    ${desired caps}    getCapabilities    // capabilities are returned in this in string format with enablevnc as true
    Open Browser    ${SSO_URL}    ${Browser}    None    http://0.0.0.0:4444/wd/hub  ${desired caps}

Tests are executing on Selenoid but not able to see the execution, VNC flag is missing.

On the other hand i had done the setup in selenium 4 chrome standalone docker image and executed the robot tests on this image , i am able to see the execution even without the enable VNC flag. (tests are executed on noVNC).

Could some one help me in viewing the robot test (Java Port) execution on Selenoid.

**Comment by vania-pooh** [comment]
@kiruparkuma see https://github.com/aerokube/selenoid/issues/554#issuecomment-432604950.

**Comment by madb1ker** [comment]
Trying to run Selenoid on my Robot Framework tests but I am unable to view Video or record it.

![image](https://github.com/aerokube/selenoid/assets/79003568/93c4a7ce-5c6d-44b5-8d9c-36cd52040a4a)

![image](https://github.com/aerokube/selenoid/assets/79003568/9d76cbe5-7bb5-4d74-bba4-291d25777f20)

![image](https://github.com/aerokube/selenoid/assets/79003568/4e4425ab-b7c7-4bfe-9fc7-465ed9e5c0ca)

What am I doing wrong?

**Comment by vania-pooh** [comment]
@madb1ker see my comment above.

**Comment by madb1ker** [comment]
> @madb1ker see my comment above.

desired_capabilities has been deprecated and removed. 
I can run my tests in Robot Framework with Selenoid, I just cannot find how to set enableVNC and enableVideo to True.

**Comment by vania-pooh** [comment]
@madb1ker Selenoid supports W3C version of the protocol which is current standard, so Selenoid capabilities can go under `selenoid:options` key. Not sure how to add this in robot-framework. https://www.w3.org/TR/webdriver2/#extensions-0

**Comment by madb1ker** [comment]
> @madb1ker Selenoid supports W3C version of the protocol which is current standard, so Selenoid capabilities can go under `selenoid:options` key. Not sure how to add this in robot-framework. https://www.w3.org/TR/webdriver2/#extensions-0

Thank you!
For the record this is the correct way to use Selenoid with Robot Framework passing the arguments in the browser options:

`${selenoid_args}    Create Dictionary     enableVNC=${True}    enableVideo=${True}
      Open Browser  ${WMS_URL}  ${BROWSER}  remote_url=${SELENOID_SERVER}  options=set_capability("selenoid:options",${selenoid_args})`

**Comment by vania-pooh** [comment]
Ok, closing then.
