### ISSUE TITLE
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed.

### ISSUE THREAD

**Issue by regiewby** [aerokube/selenoid#1109]
Hi,
i'm trying to use selenoid in Mac M1 chip and i always get problem while execute the test script.
but when i move to Mac for intel, it absolutely works.

<img width="1058" alt="Screen Shot 2021-06-05 at 08 19 09" src="https://user-images.githubusercontent.com/63327727/120875589-c4c74900-c5d6-11eb-9f8c-355f4ffe00cc.png">

<img width="747" alt="Screen Shot 2021-06-05 at 08 19 16" src="https://user-images.githubusercontent.com/63327727/120875594-cabd2a00-c5d6-11eb-90cf-50618f455aa1.png">

**Comment by vania-pooh** [comment]
@regiewby Mac M1 CPU has ARM64 architecture and all our binaries and images are compiled for x86. Either move to x86 or rebuild browser images yourself from source code.

**Comment by gromanas** [comment]
Hello! Are there any thoughts on supporting also arm64 architecture? Thank you in advance!

**Comment by vania-pooh** [comment]
@gromanas we are now investigating this case.

**Comment by gromanas** [comment]
> @gromanas we are now investigating this case.

Thank you very much! Actually this will help a lot of users

**Comment by PolishchukSergey** [comment]
@gromanas  agree with you

**Comment by gromanas** [comment]
Any updates on that? Thank you in advance!

**Comment by vania-pooh** [comment]
It is possible to build some browser images for ARM64. However e.g. Chrome does not provide ARM64 builds for Linux, so this will just not work.

**Comment by gromanas** [comment]
Thank you @vania-pooh. Maybe I can use chromium images. I have seen also another issue related to that https://github.com/aerokube/selenoid/issues/1107
I have downloaded the image and I can start it, but I couldn't connect it with selenoid. In general, could you please guide or are there any instructions on how to connect selenoid to browser images outside from https://aerokube.com/images/latest/ ? Thank you again!

**Comment by sskorol** [comment]
FYI, created a draft PR https://github.com/aerokube/images/pull/524 with a build script. Or you can test it with a [prebuilt image](https://hub.docker.com/r/sskorol/selenoid_chromium_vnc/tags).

**Comment by asolntsev** [comment]
@vania-pooh What is the state of this issue? I see PR https://github.com/aerokube/images/pull/524 is already merged. Will it be released?

**Comment by vania-pooh** [comment]
@asolntsev we can put a tag. :) Currently we consider that people who have M1 can build images using this merged source code themselves. Currently we are building on x86 only. This can change during next months.

**Comment by gromanas** [comment]
@vania-pooh Thank you very much for the reply. Could you please provide some instructions on how to build m1 images?

**Comment by vania-pooh** [comment]
@gromanas see http://aerokube.com/images/latest/#_building_images. You should use `chromium` as `images` command argument.

**Comment by ValeriiBaidin** [comment]
> Any updates on that? Thank you in advance!
Thank you for your work.
Any updates?
