### ISSUE TITLE
Feature Request/Question: Possible to run Selenoid w/o auto-scaler? 

### ISSUE THREAD

**Issue by esaari** [aerokube/selenoid#1114]
Apologies if this is not the correct place for asking this - 

Is it possible to run Selenoid with a fixed number of nodes, similar to traditional Selenium grid if the auto-scaling is not desired?

**Comment by vania-pooh** [comment]
@esaari Selenoid is a static service allowing to run as many browsers as 1 host or VM allows. If you need to have several hosts - you have to use our load balancer called [Ggr](https://github.com/aerokube/ggr).

**Comment by esaari** [comment]
To rephrase my question, would it be possible, on a single host, to attach a fixed number of browser nodes to the Selenoid hub and not have them tear down after test execution? Similar to how Selenium Grid 3 starts with a fixed number of nodes and they may remain up all the time. 

(Also while I have you - does this Safari image work with Selenium Grid or will it only work with Selenoid? https://hub.docker.com/r/browsers/safari/tags?page=1&ordering=last_updated)

**Comment by vania-pooh** [comment]
@vania-pooh you can start several Selenoid instances on different network ports using `-listen` flag. Our browser images don't have grid registration support, so they will not be able to self-register to hub.

**Comment by esaari** [comment]
@vania-pooh would there be an issue if I tried extending your image to add that support?

**Comment by vania-pooh** [comment]
@esaari no, we consider grid registration an overkill and intentionally removed it. But you can do anything you wish in your fork.

**Comment by esaari** [comment]
@vania-pooh Thank you very much, this info was super helpful.
