### ISSUE TITLE
How we run "Brave browser" with  selenoid.

### ISSUE THREAD

**Issue by ankitjain082** [aerokube/selenoid#1115]
Hi,

I am using GGR and Selenoid for Grid to run automation test cases.
We have some specific test case which we want to run on "Brave browser", Brave is based on Chromium project and Chrome Browser also use the chromium project, It means both browsers are distant siblings.

I want to know, is there any option to run  **Brave browser**  on selenoid ?

Could anyone help me for the same.

Thanks,
Ankit Jain

**Comment by vania-pooh** [comment]
@ankitjain082 if that's based on Chromium (i.e. has the same rendering and Javascript engine) what is the reason for using Brave?

**Comment by Ankit-TWC** [comment]
@vania-pooh Brave browser is Global Privacy Control (GPC) by default and we released the code to support GPC for our site. So if we add that browser in automation, it would be easier for adding the automated test cases for GPC feature.

**Comment by vania-pooh** [comment]
@Ankit-TWC is there a webdriver being built for each version of Brave browser? So far as I can see there is no such driver. In that case we need a compatibility table between Brave versions and Chrome versions.

**Comment by Ankit-TWC** [comment]
Yes, you are right but do we have any workaround now?
Can you help me to archive this.

Thanks.

**Comment by Anticope12** [comment]
Hi @Ankit-TWC , 2 years later :) 
Were you able to find a work around for use of Brave Broswer?
