### ISSUE TITLE
Unable to access downloaded file through selenoid download api 

### ISSUE THREAD

**Issue by aliaksandrdziahel** [aerokube/selenoid#1117]
Hello ! 

Have an issue with accessing downloaded file through selenoid download api: when i am trying to get list of downloaded files using this instruction ( https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser ) i get empty list. 
However, when i go to chrome://downloads page, I see and can get access to desired file
Accessing it through chrome downloads page doesn't suite me as I need to run this autotest on different browsers, not only chrome
File name is generated dynamically so I cannot fetch it with GET request bypassing selenoid downloads page (by selenoid downloads page I mean  $hostname:4444/download/$session_id )

I will be very glad if you can help me, it is strange that I can access file through chrome downloads page and cannot through selenoid downloads page

**Comment by vania-pooh** [comment]
@aliaksandrdziahel are you saving to `/home/selenium/Downloads`?

**Comment by aliaksandrdziahel** [comment]
@vania-pooh when i run tests remotely on jenkins i don't explicitly set any folder to `download.default_directory` variable

**Comment by vania-pooh** [comment]
@aliaksandrdziahel by default our containers are using `selenium` as user and default download directory under Linux is `~/Downloads`. So it should work out of the box if you don't override related settings.

**Comment by aliaksandrdziahel** [comment]
@vania-pooh I am having this issue when i run autotests on Jenkins. I am not checking this folder as it is hard to check downloads folder in chrome container from selenoid container where autotests are run. Why I cannot access downloaded file within  $hostname:4444/download/$session_id link ?
