### ISSUE TITLE
Selenoid is unable to create more than 5 parallel sessions even when limit is set to 15

### ISSUE THREAD

**Issue by dhingraaditya** [aerokube/selenoid#1118]
![image](https://user-images.githubusercontent.com/51178791/125537661-f7469e2a-8781-4e5b-a0cc-b6b89be9eb39.png)

Hi ! We just started using Selenoid and noticed that even after increasing the container limit to 15, Selenoid is unable to create more than 5 test sessions. We have tried running Selenoid through cm binary for linux and through docker-compose. The issue persists in both the cases.

Used count in stats, in our case, never exceeds 5. Ideally there should be 12 tests running in parallel.
We are migrating from Zalenium and we did not have this issue with it .

We have docker running on Ubuntu 18.04.5 VM on ESXI
CPUs: 30 vCPUs
RAM: 27
Docker Version 20.10.7

**Comment by dhingraaditya** [comment]
I noticed that if I increase the limit to 30, I am able to launch 10 instances . So whatever limit I am passing is getting divided by three and I dont know why. I have even tried having only one browser entry for chrome browser in browsers.json .

**Comment by vania-pooh** [comment]
@dhingraaditya how about checking Selenoid logs with `docker logs selenoid`? Maybe this will clarify things.
