### ISSUE TITLE
Selenoid stop running after timeout

### ISSUE THREAD

**Issue by mhbm** [aerokube/selenoid#1119]
My RPA in selenoid makes many request and interaction in the web page, but after the time of timeout config (In my case is 5 minutes), the session is closed.

I think that the problem is checking if the download finished before the navigation.

My code of check download:

`php
public static function check_downloaded_file($download_folder, $sessionID, $timeout = 15)
    
    {
        for ($i = 0; $i < $timeout; $i++) {
            //verifica se arquivo está disponível no container
            $url = str_replace("wd/hub", "download/" , env('PATH_TO_SELENIUM_HUB'));
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 15);
            curl_setopt($ch, CURLOPT_TIMEOUT, 15);
            sleep(1);

            $result = curl_exec($ch);
            if (curl_errno($ch) !== 0) {
                curl_close($ch);
                throw new \Exception("Erro no download do arquivo: " . curl_error($ch));
            }

            curl_close($ch);

            //caso arquivo esteja disponível, baixa ele para o servidor da aplicação
            if (strpos($result, "href") !== false) {
                $file_name = substr($result, strpos($result, '"') + 1);
                $file_name = substr($file_name, 0, strpos($file_name, '"'));

                if (strpos($file_name, "crdownload") !== false) {
                    sleep(1);
                    continue;
                }

                $saveTo = $download_folder . DIRECTORY_SEPARATOR . $file_name;

                //Open file handler.
                $fp = fopen($saveTo, 'w+');

                //If $fp is FALSE, something went wrong.
                if ($fp === false) {
                    curl_close($ch);
                    throw new \Exception("Erro no download do arquivo: " . curl_error($ch));
                }

                //Create a cURL handle.
                $ch = curl_init($url . DIRECTORY_SEPARATOR . $file_name);

                //Pass our file handle to cURL.
                curl_setopt($ch, CURLOPT_FILE, $fp);

                //Timeout if the file doesn't download after 20 seconds.
                curl_setopt($ch, CURLOPT_TIMEOUT, 15);

                //Execute the request.
                curl_exec($ch);

                //If there was an error, throw an Exception
                if (curl_errno($ch)) {
                    curl_close($ch);
                    throw new \Exception("Erro no download do arquivo: " . curl_error($ch));
                }

                //Get the HTTP status code.
                $statusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

                //Close the cURL handler.
                curl_close($ch);

                //Close the file handler.
                fclose($fp);

                if ($statusCode != 200) {
                    throw new \Exception("Erro no download do arquivo: " . curl_error($ch));
                }

                //deleta o arquivo do contaner
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url . DIRECTORY_SEPARATOR . $file_name);
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
                $result = curl_exec($ch);
                $statusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

                if ($statusCode != 200) {
                    curl_close($ch);
                    throw new \Exception("Erro no download do arquivo: " . curl_error($ch));
                }
                curl_close($ch);

                //retorna caminho completo do arquivo no servidor
                return $saveTo;
                
            }
        }
`

Thanks

**Comment by mhbm** [comment]
When I didn't use this function, the timeout doesn't happen.
But I don't know where is the bug in the check download

**Comment by vania-pooh** [comment]
@mhbm what is your Selenoid version?

**Comment by mhbm** [comment]
> @mhbm what is your Selenoid version?

Selenoid 1.10.3!

**Comment by vania-pooh** [comment]
@mhbm timeout is being reset [here](https://github.com/aerokube/selenoid/blob/master/selenoid.go#L532-L534) when you start downloading files.

**Comment by mhbm** [comment]
@vania-pooh  but the problem is not this.
I used the function to check if the download finished.
When I didn't use this function, the navigation in the crawler works, but if I use this function, the timeout happens.
How do you do to check if the download finished?

**Comment by vania-pooh** [comment]
@mhbm Selenoid does not check this. Instead it operates with HTTP request timeouts.

**Comment by mhbm** [comment]
@vania-pooh I know that solenoid doesn`t check this.
But I need to verify if the download is finished, because I need to read the file.

I think that in this function, the selenoid thinks that one request in open, occurring the timeout (like I say in the below comment)

**Comment by mhbm** [comment]
@vania-pooh how do you check if download was finish using selenoid?
And How do you get the download?
