### ISSUE TITLE
Selenoid is not working in MAC

### ISSUE THREAD

**Issue by murtaza-aj** [aerokube/selenoid#1120]
### Setup

`docker images` output
![image](https://user-images.githubusercontent.com/48693600/126136316-92be10ea-1695-47d4-9814-5899c5482a63.png)

`docker ps` output
![image](https://user-images.githubusercontent.com/48693600/126136359-dc570048-28ca-446e-b033-9fc7d0aa9155.png)

docker UI (both selenoid and selenoid-ui are running)

![image](https://user-images.githubusercontent.com/48693600/126136458-8d644ce9-f384-4b13-a02b-dedb25b3824c.png)

`http://localhost:8080/#/` output
![image](https://user-images.githubusercontent.com/48693600/126136599-220615b9-4c02-4ca1-b964-0d789ae2cd30.png)

`http://localhost:4444/` output

![image](https://user-images.githubusercontent.com/48693600/126136698-37cbf1e6-9469-4bec-b389-245e118dd3b0.png)

`http://localhost:4444/status` output

![image](https://user-images.githubusercontent.com/48693600/126136762-3a9cc38e-44b0-4578-b6dd-d5c2ccae764d.png)

### Executing Tests

now executing tests using command `npx codeceptjs run-workers --suites 2`

getting following error

`Error: Error: Command failed: docker create --rm --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /Users/apple/Documents/office/github/Parallel-Execution/tests/bdd/config/:/etc/selenoid/:ro -v /Users/apple/Documents/office/github/Parallel-Execution/tests/bdd/report/video/:/opt/selenoid/video/ -v /Users/apple/Documents/office/github/Parallel-Execution/tests/bdd/report/logs/:/opt/selenoid/logs/ -e OVERRIDE_VIDEO_OUTPUT_DIR=/Users/apple/Documents/office/github/Parallel-Execution/tests/bdd/report/video/  aerokube/selenoid:latest-release -log-output-dir /opt/selenoid/logs
Error response from daemon: Conflict. The container name "/selenoid" is already in use by container "7f6f3ed61d70fd77d63498c0fe4c582af3f48901cd45d4737b78281f449d8d20". You have to remove (or rename) that container to be able to reuse that name.`

![image](https://user-images.githubusercontent.com/48693600/126137163-2bd752b1-48e3-4e11-93ef-b3e6df550894.png)

already tried removing the exiting container but always run into same error

cc: @vania-pooh

**Comment by vania-pooh** [comment]
@murtaza-aj this error comes from Docker and clearly states that you already have container with name `selenoid`.

**Comment by murtaza-aj** [comment]
@vania-pooh thanks for your swift response, 
I've updated `autoCreate` and set it to false

`selenoid: {
      enabled:        true,
      deletePassed:   true,
      autoCreate:     false,
      autoStart:      true,
      sessionTimeout: '30m',
      enableVideo:    false,
      enableLog:      false,
    }`


now the tests does execute but now they fail with a different error during execution

`connect ECONNREFUSED 127.0.0.1:4444`

![image](https://user-images.githubusercontent.com/48693600/126183824-aff7946c-9cf8-4aa3-9482-781a83b5cd50.png)

**Comment by vania-pooh** [comment]
@murtaza-aj that means "nothing is listening on localhost port 4444".
