### ISSUE TITLE
Allow more granular control of video recording

### ISSUE THREAD

**Issue by EvanShaw** [aerokube/selenoid#1122]
This issue is basically just a bump of #336.

While the video recording feature is great, it seems to me that the most likely use case for recording video is not per session but **per test**, with the name of each video being the name of the test with the exit status appended. So, something like `item-can-be-added-to-cart.failed.mpg` or `item-can-be-added-to-cart.success.mpg`.

Does the video-recorder or selenoid container provide an API to accomplish this?

Thanks

**Comment by vania-pooh** [comment]
@EvanShaw no, it does not. But there is an alternative video recorder: https://github.com/presidenten/selenoid-video-api

**Comment by EvanShaw** [comment]
@vania-pooh Thanks for the quick reply and suggestion. I'm considering using that alternative if need be.

I just want to confirm one thing though. In #336, you said:
> We are currently considering another approach which could help to solve the same issues

Did you guys ever implement what you were considering?

**Comment by vania-pooh** [comment]
@EvanShaw I don't think so and I frankly can't remember what we were considering.

**Comment by EvanShaw** [comment]
@vania-pooh Okay, I'll close this then.
