### ISSUE TITLE
Control recording Video Speed

### ISSUE THREAD

**Issue by AlexGrs** [aerokube/selenoid#1125]
As of now, the video record is a bit faster than in real life. 

I was wondering if there was an option or capability one could use to control the recording speed of the video record ? If not, would you be open to have this added on selenoid and how would you like to have it ?

**Comment by vania-pooh** [comment]
@AlexGrs currently we don't have such capability. But videos are recorded by default with 12 fps frame rate. So trying to set another value to `videoFrameRate` capability probably could help you. https://aerokube.com/selenoid/latest/#_video_recording_enablevideo_videoname_videoscreensize_videoframerate_videocodec
