### ISSUE TITLE
Android 11 build issue

### ISSUE THREAD

**Issue by f0rzer** [aerokube/selenoid#1126]
Hi.
there is a problem with building android 11 using the automate_android.sh

no problem at 8, 9, 10

in the current configuration, only the android version changes to "11.0"
and an error like this occurs:
![image](https://user-images.githubusercontent.com/24559628/127012050-c4261ce6-52e9-494c-8304-5c054dd9bcfb.png)

**Comment by vania-pooh** [comment]
@f0rzer so far as I can remember you have an issue in `default` keyword for Android system image. For Android 11 value differs. Correct values can be checked with `$sdkmanager --list` command.

**Comment by f0rzer** [comment]
build is success!

but how now in browser.json specify the path to it?

everything is started via cm

how exactly for this image to indicate that it is located locally?
and the rest are all images in the remote repository

**Comment by vania-pooh** [comment]
@f0rzer not possible in CM. Simply edit `browsers.json` manually and add new image. Path is always `/wd/hub` for Android images because of Appium.

**Comment by f0rzer** [comment]
@vania-pooh thanks

it turns out, unfortunately, the problem still exists during assembly

please build image android 11 on your docker hub, as with previous versions

**Comment by f0rzer** [comment]
@vania-pooh can you build?

**Comment by vania-pooh** [comment]
@f0rzer probably in a few days.

**Comment by Dor-bl** [comment]
Hi, 
Any android 11.0 image is coming soon?
