### ISSUE TITLE
[New session attempts retry count exceeded] on all attempts except 1st

### ISSUE THREAD

**Issue by MiluchOK** [aerokube/selenoid#1129]
I am seeing selenoid erroring out with [New session attempts retry count exceeded] on any new session creation attempts that is not 1st since docker restart. 

So, if I restart docker. First session will go through, but any other request will fail. 

Any idea how I can debug this?

**Comment by edurb** [comment]
i am also seeing this issue

**Comment by vania-pooh** [comment]
@MiluchOK need more details like browser container logs, Selenoid logs and Docker version.

**Comment by edurb** [comment]
how can we get selenoid logs?

**Comment by vania-pooh** [comment]
@edurb https://aerokube.com/selenoid/latest/#_logs_and_dirs
