### ISSUE TITLE
VNC support

### ISSUE THREAD

**Issue by remy-tiitre** [aerokube/selenoid#113]
I still dont undestand how to get this working. I tried your docker-compose file to start up selenoid and selenoid-ui. Then added this to my java code:
ChromeOptions options = new ChromeOptions();
options.addArguments("enableVNC=true");
capabilities.setCapability(ChromeOptions.CAPABILITY, options);

Is that what you mean in your documentation by "Pass enableVNC capability in tests". Either case I can see that the session is started but the VNC page sais "Sessions without VNC: 1".

**Comment by vania-pooh** [comment]
@remy-tiitre you should use a Docker image with VNC server inside. Default images do not contain VNC. I recently added information about VNC images here: http://aerokube.com/selenoid/latest/#_browser_image_information

**Comment by aandryashin** [comment]
The correct capability should be:
capabilities.setCapability("enableVNC", true);

**Comment by remy-tiitre** [comment]
capabilities.setCapability("enableVNC", true); That was the key that enabled the VNC. Don't know why I was trying to add it as ChromeOption. Maybe its a good idea to make a code example to documentation. But still both, VNC and Logs, will try to connect and then say disconnected. At first I tried to used custom built chrome image, but as that failed I started to use selenoid-images. Result is the same. In Selenoid UI I can see the sessions, they count for quota, but Logs and VNC connections seem to fail. Container logs don't provide much that would help me forward.

**Comment by vania-pooh** [comment]
Please then describe your environment:
1) Selenoid version
2) UI version
3) Operating system
4) Are you running in Docker or not

**Comment by remy-tiitre** [comment]
Using http://aerokube.com/selenoid/latest/#_selenoid_with_docker_compose composer file. browsers.json contains only 1 option: selenoid/chrome:58.0. Using docker.
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.9.0, build 2585387
CentOS 7.3
Linux 3.10.0-514.16.1.el7.x86_64 GNU/Linux
Selenoid image ae5c1c1c3aca
Selenoid-ui image 9d92a76acf6a

On CentOS you have to add IPTables rule to enable communication between the containers on the same host. Have done that. (iptables -I INPUT 4 -i docker0 -j ACCEPT) Without that UI doesn't even see the sessions.

**Comment by vania-pooh** [comment]
@remy-tiitre Selenoid UI is using Selenoid port 5900 to fetch VNC data. Couldn't it be that this port is unaccessible for some reason? However so far as stats are shown there is access to Selenoid port 4444. Could you also provide Selenoid UI container logs last lines?
@aandryashin, @lanwen any ideas?

**Comment by aandryashin** [comment]
It is necessary to use vnc-enabled images for corresponding browsers that
can be found here:

https://hub.docker.com/r/selenoid/vnc/tags/

please replace selenoid/chrome:58.0 with selenoid/vnc:chrome_58.0 that
packed with vnc server.

2017-06-08 20:07 GMT+03:00 Remy Tiitre <notifications@github.com>:

**Comment by remy-tiitre** [comment]
I changed the image at browsers.json and confirmed that selenoid will start selenoid/vnc:chrome_58.0. But the error remains the same. Session is there but connection failes for both - VNC and Logs.

Selenium UI seems to be quite quiet. Last log lines are:
2017/06/08 20:46:38 Listening on :8080
2017/06/08 20:47:01 Client added. 1 registered clients

How does UI fetch the logs, as it seems to be a similar connection issue there.

**Comment by vania-pooh** [comment]
@remy-tiitre this is done via websocket connection from UI to Selenoid `/logs/<session-id>`.

**Comment by aandryashin** [comment]
As I understand you are using CentOS, is there some firewall restrictions
can cause connection errors?

2017-06-09 6:46 GMT+03:00 Ivan Krutov <notifications@github.com>:

**Comment by aandryashin** [comment]
Just to double check everything. I ran selenoid and selenoid-ui with the
following configuration:

$ cat selenoid/browsers.json
{
    "chrome": {
        "default": "58.0",
        "versions": {
            "58.0": {
                "image": "selenoid/vnc:chrome_58.0",
                "port": "4444",
                "tmpfs": {"/tmp":"size=512m"}
            }
        }
    }
}

$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v
$(pwd)/selenoid:/etc/selenoid -p 4444:4444 aerokube/selenoid:1.3.1

$ docker run -it --rm -p 8080:8080 aerokube/selenoid-ui:1.3.0 -selenoid-uri
http://@host_ip@:4444

Then I was able to get vnc session for chrome browser.

2017-06-09 8:51 GMT+03:00 Alexander Andryashin <aandryashin@gmail.com>:

**Comment by vania-pooh** [comment]
@remy-tiitre any success?

**Comment by remy-tiitre** [comment]
Nope, no luck. I tried from different docker hosts as well. Will check tomorrow if we have some network rules disallowing that. But it's wierd that test run fine, so 4444 port works. Its just the vnc and logs proxy that doesnt seem to work.

**Comment by remy-tiitre** [comment]
I can confirm that when I put the selenoid and selenoid-ui to a different host then both work VNC and logs. So it is somekind of networking issue on CentOS host, probably IPTables. Will let you know when I have time to investigate it more deeply.

**Comment by remy-tiitre** [comment]
One thing I did notice though. Right now you have to use network_mode = bridge so that selenoid can connect to "browser" containers. This does not work very well when you run in docker swarm or any other orhestration solution. Network component should be configurable for browser containers or even better it should be smart enough to take it from selenoid container.

**Comment by tlytvyn** [comment]
I have the same issue on OS X - vnc and logs tabs are empty but the session is started and tests are passing.

**Comment by vania-pooh** [comment]
@tlytvyn could you please try with ```aerokube/selenoid-ui:latest```? We implemented VNC proxying via UI backend but did not release yet.

**Comment by tlytvyn** [comment]
@vania-pooh tried - same thing (

**Comment by vania-pooh** [comment]
@tlytvyn what errors do you have inside UI logs?

**Comment by vania-pooh** [comment]
@tlytvyn these issues are only reproducible in Docker containers. Just launch standalone binary instead while we're search for solution.

**Comment by vania-pooh** [comment]
We implemented proxying of VNC port through UI backend. This should work. Feel free to reopen if does not work with latest UI and Selenoid releases.

**Comment by edsherwin** [comment]
I'm having this issue on my Windows host machine also. Able to create a session on my tests however the VNC session is not displayed in Selenoid UI.

**Comment by vania-pooh** [comment]
@edsherwin not related to this issue. You are not passing enableVNC = true capability in your code.
