### ISSUE TITLE
Is selenoid gonna quit itself?

### ISSUE THREAD

**Issue by udemy1013** [aerokube/selenoid#1130]
I'm trying to use selenoid with GUI. remote drivers quit themselves after getting some URLs. How can I make them wait until I send some action? sorry for bad English

**Comment by vania-pooh** [comment]
@udemy1013 by default Selenoid is closing a session after 1 minute without new requests to browser. This is controlled by `sessionTimeout` capability or `-timeout` flag. For manual session from UI this timeout is explicitly set to 1 hour.

**Comment by udemy1013** [comment]
@vania-pooh Thanks, sir. It helped.
