### ISSUE TITLE
Locale not set correctly inside Firefox VNC image at OS level

### ISSUE THREAD

**Issue by sandipchitale** [aerokube/selenoid#1131]
![image](https://user-images.githubusercontent.com/3310939/129122574-de7e78cc-397e-4e3d-97ac-171423087149.png)

And because I cannot **sudo** I cannot set locale myself. May be there is away.

This causes weird behavior for the JavaScript method inside Firefox console:

![image](https://user-images.githubusercontent.com/3310939/129122803-1ef15d99-b42a-4d15-8309-5a256a0268c7.png)

On any other VM where locale is set correctly it works differently.

![image](https://user-images.githubusercontent.com/3310939/129122919-f7c47b82-9beb-49d5-8fa8-57d3109a9c92.png)

**Comment by vania-pooh** [comment]
@sandipchitale you can set any value using `env` capability or the same key in `browsers.json`. All Unicode locales are actually generated inside browser images.

**Comment by sandipchitale** [comment]
Thanks. I will give it a try.

**Comment by sandipchitale** [comment]
That worked. Thanks for quick response. Please close the issue.
