### ISSUE TITLE
VNC on windows machine not working

### ISSUE THREAD

**Issue by soumyathampi** [aerokube/selenoid#1134]
Hi,

Iam running the following commands on windows 10 machine:
o start selenoid:
"cm_windows_amd64 (1).exe"  selenoid start --vnc -d 
Using driver binaries...
Selenoid is already downloaded
Selenoid is already configured
Starting Selenoid...
Successfully started Selenoid
2021/08/17 23:52:47 [-] [INIT] [Loading configuration files...]
2021/08/17 23:52:47 [-] [INIT] [Loaded configuration from C:\Users\auto.aerokube\selenoid\browsers.json]
2021/08/17 23:52:47 [-] [INIT] [Logs Dir: C:\c\Users\auto.aerokube\selenoid\logs]
2021/08/17 23:52:47 [-] [INIT] [Timezone: Local]
2021/08/17 23:52:47 [-] [INIT] [Listening on :4444]===========

Now if I start a manual session from selenoid UI, on manual UI I get this error
Connecting to ws://10.1.124.207:8080/ws/logs/a9133034-772b-4c8a-9182-cd8668dd409e...
Connected!
Disconnected

========================================================================

Logs On Selenoid command 

C:\Users\auto\Downloads>2021/08/18 03:50:35 [-] [INIT] [Loading configuration files...]
2021/08/18 03:50:35 [-] [INIT] [Loaded configuration from C:\Users\auto\.aerokube\selenoid\browsers.json]
2021/08/18 03:50:35 [-] [INIT] [Logs Dir: C:\c\Users\auto\.aerokube\selenoid\logs]
2021/08/18 03:50:35 [-] [INIT] [Timezone: Local]
2021/08/18 03:50:35 [-] [INIT] [Listening on :4444]n] [10.227.142.155]
2021/08/18 03:59:23 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.227.142.155]
2021/08/18 03:59:23 [3] [LOCATING_SERVICE] [internet explorer] [11]
2021/08/18 03:59:23 [3] [USING_DRIVER] [internet explorer] [11]
2021/08/18 03:59:23 [3] [ALLOCATING_PORT]
2021/08/18 03:59:23 [3] [ALLOCATED_PORT] [51109]
2021/08/18 03:59:23 [3] [STARTING_PROCESS] [[C:\Users\auto\.aerokube\selenoid\IEDriverServer.exe --port=51109]]
2021/08/18 03:59:24 [3] [PROCESS_STARTED] [5220] [0.50s]
2021/08/18 03:59:24 [3] [PROXY_TO] [http://127.0.0.1:51109/]
2021/08/18 03:59:24 [3] [SESSION_ATTEMPTED] [http://127.0.0.1:51109/] [1]
2021/08/18 03:59:25 [3] [SESSION_CREATED] [a9133034-772b-4c8a-9182-cd8668dd409e] [1] [1.84s]
2021/08/18 03:59:26 [4] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 03:59:31 [5] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 03:59:59 [6] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 03:59:59 [8] [SESSION_NOT_FOUND] [a9133034-772b-4c8a-9182-cd8668dd409e]
2021/08/18 03:59:59 [9] [VNC_ENABLED] [a9133034-772b-4c8a-9182-cd8668dd409e]
2021/08/18 04:00:01 [10] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 04:00:06 [11] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 04:00:11 [12] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 04:00:16 [13] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 04:00:21 [14] [VIDEO_ERROR] [Failed to list directory C:\c\Users\auto\.aerokube\selenoid\logs: open video: The system cannot find the file specified.]
2021/08/18 04:00:26 [9] [VNC_CLIENT_DISCONNECTED] [a9133034-772b-4c8a-9182-cd8668dd409e]
2021/08/18 04:00:26 [9] [VNC_SESSION_CLOSED] [a9133034-772b-4c8a-9182-cd8668dd409e]

===========================================================================

Logs On selenoid-ui command
2021/08/18 03:59:59 [WS_PROXY] [/ws/logs/a9133034-772b-4c8a-9182-cd8668dd409e] [ws://localhost:4444/logs/a9133034-772b-4c8a-9182-cd8668dd409e]
2021/08/18 03:59:59 [WS_PROXY] [/ws/vnc/a9133034-772b-4c8a-9182-cd8668dd409e] [ws://localhost:4444/vnc/a9133034-772b-4c8a-9182-cd8668dd409e]
2021/08/18 04:00:26 [WS_PROXY] [/logs/a9133034-772b-4c8a-9182-cd8668dd409e] [CLOSED]
2021/08/18 04:00:26 [WS_PROXY] [/vnc/a9133034-772b-4c8a-9182-cd8668dd409e] [CLOSED]

**Comment by soumyathampi** [comment]
If I dont' try connecting to VNC, the SESSION gets added and deleted successfully, whereas if I connect to vnc in between SESSION_NOT_FOUND error is thrown.
As per the doc SESSION_NOT_FOUND error is thrown when we request VNC or logs for unknown session. Is it related to this issue [1133](https://github.com/aerokube/selenoid/issues/1133) as both occurs on same machine.

**Comment by vania-pooh** [comment]
@soumyathampi not related to logs.

**Comment by soumyathampi** [comment]
No, I just started selenoid UI with"cm_windows_amd64 (1).exe" selenoid-ui start -d

**Comment by soumyathampi** [comment]
Got the vnc to work, On windows machine, tight vnc configurations -> access control ->allow loopback connections. will allow the vnc to work.

But the mouse movements are not transferred to windows server.

**Comment by soumyathampi** [comment]
Issue fixed with following change:
 On windows machine, tight vnc configurations -> access control ->allow loopback connections.
