### ISSUE TITLE
unrecognized chrome option: AcceptInsecureCertificates while passing ChromeOptions to AppiumOptions - C# Selenium

### ISSUE THREAD

**Issue by roshanust** [aerokube/selenoid#1141]
I'm trying to send the below chrome option because the chrome(version: 74.XXX) in my android emulator is blocking selenium scripts. But when building, I get this error and tried in different ways

**chromeOptions.AddArgument("--disable-blink-features=AutomationControlled");** 
and I tried to pass in AppiumOptions by
**options.AddAdditionalCapability(AndroidMobileCapabilityType.ChromeOptions, chromeOptions);** OR
**options.AddAdditionalCapability(ChromeOptions.Capability, chromeOptions);**
But getting bellow error
**Mobiledriver initialisation issuesException :OpenQA.Selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: invalid argument: cannot parse capability: chromeOptions
    from invalid argument: unrecognized chrome option: AcceptInsecureCertificates**

I see a similar issue earlier https://github.com/aerokube/selenoid/issues/348 but the solution doesn't seem to be working since DesiredCapabilities are obsolete now

Any help would be highly appreciated

**Comment by vania-pooh** [comment]
@roshanust probably should be lowercase `acceptInsecureCerts = true` or should go under `goog:chromeOptions`.

**Comment by roshanust** [comment]
@vania-pooh I'm not passing AcceptInsecureCertificates in chromeoptions at all. Looks like this is specific to C# because as per other discussions the same solutions works fine for JAVA. Not sure if any tired to pass chromeoptions to appium using C#

**Comment by petersilva-ece** [comment]
Is this resolved? Facing the same issue
