### ISSUE TITLE
Selenium session fails with new geckodriver 0.30.0

### ISSUE THREAD

**Issue by ruescar** [aerokube/selenoid#1142]
geckodriver 0.30.0 [release](https://github.com/mozilla/geckodriver/releases/tag/v0.30.0) introduces a change that breaks Firefox Selenium sessions:
**Improved Host header checks to reject requests not sent to a well-known
local hostname or IP, or the server-specified hostname.**

Selenoid logs:
[SESSION_FAILED] [http://127.0.0.1:40377] [500 Internal Server Error]

geckodriver logs:
WebDriver Host header doesn't match server localhost

**Comment by ruescar** [comment]
I wonder if this could be related with #1128

**Comment by kornel-filep** [comment]
+1, also encountered this issue. I wonder if it is possible to configure something in browsers.json to circumvent this? Like configuring the whitelisted ips?

**Comment by kornel-filep** [comment]
Also a Note: I see this in Selenoid version 1.10.4. Which does not contain the changes from #1128.

**Comment by ruescar** [comment]
@kornel-filep Yes. I also confirm that #1128 is not causing this. I suggest to stick to geckodriver 0.29.1 when building the browser images until this issue is fixed. You just need to pass **-d 0.29.1** to the **images** command

**Comment by vania-pooh** [comment]
Did you try version 1.10.5?

**Comment by vania-pooh** [comment]
@kornel-filep currently there is no such setting to overcome this. Because this is related to HTTP header checking.

**Comment by ruescar** [comment]
@vania-pooh This issue does happen with Selenoid 1.10.5 as well as when building images and running selenoid-container-tests.

**Comment by kornel-filep** [comment]
Hi, any news regarding a fix for this issue? Can't this be solved the same way as https://github.com/aerokube/selenoid/issues/1070 was solved?

**Comment by vania-pooh** [comment]
That was fixed in 0.31.0.

**Comment by callenmas14** [comment]
@vania-pooh - do we need to update geckodriver to 0.31.0 and selenoid for this to work?  Or will just the upgraded geckodriver 0.31.0 suffice?  I ask because we forked an older version of selenoid and would need to do a  sizeable project to merge in the latest selenoid code.  I know - not the best way to use open source.  But it is what it is.  We'll upgrade Selenoid at some point.  But for the time being can we update just the 0.31.0 driver to solve this issue?

**Comment by vania-pooh** [comment]
@callenmas14 there is 0.32.0 already. https://github.com/mozilla/geckodriver/releases/tag/v0.32.0

**Comment by callenmas14** [comment]
@vania-pooh - I would use that but 0.32.0 has a min of 102 ESR.  We provide browsers starting from 95.0 internally.  So we'll need 0.31.0.

BTW I tried out 0.31.0 last night, without the selenoid changes and by providing the --host-names argument and I didn't get the 'Invalid host header' error.
