### ISSUE TITLE
Get UnreachableBrowserException error When I run selenoid tests in Gitlab CI

### ISSUE THREAD

**Issue by RLCai** [aerokube/selenoid#1147]
I am running the gitlab CI with selenoid and chrome docker images.
First I developed the docker-compose.yml with images: "aerokube/selenoid:latest", "aerokube/selenoid-ui:latest" and "selenoid/vnc_chrome:90.0". And run the test on docker locally. It's passed. Below is the test part which related to the remote url setup for the test runned locally.
    
     @BeforeSuite
     fun setup() {
        Configuration.driverManagerEnabled = false
        Configuration.remote = "http://localhost:4444/wd/hub"
        Configuration.baseUrl = "https://www.google.com/"

        //System.setProperty("selenide.browser", "chrome")
        Configuration.browser = "chrome"
        Configuration.browserVersion = "90.0"
        //Configuration.browserSize = "1920x1080"
        Configuration.startMaximized
    

        val capabilities = DesiredCapabilities()
        Configuration.browserCapabilities = capabilities
        capabilities.setCapability("enableVNC", true)
        capabilities.setCapability("enableVideo", true)

    @Test
    fun logIn() {
        open("https://www.google.com/")
  
Then I wrote a gitlab-ci.yml file and wanted to run it on Gitlab CI with gitlab runner.
But when I run the test. It failed. The error is:

Gradle suite > Gradle test > com.UItest.ManageProject > logIn FAILED
59    org.openqa.selenium.remote.UnreachableBrowserException at ManageProject.kt:46
60        Caused by: java.net.ConnectException at ManageProject.kt:46
61            Caused by: java.net.ConnectException at ManageProject.kt:46

I thought it's because the reason should be on the remote URL. Then I tried to change the remote url as those below, but still failed.

     Configuration.remote = "http://selenoid__vnc-chrome:4444/wd/hub"
     Configuration.remote = "http://selenoid-chrome:4444/wd/hub"
     Configuration.remote = "http://selenoid:4444/wd/hub"

The error is:

Gradle suite > Gradle test > com.UItest.ManageProject > logIn FAILED
    org.openqa.selenium.remote.UnreachableBrowserException at ManageProject.kt:46
        Caused by: java.net.UnknownHostException at ManageProject.kt:46

Dose anyone know the reasons and help me? If you need more details, please tell me. Thanks in advance.

**Comment by vania-pooh** [comment]
@RLCai this is something related to Gitlab CI and not related to Selenoid. Need to make sure Gitlab CI can resolve container names like Docker does in custom networks.

**Comment by RLCai** [comment]
Hi, @vania-pooh I am not sure if I understand what you mean. The error is about the remote browser. So I guess the problem is on "Configuration.remote = "http://localhost:4444/wd/hub"", because when the test running in gitlab CI, it cannot use the local url. we need to find out the selenoid url. Is that right? or is there any other problems in my codes?
The files I am using are below, could you have a look? Thank you so much.
The gitlab-ci.yml file:

image: gradle:jdk11

stages:
  - gradle-build
  - docker-test

.gradle_template: &gradle_definition
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - export GRADLE_USER_HOME=${CI_PROJECT_DIR}/.gradle

gradle-build:
  <<: *gradle_definition
  stage: gradle-build
  script:
    - chmod +x ./gradlew
    - ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour
  only:
    - feature/edit_section

docker-test:
  stage: docker-test
  image:
    name: docker/compose:1.29.2
    entrypoint: [ "/bin/sh", "-c" ]
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  dependencies:
    - gradle-build
  before_script:
    - docker info
    - docker-compose --version
  script:
    - apk add --no-cache docker-compose
    - apk add openjdk11
    - docker network create selenoid
    - docker-compose down
    - docker-compose up --build --force-recreate --no-deps -d
    - docker network inspect selenoid
    - echo "Hello, UI-test"
    - chmod +x ./gradlew
    - ./gradlew :test --tests "com.UItest.ManageProject"
  only:
    - feature/edit_section 

after_script:
  - echo "End CI"


docker-compose.yml:

version: '3'

services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - selenoid
    volumes:
      - ".:/etc/selenoid"
      - "/c/labb:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/labb:/opt/selenoid/video"
    environment:
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/c/labb"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  chrome_90.0:
    image: "selenoid/vnc_chrome:90.0"
    container_name: chrome_90.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"

networks:
  selenoid:
    external:
      name: selenoid

And the browsers.json file:
{
  "chrome": {
    "default": "90.0",
    "versions": {
      "90.0": {
        "image": "selenoid/vnc:chrome_90.0",
        "port": "4444",
        "path": "/"
      }
    }
  }

**Comment by aandryashin** [comment]
It is not necessary to run selenoid on GitlabCI, first because it denies to
run privileged containers, second you can run browser image directly. Also
you have to add appropriate service to be able access container by name.

вс, 17 окт. 2021 г., 18:54 RLCai ***@***.***>:

**Comment by RLCai** [comment]
Thanks. @aandryashin It's a good solution. If finally I cannot solve it, I have to run it without selenoid.
