### ISSUE TITLE
Add description for statistic metrics and session lifecycle

### ISSUE THREAD

**Issue by bashlakov** [aerokube/selenoid#115]
Hi!
I have several questions:
1) Could you explain, what does pending sessions and queued sessions metrics mean?
2) How does the session change its state (queued, pended, attempted and allocated) within the request process?
3) What is limited by setting limit flag?
4) What is going on with new requests when the limit is reached?

Please, add this information to docs.
Thanks!

**Comment by vania-pooh** [comment]
@bashlakov: see http://aerokube.com/selenoid/latest/#_what_statistics_mean

**Comment by bashlakov** [comment]
Good, thanks!
