### ISSUE TITLE
Chrome 94/95 Not Detecting Site Updates

### ISSUE THREAD

**Issue by omegadash** [aerokube/selenoid#1153]
I am running Selenoid through Docker Desktop on Windows 10. I have an automation that sends a request that causes a button to automatically pop up. When checking this manually on normal desktop Chrome the button pops up automatically as expected but on Selenoid Chrome 94/95 it does not. 

So far the most stable version of Selenoid Chrome is 91. Any suggestions on how to fix. Also is there any additional detail required?

**Comment by vania-pooh** [comment]
@omegadash I would suggest trying to reproduce the same in Selenoid UI to get more details on what's happening.

**Comment by omegadash** [comment]
> @omegadash I would suggest trying to reproduce the same in Selenoid UI to get more details on what's happening.

Sorry, I forgot to mention that I use Selenoid UI to look in on the session, that is how I noticed this behaviour. If I unlock the session and click refresh the button will then pop up.

**Comment by vania-pooh** [comment]
@omegadash in Selenoid UI you are using just the same browser image in automated tests. The only difference is that you are interacting using real mouse. There could be something related to mouse events attached to your button. E.g. you are expecting a mouse pointer to move over some area and in automated test pointer is probably moves immediately to the point specified in the test case.

**Comment by omegadash** [comment]
> @omegadash in Selenoid UI you are using just the same browser image in automated tests. The only difference is that you are interacting using real mouse. There could be something related to mouse events attached to your button. E.g. you are expecting a mouse pointer to move over some area and in automated test pointer is probably moves immediately to the point specified in the test case.

I do not think this is the case, the way the site is designed is such that certain elements can automatically appear without any user interactions. I remember reading a issue thread with a similar issue and there was mention of disabling hardware acceleration on the Chrome image, is that something that I can try? If so, how do I go about doing it?

**Comment by vania-pooh** [comment]
@omegadash acceleration is already disabled by default.
