### ISSUE TITLE
How can I put proxy in selenoid?

### ISSUE THREAD

**Issue by TKS-MateusMacedo** [aerokube/selenoid#1159]
How can I put proxy in selenoid?

**Comment by TKS-MateusMacedo** [comment]
@vania-pooh

**Comment by vania-pooh** [comment]
@TKS-MateusMacedo using standard Selenium `proxy` capability. Selenoid is W3C compatible.

**Comment by TKS-MateusMacedo** [comment]
@vania-pooh  I used but not working.

```php
       
            $capabilities->setCapability(WebDriverCapabilityType::PROXY, [
                'httpProxy' => $proxyUrl,
                'sslProxy' => $proxyUrl,
                'ftpProxy' => $proxyUrl,
                "noProxy"   => "",
                'proxyType' => 'manual',
            ]);
```

**Comment by vania-pooh** [comment]
@TKS-MateusMacedo seems to be correct. Make sure you are using recent WebDriver client version. Also try to remove `ftpProxy` which is deprecated in some browsers.

**Comment by mhbm** [comment]
@vania-pooh  Thanks! The WebDriver is the last version but it didn't work.

Is it possible to put proxy in selenoid?

**Comment by vania-pooh** [comment]
@mhbm need an exact error message then.

**Comment by TKS-MateusMacedo** [comment]
@vania-pooh The error is that que proxy didnt work. The IP of selenoid doesnt change

**Comment by Tyson1986** [comment]
I have vise versa problem, we have proxy set via variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY
So I believe if you set these, it should work.

**Comment by TZbooo** [comment]
similar problem...
