### ISSUE TITLE
How can I emulate mobile device in Selenoid and WDIO

### ISSUE THREAD

**Issue by DanyloRomanov** [aerokube/selenoid#1161]
Dear selenoid team,
I am trying to run WDIO automation tests in selenoid  using 
"selenoid:options": {
  "mobileEmulation": { "deviceName": "iPhone 7" },
  "args": ["disable-infobars", "--window-size=420,667", "--no-sandbox", "--disable-gpu", "--user-agent='Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53'"],
  "enableVNC": true,
  "enableVideo": false,
  "sessionTimeout": "240s"
}

same options work for goog:chromeOptions.
When I run tests using the options above - the tests are run on desktop. Can you please advice me what is wrong with my config or how can I run those tests emulating mobile devices?

Thank you,
Danylo

**Comment by vania-pooh** [comment]
@DanyloRomanov Selenoid support all capabilities for respective drivers. You can continue sending `goog:chromeOptions` and these capabilities will be passed to Chromedriver.

**Comment by DanyloRomanov** [comment]
Hi @vania-pooh! Unfortunately it does not work for me. When I pass goog:chromeOptions  I cannot pass parameters like "enableVNC":true, "enableVideo": false as they are only supported by selenoid:options. Also If I exclude these parameters - I get error " Failed to fetch browser webSocket URL from http://localhost:41741/json/version: request to http://localhost:41741/json/version failed, reason: connect ECONNREFUSED 127.0.0.1:41741"
So the only setup it works for me is desktop version of selenoid:options. May be you know some boilerplates that I can look into to make it work with mobile? 
This is my config file in Json format {
    "specs": [
        "list of features"
    ],
    "exclude": [],
    "maxInstances": 10,
    "logLevel": "error",
    "bail": 0,
    "waitforTimeout": 1000,
    "pageLoad": 10000,
    "script": 10000,
    "connectionRetryTimeout": 120000,
    "connectionRetryCount": 3,
    "capabilities": [
        {
            "maxInstances": 15,
            "browserName": "chrome",
            "hostname": "selenoid-selenoid.selenoid",
            "path": "/wd/hub",
            "protocol": "http",
            "selenoid:options": {
                "args": [
                    "disable-infobars",
                    "--window-size=420,667",
                    "--no-sandbox",
                    "--disable-gpu",
                    "--user-agent='Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53'"
                ],
                "enableVNC": true,
                "enableVideo": false,
                "sessionTimeout": "240s"
            }
        }
    ],
    "framework": "cucumber",
    "reporters": [
        [
            "cucumberjs-json",
            {
                "jsonFolder": "results/json/",
                "language": "en"
            }
        ],
        "spec"
    ],
    "cucumberOpts": {
        "require": [
            "./step_definitions/*.js",
            "./support/*.js"
        ],
        "backtrace": false,
        "requireModule": [],
        "dryRun": false,
        "failFast": false,
        "format": [
            "json:results/results.json"
        ],
        "snippets": true,
        "source": true,
        "profile": [],
        "strict": false,
        "tagExpression": "tags expression",
        "timeout": 120000,
        "ignoreUndefinedDefinitions": false
    },
    "baseUrl": "baseurl",
    "isMobile": true,
    "services": [
        "devtools"
    ]
}

**Comment by vania-pooh** [comment]
@DanyloRomanov `/devtools` API only works in containers. You should be able to pass both `goog:chromeOptions` and `selenoid:options` keys in the same request.

**Comment by qtis** [comment]
We are doing it with mix of userAgent and deviceMetrics.

in wdio.config: 
`        {
            maxInstances: 1,
            browserName: 'chrome',
            browserVersion: 'vnc_chrome:96.0',
            specs: mobileFeatures,
            'goog:chromeOptions': {
                mobileEmulation: {
                    userAgent: 'Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.119 Mobile Safari/537.36',
                    deviceMetrics: {
                        width: 360,
                        height: 640,
                        pixelRatio: 3
                    }
                },
                args: [ 'disable-extensions' ],
            },
            'selenoid:options': {
                enableVNC: true,
                enableVideo: true
            }
        }`
        
Above example runs like Samsung Galaxy S7

**Comment by vania-pooh** [comment]
@DanyloRomanov  `maxInstances` and `specs` are not W3C compatible capabilities.

**Comment by DanyloRomanov** [comment]
> @DanyloRomanov `/devtools` API only works in containers. You should be able to pass both `goog:chromeOptions` and `selenoid:options` keys in the same request.

Worked with both! Thanks

**Comment by vania-pooh** [comment]
Ok, closing then.
