### ISSUE TITLE
How to (re)set initial mouse position for OS?

### ISSUE THREAD

**Issue by qtis** [aerokube/selenoid#1163]
We are experiencing problem that OS cursor seems to be placed in the middle of the screen and affects mouse events when application is running.

I took a screenshot from recording (before chrome starts, which is in next second) and you can see mouse cursor in the middle of the screen.

![image](https://user-images.githubusercontent.com/16225254/146927677-23dd6d0c-e2c4-4cea-8976-0e848b31c6fd.png)

Is there a way to control or remove OS mouse cursor as chromedriver (via webdriver) seems to emulate it's own cursor, not via OS so you end up with two cursors :|

**Comment by vania-pooh** [comment]
@qtis you can add `xdotool` command call to browser image `entrypoint.sh` to fix this. Currently this is not supported out of the box.

**Comment by qtis** [comment]
> @qtis you can add `xdotool` command call to browser image `entrypoint.sh` to fix this. Currently this is not supported out of the box.

That helped. Now I've built custom image based on chrome_vnc with xdotool installed via Docker build 
and extra line in entrypoint.sh:
```
echo Moving mouse to position 0 0
DISPLAY="$DISPLAY" /usr/bin/xdotool mousemove 0 0
```

You can see it is in the corner now:

![image](https://user-images.githubusercontent.com/16225254/147104462-9ca0e29b-ae11-4b95-8e0c-c9f68e9f0e4b.png)

Would be great if you could also add it to official images as same issue might be causing issues for other as well. Otherwise I guess I'd have to rebuild custom images on each release ¯\_(ツ)_/¯

**Comment by gdonati78** [comment]
We experience a cursor displayed when we run Chrome with mobile emulation enabled (experimental option mobileEmulation). No cursor would be expected, none is shown when using other hubs with the same settings. Is it related to this same issue?

**Comment by vania-pooh** [comment]
@gdonati78 Chrome in mobile emulation is the same as Chrome desktop. So yes, that's related.
