### ISSUE TITLE
Android Emulator can't start tests wait: http://172.18.0.4:4444/wd/hub does not respond. SOLVED 

### ISSUE THREAD

**Issue by BorisPotapov** [aerokube/selenoid#1166]
Hello,

I have the same question 
https://stackoverflow.com/questions/68915182/how-to-close-nested-virtualization-popup-for-emulator-while-running-automation-t

My tests can't start cause sees  Nested Virtualization popup. (image default android 6.0)
I downloaded https://github.com/aerokube/images 
then went so /selenium/ and started ./automate_android.sh with defaults 

I got images android:8.1
then I added this to browser and started my tests

when I start this image Can't start test wait: http://172.18.0.4:4444/wd/hub 
Max time for waiting 20m 

environment: win10 i7 +VirtBox Ubuntu 18 + testng + gradle

May be you can help me!

**Comment by vania-pooh** [comment]
@BorisPotapov should not be shown. https://github.com/aerokube/images/blob/master/selenium/android/Emulator.conf#L2

**Comment by BorisPotapov** [comment]
@vania-pooh thanks for fast answer.

I can't build image correctly with this emulator config.  After build i see wait: http://172.18.0.4:4444/wd/hub does not respond in 20m0s

or you mean I should switch this parameter manually? Please, send me example

**Comment by vania-pooh** [comment]
@BorisPotapov should build your image from scratch.

**Comment by BorisPotapov** [comment]
@vania-pooh could you send me a steps for it, please. I am not sure that I can build image from scratch.

I see only this documentation "` https://aerokube-com.translate.goog/images/latest/?_x_tr_sl=auto&_x_tr_tl=ru&_x_tr_hl=be#_building_images `" and for creating android image i found two lines
```
$ cd selenium
$ ./automate_android.sh
```
I used they the previous time. this lines don't suite for my problem.

Interesting, I downloaded image from this repo budim/selenoid-android:11.0-no-google and got the same problem

If you send me more information i will appreciate

**Comment by BorisPotapov** [comment]
@vania-pooh I have idea.

Perhaps, this example https://github.com/aerokube/images was created without Enable Nested Virtualization because it is the same problem like I solved when installed Virtual Box to Win10. 

I mean maybe default android images hasn't this config https://github.com/aerokube/images/blob/master/selenium/android/Emulator.conf#L2 and start correctly, but this example https://github.com/aerokube/images has this conf and haven't  Enable Nested Virtualization true.

What about this idea?

**Comment by vania-pooh** [comment]
@BorisPotapov older images in Docker hub don't have this config.

**Comment by BorisPotapov** [comment]
@vania-pooh I build image with showNestedWarning=true and this image start works correctly like older images. I see this Nested Virtualization popup.

Now I am sure that showNestedWarning=false works with some problems for my configuration VirtBox Ubuntu 18 + android image for win10.

**Comment by BorisPotapov** [comment]
I did it.

I just rewrote showNestedWarning=false without space and it works for me

**Comment by vania-pooh** [comment]
@BorisPotapov don't get how you fixed it.

**Comment by BorisPotapov** [comment]
I deleted extra spaces at the end

**Comment by vania-pooh** [comment]
@BorisPotapov closing then?

**Comment by BorisPotapov** [comment]
@vania-pooh yes, please :)

**Comment by BorisPotapov** [comment]
May be need to delete extra spaces at the end of https://github.com/aerokube/images/blob/master/selenium/android/Emulator.conf#L2 too.

**Comment by vania-pooh** [comment]
@BorisPotapov I don't see such spaces in raw file version. Probably that's a Windows BOM symbol.
