### ISSUE TITLE
Support `cloud:options` for options classes

### ISSUE THREAD

**Issue by symonk** [aerokube/selenoid#1167]
As of selenium `4.x` I think it is common place to store some capabilities in a `cloud:options` key.  Can we support fetching the `browserVersion` out of that for selenoid version routing?

old:

```
caps = {}
caps['browserName'] = 'firefox'
caps['platform'] = 'Windows 10'
caps['version'] = '92'
caps['build'] = my_test_build
caps['name'] = my_test_name
driver = webdriver.Remote(cloud_url, desired_capabilities=caps)
```

new:

```
from selenium.webdriver.firefox.options import Options as FirefoxOptions
options = FirefoxOptions()
options.browser_version = '92'
options.platform_name = 'Windows 10'
cloud_options = {}
cloud_options['build'] = my_test_build
cloud_options['name'] = my_test_name
options.set_capability('cloud:options', cloud_options)
driver = webdriver.Remote(cloud_url, options=options)
```

**Comment by vania-pooh** [comment]
@symonk any details about this `cloud:options` key? According to W3C standard vendors can use any key having colon(`:`) inside to store vendor-specific capabilities.

**Comment by symonk** [comment]
I may have misread actually when I revisit; `browserVersion` is W3C compliant - closing
