### ISSUE TITLE
Not able to start a webdriver session using Selenoid because of FAILED_TO_REMOVE_CONTAINER error

### ISSUE THREAD

**Issue by Arv1ndKumar** [aerokube/selenoid#1170]
Hi,

I have started a selenoid container using the following command:-

docker run -d --name selenoid -p 4444:4444 -v /root/.aerokube/selenoid/video:/opt/selenoid/video:Z -v /root/.aerokube/selenoid/logs:/opt/selenoid/logs:Z -v /var/run/docker.sock:/var/run/docker.sock:Z -v /root/.aerokube/selenoid:/etc/selenoid:ro,Z aerokube/selenoid:latest-release -timeout 10m0s -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -video-recorder-image selenoid/video-recorder:latest-release -log-output-dir /opt/selenoid/logs/ -container-network selenoid -retry-count 3 -session-attempt-timeout 1800s -session-delete-timeout 1800s

And the Selenoid container is started successfully because I can see following while using CM command:-
./cm selenoid status 

> Using Docker
- Your Docker API version is 1.40
- Using Selenoid image: aerokube/selenoid:latest-release (sha256:fdc2ce7d1eb855e9c60a75cd113c230071267603453a5506bce0373306c7e849)
- Selenoid configuration directory is /root/.aerokube/selenoid
- Selenoid configuration file is /root/.aerokube/selenoid/browsers.json
- Selenoid container is running: selenoid (ceea2479196d81f68b5e9bcb95f8834ad9851af9bf900d064226a3acc9e44f8c)

However when we hit the hub using our java code with desired capabilities , we run into following error:-
![image](https://user-images.githubusercontent.com/97246951/148423312-199605db-f46e-4f32-bbd6-08b448ffc3fa.png)

**Comment by vania-pooh** [comment]
@Arv1ndKumar either use CM tool to install everything in automated more or don't use it at all. But it seems that for some reason video recorder container does not start at all. Additional flags can be passed using `--args`:

```
$ cm selenoid start --args '-retry-count 3 -session-attempt-timeout 1800s -session-delete-timeout 1800s'
```
