### ISSUE TITLE
The video container closes immediately after launch

### ISSUE THREAD

**Issue by philipp-kochnov-stenn** [aerokube/selenoid#1171]
Installed everything as in the manual
docker run -d 
--name selenoid 
-p 4444:4444 
-v //var/run/docker.sock:/var/run/docker.sock 
-v /c/selenoid/config/:/etc/selenoid/:ro 
-v /c/selenoid/video/:/opt/selenoid/video/ 
-e OVERRIDE_VIDEO_OUTPUT_DIR=/c/selenoid/video/ 
aerokube/selenoid:latest-release

When I run my tests, the video recording container starts for just a second, and then immediately closes

2022/01/21 12:57:11 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/01/21 12:57:11 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/01/21 12:57:11 [65] [LOCATING_SERVICE] [firefox] [94.0]
2022/01/21 12:57:11 [65] [USING_DOCKER] [firefox] [94.0]
2022/01/21 12:57:11 [65] [CREATING_CONTAINER] [selenoid/vnc_firefox:94.0]
2022/01/21 12:57:11 [65] [STARTING_CONTAINER] [selenoid/vnc_firefox:94.0] [0410a2133f5b88d76c7dda2ddbf7da0dba97bf6526c0b44a162bd9e3e1c7040f]
2022/01/21 12:57:11 [65] [CONTAINER_STARTED] [selenoid/vnc_firefox:94.0] [0410a2133f5b88d76c7dda2ddbf7da0dba97bf6526c0b44a162bd9e3e1c7040f] [0.40s]
2022/01/21 12:57:11 [65] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/01/21 12:57:11 [65] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [7ed7c9c8c9042c1b10862c9abdfd5a270cd0d64ee2fda37bffd6ab9d5bfb1145]
2022/01/21 12:57:12 [65] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [7ed7c9c8c9042c1b10862c9abdfd5a270cd0d64ee2fda37bffd6ab9d5bfb1145] [0.45s]
2022/01/21 12:57:12 [65] [SERVICE_STARTED] [selenoid/vnc_firefox:94.0] [0410a2133f5b88d76c7dda2ddbf7da0dba97bf6526c0b44a162bd9e3e1c7040f] [0.10s]
2022/01/21 12:57:12 [65] [PROXY_TO] [0410a2133f5b88d76c7dda2ddbf7da0dba97bf6526c0b44a162bd9e3e1c7040f] [http://172.17.0.3:4444/wd/hub]
2022/01/21 12:57:12 [65] [SESSION_ATTEMPTED] [http://172.17.0.3:4444/wd/hub] [1]
2022/01/21 12:57:14 [65] [SESSION_CREATED] [01c3d958-aaed-4ba1-89d2-3cb50967ccdc] [1] [3.21s]
2022/01/21 12:58:00 [78] [SESSION_DELETED] [01c3d958-aaed-4ba1-89d2-3cb50967ccdc]
2022/01/21 12:58:01 [65] [STOPPING_VIDEO_CONTAINER] [7ed7c9c8c9042c1b10862c9abdfd5a270cd0d64ee2fda37bffd6ab9d5bfb1145]
2022/01/21 12:58:01 [65] [FAILED_TO_STOP_VIDEO_CONTAINER] [7ed7c9c8c9042c1b10862c9abdfd5a270cd0d64ee2fda37bffd6ab9d5bfb1145] [Error response from daemon: Cannot kill container: 7ed7c9c8c9042c1b10862c9abdfd5a270cd0d64ee2fda37bffd6ab9d5bfb1145: No such container: 7ed7c9c8c9042c1b10862c9abdfd5a270cd0d64ee2fda37bffd6ab9d5bfb1145]
2022/01/21 12:58:01 [65] [REMOVING_CONTAINER] [0410a2133f5b88d76c7dda2ddbf7da0dba97bf6526c0b44a162bd9e3e1c7040f]
2022/01/21 12:58:01 [65] [CONTAINER_REMOVED] [0410a2133f5b88d76c7dda2ddbf7da0dba97bf6526c0b44a162bd9e3e1c7040f]
2022/01/21 12:58:01 [65] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid02b2d86752ce00f0c73b21e3e8ac4f98.mp4 to /opt/selenoid/video/01c3d958-aaed-4ba1-89d2-3cb50967ccdc.mp4: rename /opt/selenoid/video/selenoid02b2d86752ce00f0c73b21e3e8ac4f98.mp4 /opt/selenoid/video/01c3d958-aaed-4ba1-89d2-

The logs show that when it comes to closing the container, it is no longer there

**Comment by vania-pooh** [comment]
@Philya-gross video recorder container is started with `--rm` flag, so that's an expected behavior if something goes wrong. I would try to get container logs when it's running.

**Comment by Philya-gross** [comment]
@vania-pooh Yes, it's this variable, but I don't understand what exactly, because if I delete it from the command, the container stops closing 2 seconds after the start. I absolutely correctly indicate the path to the folder that I created to store the video. What could be the problem?

**Comment by vania-pooh** [comment]
@Philya-gross could you show an exact Selenoid startup command then?
