### ISSUE TITLE
Selenoid locates service with a wrong address

### ISSUE THREAD

**Issue by vadpopov** [aerokube/selenoid#1172]
I'm trying to execute tests with latests versions of selenoid and chrome and seeing this:

2022/01/26 11:38:22 [13] [LOCATING_SERVICE] [chrome] [96.0]
2022/01/26 11:38:22 [13] [ENVIRONMENT_NOT_AVAILABLE] [chrome] [96.0]
2022/01/26 11:38:22 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/01/26 11:38:22 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/01/26 11:38:22 [14] [LOCATING_SERVICE] [chrome] [96.0]
2022/01/26 11:38:22 [14] [ENVIRONMENT_NOT_AVAILABLE] [chrome] [96.0]

I'm not sure but why container looks at 172.17.0.1 when i can see that chrome is running on different one...
<img width="1450" alt="Снимок экрана 2022-01-26 в 15 40 04" src="https://user-images.githubusercontent.com/49361237/151164575-c413797a-8841-47a5-8d14-2f4203601eed.png">

**Comment by vania-pooh** [comment]
@vadpopov usually this error means there is no browser version 96.0 in `browsers.json`.

**Comment by vadpopov** [comment]
@vania-pooh thanks a lot for quick response, have i added it incorrectly ?

<img width="488" alt="Снимок экрана 2022-01-26 в 16 13 31" src="https://user-images.githubusercontent.com/49361237/151169195-9bfae985-fc8e-4562-81f3-1af31bf22ec6.png">

**Comment by vania-pooh** [comment]
@vadpopov for Chrome path should be `/`. However it seems that Selenoid did not read this file at all.

**Comment by vadpopov** [comment]
@vania-pooh you were right, my browsers.json file was in private folder with only admin access. Moved config to another folder and all worked out.
