### ISSUE TITLE
android on centos

### ISSUE THREAD

**Issue by Serikxx** [aerokube/selenoid#1174]
браузеры в selenoid работают хорошо. но вот android почему то не может открыться. создавал машину centos 7 в hetzner. логи следующие:
docker logs fe4c0aedaf70
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
Waiting X server...
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
emulator: WARNING: System image is writable
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

 --- x11vnc loop: waiting for: 85

PORT=5900
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found

**Comment by vania-pooh** [comment]
@Serikxx попробуйте свои собрать из исходников. Могут ядра отличаться.
