### ISSUE TITLE
Websocket in selenoid not working when using CDP Network.emulateNetworkConditions

### ISSUE THREAD

**Issue by yasveshnikov** [aerokube/selenoid#1177]
Hello!
I tried to use CDP Network.emulateNetworkConditions with RemoteWebDriver but got problem - Websocket in selenoid not working.
But it worked locally with ChromeDriver.

I used 2 methods to connect to devtools:
- https://github.com/aerokube/chrome-developer-tools-protocol-java-example
- and from #1146

Both methods work fine with Network.setExtraHTTPHeaders

Can you help me with it?

Selenium 4.1.2 and CDP v97

**Comment by vania-pooh** [comment]
@yasveshnikov Selenoid is just proxying everything to the websocket. That's the same as going directly to browser web socket. Any details about the error?

**Comment by yasveshnikov** [comment]
Sorry, false alarm
