### ISSUE TITLE
Release docker tags for majors and minors

### ISSUE THREAD

**Issue by giggio** [aerokube/selenoid#1178]
It would help in maintenance if Selenoid and Selenoid UI had tagged images for major and major.minor versions.

For example, currently the latest released version is [1.10.7](https://hub.docker.com/layers/aerokube/selenoid/1.10.7/images/sha256-2e3b71da1f5f5302f239f806cbe9cd6010f9cd8d496d25ade74e89fde8eed1c5?context=explore). The exact same image could also be tagged `1.10` and `1`.

This would help on autoupdate scenarios, for example, if I assume the project is using semver, I could rely on the fact that there will not be breaking changes with minor version updates in version 1, simply reference `aerokube/selenoid-ui:1` and then let [Watchtower](https://containrrr.dev/watchtower/) update the container when a new version is available, without having to manualy change from `1.10.6` to `1.10.7`.

Looking at the github actions [release script](https://github.com/aerokube/selenoid/blob/master/.github/workflows/release.yml) it seems that updating https://github.com/aerokube/selenoid/blob/master/ci/docker-push.sh to support it would be enough.

Relying on the `latest-release` tag could break the app, as a version `2.x` could come out with breaking changes.

**Comment by vania-pooh** [comment]
@giggio right now we just tag images with `latest-release`.

**Comment by giggio** [comment]
Yes, I understand, my concern is a breaking change.
