### ISSUE TITLE
Can i control video record start or stop at where i want?thanks

### ISSUE THREAD

**Issue by EzrealerQAQ** [aerokube/selenoid#1180]
i want to start or stop record at anytime,can selenoid do it?thank you~

**Comment by vania-pooh** [comment]
@EzrealerQAQ not supported. Possible solution is to use custom image like this: https://github.com/presidenten/selenoid-video-api

**Comment by EzrealerQAQ** [comment]
@vania-pooh   thank you for so quick and useful anwser,i'll try it
