### ISSUE TITLE
i want to know how the selenoid/vnc:chrome docker container start

### ISSUE THREAD

**Issue by EzrealerQAQ** [aerokube/selenoid#1181]
i want to start a selenoid/chrome docker container manually and then i can see it in selenoid-ui,how can i do it? when i user webdriver to connect ip:4444,how the selenoid/vnc:chrome docker container start,thank you

**Comment by vania-pooh** [comment]
```
$ docker run -d -p 4444:4444 --privileged selenoid/vnc_chrome:97.0
```

**Comment by vania-pooh** [comment]
@EzrealerQAQ use any other port, e.g. `-p 4445:4444`.
