### ISSUE TITLE
AWS -  Cloudformation fargate Selenoid configurations

### ISSUE THREAD

**Issue by vinothvasu5300** [aerokube/selenoid#1182]
I am trying to run the selenium automated scripts in AWS Cloudformation - Fargate - Selenoid. However I didn't know the configurations which we need to pass in .yml or json file. Can you please help with this.

**Comment by vania-pooh** [comment]
@vinothvasu5300 we personally have no experience with Fargate. Don't use Selenoid with Fargate EKS: https://aerokube.com/selenoid/latest/#_selenoid_in_kubernetes Probably it will work with Fargate ECS.

**Comment by vinothvasu5300** [comment]
Thanks for the response @vania-pooh
