### ISSUE TITLE
AWS ECS Selenoid commands 

### ISSUE THREAD

**Issue by vinothvasu5300** [aerokube/selenoid#1184]
In my local machine below command successfully invokes Selenoid. 

docker run -d --name selenoid -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v **/E/selenoid/config/**:/etc/selenoid/:ro -v /E/selenoid/video/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_OUTPUT_DIR=/E/selenoid/video/ aerokube/selenoid:latest 

However while trying to run the same in AWS ECS I am not sure how to mount the browsers.json to /etc/selenoid/. ECS logs shows "/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory"

Can you please help with the commands which I can use in AWS - ECS ?

**Comment by vania-pooh** [comment]
@vinothvasu5300 you can put `browsers.json` anywhere on the host, e.g. to `/your/path/browsers.json`. Inside Selenoid container path is hard-coded to `/etc/selenoid`. So path could be mounted as `-v /your/path:/etc/selenoid`.

**Comment by vinothvasu5300** [comment]
@vania-pooh  Is it possible to spin the container without the below command. so that the container can run with default browsers configurations

-v /your/path:/etc/selenoid.

**Comment by vania-pooh** [comment]
@vania-pooh under Linux `cm` tool should work.

**Comment by vania-pooh** [comment]
@vinothvasu5300 you can pass any value to `-v` flag.

**Comment by vinothvasu5300** [comment]
Thanks for your response @vania-pooh
