### ISSUE TITLE
VNC is not enabled for Selenoide test run c# selenium

### ISSUE THREAD

**Issue by DenisSokol** [aerokube/selenoid#1187]
I'm trying to run UI test with selenoid in docker container. Once I connect to http://localhost:8080/ i'm seeing just window with logs of created session but I don't see the browser window itself even though enableVNC is set to true

```
ChromeOptions chromeOptions = new ChromeOptions();
                                    
chromeOptions.AddAdditionalOption("enableVNC",  true);
                                    
chromeOptions.AddAdditionalOption("enableVideo", true);
```
![Screenshot_14](https://user-images.githubusercontent.com/9582784/156333613-9c3ab174-efe0-4bbe-9fcb-b3d0cdc8a3db.png)
![Screenshot_15](https://user-images.githubusercontent.com/9582784/156333621-e7960633-0592-4627-a662-59c4605e98ae.png)
![InkedScreenshot_16](https://user-images.githubusercontent.com/9582784/156349918-6fe24ecf-3212-4994-8477-9f53c428813c.jpg)

I've tried also this way:
```

chromeOptions.AddAdditionalCapability("enableVNC",  true, true);
                            
chromeOptions.AddAdditionalCapability("enableVideo", true, true);
```
but no luck.

Am i missing smth to view the browser window session? Any help is much appreciated

**Comment by Anticope12** [comment]
Hi @DenisSokol , Try to add : "selenoid:options": 

Use it like that: 

        capabilities = {"browserName": "chrome", "version": "100.0",
                         "selenoid:options": {"screenResolution": "1280x1024x24", "enableVNC": True}}
