### ISSUE TITLE
Not able to launch browser - getting msg env not availaible 

### ISSUE THREAD

**Issue by Himani1519** [aerokube/selenoid#1188]
Whenever tried to run selenoid its gives error [ENVIRONMENT_NOT_AVAILABLE] [chrome] []

2022/02/28 16:57:08 [-] [INIT] [Loading configuration files...]
2022/02/28 16:57:08 [-] [INIT] [Loaded configuration from C:\Users\hpathak\.aerokube\selenoid\browsers.json]
2022/02/28 16:57:08 [-] [INIT] [Timezone: Local]
2022/02/28 16:57:08 [-] [INIT] [Listening on :4444]
2022/02/28 17:06:43 [-] [NEW_REQUEST] [unknown] [::1]
2022/02/28 17:30:18 [-] [NEW_REQUEST_ACCEPTED] [unknown] [::1]
2022/02/28 17:30:18 [0] [LOCATING_SERVICE] [chrome] []
2022/02/28 17:30:18 [0] [ENVIRONMENT_NOT_AVAILABLE] [chrome] []

**Comment by vania-pooh** [comment]
@Himani1519 you don't have browser `chrome` in your `browsers.json`.

**Comment by riraga001m** [comment]
@vania-pooh 
This is how my browsers.json is,
Is something missing. Please help. chrome and msedge work fine
![image](https://user-images.githubusercontent.com/93780328/157748441-0fbf7d9d-b56b-4331-afbc-66bfff28b0e7.png)
