### ISSUE TITLE
 Cannot open display browser:99, error 1. browser:99: I/O error

### ISSUE THREAD

**Issue by EzrealerQAQ** [aerokube/selenoid#1189]
when i run webdriver.Remote() in my program for some times ,the first few times success,after 3 or more times，errors as follows:

program error:
selenium.common.exceptions.SessionNotCreatedException: Message: wait: http://172.17.0.2:4444/ does not respond in 1m0s

selenoid contaioner logs:
2022/03/09 04:17:55 [948] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.2:4444/ does not respond in 1m0s]

video_record container logs:

Sleeping before next attempt...
Sleeping before next attempt...
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --prefix=/usr --enable-avfilter --enable-gpl --enable-libx264 --enable-libpulse --enable-static --enable-small --disable-ffplay --disable-ffprobe --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --disable-alsa --disable-audiotoolbox --disable-cuda --disable-cuvid --disable-d3d11va --disable-dxva2 --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-librtmp --disable-devices --enable-indev=xcbgrab --enable-indev=pulse --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[x11grab @ 0x7ff23a8633c0] Cannot open display browser:99, error 1.
browser:99: I/O error

need help,thanks a lot

**Comment by vania-pooh** [comment]
@EzrealerQAQ need browser container logs.

**Comment by vania-pooh** [comment]
@EzrealerQAQ probably your cluster is just overloaded.

**Comment by EzrealerQAQ** [comment]
@vania-pooh deploy stand alone by docker,ram 200G+ left，cpu 1.7 used ，storage 5T left, i'll try to deploy in a new server

**Comment by EzrealerQAQ** [comment]
but it seems the reson of error is about ffmpeg or x11grap as
[x11grab @ 0x7ff23a8633c0] Cannot open display browser:99, error 1.
browser:99: I/O error

**Comment by vania-pooh** [comment]
@EzrealerQAQ video recorder is unable to access X server because it does not start for some reason. X server is anyway started in browser container. These messages `Waiting X server...` should take 1-2 seconds maximum. Probably you are also running Selenoid in some restricted environment.

**Comment by EzrealerQAQ** [comment]
@vania-pooh thank you very much,i can't find what to prevent X server from start,maybe a new clear server would work...

**Comment by vania-pooh** [comment]
@EzrealerQAQ we are testing everything under Ubuntu. in case of using CentOS probably turning off SELinux can help.

**Comment by EzrealerQAQ** [comment]
@vania-pooh i use centos7, 
[root@ezrealer selenoid]# getenforce
Disabled
and anthor new clear server also don't work...

**Comment by EzrealerQAQ** [comment]
@vania-pooh 
i add try as follows:
        while True:
            try:
                driver = webdriver.Remote(command_executor=command_executor,
                                          desired_capabilities=capabilities, options=self.options)
                break
            except Exception as e:
                print(e)
                time.sleep(1)
every try could  success,so strange...

**Comment by EzrealerQAQ** [comment]
i add try to my program

```python
        while True:
            try:
                driver = webdriver.Remote(command_executor=command_executor,
                                          desired_capabilities=capabilities, options=self.options)

                break
            except Exception as e:
                print(e)
                time.sleep(1)
```

every try could success,so strange....

**Comment by vania-pooh** [comment]
@EzrealerQAQ try under Ubuntu is possible.
