### ISSUE TITLE
Failed to pull image : Error response from daemon: toomanyrequests: 

### ISSUE THREAD

**Issue by ananthraj007** [aerokube/selenoid#1191]
Failed to pull image "aerokube/selenoid:1.10.7": Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 

Solutions we have tried so far.

1. We have purchased a Pro account and use Docker Login command  before pulling aerokube/selenoid image. 
As selenoid directly talks to Docker API **how can we make selenoid use those credentials while pulling the images from Docker Hub.**

2. We hosted all the images in our own Docker registry and tried to pull the images from that registry. **But selenoid by default pulling the images from Docker HUB - How to change this behavior ?**

> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
**registry.ping url=https://index.docker.io/v2/**
registry.tags url=https://index.docker.io/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid

**Comment by vania-pooh** [comment]
@ananthraj007 Selenoid is not pulling images automatically. It's expecting that they are pulled by some other tool.

**Comment by ananthraj007** [comment]
okay in that case cm is trying to pull the images

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /root/.docker:/root/.docker/ -v ~/.aerokube/selenoid:/root/.aerokube/selenoid nexus-docker-anonymous.XXXXXX.com/aerokube/cm:${SELENOID_CONFIGURATION_MANAGER_VERSION} selenoid start -conf ./browsers.json --shm-size 2048 --tmpfs 1024 --args "-timeout 50m"
Unable to find image 'nexus-docker-anonymous.XXXXXXXX.com/aerokube/cm:latest-release' locally
latest-release: Pulling from aerokube/cm
339de151aab4: Pulling fs layer
be1dcee63452: Pulling fs layer
fee4a2e26675: Pulling fs layer
be1dcee63452: Verifying Checksum
be1dcee63452: Download complete
339de151aab4: Verifying Checksum
339de151aab4: Download complete
fee4a2e26675: Verifying Checksum
fee4a2e26675: Download complete
339de151aab4: Pull complete
be1dcee63452: Pull complete
fee4a2e26675: Pull complete
Digest: sha256:0f94706064e0618ce0489005ab6ca6f1a48f31d04fb74e8dc3b7bc097bbfc465
Status: Downloaded newer image for nexus-docker-anonymous.rwts-tools.com/aerokube/cm:latest-release
> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://index.docker.io/v2/
registry.tags url=https://index.docker.io/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.10.7
x Failed to pull image "aerokube/selenoid:1.10.7": Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by vania-pooh** [comment]
@ananthraj007 please use CM as a binary for your platform. In that case CM will read your local authentication settings from `~/.docker/`. When running the same as container, config files don't get mounted to container.

**Comment by ananthraj007** [comment]
As you can see we are mounting the config file to container using -v /root/.docker:/root/.docker/

**Comment by vania-pooh** [comment]
@ananthraj007 this was never tested.

**Comment by vania-pooh** [comment]
@ananthraj007 

1) Using Selenoid is container is OK and is recommended. Using CM is container is too complicated and error-prone according to our experience. You can even start Selenoid without using CM tool at all (just with regular `docker run` command).

2) CM binary is reading this information here: https://github.com/aerokube/cm/blob/8d351c8fc84937913d5059d797d422d496d2c723/selenoid/docker.go#L150-L170 You just need to provide your registry with `--registry` flag.

**Comment by ananthraj007** [comment]
Thanks @vania-pooh  --registry worked. At least now we have a workaround to the issue.

**Comment by vania-pooh** [comment]
@ananthraj007 this is not a workaround. This is how it expected to work.

**Comment by ananthraj007** [comment]
@vania-pooh  It is work around for actual issue "Failed to pull image : Error response from daemon: toomanyrequests:"  

Expected behavior : cm should be able to authenticate to Docker Hub! --> any other flag to pass credentials to cm ?

**Comment by vania-pooh** [comment]
@ananthraj007 as I said these credentials are also read from Docker config file, so should just work when you do `docker login` before using CM on the same machine.

**Comment by ananthraj007** [comment]
@vania-pooh  I as mentioned in the first comment we have tried using Docker Login command and share to Docker config to cm container but it is not working.

**Comment by Tarasovych** [comment]
Same issue, `docker login` doesn't affect cm to use credentials

**Comment by vania-pooh** [comment]
@Tarasovych it depends on the command you are using to run CM. Usually Docker credentials are stored under `~/.docker/config.json`, so CM will read everything from this file.

**Comment by Tarasovych** [comment]
@vania-pooh what if they're stored under `/root/.docker/config.json`?

**Comment by Tarasovych** [comment]
I've built `cm` from source, added some debug to https://github.com/aerokube/cm/blob/1.8.2/selenoid/docker.go#L200, and I see that `configFile` is being read correctly. For some reason I still get rate limit error

**Comment by Tarasovych** [comment]
In my case `host` in `config.json` is `https://index.docker.io/v1/`. I'm getting `index.docker.io` in [`registryHost`](https://github.com/aerokube/cm/blob/master/selenoid/docker.go#L210), so [`configFile.AuthConfigs[registryHost]`](https://github.com/aerokube/cm/blob/master/selenoid/docker.go#L214) is empty

**Comment by dvdrbn-m9** [comment]
Having this issue as well. Running from root account, so docker credentials are at `/root/.docker/config.json` and it seems `docker login` doesn't affect `cm`. We're using docker hub registry, so `--registry` shouldn't be needed and regular pulls do work of course.
Is there any solution for this or some kind of workaround?
