### ISSUE TITLE
IE: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by riraga001m** [aerokube/selenoid#1192]
When I run tests on IE, browser opens, launches the url then test fails. 
Here are the errors I see.

**Selenoid logs:**
2022/03/10 16:02:28 [2] [STARTING_PROCESS] [[C:\selenoid\IEDriverServer.exe --log-level=DEBUG --whitelisted-ips --port=63406]]
2022/03/10 16:02:29 [2] [PROCESS_STARTED] [7424] [0.56s]
2022/03/10 16:02:29 [2] [PROXY_TO] [http://127.0.0.1:63406]
2022/03/10 16:02:29 [2] [SESSION_ATTEMPTED] [http://127.0.0.1:63406] [1]
2022/03/10 16:02:31 [2] [SESSION_CREATED] [98d5dc6c-888f-4cc9-aba4-09a727ebbd61] [1] [2.53s]
2022/03/10 16:03:31 [4] [SESSION_TIMED_OUT] [98d5dc6c-888f-4cc9-aba4-09a727ebbd61]
2022/03/10 16:03:31 [5] [SESSION_DELETED] [98d5dc6c-888f-4cc9-aba4-09a727ebbd61]
2022/03/10 16:03:31 [4] [CLIENT_DISCONNECTED] [unknown] [127.0.0.1] [Error: read tcp 127.0.0.1:63408->127.0.0.1:63406: wsarecv: An existing connection was forcibly closed by the remote host.]
2022/03/10 16:03:31 [5] [CLIENT_DISCONNECTED] [unknown] [127.0.0.1] [Error: read tcp 127.0.0.1:63461->127.0.0.1:63406: wsarecv: An existing connection was forcibly closed by the remote host.]
2022/03/10 16:03:31 [2] [TERMINATING_PROCESS] [7424]
2022/03/10 16:03:31 [4] [DELETE_FAILED] [98d5dc6c-888f-4cc9-aba4-09a727ebbd61] [502 Bad Gateway]
2022/03/10 16:03:31 [2] [FAILED_TO_TERMINATE_PROCESS] [7424] [TerminateProcess: Access is denied.]

**When I debug Test and see Exception as below:** [Masked sensitive info]

org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XXXX', ip: 'XXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
selenide.remote: http://localhost:4444/wd/hub
Driver info: driver.version: SelenideDriver
selenide.url: https://XXXXX
selenide.baseUrl: http://localhost:8080

NOTE: Chrome and msEdge work fine

**Comment by vania-pooh** [comment]
@riraga001m I think this is related to security \ firewall settings.

**Comment by riraga001m** [comment]
Thank you will check on that.

**Comment by riraga001m** [comment]
Hi @vania-pooh 
Thanks for pointing the security issue.
That was org level firewall issue and it is fixed now.
