### ISSUE TITLE
IE: Unable to run tests on IE

### ISSUE THREAD

**Issue by riraga001m** [aerokube/selenoid#1196]
When I run tests on IE,
Browser opens, and then tests fails with "java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first."

**Selenoid Logs are as below**

2022/03/18 12:33:14 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2022/03/18 12:33:14 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2022/03/18 12:33:14 [1] [LOCATING_SERVICE] [internet explorer] [11]
2022/03/18 12:33:14 [1] [USING_DRIVER] [internet explorer] [11]
2022/03/18 12:33:14 [1] [ALLOCATING_PORT]
2022/03/18 12:33:14 [1] [ALLOCATED_PORT] [54965]
2022/03/18 12:33:14 [1] [STARTING_PROCESS] [[C:\selenoid\IEDriverServer.exe --log-level=DEBUG --whitelisted-ips --port=54965]]
I 2022-03-18 12:33:14:297 C:\Projects\selenium\cpp\webdriver-server\server.cc(88) Starting WebDriver server on port: '54965' on host: ''
I 2022-03-18 12:33:14:298 C:\Projects\selenium\cpp\iedriver\IEServer.cpp(33) Driver version: 4.0.0.0 (64-bit)
Started InternetExplorerDriver server (64-bit)
4.0.0.0
Listening on port 54965
Log level is set to DEBUG
Only local connections are allowed
2022/03/18 12:33:14 [1] [PROCESS_STARTED] [21344] [0.60s]
2022/03/18 12:33:14 [1] [PROXY_TO] [http://127.0.0.1:54965]
2022/03/18 12:33:14 [1] [SESSION_ATTEMPTED] [http://127.0.0.1:54965] [1]
D 2022-03-18 12:33:14:767 C:\Projects\selenium\cpp\webdriver-server\server.cc(343) Command: POST /session {"capabilities":{"firstMatch":[{"browserName":"internet explorer","pageLoadStrategy":"normal","se:ieOptions":{}}]},"desiredCapabilities":{"acceptSslCerts":true,"browserName":"internet explorer","enableVNC":true,"handlesAlerts":true,"javascriptEnabled":true,"pageLoadStrategy":"normal","se:ieOptions":{},"takesScreenshot":true,"version":"11"}}
D 2022-03-18 12:33:14:767 C:\Projects\selenium\cpp\iedriver\IESession.cpp(60) Mutex acquired for session initalization
D 2022-03-18 12:33:14:777 C:\Projects\selenium\cpp\iedriver\IESession.cpp(116) Releasing session initialization mutex
D 2022-03-18 12:33:14:778 C:\Projects\selenium\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"capabilities":{"firstMatch":[{"browserName":"internet explorer","pageLoadStrategy":"normal","se:ieOptions":{}}]},"desiredCapabilities":{"acceptSslCerts":true,"browserName":"internet explorer","enableVNC":true,"handlesAlerts":true,"javascriptEnabled":true,"pageLoadStrategy":"normal","se:ieOptions":{},"takesScreenshot":true,"version":"11"}} }
D 2022-03-18 12:33:14:778 C:\Projects\selenium\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"capabilities":{"firstMatch":[{"browserName":"internet explorer","pageLoadStrategy":"normal","se:ieOptions":{}}]},"desiredCapabilities":{"acceptSslCerts":true,"browserName":"internet explorer","enableVNC":true,"handlesAlerts":true,"javascriptEnabled":true,"pageLoadStrategy":"normal","se:ieOptions":{},"takesScreenshot":true,"version":"11"}} }
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\IECommandExecutor.cpp(1039) Executing command: newSession
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(48) Found W3C capabilities structure
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(199) Validating alwaysMatch capability set
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(673) Validating capabilities object
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(220) Validating firstMatch capability set with index 0
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(673) Validating capabilities object
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(722) Found browserName capability. Validating value type is string.
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(797) Found pageLoadStrategy capability. Validating value type is string.
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(807) Validating pageLoadStrategy capability is a valid value.
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(989) Found se:ieOptions capability. Validating value type is object.
D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(279) Processing matched capability set with index 0
W 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\CommandHandlers\NewSessionCommandHandler.cpp(105) Invalid capability setting: timeouts is type null instead of object. Default value will be used: null

D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(128) path before was 

D 2022-03-18 12:33:14:779 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(130) path after was 000001BEDC0CCFA0

D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(154) Ignoring Protected Mode Settings: 0
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(157) Checking validity of Protected Mode settings.
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1301) Detected IE version: 11, Windows version supports Protected Mode: 1
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1392) Found Protected Mode setting value of 0 for zone 1
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1392) Found Protected Mode setting value of 0 for zone 2
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1392) Found Protected Mode setting value of 0 for zone 3
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1392) Found Protected Mode setting value of 0 for zone 4
D 2022-03-18 12:33:14:780 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(160) Has Valid Protected Mode Settings: 1
D 2022-03-18 12:33:14:788 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(258) Starting IE using the IELaunchURL API
D 2022-03-18 12:33:15:257 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(212) IE launched successfully with process ID 6272
D 2022-03-18 12:33:15:257 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(218) Process with ID 6272 is executing iexplore.exe
D 2022-03-18 12:33:15:257 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(487) Using Active Accessibility to find IWebBrowser2 interface
D 2022-03-18 12:33:15:258 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1145) Looking for 6272
D 2022-03-18 12:33:15:513 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1145) Looking for 6272
D 2022-03-18 12:33:15:767 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1145) Looking for 6272
D 2022-03-18 12:33:15:881 C:\Projects\selenium\cpp\webdriver-server\server.cc(343) Command: GET /favicon.ico {}
D 2022-03-18 12:33:15:881 C:\Projects\selenium\cpp\webdriver-server\server.cc(426) Response: {
	"value" : 
	{
		"error" : "unknown command",
		"message" : "Command not found: GET /favicon.ico",
		"stacktrace" : ""
	}
}
D 2022-03-18 12:33:16:033 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1145) Looking for 6272
D 2022-03-18 12:33:16:034 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(1145) Looking for 6272
D 2022-03-18 12:33:16:034 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(565) Found window handle 0000000000030E04 for window with class 'Internet Explorer_Server' belonging to process with id 6272
D 2022-03-18 12:33:16:104 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(508) Ignoring zoom setting: 0
D 2022-03-18 12:33:16:154 C:\Projects\selenium\cpp\iedriver\BrowserFactory.cpp(829) Browser zoom level is 100%
I 2022-03-18 12:33:16:157 C:\Projects\selenium\cpp\iedriver\IECommandExecutor.cpp(1584) Persistent hovering set to: 1
D 2022-03-18 12:33:16:157 C:\Projects\selenium\cpp\iedriver\ProxyManager.cpp(119) Using existing system proxy settings.
2022/03/18 12:33:44 [1] [SESSION_ATTEMPT_TIMED_OUT] [30s]
2022/03/18 12:33:44 [1] [SESSION_FAILED] [http://127.0.0.1:54965] [New session attempts retry count exceeded]
2022/03/18 12:33:44 [1] [TERMINATING_PROCESS] [21344]
2022/03/18 12:33:44 [1] [TERMINATED_PROCESS] [21344] [0.02s]

**Comment by vania-pooh** [comment]
@riraga001m try to remove `enableVNC` capability. According to W3C standard it should live under `selenoid:options`.

**Comment by riraga001m** [comment]
[Selenoid_debug.txt](https://github.com/aerokube/selenoid/files/8326080/Selenoid_debug.txt)

**Comment by riraga001m** [comment]
IE is no more Valid
