### ISSUE TITLE
Unable to start an electron session

### ISSUE THREAD

**Issue by GolubNick** [aerokube/selenoid#1198]
Hi @vania-pooh.  The error 'create gzip reader: gzip: invalid header' appears when trying to start the electron image. I use the latest version of image browsers/cypress-electron:latest.
Could you help me to resolve this issue, please?

**Comment by vania-pooh** [comment]
@GolubNick Cypress images work in Moon only.

**Comment by GolubNick** [comment]
So, I won't be able to run electron tests on Selenoid, isn't it? Is there some opportunity to run an electron session on Selenoid?

**Comment by vania-pooh** [comment]
@GolubNick we never tried.

**Comment by GolubNick** [comment]
Hi @vania-pooh . I've tried to create an electron image myself to run electron tests in Selenoid. I've took a Dockerfile from thia https://github.com/aerokube/images/tree/master/static/chrome/Dockerfile like the foundation and added some command to install an electron application. Docker image is built successfully but when  try to create session in Selenoid the error is caught
'value: {error: "session not created", message: "session not created: No matching capabilities found",…}
error: "session not created"
message: "session not created: No matching capabilities found"
stacktrace: "#0 0x5601c1773b33 <unknown>\n#1 0x5601c123c6d8 <unknown>\n#2 0x5601c1295115 <unknown>\n#3 0x5601c1294536 <unknown>\n#4 0x5601c1295b9d <unknown>\n#5 0x5601c128ff53 <unknown>\n#6 0x5601c1265a0a <unknown>\n#7 0x5601c1266ad5 <unknown>\n#8 0x5601c17a52fd <unknown>\n#9 0x5601c17be4bb <unknown>\n#10 0x5601c17a70d5 <unknown>\n#11 0x5601c17bf145 <unknown>\n#12 0x5601c179aaaf <unknown>\n#13 0x5601c17dbba8 <unknown>\n#14 0x5601c17dbd28 <unknown>\n#15 0x5601c17f648d <unknown>\n#16 0x7f0c389fb6db <unknown>\n"'.
Also this error is appear when I try to build docker image from Dockerfile above without my changes. 
Could you help me please? Maybe Docekrfile that I've choosen is incorrect? Thank you.
