### ISSUE TITLE
Не загружаются файлы в /home/selenium/Downloads

### ISSUE THREAD

**Issue by tikhomirov-zyfra** [aerokube/selenoid#1199]
Господа, всем добрый день.

Прошу прощения, что на русском. Хотел бы попросить вашей помощи в решении моего вопроса.

1. Машина, где запускаются тесты - Windows 10, тесты на Python.

2. Есть удалленый Selenoid - Linux e1d6054872aa 5.8.0-1043-azure 46~20.04.1-Ubuntu SMP

Запускается браузер в контейнере. Я пытаюсь скачать файл в папочку /home/selenium/Downloads, но у пользователя selenium не хватает прав для записи в эту папку. К примеру, в /home/selenium сохранить файл я могу, но тогда, насколько я понимаю, я не смогу его получить, т.к. запрос GET http://selenoid-host.example.com:4444/download/f2bcd32b-d932-4cdc-a639-687ab8e4f840/?json вернет список файлов именно в папочке ~Downloads.

Конфиг у меня такой:
![Screenshot_1](https://user-images.githubusercontent.com/84173562/159416164-29a74b34-a622-44a4-af32-28ca9a0a84bb.png)

browsers.json
![Screenshot_1](https://user-images.githubusercontent.com/84173562/159433065-eaa16aba-98f5-4d93-be2e-9212ddedc9b0.png)

Подскажите, пожалуйста, как же все-таки можно решить проблему? Как мне сохранять файлы в папку /home/selenium/Downloads?

P.S. когда я поднимаю контейнер с Селеноидом на своей машине и делаю запуск в нем, то файл успешно скачивается в папку /home/selenium/Downloads

**Comment by vania-pooh** [comment]
@tikhomirov-zyfra может какой-нибудь SELinux надо отключить? Что там за операционная система?

**Comment by tikhomirov-zyfra** [comment]
@vania-pooh большое спасибо Вам за быстрый ответ.
ОС:
![Screenshot_2](https://user-images.githubusercontent.com/84173562/159455581-6fd9e347-f853-4417-bde2-b453d6648541.png)

SELinux нет

**Comment by tikhomirov-zyfra** [comment]
В контейнере с браузером:
![Screenshot_3](https://user-images.githubusercontent.com/84173562/159457123-8faeb8de-6298-4906-add1-5a338dfebbb3.png)

**Comment by tikhomirov-zyfra** [comment]
В контейнере с браузером: 
![Screenshot_4](https://user-images.githubusercontent.com/84173562/159457700-20516e98-751f-4366-b480-92cb4febf740.png)

**Comment by tikhomirov-zyfra** [comment]
@vania-pooh Иван, прошу прощения, что отнял время. оказывается, что папка ~Downloads монтировалась к папке, к которой нет доступа, поэтому и не сохранялось.
Большое спасибо за помощь!

**Comment by markindim** [comment]
> @vania-pooh Иван, прошу прощения, что отнял время. оказывается, что папка ~Downloads монтировалась к папке, к которой нет доступа, поэтому и не сохранялось. Большое спасибо за помощь!

Добрый день! 
Как в итоге решили проблему ?
