### ISSUE TITLE
Add option to disable queueing

### ISSUE THREAD

**Issue by bashlakov** [aerokube/selenoid#120]
Hi! 

When using Selenoid with GGR we observe that load on some node is much more than on others. In that case session queueing prevent GGR to skip overloaded node and redirect session to another Selenoid node. I think disabling queueing and rejecting overlimited session by Selenoid will force GGR to select another node and will provide more fair load-balancing.

**Comment by vania-pooh** [comment]
@bashlakov instead of completely disabling queues - which will lead to hardware overload - just use Ggr `-timeout` flag allowing to specify max new session request timeout. Default timeout is 300 seconds but you may want to set shorter value - e.g. 10 seconds.
```
# docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro --net host aerokube/ggr:1.1.1 -timeout 10s
```

**Comment by vania-pooh** [comment]
@bashlakov any updates? You can also ask questions online in our Telegram channel: https://telegram.me/aerokube

**Comment by bashlakov** [comment]
To summarise conversation in telegram: disable queueing should not be equal to limit=infinity, but rather return 503 error if number of serving sessions (active and pending) reach the limit value. This will force ggr to skip this node without waiting for timeout and will provide more fair and fast node selecting mechanism. Because this behaviour break capability with selenoid-hub, I think this feature should be enabled via appropriate command-line flag (e.g. --disable-queue).

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/selenoid/commit/4762ee186c912a64cf6d99ba2d061ca919eed213.
