### ISSUE TITLE
How to use the Solenoid in the bitbucket pipeline?

### ISSUE THREAD

**Issue by SpardaVk** [aerokube/selenoid#1201]
I am trying to run my tests in bitbucket and have encountered difficulties using selenoid there

"x Failed to start: failed to create container: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories"
![image](https://user-images.githubusercontent.com/45706626/159713603-a7eabea3-2634-4c7b-a426-b5f54a29147e.png)
Can you tell me how to properly configure selenoid to run?

https://community.atlassian.com/t5/Bitbucket-questions/How-to-run-selenide-tests-in-bitbucket-pipelines-selenoid/qaq-p/1976114

**Comment by vania-pooh** [comment]
Probably you just need to use browser images directly.
