### ISSUE TITLE
Incorrect status code in case of "Too many requests" response

### ISSUE THREAD

**Issue by eGavr** [aerokube/selenoid#1203]
Selenoid version: 1.10.7
Broken since selenoid version: 1.10.7
Run selenoid with options `-disable-queue -limit 5`

Current behaviour:
```
If queue is full selenoid returns an unknown error with status code 500
```

Expected behaviour:
```
If queue is full selenoid returns an error with status code 429 (too many requests)
```

--------

JFYI. In out team we've hacked the problem [this](https://github.com/gemini-testing/selenoid/commit/118797e115faa9fe1c9f331a324e4eed1e060951) way.

**Comment by vania-pooh** [comment]
@eGavr no such status code in W3C standard. https://www.w3.org/TR/webdriver/#errors

**Comment by eGavr** [comment]
> @eGavr no such status code in W3C standard. https://www.w3.org/TR/webdriver/#errors

Yes, you are right.

But how can we determine that the error reason is "Too many requests"? This value is in error message, but I think relying for this value in error message is not a good idea.

**Comment by eGavr** [comment]
The full error is

```
{"name":"HTTPError","hostname":"127.0.0.1","method":"POST","path":"/wd/hub/session","protocol":"http:","url":"http://127.0.0.1:4444/wd/hub/session","gotOptions":{"path":"/wd/hub/session","protocol":"http:","hostname":"127.0.0.1","hash":"","search":"","pathname":"/wd/hub/session","href":"http://127.0.0.1:4444/wd/hub/session","port":4444,"retry":{"methods":{},"statusCodes":{},"errorCodes":{},"maxRetryAfter":60001},"headers":{"user-agent":"@yandex-int/si.ci.requests@3.0.12","accept":"application/json","accept-encoding":"gzip, deflate","content-type":"application/json","x-request-id":"27a71ca75354ec64b0f3706bce94200c","content-length":107},"hooks":{"beforeError":[],"init":[],"beforeRequest":[],"beforeRedirect":[],"beforeRetry":[],"afterResponse":[]},"decompress":true,"throwHttpErrors":true,"followRedirect":true,"stream":false,"form":false,"json":true,"cache":false,"useElectronNet":false,"nonRetriableStatusCodes":[],"retryCount":4,"applyMaxRetryTotalTimeBeforeRetry":true,"truncateResponseBodyLogAfter":500,"gotTimeout":{"request":60001},"method":"POST","baseUrl":"http://127.0.0.1:4444/","body":"{\"desiredCapabilities\":{\"screenResolution\":\"1600x1200x24\",\"browserName\":\"firefox\",\"browserVersion\":\"95.0\"}}"},"statusCode":500,"statusMessage":"Internal Server Error","headers":{"content-type":"application/json; charset=utf-8","date":"Mon, 28 Mar 2022 13:55:57 GMT","content-length":"62","connection":"close","x-request-id":"27a71ca75354ec64b0f3706bce94200c"},"body":{"value":{"error":"unknown error","message":"Queue Is Full"}}}
```

"unknown error" is not concrete error which cannot be associated with the original reason about "Queue Is Full"

**Comment by vania-pooh** [comment]
@eGavr probably we can introduce a new error code that is not included to the standard.

**Comment by eGavr** [comment]
Until version 1.10.7 selenoid has an error that is not included to the standard, and this error was with status code 459 :)

**Comment by aandryashin** [comment]
That error code needs only for ggr, and can be disabled by command line
option. Selenoid was developed when w3c standard did not exist.

вт, 29 мар. 2022 г., 10:46 Evgeniy Gavryushin ***@***.***>:
