### ISSUE TITLE
@EzrealerQAQ this was working previously out of the box but now it's broken for some reason.

### ISSUE THREAD

**Issue by EzrealerQAQ** [aerokube/selenoid#1212]
@EzrealerQAQ this was working previously out of the box but now it's broken for some reason.

_Originally posted by @vania-pooh in https://github.com/aerokube/selenoid/issues/1197#issuecomment-1074122500_

which version of video-recorder image support audio record,thank you very much

**Comment by vania-pooh** [comment]
Duplicated of #1197.
