### ISSUE TITLE
org.openqa.selenium.InvalidArgumentException: Requested environment is not available

### ISSUE THREAD

**Issue by aravindraveendran7** [aerokube/selenoid#1214]
Hi Guys, I tried to launch selenoid  tests on windows machine withcontainers, using selenoid . I have following browsers.json:
`{
    "chrome": {
        "default": "100.0",
        "versions": {
            "100.0": {
                "image": "selenoid/vnc_chrome:100.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "84.0": {
                "image": "selenoid/vnc_chrome:84.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "firefox": {
        "default": "77.0",
        "versions": {
            "77.0": {
                "image": "selenoid/vnc_firefox:77.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "78.0": {
                "image": "selenoid/vnc_firefox:78.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    }
}`

ran the command docker run -d --name selenoid -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v ${current}/config/:/etc/selenoid/:ro -v /c/Users/test/selenoid/video/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/test/selenoid/video/ aerokube/selenoid:latest
and got the logs as below:
2022/04/26 15:26:32 [-] [INIT] [Loading configuration files...]
2022/04/26 15:26:32 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2022/04/26 15:26:32 [-] [INIT] [Video Dir: /opt/selenoid/video]
2022/04/26 15:26:32 [-] [INIT] [Your Docker API version is 1.41]
2022/04/26 15:26:32 [-] [INIT] [Timezone: UTC]
2022/04/26 15:26:32 [-] [INIT] [Listening on :4444]

my sample test code:
`public class TestPg {

    @Test
    public void test2() throws InterruptedException, MalformedURLException {
        DesiredCapabilities dc=new DesiredCapabilities();
        dc.setBrowserName("chrome");
        dc.setVersion("100.0");
        WebDriver driver=new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),dc);
        driver.get("https://www.google.in");
        System.out.println(driver.getTitle());
        Thread.sleep(100000);
        driver.quit();
    }
}
`
once the test is triggered from intellij it throws the error Requested environment is not available. Am I missing any steps. Please advise.

**Comment by vania-pooh** [comment]
@aravindraveendran7 make sure you are editing correct `browsers.json` file. It seems that you don't have `Chrome 100.0` in really used `browsers.json`.

**Comment by aravindraveendran7** [comment]
Could you please elaborate more.. as i could see selenoid/vnc_chrome:100.0 in my browsers.json..

**Comment by vania-pooh** [comment]
@aravindraveendran7 e.g. `docker exec selenoid cat /etc/browsers.json`.

**Comment by aravindraveendran7** [comment]
closing the thread as the issue was with the power shell command ($current = $PWD -replace "\\", "/" -replace "C", "c") where during each run this was not ran.Thank you @vania-pooh  for the support
