### ISSUE TITLE
Unclear documentation in section "2.7. Special Capabilities" 

### ISSUE THREAD

**Issue by neilcronin** [aerokube/selenoid#1218]
Section 2.7 of the documentation outlines some per-test or per-session capabilities, but it is not stated how to use these.   The docs are at: https://aerokube.com/selenoid/latest/#_special_capabilities

I need to alter the timezone of the browser in a test, which runs under selenium on a jvm. 

Using the "timeZone" value as a webdriver's "ChromeOptions()" does not seem to have any affect.  `options.setCapability("timeZone", "Asia/Tokyo")`

Using the "timeZone" value in selenoid's `browsers.json` does not seem to have any affect. 

```
{
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "timeZone": "Asia/Tokyo",
```

I am running Selenoid via `cm`, and there is no apparent documentation about if or how to pass these values into `cm` or `selenoid_xx` binaries. 

I could not see any other way to send these values to the actual webdriver executing the tests. 

Thanks!

**Comment by vania-pooh** [comment]
@neilcronin Selenium capabilities are obviously used in the code and not in `browsers.json` file. You need to place all Selenoid specific capabilities under `selenoid:options` key.
```
{"selenoid:options": {"enableVideo": true}}
```
In case of statically typed languages like Java or C# you should pass a Map\Dictionary in your code, so it serializes to JSON object then. More about capabilities: https://www.selenium.dev/documentation/webdriver/capabilities/
