### ISSUE TITLE
"Requested environment is not available"

### ISSUE THREAD

**Issue by tijnster** [aerokube/selenoid#1219]
Hi!

When initializing my test I am getting the following error:

Selenium::WebDriver::Error::InvalidArgumentError:
            Requested environment is not available

I am using the docker setup, and started both the Hub and Selenoid UI. I am using Macos when an Intel chip.

I can access the Hub and UI without any problem, the /status endpoint also gives me json about the browsers so that should all be good. I am using ruby as language binding.

![image](https://user-images.githubusercontent.com/34685850/167370659-5e0742e2-53d4-48f4-8133-087f57edcfa7.png)
![image](https://user-images.githubusercontent.com/34685850/167370706-ab14eae4-a885-4b18-9b8a-dd7d37d5934e.png)

I started both the Hub and UI with the quickstart:
./cm selenoid start --vnc
./cm selenoid-ui start 

Any help would be greatly appreciated!

**Comment by vania-pooh** [comment]
@tijnster make sure that browser name and version you are requesting are present in `/status` API output.

**Comment by tijnster** [comment]
Hi @vania-pooh I have it fixed now, thank you. Running into another issue now, if you could give me a pointer on this one that would be great, else I can open another ticket;

Getting the following error when initializing the driver:

1652183218.445][SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)
 --- x11vnc loop: waiting for: 191

**Comment by vania-pooh** [comment]
@tijnster this is not related. Probably you don't have IPv6 on your machine.
