### ISSUE TITLE
Cannot open display browser:99, error 1. browser:99: I/O error

### ISSUE THREAD

**Issue by ShwethaParthasarathy** [aerokube/selenoid#1222]
selenoid recorder is not launching and tests are not getting triggered due to this error. Below is log that is see.
selenoid-video-recorder_1  | ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
selenoid-video-recorder_1  |   built with gcc 9.3.0 (Alpine 9.3.0)
selenoid-video-recorder_1  |   configuration: --prefix=/usr --enable-avfilter --enable-gpl --enable-libx264 --enable-libpulse --enable-static --enable-small --disable-ffplay --disable-ffprobe --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --disable-alsa --disable-audiotoolbox --disable-cuda --disable-cuvid --disable-d3d11va --disable-dxva2 --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-librtmp --disable-devices --enable-indev=xcbgrab --enable-indev=pulse --disable-debug
selenoid-video-recorder_1  |   libavutil      56. 51.100 / 56. 51.100
selenoid-video-recorder_1  |   libavcodec     58. 91.100 / 58. 91.100
selenoid-video-recorder_1  |   libavformat    58. 45.100 / 58. 45.100
selenoid-video-recorder_1  |   libavdevice    58. 10.100 / 58. 10.100
selenoid-video-recorder_1  |   libavfilter     7. 85.100 /  7. 85.100
selenoid-video-recorder_1  |   libswscale      5.  7.100 /  5.  7.100
selenoid-video-recorder_1  |   libswresample   3.  7.100 /  3.  7.100
selenoid-video-recorder_1  |   libpostproc    55.  7.100 / 55.  7.100
selenoid-video-recorder_1  | [x11grab @ 0x7fe1ed7673c0] Cannot open display browser:99, error 1.
selenoid-video-recorder_1  | browser:99: I/O error
selenoid_selenoid-video-recorder_1 exited with code 1

Selenoid ui container is launched and is working fine. 

Trying to run it on Mac.

**Comment by ShwethaParthasarathy** [comment]
Container logs attached:
Waiting for display to open...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
Sleeping before next attempt...
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --prefix=/usr --enable-avfilter --enable-gpl --enable-libx264 --enable-libpulse --enable-static --enable-small --disable-ffplay --disable-ffprobe --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --disable-alsa --disable-audiotoolbox --disable-cuda --disable-cuvid --disable-d3d11va --disable-dxva2 --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-librtmp --disable-devices --enable-indev=xcbgrab --enable-indev=pulse --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[x11grab @ 0x7fe1ed7673c0] Cannot open display browser:99, error 1.
browser:99: I/O error

**Comment by vania-pooh** [comment]
@ShwethaParthasarathy if you are using Red Hat \ CentOS as base OS, this could be because of security restrictions. We are testing everything under Ubuntu.

**Comment by deepareddy14** [comment]
Any solution to this issue?

**Comment by vania-pooh** [comment]
@deepareddy14 try to disable SELInux.
