### ISSUE TITLE
can't get a file with spaces in the name with API 

### ISSUE THREAD

**Issue by jshvlv** [aerokube/selenoid#1223]
When my test downloads a file in which contains spaces in the name I can not get this file using the API, the file is just not at the standard address.
With normal files it works fine
API I mean =  GET http://selenoid-host.example.com:4444/download/f2bcd32b-d932-4cdc-a639-687ab8e4f840/myfile.txt - **works fine**
GET http://selenoid-host.example.com:4444/download/f2bcd32b-d932-4cdc-a639-687ab8e4f840/my file.txt - **file doesn't exist**

**Comment by vania-pooh** [comment]
@jshvlv you have to URL encode spaces.

**Comment by jshvlv** [comment]
> @jshvlv you have to URL encode spaces.

Thanks, I'll try it and comment to this!

**Comment by jshvlv** [comment]
Thanks a lot! This is my answer!

**Comment by vania-pooh** [comment]
@jshvlv closing then.
