### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by keshavjha06** [aerokube/selenoid#1224]
I am try to run my selenium test in mac.But I'm getting the above error.How to resolve this?
docker version : 20.10.14
selenoid version: aerokube/selenoid:latest-release

**Comment by keshavjha06** [comment]
@vania-pooh

**Comment by vania-pooh** [comment]
@keshavjha06 usually this is because of invalid flags being passed from the test or because of insufficient memory.

**Comment by keshavjha06** [comment]
@vania-pooh I"m not passing any valid/invalid flags in my test.Still getting the error

**Comment by keshavjha06** [comment]
@vania-pooh Here is the code which I'm using in macOS:

 WebDriverManager.chromedriver().setup();
        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setBrowserName(BrowserType.CHROME);
        cap.setCapability("enableVNC", true);
        cap.setCapability("enableVideo", true);
        cap.setCapability("videoName", "test3_video.mov");
        //RemoteWebDriver  driver = new RemoteWebDriver(URI.create("http://localhost:4444/wd/hub").toURL(), cap);
        WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), cap);

        driver.get("https://www.google.com");
        driver.findElement(By.xpath("//*[@type='text']")).sendKeys("123456");
        driver.close();

**Comment by keshavjha06** [comment]
@vania-pooh **Selenoid Logs**

docker logs selenoid
2022/05/27 04:30:35 [-] [INIT] [Loading configuration files...]
2022/05/27 04:30:35 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2022/05/27 04:30:35 [-] [INIT] [Video Dir: /opt/selenoid/video]
2022/05/27 04:30:35 [-] [INIT] [Your Docker API version is 1.41]
2022/05/27 04:30:35 [-] [INIT] [Timezone: UTC]
2022/05/27 04:30:35 [-] [INIT] [Listening on :4444]
2022/05/27 04:31:30 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/05/27 04:31:30 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/05/27 04:31:30 [0] [LOCATING_SERVICE] [chrome] []
2022/05/27 04:31:30 [-] [DEFAULT_VERSION] [Using default version: 101.0]
2022/05/27 04:31:30 [0] [USING_DOCKER] [chrome] [101.0]
2022/05/27 04:31:30 [0] [CREATING_CONTAINER] [selenoid/vnc_chrome:101.0]
2022/05/27 04:31:30 [0] [STARTING_CONTAINER] [selenoid/vnc_chrome:101.0] [f8959de068ba2f08a1d716077894b581c734473a2fb1f5c7c09951234f24c0cb]
2022/05/27 04:31:30 [0] [CONTAINER_STARTED] [selenoid/vnc_chrome:101.0] [f8959de068ba2f08a1d716077894b581c734473a2fb1f5c7c09951234f24c0cb] [0.19s]
2022/05/27 04:31:30 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/05/27 04:31:30 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [c590a49a9f434a7475f7e92620b91837fca1133bc983d48d4fc4791b46cebf10]
2022/05/27 04:31:30 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [c590a49a9f434a7475f7e92620b91837fca1133bc983d48d4fc4791b46cebf10] [0.20s]
2022/05/27 04:31:33 [0] [SERVICE_STARTED] [selenoid/vnc_chrome:101.0] [f8959de068ba2f08a1d716077894b581c734473a2fb1f5c7c09951234f24c0cb] [2.28s]
2022/05/27 04:31:33 [0] [PROXY_TO] [f8959de068ba2f08a1d716077894b581c734473a2fb1f5c7c09951234f24c0cb] [http://172.17.0.4:4444/]
2022/05/27 04:31:33 [0] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2022/05/27 04:31:34 [0] [SESSION_FAILED] [http://172.17.0.4:4444/] [500 Internal Server Error]
2022/05/27 04:31:34 [0] [STOPPING_VIDEO_CONTAINER] [c590a49a9f434a7475f7e92620b91837fca1133bc983d48d4fc4791b46cebf10]
2022/05/27 04:31:39 [0] [REMOVING_CONTAINER] [c590a49a9f434a7475f7e92620b91837fca1133bc983d48d4fc4791b46cebf10]
2022/05/27 04:31:39 [0] [FAILED_TO_REMOVE_CONTAINER] [c590a49a9f434a7475f7e92620b91837fca1133bc983d48d4fc4791b46cebf10] [Error: No such container: c590a49a9f434a7475f7e92620b91837fca1133bc983d48d4fc4791b46cebf10]
2022/05/27 04:31:39 [0] [REMOVING_CONTAINER] [f8959de068ba2f08a1d716077894b581c734473a2fb1f5c7c09951234f24c0cb]
2022/05/27 04:31:39 [0] [CONTAINER_REMOVED] [f8959de068ba2f08a1d716077894b581c734473a2fb1f5c7c09951234f24c0cb]
2022/05/27 04:34:56 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/05/27 04:34:56 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/05/27 04:34:56 [1] [LOCATING_SERVICE] [chrome] []
2022/05/27 04:34:56 [-] [DEFAULT_VERSION] [Using default version: 101.0]
2022/05/27 04:34:56 [1] [USING_DOCKER] [chrome] [101.0]
2022/05/27 04:34:56 [1] [CREATING_CONTAINER] [selenoid/vnc_chrome:101.0]
2022/05/27 04:34:56 [1] [STARTING_CONTAINER] [selenoid/vnc_chrome:101.0] [5454112613e291f3a0cf3e57a06699b95fc84f3c3b30d8a97380e394cc8b6924]
2022/05/27 04:34:56 [1] [CONTAINER_STARTED] [selenoid/vnc_chrome:101.0] [5454112613e291f3a0cf3e57a06699b95fc84f3c3b30d8a97380e394cc8b6924] [0.19s]
2022/05/27 04:34:56 [1] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/05/27 04:34:56 [1] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [cbf627d1b300740387ab2e7113e85dc8d0a35c08d1c31cea46808c44ef0bb22a]
2022/05/27 04:34:56 [1] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [cbf627d1b300740387ab2e7113e85dc8d0a35c08d1c31cea46808c44ef0bb22a] [0.23s]
2022/05/27 04:34:58 [1] [SERVICE_STARTED] [selenoid/vnc_chrome:101.0] [5454112613e291f3a0cf3e57a06699b95fc84f3c3b30d8a97380e394cc8b6924] [1.77s]
2022/05/27 04:34:58 [1] [PROXY_TO] [5454112613e291f3a0cf3e57a06699b95fc84f3c3b30d8a97380e394cc8b6924] [http://172.17.0.4:4444/]
2022/05/27 04:34:58 [1] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2022/05/27 04:35:00 [1] [SESSION_FAILED] [http://172.17.0.4:4444/] [500 Internal Server Error]
2022/05/27 04:35:00 [1] [STOPPING_VIDEO_CONTAINER] [cbf627d1b300740387ab2e7113e85dc8d0a35c08d1c31cea46808c44ef0bb22a]
2022/05/27 04:35:04 [1] [REMOVING_CONTAINER] [cbf627d1b300740387ab2e7113e85dc8d0a35c08d1c31cea46808c44ef0bb22a]
2022/05/27 04:35:04 [1] [FAILED_TO_REMOVE_CONTAINER] [cbf627d1b300740387ab2e7113e85dc8d0a35c08d1c31cea46808c44ef0bb22a] [Error: No such container: cbf627d1b300740387ab2e7113e85dc8d0a35c08d1c31cea46808c44ef0bb22a]
2022/05/27 04:35:04 [1] [REMOVING_CONTAINER] [5454112613e291f3a0cf3e57a06699b95fc84f3c3b30d8a97380e394cc8b6924]
2022/05/27 04:35:04 [1] [CONTAINER_REMOVED] [5454112613e291f3a0cf3e57a06699b95fc84f3c3b30d8a97380e394cc8b6924]
2022/05/27 04:41:50 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/05/27 04:41:50 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/05/27 04:41:50 [2] [LOCATING_SERVICE] [chrome] []
2022/05/27 04:41:50 [-] [DEFAULT_VERSION] [Using default version: 101.0]
2022/05/27 04:41:50 [2] [USING_DOCKER] [chrome] [101.0]
2022/05/27 04:41:50 [2] [CREATING_CONTAINER] [selenoid/vnc_chrome:101.0]
2022/05/27 04:41:50 [2] [STARTING_CONTAINER] [selenoid/vnc_chrome:101.0] [034b68aecd5523b163d88d2fc1856ba67cbb5c9a56ed960e6a02ed3d4a20c986]
2022/05/27 04:41:50 [2] [CONTAINER_STARTED] [selenoid/vnc_chrome:101.0] [034b68aecd5523b163d88d2fc1856ba67cbb5c9a56ed960e6a02ed3d4a20c986] [0.25s]
2022/05/27 04:41:50 [2] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/05/27 04:41:50 [2] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [27836d8eb4d4902d5e026f64b96f0a632ff3ac4c9acf8e84536525a24b80dac5]
2022/05/27 04:41:51 [2] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [27836d8eb4d4902d5e026f64b96f0a632ff3ac4c9acf8e84536525a24b80dac5] [0.33s]
2022/05/27 04:41:52 [2] [SERVICE_STARTED] [selenoid/vnc_chrome:101.0] [034b68aecd5523b163d88d2fc1856ba67cbb5c9a56ed960e6a02ed3d4a20c986] [1.84s]
2022/05/27 04:41:52 [2] [PROXY_TO] [034b68aecd5523b163d88d2fc1856ba67cbb5c9a56ed960e6a02ed3d4a20c986] [http://172.17.0.4:4444/]
2022/05/27 04:41:52 [2] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
**2022/05/27 04:41:54 [2] [SESSION_FAILED] [http://172.17.0.4:4444/] [500 Internal Server Error]**
2022/05/27 04:41:54 [2] [STOPPING_VIDEO_CONTAINER] [27836d8eb4d4902d5e026f64b96f0a632ff3ac4c9acf8e84536525a24b80dac5]
2022/05/27 04:41:58 [2] [REMOVING_CONTAINER] [27836d8eb4d4902d5e026f64b96f0a632ff3ac4c9acf8e84536525a24b80dac5]
2022/05/27 04:41:58 [2] [FAILED_TO_REMOVE_CONTAINER] [27836d8eb4d4902d5e026f64b96f0a632ff3ac4c9acf8e84536525a24b80dac5] [Error: No such container: 27836d8eb4d4902d5e026f64b96f0a632ff3ac4c9acf8e84536525a24b80dac5]
2022/05/27 04:41:58 [2] [REMOVING_CONTAINER] [034b68aecd5523b163d88d2fc1856ba67cbb5c9a56ed960e6a02ed3d4a20c986]
2022/05/27 04:41:58 [2] [CONTAINER_REMOVED] [034b68aecd5523b163d88d2fc1856ba67cbb5c9a56ed960e6a02ed3d4a20c986]

**Comment by vania-pooh** [comment]
@keshavjha06 probably you are on Mac M1 then?

**Comment by keshavjha06** [comment]
@vania-pooh Yes I'm using Mac M1, But it is working for firefox browser. Do I need to install docker desktop with intel version to work with chrome browser?or are there any other options?

**Comment by keshavjha06** [comment]
@vania-pooh After the latest release,now selenoid browser images(Chrome) will work on ARM arch?

**Comment by vania-pooh** [comment]
@keshavjha06 we only have ARM64-compatible Selenoid binary. Anyway browser images should be built separately.

**Comment by vania-pooh** [comment]
@gribanoveu is Selenoid running as a binary or as a container?

**Comment by gribanoveu** [comment]
> @gribanoveu is Selenoid running as a binary or as a container?

in the container. in the logs goes a request to start the browser, but the browser does not open. put a timeout for 60 minutes, after the time expires, displays an error on connection timeout

**Comment by vania-pooh** [comment]
@gribanoveu make sure with `docker inspect selenoid` in `Binds` section that existing Docker socket is mount as `/var/run/docker.sock`.
