### ISSUE TITLE
ChomeOptions in Selenium 4.3?

### ISSUE THREAD

**Issue by kaygee** [aerokube/selenoid#1225]
I updated to the latest [version](https://www.selenium.dev/blog/2022/legacy-protocol-support/) of WebDriver and started seeing some deprecation messages. After addressing these I saw the following Selenoid related [capabilities](https://aerokube.com/selenoid/latest/#_special_capabilities) being flagged in the console output...

`Jun 01, 2022 4:16:51 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "screenResolution" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jun 01, 2022 4:16:51 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "enableVNC" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jun 01, 2022 4:16:51 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "enableVideo" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jun 01, 2022 4:16:51 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "enableLog" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jun 01, 2022 4:16:51 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "name" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
Jun 01, 2022 4:16:51 PM org.openqa.selenium.W3CCapabilityKeysValidator validateCapability
WARNING: Support for Legacy Capabilities is deprecated; You are sending "sessionTimeout" which is an invalid capability. Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/`

I've read a SO [article](https://stackoverflow.com/questions/72424146/getting-warning-for-deprecation-without-using-setcapabilities-class) mentioning that this is a logging issue that'll be patched. But, I also see [these](https://github.com/aerokube/selenoid/issues?q=is%3Aissue++deprecated+capabilities) older Issues in the Selenoid repository... Just trying to make certain that I'm still up to date on what should be done. ;)

**Comment by vania-pooh** [comment]
@kaygee just move Selenium capabilities under `selenoid:options` key.

**Comment by vania-pooh** [comment]
@kaygee correct. This should work.

**Comment by kaygee** [comment]
Thanks for confirming @vania-pooh ! Closing!
