### ISSUE TITLE
VNC ISSUE

### ISSUE THREAD

**Issue by Anticope12** [aerokube/selenoid#1227]
Hello Team, 
I've just created a new setup. with the new update, it looks like there is an issue with VNC. With I run the ./cm selenoid start 
One of the lines says the following : 

- Requested to download VNC images but this feature is now deprecated as all images contain VNC.

and whenever I run the code it doesn't provide a screen view. taking into consideration that the same code/browsers/capabilities are the same. 

Not sure if there are some changes in the new update.

**Comment by vania-pooh** [comment]
@Anticope12 you anyway need to provide `enableVNC = true` capability to enable VNC.

**Comment by Anticope12** [comment]
Hi @vania-pooh , I've it Enabled. 
I'm using the same code/script. I've just moved to a new host and I've created a new Selenoid, it looks like VNC images are not being executed correctly with the latest updates it.

**Comment by Anticope12** [comment]
Closing this case, as the issue was from my Python setup locally.

**Comment by Anticope12** [comment]
Soluation 
        capabilities = {"browserName": "chrome", "version": "100.0",
                         "selenoid:options": {"screenResolution": "1280x1024x24", "enableVNC": True}}
