### ISSUE TITLE
video-recorder container is not started

### ISSUE THREAD

**Issue by suzhenyu006** [aerokube/selenoid#1228]
when i start a test, i found that video file was not found, i check the docker logs :

> 2022/06/14 04:02:34 [-] [INIT] [Loading configuration files...]
> 2022/06/14 04:02:34 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
> 2022/06/14 04:02:34 [-] [INIT] [Video Dir: /opt/selenoid/video]
> 2022/06/14 04:02:34 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
> 2022/06/14 04:02:34 [-] [INIT] [Using Docker API version: 1.26]
> 2022/06/14 04:02:34 [-] [INIT] [Timezone: UTC]
> 2022/06/14 04:02:34 [-] [INIT] [Listening on :4444]
> 2022/06/14 04:05:47 [-] [NEW_REQUEST] [unknown] [10.18.32.141]
> 2022/06/14 04:05:47 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.18.32.141]
> 2022/06/14 04:05:47 [0] [LOCATING_SERVICE] [chrome] [90.0]
> 2022/06/14 04:05:47 [0] [USING_DOCKER] [chrome] [90.0]
> 2022/06/14 04:05:47 [0] [CREATING_CONTAINER] [selenoid/vnc_chrome:90.0]
> 2022/06/14 04:05:47 [0] [STARTING_CONTAINER] [selenoid/vnc_chrome:90.0] [69edf4e173c29734149f458da457c910985c38006ccb422926b0f6c15b92801e]
> 2022/06/14 04:05:48 [0] [CONTAINER_STARTED] [selenoid/vnc_chrome:90.0] [69edf4e173c29734149f458da457c910985c38006ccb422926b0f6c15b92801e] [0.31s]
> 2022/06/14 04:05:50 [0] [SERVICE_STARTED] [selenoid/vnc_chrome:90.0] [69edf4e173c29734149f458da457c910985c38006ccb422926b0f6c15b92801e] [2.53s]
> 2022/06/14 04:05:50 [0] [PROXY_TO] [69edf4e173c29734149f458da457c910985c38006ccb422926b0f6c15b92801e] [http://172.18.0.3:4444/]
> 2022/06/14 04:05:50 [0] [SESSION_ATTEMPTED] [http://172.18.0.3:4444/] [1]
> 2022/06/14 04:05:52 [0] [SESSION_CREATED] [6949de505afe25b1f2e94be81f85a6e9] [1] [4.79s]
> 2022/06/14 04:10:21 [81] [SESSION_DELETED] [6949de505afe25b1f2e94be81f85a6e9]
> 2022/06/14 04:10:21 [0] [REMOVING_CONTAINER] [69edf4e173c29734149f458da457c910985c38006ccb422926b0f6c15b92801e]
> 2022/06/14 04:10:21 [0] [CONTAINER_REMOVED] [69edf4e173c29734149f458da457c910985c38006ccb422926b0f6c15b92801e]
> 

i found selenoid was not create video-recorder container , why?

this is my config:

> options = seleniumdriver.ChromeOptions()
>                         options.add_experimental_option('w3c', True)
>                         options.add_argument('--disable-gpu')
>                         options.add_argument('--start-maximized')
>                         options.add_argument('--no-sandbox')
> 
> capabilities = {
>                         'browserName': self.device_name,
>                         'version': self.device_version,
>                         'pageLoadStrategy': 'none',
>                         'screenResolution': '1920x1080x24',
>                         'enableLog': True,
>                         'enableVideo':True,
>                         'enableVNC':False,
>                         'logName': self.device_id + '.log',
>                         'videoName': self.device_id + '.mp4'
>                     }
> 
>  self.driver = seleniumdriver.Remote(command_executor="http://" + self.agent + ":4444/wd/hub",options=options,desired_capabilities=capabilities)

**Comment by vania-pooh** [comment]
@suzhenyu006 try to put all Selenoid-specific capabilities under `selenoid:options` key.
