### ISSUE TITLE
Issue with Edge 101 : Host header or origin header is specified and is not whitelisted or localhost

### ISSUE THREAD

**Issue by AlexGrs** [aerokube/selenoid#1229]
We are trying to use Edge:101 docker image for our tests. 

Somehow, we run before executing our tests the following wdio command in a beforeSuite:
`browser.maximizeWindow();`

What works well for Chrome and Firefox is not working with Edge. We have the following error with the raw Docker Image: 

```
[0-0] 2022-06-14T12:28:11.665Z INFO webdriver: COMMAND maximizeWindow()
[0-0] 2022-06-14T12:28:11.665Z INFO webdriver: [POST] http://selenoid:4444/wd/hub/session/9d5ef28aeeebf7ce52e0cc59d868d551/window/maximize
[0-0] 2022-06-14T12:28:11.670Z ERROR webdriver: Request failed with status 500 due to Error: Host header or origin header is specified and is not whitelisted or localhost.
```

We thought it was linked with parameters like `whitelisted-ips` and `allowed-origins` but we are failing to do so. 

I also tried to build an image using the aeroku/images repo but i go an error as well:

```
./images edge -b 102.0.1245.39 -t selenoid/edge:88.0
.....
Get:20 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [53.8 kB]
Fetched 22.6 MB in 2s (10.1 MB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '102.0.1245.39' for 'microsoft-edge-stable' was not found
```

Any ideas what I can do to continue the troubleshooting ?

**Comment by vania-pooh** [comment]
@AlexGrs package versions usually contain `-1` suffix, so try with `102.0.1245.39-1`. Also don't forget to rebuild `images` binary and do `go generate` command as shown here: https://aerokube.com/images/latest/#_building_procedure
