### ISSUE TITLE
unable to start selenoid on mac  

### ISSUE THREAD

**Issue by maheshsamudrala241** [aerokube/selenoid#1232]
Hi  Team 
I am unable to start up the selenoid service. Could please help by fixing this.
Getting error as **"IMAGE MAY HAVE POOR PERFORMANCE, OR FAIL, IF RUN VIA EMULATION"**
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/48947217/174569931-2144b489-e832-4e90-8a08-6a8c0e68229b.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/48947217/174570474-cdfbe8c6-9984-4f1e-9ff1-470b4aa0f952.png">

**Comment by vania-pooh** [comment]
@maheshsamudrala241 we currently do not support Mac M1.

**Comment by maheshsamudrala241** [comment]
**Could please let us know by when it will be available**

**Comment by vania-pooh** [comment]
@maheshsamudrala241 Selenoid binaries and Docker images for M1 are available in latest release. Browser image for Chrome can be built from these sources: https://github.com/aerokube/images/tree/master/static/chromium

**Comment by amit-chaudhary4** [comment]
@vania-pooh I downloaded latest linux binary (1.8.1) but when I try to execute **./cm selenoid start --vnc**, I get error on Mac M1.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/111855531/187419074-a007f2db-e401-415e-8ec8-f3594c31217e.png">

FYI, I downloaded the binary using wget -o cm https://github.com/aerokube/cm/releases/download/1.8.1/cm_linux_amd64

**Comment by vania-pooh** [comment]
@amit-chaudhary4 obviously for M1 binary architecture should be arm64. This was fixed in https://github.com/aerokube/cm/pull/316, but not yet released.

**Comment by maheshsamudralaphenom** [comment]
could please lets us know when it will be released

**Comment by cbasdev** [comment]
@vania-pooh  Hello, I have the same error when trying to run the aerokube image on ARM architectures.
Is there a version where this is fixed? thanks! 😄

**Comment by vania-pooh** [comment]
@cbasdev not yet fixed.

**Comment by mjevtovic** [comment]
@vania-pooh Any idea when we can expect ARM?

**Comment by vania-pooh** [comment]
@mjevtovic ARM binaries of Selenoid are already attached to latest releases. However, we don't have ARM browser images yet. You can build Chromium image using this source code: https://github.com/aerokube/images/tree/master/static/chromium

**Comment by kemalgoekhan** [comment]
@vania-pooh thanks for sharing. 
To use selenoid vnc on arm64_linux
You already shared sskorol/selenoid_chromium_vnc:100.0 this image for running on arm. The problem is CM executable file for arm.
here is the cm distributions but I cant find linux_arm64  or how can I execute with extracted zip file. you call cm but inside of zip there is no cm file. 
https://github.com/aerokube/cm/releases/tag/1.8.2

**Comment by vania-pooh** [comment]
@kemalgoekhan it's there. 
<img width="1207" alt="Screen Shot 2023-02-20 at 20 02 01" src="https://user-images.githubusercontent.com/829320/220165712-d6a0f727-0210-4a09-bfba-0d502e6cdc83.png">
