### ISSUE TITLE
can't set args in selenoid:options

### ISSUE THREAD

**Issue by DarksideTheDark** [aerokube/selenoid#1234]
my code 
(async () => {
  const browser = await remote({
    path: "/wd/hub",
    "capabilities": {
      browserName: "chrome",
      browserVersion: "102.0",
      "selenoid:options": {
        args:[
            '--disable-web-security','--no-sendbox','--privileged','--user-data-dir=/home/selenium/cache',"--profile-directory=Profile 1"
        ],
        enableVNC: true,
        enableVideo: false,
        name: name,
        setSize:"maximize",
        enableLog: true,
      },
    },
  });
  
  For some reason whenever I start a container it doesn't pull the args, would you help me? :)

**Comment by vania-pooh** [comment]
@DarksideTheDark Chrome args should be certainly sent under `goog:chromeOptions`. We never said you should do it like this.

**Comment by DarksideTheDark** [comment]
how can I rename or start a browser container with a name that I want to use?

**Comment by vania-pooh** [comment]
@DarksideTheDark this is not implemented. Names are always random. But what is the use case?

**Comment by DarksideTheDark** [comment]
@vania-pooh as I do several tests, it would be interesting to have the name of the container represented by the test I'm running

**Comment by vania-pooh** [comment]
@DarksideTheDark it makes no sense because you can use `labels` capability to put custom labels on container and then filter by these labels.

**Comment by DarksideTheDark** [comment]
@vania-pooh 
I do the test follow-ups in a netdata, because his metrics are "easier" to visualize. as selenoid starts a container with a random name it is difficult to know which type of test is running

**Comment by vania-pooh** [comment]
@DarksideTheDark all Docker monitoring software should be able to filter by container metrics.
