### ISSUE TITLE
An issue with  MS Edge: Unable to start a WebDriver session - Host header or origin header is specified and is not whitelisted or localhost

### ISSUE THREAD

**Issue by roma3784** [aerokube/selenoid#1241]
I've been having an issue with MS Edge. I'm trying to run tests on virtual desktop against Edge using **selenoid**.
Jenkins errors: 
"E/runner - **Unable to start a WebDriver session**." 
"I/runnerCli - **Host header or origin header is specified and is not whitelisted or localhost**."

in cmd selenoid.bat  error- "**Passthrough is not supported, GL is disabled, ANGLE is**"
Browsers open , but nothing else happens -> can see 'data' shown, but tests don't run. 

What I've tried to do to fix it up: 
1. Checked '**Use hardware acceleration when available**', enabled '**WebGL**' and '**Override software rendering list**' it didn't help, browsers that run using 'selenoid' don't have these settings on.
2. Used a lot of flags inside **browsers.json** - e.g. -
"image": ["C:\\selenoid\\msedgedriver.exe", "--disable-gpu", "--whitelisted-ips=''", "--verbose", "--allowed-origins=*", "--disable-software-rasterizer"], used them separately as well as together.
Certainly, **browserName** and **version** in **browser.json** is alright.
3. Tried to use different Edge versions as well.

In order to run tests against Edge locally, I'm using  'webdriver-manager start --edge ..path/msedgedriver.exe' to run 'Selenium Server ' after that everything works fine locally -> I don't know if it helps, 
I tried to use the way like this on **Jenkins** instance where containers with 'ggr' ,'ggr-ui' ,'selenoid' are, but it didn't help.

Using Protractor, Windows 10.

Any ideas what I missed? 
Thank you!

**Comment by vania-pooh** [comment]
@roma3784 `allowed-origins` should normally fix it.

**Comment by roma3784** [comment]
Hello! @vania-pooh, **allowed-origins** doesn't help unfortunately,
here's my **browser.json** - 

{
"MicrosoftEdge": {
"default": "103.0",
"versions": {
  "103.0": {
    "image": ["C:\\selenoid\\msedgedriver.exe", "--allowed-origins=*"]
  }
}
}
}

Maybe there's another way to write it down 

Here's the screenshot
![image](https://user-images.githubusercontent.com/57619778/176627440-cc5b9db6-64a9-4afa-854d-04044d94db82.png)

**Comment by vania-pooh** [comment]
@roma3784 probably trying to build `selenoid` binary from latest source code will help.

**Comment by vania-pooh** [comment]
Closing then.
