### ISSUE TITLE
'This file may harm your computer.' popup appears when try to download file.

### ISSUE THREAD

**Issue by GolubNick** [aerokube/selenoid#1245]
Hi @vania-pooh. I use Selenoid and I try to download a file in tests. I've configured my tests according to the link https://github.com/aerokube/selenoid/blob/master/docs/file-download.adoc. When I download directly like this `driver.navigate().to("http://example.com/myfile.odt");` it will work.
But clicking a download button leads to the popup 'This file may harm your computer.'
I've tried to add these options but it hasn't worked.
```
            chromeOptions.addArguments("--safebrowsing-disable-download-protection");
            chromeOptions.addArguments("--safebrowsing-disable-extension-blacklist");
```
Could you help please to resolve this issue?
<img width="1429" alt="Screenshot 2022-07-06 at 18 20 38" src="https://user-images.githubusercontent.com/8925254/177591294-ba5466cf-9178-4009-8100-05f431894403.png">

**Comment by vania-pooh** [comment]
@GolubNick I don't know a working solution for this. This needs investigation.

**Comment by GolubNick** [comment]
@vania-pooh Thank you. Let me know when you have a solution, please.

**Comment by iamkhusainov7** [comment]
I have got exactly the same issue :/

**Comment by GolubNick** [comment]
@iamkhusainov7 Unfortunately, not yet.
