### ISSUE TITLE
[FAILED_TO_REMOVE_CONTAINER] [X] [Error response from daemon: removal of container X is already in progress]

### ISSUE THREAD

**Issue by andrewidqa** [aerokube/selenoid#1246]
Hi, I am getting **FAILED_TO_REMOVE_CONTAINER** in the logs for each test that I run with video enabled. It seems something is trying to remove the video recording container after it's already been deleted? The video saves fine however. If I don't enable video recording for the test, I don't see these errors.  Also running docker stats I see there are no zombie containers which is good. I've attached my docker compose yml file here [docker-compose.yml.txt](https://github.com/aerokube/selenoid/files/9059344/docker-compose.yml.txt)

I'm not sure how this is affecting functionality but the error is concerning.

In this run, I ran 4 different selenium tests and got 4 of these error messages.

docker logs below:
2022/07/06 23:47:59 [-] [INIT] [Loading configuration files...]
2022/07/06 23:47:59 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2022/07/06 23:47:59 [-] [INIT] [Video Dir: /opt/selenoid/video]
2022/07/06 23:47:59 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2022/07/06 23:48:00 [-] [INIT] [Your Docker API version is 1.41]
2022/07/06 23:48:00 [-] [INIT] [Timezone: UTC]
2022/07/06 23:48:00 [-] [INIT] [Listening on :4444]
2022/07/06 23:55:03 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [0] [LOCATING_SERVICE] [chrome] [102]
2022/07/06 23:55:03 [0] [USING_DOCKER] [chrome] [102]
2022/07/06 23:55:03 [0] [CREATING_CONTAINER] [selenoid/chrome:102.0]
2022/07/06 23:55:03 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [1] [LOCATING_SERVICE] [chrome] [102]
2022/07/06 23:55:03 [1] [USING_DOCKER] [chrome] [102]
2022/07/06 23:55:03 [1] [CREATING_CONTAINER] [selenoid/chrome:102.0]
2022/07/06 23:55:03 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [2] [LOCATING_SERVICE] [chrome] [102]
2022/07/06 23:55:03 [2] [USING_DOCKER] [chrome] [102]
2022/07/06 23:55:03 [2] [CREATING_CONTAINER] [selenoid/chrome:102.0]
2022/07/06 23:55:03 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/07/06 23:55:03 [3] [LOCATING_SERVICE] [chrome] [102]
2022/07/06 23:55:03 [3] [USING_DOCKER] [chrome] [102]
2022/07/06 23:55:03 [3] [CREATING_CONTAINER] [selenoid/chrome:102.0]
2022/07/06 23:55:03 [2] [STARTING_CONTAINER] [selenoid/chrome:102.0] [d0cdca70d9742673153d5fe32b81e4e947cbd75bffc137cdf27d9140aa4099f6]
2022/07/06 23:55:03 [0] [STARTING_CONTAINER] [selenoid/chrome:102.0] [70a025f6604eb533be09b39dac0d4a61041272a29c125796eff5b09ebcc3ff95]
2022/07/06 23:55:03 [3] [STARTING_CONTAINER] [selenoid/chrome:102.0] [e2dc8243b1401eba57c2394b3acab09daced18dba39282dd5a83371f98fc4b7b]
2022/07/06 23:55:03 [1] [STARTING_CONTAINER] [selenoid/chrome:102.0] [e9ca96e184542a9133dbc6f49b3eb74aa7708863ed53c8e2fd9b00411060b5e6]
2022/07/06 23:55:04 [2] [CONTAINER_STARTED] [selenoid/chrome:102.0] [d0cdca70d9742673153d5fe32b81e4e947cbd75bffc137cdf27d9140aa4099f6] [0.60s]
2022/07/06 23:55:04 [2] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/07/06 23:55:04 [2] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [3608fcb1291a9004f85f49b84c1edf803a545cdf382851b28d62471919984011]
2022/07/06 23:55:04 [3] [CONTAINER_STARTED] [selenoid/chrome:102.0] [e2dc8243b1401eba57c2394b3acab09daced18dba39282dd5a83371f98fc4b7b] [0.88s]
2022/07/06 23:55:04 [3] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/07/06 23:55:04 [3] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [6cb46d66275185f7588b5a1ba456b99470a36d43bd8affd4b068f2d87235352a]
2022/07/06 23:55:04 [0] [CONTAINER_STARTED] [selenoid/chrome:102.0] [70a025f6604eb533be09b39dac0d4a61041272a29c125796eff5b09ebcc3ff95] [1.31s]
2022/07/06 23:55:04 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/07/06 23:55:04 [1] [CONTAINER_STARTED] [selenoid/chrome:102.0] [e9ca96e184542a9133dbc6f49b3eb74aa7708863ed53c8e2fd9b00411060b5e6] [1.32s]
2022/07/06 23:55:04 [1] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/07/06 23:55:04 [1] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [c2a0918c42b6b1ba18a5be90b9129dbf7390a96035baa0fdf812ad38f7624265]
2022/07/06 23:55:04 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [f2914faeac554c7d4460b5905fa8fc59a38a1bb26789fdff43e9cebb81389b63]
2022/07/06 23:55:05 [2] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [3608fcb1291a9004f85f49b84c1edf803a545cdf382851b28d62471919984011] [0.95s]
2022/07/06 23:55:05 [2] [SERVICE_STARTED] [selenoid/chrome:102.0] [d0cdca70d9742673153d5fe32b81e4e947cbd75bffc137cdf27d9140aa4099f6] [0.00s]
2022/07/06 23:55:05 [2] [PROXY_TO] [d0cdca70d9742673153d5fe32b81e4e947cbd75bffc137cdf27d9140aa4099f6] [http://172.17.0.3:4444/]
2022/07/06 23:55:05 [2] [SESSION_ATTEMPTED] [http://172.17.0.3:4444/] [1]
2022/07/06 23:55:05 [3] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [6cb46d66275185f7588b5a1ba456b99470a36d43bd8affd4b068f2d87235352a] [1.00s]
2022/07/06 23:55:05 [1] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [c2a0918c42b6b1ba18a5be90b9129dbf7390a96035baa0fdf812ad38f7624265] [0.85s]
2022/07/06 23:55:05 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [f2914faeac554c7d4460b5905fa8fc59a38a1bb26789fdff43e9cebb81389b63] [0.94s]
2022/07/06 23:55:05 [3] [SERVICE_STARTED] [selenoid/chrome:102.0] [e2dc8243b1401eba57c2394b3acab09daced18dba39282dd5a83371f98fc4b7b] [0.56s]
2022/07/06 23:55:05 [3] [PROXY_TO] [e2dc8243b1401eba57c2394b3acab09daced18dba39282dd5a83371f98fc4b7b] [http://172.17.0.4:4444/]
2022/07/06 23:55:05 [3] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2022/07/06 23:55:06 [0] [SERVICE_STARTED] [selenoid/chrome:102.0] [70a025f6604eb533be09b39dac0d4a61041272a29c125796eff5b09ebcc3ff95] [0.31s]
2022/07/06 23:55:06 [0] [PROXY_TO] [70a025f6604eb533be09b39dac0d4a61041272a29c125796eff5b09ebcc3ff95] [http://172.17.0.5:4444/]
2022/07/06 23:55:06 [0] [SESSION_ATTEMPTED] [http://172.17.0.5:4444/] [1]
2022/07/06 23:55:06 [1] [SERVICE_STARTED] [selenoid/chrome:102.0] [e9ca96e184542a9133dbc6f49b3eb74aa7708863ed53c8e2fd9b00411060b5e6] [0.91s]
2022/07/06 23:55:06 [1] [PROXY_TO] [e9ca96e184542a9133dbc6f49b3eb74aa7708863ed53c8e2fd9b00411060b5e6] [http://172.17.0.6:4444/]
2022/07/06 23:55:06 [1] [SESSION_ATTEMPTED] [http://172.17.0.6:4444/] [1]
2022/07/06 23:55:07 [3] [SESSION_CREATED] [1d971703b85aea0f8a36513c2533bf13] [1] [3.79s]
2022/07/06 23:55:07 [2] [SESSION_CREATED] [0d6e661fd705ba79b0936652e7cd6dc6] [1] [3.89s]
2022/07/06 23:55:07 [0] [SESSION_CREATED] [cbea20c9be8f9972bf70fc7ddc41fd1f] [1] [4.18s]
2022/07/06 23:55:08 [1] [SESSION_CREATED] [1432138401421f444ba508bca43e7404] [1] [5.40s]
2022/07/06 23:55:40 [9] [SESSION_DELETED] [1d971703b85aea0f8a36513c2533bf13]
2022/07/06 23:55:41 [3] [STOPPING_VIDEO_CONTAINER] [6cb46d66275185f7588b5a1ba456b99470a36d43bd8affd4b068f2d87235352a]
2022/07/06 23:55:41 [10] [SESSION_DELETED] [0d6e661fd705ba79b0936652e7cd6dc6]
2022/07/06 23:55:41 [2] [STOPPING_VIDEO_CONTAINER] [3608fcb1291a9004f85f49b84c1edf803a545cdf382851b28d62471919984011]
2022/07/06 23:55:42 [11] [SESSION_DELETED] [cbea20c9be8f9972bf70fc7ddc41fd1f]
2022/07/06 23:55:42 [0] [STOPPING_VIDEO_CONTAINER] [f2914faeac554c7d4460b5905fa8fc59a38a1bb26789fdff43e9cebb81389b63]
2022/07/06 23:55:43 [2] [REMOVING_CONTAINER] [3608fcb1291a9004f85f49b84c1edf803a545cdf382851b28d62471919984011]
2022/07/06 23:55:43 [2] [FAILED_TO_REMOVE_CONTAINER] [3608fcb1291a9004f85f49b84c1edf803a545cdf382851b28d62471919984011] [Error: No such container: 3608fcb1291a9004f85f49b84c1edf803a545cdf382851b28d62471919984011]
2022/07/06 23:55:43 [2] [REMOVING_CONTAINER] [d0cdca70d9742673153d5fe32b81e4e947cbd75bffc137cdf27d9140aa4099f6]
2022/07/06 23:55:44 [2] [CONTAINER_REMOVED] [d0cdca70d9742673153d5fe32b81e4e947cbd75bffc137cdf27d9140aa4099f6]
2022/07/06 23:55:44 [3] [REMOVING_CONTAINER] [6cb46d66275185f7588b5a1ba456b99470a36d43bd8affd4b068f2d87235352a]
2022/07/06 23:55:44 [3] [FAILED_TO_REMOVE_CONTAINER] [6cb46d66275185f7588b5a1ba456b99470a36d43bd8affd4b068f2d87235352a] [Error: No such container: 6cb46d66275185f7588b5a1ba456b99470a36d43bd8affd4b068f2d87235352a]
2022/07/06 23:55:44 [3] [REMOVING_CONTAINER] [e2dc8243b1401eba57c2394b3acab09daced18dba39282dd5a83371f98fc4b7b]
2022/07/06 23:55:44 [3] [CONTAINER_REMOVED] [e2dc8243b1401eba57c2394b3acab09daced18dba39282dd5a83371f98fc4b7b]
2022/07/06 23:55:44 [0] [REMOVING_CONTAINER] [f2914faeac554c7d4460b5905fa8fc59a38a1bb26789fdff43e9cebb81389b63]
2022/07/06 23:55:44 [0] [FAILED_TO_REMOVE_CONTAINER] [f2914faeac554c7d4460b5905fa8fc59a38a1bb26789fdff43e9cebb81389b63] [Error: No such container: f2914faeac554c7d4460b5905fa8fc59a38a1bb26789fdff43e9cebb81389b63]
2022/07/06 23:55:44 [0] [REMOVING_CONTAINER] [70a025f6604eb533be09b39dac0d4a61041272a29c125796eff5b09ebcc3ff95]
2022/07/06 23:55:45 [0] [CONTAINER_REMOVED] [70a025f6604eb533be09b39dac0d4a61041272a29c125796eff5b09ebcc3ff95]
2022/07/06 23:56:15 [8] [SESSION_TIMED_OUT] [1432138401421f444ba508bca43e7404]
2022/07/06 23:56:15 [12] [SESSION_DELETED] [1432138401421f444ba508bca43e7404]
2022/07/06 23:56:15 [1] [STOPPING_VIDEO_CONTAINER] [c2a0918c42b6b1ba18a5be90b9129dbf7390a96035baa0fdf812ad38f7624265]
2022/07/06 23:56:16 [1] [REMOVING_CONTAINER] [c2a0918c42b6b1ba18a5be90b9129dbf7390a96035baa0fdf812ad38f7624265]
2022/07/06 23:56:16 [1] [FAILED_TO_REMOVE_CONTAINER] [c2a0918c42b6b1ba18a5be90b9129dbf7390a96035baa0fdf812ad38f7624265] [Error response from daemon: removal of container c2a0918c42b6b1ba18a5be90b9129dbf7390a96035baa0fdf812ad38f7624265 is already in progress]
2022/07/06 23:56:16 [1] [REMOVING_CONTAINER] [e9ca96e184542a9133dbc6f49b3eb74aa7708863ed53c8e2fd9b00411060b5e6]
2022/07/06 23:56:16 [1] [CONTAINER_REMOVED] [e9ca96e184542a9133dbc6f49b3eb74aa7708863ed53c8e2fd9b00411060b5e6]

Let me know if any other info is needed. 

Appreciate the project! Thanks for your help!

**Comment by vania-pooh** [comment]
@andrewidqa video containers are started with `--rm` flag by default. Probably your containers just exit because of wrong configuration.

**Comment by andrewidqa** [comment]
Hi @vania-pooh what configuration is wrong in this case? The selenoid configuration, selenium test config, or the host machine config? (I'm running Ubuntu 18.04). 

Here is a simple python test that reproduces the issue:

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


def test_1():
    browser = webdriver.Remote(options=webdriver.ChromeOptions(), command_executor="http://127.0.0.1:4444/wd/hub",
            desired_capabilities={"enableVideo": bool(True)})
    try:
        browser.get("http://www.python.org")
    finally:
        browser.close()
        browser.quit()
```

I also tried with default settings using ./cm selenoid start and still get the failed container issue.

**Comment by andrewidqa** [comment]
To be sure it's not my config I'm using the default auto config cm tool, that should work right?

**Comment by andrewidqa** [comment]
Hi @vania-pooh, 

I am certain there is a bug somewhere. I see this error using Ubuntu and macOS with both python and javascript tests. I am using **default settings from Configuration Manager**.

Steps to reproduce:

Following the quick start guide https://aerokube.com/selenoid/latest/#_quick_start_guide 1. 

1. Download latest release v1.8.1
2. Start selenoid: ./cm selenoid start --vnc
3. Monitor logs docker logs -f selenoid
4. Target tests to run against Selenoid with capabilities  
'selenoid:options': {
enableVideo: true 
}
6.  Error in logs FAILED_TO_REMOVE_CONTAINER

2022/07/09 17:36:20 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]

2022/07/09 17:36:20 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [135b2fb894bba626910cdd195f912712442948b9d29506c87b7d6d3d138da722]

2022/07/09 17:36:21 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [135b2fb894bba626910cdd195f912712442948b9d29506c87b7d6d3d138da722] [0.47s]

2022/07/09 17:36:33 [0] [STOPPING_VIDEO_CONTAINER] [135b2fb894bba626910cdd195f912712442948b9d29506c87b7d6d3d138da722]

2022/07/09 17:36:34 [0] [REMOVING_CONTAINER] [135b2fb894bba626910cdd195f912712442948b9d29506c87b7d6d3d138da722]

2022/07/09 17:36:34 [0] [**FAILED_TO_REMOVE_CONTAINER**] [135b2fb894bba626910cdd195f912712442948b9d29506c87b7d6d3d138da722] [Error: No such container: 135b2fb894bba626910cdd195f912712442948b9d29506c87b7d6d3d138da722]


Please try and let me know. Thanks!

**Comment by andrewidqa** [comment]
@vania-pooh any updates on this?

**Comment by vania-pooh** [comment]
@andrewidqa are you using CM under Windows and WSL?

**Comment by andrewidqa** [comment]
@vania-pooh No I am using Ubuntu and macOS

**Comment by andrewidqa** [comment]
Checking in again, my logs are still filled with this error.

**Comment by wolket** [comment]
The same error occurs with Java tests. I also use the default cm configuration and the latest version of the Firefox browser image

**Comment by Noro63853** [comment]
@vania-pooh my selenoid also doesn't record video, i used all instructions, but received the screenshot

![Screenshot_5](https://user-images.githubusercontent.com/26900490/220395622-2be70530-5b81-45ab-b7cc-66f48705611f.png)

**Comment by vania-pooh** [comment]
@Noro63853 you have incorrect value for OVERRIDE_VIDEO_OUTPUT_DIR variable.
