### ISSUE TITLE
Unable start Selenoid server with docker in Windows

### ISSUE THREAD

**Issue by riraga001m** [aerokube/selenoid#1248]
![image](https://user-images.githubusercontent.com/93780328/178340176-de21ee62-95ec-461c-a34c-f8cb5da50fe6.png)

I see this error. When I download latest selenoid it says not compatible
![image](https://user-images.githubusercontent.com/93780328/178340666-8833f808-f5f5-451d-8ecb-927b1913730b.png)

How can I fix this issue.

Also would like to know how can I pull msEdge browser images in windows.

**Comment by vania-pooh** [comment]
@riraga001m switch your Docker for Windows to Linux mode. There is a context menu entry allowing to do this.

**Comment by riraga001m** [comment]
Thank you @vania-pooh This solved the issue with selenoid start.
Please advise about msedge. I did pull image for Edge, but it is not getting. Did update the browsers file but it is not taking the edge.
When I redo the process, it downloads Chrome, FF and Opera but skipping edge.

**Comment by vania-pooh** [comment]
@riraga001m just explicitly request to add edge:
```
$ ./cm selenoid start --browsers 'firefox;chrome;opera;MicrosoftEdge' --last-versions 2  --force
```

**Comment by riraga001m** [comment]
Updating the browser settings this way worked fine. Closing the ticket.
![image](https://user-images.githubusercontent.com/93780328/178525024-2460ad32-c26b-4b49-99c9-503607b075ec.png)
