### ISSUE TITLE
How to enable VNC password?

### ISSUE THREAD

**Issue by cheesepaulo** [aerokube/selenoid#1250]
Today using Selenoid in the latest version when turning on VNC we can automatically login without using a password through selenoid-ui.

Are there any extra parameters that can be used to require a password for VNC access?

**Comment by vania-pooh** [comment]
@cheesepaulo you can instead restrict access to Selenoid UI with a reverse proxy like Nginx and basic HTTP authentication.

**Comment by cheesepaulo** [comment]
Yes for sure or restrict access via VPN or something else.

I say because in the past access via VNC in selenoid asked for a default password "selenoid". And if it had a password it is because it was defined somewhere, and if it is defined it is possible to customize it.

**Comment by vania-pooh** [comment]
@cheesepaulo Selenoid VNC password is still present but UI automatically provides it. Password is defined as `x11vnc` command-line flag. E.g. https://github.com/aerokube/images/blob/master/static/chrome/entrypoint.sh#L86

**Comment by cheesepaulo** [comment]
Thanks, this will help a lot 🚀
