### ISSUE TITLE
Selenium sendkeys or upload fails when uploading multiple large file

### ISSUE THREAD

**Issue by poryee** [aerokube/selenoid#1251]
Largest file 90mb
No special character for filename
The test would pass in local (2 seconds per file) roughly 12 files
Fails on remote

	
org.openqa.selenium.WebDriverException: The following error occurred: unknown error: unable to unzip 'file'
from unknown error: archive error: (unknown error: could not unzip archive), entry error: (unknown error: invalid data descriptor signature)
  (Session info: chrome=101.0.4951.54)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ta-chrome-itt-xwcq1', ip: '192.168.94.66', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-305.19.1.el8_4.x86_64', java.version: '11.0.7'
Driver info: com.x.testcenter.drivers.remote.GridDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 101.0.4951.54, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.0jdYOe}, goog:chromeOptions: {debuggerAddress: localhost:33559}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(manual), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 57121b855e4235ed3b14b8f10487dbe18a2f1471dff93e5367ca1f42f3286530

**Comment by vania-pooh** [comment]
@poryee do you have any reverse proxy servers between your code and Selenoid?

**Comment by poryee** [comment]
hello vania, I don't think so. Is there a quick way I can confirm this?

**Comment by vania-pooh** [comment]
@poryee ask the person who installed Selenoid.

**Comment by poryee** [comment]
hello vania, double confirmed there is no reverse proxy servers between our code and selenoid
