### ISSUE TITLE
Failed to pull image "aerokube/selenoid:nc": Error response from daemon: manifest for aerokube/selenoid:nc not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by riraga001m** [aerokube/selenoid#1256]
![image](https://user-images.githubusercontent.com/93780328/184191992-a6bc7386-fa7c-4e33-8f59-38482acede66.png)

**Comment by engeen** [comment]
What s was the problem?

**Comment by vania-pooh** [comment]
@engeen `--vnc` does not equal to `-vnc` (with one dash). Using `-vnc` is the same as `--version nc` which does not exist.
