### ISSUE TITLE
Requested Environment is Not Available (Windows 10)

### ISSUE THREAD

**Issue by Iskandar0019** [aerokube/selenoid#1259]
Hi,

I am using Selenium 4.3.0, Selenoid 1.10.8, MS Edge 104.0, and getting the following error when I run from C# solution:

OpenQA.Selenium.WebDriverArgumentException: Requested environment is not available at MainTestSelenium_Parallel.Web3Functions.OpenBrowserAdvanced(String browser, String uRL, String options, String preferences, String extension, String networkProfile) in D:\BuildAreas\Selenium-Parallel\Source\MainTestSelenium_Parallel\WebFunctions.cs:line 3033 Additional info:Web3Functions.OpenBrowserAdvanced("msedge","**URL I'm using**","ms:inPrivate= true","","","");

I saw there was a similar issue here:

https://github.com/aerokube/selenoid/issues/114#issue-234426314

Thanks!

**Comment by Iskandar0019** [comment]
Hi Vania, yes, the version is 104.0 in browsers.json.

**Comment by vania-pooh** [comment]
@Iskandar0019 make sure you have this version in the following address output:
```
http://localhost:4444/status
```
If you don't - make sure you are editing correct file (on Windows default is `c:\Users\<user>\.aerokube\selenoid\browsers.json`).

**Comment by Iskandar0019** [comment]
Thanks @vania-pooh , this helped.
