### ISSUE TITLE
traceparent header not forwarded to browser container

### ISSUE THREAD

**Issue by davidamir10** [aerokube/selenoid#1260]
Hello,
we are using opentelemetry and instrumenting urllib3  in pytest. Each request on the remote web-driver has traceparent header
https://www.w3.org/TR/trace-context/#traceparent-header-field-values
It seems that selenoid is not forwarding the header to the browser, so we are not able to see the traces coming from backend.

Can you please include the traceparent header (if exist) in the request to the browser?

**Comment by vania-pooh** [comment]
@davidamir10 Selenoid is reverse proxying all requests except new session request. Could you please provide an exact HTTP request header that you want to reverse proxy?

**Comment by davidamir10** [comment]
@vania-pooh, thanks for quick respones! 
here's an examle traceparent header:
traceparent: 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01

the header key is traceparent

**Comment by vania-pooh** [comment]
Need to proxy `Tracestate` and `Traceparent` headers.
