### ISSUE TITLE
can not upload file in webdriverio with selenoid

### ISSUE THREAD

**Issue by halit-carbon** [aerokube/selenoid#1262]
I wrote some upload file test cases in webdriverio. When I run selenoid in docker , selenoid can not find the path of the file. But the same code work in the selenium grid.

-enable-file-upload added to selenoid.

Chrome 104
Selenoid : latest 

await this.uploadImage.click();
const remoteFilePath = await browser.uploadFile('usr/lib/wdio/src/common/resources/logo.jpeg');

**Comment by vania-pooh** [comment]
@halit-carbon this flag is only needed when Docker containers are not used and for Firefox only. Need an exact error message.

**Comment by halit-carbon** [comment]
I know but I wanted to give more detail. exact error message is "can't find the logo.jpeg". But I control that the file is exist.

**Comment by vania-pooh** [comment]
@halit-carbon this file exists in your test project but probably don't exist in container where browser is running.

**Comment by halit-carbon** [comment]
I understand, I need to add volume between containers to get file. Am I right?

**Comment by vania-pooh** [comment]
@halit-carbon no, Selenium protocol supports remote file upload out of the box. https://webdriver.io/blog/2019/06/25/file-upload/

**Comment by dothebart** [comment]
hm, read through this, but couldn't find the way how to achieve that from the python selenium bindings?

However, https://github.com/aerokube/selenoid/blob/master/docs/browsers-configuration-file.adoc says that one can:
```
    "volumes": ["/from:/to", "/another:/one:ro"],
```
but how to specify `$(pwd)` for that? need to sed-generate `browser.json` then?

So is there a way to substitute things into the `browser.json`? Like `@ENV_VAR@/bla/:/foo` ?

**Comment by vania-pooh** [comment]
@dothebart Selenoid itself does not support `$PWD`. You could use third-party tools like `sed` to do substitution.
