### ISSUE TITLE
How to attach Fake Video Chrome browser capability to selenoid docker container 

### ISSUE THREAD

**Issue by HarryFree** [aerokube/selenoid#1263]
Hi,

I am working on WebRTC (video conferencing application) where I will add fake video and audio capability to chrome browser. 

NodePackage: `https://github.com/JustSittinHere/wdio-selenoid-standalone-service`

Capabilities: 
```
        '--autoplay-policy=no-user-gesture-required',
        '--use-fake-ui-for-media-stream',
        '--use-fake-device-for-media-stream',
        '--allow-file-access-from-files',
        '--use-file-for-fake-video-capture=<videoFullPath.y4m>'
        '--use-file-for-fake-audio-capture=<audioFullPath.wav>'
```

When I run the tests in local, It is playing the video but when run tests on Selenoid Docker containers, Video and Audio are not attached. 

Note: I use the exact configuration from the service as mentioned below and logs are not generated. Would be nice if you guide me how to add the logs

```
services: [
        [
            'selenoid-standalone', { 
                pathToBrowsersConfig: './browsers.json',
                skipAutoPullImages: 'false',
                customSelenoidContainerName: 'wdio-selenoid',
                terminateWdioOnError: true,
                selenoidVersion: 'latest-version',
                port: 4444,
                dockerArgs: ['-rm'],
                selenoidArgs: ['-limit', '10'],
            },
        ],
    ],
```

In Selenoid Container - (Video icon is blocked)

<img width="454" alt="image" src="https://user-images.githubusercontent.com/107098655/189032673-5c47d521-4103-498a-a79f-b8489212232f.png">

In Local machine

<img width="917" alt="image" src="https://user-images.githubusercontent.com/107098655/189033037-998e3d00-91c9-4d42-b7b1-2a33a16390ec.png">

**Comment by vania-pooh** [comment]
@HarryFree at least you have to use `volumes` functionality in `browsers.json` to make your video available inside browser container. https://aerokube.com/selenoid/latest/#_browsers_configuration_file

**Comment by HarryFree** [comment]
@vania-pooh Thanks for your message. As instructed, I pass the video and audio in volumes and still i am facing the same issue. Also I tried to pass the chrome browser capability as new path `/opt/docker/video/video.y4m`, it doesn't work. Could you please point me what I am doing wrong here.

```
"chrome": {
        "default": "100.0",
        "versions": {
            "100.0": {
                "image": "sskorol/selenoid_chromium_vnc:100.0",
                "port": "4444",
                "path": "/",
                "screen": "1920x1080x24",
                "volumes": [
                    "/Users/automation/resources/videos/video.y4m:/opt/docker/video",
                    "/Users/automation/resources/videos/audio.wav:/opt/docker/audio"
                ]
            }
        }
    },
```

**Comment by HarryFree** [comment]
Sorry my bad. I should send only one and it is working fine.

```
"chrome": {
        "default": "100.0",
        "versions": {
            "100.0": {
                "image": "sskorol/selenoid_chromium_vnc:100.0",
                "port": "4444",
                "path": "/",
                "screen": "1920x1080x24",
                "volumes": [
                    "/Users/automation/resources/videos:/opt/docker/video"
                ]
            }
        }
    },
```

**Comment by vania-pooh** [comment]
@HarryFree so this is resolved?

**Comment by HarryFree** [comment]
@vania-pooh Yes, Thank you.

**Comment by HarryFree** [comment]
@vania-pooh it stopped working again :(
