### ISSUE TITLE
Windows Container[OS] to access browsers

### ISSUE THREAD

**Issue by Redinbox** [aerokube/selenoid#1266]
Hello,
we have a requirement to test application on different browsers on windows OS but unfortunately our machines are iOS. so we are planning to go with solenoid but we do not have an idea ,how to do setup of windows OS ?

can you please assist me to do setup.

currently in our iOS , installed docker and solenoid and able to access browser images by default ..but we need these images on windows containers.

**Comment by vania-pooh** [comment]
@Redinbox Selenoid runs browsers in Docker containers and Docker is Linux-only, so it is just impossible to run Windows browsers in Docker containers. You have two options:

1) Build Windows containers using these [instructions](https://github.com/aerokube/windows-images/). But this will anyway be slow and will require 2 times more CPUs and memory.
2) Use Selenoid without Docker as explained [here](https://aerokube.com/selenoid/latest/#_using_selenoid_without_docker).

**Comment by Redinbox** [comment]
Thanks you @vania-pooh , I will try it
