### ISSUE TITLE
Exract info in console rusing Selenium Devtools

### ISSUE THREAD

**Issue by Vijay2871** [aerokube/selenoid#1267]
I have successfully got the logs but unable to parse the json object in selenium in below screenshot

![image](https://user-images.githubusercontent.com/54226136/191148219-e8372e19-1a04-4955-9937-4564ee32c672.png)

Orginal console looks like 
![image](https://user-images.githubusercontent.com/54226136/191148484-f2f2018c-454b-4ac8-ba80-f0177b74a43f.png)

Expanded info below i need to extract
![image](https://user-images.githubusercontent.com/54226136/191148057-194694cb-632d-46be-b133-03ad9ae0f79d.png)

**Comment by vania-pooh** [comment]
@Vijay2871 Selenoid does not support Selenium 4 Devtools feature.

**Comment by Vijay2871** [comment]
> @Vijay2871 Selenoid does not support Selenium 4 Devtools feature. Respective issue #1063.

This is serenity

**Comment by vania-pooh** [comment]
@Vijay2871 `HasDevTools` interface anyway comes from Selenium 4 client.
