### ISSUE TITLE
Is it now possible to run electron app with selenoid?

### ISSUE THREAD

**Issue by chernyshov-dmitrii** [aerokube/selenoid#1270]
I have a problem with running electron based tests with selenoid.
I extends chrome image by adding my built electron app (based on chrome) for unix (.AppImage file)
Configured driver capabilities with binary path to my electron app.
And tried '--no-sandbox' and "--disable-dev-shm-usage" args for driver.
My driver settings

```
let driver = new Builder()
        .usingServer("http://localhost:4444/wd/hub")
        .withCapabilities({
            'goog:chromeOptions': {
                binary: '/usr/bin/client.AppImage',
                'args': ['--no-sandbox', "--disable-dev-shm-usage"],
            },
            enableVNC: true,
            screenResolution: "1920x1080x24",
        }).forBrowser("chrome").build();
```

To extend image I jist simple copy my directory with electron app to selenoid/chrome image
dockerfile:
```
FROM selenoid/chrome:83.0
COPY . /usr/bin
```

created image I named 'electron/chrome'
browsers.json
```
{
    "chrome": {
        "default": "83.0",
        "versions": {
            "83.0": {
                "image": "electron/chrome",
                "port": "4444",
                "path": "/"
            }
        }
    }
}
```

 As a result I see next error

```
WebDriverError: unknown error: Chrome failed to start: exited abnormally.
         (unknown error: DevToolsActivePort file doesn't exist)
```

May be somebody faced with this issue too and know ways to resolve it?

**Comment by vania-pooh** [comment]
@chernishow-dima couldn't it be that our overwrote some necessary system files with this COPY instruction?

**Comment by chernishow-dima** [comment]
> @chernishow-dima couldn't it be that our overwrote some necessary system files with this COPY instruction?

I just tried to COPY only my "client.AppImage" file to the root any directories and still gets the same error

**Comment by vania-pooh** [comment]
@chernishow-dima don't have a lot of experience with Electron. Are there any specific requirements like GPU support?
