### ISSUE TITLE
Not able to perform Keyboard actions in selenoid

### ISSUE THREAD

**Issue by steenpjames5** [aerokube/selenoid#1272]
I'm using js based script(wedriverIO) to automate the web browser. I'm trying to perform the page-down key press using the following snippet.

await browser.keys("PageDown")

The script is executed successfully, but there is no action taken from the selenoid.
The same code will work in my local browser.

**Comment by steenpjames5** [comment]
@vania-pooh Thank you very much for the replay.

I have tried my selenium script in both Selenoid and local browsers. ln local browser the key press is working. But in the Selenoid it's printing a "?" mark on the input field. Here is the code which I'm tried. 

```
import java.io.File;
import java.io.IOException;
import java.net.URL;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;  
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import javax.imageio.ImageIO;

  
public class selenoidTest{  
  
    public static void main(String[] args) throws IOException {  
    	
    	String nodeURL = "localhost:4444/wd/hub";
    	 ChromeOptions options = new ChromeOptions();
    	 options.addArguments("enableVNC=true");
    	 

    // declaration and instantiation of objects/variables  
    System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");  
    //WebDriver driver=new ChromeDriver();  
      
    WebDriver driver = new RemoteWebDriver(new URL(nodeURL), options);
    
    // Launch website  
    driver.navigate().to("http://www.google.com/");  
          
    // Click on the search text box and send value  
    driver.findElement(By.xpath("//input[@title='Search']")).sendKeys("javatpoint");  
          
    // key press actions  
    driver.findElement(By.xpath("//input[@title='Search']")).sendKeys(Keys.ENTER);    
    driver.findElement(By.xpath("//body")).sendKeys(Keys.chord(Keys.CONTROL, "a"));    
    Screenshot screenshot=new AShot().takeScreenshot(driver); 
    
    //screenshot
    ImageIO.write(screenshot.getImage(),"PNG",new File("D:\\screenshot.png"));
   
    }   
}  
```
Here is the result- We are expecting an "Enter" key and "Alt+a" (Select all) after the input text. But printed a "?" mark instead of key presses. **Please let me know, If I'm missing anything on the capabilities side**

![screenshot](https://user-images.githubusercontent.com/87768673/197945603-ecf278e5-7a51-4002-9ae2-463540aec821.png)

**Comment by vania-pooh** [comment]
@steenpjames5 shouldn't you change focus to `body` element first before sending `Ctrl+A`?

**Comment by steenpjames5** [comment]
@vania-pooh I have tried using `body` still, the keystrokes (Enter, Ctrl, etc) are not working.
