### ISSUE TITLE
Selenoid: Requested environment is not available

### ISSUE THREAD

**Issue by ltoczek** [aerokube/selenoid#1273]
I tried to run script from inteliiJ. I think that i did all configuration. My script
WebDriver driver2;

    @BeforeEach
    public void setUp() throws MalformedURLException {

        ChromeOptions chromeOptions = new ChromeOptions();
        WebDriverManager.chromedriver().setup();
        chromeOptions.addArguments("--disable-notifications");
        chromeOptions.addArguments("start-maximized");
        chromeOptions.setCapability("enableVNC",true);
        chromeOptions.setCapability("enableVideo", true);
        chromeOptions.setExperimentalOption("videoName","TestsVideo.mp4");

        driver2 = new RemoteWebDriver(new URL(" http://localhost:4444/wd/hub/"),chromeOptions);
    }

    @Test
    public void method()
    {
        driver2.get("https://www.onet.pl/");
        driver2.quit();
    }

but in console after running script i get error:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Requested environment is not available
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'POL-5M4XVG3', ip: '192.168.0.149', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-notifications, start-maximized], extensions: [], videoName: TestsVideo.mp4}}], desiredCapabilities=Capabilities {browserName: chrome, enableVNC: true, enableVideo: true, goog:chromeOptions: {args: [--disable-notifications, start-maximized], extensions: [], videoName: TestsVideo.mp4}}}]
Capabilities {}

and when type get logs from powershell i get

2022/10/21 17:55:13 [-] [INIT] [Loading configuration files...]
2022/10/21 17:55:13 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2022/10/21 17:55:13 [-] [INIT] [Video Dir: /opt/selenoid/video]
2022/10/21 17:55:13 [-] [INIT] [Your Docker API version is 1.41]
2022/10/21 17:55:13 [-] [INIT] [Timezone: UTC]
2022/10/21 17:55:13 [-] [INIT] [Listening on :4444]
2022/10/21 17:55:45 [-] [SHUTTING_DOWN] [5m0s]
2022/10/21 17:55:57 [-] [INIT] [Loading configuration files...]
2022/10/21 17:55:57 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2022/10/21 17:55:57 [-] [INIT] [Video Dir: /opt/selenoid/video]
2022/10/21 17:55:57 [-] [INIT] [Your Docker API version is 1.41]
2022/10/21 17:55:57 [-] [INIT] [Timezone: UTC]
2022/10/21 17:55:57 [-] [INIT] [Listening on :4444]
2022/10/21 17:57:32 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/10/21 17:57:32 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/10/21 17:57:32 [0] [LOCATING_SERVICE] [chrome] []
2022/10/21 17:57:32 [-] [DEFAULT_VERSION] [Using default version: 106.0]
2022/10/21 17:57:32 [0] [ENVIRONMENT_NOT_AVAILABLE] [chrome] []
2022/10/21 18:05:40 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/10/21 18:05:40 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/10/21 18:05:40 [4] [LOCATING_SERVICE] [chrome] [latest]
2022/10/21 18:05:40 [4] [USING_DOCKER] [chrome] [latest]
2022/10/21 18:05:40 [4] [CREATING_CONTAINER] [selenoid/chrome]
2022/10/21 18:05:40 [4] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/chrome:latest]

WHAT I AM DOING WRONG?

**Comment by vania-pooh** [comment]
@ltoczek you don't have image `selenoid/chrome:latest` in your Docker. Need to pull it - Selenoid never does this automatically.
```
$ docker pull selenoid/chrome:latest
```

**Comment by ltoczek** [comment]
Hi, thanks for responding. I type belew command, but stil lit doesnt work:(

**Comment by vania-pooh** [comment]
@ltoczek probably you have to switch Docker for Windows to Linux mode.

**Comment by ltoczek** [comment]
Hi it seems it is working, but not way i wanted
***@***.***

When i turn off enableVideo everything is working fine, but i want recordigs and when i type enablevideo as true i get error
rg.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: start video container: create video container: Error response from daemon: No such image: selenoid/video-recorder:latest-release
