### ISSUE TITLE
timeZone, enableVNC capabilities are not passed

### ISSUE THREAD

**Issue by StanislavKharchenko** [aerokube/selenoid#1275]
Pre-conditions:
- selenium-webdriver for JS 4.5.0
- selenoid, run under Docker (linux container under Docker Desktop)

Scenario:
1. Create new driver using remote selenoid url, and pass capabilities with timeZone other than timeZone where browser started:
```
const driver = new Builder()
     .usingServer(this.config_.selenoidAddress)
     .withCapabilities({
         timeZone: 'Europe/Madrid',
         enableVNC: true,
         ...capabilities
     })
     .build();
```
2. Start any web-application using web driver created in step#1 and observe timezone
Expected: the browser displays timezone from capabilities;
Problem: the browser displays timezone from server machine (default UTC from docker container)

The problem not reproduced with selenium-webdriver 4.4.0
Perhaps this related to selenium commit?
https://github.com/SeleniumHQ/selenium/commit/fa6deeea6bda1e73317157845772e114bd569b7d

I can't reproduce this with selenium grid, but looks like these capabilities are suitable only for selenoid?

**Comment by StanislavKharchenko** [comment]
Got an answer from Selenium team, that now any non-w3c capabilities should be send with specific suffix, and this works if use "selenoid: options" for timeZone.
I found an alternate if add TZ to browsers.json "ENV" section. But looks like this doesn't work with Edge.
@vania-pooh could you please assist is there possible way to set custom timezone from browsers.json for edge? Or any other similar way?

Thanks in advance

**Comment by vania-pooh** [comment]
@StanislavKharchenko yes, correct answer is using `env` key under `browsers.json` or `env` capability under `selenoid:options`. So far as Edge for Linux is using the same Chromium engine, TZ environment variable should work. What kind of value are your trying to pass?

**Comment by StanislavKharchenko** [comment]
It was a problem with "Europe/Kyiv" timezone.
Edge accepts "Europe/Kiev", but Chrome "Europe/Kyiv".
Closing this issue.

**Comment by vania-pooh** [comment]
@StanislavKharchenko eah, probably their timezone databases differ.
