### ISSUE TITLE
How to build an IE and safari browser docker image with VNC function???

### ISSUE THREAD

**Issue by suzhenyu006** [aerokube/selenoid#1277]
How to build an IE and safari browser docker image with VNC function???

Currently I can't see IMAGE with VNC from the official website

![image](https://user-images.githubusercontent.com/38517127/199941126-84374f60-983f-426d-b4f1-0d62cb58b6b7.png)

**Comment by vania-pooh** [comment]
@suzhenyu006 all Edge images contain VNC by default. IE is deprecated by Microsoft a few months ago.
