### ISSUE TITLE
FAILED_TO_STOP_VIDEO_CONTAINER. Videos are not recorded in selenoid

### ISSUE THREAD

**Issue by TatsianaZ** [aerokube/selenoid#1278]
I have the following images:
![image](https://user-images.githubusercontent.com/30373875/200184853-cd427ec7-dad9-43d6-a213-efdcb8e5924b.png)

My run container commands:

PS C:\> cd c:\selenoid
PS C:\selenoid> $current = $PWD -replace "\\", "/" -replace "C", "c"
PS C:\selenoid> echo $current
c:/selenoid
PS C:\selenoid> docker run -d --name selenoid -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v ${current}/config/:/etc/selenoid/:ro -v /c/selenoid/video/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_OUTPUT_DIR=/c/selenoid/video/ aerokube/selenoid:latest-release
7d04a39cc0fa80f17e4e4461c5acf898f0d9c510a8e7c0bbc0e98d1423c3d6df
PS C:\selenoid> docker run --rm -d --name selenoid-ui --link selenoid -p 8090:8080 aerokube/selenoid-ui --selenoid-uri=http://selenoid:4444
7db5f5587d009f9e4c631e717698cf44a2d4e1a1a0ed8dbacb7becfae2b1c1bf

Tests are running, but videos are not recorded, please see my log below:
![image](https://user-images.githubusercontent.com/30373875/200184933-94af0ad8-7214-417f-967f-547fd028e59a.png)

Win 10

**Comment by vania-pooh** [comment]
@TatsianaZ could be a Windows WSL related directory permissions issues.

**Comment by TatsianaZ** [comment]
Can I update this some how? I have the following check in settings:
![image](https://user-images.githubusercontent.com/30373875/201343817-1ee80c79-46b5-4920-816b-2f4717c77f36.png)

**Comment by vania-pooh** [comment]
@TatsianaZ probably if you turn it off, Selenoid will work.

**Comment by Bohatov** [comment]
Yep, need to unselect WSL and turn on Hyper-V on windows and no more error
