### ISSUE TITLE
Waiting time in queue

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#1279]
Hi,

we have a lot of tests and the queue of selenoid is working fine, but we would like to have tests to stay longer in queue.
Today it seems like there is some timeout that causes the error message `Reason is: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.` when there is not free spot in queue after about 180 seconds. But we could not find a setting to change to a longer waiting time as our queue might get pretty long and ressources are limited.

Currently we start selenoid like this:
```
docker run -d --name selenoid --restart=always -p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v $aerokubeFolder/selenoid/config/:/etc/selenoid/:ro \
-v $aerokubeFolder/selenoid/video/:/opt/selenoid/video/ \
-v $aerokubeFolder/selenoid/logs/:/opt/selenoid/logs/ \
-e OVERRIDE_VIDEO_OUTPUT_DIR=$aerokubeFolder/selenoid/video/ \
aerokube/selenoid:1.10.7 \
-limit 2 -cpu 1.0 -mem 1g -retry-count 10 -capture-driver-logs -timeout 300s -service-startup-timeout 300s -session-attempt-timeout 300s -session-delete-timeout 300s -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -video-recorder-image selenoid/video-recorder:latest-release -log-output-dir /opt/selenoid/logs/
```

Changing any or all timeout parameters to 10s doesnt help.

Our current solution to this is, to create the driver in a retry loop until some maximum retry limit is hit. But this has the drawback, that every new driver creation will be added to the end of the queue. Staying in queue and just wait a custom timeout would be way more useful.

Any solution to this problem?

**Comment by vania-pooh** [comment]
@benzman81 you have to increase HTTP client timeout in your code.
```
NettyClient.Factory httpClientFactory = new NettyClient.Factory() {
    @Override
    public HttpClient createClient(ClientConfig config) {
        return super.createClient(config.readTimeout(Duration.ofMinutes(3)));
    }
};
CommandExecutor commandExecutor = new HttpCommandExecutor(Collections.emptyMap(), new URL(“http://localhost:4444/wd/hub”), httpClientFactory);
WebDriver driver = new RemoteWebDriver(commandExecutor, browser);
```

**Comment by benzman81** [comment]
@vania-pooh thank you, that works.

Just as reference, code can be simplified by using this:
```
ClientConfig config = ClientConfig.defaultConfig().baseUrl(new URL("http://localhost:4444/wd/hub")).readTimeout(Duration.ofMinutes(5));
return new RemoteWebDriver(new HttpCommandExecutor(config), capabilities);
```
