### ISSUE TITLE
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.

### ISSUE THREAD

**Issue by Anand9177** [aerokube/selenoid#1282]
Hello,
I am using eclipse tool with selenium java, while I am running the code I am getting this issue and the chrome driver is correct.But i am not understanding how to solve this issue.
![Screenshot 2022-11-21 at 8 34 19 AM](https://user-images.githubusercontent.com/118704580/202954817-a5cbe963-1cae-4799-9628-b0b2e88d8e9b.png)

**Comment by vania-pooh** [comment]
@Anand9177 are you using Selenoid at all with your code? So far as I can see on the screenshot Chrome is being launched locally whereas Selenoid is launching browsers in container.
