### ISSUE TITLE
Errors running tests in multiple threads

### ISSUE THREAD

**Issue by cybertuck** [aerokube/selenoid#1284]
When run tests in 1 thread it works quick and w/o any issue. I have VNC and session logs enabled
Once I run in two threads it fails with multiple errors (like org.openqa.selenium.NoSuchSessionException: session timed out or not found). Also in some sessions browser window does not open in full. For some sessions screen shows only 'data;' (like in https://github.com/aerokube/selenoid/issues/622)
From what I see in VNC console browser actions are extremely slow. 
I`ve applied recommended Docker settings for mac address to match docker0 with ens192. Storage type is overlay2.
I set timeouts: ./cm selenoid start --vnc --args "-timeout 300s -service-startup-timeout 90s -session-attempt-timeout 90s -cpu 1"
It didn`t help. From 24 tests 21 is failing to execute.

**Session log (that is whole log) do not write messages except chrome driver started:**
2022-11-25T15:10:19.490810501Z 2022/11/25 15:10:19 [INIT] [Listening on :7070]
2022-11-25T15:10:19.512447389Z 19
2022-11-25T15:10:19.521803974Z Waiting X server...
2022-11-25T15:10:19.637563082Z Waiting X server...
2022-11-25T15:10:19.642904581Z Logging to: /dev/null
2022-11-25T15:10:19.745193575Z Waiting X server...
2022-11-25T15:10:19.884815799Z Starting ChromeDriver 105.0.5195.19 (b9c217c128c16f53d12f9a02933fcfdec1bf49af-refs/branch-heads/5195@{https://github.com/aerokube/selenoid/issues/176%7D) on port 4444
2022-11-25T15:10:19.884864811Z All remote connections are allowed. Use an allowlist instead!
2022-11-25T15:10:19.884871094Z Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-11-25T15:10:19.888345911Z ChromeDriver was started successfully.
2022-11-25T15:10:19.888913590Z
2022-11-25T15:10:19.888929950Z --- x11vnc loop: 1 ---
2022-11-25T15:10:19.888935534Z
2022-11-25T15:10:20.390196443Z --- x11vnc loop: waiting for: 142
2022-11-25T15:10:20.390216254Z
2022-11-25T15:10:20.577341831Z PORT=5900

**docker ps**
CONTAINER ID   IMAGE                      COMMAND                  CREATED       STATUS                 PORTS                    NAMES
d76eac317ac3   aerokube/selenoid:1.10.8   "/usr/bin/selenoid -…"   2 hours ago   Up 2 hours             0.0.0.0:4444->4444/tcp   selenoid
9f20b88b1033   aerokube/selenoid-ui       "/selenoid-ui --sele…"   2 hours ago   Up 2 hours (healthy)   0.0.0.0:8088->8080/tcp   selenoid-ui

**docker version**
Client: Docker Engine - Community
Version: 20.10.18
API version: 1.40
Go version: go1.18.6
Git commit: b40c2f6
Built: Thu Sep 8 23:11:56 2022
OS/Arch: linux/amd64
Context: default
Experimental: true

Server: Docker Engine - Community
Engine:
Version: 19.03.15
API version: 1.40 (minimum version 1.12)
Go version: go1.13.15
Git commit: 99e3ed8919
Built: Sat Jan 30 03:15:19 2021
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.2.6
GitCommit: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc:
Version: 1.0.0-rc8
GitCommit: 425e105d5a03fabd737a126ad93d62a9eeede87f
docker-init:
Version: 0.18.0
GitCommit: fec3683

**docker inspect selenoid**
[
    {
        "Id": "d76eac317ac3d3641f86d659a8f11f5690da2ee959876ef37649ee741819b197",
        "Created": "2022-11-25T13:48:43.253292112Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-listen",
            ":4444",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-timeout",
            "300s",
            "-service-startup-timeout",
            "90s",
            "-session-attempt-timeout",
            "90s",
            "-cpu",
            "1",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-video-recorder-image",
            "selenoid/video-recorder:latest-release",
            "-log-output-dir",
            "/opt/selenoid/logs/",
            "-container-network",
            "selenoid"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 21672,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-11-25T13:48:43.787401391Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:3b109a9b5eaae76baeca5e2d7e138f8cbfa9b9f66a6ff06a597b5f679fc93050",
        "ResolvConfPath": "/var/lib/docker/containers/d76eac317ac3d3641f86d659a8f11f5690da2ee959876ef37649ee741819b197/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/d76eac317ac3d3641f86d659a8f11f5690da2ee959876ef37649ee741819b197/hostname",
        "HostsPath": "/var/lib/docker/containers/d76eac317ac3d3641f86d659a8f11f5690da2ee959876ef37649ee741819b197/hosts",
        "LogPath": "/var/lib/docker/containers/d76eac317ac3d3641f86d659a8f11f5690da2ee959876ef37649ee741819b197/d76eac317ac3d3641f86d659a8f11f5690da2ee959876ef37649
ee741819b197-json.log",
        "Name": "/selenoid",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/root/.aerokube/selenoid:/etc/selenoid:ro,Z",
                "/root/.aerokube/selenoid/video:/opt/selenoid/video:Z",
                "/root/.aerokube/selenoid/logs:/opt/selenoid/logs:Z",
                "/var/run/docker.sock:/var/run/docker.sock:Z"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "selenoid",
            "PortBindings": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/44508ee506617ce62e0b7525f9bba847469c1241c4cdfc9b221d8c7eddcfb37f-init/diff:/var/lib/docker/overlay2/44a47dd893
c611f302102cdc91d5c1fc22de35bef5d566974c38df8d2b656232/diff:/var/lib/docker/overlay2/0412bb5c11e4fa8e2fa397e1b050cddde3ba9421c8f103101cf6b34cbec0f966/diff:/var/lib/
docker/overlay2/ba373c5e1f8971f001aadabd0dcd89a87424ecb8ac73ad33706069a86af2e95e/diff",
                "MergedDir": "/var/lib/docker/overlay2/44508ee506617ce62e0b7525f9bba847469c1241c4cdfc9b221d8c7eddcfb37f/merged",
                "UpperDir": "/var/lib/docker/overlay2/44508ee506617ce62e0b7525f9bba847469c1241c4cdfc9b221d8c7eddcfb37f/diff",
                "WorkDir": "/var/lib/docker/overlay2/44508ee506617ce62e0b7525f9bba847469c1241c4cdfc9b221d8c7eddcfb37f/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/root/.aerokube/selenoid/video",
                "Destination": "/opt/selenoid/video",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/root/.aerokube/selenoid/logs",
                "Destination": "/opt/selenoid/logs",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/root/.aerokube/selenoid",
                "Destination": "/etc/selenoid",
                "Mode": "ro,Z",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "localhost",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "OVERRIDE_VIDEO_OUTPUT_DIR=/root/.aerokube/selenoid/video",
                "DOCKER_API_VERSION=1.40",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "-timeout",
                "300s",
                "-service-startup-timeout",
                "90s",
                "-session-attempt-timeout",
                "90s",
                "-cpu",
                "1",
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/",
                "-video-recorder-image",
                "selenoid/video-recorder:latest-release",
                "-log-output-dir",
                "/opt/selenoid/logs/",
                "-container-network",
                "selenoid"
            ],
            "Image": "aerokube/selenoid:1.10.8",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "38b9344e492731d613c7aed47d1d8f72ba4456e9e60652058b3434b69ab0a2f4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/38b9344e4927",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "selenoid": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "d76eac317ac3"
                    ],
                    "NetworkID": "ce6ec4a75c44c7078ed2660df293c7f8a06173aa1dfae766012fcd2e5a6b5537",
                    "EndpointID": "ee0b694f2348cf7f7607746d8491425c31e687dd25cb73dded4fb50b923ee832",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }

    "chrome": {
        "default": "106.0",
        "versions": {
            "105.0": {
                "image": "selenoid/chrome:105.0",
                "port": "4444",
                "path": "/",
                "volumes": ["//sambaShare/files:/wd/hub/etc/"]
            },
            "106.0": {
                "image": "selenoid/chrome:106.0",
                "port": "4444",
                "path": "/",
                "volumes": ["//sambaShare/files:/wd/hub/etc/"]
            }
        }
    },

**wd/hub/status**
{"value":{"message":"Selenoid 1.10.8 built at 2022-07-12_12:47:46PM","ready":true}}

**parallel configuration from pom.xml**
                <configuration>
                    <redirectTestOutputToFile>true</redirectTestOutputToFile>
                    <runOrder>alphabetical</runOrder>
                    <perCoreThreadCount>false</perCoreThreadCount>
                    <parallel>classes</parallel>
                    <threadCountClasses>2</threadCountClasses>
                </configuration>

**Comment by cybertuck** [comment]
Linux VM where I`m running it has 4 cores and 9Gb of free space. I`m not sure whether I define tmps or shm size arguments when run selenoid.

**Comment by vania-pooh** [comment]
@cybertuck make sure you set `-limit` flag e.g. to the value from ~10 to 16. Default limit is 5, so only 5 containers will be allowed to run by Selenoid. https://aerokube.com/selenoid/latest/#_selenoid_cli_flags

**Comment by vania-pooh** [comment]
@cybertuck in your previous comment you have these containers:
```
885e116fdb38 quirky_liskov 0.12% 227.5MiB / 15.51GiB 1.43% 114kB / 22.6kB 0B / 5.96MB 100
f3fb811cc40e wizardly_stonebraker 0.16% 265.7MiB / 15.51GiB 1.67% 2.38MB / 62.5kB 0B / 8.5MB 103
ed931437ca49 elastic_hodgkin 0.06% 268.9MiB / 15.51GiB 1.69% 2.29MB / 49kB 0B / 7.88MB 115
32f235147686 gallant_gagarin 33.04% 398.8MiB / 15.51GiB 2.51% 2.29MB / 52.2kB 0B / 7.06MB 126
628db2deb921 quizzical_proskuriakova 35.37% 327.8MiB / 15.51GiB 2.06% 2.29MB / 50.3kB 0B / 5.74MB 128
```
They all seem to be browser containers. With default limit of 5 you have exactly 5 browser containers running. So any new requests for browsers will wait in queue until these are removed.
