### ISSUE TITLE
wait: http://172.17.0.3:4444/ does not respond in 30s

### ISSUE THREAD

**Issue by suzhenyu006** [aerokube/selenoid#1287]
use ./cm selenoid start --port 4444 vnc

log here:

2022/12/08 04:15:58 [-] [INIT] [Loading configuration files...]
2022/12/08 04:15:58 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2022/12/08 04:15:58 [-] [INIT] [Video Dir: /opt/selenoid/video]
2022/12/08 04:15:58 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2022/12/08 04:15:58 [-] [INIT] [Using Docker API version: 1.41]
2022/12/08 04:15:58 [-] [INIT] [Timezone: UTC]
2022/12/08 04:15:58 [-] [INIT] [Listening on :4444]
2022/12/08 04:17:01 [-] [NEW_REQUEST] [unknown] [10.2.131.82]
2022/12/08 04:17:01 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.2.131.82]
2022/12/08 04:17:01 [0] [LOCATING_SERVICE] [chrome] [100.0]
2022/12/08 04:17:01 [0] [USING_DOCKER] [chrome] [100.0]
2022/12/08 04:17:01 [0] [CREATING_CONTAINER] [selenoid/vnc_chrome:100.0]
2022/12/08 04:17:01 [0] [STARTING_CONTAINER] [selenoid/vnc_chrome:100.0] [b317506c6e1e01397194fe804384c84fd467098d6b0af5962f0847069f76fd3f]
2022/12/08 04:17:02 [0] [CONTAINER_STARTED] [selenoid/vnc_chrome:100.0] [b317506c6e1e01397194fe804384c84fd467098d6b0af5962f0847069f76fd3f] [0.35s]
2022/12/08 04:17:02 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/12/08 04:17:02 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [dfcd929e052b0826ed27785c6e5062482e3b02645025c1dddfe14c1d29dfe75b]
2022/12/08 04:17:02 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [dfcd929e052b0826ed27785c6e5062482e3b02645025c1dddfe14c1d29dfe75b] [0.29s]
2022/12/08 04:17:32 [0] [STOPPING_VIDEO_CONTAINER] [dfcd929e052b0826ed27785c6e5062482e3b02645025c1dddfe14c1d29dfe75b]
2022/12/08 04:17:33 [0] [REMOVING_CONTAINER] [dfcd929e052b0826ed27785c6e5062482e3b02645025c1dddfe14c1d29dfe75b]
2022/12/08 04:17:33 [0] [FAILED_TO_REMOVE_CONTAINER] [dfcd929e052b0826ed27785c6e5062482e3b02645025c1dddfe14c1d29dfe75b] [Error: No such container: dfcd929e052b0826ed27785c6e5062482e3b02645025c1dddfe14c1d29dfe75b]
2022/12/08 04:17:33 [0] [REMOVING_CONTAINER] [b317506c6e1e01397194fe804384c84fd467098d6b0af5962f0847069f76fd3f]
2022/12/08 04:17:33 [0] [CONTAINER_REMOVED] [b317506c6e1e01397194fe804384c84fd467098d6b0af5962f0847069f76fd3f]
2022/12/08 04:17:33 [0] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.3:4444/ does not respond in 30s]

help please

**Comment by suzhenyu006** [comment]
> @suzhenyu006 you have to set Selenoid `-container-network` command-line flag to the network where Selenoid is running.

./cm selenoid start --port 4444 vnc --args "-container-network default" 
I start with cm, not have this parameter "-container-network"

**Comment by suzhenyu006** [comment]
@vania-pooh help me please

**Comment by suzhenyu006** [comment]
someone help me!!

i made a network named selenoid by docker

and then i used command :

./cm selenoid start --config-dir /data/apps/selenoid/ --browsers-json /data/apps/selenoid/browsers.json --vnc --port 4444 --args "-limit 2 -timeout 3m -log-output-dir /data/apps/selenoid/logs/ -video-output-dir /data/apps/selenoid/video/ -session-attempt-timeout 2m -service-startup-timeout 2m -container-network selenoid"

but still not working , got same error

**Comment by suzhenyu006** [comment]
version: '3'
services:
  selenoid:
    deploy:
      mode: global
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid
    ports:
      - "4444:4444"
    volumes:
      - "/data/apps/selenoid/:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/apps/selenoid/video:/opt/selenoid/video"
      - "/data/apps/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/data/apps/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid","-limit","2","-timeout","3m"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]


networks:
  selenoid:
    external:
      name: selenoid # This assumes network is already created


use this docker-compose still not working!!!!!!

**Comment by suzhenyu006** [comment]
i  found some error when i use :
docker run --rm -it --privileged selenoid/chrome:latest



ERROR:

Digest: sha256:e773ec23ce677b0eb167ea55186616b55d65b9b654b3fc1383cb28bdd30b9446
Status: Downloaded newer image for selenoid/chrome:latest
mkdir: cannot create directory '/home/selenium/pulse': Permission denied
/entrypoint.sh: line 67: /home/selenium/pulse/.config/pulse/cookie: No such file or directory
E: [autospawn] core-util.c: Failed to create secure directory (/home/selenium/pulse/.config/pulse): No such file or directory
W: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
E: [pulseaudio] main.c: Failed to acquire autospawn lock
Failed to create secure directory (/home/selenium/pulse/.config/pulse): No such file or directory
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
2022/12/09 06:29:32 [INIT] [Listening on :7070]
Waiting X server...
Logging to: /dev/null
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
feh WARNING: Can't write to /home/selenium/.fehbg
/usr/bin/fbsetbg: 159: cannot create /home/selenium/.fluxbox/lastwallpaper.tmp: Permission denied
mv: cannot stat '/home/selenium/.fluxbox/lastwallpaper.tmp': No such file or directory
/usr/bin/fbsetbg: 168: cannot create /home/selenium/.fluxbox/lastwallpaper: Permission denied

**Comment by suzhenyu006** [comment]
i solve this problem by my own!

**Comment by edsherwin** [comment]
> 

Hi @suzhenyu006, may I know your fix on your error. Thanks

**Comment by jfholanda** [comment]
I have the same error, @suzhenyu006 Can you help me?
