### ISSUE TITLE
Manual debugging page, timeout

### ISSUE THREAD

**Issue by madeying** [aerokube/selenoid#1288]
Hi
In order to release resources in time，I set the timeout when I start the browser，`timeout=2min`。
But，When I was on the manual debugging page, the vnc page broke in 2 minutes。
How do I set the timeout period for manual debugging。

**Comment by vania-pooh** [comment]
@madeying this is not supported. Manual session timeout is 1 hour.

**Comment by madeying** [comment]
Thank you for your answer.
another question. Using Configuration Items,`    capabilities = {
        "browserName": "chrome", 
        "version": "106.0",  
        "env": ["CHROME_LOG_FILE=/dev/stdout"]
    }
CHROME_LOG_FILE` I got the browser log.
Which configuration is available to get the network request log?

**Comment by vania-pooh** [comment]
@madeying you should use Chrome Developer Tools to get network requests.

**Comment by madeying** [comment]
Thank you for your help. Thank you
