### ISSUE TITLE
Login in Chrome using devTools() setExtraHTTPHeaders()

### ISSUE THREAD

**Issue by andrewGaara** [aerokube/selenoid#1289]
We have test sites that require an authorization
![auth](https://user-images.githubusercontent.com/120683091/207960840-a5965d36-eb03-47ae-a8f3-10fce4e7dc2e.jpg)

I'm trying login on site using devtools protocol but i dont know how exacly.

If i use selenium 4 devtools localy code like this works:

```
    @Test
    public void localChromeLoginTest() throws MalformedURLException {
        driver = createLocalChromeDriver();
        var augmenter = new Augmenter();
        driver = augmenter.augment(driver);

        var devTools = ((HasDevTools) driver).getDevTools();
        devTools.createSession();

        driver = augmenter.
            addDriverAugmentation("chrome", HasAuthentication.class, (caps, exec) ->
                (whenThisMatches, useTheseCredentials) -> {
                    devTools.getDomains().network().addAuthHandler(whenThisMatches, useTheseCredentials);
                }).augment(driver);

        ((HasAuthentication) driver).register(UsernameAndPassword.of(username, password));

        driver.get("URL HERE");
    }
```

I could not find any example how to do this with selenoid devtools protocol.
I found only [https://github.com/aerokube/chrome-developer-tools-protocol-java-example/blob/master/src/test/java/com/aerokube/selenoid/ChromeDevtoolsTest.java](https://github.com/aerokube/chrome-developer-tools-protocol-java-example/blob/master/src/test/java/com/aerokube/selenoid/ChromeDevtoolsTest.java).
But there is no example, no documentation.

I have tried something like this:

```
    @Test
    public void chromeStartTest3() throws MalformedURLException, WebSocketServiceException, URISyntaxException {
        driver = createRemoteChromeDriver();

        var id = ((RemoteWebDriver) driver).getSessionId();
        var devToolsUrl = String.format("wss://selenoid.domain/devtools/%s/page", id);

        devtools = ChromeDevToolsService.from(devToolsUrl);

        var n = devtools.getNetwork();

        var logon = Base64.getEncoder().encode("%s:%s".formatted(username, password).getBytes(StandardCharsets.UTF_8));
        n.setExtraHTTPHeaders(Map.of("Authorization", "Basic " + new String(logon)));

        n.enable();
        // n.enable(100000, 100000, 100000);

        driver.get("URL HERE");
    }
```

in diffrent variation but no luck.

Could someone help me, please :)

**Comment by vania-pooh** [comment]
@andrewGaara I think you just have to use username and password when opening the main page. In that case all background requests will use the same credentials.

**Comment by andrewGaara** [comment]
@vania-pooh URL https://username:password@site.com does not work. Site uses NTLM type authorization, so there is no  login page. I dont know how exacly i can "just have to use username and password".

**Comment by vania-pooh** [comment]
@andrewGaara probably you may need to set some browser preferences using Selenium capabilities or even do manual modifications in our images. We never said NTLM will work out of the box.

**Comment by andrewGaara** [comment]
I found solution through dynamically creating extension for autofill login and password.
