### ISSUE TITLE
@vania-pooh Found an easier solution.

### ISSUE THREAD

**Issue by madeying** [aerokube/selenoid#1290]
@vania-pooh Found an easier solution.
Checked out it for chrome. If setting the CHROME_LOG_FILE environment variable to /home/selenium/Downloads you can grab it through the downloads API. Or even better, if setting the env variable to /dev/stdout you will get the logs automatically saved by Selenoid.

_Originally posted by @kornel-filep in https://github.com/aerokube/selenoid/issues/1082#issuecomment-816726051_

**Comment by vania-pooh** [comment]
@madeying so, where is the issue?
