### ISSUE TITLE
Network container to be a an actually container/Browsers.json

### ISSUE THREAD

**Issue by Anticope12** [aerokube/selenoid#1293]
Hi team,

I was able to make Selenoid/and the UI run through Container as network... not :container network.

The issue I'm facing at the moment, I'm not able to create sessions for the following reason:

`2023/01/05 00:14:16 [190] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: conflicting options: hostname and the network mode]

The command I'm using inside yaml is :          "-container-network","container:gluetun", 
"gluetun" it's not a network container, it's an actual VPN container. 

I've tried to use a Container network but there was no way to mask the IP. the only option was to use the above case. 

Passing the browser container to run through the VPN container.

I'm not sure if anyone has a better work around or a solution for that. 
`

**Comment by Anticope12** [comment]
I think I've found the issues related to network issue. 

If anyone has any insights would really appreciate that

**Comment by vania-pooh** [comment]
@Anticope12 we are only testing Selenoid in bridge Docker network and never tested it in other types of Docker networks.
