### ISSUE TITLE
Video is not recorded at all

### ISSUE THREAD

**Issue by SRVFLLN** [aerokube/selenoid#1295]
Hi! I'm trying to get some practice with selenoid, and i read about video recording feauture, but i can't use it. I added capabilty "enableVideo" but nothing happened. 
I'm using Win10, code written on C# and selenoid started with cm.exe.
Here is how my driver initialized:
```
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("--disable-notifications");
            options.AddAdditionalOption("enableVideo", true);
            options.AddAdditionalOption("enableLog", true);
            options.AddAdditionalOption("videoCodec", "mpeg4");
            options.BrowserVersion = "104.0";
            var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), options);
```

This's container list without running any test:

![image](https://user-images.githubusercontent.com/93190152/211000979-4019278f-5fd9-4d0e-820a-ed063374bd9a.png)

And when test is running:

![image](https://user-images.githubusercontent.com/93190152/211001106-acc2c61b-5916-404c-8a4e-cdd9d23892cf.png)

Also, here are the selenoid logs(which, by the way, are not recorded on the host machine either):
![image](https://user-images.githubusercontent.com/93190152/211001335-662aec5d-7791-4cbe-a4f1-757714786549.png)

I tried to start the recorder container manually, but it's just 'sleeping' all the time:
![image](https://user-images.githubusercontent.com/93190152/211001613-1ef975a0-7034-4e57-bad7-d1200ac533c6.png)

What am i doing wrong?

**Comment by SRVFLLN** [comment]
I changed driver initializing to this: 
```
ChromeOptions options = new ChromeOptions();
            options.AddArgument("--disable-notifications");
            Dictionary<string, object> keyValues = new Dictionary<string, object>() 
            {
                {"enableVideo", true},
                {"enableVNC", true},
                { "enableLog", true },
                { "videoCodec", "mpeg4"}
            };
            options.AddAdditionalOption("selenoid:options", keyValues);
            options.BrowserVersion = "104.0";
            var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), options);
```

And now logs are saved on the host machine, and vnc works. But video still not recorded.
![image](https://user-images.githubusercontent.com/93190152/211010407-bb183204-8253-42f0-90c4-ea66cb4b8c5c.png)

**Comment by vania-pooh** [comment]
@SRVFLLN `OVERRIDE_VIDEO_OUTPUT_DIR=/c/users/hp/desktop/selenoid/` this is set automatically by CM, so no need to set this value manually. Probably there is a typo in `aerokube \ aerocube` somewhere.

**Comment by SRVFLLN** [comment]
@vania-pooh I tried to get the video container logs, because it stops 2 seconds after starting, and here's what I got before it closed

![videocontainerlogs](https://user-images.githubusercontent.com/93190152/211501929-fcedd619-9103-491e-9b5d-425414b66298.png)

**Comment by vania-pooh** [comment]
@SRVFLLN this is probably Windows permissions issue. Make sure writing is allowed to this directory.
