### ISSUE TITLE
Couldn't create a session for microsoft edge v107. Response code 500.

### ISSUE THREAD

**Issue by sachinhr10** [aerokube/selenoid#1296]
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Microsoft Edge failed to start: crashed.
 (chrome not reachable)
 (The process started from msedge location /usr/bin/microsoft-edge is no longer running, so msedgedriver is assuming that msedge has crashed.)
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: '', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

Docker image used : /browsers/edge  107.0
Issue with manually creating the session on selenoid ui as well as automation.

**Comment by vania-pooh** [comment]
<img width="881" alt="Screen Shot 2023-01-10 at 18 13 21" src="https://user-images.githubusercontent.com/829320/211588872-9ad8685c-79b2-4de2-8be0-07e18242c38b.png">
Manual session works on my Mac.

**Comment by sachinhr10** [comment]
Try creating new Selenoid docker environment and launch a session. That might recreate the issue.

**Comment by vania-pooh** [comment]
@sachinhr10 I installed a fresh instance of Selenoid and Selenoid UI before trying.
