### ISSUE TITLE
How to save session metadata?

### ISSUE THREAD

**Issue by MaxoH4uk** [aerokube/selenoid#1297]
Hi guys. I read in selenoid documentation that it is possible to save session metadata.

 I see a note that "This feature only becomes available when Selenoid is compiled with metadata build tag (missing by default)."

I want to use this feature, but I don't really understand what exactly I need to do to create a json file.

At the moment, the logs are written in the following format:

Initialize...

Connecting to ws://SOME_URL/ws/logs/f7c432a927fdd6b90fd68849d96b5709...
Connected!
20
Waiting X server...
2023/01/13 12:21:50 [INIT] [Listening on :7070]
Logging to: /dev/null
Waiting X server...
Starting ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

 --- x11vnc loop: 1 ---

 --- x11vnc loop: waiting for: 182

PORT=5900

**Comment by vania-pooh** [comment]
@MaxoH4uk you should compile binary:
```
$ go build -tags s3,metadata
```
