### ISSUE TITLE
How to set mem limit for Selenoid process itself

### ISSUE THREAD

**Issue by sergey-chechaev** [aerokube/selenoid#1298]
How to set limit for selenoid process itself? We find that selenoid process has memory leak if it lives very long time:

```
 systemctl status selenoid
● selenoid.service - Selenoid
     Loaded: loaded (/etc/systemd/system/selenoid.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-05-23 15:41:25 MSK; 7 months 24 days ago
   Main PID: 1328 (selenoid)
      Tasks: 17 (limit: 28789)
     Memory: 11.2G
```

![telegram-cloud-photo-size-2-5343683527138461167-y](https://user-images.githubusercontent.com/4598042/213717703-cc09842a-f27f-4d76-a5af-74d448954cd6.jpg)

Selenoid has the following flags but for container not for selenoid process:

```
-cpu value
    Containers cpu limit as float e.g. 0.2 or 1.0

-mem value
    Containers memory limit e.g. 128m or 1g
```

**Comment by vania-pooh** [comment]
@sergey-chechaev use operating system tools to do this. E.g. when running Selenoid in Docker you have exactly the same flag for `docker run` command.

**Comment by sergey-chechaev** [comment]
> @sergey-chechaev use operating system tools to do this. E.g. when running Selenoid in Docker you have exactly the same flag for `docker run` command.

Yes, I know but system will kill the process if it exceeds the limit.

**Comment by vania-pooh** [comment]
@sergey-chechaev obviously no, this is how Linux kernel works. But Selenoid should not be killed because of OOM. If it's consuming too much memory, you can send `SIGQUIT` to the process and paste goroutines dump here that will be output to Selenoid logs imediately.
