### ISSUE TITLE
Security issues with this container

### ISSUE THREAD

**Issue by elvovsky** [aerokube/selenoid#1300]
The docker desktop now shows that there are 3 security issues in the latest version . Attached is the screenshot,
![2023-01-22 12_16_17-](https://user-images.githubusercontent.com/19784304/213930126-dd3e7938-70be-410b-9f60-a6837e28479d.jpg)

**Comment by vania-pooh** [comment]
@elvovsky there will be more releases this year fixing this.

**Comment by elvovsky** [comment]
@vania-pooh  Thank you ! Just wanted to make sure that you were aware of this.
