### ISSUE TITLE
Getting Internal Server for Chorme Browser 

### ISSUE THREAD

**Issue by ayushi-nyk** [aerokube/selenoid#1303]
Hi Team,

I am getting internal server error for chrome browser , below is my json .
{
    "chrome": {
        "default": "108.0",
        "versions": {
            "108.0": {
                "image": "selenoid/chrome:108.0",
                "port": "4444",
                "path": ""
            },
            "109.0": {
                "image": "selenoid/chrome:109.0",
                "port": "4444",
                "path": "/"
            },
            "64.0": {
                "image": "selenoid/vnc_chrome:64.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "109.0",
        "versions": {
            "109.0": {
                "image": "selenoid/vnc_firefox:109.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
    }

However using same json I am able to launch firefox. Please help.

Please suggest

**Comment by vania-pooh** [comment]
@ayushi-nyk path parameter for Chrome should be `/`.

**Comment by ayushi-nyk** [comment]
@vania-pooh Tried that as well still same issue . 
2023/02/01 07:03:37 [-] [INIT] [Loading configuration files...]
2023/02/01 07:03:37 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2023/02/01 07:03:37 [-] [INIT] [Video Dir: /opt/selenoid/video]
2023/02/01 07:03:37 [-] [INIT] [Your Docker API version is 1.41]
2023/02/01 07:03:37 [-] [INIT] [Timezone: UTC]
2023/02/01 07:03:37 [-] [INIT] [Listening on :4444]
2023/02/01 07:04:50 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2023/02/01 07:04:50 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2023/02/01 07:04:50 [2] [LOCATING_SERVICE] [chrome] [108.0]
2023/02/01 07:04:50 [2] [USING_DOCKER] [chrome] [108.0]
2023/02/01 07:04:50 [2] [CREATING_CONTAINER] [selenoid/chrome:108.0]
2023/02/01 07:04:51 [2] [STARTING_CONTAINER] [selenoid/chrome:108.0] [f762ecde79a197c4754d302fe38c74baaf408fbe8c0a55bcfcc9cbcb1f797e45]
2023/02/01 07:04:51 [2] [CONTAINER_STARTED] [selenoid/chrome:108.0] [f762ecde79a197c4754d302fe38c74baaf408fbe8c0a55bcfcc9cbcb1f797e45] [0.25s]
2023/02/01 07:04:53 [2] [SERVICE_STARTED] [selenoid/chrome:108.0] [f762ecde79a197c4754d302fe38c74baaf408fbe8c0a55bcfcc9cbcb1f797e45] [2.58s]
2023/02/01 07:04:53 [2] [PROXY_TO] [f762ecde79a197c4754d302fe38c74baaf408fbe8c0a55bcfcc9cbcb1f797e45] [http://172.17.0.4:4444]
2023/02/01 07:04:53 [2] [SESSION_ATTEMPTED] [http://172.17.0.4:4444] [1]
2023/02/01 07:04:57 [2] [SESSION_FAILED] [http://172.17.0.4:4444] [500 Internal Server Error]
2023/02/01 07:04:57 [2] [REMOVING_CONTAINER] [f762ecde79a197c4754d302fe38c74baaf408fbe8c0a55bcfcc9cbcb1f797e45]
2023/02/01 07:04:57 [2] [CONTAINER_REMOVED] [f762ecde79a197c4754d302fe38c74baaf408fbe8c0a55bcfcc9cbcb1f797e45]

**Comment by ayushi-nyk** [comment]
@vania-pooh 
Update Json - 
{
    "chrome": {
        "default": "108.0",
        "versions": {
            "108.0": {
                "image": "selenoid/vnc_chrome:108.0",
                "port": "4444",
                "path": "/"
            },
            "109.0": {
                "image": "selenoid/vnc_chrome:109.0",
                "port": "4444",
                "path": "/"
            },
            "64.0": {
                "image": "selenoid/vnc_chrome:64.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "109.0",
        "versions": {
            "109.0": {
                "image": "selenoid/vnc_firefox:109.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
    }

**Comment by ayushi-nyk** [comment]
@vania-pooh Even if i am trying to start the session manually then as well it is throwing same error , however firefox is working fine.

**Comment by vania-pooh** [comment]
@ayushi-nyk if you have Mac M1 then Chrome will not work.

**Comment by ayushi-nyk** [comment]
really .. why so ?

**Comment by ayushi-nyk** [comment]
will it work on linux / ubantu machine @vania-pooh

**Comment by ayushi-nyk** [comment]
@vania-pooh it's not running on mac it is running under docker container then why it wont work . can you please help me to understand . 

is it the case that the docker images - selenoid/vnc_chrome wont support chrome if host machine is mac.

**Comment by ayushi-nyk** [comment]
@vania-pooh I have tried on ubuntu machine as well , there alse firefox driver got created but not chrome - below is the error  logs - 
Exception found  - org.openqa.selenium.InvalidArgumentException: Requested environment is not available
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ip-172-*.*.*', ip: '172.*.*.*', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1021-aws', java.version: '1.8.0_352'
Driver info: driver.version: RemoteWebDriver
remote stacktrace: 
org.openqa.selenium.InvalidArgumentException: Requested environment is not available
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ip-172-*-*-*', ip: '172.*.*.*', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1021-aws', java.version: '1.8.0_352'
Driver info: driver.version: RemoteWebDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at SeleniumTest.main(SeleniumTest.java:20)


Any insight about it .

**Comment by vania-pooh** [comment]
@ayushi-nyk you are providing browser name and version that are not present in Selenoid configuration.

**Comment by ayushi-nyk** [comment]
@vania-pooh even without that it is not working ..

**Comment by ayushi-nyk** [comment]
Exception found  - org.openqa.selenium.InvalidArgumentException: Requested environment is not available
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '', ip: '172.26.12.81', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1021-aws', java.version: '1.8.0_352'
Driver info: driver.version: RemoteWebDriver

**Comment by vania-pooh** [comment]
@ayushi-nyk let's compare your capabilities and `browsers.json` contents here then.

**Comment by ayushi-nyk** [comment]
@vania-pooh - my browsers.json - 
{
  "chrome": {
    "default": "108.0",
    "versions": {
      "108": {
        "image": "selenoid/vnc_chrome:108.0",
        "port": "4444",
        "path": "/"
      },
      "109": {
        "image": "selenoid/vnc_chrome:109.0",
        "port": "4444",
        "path": "/"
      }
    }
  },
  "firefox": {
    "default": "109.0",
    "versions": {
      "109.0": {
        "image": "selenoid/vnc_firefox:109.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  }
}

my code looks like -

import java.net.URL;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class SeleniumTest {
public static void main(String[] args)  {
			try {
			System.out.println("Test Start");
		    DesiredCapabilities caps = new DesiredCapabilities();  
		    
		    System.out.println("created caps");

		    String url = "http://localhost:4444/wd/hub/";
			WebDriver driver = new RemoteWebDriver(new URL(url), caps);
			System.out.println("created remote driver");
			driver.get("https://google.com");
			
			Thread.sleep(2000);

			driver.quit();
			System.out.println("Test End");
			
			}
 catch (Exception e) {
	
System.out.println("Exception found  - " + e);
e.printStackTrace();
 }
}
}

**Comment by ayushi-nyk** [comment]
just to highlight on running the chrome driver locally getting error - ChromeDriver was started successfully.
Exception found  - org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '', ip: ''**, os.name: 'Linux', os.arch: 'amd64',** os.version: '5.15.0-1021-aws', java.version: '1.8.0_352'

But if selenoid uses docker conatiner to run browser then it should be the issue . 

Please suggest .

**Comment by vania-pooh** [comment]
@ayushi-nyk your desired capabilities are empty:
```java
DesiredCapabilities caps = new DesiredCapabilities();
```

At least you should set browser name:

```java
caps.setCapability("browserName", "chrome");
```

This is Selenium basics and not related to Selenoid at all.

**Comment by ayushi-nyk** [comment]
@vania-pooh Even for firefox it works like this only ,in selenium it is not mandate .. 
Still i tried that as well but it is not working

**Comment by ayushi-nyk** [comment]
reference-
public class Test {
public static void main(String[] args)  {
			try {
			System.out.println("Test Start");
             
		   DesiredCapabilities caps = new DesiredCapabilities();  
		caps.setCapability("browserName", "chrome");

		    System.out.println("created options");

		    String url = "http://localhost:4444/wd/hub/";
			    
			WebDriver driver = new RemoteWebDriver(new URL(url), caps);
			
			System.out.println("created remote driver");
			driver.get("https://google.com");
			
			Thread.sleep(2000);

			driver.quit();
			System.out.println("Test End");
			
			}
 catch (Exception e) {
	
System.out.println("Exception found  - " + e);
e.printStackTrace();
 }
}
}

**Comment by ayushi-nyk** [comment]
@vania-pooh I have requirement to run 25-30 test in parallel on Chrome browser on 108 / latest chrome version . Can you please share me detailed documentation to do so if possible so that I can follow that only. I have already check Selenoid official documentation and followed that so far . 
I will be using aws for infra . 

Not able to run chrome browser.

**Comment by vania-pooh** [comment]
@ayushi-nyk to run dozens of tests in parallel with Selenoid you have to start one big VM with 20-30 CPUs and set Selenoid `-limit` flag accordingly or use [Ggr](https://github.com/aerokube/ggr/).
