### ISSUE TITLE
Connecting ipv4 proxies via python 

### ISSUE THREAD

**Issue by poikl246** [aerokube/selenoid#1304]
Please tell me how to connect a proxy to your browser. That is, I am interested in connecting not all containers, but each separately. 

That is, I start a container with a browser in python. 
But I do not really understand how to add a proxy during initialization. I am interested in proxy without authorization, as well as with authorization. 

```
capabilities = {
    "browserName": "firefox",
    "browserVersion": "108.0",
    "selenoid:options": {
        "enableVNC": True,
        "enableVideo": False
    },

}

driver = webdriver.Remote(command_executor="http://127.0.0.1:4444/wd/hub", desired_capabilities=capabilities)
```

Thanks in advance

**Comment by vania-pooh** [comment]
@poikl246 Selenoid is fully W3C compatible WebDriver solution. So you can use standard proxy capabilities: https://stackoverflow.com/questions/17082425/running-selenium-webdriver-with-a-proxy-in-python

**Comment by poikl246** [comment]
Thanks))
