### ISSUE TITLE
Selenoid works improperly with new Docker 23.0

### ISSUE THREAD

**Issue by irublev** [aerokube/selenoid#1306]
Hi Team,

After the latest release of Docker (see https://docs.docker.com/engine/release-notes/23.0/ for details) Selenoid stopped to work propertly being launched in Docker. The problem is that `cm` outputs improperly Docker API version as 1.12 instead of 1.43. Possibly due to this Selenoid can't create browser sessions.

I've solved the issue by rolling back the version of `docker-ce`, may be it can be fixed via setting `DOCKER_API_VERSION` environment variable, but it would be perfect if Selenoid could work with this release of `docker-ce` (and all future releases) smoothly.

Thanks in advance,

**Comment by vania-pooh** [comment]
Yes, we need to support API 1.42.

**Comment by irublev** [comment]
> Yes, we need to support Docker API 1.42.

Thank you so much. But I believe not only 1.42, but also 1.43, it is the latest available version: https://docs.docker.com/engine/api/version-history/

**Comment by vania-pooh** [comment]
@irublev current stable API is 1.42 so updated to this version. Now try with `aerokube/selenoid:latest` image - should work.

**Comment by sereinity** [comment]
> @irublev current stable API is 1.42 so updated to this version. Now try with `aerokube/selenoid:latest` image - should work.

It works, thanks, can we hope to have an official release soon?

**Comment by vania-pooh** [comment]
Released as https://github.com/aerokube/selenoid/releases/tag/1.10.10.
