### ISSUE TITLE
S3 upload doesn't work

### ISSUE THREAD

**Issue by korsar182** [aerokube/selenoid#1311]
Hi,
I've compiled selenoid with s3 build tag and run it with 
`-s3-endpoint https://s3.eu-central-1.amazonaws.com --s3-region eu-central-1 --s3-bucket-name my-bucket --s3-access-key my-access-key --s3-secret-key my-secret-key`

It starts with message:
` Initialized S3 support: endpoint = https://s3.eu-central-1.amazonaws.com, region = eu-central-1, bucketName = my-bucket , accessKey = my-access-key, keyPattern = $fileName, includeFiles = , excludeFiles = , forcePathStyle = false`

But video doesnt upload to bucket. There are no error instead 
`Failed to rename /video/selenoide7c2aae11adef2deabf23c00edda2044.mp4 to /video/test_video_1676646274_953978.mp4: rename /video/selenoide7c2aae11adef2deabf23c00edda2044.mp4 /video/test_video_1676646274_953978.mp4: no such file or directory`

**Comment by vania-pooh** [comment]
@korsar182 you specified OVERRIDE_VIDEO_OUTPUT_DIR variable incorrectly.

**Comment by korsar182** [comment]
Ah, yes, thanks!
