### ISSUE TITLE
Not able to run test cases  from selenoid in gke

### ISSUE THREAD

**Issue by ankitanuj30** [aerokube/selenoid#1312]
i am getting error as 
2023/02/17 18:07:30 [0] [LOCATING_SERVICE] [chrome] []
2023/02/17 18:07:30 [-] [DEFAULT_VERSION] [Using default version: ]
2023/02/17 18:07:30 [0] [ENVIRONMENT_NOT_AVAILABLE] [chrome] []

My browsers.json file looks like this below
{
    "chrome": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": "selenoid/chrome:latest",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "110.0": {
                "image": "selenoid/chrome:110.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
}
Below are the steps i have used for running selenoid
 kubectl create configmap selenoid-browsers-config --from-file=browsers.json=browsers.json -n uap-gke-dev
  kubectl apply -f aerokube.yaml -n=uap-gke-dev 
  kubectl expose deployment selenoid --name="selenoid" --type=ClusterIP --port=4444
   kubectl apply -f vs-sample.yaml -n=uap-gke-dev(exposing as virtual service ->my company mandate)

please let me know where i am going wrong
@vania-pooh  please help me regarding this issue

**Comment by ankitanuj30** [comment]
Hi Team Please help and resolve my issues.

**Comment by vania-pooh** [comment]
@ankitanuj30 we don't recommend to use Selenoid in Kubernetes and never said it will work. https://aerokube.com/selenoid/latest/#_selenoid_in_kubernetes
