### ISSUE TITLE
manifest for docker.io/aerokube/selenoid:latest not found

### ISSUE THREAD

**Issue by rahul-vinaudit** [aerokube/selenoid#1314]
First I tried 
https://github.com/aerokube/selenoid-ui/blob/master/docker-compose.yml

It was working couple of months ago

The above commnad
And
docker pull aerokube/selenoid
Returning
Trying to pull repository docker.io/aerokube/selenoid ... 
manifest for docker.io/aerokube/selenoid:latest not found

But a specific version from history is working
docker pull aerokube/selenoid:1.10.7
Trying to pull repository [docker.io/aerokube/selenoid](http://docker.io/aerokube/selenoid) ...
1.10.7: Pulling from [docker.io/aerokube/selenoid](http://docker.io/aerokube/selenoid)
97518928ae5f: Pull complete
af0870f9b422: Pull complete
dc8779278fdd: Pull complete
Digest: sha256:2e3b71da1f5f5302f239f806cbe9cd6010f9cd8d496d25ade74e89fde8eed1c5
Status: Downloaded newer image for [docker.io/aerokube/selenoid:1.10.7](http://docker.io/aerokube/selenoid:1.10.7)

First I thought the latest tag may not exisit anymore. So I went in there and looked
And found the latest
![image](https://user-images.githubusercontent.com/79594107/221331948-7c9eb156-3ea6-474b-8f19-6d677d012d4c.png)

**Comment by vania-pooh** [comment]
@rahul-vinaudit something on your side. Everything works.
<img width="604" alt="Screen Shot 2023-02-26 at 20 42 45" src="https://user-images.githubusercontent.com/829320/221426994-1b93becf-3af5-4de9-bee4-ee991df9d615.png">
<img width="1253" alt="Screen Shot 2023-02-26 at 20 42 08" src="https://user-images.githubusercontent.com/829320/221426998-b3cd991a-0671-4ceb-b97b-c25d08187729.png">

**Comment by rahul-vinaudit** [comment]
How can it be a problem at my end, when I'm getting error from the server 
Is ti a particular docker version that it supports.
Can you tell me the docker version you are using

**Comment by vania-pooh** [comment]
@rahul-vinaudit already existing layer is `alpine:3` layer.

**Comment by rahul-vinaudit** [comment]
@vania-pooh 

It is working on ubuntu machines but not on the centos machines

  108  yum install docker --assumeyes
  109  systemctl start docker
  110  systemctl enable docker
  111  systemctl status docker
  112  docker pull aerokube/selenoid:latest

**Comment by vania-pooh** [comment]
@rahul-vinaudit we don't have experience with CentOS. Probably they just broke something in Docker package. I tested things on MacOS.

**Comment by rahul-vinaudit** [comment]
@vania-pooh 
Which all linux OS do you support

**Comment by vania-pooh** [comment]
@rahul-vinaudit we test everything on Ubuntu. What you are seeing is a Docker issue, not related to Selenoid at all.
