### ISSUE TITLE
Copy-paste for images

### ISSUE THREAD

**Issue by VinokurovVV** [aerokube/selenoid#1316]
I don’t know if it was originally meant that there would be such an opportunity, since there was nothing of the kind in the documentation, but I had a task to check that the picture was copied to the clipboard, so I tried it. After copying the picture to the clipboard, I follow the link http://selenoid-host.example.com:4444/clipboard/sessionId and see that there is nothing there. Accordingly, I send a request to get the value, nothing is returned to me. When receiving text from the clipboard, I have no such problems. The question is: is it possible to somehow get the copied image from the clipboard, and if this is not possible now, will the feature be added later?

**Comment by vania-pooh** [comment]
@VinokurovVV currently image copy-paste is implemented in Moon only.
