### ISSUE TITLE
Support missing for JSON Version

### ISSUE THREAD

**Issue by LukeIGS** [aerokube/selenoid#1322]
Some clients (for example, [Ferrum ](https://github.com/rubycdp/ferrum) for ruby) utilize this endpoint to gather version information about the browser, as well as the websocket debugger url.

**Comment by vania-pooh** [comment]
Probably we just need to support this: https://github.com/aerokube/selenoid/issues/1063

**Comment by LukeIGS** [comment]
in Ferrum's case at least, it doesn't seem to have any care "where" the websocket endpoint lives.  Selenium for ruby doesn't really care beyond its initial checks either; However, for some reason if you bypass those checks it dies when you attempt to call anything using [The bidirectional api](https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/) with a network timeout.

If you bypass any of that both "will" connect to the endpoint, allowing you to execute raw cdp commands just fine, though for a good connection from Ferrum at least, we would need the json/version endpoint to be supported alongside the current json/protocal as per this spec, as ferrum uses the former to gather version information like the websocket endpoint for the cluster.

```
GET /json/version

{
    "Browser": "Chrome/72.0.3601.0",
    "Protocol-Version": "1.3",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3601.0 Safari/537.36",
    "V8-Version": "7.2.233",
    "WebKit-Version": "537.36 (@cfede9db1d154de0468cb0538479f34c0755a0f4)",
    "webSocketDebuggerUrl": "ws://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8"
}
```

This does of course mean the selenoid would have to know its own external hostname in the event there was some sort of ingressing being used.

**Comment by LukeIGS** [comment]
specs for relevance.
https://chromedevtools.github.io/devtools-protocol

**Comment by LukeIGS** [comment]
Looks like the change would take place here...
https://github.com/aerokube/images/blob/e943c3a5f4706ca3b8a5d284fc09f63b642e0806/static/chrome/devtools/devtools.go#L81

Selenoid's CDP router seems to only define json/protocol, it should probably be more up to the linked specs and support the following at the bare minimum:
`GET /json/list` and `GET /json` - used by multiple cdp clients to get a target list for bidirectional apis
`GET /json/version` - Used to describe version information and websocket location
`WebSocket /devtools/page/{targetId}` - Used to attach to a given taget via websocket

Though it might be a good idea to just follow the specs completely for CDP functionality.

**Comment by vania-pooh** [comment]
@LukeIGS what do you mean by "incoming host"? How is this expected to work when our tools are running behind one or several reverse-proxies and behind a fault-tolerant load balancer?

**Comment by LukeIGS** [comment]
this is all especially try if you're using any sort of https termination, as the proxy would need to forward tls encrypted requests to the service stack in question (be it kubernetes or docker)

**Comment by LukeIGS** [comment]
quick sketch of a go function that would probably do what we need
```go
type versionTransport struct {
	http.RoundTripper
}

func (t *versionTransport) RoundTrip(req *http.Request) (resp *http.Response, err error) {
	resp, err = t.RoundTripper.RoundTrip(req)
	if err != nil {
			return nil, err
	}
	b, err := ioutil.ReadAll(resp.Body)
	if err != nil {
			return nil, err
	}
	err = resp.Body.Close()
	if err != nil {
			return nil, err
	}
	b = bytes.Replace(b, 
		[]byte("\"webSocketDebuggerUrl\": \"ws://localhost:9222"), 
		[]byte( fmt.Sprint("\"webSocketDebuggerUrl\": \"ws://%s", req.Host)), 
		-1,
	)
	body := ioutil.NopCloser(bytes.NewReader(b))
	resp.Body = body
	resp.ContentLength = int64(len(b))
	resp.Header.Set("Content-Length", strconv.Itoa(len(b)))
	return resp, nil
}


func version(w http.ResponseWriter, r *http.Request) {


	h, err := devtoolsHost()
	if err != nil {
		log.Printf("[DEVTOOLS_HOST_ERROR] [%v]", err)
		http.Error(w, fmt.Sprintf("Failed to detect devtools host: %v", err), http.StatusInternalServerError)
		return
	}
	u := &url.URL{
		Host:   h,
		Scheme: "http",
		Path:   "/json/version",
	}
	log.Printf("[PROTOCOL] [%s]", u.String())
	(&httputil.ReverseProxy{
		Director: func(r *http.Request) {
			r.Host = "localhost"
			r.URL = u
		},
		Transport: &versionTransport{http.DefaultTransport},
	}).ServeHTTP(w, r)
}
```

With my (albeit) limited knowledge of go, this function would probably do something akin to what we'd need provided we were working with a proxy that was routing on host alone..

I'm sure someone with better go would be able to write something way better though.

**Comment by andrii-rymar** [comment]
@LukeIGS have you tried to build a custom Selenoid version with the changes you proposed?

**Comment by LukeIGS** [comment]
I have not.

**Comment by Juice10** [comment]
bump

**Comment by vania-pooh** [comment]
PRs are welcome.
