### ISSUE TITLE
[SESSION_FAILED]  [500 Internal Server Error] while running tests in selenoid

### ISSUE THREAD

**Issue by saikrishnapalakollu** [aerokube/selenoid#1325]
I started running tests on selenoid with three browser instances, anyhow they got started by selenoid and added to the docker network but I'm not sure why the session is closing and chrome containers are getting removed. Could you please help me with this

selenoid                    | 2023/03/22 17:24:36 [1] [SESSION_ATTEMPTED] [http://172.26.0.6:4444] [1]
chrome                      | Waiting X server...
selenoid                    | 2023/03/22 17:24:36 [2] [SERVICE_STARTED] [selenoid/chrome:108.0] [78fce558622c4e34fa82f3dbfee798dc8f4216cc9aa0ee9e3bf73cf9316b24cf] [2.75s]
selenoid                    | 2023/03/22 17:24:36 [2] [PROXY_TO] [78fce558622c4e34fa82f3dbfee798dc8f4216cc9aa0ee9e3bf73cf9316b24cf] [http://172.26.0.7:4444]
selenoid                    | 2023/03/22 17:24:36 [2] [SESSION_ATTEMPTED] [http://172.26.0.7:4444] [1]
selenoid                    | 2023/03/22 17:24:36 [0] [SERVICE_STARTED] [selenoid/chrome:108.0] [6a4fa723fa479ae083f6d00f534550e1e67afce6adcbfb92765e412f8d012215] [2.75s]
selenoid                    | 2023/03/22 17:24:36 [0] [PROXY_TO] [6a4fa723fa479ae083f6d00f534550e1e67afce6adcbfb92765e412f8d012215] [http://172.26.0.5:4444]
selenoid                    | 2023/03/22 17:24:36 [0] [SESSION_ATTEMPTED] [http://172.26.0.5:4444] [1]
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
chrome                      | Waiting X server...
selenoid                    | 2023/03/22 17:24:39 [2] [SESSION_FAILED] [http://172.26.0.7:4444] [500 Internal Server Error]
selenoid                    | 2023/03/22 17:24:39 [2] [REMOVING_CONTAINER] [78fce558622c4e34fa82f3dbfee798dc8f4216cc9aa0ee9e3bf73cf9316b24cf]
chrome                      | Waiting X server...
selenoid                    | 2023/03/22 17:24:39 [1] [SESSION_FAILED] [http://172.26.0.6:4444] [500 Internal Server Error]
selenoid                    | 2023/03/22 17:24:39 [1] [REMOVING_CONTAINER] [ba3613adf27c11c2cc5f0cc77f8f6c3255d48eb9f280943aee4feac665dce487]
selenoid                    | 2023/03/22 17:24:39 [0] [SESSION_FAILED] [http://172.26.0.5:4444] [500 Internal Server Error]
selenoid                    | 2023/03/22 17:24:39 [0] [REMOVING_CONTAINER] [6a4fa723fa479ae083f6d00f534550e1e67afce6adcbfb92765e412f8d012215]
chrome                      | Waiting X server...
selenoid                    | 2023/03/22 17:24:39 [2] [CONTAINER_REMOVED] [78fce558622c4e34fa82f3dbfee798dc8f4216cc9aa0ee9e3bf73cf9316b24cf]
selenoid                    | 2023/03/22 17:24:39 [-] [NEW_REQUEST] [unknown] [172.26.0.3]
selenoid                    | 2023/03/22 17:24:39 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.26.0.3]
selenoid                    | 2023/03/22 17:24:39 [3] [LOCATING_SERVICE] [chrome] []
selenoid                    | 2023/03/22 17:24:39 [-] [DEFAULT_VERSION] [Using default version: latest]
selenoid                    | 2023/03/22 17:24:39 [3] [USING_DOCKER] [chrome] [latest]
selenoid                    | 2023/03/22 17:24:39 [3] [CREATING_CONTAINER] [selenoid/chrome:108.0]
selenoid                    | 2023/03/22 17:24:39 [3] [STARTING_CONTAINER] [selenoid/chrome:108.0] [417d1a8b31f4412f46d04753558f003b358be8518b4ea684f8f6e1532fb8952a]

**Comment by vania-pooh** [comment]
@saikrishnapalakollu what kind of error are you getting in tests?
