### ISSUE TITLE
video rename failed cause no such file or dictionary

### ISSUE THREAD

**Issue by suzhenyu006** [aerokube/selenoid#1327]
I started Selenoid using CM, and overwrote the default video storage path, but when a task ended, an error was reported that the video file was not found. The following is the output log of Selenoid：

···
023/03/30 09:50:24 [-] [INIT] [Using Docker API version: 1.41]
2023/03/30 09:50:24 [-] [INIT] [Timezone: UTC]
2023/03/30 09:50:24 [-] [INIT] [Listening on :4444]
2023/03/30 09:51:50 [-] [NEW_REQUEST] [unknown] [10.19.43.154]
2023/03/30 09:51:50 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.19.43.154]
2023/03/30 09:51:50 [0] [LOCATING_SERVICE] [chrome] [101.0]
2023/03/30 09:51:50 [0] [USING_DOCKER] [chrome] [101.0]
2023/03/30 09:51:50 [0] [CREATING_CONTAINER] [selenoid/vnc_chrome:101.0]
2023/03/30 09:51:50 [0] [STARTING_CONTAINER] [selenoid/vnc_chrome:101.0] [57a8fa68185b5b76751cb9adb93cd65f664a7b87031604e9d97ba4e5b89b70dc]
2023/03/30 09:51:50 [0] [CONTAINER_STARTED] [selenoid/vnc_chrome:101.0] [57a8fa68185b5b76751cb9adb93cd65f664a7b87031604e9d97ba4e5b89b70dc] [0.36s]
2023/03/30 09:51:50 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/03/30 09:51:50 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [52d2a818239b4b3e3f17d9cdbc4017f7ba6c5a50d92339b4cdf00a95174b7376]
2023/03/30 09:51:51 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [52d2a818239b4b3e3f17d9cdbc4017f7ba6c5a50d92339b4cdf00a95174b7376] [0.57s]
2023/03/30 09:51:51 [0] [SERVICE_STARTED] [selenoid/vnc_chrome:101.0] [57a8fa68185b5b76751cb9adb93cd65f664a7b87031604e9d97ba4e5b89b70dc] [0.00s]
2023/03/30 09:51:51 [0] [PROXY_TO] [57a8fa68185b5b76751cb9adb93cd65f664a7b87031604e9d97ba4e5b89b70dc] [http://172.17.0.4:4444/]
2023/03/30 09:51:51 [0] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2023/03/30 09:51:52 [0] [SESSION_CREATED] [a8535d93afac3bb6f2ceb066cd48fe46] [1] [1.75s]
2023/03/30 09:56:59 [4164] [SESSION_DELETED] [a8535d93afac3bb6f2ceb066cd48fe46]
2023/03/30 09:56:59 [0] [STOPPING_VIDEO_CONTAINER] [52d2a818239b4b3e3f17d9cdbc4017f7ba6c5a50d92339b4cdf00a95174b7376]
2023/03/30 09:57:00 [0] [REMOVING_CONTAINER] [52d2a818239b4b3e3f17d9cdbc4017f7ba6c5a50d92339b4cdf00a95174b7376]
2023/03/30 09:57:00 [0] [FAILED_TO_REMOVE_CONTAINER] [52d2a818239b4b3e3f17d9cdbc4017f7ba6c5a50d92339b4cdf00a95174b7376] [Error response from daemon: removal of container 52d2a818239b4b3e3f17d9cdbc4017f7ba6c5a50d92339b4cdf00a95174b7376 is already in progress]
2023/03/30 09:57:00 [0] [REMOVING_CONTAINER] [57a8fa68185b5b76751cb9adb93cd65f664a7b87031604e9d97ba4e5b89b70dc]
2023/03/30 09:57:00 [0] [CONTAINER_REMOVED] [57a8fa68185b5b76751cb9adb93cd65f664a7b87031604e9d97ba4e5b89b70dc]
2023/03/30 09:57:00 [0] [VIDEO_ERROR] [Failed to rename /data/apps/selenoid/video/selenoid4d7d695b45a07445ff6aa168a7e82297.mp4 to /data/apps/selenoid/video/chrome982Z.mp4: rename /data/apps/selenoid/video/selenoid4d7d695b45a07445ff6aa168a7e82297.mp4 /data/apps/selenoid/video/chrome982Z.mp4: no such file or directory]
···

The strange thing is that the video storage address I specified has this video. What is the reason?

```
[@jsy19-43-152 /data/apps/selenoid/video]# ls -ll
total 51300
-rw-r--r-- 1 root root  6061329 Mar 30 14:33 selenoid2f04e740e2924418e96f37c946892986.mp4
-rw-r--r-- 1 root root  5052357 Mar 30 16:30 selenoid3eafdd6088457654abfdae3f23754ade.mp4
-rw-r--r-- 1 root root  5030674 Mar 30 17:57 selenoid4d7d695b45a07445ff6aa168a7e82297.mp4
-rw-r--r-- 1 root root 15894839 Dec  9 17:22 selenoid529b1de5f2ab1b8791abbbca9801676e.mp4
-rw-r--r-- 1 root root  6139882 Mar 30 14:34 selenoid8459de847e5fb72108bead8abea1ec31.mp4
-rw-r--r-- 1 root root 14338547 Dec 13 12:56 selenoidf4c92d231db8b4a399d3a1e6260246cf.mp4
```

**Comment by suzhenyu006** [comment]
here is my cm command :

./cm selenoid start --config-dir /data/apps/selenoid/ --browsers-json /data/apps/selenoid/browsers.json --vnc --port 4444 --args "-limit 2 -timeout 3m -log-output-dir /data/apps/selenoid/logs/ -video-output-dir /data/apps/selenoid/video/ -session-attempt-timeout 2m -service-startup-timeout 2m -container-network bridge"

**Comment by vania-pooh** [comment]
@suzhenyu006 just using `--config-dir` should be sufficient. No need to override `-log-output-dir` and other flags as these directories are `inside` container and `--config-dir` is outside.
