### ISSUE TITLE
Video recording error response from daemon: delete container

### ISSUE THREAD

**Issue by se7en8** [aerokube/selenoid#1332]
I use selenoid for testing, and the test samples will simultaneously enable four Google browsers for testing. My Google browser version v106, if the video recording function is not enabled, can complete the testing. However, if the video recording function is enabled, it will cause the container to be deleted. I don't know what data needs to be provided, but I can provide the known detailed configuration. Can you help me check the problem? thank you.

docker-compose.yaml
```
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:1.10.9
    container_name: selenoid
    volumes:
      # - "/path/to/config:/etc/selenoid"
      # - "/var/run/docker.sock:/var/run/docker.sock"
      # - "/path/to/config/video:/opt/selenoid/video"
      # - "/path/to/config/logs:/opt/selenoid/logs"
      - "/root/.aerokube/selenoid:/etc/selenoid"
      - "/root/.aerokube/selenoid/video:/opt/selenoid/video"
      - "/root/.aerokube/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"

    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/root/.aerokube/selenoid/video
      # - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
      # command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    # command: [
    #   "-conf", "/etc/selenoid/browsers.json",
    #   "-video-output-dir", "/opt/selenoid/video",
    #   "-log-output-dir", "/opt/selenoid/logs",
    #   "-capture-driver-logs", "true",
    #   "-graceful-period", "7200s",
    #   "-session-delete-timeout", "7200s",
    #   "--timeout", "1h",
    #   "-limit", "5",
    #   "-disable-queue", "true",
    #   "-session-attempt-timeout", "7200s",
    #   "-timeout", "2m",
    #   "-retry-count", "3"

    # ]
    command: -limit 5 -service-startup-timeout 30m  -session-attempt-timeout 30m -retry-count 3 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video -log-output-dir /opt/selenoid/logs
    ports:
      - "4444:4444"
  
  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    network_mode: bridge
    depends_on:
      - selenoid
    environment:
      - TZ=Asia/Shanghai
    command: ["-period", "5s", "-selenoid-uri", "http://127.0.0.1:4444"]
    ports:
      - "8888:8080"
```

docker logs -f selenoid
```
2023/04/17 01:46:40 [79] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [80] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [81] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [82] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [83] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [84] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [85] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [86] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [87] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:40 [88] [VIDEO_LISTING] [unknown] [172.16.33.160]
2023/04/17 01:46:53 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [92] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/17 01:46:53 [92] [USING_DOCKER] [chrome] [106.0]
2023/04/17 01:46:53 [92] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/17 01:46:53 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [93] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/17 01:46:53 [93] [USING_DOCKER] [chrome] [106.0]
2023/04/17 01:46:53 [93] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/17 01:46:53 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [94] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/17 01:46:53 [94] [USING_DOCKER] [chrome] [106.0]
2023/04/17 01:46:53 [94] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/17 01:46:53 [92] [STARTING_CONTAINER] [selenoid/chrome:106.0] [085bd2197bbf5538924ecd024aa74b7643d97f2a44ed542732a01064cf566e0d]
2023/04/17 01:46:53 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/17 01:46:53 [95] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/17 01:46:53 [95] [USING_DOCKER] [chrome] [106.0]
2023/04/17 01:46:53 [95] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/17 01:46:53 [93] [STARTING_CONTAINER] [selenoid/chrome:106.0] [223bae4b8709fe16361834955b5c6737a4dd7810a8214a52f3ff3c243e7bdb2a]
2023/04/17 01:46:53 [94] [STARTING_CONTAINER] [selenoid/chrome:106.0] [76c5d37442cc626d772a47f29c40296f9bf36febbfa58b19fce4a898f1a91c5b]
2023/04/17 01:46:53 [95] [STARTING_CONTAINER] [selenoid/chrome:106.0] [9fa6c5090edc1d7dcdc93e0f83f65d20f78b319cb6b95418a9c08ee056dcc54a]
2023/04/17 01:46:54 [92] [CONTAINER_STARTED] [selenoid/chrome:106.0] [085bd2197bbf5538924ecd024aa74b7643d97f2a44ed542732a01064cf566e0d] [0.85s]
2023/04/17 01:46:54 [92] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/17 01:46:54 [92] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [0731b42ead575c3012b90a77b97e976e71768a4c2824c0150c5cce977997ea70]
2023/04/17 01:46:54 [93] [CONTAINER_STARTED] [selenoid/chrome:106.0] [223bae4b8709fe16361834955b5c6737a4dd7810a8214a52f3ff3c243e7bdb2a] [1.15s]
2023/04/17 01:46:54 [93] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/17 01:46:55 [93] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [d44087665811e86eaf7bd6d20451b35d1d1e48157813884d29b554e8fc67b77e]
2023/04/17 01:46:55 [94] [CONTAINER_STARTED] [selenoid/chrome:106.0] [76c5d37442cc626d772a47f29c40296f9bf36febbfa58b19fce4a898f1a91c5b] [1.76s]
2023/04/17 01:46:55 [94] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/17 01:46:55 [95] [CONTAINER_STARTED] [selenoid/chrome:106.0] [9fa6c5090edc1d7dcdc93e0f83f65d20f78b319cb6b95418a9c08ee056dcc54a] [1.96s]
2023/04/17 01:46:55 [94] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [3efd898b3d869f78498e32613313fb77044979bbb04eb803bd98fa49bbbef310]
2023/04/17 01:46:55 [95] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/17 01:46:56 [95] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [83f0d097fbf4c55ed331e432d62f185acc09700f3387cb0487bfe8f4e13c375a]
2023/04/17 01:46:57 [93] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [d44087665811e86eaf7bd6d20451b35d1d1e48157813884d29b554e8fc67b77e] [2.13s]
2023/04/17 01:46:57 [92] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [0731b42ead575c3012b90a77b97e976e71768a4c2824c0150c5cce977997ea70] [3.15s]
2023/04/17 01:46:58 [93] [SERVICE_STARTED] [selenoid/chrome:106.0] [223bae4b8709fe16361834955b5c6737a4dd7810a8214a52f3ff3c243e7bdb2a] [1.51s]
2023/04/17 01:46:58 [93] [PROXY_TO] [223bae4b8709fe16361834955b5c6737a4dd7810a8214a52f3ff3c243e7bdb2a] [http://172.17.0.5:4444/]
2023/04/17 01:46:58 [93] [SESSION_ATTEMPTED] [http://172.17.0.5:4444/] [1]
2023/04/17 01:46:58 [92] [SERVICE_STARTED] [selenoid/chrome:106.0] [085bd2197bbf5538924ecd024aa74b7643d97f2a44ed542732a01064cf566e0d] [0.90s]
2023/04/17 01:46:58 [92] [PROXY_TO] [085bd2197bbf5538924ecd024aa74b7643d97f2a44ed542732a01064cf566e0d] [http://172.17.0.4:4444/]
2023/04/17 01:46:58 [92] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2023/04/17 01:46:58 [94] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [3efd898b3d869f78498e32613313fb77044979bbb04eb803bd98fa49bbbef310] [3.05s]
2023/04/17 01:46:58 [95] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [83f0d097fbf4c55ed331e432d62f185acc09700f3387cb0487bfe8f4e13c375a] [3.02s]
2023/04/17 01:46:59 [94] [SERVICE_STARTED] [selenoid/chrome:106.0] [76c5d37442cc626d772a47f29c40296f9bf36febbfa58b19fce4a898f1a91c5b] [0.73s]
2023/04/17 01:46:59 [94] [PROXY_TO] [76c5d37442cc626d772a47f29c40296f9bf36febbfa58b19fce4a898f1a91c5b] [http://172.17.0.6:4444/]
2023/04/17 01:46:59 [94] [SESSION_ATTEMPTED] [http://172.17.0.6:4444/] [1]
2023/04/17 01:46:59 [95] [SERVICE_STARTED] [selenoid/chrome:106.0] [9fa6c5090edc1d7dcdc93e0f83f65d20f78b319cb6b95418a9c08ee056dcc54a] [0.72s]
2023/04/17 01:46:59 [95] [PROXY_TO] [9fa6c5090edc1d7dcdc93e0f83f65d20f78b319cb6b95418a9c08ee056dcc54a] [http://172.17.0.7:4444/]
2023/04/17 01:46:59 [95] [SESSION_ATTEMPTED] [http://172.17.0.7:4444/] [1]
2023/04/17 01:47:09 [92] [SESSION_CREATED] [4ed9d0b10e758b0a7bc185bbac5f3756] [1] [15.84s]
2023/04/17 01:47:11 [94] [SESSION_CREATED] [566cc300fc7d994642440896263c844a] [1] [17.46s]
2023/04/17 01:47:11 [93] [SESSION_CREATED] [4c06e4f84702866af4525d31b7d637e5] [1] [17.59s]
2023/04/17 01:47:12 [95] [SESSION_CREATED] [7424e8050bf084c5011a10e75fa1dcff] [1] [18.73s]
2023/04/17 01:47:44 [123] [CONTAINER_LOGS] [085bd2197bbf5538924ecd024aa74b7643d97f2a44ed542732a01064cf566e0d]
2023/04/17 01:47:44 [124] [VNC_ENABLED] [4ed9d0b10e758b0a7bc185bbac5f3756]
2023/04/17 01:48:09 [102] [SESSION_TIMED_OUT] [4ed9d0b10e758b0a7bc185bbac5f3756]
2023/04/17 01:48:09 [130] [SESSION_DELETED] [4ed9d0b10e758b0a7bc185bbac5f3756]
2023/04/17 01:48:11 [108] [SESSION_TIMED_OUT] [566cc300fc7d994642440896263c844a]
2023/04/17 01:48:11 [131] [SESSION_DELETED] [566cc300fc7d994642440896263c844a]
2023/04/17 01:48:11 [110] [SESSION_TIMED_OUT] [4c06e4f84702866af4525d31b7d637e5]
2023/04/17 01:48:11 [132] [SESSION_DELETED] [4c06e4f84702866af4525d31b7d637e5]
2023/04/17 01:48:11 [124] [VNC_CLIENT_DISCONNECTED] [4ed9d0b10e758b0a7bc185bbac5f3756]
2023/04/17 01:48:11 [124] [VNC_SESSION_CLOSED] [4ed9d0b10e758b0a7bc185bbac5f3756]
2023/04/17 01:48:12 [115] [SESSION_TIMED_OUT] [7424e8050bf084c5011a10e75fa1dcff]
2023/04/17 01:48:12 [134] [SESSION_DELETED] [7424e8050bf084c5011a10e75fa1dcff]
2023/04/17 01:48:30 [94] [STOPPING_VIDEO_CONTAINER] [3efd898b3d869f78498e32613313fb77044979bbb04eb803bd98fa49bbbef310]
2023/04/17 01:48:34 [93] [STOPPING_VIDEO_CONTAINER] [d44087665811e86eaf7bd6d20451b35d1d1e48157813884d29b554e8fc67b77e]
2023/04/17 01:48:35 [95] [STOPPING_VIDEO_CONTAINER] [83f0d097fbf4c55ed331e432d62f185acc09700f3387cb0487bfe8f4e13c375a]
2023/04/17 01:48:36 [92] [STOPPING_VIDEO_CONTAINER] [0731b42ead575c3012b90a77b97e976e71768a4c2824c0150c5cce977997ea70]
2023/04/17 01:48:39 [94] [REMOVING_CONTAINER] [3efd898b3d869f78498e32613313fb77044979bbb04eb803bd98fa49bbbef310]
2023/04/17 01:48:39 [94] [FAILED_TO_REMOVE_CONTAINER] [3efd898b3d869f78498e32613313fb77044979bbb04eb803bd98fa49bbbef310] [Error response from daemon: removal of container 3efd898b3d869f78498e32613313fb77044979bbb04eb803bd98fa49bbbef310 is already in progress]
2023/04/17 01:48:39 [94] [REMOVING_CONTAINER] [76c5d37442cc626d772a47f29c40296f9bf36febbfa58b19fce4a898f1a91c5b]
2023/04/17 01:48:40 [94] [CONTAINER_REMOVED] [76c5d37442cc626d772a47f29c40296f9bf36febbfa58b19fce4a898f1a91c5b]
2023/04/17 01:48:41 [93] [REMOVING_CONTAINER] [d44087665811e86eaf7bd6d20451b35d1d1e48157813884d29b554e8fc67b77e]
2023/04/17 01:48:41 [93] [FAILED_TO_REMOVE_CONTAINER] [d44087665811e86eaf7bd6d20451b35d1d1e48157813884d29b554e8fc67b77e] [Error response from daemon: removal of container d44087665811e86eaf7bd6d20451b35d1d1e48157813884d29b554e8fc67b77e is already in progress]
2023/04/17 01:48:41 [93] [REMOVING_CONTAINER] [223bae4b8709fe16361834955b5c6737a4dd7810a8214a52f3ff3c243e7bdb2a]
2023/04/17 01:48:42 [93] [CONTAINER_REMOVED] [223bae4b8709fe16361834955b5c6737a4dd7810a8214a52f3ff3c243e7bdb2a]
2023/04/17 01:48:42 [95] [REMOVING_CONTAINER] [83f0d097fbf4c55ed331e432d62f185acc09700f3387cb0487bfe8f4e13c375a]
2023/04/17 01:48:42 [95] [FAILED_TO_REMOVE_CONTAINER] [83f0d097fbf4c55ed331e432d62f185acc09700f3387cb0487bfe8f4e13c375a] [Error response from daemon: removal of container 83f0d097fbf4c55ed331e432d62f185acc09700f3387cb0487bfe8f4e13c375a is already in progress]
2023/04/17 01:48:42 [95] [REMOVING_CONTAINER] [9fa6c5090edc1d7dcdc93e0f83f65d20f78b319cb6b95418a9c08ee056dcc54a]
2023/04/17 01:48:42 [95] [CONTAINER_REMOVED] [9fa6c5090edc1d7dcdc93e0f83f65d20f78b319cb6b95418a9c08ee056dcc54a]
2023/04/17 01:48:43 [92] [REMOVING_CONTAINER] [0731b42ead575c3012b90a77b97e976e71768a4c2824c0150c5cce977997ea70]
2023/04/17 01:48:43 [92] [FAILED_TO_REMOVE_CONTAINER] [0731b42ead575c3012b90a77b97e976e71768a4c2824c0150c5cce977997ea70] [Error response from daemon: removal of container 0731b42ead575c3012b90a77b97e976e71768a4c2824c0150c5cce977997ea70 is already in progress]
2023/04/17 01:48:43 [92] [REMOVING_CONTAINER] [085bd2197bbf5538924ecd024aa74b7643d97f2a44ed542732a01064cf566e0d]

```

browser.json
```
{
    "chrome": {
        "default": "102.0",
        "versions": {
            "101.0": {
                "image": "selenoid/chrome:101.0",
                "port": "4444",
                "path": "/",
                "shmSize": 2147483648
            },
            "102.0": {
                "image": "selenoid/chrome:102.0",
                "port": "4444",
                "path": "/",
                "shmSize": 2147483648
            },
            "106.0": {
                "image": "selenoid/chrome:106.0",
                "port": "4444",
                "path": "/",
                "shmSize": 2147483648
            }

        }
    },
    "firefox": {
        "default": "101.0",
        "versions": {
            "100.0": {
                "image": "selenoid/firefox:100.0",
                "port": "4444",
                "path": "/wd/hub",
                "mem" : "512m"
            },
            "101.0": {
                "image": "selenoid/firefox:101.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },
    "opera": {
        "default": "88.0",
        "versions": {
            "86.0": {
                "image": "selenoid/opera:86.0",
                "port": "4444",
                "path": "/"
            },
            "88.0": {
                "image": "selenoid/opera:88.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}


```

**Comment by se7en8** [comment]
My server configuration is 2-core 8g
My operating system CentOS Linux release 7.2.1511 (Core) 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2

**Comment by vania-pooh** [comment]
@se7en8 this is weird Docker behavior. You can ignore these messages.

**Comment by se7en8** [comment]
But my test will terminate abnormally, and I cannot find the reason. I can only preliminarily find that it was caused by video recording, as my load has not increased and I have not yet reached the bottleneck. @vania-pooh

**Comment by vania-pooh** [comment]
@se7en8 what is an exact error message in your test?

**Comment by se7en8** [comment]
This is the output of the console when I try to run it:
`2023/04/23 09:39:02 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/23 09:39:02 [30719] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/23 09:39:02 [30719] [USING_DOCKER] [chrome] [106.0]
2023/04/23 09:39:02 [30719] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/23 09:39:03 [30719] [STARTING_CONTAINER] [selenoid/chrome:106.0] [43b8c7094f6ed70227f26201ab6a773a6402ab0d9ab8f8759abd8467bd652948]
2023/04/23 09:39:03 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/23 09:39:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/23 09:39:03 [30720] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/23 09:39:03 [30720] [USING_DOCKER] [chrome] [106.0]
2023/04/23 09:39:03 [30720] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/23 09:39:03 [30720] [STARTING_CONTAINER] [selenoid/chrome:106.0] [c9533e7f162c32156582b79bd1c0e114266c4146a7895137eb53111456a7f03d]
2023/04/23 09:39:03 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/23 09:39:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/23 09:39:03 [30721] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/23 09:39:03 [30721] [USING_DOCKER] [chrome] [106.0]
2023/04/23 09:39:03 [30721] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/23 09:39:03 [30721] [STARTING_CONTAINER] [selenoid/chrome:106.0] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57]
2023/04/23 09:39:03 [-] [NEW_REQUEST] [unknown] [10.14.1.6]
2023/04/23 09:39:03 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.14.1.6]
2023/04/23 09:39:03 [30722] [LOCATING_SERVICE] [chrome] [106.0]
2023/04/23 09:39:03 [30722] [USING_DOCKER] [chrome] [106.0]
2023/04/23 09:39:03 [30722] [CREATING_CONTAINER] [selenoid/chrome:106.0]
2023/04/23 09:39:03 [30722] [STARTING_CONTAINER] [selenoid/chrome:106.0] [0385bc94a5458e3998302a9b4aa6f67cd271915f772cdc1c46bc4f29d834a26c]
2023/04/23 09:39:03 [30719] [CONTAINER_STARTED] [selenoid/chrome:106.0] [43b8c7094f6ed70227f26201ab6a773a6402ab0d9ab8f8759abd8467bd652948] [0.58s]
2023/04/23 09:39:03 [30719] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/23 09:39:03 [30719] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [6ee586fc99d7da7e299850740eba807b3387efcd888a1552a66d1e0f5b012746]
2023/04/23 09:39:03 [30720] [CONTAINER_STARTED] [selenoid/chrome:106.0] [c9533e7f162c32156582b79bd1c0e114266c4146a7895137eb53111456a7f03d] [0.75s]
2023/04/23 09:39:03 [30720] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/23 09:39:04 [30720] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [f588be1113b30514deb08656697b6b5fda3466d826a388125a634ad50684a441]
2023/04/23 09:39:04 [30721] [CONTAINER_STARTED] [selenoid/chrome:106.0] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57] [1.01s]
2023/04/23 09:39:04 [30721] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/23 09:39:04 [30721] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [003e6f741447862a066e69ce2f35c12632c1cfeb74f65e4ee343ac8240f95312]
2023/04/23 09:39:04 [30722] [CONTAINER_STARTED] [selenoid/chrome:106.0] [0385bc94a5458e3998302a9b4aa6f67cd271915f772cdc1c46bc4f29d834a26c] [1.31s]
2023/04/23 09:39:04 [30722] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2023/04/23 09:39:04 [30722] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [550a9a6a0283fa44ad6dbcd6a3c9ba0b13a07f1663618630e04dc81066ba6c60]
2023/04/23 09:39:05 [30719] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [6ee586fc99d7da7e299850740eba807b3387efcd888a1552a66d1e0f5b012746] [1.61s]
2023/04/23 09:39:05 [30720] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [f588be1113b30514deb08656697b6b5fda3466d826a388125a634ad50684a441] [1.41s]
2023/04/23 09:39:05 [30721] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [003e6f741447862a066e69ce2f35c12632c1cfeb74f65e4ee343ac8240f95312] [1.29s]
2023/04/23 09:39:05 [30722] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [550a9a6a0283fa44ad6dbcd6a3c9ba0b13a07f1663618630e04dc81066ba6c60] [0.84s]
2023/04/23 09:39:06 [30719] [SERVICE_STARTED] [selenoid/chrome:106.0] [43b8c7094f6ed70227f26201ab6a773a6402ab0d9ab8f8759abd8467bd652948] [1.29s]
2023/04/23 09:39:06 [30719] [PROXY_TO] [43b8c7094f6ed70227f26201ab6a773a6402ab0d9ab8f8759abd8467bd652948] [http://172.17.0.4:4444/]
2023/04/23 09:39:06 [30719] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2023/04/23 09:39:07 [30720] [SERVICE_STARTED] [selenoid/chrome:106.0] [c9533e7f162c32156582b79bd1c0e114266c4146a7895137eb53111456a7f03d] [1.70s]
2023/04/23 09:39:07 [30720] [PROXY_TO] [c9533e7f162c32156582b79bd1c0e114266c4146a7895137eb53111456a7f03d] [http://172.17.0.5:4444/]
2023/04/23 09:39:07 [30720] [SESSION_ATTEMPTED] [http://172.17.0.5:4444/] [1]
2023/04/23 09:39:07 [30721] [SERVICE_STARTED] [selenoid/chrome:106.0] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57] [2.11s]
2023/04/23 09:39:07 [30721] [PROXY_TO] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57] [http://172.17.0.6:4444/]
2023/04/23 09:39:07 [30721] [SESSION_ATTEMPTED] [http://172.17.0.6:4444/] [1]
2023/04/23 09:39:08 [30722] [SERVICE_STARTED] [selenoid/chrome:106.0] [0385bc94a5458e3998302a9b4aa6f67cd271915f772cdc1c46bc4f29d834a26c] [2.36s]
2023/04/23 09:39:08 [30722] [PROXY_TO] [0385bc94a5458e3998302a9b4aa6f67cd271915f772cdc1c46bc4f29d834a26c] [http://172.17.0.7:4444/]
2023/04/23 09:39:08 [30722] [SESSION_ATTEMPTED] [http://172.17.0.7:4444/] [1]
2023/04/23 09:39:16 [30719] [SESSION_CREATED] [ae8b0f7054df80d37a806470c765d6f0] [1] [13.19s]
2023/04/23 09:39:16 [30720] [SESSION_CREATED] [71c6271f56fbdaf69e701984a36ea109] [1] [13.79s]
2023/04/23 09:39:18 [30721] [SESSION_CREATED] [2edc2babf9c950a85120d4f5e98ea81a] [1] [15.43s]
2023/04/23 09:39:19 [30722] [SESSION_CREATED] [42e3e358a383ab8ea73e5bb0704bbd56] [1] [15.73s]
2023/04/23 09:39:23 [30744] [CONTAINER_LOGS] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57]
2023/04/23 09:39:23 [30745] [VNC_ENABLED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:32 [30745] [VNC_CLIENT_DISCONNECTED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:32 [30745] [VNC_SESSION_CLOSED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:33 [30785] [CONTAINER_LOGS] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57]
2023/04/23 09:40:33 [30786] [VNC_ENABLED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:33 [30787] [SESSION_DELETED] [71c6271f56fbdaf69e701984a36ea109]
2023/04/23 09:40:33 [30720] [STOPPING_VIDEO_CONTAINER] [f588be1113b30514deb08656697b6b5fda3466d826a388125a634ad50684a441]
2023/04/23 09:40:34 [30788] [SESSION_DELETED] [ae8b0f7054df80d37a806470c765d6f0]
2023/04/23 09:40:34 [30719] [STOPPING_VIDEO_CONTAINER] [6ee586fc99d7da7e299850740eba807b3387efcd888a1552a66d1e0f5b012746]
2023/04/23 09:40:35 [30789] [SESSION_DELETED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:35 [30721] [STOPPING_VIDEO_CONTAINER] [003e6f741447862a066e69ce2f35c12632c1cfeb74f65e4ee343ac8240f95312]
2023/04/23 09:40:37 [30786] [VNC_CLIENT_DISCONNECTED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:37 [30786] [VNC_SESSION_CLOSED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:39 [30720] [REMOVING_CONTAINER] [f588be1113b30514deb08656697b6b5fda3466d826a388125a634ad50684a441]
2023/04/23 09:40:39 [30720] [FAILED_TO_REMOVE_CONTAINER] [f588be1113b30514deb08656697b6b5fda3466d826a388125a634ad50684a441] [Error response from daemon: removal of container f588be1113b30514deb08656697b6b5fda3466d826a388125a634ad50684a441 is already in progress]
2023/04/23 09:40:39 [30720] [REMOVING_CONTAINER] [c9533e7f162c32156582b79bd1c0e114266c4146a7895137eb53111456a7f03d]
2023/04/23 09:40:40 [30720] [CONTAINER_REMOVED] [c9533e7f162c32156582b79bd1c0e114266c4146a7895137eb53111456a7f03d]
2023/04/23 09:40:40 [30719] [REMOVING_CONTAINER] [6ee586fc99d7da7e299850740eba807b3387efcd888a1552a66d1e0f5b012746]
2023/04/23 09:40:40 [30719] [FAILED_TO_REMOVE_CONTAINER] [6ee586fc99d7da7e299850740eba807b3387efcd888a1552a66d1e0f5b012746] [Error response from daemon: removal of container 6ee586fc99d7da7e299850740eba807b3387efcd888a1552a66d1e0f5b012746 is already in progress]
2023/04/23 09:40:40 [30719] [REMOVING_CONTAINER] [43b8c7094f6ed70227f26201ab6a773a6402ab0d9ab8f8759abd8467bd652948]
2023/04/23 09:40:40 [30719] [CONTAINER_REMOVED] [43b8c7094f6ed70227f26201ab6a773a6402ab0d9ab8f8759abd8467bd652948]
2023/04/23 09:40:41 [30721] [REMOVING_CONTAINER] [003e6f741447862a066e69ce2f35c12632c1cfeb74f65e4ee343ac8240f95312]
2023/04/23 09:40:41 [30721] [FAILED_TO_REMOVE_CONTAINER] [003e6f741447862a066e69ce2f35c12632c1cfeb74f65e4ee343ac8240f95312] [Error response from daemon: removal of container 003e6f741447862a066e69ce2f35c12632c1cfeb74f65e4ee343ac8240f95312 is already in progress]
2023/04/23 09:40:41 [30721] [REMOVING_CONTAINER] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57]
2023/04/23 09:40:41 [30785] [CONTAINER_LOGS_DISCONNECTED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:41 [30744] [CONTAINER_LOGS_DISCONNECTED] [2edc2babf9c950a85120d4f5e98ea81a]
2023/04/23 09:40:41 [30791] [SESSION_DELETED] [42e3e358a383ab8ea73e5bb0704bbd56]
2023/04/23 09:40:41 [30721] [CONTAINER_REMOVED] [a08ae17341244e678ca4d18cb85e6a7db593c49218d3a72e4daec89ad5a23a57]
2023/04/23 09:40:41 [30722] [STOPPING_VIDEO_CONTAINER] [550a9a6a0283fa44ad6dbcd6a3c9ba0b13a07f1663618630e04dc81066ba6c60]
2023/04/23 09:40:43 [30722] [REMOVING_CONTAINER] [550a9a6a0283fa44ad6dbcd6a3c9ba0b13a07f1663618630e04dc81066ba6c60]
2023/04/23 09:40:43 [30722] [FAILED_TO_REMOVE_CONTAINER] [550a9a6a0283fa44ad6dbcd6a3c9ba0b13a07f1663618630e04dc81066ba6c60] [Error: No such container: 550a9a6a0283fa44ad6dbcd6a3c9ba0b13a07f1663618630e04dc81066ba6c60]
2023/04/23 09:40:43 [30722] [REMOVING_CONTAINER] [0385bc94a5458e3998302a9b4aa6f67cd271915f772cdc1c46bc4f29d834a26c]
2023/04/23 09:40:43 [30722] [CONTAINER_REMOVED] [0385bc94a5458e3998302a9b4aa6f67cd271915f772cdc1c46bc4f29d834a26c]
`

> @se7en8您的测试中的确切错误消息是什么？

**Comment by vania-pooh** [comment]
@se7en8 need your code stacktrace or error message instead.
