### ISSUE TITLE
Cannot see VNC on selenoid docker container

### ISSUE THREAD

**Issue by saadbaig2** [aerokube/selenoid#1339]
Hello @vania-pooh , I cannot see the Chrome VNC on for my tests running on robot frameowork. I have already added enableVNC=True option for the desired capabilities in my code. 
It is working fine with the same browser containers on 1 PC but not on the other one. The one that doesnt work has windows 11 installed on it. 
What could be the reason ?

**Comment by vania-pooh** [comment]
@saadbaig2 need more details: exact error message, screenshot, capabilities, Selenoid version, Chrome version and so on.

**Comment by saadbaig2** [comment]
@vania-pooh I have problem accessing the machine right now. But please see the screenshot below from my machine. Everything works fine on my machine but just sharing for your reference. The below **enableVNC: true** option is not visible on windows 1 machine.

I tried setting up the selenoid and selenoid-ui as below. 

1. selenoid start --args="-timeout 500s -limit 10"
2. selenoid start --vnc
3. selenoid-ui start

or like below. (Please note that the port 8080 is already being used by another service on the machine)

1. docker run -d --name selenoid -p 4422:4444 -v /c/Users/SaadBaig/.aerokube/selenoid:/etc/selenoid:ro -v //var/run/docker.sock:/var/run/docker.sock aerokube/selenoid:latest-release -conf /etc/selenoid/browsers.json -limit 10
2. docker run --rm -d --name selenoid-ui --link selenoid -p 8090:8080 aerokube/selenoid-ui --selenoid-uri=http://192.168.178.44:4422

When the test is executed from robot framework, the the tests gets shown on selenoid ui but there is no VNC at all but only session logs appear. 

Here are the robot framework desired capabilities. 

```
${log_pref}=        Create Dictionary           enableNetwork=true               enablePage=false                          browser=ALL   driver=ALL        goog:loggingPrefs=${Dic}     enableLog=${True}       enableVnc=${True}

Open Browser       browser=chrome       remote_url=${remote_URL}          desired_capabilities=${log_pref}
```

![image](https://github.com/aerokube/selenoid/assets/101516309/86ae53b3-bbcb-4a40-ab51-001612dd664c)

**Comment by saadbaig2** [comment]
@vania-pooh The same above setup works fine on my windows 10 machine.

**Comment by saadbaig2** [comment]
![image (4)](https://github.com/aerokube/selenoid/assets/101516309/8686e730-c201-4b2f-9502-a9661817101a)
![image (5)](https://github.com/aerokube/selenoid/assets/101516309/dee51c0f-0d31-437b-ac10-4804a5f18124)
![image (2)](https://github.com/aerokube/selenoid/assets/101516309/c8008178-59c5-478e-a324-0c07d32d1e91)
![image (3)](https://github.com/aerokube/selenoid/assets/101516309/5186f475-333b-496f-9256-9bf3ac4b7562)

**Comment by saadbaig2** [comment]
We have also tried using the vnc_chrome images for selenoid and its the same issue with them. The VNC just never appears.

**Comment by vania-pooh** [comment]
@saadbaig2 on your screenshot you can see that ENABLE_VNC variable is set to false, so you don't pass `enableVNC` capability as expected by Selenoid. That's why you don't see VNC.

**Comment by saadbaig2** [comment]
@vania-pooh Is there any update in selenoid documentation that now we have to pass the "selenoid:options" key for ENABLE_VNC variable ? Before it used to work without "selenoid:options" key

**Comment by vania-pooh** [comment]
@saadbaig2 Selenoid still supports both ways. However your client library may omit non-standard capabilities in recent versions, so we recommend using `selenoid:options` anyway.

**Comment by saadbaig2** [comment]
@vania-pooh Yes it worked with selenoid:options. 
Thanks a lot. I am closing this issue now.
