### ISSUE TITLE
Unable to create a new session on a new Docker version (API 1.43)

### ISSUE THREAD

**Issue by valentyn-red-bird** [aerokube/selenoid#1340]
Docker API: 1.43
Engine: 24.0.0
Compose: 2.18.1
Selenoid: 1.10.10

Client:
 Version:           23.0.5
 API version:       1.43 (downgraded from 1.42)
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:12:25 20[23](https://github.com/pdffiller/jsfiller/actions/runs/5021970752/jobs/9004888779#step:20:24)
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          [24](https://github.com/pdffiller/jsfiller/actions/runs/5021970752/jobs/9004888779#step:20:25).0.0
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       1331b8c
  Built:            Mon May 15 18:48:30 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        1677a179643113[25](https://github.com/pdffiller/jsfiller/actions/runs/5021970752/jobs/9004888779#step:20:26)ed1c31e2c0a3589ce6d5c[30](https://github.com/pdffiller/jsfiller/actions/runs/5021970752/jobs/9004888779#step:20:31)d
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de[40](https://github.com/pdffiller/jsfiller/actions/runs/5021970752/jobs/9004888779#step:20:41)ad0

Step: navigate to any URL via Selenium API
Expected: browser is opened and redirected to specified URL.
Actual: session is failing by timeout: ERROR: New session attempts retry count exceeded

Logs:

selenoid-1            | 2023/05/19 07:39:19 [-] [INIT] [Loading configuration files...]
selenoid-1            | 2023/05/19 07:39:19 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
selenoid-1            | 2023/05/19 07:39:19 [-] [INIT] [Video Dir: /opt/selenoid/video]
selenoid-1            | 2023/05/19 07:39:19 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
selenoid-1            | 2023/05/19 07:39:19 [-] [INIT] [Did not manage to determine your Docker API version - using default version: 1.42]
selenoid-1            | 2023/05/19 07:39:19 [-] [INIT] [Listening on :4444]
selenoid-1            | 2023/05/19 07:39:36 [-] [NEW_REQUEST] [unknown] [172.18.0.2]
selenoid-1            | 2023/05/19 07:39:36 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.2]
selenoid-1            | 2023/05/19 07:39:36 [0] [LOCATING_SERVICE] [chrome] [112.0]
selenoid-1            | 2023/05/19 07:39:36 [0] [USING_DOCKER] [chrome] [112.0]
selenoid-1            | 2023/05/19 07:39:36 [0] [CREATING_CONTAINER] [selenoid/vnc_chrome:112.0]
selenoid-1            | 2023/05/19 07:39:36 [0] [STARTING_CONTAINER] [selenoid/vnc_chrome:112.0] [81518f2690901c7dcff1d47dc4d9f079b5b55937269740b75899f7c96480b151]
selenoid-1            | 2023/05/19 07:39:36 [0] [CONTAINER_STARTED] [selenoid/vnc_chrome:112.0] [81518f2690901c7dcff1d47dc4d9f079b5b55937269740b75899f7c96480b151] [0.23s]
selenoid-1            | 2023/05/19 07:39:36 [0] [SERVICE_STARTED] [selenoid/vnc_chrome:112.0] [81518f2690901c7dcff1d47dc4d9f079b5b55937269740b75899f7c96480b151] [0.00s]
selenoid-1            | 2023/05/19 07:39:36 [0] [PROXY_TO] [81518f2690901c7dcff1d47dc4d9f079b5b55937269740b75899f7c96480b151] [http://:4444/]
selenoid-1            | 2023/05/19 07:39:36 [0] [SESSION_ATTEMPTED] [http://:4444/] [1]
selenoid-1            | 2023/05/19 07:39:36 [0] [SESSION_FAILED] [http://:4444/] [200 OK]
selenoid-1            | 2023/05/19 07:39:36 [0] [REMOVING_CONTAINER] [81518f2690901c7dcff1d47dc4d9f079b5b55937269740b75899f7c96480b151]
selenoid-1            | 2023/05/19 07:39:36 [0] [CONTAINER_REMOVED] [81518f[269](https://github.com/pdffiller/jsfiller/actions/runs/5021970752/jobs/9004888779#step:29:270)0901c7dcff1d47dc4d9f079b5b55937269740b75899f7c96480b151]
selenoid-1            | 2023/05/19 07:39:37 [-] [NEW_REQUEST] [unknown] [172.18.0.2]
selenoid-1            | 2023/05/19 07:39:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.2]
selenoid-1            | 2023/05/19 07:39:37 [1] [LOCATING_SERVICE] [chrome] [112.0]
selenoid-1            | 2023/05/19 07:39:37 [1] [USING_DOCKER] [chrome] [112.0]
selenoid-1            | 2023/05/19 07:39:37 [1] [CREATING_CONTAINER] [selenoid/vnc_chrome:112.0]
selenoid-1            | 2023/05/19 07:39:37 [1] [STARTING_CONTAINER] [selenoid/vnc_chrome:112.0] [976bf60454b159b3367c0ee673f3c69bf972e10c7e7e691378c6d5afcad14fd8]

**Root cause: Did not manage to determine your Docker API version - using default version: 1.43**

**Comment by valentyn-red-bird** [comment]
@vania-pooh seems like a similar to https://github.com/aerokube/selenoid/issues/500 and https://github.com/aerokube/selenoid/issues/556

**Comment by vania-pooh** [comment]
@valentyn-red-bird check with `aerokube/selenoid:latest` image.
