### ISSUE TITLE
Copy File layer Vulnerability

### ISSUE THREAD

**Issue by Dor-bl** [aerokube/selenoid#1342]
Hi!

I assume we need to update the Golang version here as well

![image](https://github.com/aerokube/selenoid/assets/59066376/950b4ee6-7b5e-4801-a469-542649381bc4)

**Comment by vania-pooh** [comment]
@Dor-bl already fixed in https://github.com/aerokube/selenoid/pull/1341. Take a look at `aerokube/selenoid:latest` image.
