### ISSUE TITLE
Problem downloading files with special characters in filename

### ISSUE THREAD

**Issue by bughuntDe** [aerokube/selenoid#1343]
Hi,

I'm using latest version of Selenoid, with Chrome110

Background:
Trying to download an Excel file which should be analyzed.
Filename is something like "analysegerät.xlsx".

Other filenames are working as expected, but those like the example are strange.
Instead of downloading the excel, it receives a binary.

I checked the file in the container as well... it's just "download":
![image](https://github.com/aerokube/selenoid/assets/134427579/774f87ad-859c-4799-9501-fc1448e5bc65)

Looks like it has something to do with the German "ä" in the filename.

Thank you for help in advance :)
Jan

**Comment by vania-pooh** [comment]
@bughuntDe you can set LANG variable for german (`de_DE.UTF-8`). https://aerokube.com/selenoid/latest/#_per_session_environment_variables_env

**Comment by bughuntDe** [comment]
This was incredible easy :D

Thanks a lot @vania-pooh !!
