### ISSUE TITLE
how long will the recorded videos keep on the server? can the server clean the expired videos automatically?

### ISSUE THREAD

**Issue by bomblet2** [aerokube/selenoid#1345]
Because my server disk size is small, but I have many videos recorded everyday. so I want to know does the selenoid have a feature to clean the expired videos automatically?

**Comment by vania-pooh** [comment]
@bomblet2 they are stored forever. Configure a cron job to do a periodic cleanup.

**Comment by bomblet2** [comment]
> @bomblet2 they are stored forever. Configure a cron job to do a periodic cleanup.

thanks. I have add a crontab job to clean the expired videos and only keep the latest videos generated in 30 days.
the crontab job runs at 03:25 am every day.

25 3 * * * find /root/.aerokube/selenoid/video/ -type f -mtime +30 -exec rm -f {} \;

**Comment by vania-pooh** [comment]
@bomblet2 closing then?

**Comment by bomblet2** [comment]
> @bomblet2 closing then?

Yes. but if it can be a feature of the selenoid product, I think it will be better.

**Comment by vania-pooh** [comment]
@bomblet2 we consider this out of Selenoid scope.
