### ISSUE TITLE
Getting HTTP 304 Not Modified status code while fetching logs

### ISSUE THREAD

**Issue by RajPradhan75** [aerokube/selenoid#1346]
Getting 304 status code with a blank screen while fetching logs from this url
`http://<server-address>:4444/logs/`

**Comment by RajPradhan75** [comment]
for listing all logs files, this is the url 
`http://selenoid-host.example.com:4444/logs/` right?

**Comment by RajPradhan75** [comment]
> @RajPradhan75 correct.

@vania-pooh then why is this url http://<server-address>:4444/logs 
Is not working?

**Comment by vania-pooh** [comment]
@RajPradhan75 need exact command line used to start Selenoid.
