### ISSUE TITLE
[/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: not a directory]

### ISSUE THREAD

**Issue by iamumairayub** [aerokube/selenoid#1351]
I want to run Selenoid with Docker by myself on my Ubuntu Linux, instead of running with CM

I have tried these commands 

```
docker run -d  --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/etc/selenoid/:ro  aerokube/selenoid:latest-release
docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /home:/etc/selenoid/:ro  aerokube/selenoid:latest-release
docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /etc/selenoid:/etc/selenoid/:ro  aerokube/selenoid:latest-release
```

I have browsers.json exists in /home directory, I am running above commands from /home as well

but I am getting

`[/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: not a directory]
`
my question is how  I can fix this? how I can provide path to my browsers.json file?

PS: reason I want to run with Docker instead of CM is that we are getting plenty of `Message: unknown error: session deleted because of page crash` errors and lots of posts say that we should run it with `-v /dev/shm:/dev/shm` to solve issue. I do have `"shmSize" : 2073741824` set in `browsers.json` but that did not help.

**Comment by vania-pooh** [comment]
@iamumairayub how to mount a file into directory in container is a Docker-related question, nothing specific in Selenoid. CM also can read your existing browsers.json file: https://aerokube.com/cm/latest/#_using_existing_configuration_file
