### ISSUE TITLE
VNC is not working

### ISSUE THREAD

**Issue by la4zen** [aerokube/selenoid#1352]
![image](https://github.com/aerokube/selenoid/assets/65774126/2230da3e-2db8-4b31-9755-18c42a2815ac)
![image](https://github.com/aerokube/selenoid/assets/65774126/5591bce1-c578-4a58-a7a4-3a60ecbccf2f)
![image](https://github.com/aerokube/selenoid/assets/65774126/b7cf112d-ee14-4759-8a77-982d9958dd94)
![image](https://github.com/aerokube/selenoid/assets/65774126/13510891-7228-44a6-91a1-6a5c2285ef06)
![image](https://github.com/aerokube/selenoid/assets/65774126/d9ec6e77-f5e7-46fb-87a6-a2fa83c9a97f)

Selenoid UI VNC not working. 

what could this be related to?

docker logs do not give errors

**Comment by la4zen** [comment]
selenoid proxy just doesn't send data to ws on VNC endpoint

**Comment by s10wn** [comment]
i don't know

**Comment by vania-pooh** [comment]
@la4zen take a look at browser developer tools for errors. This is something related to security settings \ reverse proxy settings if any.

**Comment by la4zen** [comment]
> @la4zen take a look at browser developer tools for errors. This is something related to security settings \ reverse proxy settings if any.

![image](https://github.com/aerokube/selenoid/assets/65774126/5272c8d0-f339-4c2f-8e8c-9b6073d92224)
no, not available

**Comment by la4zen** [comment]
the solenoid was started using the cm utility
docker logs solenoid writes VNC STARTED, but the problem remains.

**Comment by vania-pooh** [comment]
@la4zen respective web-socket request will fail when opening VNC. This should be visible on the Network tab of Devtools. According to the browser image log visible on your screenshot VNC server is successfully starting inside browser image.

**Comment by la4zen** [comment]
> @la4zen respective web-socket request will fail when opening VNC. This should be visible on the Network tab of Devtools. According to the browser image log visible on your screenshot VNC server is successfully starting inside browser image.

I'm talking about too, the server starts, but does not send screen data.
What could be the problem?

**Comment by la4zen** [comment]
it turned out.
There is a connection, but VNC starts transmitting data after 5 minutes of the session.
