### ISSUE TITLE
Session timed out or not found

### ISSUE THREAD

**Issue by ArmandsBruns** [aerokube/selenoid#1357]
Hi,

We are running tests on Selenoid using docker:

Dockerfile:

> FROM ubuntu:21.04
> RUN apt update && apt install -y default-jdk maven curl jq locales locales-all tzdata
> RUN mkdir docker
> WORKDIR docker
> ENV LC_ALL lv_LV.utf8
> ENV LANG lv_LV.utf8
> ENV LANGUAGE lv_LV.utf8
> ENV TZ=Europe/Riga
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> RUN dpkg-reconfigure --frontend noninteractive tzdata
> COPY lib ./lib
> COPY src ./src
> COPY testui-grid ./testui-grid

 We regularly got the following error message in jenkins:

> session timed out or not found
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'automation-docker', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-135-generic', java.version: '11.0.12'
> Driver info: org.openqa.selenium.remote.RemoteWebDriver
> Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 113.0.5672.126, chrome: {chromedriverVersion: 113.0.5672.63 (0e1a4471d5ae..., userDataDir: /tmp/.com.google.Chrome.ium2mb}, goog:chromeOptions: {debuggerAddress: localhost:34731}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
> Session ID: e695ef7a068e2c83e2235d491c7f9151
> org.openqa.selenium.NoSuchSessionException: session timed out or not found
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'automation-docker', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-135-generic', java.version: '11.0.12'
> Driver info: org.openqa.selenium.remote.RemoteWebDriver
> Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 113.0.5672.126, chrome: {chromedriverVersion: 113.0.5672.63 (0e1a4471d5ae..., userDataDir: /tmp/.com.google.Chrome.ium2mb}, goog:chromeOptions: {debuggerAddress: localhost:34731}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
> Session ID: e695ef7a068e2c83e2235d491c7f9151
> 	at jdk.internal.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
> 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
> 	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:287)
> 	at testUI.elements.Element.getCurrentUrl(Element.java:836)
> 	at helpers.LanguageHelper.getLanguageFromUrl(LanguageHelper.java:34)
> 	at helpers.DateTimeHelper.getDateTimeLocale(DateTimeHelper.java:124)
> 	at helpers.DateTimeHelper.getDateTime(DateTimeHelper.java:24)
> 	at helpers.soapHelpers.SOAPHelper.getActivePoliciesByDateAndPlateNumber(SOAPHelper.java:116)
> 	at stepDefinitions.general.LoginSteps.userIsClearedWS(LoginSteps.java:213)
> 	at ✽.check by WS if there is active transport policy for car: CASCO(target/parallel/features/CascoPolicy_feature003_run001_IT.feature:54)

	
config:	
/home/jenkins/.aerokube/selenoid/browsers.json

	{
    "chrome": {
        "default": "113.0",
        "versions": {
            "113.0": {
                "image": "selenoid/chrome:113.0",
                "port": "4444",
                "env" : ["TZ=Europe/Riga", "LC_ALL=lv_LV.utf8", "LANG=lv_LV.utf8", "LANGUAGE=lv_LV.utf8"],
                "path": "/",
                "volumes" : ["/home/jenkins/docker_downloads:/home/seluser/Downloads"]
            },
            "96.0": {
                "image": "selenoid/chrome:96.0",
                "port": "4444",
                "env" : ["TZ=Europe/Riga", "LC_ALL=lv_LV.utf8", "LANG=lv_LV.utf8", "LANGUAGE=lv_LV.utf8"],
                "path": "/",
                "volumes" : ["/home/jenkins/docker_downloads:/home/seluser/Downloads"]
            }
        }
    },
	
	
jenkins@automation-docker:~$ docker ps

> CONTAINER ID   IMAGE                         COMMAND                  CREATED              STATUS                PORTS                                              NAMES
> 33fcf8495110   selenoid/chrome:113.0         "/entrypoint.sh"         3 seconds ago        Up 2 seconds          4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   nervous_chebyshev
> c37b4c3b9f3d   selenoid/chrome:113.0         "/entrypoint.sh"         7 seconds ago        Up 4 seconds          4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   eager_murdock
> 12f55dabc207   selenoid/chrome:113.0         "/entrypoint.sh"         15 seconds ago       Up 9 seconds          4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   intelligent_hodgkin
> 403d73142e94   selenoid/chrome:113.0         "/entrypoint.sh"         24 seconds ago       Up 20 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   mystifying_buck
> c24a77bf2178   selenoid/chrome:113.0         "/entrypoint.sh"         26 seconds ago       Up 20 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   wizardly_mendel
> 9eabba6ba707   selenoid/chrome:113.0         "/entrypoint.sh"         27 seconds ago       Up 21 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   focused_hermann
> 8b8dc236b59c   selenoid/chrome:113.0         "/entrypoint.sh"         27 seconds ago       Up 21 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   ecstatic_tu
> f22b55406764   selenoid/chrome:113.0         "/entrypoint.sh"         27 seconds ago       Up 21 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   nifty_pascal
> 78200a9cc6f0   selenoid/chrome:113.0         "/entrypoint.sh"         28 seconds ago       Up 21 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   peaceful_lewin
> 3d706f49a846   selenoid/chrome:113.0         "/entrypoint.sh"         28 seconds ago       Up 22 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   adoring_vaughan
> 9a0c4d6a778b   selenoid/chrome:113.0         "/entrypoint.sh"         28 seconds ago       Up 23 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   pensive_bhaskara
> 820d0755db64   selenoid/chrome:113.0         "/entrypoint.sh"         28 seconds ago       Up 24 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   sad_bardeen
> 225a09a63d42   selenoid/chrome:113.0         "/entrypoint.sh"         28 seconds ago       Up 27 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   jolly_cori
> 9120ea4e5a06   selenoid/chrome:113.0         "/entrypoint.sh"         30 seconds ago       Up 29 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   gallant_hugle
> 745b4c6ee0c0   selenoid/chrome:113.0         "/entrypoint.sh"         31 seconds ago       Up 30 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   intelligent_ganguly
> a075c45abf1e   selenoid/chrome:113.0         "/entrypoint.sh"         32 seconds ago       Up 30 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   practical_bartik
> f9e839860a64   selenoid/chrome:113.0         "/entrypoint.sh"         32 seconds ago       Up 30 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   condescending_cohen
> 9afbeb2e7819   selenoid/chrome:113.0         "/entrypoint.sh"         33 seconds ago       Up 30 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   stoic_ganguly
> 1c04455f22ec   selenoid/chrome:113.0         "/entrypoint.sh"         33 seconds ago       Up 30 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   competent_boyd
> 7d4693005c3a   selenoid/chrome:113.0         "/entrypoint.sh"         33 seconds ago       Up 30 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   amazing_brahmagupta
> dd3346903342   selenoid/chrome:113.0         "/entrypoint.sh"         42 seconds ago       Up 39 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   gracious_chaum
> 457043e02f04   selenoid/chrome:113.0         "/entrypoint.sh"         52 seconds ago       Up 52 seconds         4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   gifted_almeida
> 2d6785ae5749   selenoid/chrome:113.0         "/entrypoint.sh"         About a minute ago   Up About a minute     4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   practical_chatterjee
> b88f4c5e8a2a   aerokube/selenoid:1.10.7      "/usr/bin/selenoid -…"   11 days ago          Up 5 days             0.0.0.0:4444->4444/tcp                             selenoid
> 2c5de349a68d   aerokube/selenoid-ui:1.10.4   "/selenoid-ui --sele…"   19 months ago        Up 5 days (healthy)   0.0.0.0:8080->8080/tcp                             selenoid-ui

**Comment by ArmandsBruns** [comment]
For Selenoid restart we are using:
./cm_linux_amd64 selenoid stop && ./cm_linux_amd64 selenoid start --args "-limit 80"

Maybe I can add some parameter that will increase the session time from 30 seconds to 60 seconds?

**Comment by ArmandsBruns** [comment]
Can I use this way?

> ./cm_linux_amd64 selenoid stop && ./cm_linux_amd64 selenoid start --args "-limit 80" "-service-startup-timeout 60s" "-session-attempt-timeout 60s"

**Comment by vania-pooh** [comment]
@ArmandsBruns make sure that with `-limit 80` you have similar number of CPUs (e.g. 50 or 60). Otherwise you are launching too many browser sessions in parallel.

**Comment by ArmandsBruns** [comment]
Hi @vania-pooh 
Thank you for your response.

STATS:

SSE
CONNECTED
SELENOID
CONNECTED
 
USED
5%
 
QUEUED
0
 
QUOTA
4 + 0 / 80

**Comment by ArmandsBruns** [comment]
I haven't seen the session timed out since I applied the changes.

> ./cm_linux_amd64 selenoid stop && ./cm_linux_amd64 selenoid start --args "-limit 80" "-service-startup-timeout 60s" "-session-attempt-timeout 60s"

I'll keep checking if it doesn't show up
