### ISSUE TITLE
Android Test

### ISSUE THREAD

**Issue by KpoJIuk06** [aerokube/selenoid#1358]
Hi , 
i want to ask selenoid android :
I have linux machine: 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Linux 5.15.0-25-generic
when i start maven test ,  i got this logs :
This error : browserTest(com.aerokube.selenoid.AndroidDemoTest): wait: http://172.17.0.5:4444/wd/hub does not respond in 30s(..)

Logs in container which created ( android 10.0) : 

root@vmi1303393:~# docker logs 4b6fa3118ff8
Waiting X server...
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
Waiting X server...
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
emulator: autoconfig: -kernel /opt/android-sdk-linux/system-images/android-29/default/x86//kernel-ranchu-64
emulator: Target arch = 'x86'
emulator: Auto-config: -qemu -cpu qemu32
emulator: Auto-detect: Kernel image requires new device naming scheme.
emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
emulator: autoconfig: -ramdisk /opt/android-sdk-linux/system-images/android-29/default/x86//ramdisk.img
emulator: Using initial system image: /opt/android-sdk-linux/system-images/android-29/default/x86//system.img
emulator: Using initial vendor image: /opt/android-sdk-linux/system-images/android-29/default/x86//vendor.img
emulator: autoconfig: -data /root/.android/avd/android10.0-1.avd/userdata-qemu.img
emulator: autoconfig: -initdata /root/.android/avd/android10.0-1.avd/userdata.img
emulator: autoconfig: -cache /root/.android/avd/android10.0-1.avd/cache.img
emulator: Increasing RAM size to 2048MB
emulator: VM heap size 0MB is below hardware specified minimum of 512MB,setting it to that value
emulator: WARNING: System image is writable
emulator: Found 2 DNS servers: 213.136.95.11 213.136.95.10
emulator: there is no '1080x1920' skin in '/opt/android-sdk-linux/platforms/android-29/skins/'
emulator: found magic skin width=1080 height=1920 bpp=16

emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'qemu.cmdline' = 'androidboot.logcat=v:* androidboot.consolepipe=qemu_pipe,pipe:logcat'
emulator: Adding boot property: 'qemu.logcat' = 'start'
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

 --- x11vnc loop: waiting for: 87

PORT=5900
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found

**Comment by KpoJIuk06** [comment]
я запустил  также на локальном компьютере , где включена визуализация . но теже ошибки вылетают

**Comment by KpoJIuk06** [comment]
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
emulator: autoconfig: -kernel /opt/android-sdk-linux/system-images/android-29/default/x86//kernel-ranchu-64
emulator: Target arch = 'x86'
emulator: Auto-config: -qemu -cpu qemu32
emulator: Auto-detect: Kernel image requires new device naming scheme.
emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
emulator: autoconfig: -ramdisk /opt/android-sdk-linux/system-images/android-29/default/x86//ramdisk.img
emulator: Using initial system image: /opt/android-sdk-linux/system-images/android-29/default/x86//system.img
emulator: Using initial vendor image: /opt/android-sdk-linux/system-images/android-29/default/x86//vendor.img
emulator: autoconfig: -data /root/.android/avd/android10.0-1.avd/userdata-qemu.img
emulator: autoconfig: -initdata /root/.android/avd/android10.0-1.avd/userdata.img
emulator: autoconfig: -cache /root/.android/avd/android10.0-1.avd/cache.img
emulator: Increasing RAM size to 2048MB
emulator: VM heap size 0MB is below hardware specified minimum of 512MB,setting it to that value
emulator: WARNING: System image is writable
emulator: Found 1 DNS servers: 192.168.65.5
emulator: there is no '1080x1920' skin in '/opt/android-sdk-linux/platforms/android-29/skins/'
emulator: found magic skin width=1080 height=1920 bpp=16

emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'qemu.cmdline' = 'androidboot.logcat=v:* androidboot.consolepipe=qemu_pipe,pipe:logcat'
emulator: Adding boot property: 'qemu.logcat' = 'start'
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

PORT=5900
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
 --- x11vnc loop: waiting for: 87

adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found

**Comment by vania-pooh** [comment]
@KpoJIuk06 need to increase `-session-attempt-timeout` flag to 2 minutes. Android sessions approximately starts in 30-40 seconds, this is why you get timeout.

**Comment by KpoJIuk06** [comment]
@vania-pooh  i added from json and also try and added in code setCapability. It always 30 seconds respond

**Comment by vania-pooh** [comment]
@KpoJIuk06 session attempt timeout is a command-line flag, not a capability. https://aerokube.com/selenoid/latest/#_selenoid_cli_flags

**Comment by KpoJIuk06** [comment]
Same problem if i add flag in command browserTest(com.aerokube.selenoid.AndroidDemoTest): wait: http://172.17.0.4:4444/wd/hub does not respond in 30s(..)  :
@Before
    public void openDriver() throws Exception {
        final DesiredCapabilities device = new DesiredCapabilities();
        device.setCapability("browserName", "android");
        device.setCapability("version", "10.0");
        device.setCapability("app", "F:\\demo-tests-master\\src\\test\\resources\\test.apk"); 
        device.setCapability("appPackage", "uz.pdp.calculator2"); 
        device.setCapability("appActivity", "com.example.calculator2.MainActivity");  


        driver = new RemoteWebDriver(new URL(
                "http://127.0.0.1:4444/wd/hub" 
        ), device);
    }

Docker commands : 
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v "C:/Users/Users/Documents/selenoid_Android/":/etc/selenoid/:ro -v  "C:/Users/Users/Documents/selenoid_Android/logs/":/opt/selenoid/logs/ -v /opt/selenoid/video/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_OUTPUT_DIR="/opt/selenoid/video/" -p 4444:4444 --name selenoid aerokube/selenoid:1.10.7 -log-output-dir /opt/selenoid/logs -session-attempt-timeout 2m

docker run -d ^
           --name selenoid-ui ^
           -p 8080:8080 ^
           --link selenoid:selenoid ^
           aerokube/selenoid-ui:1.10.4 ^
           --selenoid-uri "http://selenoid:4444"
           

Browser.json : 
{
  "android": {
    "default": "10.0",
    "versions": {
      "10.0": {
        "image": "selenoid/android:10.0",
	"sessionTimeout": "1m",
	"sessionAttemptTimeout": "2m",
        "env": [
          "VERBOSE=true",
          "APPIUM_ARGS=--log-level debug"
        ],
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  },
  "chrome": {
    "default": "111.0",
    "versions": {
      "111.0": {
        "image": "selenoid/chrome:111.0",
        "port": "4444",
        "path": "/",
        "tmpfs": {
          "/tmp": "size=128m"
        }
      }
    }
  }
}

**Comment by vania-pooh** [comment]
@KpoJIuk06 forgot about one more flag. Should be: `-service-startup-timeout 2m -session-attempt-timeout 2m`.

**Comment by KpoJIuk06** [comment]
Thanks now timeout browserTest(com.aerokube.selenoid.AndroidDemoTest): wait: http://172.17.0.4:4444/wd/hub does not respond in 2m0s(..)


but also had problem with emulator

Maybe need to config somewhere ? 


Log Android Container when start by code
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
emulator: autoconfig: -kernel /opt/android-sdk-linux/system-images/android-29/default/x86//kernel-ranchu-64
emulator: Target arch = 'x86'
emulator: Auto-config: -qemu -cpu qemu32
emulator: Auto-detect: Kernel image requires new device naming scheme.
emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
emulator: autoconfig: -ramdisk /opt/android-sdk-linux/system-images/android-29/default/x86//ramdisk.img
emulator: Using initial system image: /opt/android-sdk-linux/system-images/android-29/default/x86//system.img
emulator: Using initial vendor image: /opt/android-sdk-linux/system-images/android-29/default/x86//vendor.img
emulator: autoconfig: -data /root/.android/avd/android10.0-1.avd/userdata-qemu.img
emulator: autoconfig: -initdata /root/.android/avd/android10.0-1.avd/userdata.img
emulator: autoconfig: -cache /root/.android/avd/android10.0-1.avd/cache.img
emulator: Increasing RAM size to 2048MB
emulator: VM heap size 0MB is below hardware specified minimum of 512MB,setting it to that value
emulator: WARNING: System image is writable
emulator: Found 1 DNS servers: 192.168.65.5
emulator: there is no '1080x1920' skin in '/opt/android-sdk-linux/platforms/android-29/skins/'
emulator: found magic skin width=1080 height=1920 bpp=16

emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'qemu.cmdline' = 'androidboot.logcat=v:* androidboot.consolepipe=qemu_pipe,pipe:logcat'
emulator: Adding boot property: 'qemu.logcat' = 'start'
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

PORT=5900
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
 --- x11vnc loop: waiting for: 87

adb: no devices/emulators found
adb: no devices/emulators found

**Comment by vania-pooh** [comment]
@KpoJIuk06 Android images require virtualization support in CPU and will only work on Linux hardware server. It will not work on Linux VMs.

**Comment by KpoJIuk06** [comment]
Thanks for the info. It turns out that the use of selenoid, only for manual tests for android, no pipelines and gits.
