### ISSUE TITLE
selenoid/vnc_firefox:115.0 Cannot create a session

### ISSUE THREAD

**Issue by nitinjagjivan** [aerokube/selenoid#1362]
selenoid/vnc_firefox:115.0 Cannot create a session. On my test env it works well with selenoid/vnc_firefox:106.0.

Logs-
[nitin@xxxxxx ~]$ docker logs 1d7xxx626039 -f
19
Waiting X server...
Logging to: /dev/null
Waiting X server...
2023/07/25 03:09:30 [-] [INIT] [Loading configuration files...]
2023/07/25 03:09:30 [-] [INIT] [Loaded configuration from /tmp/browsers.json]
2023/07/25 03:09:30 [-] [INIT] [Timezone: America/New_York]
2023/07/25 03:09:30 [-] [INIT] [Listening on :4444]

 --- x11vnc loop: 1 ---

2023/07/25 03:09:30 [-] [NEW_REQUEST] [unknown] [111.xx.x.x]
2023/07/25 03:09:30 [-] [NEW_REQUEST_ACCEPTED] [unknown] [111.xx.x.x]
2023/07/25 03:09:30 [0] [LOCATING_SERVICE] [firefox] [115.0]
2023/07/25 03:09:30 [0] [USING_DRIVER] [firefox] [115.0]
2023/07/25 03:09:30 [0] [ALLOCATING_PORT]
2023/07/25 03:09:30 [0] [ALLOCATED_PORT] [36586]
2023/07/25 03:09:30 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --port=36586]]
1690268970913	geckodriver	INFO	Listening on 127.0.0.1:36586
 --- x11vnc loop: waiting for: 76

PORT=5900
2023/07/25 03:10:00 [0] [TERMINATING_PROCESS] [71]
2023/07/25 03:10:00 [0] [TERMINATED_PROCESS] [71] [0.00s]
2023/07/25 03:10:00 [0] [SERVICE_STARTUP_FAILED] [http://111.xx.x.10:36586 does not respond in 30s]

**Comment by vania-pooh** [comment]
@nitinjagjivan make sure you have a recent Selenoid version.

**Comment by nitinjagjivan** [comment]
Thanks @vania-pooh, It started working after Selenoid upgrade.
