### ISSUE TITLE
Cannot start firefox instance 

### ISSUE THREAD

**Issue by Edw125** [aerokube/selenoid#1363]
Hi. There is some issue when starting the firefox instance. I changed and removed options, I cleared the docker, it did not help. And chrome starts fine. Selenium version is 4.9.0
desired caps:
![image](https://github.com/aerokube/selenoid/assets/57034089/93aa0096-9424-40e0-ac2f-551d1a27931e)
error from python:
![image](https://github.com/aerokube/selenoid/assets/57034089/8445d27f-361d-4b48-bab8-ee17c8452c3e)
error from docker log:
![image](https://github.com/aerokube/selenoid/assets/57034089/1c441151-020a-4510-a7de-bee6017efe86)
my browsers.json:
![image](https://github.com/aerokube/selenoid/assets/57034089/ba4021ee-0659-44d5-8262-8d240cdea094)

**Comment by aandryashin** [comment]
Hello!

You have to add path key in browsers.json for Firefox:

"path": "/wd/hub"

Please check it in docs.

пн, 31 июл. 2023 г., 20:26 Edgar ***@***.***>:

**Comment by Edw125** [comment]
Thank you very much! Its work

**Comment by vania-pooh** [comment]
Closing then.
