### ISSUE TITLE
Could not start a new session. Response code 400. Message: Unrecognised option moz:debuggerAddress  for FF browser 

### ISSUE THREAD

**Issue by RaviNelluri** [aerokube/selenoid#1366]
I am not able to launch the Firefox Browser using selenoid docker and error coming as 

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Unrecognised option moz:debuggerAddress

**Comment by RaviNelluri** [comment]
Please find the details 
Selenoid version :  3
Firefox version : 83
Selenium client version :  4.10.0
Full capabilities  
fo = new FirefoxOptions();
fo.setCapability("browserName", "firefox");
fo.setBrowserVersion(prop.getProperty("browserversion"));

Browser name and version reading from xml file 
	<test name="Login Page Test">
		<parameter name="browser" value="firefox" />
		<parameter name="browserversion" value="83" />
		<parameter name="testname" value="LoginPageTest" />
		<classes>
			<class name="com.qa.opencart.tests.LoginPageTest" />
		</classes>
	</test>


Note: For chrome it's working fine w/o any errors but only FF it's giving error saying **_org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: Unrecognised option moz:debuggerAddress_**

**Comment by RaviNelluri** [comment]
So, we can't use Firefox on selenoid container and only chrome is supported as of now ? Just asking

**Comment by vania-pooh** [comment]
@RaviNelluri Selenoid supports all of them and all of them work. This could be considered as a bug in Selenium client. If you use older Selenium client or curl everything will work.

**Comment by Argano-GQE** [comment]
I Verified with latest selenium 4.12.0 but still I am not able to launch the FF in selenoid container

**Comment by Argano-GQE** [comment]
Today checked with selenium team and they are saying need to check with selenoid project 

![image](https://github.com/aerokube/selenoid/assets/132889138/ac9c8b49-d8cf-4904-ab42-f7c2c2f359e8)

**Comment by vania-pooh** [comment]
@Argano-GQE if you have Firefox installed locally, try to download geckodriver [here](https://github.com/mozilla/geckodriver/releases), then launch it:

```
$ ./geckodriver --port 4444
```

Then try to launch your tests against the following URL:

```
http://localhost:4444/
```

You should receive the same error without Selenoid at all.

**Comment by Argano-GQE** [comment]
It's working fine in local 

![image](https://github.com/aerokube/selenoid/assets/132889138/62926dcb-c2da-424b-9477-e81eb31b5a38)

**Comment by Argano-GQE** [comment]
![image](https://github.com/aerokube/selenoid/assets/132889138/9128f5ac-eb13-41b6-8a08-729717d0c431)

Latest geckodriver

**Comment by Argano-GQE** [comment]
![image](https://github.com/aerokube/selenoid/assets/132889138/6de5b2d9-80b3-4bfc-8e97-42985f93fbb7)

Latest geckodriver

**Comment by vania-pooh** [comment]
@Argano-GQE what you are showing is Selenium Grid. They are probably removing capabilities in their code. Try without Seleniumd Grid at all.

**Comment by Argano-GQE** [comment]
http://localhost:4444/ means we need to use selenium grid only na . Correct me If I am wrong here.  Normally  I am able to launch the FF w/o any issues in my local

**Comment by Argano-GQE** [comment]
@vania-pooh  Are you looking for this one or something else . 

![image](https://github.com/aerokube/selenoid/assets/132889138/9b54b1aa-d360-4540-a665-410048b6503d)

**Comment by vania-pooh** [comment]
@Argano-GQE sure.
