### ISSUE TITLE
It's possible to create a dynamic volume to download files?

### ISSUE THREAD

**Issue by ViniciusEd** [aerokube/selenoid#1367]
Hey guys,

It's possible create a dynamic volume to download files?

Example: if i run my python code and i need to download some file in machine X, when i perform the download, the file is automatic saved on my folder in machine X. If a run my python code in machine Y, the same happen in machine Y. Is it possible to make?

Regards,

**Comment by vania-pooh** [comment]
@ViniciusEd have you seen this feature: https://aerokube.com/moon/latest/#accessing-downloaded-files

**Comment by ViniciusEd** [comment]
Hi @vania-pooh,

Yes, and I'm already using it.

I created a logic to download files and it is working, however, I would like to know if it is possible to receive a base64 file in the Get method. 

It's possible?

**Comment by vania-pooh** [comment]
@ViniciusEd this API always sends file bytes only.
