### ISSUE TITLE
Getting issue with downloading a file 

### ISSUE THREAD

**Issue by vidushi283** [aerokube/selenoid#1368]
I have 2 setup to execute the tests on selenoid

1. Local Setup ( on laptop using cm ) as  as localhost
2. on linux box again using cm along with ggr as we have multiple selenoid machine . its a remote machine
**Problem statement** 
While running a file download case on local selenoid , it is getting passed and file is downloaded to "/home/selenium/Downloads" by default ( no download prompt) and case passes.
but When I execute the same case with same code (same Chromeoptios settings) on remote machine I get popup for download

Have gone through https://github.com/aerokube/selenoid/issues/730 and https://aerokube.com/selenoid/latest/#_downloading_files_in_different_browsers

both suggest having /home/selenium/Downloads as default download directory but I would like understand why it is working on local selenoid before I make the changes

I am trying to figure out the differences what is happening .

my ChromeOptions are like 

                        if (Settings.ExecutionType.ToLower() == "remote")
                        {
                        string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
                            chromeOptions2.AddUserProfilePreference("download.default_directory", baseDirectory + "Downloads");
                            _parallelConfig.Driver = new RemoteWebDriver(new Uri(uriString), chromeOptions2.ToCapabilities(), TimeSpan.FromSeconds(Settings.Timeout));
                            break;
                        }

**Comment by vania-pooh** [comment]
@vidushi283 `/download` is just a simple file server always listing files from `/home/selenium/Downloads`. This is why you have to always download to this directory in local and remote scenarios.
