### ISSUE TITLE
Getting 500 internal error while creating session in Selenoid UI

### ISSUE THREAD

**Issue by Velliangiri-Murugesh** [aerokube/selenoid#1369]
I'm new to selenoid and  tried to create a session in Selenoid UI and it fails to create. 

Checked the network call on the browser and it shows 500 internal error. 
![image](https://github.com/aerokube/selenoid/assets/70661535/d97ca6fe-2ab4-421a-91ec-e19360cd1e45)

**Container logs:** 
2023-08-30 16:07:21 selenoid     | 2023/08/30 10:37:21 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.28.0.1]
2023-08-30 16:07:21 selenoid     | 2023/08/30 10:37:21 [23] [LOCATING_SERVICE] [firefox] [104.0]
2023-08-30 16:07:21 selenoid     | 2023/08/30 10:37:21 [23] [USING_DOCKER] [firefox] [104.0]
2023-08-30 16:07:21 selenoid     | 2023/08/30 10:37:21 [23] [CREATING_CONTAINER] [selenoid/vnc:firefox_104.0]
2023-08-30 16:07:21 selenoid     | 2023/08/30 10:37:21 [23] [SERVICE_STARTUP_FAILED] [create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]

**browser json:** 
 {
 	"firefox": {
 		"default": "104.0",
 		"versions": {
 			"104.0": {
 				"image": "selenoid/vnc:firefox_104.0",
 				"port": "4444",
				"path": "/wd/hub",
 				"tmpfs": {
 					"/tmp": "size=512m"
 				},
 				"path": "/wd/hub",
 				"volumes": ["/from:/to:ro"],
 				"env": ["TZ=Europe/Moscow"],
 				"hosts": ["example.com:192.168.0.1"],
 				"shmSize": 268435456,
 				"cpu": "1.0",
 				"mem": "512m"
 			}
 		}
 	}
 }

**Container status :** 

![image](https://github.com/aerokube/selenoid/assets/70661535/658d74bd-26f7-46c1-a680-9b0471769417)

**Docker images status :** 
![image](https://github.com/aerokube/selenoid/assets/70661535/19928f75-cffb-4ef8-a475-0db8f8b94478)

**Comment by vania-pooh** [comment]
@Velliangiri-Murugesh you did not mount `/var/run/docker.sock` inside Selenoid container.

**Comment by Velliangiri-Murugesh** [comment]
@vania-pooh  i have mounted that in docker compose

version: '3'
services:
selenoid:
network_mode: bridge
image: aerokube/selenoid
volumes:
- "/D/Giri/IntellijAutomation/pomframework/docker/newselenoid:/etc/selenoid"
**- "/var/run/docker.sock:/var/run/docker.sock"**
- "/D/Giri/IntellijAutomation/pomframework/docker/newselenoid/video"
environment:
- OVERRIDE_VIDEO_OUTPUT_DIR=/Users/Giri/Documents/newselenoid/video
- TZ=Europe/Amsterdam
command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
ports:
- "4444:4444"

selenoid-ui:
image: "aerokube/selenoid-ui"
network_mode: bridge
links:
- selenoid
ports:
- "8080:8080"
command: ["--selenoid-uri", "http://selenoid:4444"]

**Comment by vania-pooh** [comment]
@Velliangiri-Murugesh under windows probably should be `//var/run/docker.sock:/var/run/docker.sock` with two slashes.

**Comment by Velliangiri-Murugesh** [comment]
@vania-pooh  Thanks for quick help. I have updated the value but still there is different error. 

2023-08-30 22:41:14 2023/08/30 17:11:14 [10] [CONTAINER_STARTED] [selenoid/vnc:firefox_104.0] [63f63d412372b9a16e6b861dd69943fe2024f0fa4ece143e9be5bea77f6b6e0b] [0.31s]
2023-08-30 22:41:44 2023/08/30 17:11:44 [10] [REMOVING_CONTAINER] [63f63d412372b9a16e6b861dd69943fe2024f0fa4ece143e9be5bea77f6b6e0b]
2023-08-30 22:41:45 2023/08/30 17:11:45 [10] [CONTAINER_REMOVED] [63f63d412372b9a16e6b861dd69943fe2024f0fa4ece143e9be5bea77f6b6e0b]
2023-08-30 22:41:45 2023/08/30 17:11:45 [10] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.2:4444/wd/hub does not respond in 30s]

**Comment by vania-pooh** [comment]
@Velliangiri-Murugesh you need to add `-container-flag` like shown here: https://aerokube.com/selenoid/latest/#_option_2_running_selenoid_in_custom_docker_network

**Comment by vania-pooh** [comment]
@Velliangiri-Murugesh so far as I can see you are still using Docker links instead of custom Docker network. Please take a look at our example more attentively. There should be `networks` section.

**Comment by Velliangiri-Murugesh** [comment]
@vania-pooh  Thank you so much for addressing the issue. it is started to working by changing the compos file   . Please close this case. 


For those who is facing the same issue  can use the following compose : 

### docker compose: 

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "/D/Giri/IntellijAutomation/pomframework/docker/newselenoid:/etc/selenoid" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

**### Browser.json:** 

 {
 	"chrome": {
 		"default": "100.0",
 		"versions": {
 			"100.0": {
 				"image": "selenoid/vnc:chrome_100.0",
 				"port": "4444",
				"path": "/",
 				"privileged": true
 			}
 		}
 	}
 }
