### ISSUE TITLE
Not able to setup selenoid on Mac M1

### ISSUE THREAD

**Issue by shivanishinde-trilio** [aerokube/selenoid#1371]
I am trying to setup selenoid on Mac M1.
I have tried following steps, but I am not able to get selenoid container up.

1. Selenoid container exits with following command
```
2023-08-31 12:59:25 2023/08/31 07:29:25 [-] [INIT] [Loading configuration files...] 2023-08-31 12:59:25 2023/08/31 07:29:25 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
```

I have tried this:
Created a browsers.json at above path with following content:
```
{

  "firefox": {

    "default": "latest",

    "versions": {

      "latest": {

        "image": "selenoid/firefox:latest"

      }

    }

  },

  "chrome": {

    "default": "latest",

    "versions": {

      "latest": {

        "image": "selenoid/chrome:latest"

      }

    }

  }

}
```

—————————————————————————————————————
2. Followed steps [here](https://aerokube.com/cm/latest/#_using_existing_configuration_file) to start selenoid using binary.
```
chmod +x cm_darwin_arm64
./cm_darwin_arm64 selenoid start --vnc                                      
```

Gives me following error:
```
Failed to initialize: [can not access Docker: make sure you have Docker installed and current user has access permissions]`
```

While I am able to run docker commands

```
docker ps                                                                                                               

CONTAINER ID   IMAGE                                 COMMAND                  CREATED      STATUS                    PORTS                    NAMES

672ec9e3872e   aerokube/selenoid-ui:latest-release   "/selenoid-ui --sele…"   2 days ago   Up 30 minutes (healthy)   0.0.0.0:8080->8080/tcp   selenoid-ui


docker images

REPOSITORY                           TAG              IMAGE ID       CREATED         SIZE

aerokube/selenoid                    latest           5be16d471a91   3 weeks ago     17.3MB

aerokube/selenoid                    latest-release   58f712004c5c   5 weeks ago     17.3MB
```

I have also created docker group in Mac settings and added my user there.
—————————————————————————————————————

3. I tried docker pull and run latest image, but ended up with same browsers.json file missing error.

I am not sure if the issue is M1 specific, but selenoid setup works fine on Windows and Non M1 Mac with documented commands.

Can someone help?

**Comment by vania-pooh** [comment]
@shivanishinde-trilio you are mounting browsers.json incorrectly inside Selenoid container. But you can also run Selenoid as a binary just launching `./selenoid -config browsers.json` and it will work with Docker containers.

**Comment by shivanishinde-trilio** [comment]
@vania-pooh Could you please clarify which is the selenoid binary you are referring to? And steps to get this binary?

**Comment by vania-pooh** [comment]
@shivanishinde-trilio binaries are attached to every release: https://github.com/aerokube/selenoid/releases

**Comment by vania-pooh** [comment]
Seems to be related to https://github.com/aerokube/selenoid/issues/795.

**Comment by ashwink-tech** [comment]
@vania-pooh Is selenoid supporting Mac M1 now?

**Comment by vania-pooh** [comment]
@ashwink-tech Selenoid binaries work on Mac M1 but e.g. Chrome images will not work.

**Comment by raj-billowria** [comment]
@shivanishinde-trilio can you please share the docker-compose.yml file for the same...
