### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: New session attempts retry count exceeded  while running a single test

### ISSUE THREAD

**Issue by jyoti-c** [aerokube/selenoid#1372]
I have installed selenoid using the **[configuration manager](https://github.com/aerokube/cm/releases/tag/1.8.5)**. I am running a test on the selenoid image version -  **[aerokube/selenoid:1.11.0]** and firefox image - **[selenoid/firefox:1.110.0]**. The browser attempts to start repeatedly but does not get started. 
I am getting the following error in my test script - 
`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: New session attempts retry count exceeded 
Host info: host: 'PNQ-JCHABRIA', ip: 'fe80:0:0:0:1496:45cf:a239:fff9%en0'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.3', java.version: '11.0.18'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, enableVNC: true, enableVideo: true, moz:debuggerAddress: true, moz:firefoxOptions: {}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, enableVNC: true, enableVideo: true, moz:debuggerAddress: true, moz:firefoxOptions: {}}}]
Capabilities {}`

Attaching logs from the selenoid docker container
[selenoid.log](https://github.com/aerokube/selenoid/files/12550121/selenoid.log)

**Selenium version used ** 4.5.3

**Comment by omarortega87** [comment]
I am having the same issue for Mobile on Android, due to the latest selenium version.

**Comment by vania-pooh** [comment]
@jyoti-c need browser container logs to diagnose.
