### ISSUE TITLE
can't connect to selenoid instance from robotframework using browser library

### ISSUE THREAD

**Issue by edsherwin** [aerokube/selenoid#1374]
Library    Browser

***Variables***
`${SELENOID_URL} =                   http://localhost:4444/wd/hub
${BROWSER_NAME} =                   chromium
${BROWSER_VERSION} =                108.0
${PLATFORM} =                       LINUX
${DESIRED_CAPABILITES} =            browserName=chromium        enableVideo=${True}
`
***Test Cases***
`Execute Tests in Selenoid Environment
    [Documentation]   Run various tests in Selenoid environment
    ${selenoid_caps}=   Create Dictionary   browserName=${BROWSER_NAME}   version=${BROWSER_VERSION}   platform=${PLATFORM}     enableVideo=${True}     enableVNC=${True}
    Open Browser    remote_url=${SELENOID_URL}   desired_capabilities=${selenoid_caps}`

or is there any api/websocket to use to initiate the connection between robot tests to selenoid

**Comment by vania-pooh** [comment]
@edsherwin take a look at https://github.com/aerokube/selenoid/issues/1108.

**Comment by edsherwin** [comment]
It seems that the Robot Framework **Browser** library doesn't support the direct use of custom desired capabilities, which are commonly used in Selenium-based automation.
https://docs.robotframework.org/docs/different_libraries/browser


*** Settings ***
Library    Browser

*** Variables ***
${SELENOID_URL} =                   http://localhost:4444/wd/hub
${BROWSER_NAME} =                   chromium
${BROWSER_VERSION} =                playwright-1.28.1
${PLATFORM} =                       LINUX
${DESIRED_CAPABILITES} =            browserName=chromium        enableVideo=${True}

*** Test Cases ***
Execute Tests in Selenoid Environment
    [Documentation]   Run various tests in Selenoid environment
    ${selenoid_caps}=   Create Dictionary   browserName=${BROWSER_NAME}   version=${BROWSER_VERSION}   platform=${PLATFORM}     enableVideo=${True}     enableVNC=${True}
    Open Browser    remote_url=${SELENOID_URL}   desired_capabilities=${selenoid_caps



Error


ValueError: Argument 'browser' got value 'desired_capabilities={'browserName': 'chromium', 'version': 'playwright-1.28.1', 'platform': 'LINUX', 'enableVideo': True, 'enableVNC': True}' that cannot be converted to SupportedBrowsers: SupportedBrowsers does not have member 'desired_capabilities={'browserName': 'chromium', 'version': 'playwright-1.28.1', 'platform': 'LINUX', 'enableVideo': True, 'enableVNC': True}'. Available: 'chromium', 'firefox' and 'webkit'
--

**Comment by vania-pooh** [comment]
@edsherwin it does, but how to do this is more complicated than in other frameworks.

**Comment by edsherwin** [comment]
Thanks @vania-pooh. I'll give a try to check alternative but If you have sample that would be great help. :)
