### ISSUE TITLE
SERVICE_STARTUP_FAILED

### ISSUE THREAD

**Issue by stru4OK** [aerokube/selenoid#1376]
Good evening! Struggling with the following error once try to connect to selenoid and create requested environment:

[root@uvairz5238 config]# podman logs selenoid
2023/09/21 16:43:41 [-] [INIT] [Loading configuration files...]
2023/09/21 16:43:41 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2023/09/21 16:43:41 [-] [INIT] [Video Dir: /opt/selenoid/video]
2023/09/21 16:43:41 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2023/09/21 16:43:41 [-] [INIT] [Your Docker API version is 1.41]
2023/09/21 16:43:41 [-] [INIT] [Timezone: UTC]
2023/09/21 16:43:41 [-] [INIT] [Listening on :4444]
2023/09/21 16:44:38 [-] [NEW_REQUEST] [unknown] [172.19.198.177]
2023/09/21 16:44:38 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.19.198.177]
2023/09/21 16:44:38 [11] [LOCATING_SERVICE] [chrome] []
2023/09/21 16:44:38 [-] [DEFAULT_VERSION] [Using default version: 116.0]
2023/09/21 16:44:38 [11] [USING_DOCKER] [chrome] [116.0]
2023/09/21 16:44:38 [11] [CREATING_CONTAINER] [selenoid/vnc_chrome:116.0]
2023/09/21 16:44:39 [11] [STARTING_CONTAINER] [selenoid/vnc_chrome:116.0] [05754d40c6db03f2ce24f222a98d026457a352f95f698eb727aeda8d8e145cf0]
2023/09/21 16:44:39 [11] [REMOVING_CONTAINER] [05754d40c6db03f2ce24f222a98d026457a352f95f698eb727aeda8d8e145cf0]
2023/09/21 16:44:39 [11] [FAILED_TO_REMOVE_CONTAINER] [05754d40c6db03f2ce24f222a98d026457a352f95f698eb727aeda8d8e145cf0] [Error response from daemon: container 05754d40c6db03f2ce24f222a98d026457a352f95f698eb727aeda8d8e145cf0 does not exist in database: no such container]
2023/09/21 16:44:39 [11] [SERVICE_STARTUP_FAILED] [start container: Error response from daemon: crun: write: No space left on device: OCI runtime error]

I use the following configuration: 
- OS: Red Hat Enterprise Linux release 9.2 (Plow);
- podman version 4.4.1;
- selenoid 1.11.0;
- browser containers: selenoid/vnc_firefox 117.0 or selenoid/vnc_opera 100.0 or selenoid/vnc_chrome 116.0.

As for the memory:
`[root@uvairz5238 Selenoid]# df
Filesystem               1K-blocks     Used Available Use% Mounted on
devtmpfs                      4096        0      4096   0% /dev
tmpfs                      8058120      168   8057952   1% /dev/shm
tmpfs                      3223252   337988   2885264  11% /run
/dev/mapper/vg_sys-root    3061760  2077968    983792  68% /
/dev/vda1                  1017736   356324    661412  36% /boot
/dev/mapper/vg_data-data 524027908 10985468 513042440   3% /data
/dev/vda2                   261864       20    261844   1% /boot/efi
/dev/mapper/vg_sys-opt     5109760   499536   4610224  10% /opt
/dev/mapper/vg_sys-home    5109760    69076   5040684   2% /home
/dev/mapper/vg_sys-var     5109760  1361592   3748168  27% /var
/dev/mapper/vg_sys-tmp     5109760    68780   5040980   2% /tmp
/dev/mapper/vg_sys-log     3061760  1586036   1475724  52% /var/log
/dev/mapper/vg_sys-audit   2037760    88216   1949544   5% /var/log/audit
shm                          64000        0     64000   0% /data/Podman/overlay-containers/f43aac621fb8390f6f3bfd4de641c0b0ffae3e0fe53b70dbf8e76473803b0124/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/a82ed2b97a4f49b4e181dd66709b372f9abd53da942e080ad4fac3affa44e1aa/merged
shm                          64000        0     64000   0% /data/Podman/overlay-containers/b438e9b9df1c2aeabcd185bf77afae9d863c100c4788525503fbf63ebf1c58dd/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/406d3ac78fcab5ebe58cae377c42cb9a251fa93e5b80fe71c44707abd935a557/merged
shm                          64000        0     64000   0% /data/Podman/overlay-containers/6e4ab44eddf4daa4317bbf17ed6bce827eaed28d5d5c201ee2fcf47a321090f5/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/e08358550f8057126ffc593e725f4f8196e2cd7c48c390d900fbec701a6dc1a9/merged
shm                          64000       28     63972   1% /data/Podman/overlay-containers/2def6767cd23d155604d411e471976a2a6d1c7cee5aa11fbcd9d304987efae02/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/22ae650f9f65cd6946462e24cbc18df0ca96ace57d77e51ef19cff71a7b156b8/merged
shm                          64000       28     63972   1% /data/Podman/overlay-containers/439ae6365a46071593886dcf315c08388fc0272e40ecc2d424df52d5473ed851/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/978aae548da46b2c677cdc6c702ec4cb49d0a09c9ae4b8cd14e107259b5c7de5/merged
shm                          64000        0     64000   0% /data/Podman/overlay-containers/64bac6c240c493da7178fdb4b8d42e85670a86982e32ace0cddd86e19451e00d/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/48f539a0c22e3f7b9b5fc4fc1b01503712fd18de9a637f730f2d89b3e9faa43b/merged
shm                          64000        0     64000   0% /data/Podman/overlay-containers/29e66bd5468f236b6eb6bd1dea3717c28991d5b443517b18b4465ea35cab13e5/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/861a82a8e159613769678c119e1a3cd023e57b025e4f999c20316cfda80ae3ed/merged
shm                          64000        0     64000   0% /data/Podman/overlay-containers/0ec50aa173ea5fad28a3a4f82cf777269214c0de07e2d412a5e60e122fb0bf6d/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/060a58961345a6f0dfa320d41b7c3d3d42091d6c14145375584a33b83289d76b/merged
tmpfs                      1611624        0   1611624   0% /run/user/5149
shm                          64000        0     64000   0% /data/Podman/overlay-containers/28e1270922a7ee156b6a148a191991e4786777c3f81695fbd5488a1f35e739f9/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/ff88fb10b1980fd43058c500981a7cbc4cb50312201880bf56dc2c44790dde21/merged
shm                          64000        0     64000   0% /data/Podman/overlay-containers/0c1f2a34897d0a8b2a6599f259441e23b4f7ce8fbcb916a21dd0534221d8e54e/userdata/shm
overlay                  524027908 10985468 513042440   3% /data/Podman/overlay/0b358815ebae7a653ca8255f678f844bde40648f977acdb345d7d2a176130bba/merged
[root@uvairz5238 Selenoid]#
`

**Comment by stru4OK** [comment]
Problem was solved. Root cause was in browsers.json, namely I've indicated tmpfs as follows: 
"opera": {
        "default": "100.0",
        "versions": {
            "100.0" : {
                "image": "selenoid/vnc_opera:100.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=1024m", "/var": "size=256"
                }
            }
        }
    }

I've delete tmpfs section and now it works. Could anybody explain me that even though I have enough free space why it considers that I don't have it?

And another problem that I've faced off after delete tmpfs section from browsers.json file:

2023/09/22 13:21:38 [46] [SERVICE_STARTUP_FAILED] [start video container: create video container: Error response from daemon: bad parameter: link is not supported]

Video container is presented:
`
[root@uvairz5238 config]# podman images
REPOSITORY                         TAG         IMAGE ID      CREATED       SIZE
docker.io/aerokube/selenoid        latest      f919325dede1  2 days ago    19.2 MB
docker.io/selenoid/vnc_firefox     117.0       92ae4d2b9e7c  4 weeks ago   1.22 GB
docker.io/selenoid/vnc_chrome      116.0       3e9826770c23  4 weeks ago   1.23 GB
docker.io/selenoid/vnc_opera       100.0       ee5f4c7d2c71  2 months ago  1.36 GB
docker.io/aerokube/selenoid-ui     latest      28a85efc262a  4 months ago  18 MB
docker.io/selenoid/video-recorder  latest      c8018c23fcb7  4 years ago   30.9 MB
`

**Comment by stru4OK** [comment]
Found this article: https://github.com/containers/podman/issues/11717
Does it confirm that Selenoid could be used only with docker and not podman?

**Comment by vania-pooh** [comment]
@stru4OK we never tested Selenoid on podman. Also podman by default has no REST API and Selenoid relies on Docker API.

**Comment by stru4OK** [comment]
Hello!
Yes, my bad! I've read your prerequisites but didn't realize that podman can't completely substitute docker. So right now I've removed podman and installed docker and now so far so good.
Thank you!
