### ISSUE TITLE
Manual Session itself is not getting created: Chrome failed to start: exited normally (DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by ShivaPotlapelli** [aerokube/selenoid#1380]
**Description:**
I encountered the above error while using Selenoid with Chrome. It seems to be related to Chrome not starting correctly.

**Steps to Reproduce:**
1. create the session manually from Selenoid UI 

**Expected Behavior:**
Session should be created for the corresponding version of chrom

**Additional Information:**
- Selenoid Version: 1.11.0
- Chrome Version: 117

**Screenshots or Log Files:**
<img width="1728" alt="Screenshot 2023-10-30 at 11 44 05 AM" src="https://github.com/aerokube/selenoid/assets/32088143/867d81d4-9bb5-45b1-a375-481e58d49155">
<img width="1717" alt="Screenshot 2023-10-30 at 11 44 14 AM" src="https://github.com/aerokube/selenoid/assets/32088143/76b2c925-d31a-43d9-83fb-0c3ac40e686a">

**Comment by ShivaPotlapelli** [comment]
@DudaGod please look into this in case u have any idea as am using this version for playwright tests to run on selenoid

**Comment by ShivaPotlapelli** [comment]
@DudaGod I have seen those and I have added necessary agruments as well still it is showing up the same issue

**Comment by ShivaPotlapelli** [comment]
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'http://localhost:8080/wd/hub/session',
  'headers': {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    "capabilities": {
      "alwaysMatch": {
        "browserName": "chrome",
        "browserVersion": "117.0",
        "selenoid:options": {
          "enableVNC": true,
          "sessionTimeout": "60m",
          "labels": {
            "manual": "true"
          }
        }
      },
      "firstMatch": [
        {}
      ]
    },
    "goog:chromeOptions": {
      "args": [
        "--test-type",
        "--no-sandbox",
        "--disable-dev-shm-usage"
      ],
      "prefs": {
        "profile.content_settings.exceptions.clipboard": {
          "[*.],*": {
            "last_modified": "1576491240619",
            "setting": 1
          }
        }
      }
    }
  })

};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});

@DudaGod this is the request am making for session creation

**Comment by ShivaPotlapelli** [comment]
@vania-pooh can you help me out here ??

**Comment by vania-pooh** [comment]
@ShivaPotlapelli Google Chrome e.g. will never work on Mac M1 and similar ARM processor. What is your platform?

**Comment by ShivaPotlapelli** [comment]
@vania-pooh Yes it is ARM Processor

**Comment by ShivaPotlapelli** [comment]
Thanks for confirmation
