### ISSUE TITLE
Error Occurs When Starting CM With "-container-network"

### ISSUE THREAD

**Issue by damiensprinkle** [aerokube/selenoid#1385]
I am trying to setup selenoid as part of azure devops ci/cd and would like to connect it to the existing dotnet container so they can easily communicate with each other

Relevant YML: 
```
  jobs:
  - job: SelenoidTest
    container:
      image: 'azurecr.io/dotnet/core/sdk:3.1-bionic'
      endpoint: Azure Container Registry
    steps:    
    
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.0'

    - script: |
        echo "==== Get DotNet Container Network ===="
        vsts_network_name=$(docker network ls --format "{{.Name}}" | grep 'vsts_network' || true)
        echo "VSTS Network Name: $vsts_network_name"
   
        echo "===== Setup Selenoid ====="
        curl -sSL -o cm https://github.com/aerokube/cm/releases/download/1.8.5/cm_linux_amd64
        chmod +x cm
        
        ./cm selenoid start -container-network $vsts_network_name
        sleep 15
```
The error that occurs is the following:

Configuration saved to ontainer-network/browsers.json
> Starting Selenoid...
x Failed to start: failed to create container: Error response from daemon: create ontainer-network/video: "ontainer-network/video" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

**Comment by vania-pooh** [comment]
@damiensprinkle in CM container network is hard-coded to `selenoid`. If you wish to do any customizations in Selenoid setup - use raw `docker run` command instead.
