### ISSUE TITLE
@wdio/runner: Error: Failed to create session. getaddrinfo EAI_AGAIN selenoid

### ISSUE THREAD

**Issue by en-aplecan** [aerokube/selenoid#1387]
Hi! I am trying to run webdriverIO tests on gitlab using selenoid. 
My setup looks like this:
- In wdio.conf file I have like this: exports.config = {
    hostname: 'selenoid',
    port: 4444,
    path: "/wd/hub",
....}
- Added to browser capabilities the following options:
<img width="606" alt="Screenshot 2023-12-11 at 15 52 52" src="https://github.com/aerokube/selenoid/assets/139208959/5d018d85-43fd-4bf9-ac78-1ecae40df026">

- here is gitlab-ci.yml file:
cache:
  paths:
    - node_modules/

default:
  image: alpine:latest

variables:
  FF_NETWORK_PER_BUILD: 1

stages:
  - test

test:
  stage: test
  services:
    - name: aerokube/selenoid:latest
    - name: selenoid/chrome:latest
  variables:
    # for the hub
    HUB_HOST: selenoid
    HUB_PORT: 4444
    GRID_BROWSER_TIMEOUT: 45000
    GRID_TIMEOUT: 45000
    # for the node-firefox
    SE_NODE_SHM_SIZE: 2gb # this does not have any effect, because it can only be set in the 'config.toml'. Therefore, I can't ramp up the No. of instances.
    SE_EVENT_BUS_HOST: selenoid
    SE_EVENT_BUS_PUBLISH_PORT: 4442
    SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    SE_NODE_GRID_URL: http://selenoid:4444
    LOCAL_ADMIN_PASS: "$LOCAL_ADMIN_PASS"
    STANDARD_TIMEOUT: "$STANDARD_TIMEOUT"

  before_script:
    - echo "This pipeline was started by '$CI_PIPELINE_SOURCE'" # possible values are push, web, schedule, merge_request_event, etc.
    - echo "The environment passed was '$ENVIRONMENT'"
    - echo "The test suite passed was '$SUITE'"

    - if [[ "$SUITE" == "" ]]; then
      echo "The variable 'SUITE' is empty or was NOT passed. Setting default value as SUITE=healthChecks";
      export SUITE="healthChecks";
      fi

    - echo "The job will now run with the value suite=$SUITE";

    - apk update -q
    - apk add --update nodejs npm openjdk8-jre -q
    - npm --silent install
    - node --version
    - npm -version
  script:
    - ENV=$ENVIRONMENT npm test -- --suite $SUITE
  after_script:
    - npm run generate
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - logs
      - report/allure-report

But an error occurs:
2023-12-11T14:52:54.268Z INFO webdriver: Initiate new session using the WebDriver protocol
2023-12-11T142023-12-11T14:53:14.692Z ERROR @wdio/runner: Error: Failed to create session.
getaddrinfo EAI_AGAIN selenoid

Could you help me please to setup correctly wdio? Thank you!

**Comment by vania-pooh** [comment]
@en-aplecan we are Golang developers, I would address this question to wdio support. But your issue is probably that you are trying to access domain name `selenoid`, port `4444` which does not exist. Make sure your are using correct container name.
