### ISSUE TITLE
Not able to create Chrome image with patched undetected_chromedriver

### ISSUE THREAD

**Issue by iamumairayub** [aerokube/selenoid#1388]
Hi @vania-pooh 

We have a use case where we need to scrape a few websites while staying undetected as much as possible.

We are using Selenoid on our Ubuntu 20.04 VPS and we really like it because of having ability to see real-time browser sessions in our browser and capability of recording videos.

We used this command to deploy Selenoid.

`./cm_linux_amd64 Selenoid start --vnc --browsers-json browsers.json`

And `browsers.json` looks like

```
{
    "chrome": {
        "default": "117.0",
        "versions": {
            "117.0": {
                "image": "selenoid/chrome:117.0",
                "port": "4444",
                "path": "/",
                "shmSize" : 4147483648
            }
        }
    }
}
```

So I ALREADY have patched `chromedriver` binaries that work perfectly when I use them locally.

What I would like is to build an image with that patched binary and be able to upload that image to Selenoid using above `browsers.json`

I saw your comment here https://github.com/aerokube/selenoid/issues/1226#issuecomment-1558773198

so here is what I did.

1. I got patched chromedriver binary from `~/.local/share/undetected_chromedriver`  which was generated by the https://github.com/ultrafunkamsterdam/undetected-chromedriver itself.

2. Dockerfile I have 

```
FROM selenoid/chrome:119.0

USER root
COPY undetected_chromedriver /usr/bin/chromedriver
USER selenium
```

3. `docker build . -t my_dockerhub_id/uc_selenoid`

4. `docker push my_dockerhub_id/uc_selenoid`

5. `./cm_linux_amd64 selenoid cleanup`

6. replaced `"image": "selenoid/chrome:117.0"` with `"image": "my_dockerhub_id/uc_selenoid"`

7. `./cm_linux_amd64 selenoid start --vnc --browsers-json browsers.json`

Then from my Selenoid UI I tried clicked on Create Session but it keeps showing Pending in the top-right of my Selenoid UI

Selenoid docker logs shows

```
2023/12/19 10:48:14 [2] [LOCATING_SERVICE] [chrome] [119.0]
2023/12/19 10:48:14 [2] [USING_DOCKER] [chrome] [119.0]
2023/12/19 10:48:14 [2] [CREATING_CONTAINER] [my_dockerhub_id/uc_selenoid]
2023/12/19 10:48:14 [2] [STARTING_CONTAINER] [my_dockerhub_id/uc_selenoid] [3cfb62c713694edb1f5016ab62170216acb5228e2092adeebed993e7998de0dd]
2023/12/19 10:48:14 [2] [CONTAINER_STARTED] [my_dockerhub_id/uc_selenoid] [3cfb62c713694edb1f5016ab62170216acb5228e2092adeebed993e7998de0dd] [0.34s]


2023/12/19 10:51:14 [2] [REMOVING_CONTAINER] [3cfb62c713694edb1f5016ab62170216acb5228e2092adeebed993e7998de0dd]
2023/12/19 10:51:15 [2] [CONTAINER_REMOVED] [3cfb62c713694edb1f5016ab62170216acb5228e2092adeebed993e7998de0dd]
2023/12/19 10:51:15 [2] [SERVICE_STARTUP_FAILED] [wait: http://172.18.0.4:4444/ does not respond in 3m0s]
```

Btw, what is 172.18.0.4 ??? some docker internal IP? its not my server IP though.

After little bit of more research I found this [entrypoint.sh](https://github.com/aerokube/images/blob/fc8ecc442dce2d956e58a21fd68bd14c6ef70c92/static/chrome/entrypoint.sh) 
So now Dockerfile looks like

```
FROM selenoid/chrome:119.0

USER root

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY undetected_chromedriver /usr/bin/chromedriver
USER selenium

EXPOSE 4444

ENTRYPOINT ["/entrypoint.sh"]
```

I repeated all of steps from 2 to 7 but again the logs of **aerokube/selenoid:1.11.0** container show same output

@vania-pooh how about you share complete `Dockerfile` of `selenoid/chrome:117.0`?

**Comment by vania-pooh** [comment]
@iamumairayub make sure undetected chromedriver is starting on port 4444 and listens on all network interfaces `0.0.0.0` \ `::`.

**Comment by iamumairayub** [comment]
Ok I finally managed to upload my patched chromedriver binary to Selenoid and successfully launched the Selelnoid session.

Here is final Dockerfile I used.

```
FROM selenoid/chrome:119.0

USER root

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY undetected_chromedriver /usr/bin/chromedriver
RUN chmod +x /usr/bin/chromedriver

USER selenium

EXPOSE 4444

ENTRYPOINT ["/entrypoint.sh"]
```

Only difference is now it has `RUN chmod +x /usr/bin/chromedriver`  because I saw it had permission issues by checking `docker logs my-docker-container-id`

**Comment by iamumairayub** [comment]
@vania-pooh after lots of digging into **undetected_chromedriver** code I found out that it first launches chrome binary with `remote-debugging-host` and `remote-debugging-port` arguments and then passes those same parameters to **chromedriver** that connects to that browser session.

Here are last 3 lines of my `entrypoint.sh`, all other code of this file is same 

```
DISPLAY="$DISPLAY" /usr/bin/chromedriver --remote-debugging-host=127.0.0.1 --port=4444 --allowed-ips='' --allowed-origins='*' ${DRIVER_ARGS} &
DRIVER_PID=$!
mkdir /tmp/tmpvhj68isx
DISPLAY="$DISPLAY" /usr/bin/google-chrome --remote-debugging-host=127.0.0.1 --remote-debugging-port=4444 --user-data-dir=/tmp/tmpvhj68isx --lang=en-US --no-default-browser-check --no-first-run --no-sandbox --test-type --window-size=1920,1080 --start-maximized --no-sandbox --log-level=0

wait
```

I have this Python code

```
from selenium import webdriver
options = webdriver.ChromeOptions()
options.headless = False
selenoid_options = {
    'enableVNC': True, 
    "browserName": "chrome",
    "platform": "ANY",
    "version": "my_uc_image"
}
options.set_capability("selenoid:options", selenoid_options)
driver = webdriver.Remote(command_executor='http://my-server:4444/wd/hub', options=options)
driver.get('https://nowsecure.nl')
```

but Selenoid session launches 2 chrome browsers and website is not opening in the browser that I want, instead its opening in other browser that has `Chrome is being controlled by automated test software`

![image](https://github.com/aerokube/selenoid/assets/13570295/2f097520-0ac7-4fb8-9b5d-a301d49b9d6d)

Also there errors in **docker logs** like

```
Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Failed to connect to the bus: Address does not contain a colon
socket_posix.cc(147)] bind() failed: Address already in use (98)
socket_posix.cc(147)] bind() failed: Cannot assign requested address (99)
devtools_http_handler.cc(311)] Cannot start http server for devtools
```

[Here](https://pastebin.com/raw/N2DQh0Rh) are full logs of that container.

Any suggestion on how do I control that browser with my Python code using `driver.get('....')` ?

**Comment by vania-pooh** [comment]
@iamumairayub it makes no sense to launch Chrome automatically in entrypoint. Chromedriver should do this automatically.

**Comment by iamumairayub** [comment]
Ok now I have same [entrypoint.sh](https://github.com/aerokube/images/blob/fc8ecc442dce2d956e58a21fd68bd14c6ef70c92/static/chrome/entrypoint.sh) as of yours. Last lines look like this

```
DISPLAY="$DISPLAY" /usr/bin/undetected_chromedriver --port=4444 --allowed-ips='' --allowed-origins='*' ${DRIVER_ARGS} &
DRIVER_PID=$!

wait
```

In my `Dockerfile` as you can see above, I have this

`COPY undetected_chromedriver /usr/bin/chromedriver`

So why does it launches this default chromdriver that has `chrome is being controlled by automated software` instead my patched `undetected_chromedriver`  

![image](https://github.com/aerokube/selenoid/assets/13570295/b7680f84-a0ca-4e31-bd9d-a281495b8c2a)

**Comment by vania-pooh** [comment]
@iamumairayub probably you have to override `ENTRYPOINT` section.

**Comment by iamumairayub** [comment]
@vania-pooh last lines of my entrypoint.sh looks like 

```
echo "starting undetected_chromedriver" # <<<<<<<< NOTICE THIS
DISPLAY="$DISPLAY" /usr/bin/undetected_chromedriver --port=4444 --allowed-ips='' --allowed-origins='*' ${DRIVER_ARGS} &
DRIVER_PID=$!

wait
```

Dockerfile looks like 

```
FROM selenoid/chrome:121.0

ENTRYPOINT []

USER root

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY undetected_chromedriver /usr/bin/undetected_chromedriver
RUN chmod +x /usr/bin/undetected_chromedriver

USER selenium

EXPOSE 4444

ENTRYPOINT ["/entrypoint.sh"]
```

but still getting same results as above

 `docker logs container-id` also prints `starting undetected_chromedriver`

bashing into that container also says `undetected_chromedriver` was started

`docker exec -it container-id bash`
```
selenium@39bd78547163:/$ ps aux | grep undetected
selenium      70  0.0  0.0 33627124 14744 ?      Sl   10:39   0:00 /usr/bin/undetected_chromedriver --port=4444 --allowed-ips= --allowed-origins=*
```

**Comment by iamumairayub** [comment]
@vania-pooh actually that was not required.
I have figured it out.
Its actually the undetected_chromedriver being launched in above screenshot.
I just needed to pass some extra arguments to driver.

**Comment by vania-pooh** [comment]
@iamumairayub so closing then?

**Comment by iamumairayub** [comment]
@vania-pooh yeah I will close because this ticket was "how to upload custom chromedriver to selenoid"

**Comment by nhanvu327** [comment]
> @vania-pooh actually that was not required. I have figured it out. Its actually the undetected_chromedriver being launched in above screenshot. I just needed to pass some extra arguments to driver.

@iamumairayub  what extra arguments that you needed to pass to the driver? Could you please provide full solutions ? I would really appreaciate it. Thanks

**Comment by iamumairayub** [comment]
@nhanvu327 I just copied args whatever UC uses https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/0aa5fbe252370b4cb2b95526add445392cad27ba/undetected_chromedriver/__init__.py#L453

and passed it as options into `Remote()`

`--remote-debugging-host=127.0.0.1 --remote-debugging-port=59932 --user-data-dir=C:\Users\User\AppData\Local\Temp\tmpxu3z1o3o --lang=en-US --no-default-browser-check --no-first-run --no-sandbox --test-type --window-size=1920,1080 --start-maximized --no-sandbox --log-level=0`

**Comment by hnnoye04** [comment]
@iamumairayub did your one pass https://www.browserscan.net/bot-detection or https://pixelscan.net/ .We https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1600 have pass iphey but no these two :(

**Comment by iamumairayub** [comment]
No, 
its because iphey is less strict
pixelscan is very strict, it maybe didnt pass because it detected your OS or maybe you are using proxy that is being detected as proxy instead of a real person's IP

**Comment by hnnoye04** [comment]
@iamumairayub time to work with his new amazing work https://github.com/ultrafunkamsterdam/nodriver

**Comment by iamumairayub** [comment]
@hnnoye04 thanks, I saw that 3 days ago, I have several projects running with Selenium so its hard for me to switch over to it as of now.
Btw, I tested pixelscan on nodriver on my VPS and it failed all tests

**Comment by hnnoye04** [comment]
@iamumairayub 
<img width="1267" alt="image" src="https://github.com/aerokube/selenoid/assets/79848180/26cd24de-53fa-47e5-9a0c-b0f8322fd7da"> 
<img width="1267" alt="image" src="https://github.com/aerokube/selenoid/assets/79848180/a2dfcbb3-41d7-4964-afcb-9cdca6d06aa4">
the nodriver was so sick maybe it detected your VPS ip try residential proxy.Going to test nodriver on window and linux when i back home `import asyncio
import nodriver as uc

async def main():
    browser = await uc.start()
    page = await browser.get('https://pixelscan.net/')

    await page.save_screenshot()
    await page.get_content()
    await page.scroll_down(150)
    await page.sleep(100)
    


if __name__ == '__main__':

    # since asyncio.run never worked (for me)
    uc.loop().run_until_complete(main())`

**Comment by hnnoye04** [comment]
You can use recording extension in chrome and Ofc live session same as real chrome but no like solenoid Ofc I have sent my contact to your gmail.

**Comment by iamumairayub** [comment]
@hnnoye04 havent received your email, nothing in spams as well. 
here is my email iamumairayub@gmail.com

**Comment by mastercoding** [comment]
@iamumairayub Do you have the final image uploaded to docker hub?

**Comment by iamumairayub** [comment]
@mastercoding https://hub.docker.com/r/iamumairayub/uc_selenoid

**Comment by dempc6469** [comment]
> @mastercoding https://hub.docker.com/r/iamumairayub/uc_selenoid

you sir ... are awesome! thank you for this! @iamumairayub
