### ISSUE TITLE
Failed container creation

### ISSUE THREAD

**Issue by admizh** [aerokube/selenoid#139]
```
docker --version
Docker version 17.03.1-ce, build c6d412e
```
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

```
sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /root:${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128
2017/07/01 01:28:39 Using Docker...
2017/07/01 01:28:39 registry.ping url=https://registry.hub.docker.com/v2/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x7e2353]

goroutine 1 [running]:
github.com/aerokube/cm/cmd.startImpl(0x0)
        /home/travis/gopath/src/github.com/aerokube/cm/cmd/selenoid_start.go:18 +0x43
github.com/aerokube/cm/cmd.glob..func6(0xb672e0, 0xc4201b1cb0, 0x0, 0x3)
        /home/travis/gopath/src/github.com/aerokube/cm/cmd/selenoid_start.go:12 +0x2c
github.com/aerokube/cm/vendor/github.com/spf13/cobra.(*Command).execute(0xb672e0, 0xc4201b1c20, 0x3, 0x3, 0xb672e0, 0xc4201b1c20)
        /home/travis/gopath/src/github.com/aerokube/cm/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/aerokube/cm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb66840, 0xb67720, 0xc42017df68, 0x7e304c)
        /home/travis/gopath/src/github.com/aerokube/cm/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/aerokube/cm/cmd.Execute()
        /home/travis/gopath/src/github.com/aerokube/cm/cmd/root.go:26 +0x2d
main.main()
        /home/travis/gopath/src/github.com/aerokube/cm/cm.go:8 +0x20
```

```
curl https://registry.hub.docker.com/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```
```
curl https://api.github.com/repos/aerokube/selenoid/releases/latest
{
  "url": "https://api.github.com/repos/aerokube/selenoid/releases/6746048",
  "assets_url": "https://api.github.com/repos/aerokube/selenoid/releases/6746048/assets",
  "upload_url": "https://uploads.github.com/repos/aerokube/selenoid/releases/6746048/assets{?name,label}",
  "html_url": "https://github.com/aerokube/selenoid/releases/tag/1.3.2",
  "id": 6746048,
  "tag_name": "1.3.2",
...
```

**Comment by vania-pooh** [comment]
@admizh thank you for the feedback. Will investigate.

**Comment by vania-pooh** [comment]
Fixed NPE in https://github.com/aerokube/cm/pull/40. But what's more interesting - the reason why Docker client fails to initalize in your case. Could you please try with `aerokube/cm:latest` - it already includes this fix?

**Comment by admizh** [comment]
Hi, thak you, now i see: 
```sudo docker run --rm -v /var/run/docker.sock:/var/run/do                                                                                        cker.sock -v /root:${HOME} aerokube/cm:latest selenoid start --vnc --tmpfs 128                                                                                          Unable to find image 'aerokube/cm:latest' locally
latest: Pulling from aerokube/cm
019300c8a437: Pull complete
e5483862f3cb: Pull complete
adc5deed4e82: Pull complete
Digest: .....i gue
Status: Downloaded newer image for aerokube/cm:latest
2017/07/01 19:45:41 Using Docker...
2017/07/01 19:45:41 registry.ping url=https://registry.hub.docker.com/v2/
Failed to initialize: [new configurator: Docker Registry is not available: Get https://registry.hub.docker.com/v2/: dial tcp ...: i/o timeout]
```
I guess CM not picked up proxy settings variables.

**Comment by vania-pooh** [comment]
@admizh I think you could to try to use `HTTP_PROXY` style environment variables described here: https://docs.docker.com/engine/admin/systemd/#runtime-directory-and-storage-driver So far as we are using the same client as Docker does I think something like this should work:
```
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e HTTP_PROXY=http://myproxy.example.com:8080 -v /root:${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128
```

**Comment by admizh** [comment]
Thank you for fast response! Yes it work now. Can you add this point to quick start guide?
`sudo docker run --rm -e HTTP_PROXY=proxy:8080 -v /var/run/docker.sock:/var/run/docker.sock -v /root:${HOME} aerokube/cm:latest selenoid start --vnc --tmpfs 128`
`sudo docker run --rm  -e HTTP_PROXY=proxy:8080 -d --name selenoid-ui --link selenoid  -p 90:8080 aerokube/selenoid-ui --selenoid-uri=http://selenoid:4444`
![image](https://user-images.githubusercontent.com/6014483/27765512-38a9c254-5ec4-11e7-8122-ac10fd4f2854.png)
And second issue:
![image](https://user-images.githubusercontent.com/6014483/27765538-096c0190-5ec5-11e7-8871-e80cd2f4721f.png)
Why my selenoid-ui not able to connect provide any browsers in DDL, i have connectivity issues betwen containers?

**Comment by vania-pooh** [comment]
@admizh `cm` by default creates config file in `~/.aerokube/selenoid/browers.json` (`C:\Users\my-user\.aerokube/selenoid` on Windows) - please check there. Regarding UI - need to understand why UI container can't access Selenoid container (btw, on your containers listing screenshot Selenoid is not running). Added note about working behind proxies to Selenoid [quick start guide](http://aerokube.com/selenoid/latest/#_quick_start_guide).

**Comment by vania-pooh** [comment]
@admizh JFYI we are also answering to any questions in Telegram chat here: https://telegram.me/aerokube

**Comment by vania-pooh** [comment]
@admizh it seems that we resolved proxy issue in Telegram. Any more research xhere?

**Comment by admizh** [comment]
Hi @vania-pooh now selenoid-ui container able to get status from solenoid container. Thanks for advising and quick help.
I use this comands:
`sudo -i`
for execute selenoid container (with proxy):
`docker run --rm -e HTTP_PROXY=proxy:8080 -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root aerokube/cm:latest selenoid start --vnc --tmpfs 128`
for execute selenoid-ui container (without proxy)
`docker run --rm -d --name selenoid-ui --link selenoid  -p 8080:8080 aerokube/selenoid-ui  --selenoid-uri=http://selenoid:4444
`
Ui container was able to obtain data from selenoid. I saw a list of browsers on the UI:

![image](https://user-images.githubusercontent.com/6014483/27903264-be0beec6-6249-11e7-9fc2-01ddfbcd1b29.png)

After thath i create simple test for checking:

```java
    @Test
    public void test() throws MalformedURLException, InterruptedException {
        DesiredCapabilities browser = new DesiredCapabilities();
        browser.setBrowserName("chrome");
        browser.setVersion("58.0");
        RemoteWebDriver driver = new RemoteWebDriver(
                URI.create("http://myip:4444/wd/hub").toURL(),
                browser
        );
        driver.navigate().to("http://ya.ru");
    }
```

And i get error:
```
	org.openqa.selenium.WebDriverException: wait: http://172.17.0.3:4444/ does not respond in 30s (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 30.73 seconds
	Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
	System info: host: 'myhost', ip: 'myip', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: RemoteWebDriver
```
```
	docker logs selenoid
	
	2017/07/06 08:24:54 Timezone: UTC
	2017/07/06 08:24:54 Listening on :4444
	2017/07/06 08:25:21 [NEW_REQUEST]
	2017/07/06 08:25:21 [NEW_REQUEST_ACCEPTED]
	2017/07/06 08:25:21 [0] [LOCATING_SERVICE] [chrome-58.0]
	2017/07/06 08:25:21 [0] [USING_DOCKER] [chrome-58.0]
	2017/07/06 08:25:21 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_58.0]
	2017/07/06 08:25:21 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_58.0] [d50cabf1e07de636713b21958909f1609c7ce54b57780a5afce3a98d8e125f29]
	2017/07/06 08:25:21 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_58.0] [d50cabf1e07de636713b21958909f1609c7ce54b57780a5afce3a98d8e125f29] [169.657937ms]
	2017/07/06 08:25:51 [0] [REMOVE_CONTAINER] [d50cabf1e07de636713b21958909f1609c7ce54b57780a5afce3a98d8e125f29]
	2017/07/06 08:25:52 [0] [CONTAINER_REMOVED] [d50cabf1e07de636713b21958909f1609c7ce54b57780a5afce3a98d8e125f29]
	2017/07/06 08:25:52 [0] [SERVICE_STARTUP_FAILED] [unknown] [wait: http://172.17.0.3:4444/ does not respond in 30s]
	panic: send on closed channel
	
	goroutine 8 [running]:
	github.com/aerokube/selenoid/service.wait.func1(0xc420237e00, 0x17, 0xc4201d7020)
	        /home/travis/gopath/src/github.com/aerokube/selenoid/service/service.go:68 +0x15e
	created by github.com/aerokube/selenoid/service.wait
        /home/travis/gopath/src/github.com/aerokube/selenoid/service/service.go:74 +0xce
```

After that, tried to start the selenoid from `cm` binary, (without proxy):
```
curl -L -o cm https://github.com/aerokube/cm/releases/download/1.1.2/cm_linux_amd64
chmod +x ./cm
./cm selenoid start --vnc
```
And agains get error during test execution:

```
2017/07/06 08:35:15 Timezone: UTC
2017/07/06 08:35:15 Listening on :4444
2017/07/06 08:36:58 [NEW_REQUEST]
2017/07/06 08:36:58 [NEW_REQUEST_ACCEPTED]
2017/07/06 08:36:58 [0] [LOCATING_SERVICE] [firefox-53.0]
2017/07/06 08:36:58 [0] [USING_DOCKER] [firefox-53.0]
2017/07/06 08:36:58 [0] [CREATING_CONTAINER] [selenoid/firefox:53.0]
2017/07/06 08:36:58 [0] [STARTING_CONTAINER] [selenoid/firefox:53.0] [02b3a8d53e8e713aad833b963c099a66b3f8b0f9aa205e28ebb170f0f9806d04]
2017/07/06 08:36:58 [0] [CONTAINER_STARTED] [selenoid/firefox:53.0] [02b3a8d53e8e713aad833b963c099a66b3f8b0f9aa205e28ebb170f0f9806d04] [167.094168ms]
2017/07/06 08:37:28 [0] [REMOVE_CONTAINER] [02b3a8d53e8e713aad833b963c099a66b3f8b0f9aa205e28ebb170f0f9806d04]
2017/07/06 08:37:28 [0] [CONTAINER_REMOVED] [02b3a8d53e8e713aad833b963c099a66b3f8b0f9aa205e28ebb170f0f9806d04]
2017/07/06 08:37:28 [0] [SERVICE_STARTUP_FAILED] [unknown] [wait: http://172.17.0.4:4444/wd/hub does not respond in 30s]
```

**Comment by mom143** [comment]
Selenoid-ui is not able to provide any browsers list[browser selection keep on loading] ,how can i resolve the issue? 
![selenoid](https://user-images.githubusercontent.com/29034252/32773211-644e9ce6-c94e-11e7-8a17-c71b51bcecd5.png)

**Comment by vania-pooh** [comment]
@mom143 UI should have both "Selenoid" and "SSE" indicators green. If one of them is red - then something is wrong with installation. Do you e.g. have a firewall and antivirus software enabled?

**Comment by kenlma** [comment]
hi
I have the same issue. our network behind company proxy. I start selenoid with http proxy like this
HTTP_PROXY=http://proxy:port/ ./cm selenoid start --vnc --port=port
this will fix selenoid ui load browser issue. but will meet test execution issue. this my docker log
2017/11/16 23:03:27 [NEW_REQUEST]
2017/11/16 23:03:27 [NEW_REQUEST_ACCEPTED]
2017/11/16 23:03:27 [1] [LOCATING_SERVICE] [chrome-61.0]
2017/11/16 23:03:27 [1] [USING_DOCKER] [chrome-61.0]
2017/11/16 23:03:27 [1] [CREATING_CONTAINER] [selenoid/chrome:61.0]
2017/11/16 23:03:27 [1] [STARTING_CONTAINER] [selenoid/chrome:61.0] [a5da2eebfeec721c7c0589d4cae72e3a68eff3bc38d7e3899f3af80cb1e7036b]
2017/11/16 23:03:27 [1] [CONTAINER_STARTED] [selenoid/chrome:61.0] [a5da2eebfeec721c7c0589d4cae72e3a68eff3bc38d7e3899f3af80cb1e7036b] [276.200688ms]
2017/11/16 23:03:57 [1] [REMOVE_CONTAINER] [a5da2eebfeec721c7c0589d4cae72e3a68eff3bc38d7e3899f3af80cb1e7036b]
2017/11/16 23:03:58 [1] [CONTAINER_REMOVED] [a5da2eebfeec721c7c0589d4cae72e3a68eff3bc38d7e3899f3af80cb1e7036b]
2017/11/16 23:03:58 [1] [SERVICE_STARTUP_FAILED] [unknown] [wait: http://172.17.0.4:4444/ does not respond in 30s]

any ideal for this issue?

**Comment by vania-pooh** [comment]
@kenlma you should specify HTTP proxy in your tests then. Something like this:
```java
        String proxyHost = "proxy.example.com:8080";
        Proxy proxy = new Proxy();
        proxy
                .setProxyType(Proxy.ProxyType.MANUAL)
                .setHttpProxy(proxyHost)
                .setFtpProxy(proxyHost)
                .setSslProxy(proxyHost)
                .setNoProxy("");
        caps.setCapability(CapabilityType.PROXY, proxy);
```
Selenium does not respect HTTP_PROXY variable.

**Comment by vania-pooh** [comment]
@admizh is it fixed or not relevant anymore?

**Comment by admizh** [comment]
@vania-pooh yes, i tried again with latest versions. Now it's work fine

My actions: 
1. Set proxy via systemd: https://docs.docker.com/config/daemon/systemd/
2. Start Selenoid via cm: 
```
./cm selenoid cleanup && ./cm selenoid configure --vnc --browsers firefox,chrome,opera --last-versions 5 --tmpfs 128 && ./cm selenoid start --port 4444 --args "-limit 2 -enable-file-upload -service-startup-timeout 90s -session-attempt-timeout 90s -session-delete-timeout 90s -timeout 120s"
```
3. Start selenoid-ui via docker (not cm), when using cm --> selenoid-ui still not up connection with selenoid
```
DOCKER_GATEWAY_ADDR=`docker inspect selenoid -f {{.NetworkSettings.Gateway}}`
echo $DOCKER_GATEWAY_ADDR
docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui --selenoid-uri http://${DOCKER_GATEWAY_ADDR}:4444
```
4. Set selenium proxy capabilities

**Comment by KathiresanRamkumar95** [comment]
How to specify --last-version in a browsers.json file?

**Comment by KathiresanRamkumar95** [comment]
I don't want firefox and opera and video recorder images in the selenoid docker container. How do I prevent from download this ?     
@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 `video-recorder` is always downloaded, no way to disable this in CM. To download only Chrome type:
```
$ ./cm selenoid start --browsers chrome --last-versions 5
```

**Comment by KathiresanRamkumar95** [comment]
But using docker How do I download chrome only ?
@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 just do `docker pull` only for `selenoid/chrome:XXX` images.

**Comment by admizh** [comment]
@KathiresanRamkumar95 - if you have problems with browsers downloading and you used command from my previous post, then:
Selenoid have changes in `-- browsers` switch (comma separator not supported), i had update my post. 
please try this:
```$sh
./cm selenoid cleanup && ./cm selenoid configure --vnc --browsers "firefox;chrome;opera" --last-versions 5 --tmpfs 128 && ./cm selenoid start --port 4444 --args "-limit 5 -service-startup-timeout 90s -session-attempt-timeout 90s -session-delete-timeout 90s -timeout 120s"
```

**Comment by KathiresanRamkumar95** [comment]
Okay!
After all the successful run still, I get "404 page not found" exception in my setup?
![image](https://user-images.githubusercontent.com/26536248/42812681-15a799fe-89dc-11e8-9765-e69a66fc4c02.png)


@vania-pooh  @admizh

**Comment by KathiresanRamkumar95** [comment]
But the status shows me to like Firefox and opera only configured with Not showing any chrome browsers also? 
@vania-pooh 
@admizh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 you have no Docker installed or CM tool does not see it. This is why you get `latest` as versions. Need to make sure that Docker is installed.

**Comment by KathiresanRamkumar95** [comment]
Oh God!
I have installed docker already. And I am running this using docker command to start selenoid. 
Please consider this also.

**Comment by KathiresanRamkumar95** [comment]
When I tried to run via binaries its gives like below... 
./cm selenoid start --vnc
![image](https://user-images.githubusercontent.com/26536248/42818225-ec987ec2-89ed-11e8-94a1-6db0b6c1e530.png)

**Comment by KathiresanRamkumar95** [comment]
Also the installed docker status is like this.

![image](https://user-images.githubusercontent.com/26536248/42818292-19221106-89ee-11e8-8136-1155376e1c51.png)



@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 if you do `docker ps` - are you able to see a list of containers? Probably you need to run CM as root.

**Comment by KathiresanRamkumar95** [comment]
I can see this when I put docker ps command in my command line.

![image](https://user-images.githubusercontent.com/26536248/42818921-b937ef8e-89ef-11e8-9e21-22a3f91b6908.png)


@vania-pooh

**Comment by KathiresanRamkumar95** [comment]
And also why the Docker is not supported - Using binaries...  message displays. What is wrong with this?

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 try to run this:
```
$ sudo ./cm selenoid start --force --vnc --browsers "chrome"
```

**Comment by KathiresanRamkumar95** [comment]
Thanks!
If I attach a file during run the selenoid chrome with docker.How do I attach my host machine file to the browser ?
@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 you have to use volumes feature described here: https://aerokube.com/selenoid/latest/#_other_optional_fields

**Comment by KathiresanRamkumar95** [comment]
Okay Thanks.
How do apply the Hub and Node concept like selenium, on selenoid?
@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 Selenoid does not use Selenium Grid architecture because it is not efficient on large scale.

**Comment by TollyAn** [comment]
@vania-pooh, can you help me?
I can't solve the same problem. We use docker behind proxy. 
After set http_proxy environment variable (file ~./docker/config.json) container not started with error: 407 Proxy Authentication Required.
![image](https://user-images.githubusercontent.com/32800738/64947057-e0c40d80-d87c-11e9-89a8-9d32a53eedd8.png)

**Comment by vania-pooh** [comment]
@TollyAn try to add username and password to proxy URL notation:
```
export http_proxy="https://username:password@192.168.33.10:3128/"
```

**Comment by TollyAn** [comment]
then another error:

![image](https://user-images.githubusercontent.com/32800738/64955578-4ae6ad80-d891-11e9-8bb4-ed58ec39c15a.png)

and java RemoteWebDriver return error:  
```
Exception in thread "main" org.openqa.selenium.WebDriverException: Unable to parse remote response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2018 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>

```

**Comment by vania-pooh** [comment]
@TollyAn I think this is because of incorrect Squid settings or incorrect password.

**Comment by TollyAn** [comment]
accordint to the proxy log, docker host try to access via proxy to docker container adress - http://192.168.0.3:4444/session 
Maybe docker network setting is incorrect? Everything settings as default 
 "Gateway": "192.168.0.1",  "IPAddress": "192.168.0.2",

**Comment by vania-pooh** [comment]
@TollyAn if you wish your browsers to go through proxy - then you have to set proxy settings in capabilities as follows: https://github.com/aerokube/selenoid-container-tests/blob/master/src/test/java/com/aerokube/selenoid/TestProxy.java

**Comment by TollyAn** [comment]
@vania-pooh it means browsers can't use docker settings and use only capabilities, isn't it?

**Comment by vania-pooh** [comment]
@TollyAn I think not all browsers are considering HTTP_PROXY variable. Recommended way is using capabilities.

**Comment by TollyAn** [comment]
@vania-pooh  ok. Thank U!
