### ISSUE TITLE
Having issues in starting Firefox browser with Selenoid

### ISSUE THREAD

**Issue by asemkazi** [aerokube/selenoid#1390]
@vania-pooh I am trying to run my test on selenoid version 1.10.12 with firefox version 116 I am getting below error.

Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.remote.RemoteWebDriver (Unable to establish websocket connection to ....

When I am trying to run with Firefox browser version 115.0 it is working fine. But facing issue with browser version 116 and beyond.

below is my browser.json file

{

    "chrome": {
      "default": "latest",
      "versions": {
          "120.0": {
            "image": "selenoid/chrome:120.0",
            "port": "4444",
            "path": "/",
            "mem" : "2G",
            "volumes": ["/data/dev/devtools/selenoid/data:/data:rw"],
            "tmpfs": {
                "/tmp": "size=1028m"
            }
          }
        }
      },

    "firefox": {
      "default": "latest",
      "versions": {
          "116.0": {
            "image": "selenoid/firefox:116.0",
            "port": "4444",
            "path": "/wd/hub",
            "mem" : "2G",
            "volumes": ["/data/dev/devtools/selenoid/data:/data:rw"],
            "tmpfs": {
                "/tmp": "size=1028m"
            }
          }
        }
      },

    "MicrosoftEdge": {
      "default": "latest",
      "versions": {
          "120.0": {
            "image": "browsers/edge:120.0",
            "port": "4444",
            "path": "/",
            "mem" : "2G",
            "volumes": ["/data/dev/devtools/selenoid/data:/data:rw"],
            "tmpfs": {
                "/tmp": "size=1028m"
            }
          }
        }
      }
}

**Comment by vania-pooh** [comment]
@asemkazi what is your Selenium client version?

**Comment by asemkazi** [comment]
@vania-pooh selenium 4.1.4

**Comment by asemkazi** [comment]
@vania-pooh any updates?
