### ISSUE TITLE
Partial success with nginx as SSL terminating proxy in front of selenoid.

### ISSUE THREAD

**Issue by plutocrat** [aerokube/selenoid#1402]
Our environment requires that we put all traffic over SSL, so we need to put an SSL proxy in front of selenoid. 
Selenoid is installed on the server using the cf binary. I can see:
docker proxy listening on 0.0.0.0:4444
selenoid-ui listening on       *:8080 
nginx is listening on port 8443. 

If we use the IP address and port 8080 to access selenoid-ui then everything works fine. 

Once we block that port at the firewall and use https://domain.com:8443 to access the ui, the initial pages are OK. However when we create a new session, VNC tries to connect, and then fails with
```
Initialize...
Connecting to wss://domain.com:8443/ws/logs/ca36d535c973eb8478d1200e4a62e0e6...
Disconnected 
```
in the right hand pane. In nginx logs we can see:

```
1.2.3.4 - - [08/Feb/2024:04:46:00 +0000] "GET /static/js/2.4a078c2e.chunk.js HTTP/2.0" 200 1660312 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:04:46:01 +0000] "GET /status HTTP/2.0" 401 17 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:04:46:01 +0000] "GET /manifest.json HTTP/2.0" 401 17 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:04:46:01 +0000] "GET /events HTTP/2.0" 401 17 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:04:46:01 +0000] "GET /status HTTP/2.0" 200 1464 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:05:54:14 +0000] "POST /wd/hub/session HTTP/2.0" 401 17 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:05:54:15 +0000] "POST /wd/hub/session HTTP/2.0" 200 903 "https://domain.com:8443/" "Mozilla"
1.2.3.4 - - [08/Feb/2024:05:54:18 +0000] "GET /ws/logs/b28a909639c2c6e7f0810e2830609919 HTTP/1.1" 403 10 "-" "Mozilla"
1.2.3.4 - - [08/Feb/2024:05:54:19 +0000] "GET /ws/vnc/b28a909639c2c6e7f0810e2830609919 HTTP/1.1" 403 10 "-" "Mozilla"
```
I've searched for previous nginx issues and have found those mentioning the upgrade connection items to be added to the config. However those don't seem to solve the problem. The relevant stanza in nginx is currently:

```
# at the top
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    
# later on
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version  1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```
Do I need to specify to selenoid its full domain.com name somehow? 
Do I need a separate stanza for /ws/vnc/ telling it to connect differently, perhaps to port 4444? (have tried this, but not exhaustively). Any suggestions to get full functionality behind a proxy? Would also consider switching to traefik, caddy or any other proxy that has a working config

**Comment by vania-pooh** [comment]
@plutocrat you should configure this for port `4444` and not port `8080`. Selenoid UI connects to Selenoid via web-sockets, so connection upgrade should be configure when accessing Selenoid.

**Comment by plutocrat** [comment]
OK, well I need to see the UI too, so I did previously try something like this:

```
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version  1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /ws/ {
            proxy_pass http://127.0.0.1:4444;
            proxy_http_version  1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```
But that doesn't seem to work. 
I have also tried removing the X-Forwarded-Proto headers, as initial connection is SSL and subsequent connections over localhost are not. Again no success.

**Comment by vania-pooh** [comment]
@plutocrat e.g. this is how we reverse proxy devtools web-socket API:

```
  location ~ ^/devtools/ {
    proxy_pass http://<your-upstream-host-or-name>;
    proxy_http_version 1.1;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
```
Should do the same with `/vnc/` and `/logs/` for Selenoid.

**Comment by plutocrat** [comment]
After trying a million different things, this is what's working for me currently. I can connect to port 8443, use the selenoid-ui interface, and its connecting to selenoid and VNC correctly. 

I think what actually did it in the end was using _proxy_set_header Host $http_host;_  instead of _proxy_set_header Host $host;_ but I was making so many edits I lost track!

`upstream selenoid-ui {
    server 127.0.0.1:8080;
}


server {

# general config, ssl, ports, logs, root, indexes, removed.

# Relevent config 

    location / {
        proxy_pass http://selenoid-ui;

        proxy_http_version 1.1;
        proxy_pass_header X-XSRF-TOKEN;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        chunked_transfer_encoding off;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering off;
        proxy_cache off;

        proxy_connect_timeout 600;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
    }

     location /ws {
        proxy_pass http://selenoid-ui;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
     }

}`
