### ISSUE TITLE
Not able to run Oracle Forms

### ISSUE THREAD

**Issue by MSL-GitHub** [aerokube/selenoid#1404]
I'm trying to automate Oracle EBS, The EBS contains Java Forms. Is there any way to brig that up using Selenoid
![maxresdefault](https://github.com/aerokube/selenoid/assets/158020320/6e9b5a62-041c-4f77-a013-bba503fa6974)

**Comment by vania-pooh** [comment]
@MSL-GitHub Selenoid mainly automates browsers. Is what you are showing able to start in a browser? This seems to be a desktop GUI application.

**Comment by MSL-GitHub** [comment]
@vania-pooh   No, It's not a desktop app it's a Java Webform. Please refer the below video

https://github.com/aerokube/selenoid/assets/158020320/ec50c5fb-a424-4e90-a7f8-65dee8957fc7

**Comment by vania-pooh** [comment]
@MSL-GitHub just check with developer toolbar whether you are able to access DOM tree (i.e. inspect HTML elements) on these forms. If this works, then Selenium \ Selenoid will work.
