### ISSUE TITLE
Add se:cdpVersion to returned capabilities

### ISSUE THREAD

**Issue by berkeroguz** [aerokube/selenoid#1405]
Hi everyone, I've an issue.

When i start to my test, I am facing below problem.

```
" Step failed
org.openqa.selenium.WebDriverException: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=120.0.6099.129)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.3.1', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [7bbef36da4e72d49f16fee69cb7e1341, get {url=https://opqa.etasimacilik.com/uye-girisi}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.129, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:34673}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:4444/devtool..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7bbef36da4e72d49f16fee69cb7e1341
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```
	And Log on Chrome Container:
	
	2024-02-19 16:28:40 Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2024-02-19 16:28:40 ChromeDriver was started successfully.
2024-02-19 16:28:43 X connection to :99 broken (explicit kill or server shutdown).
	
	
	Versions:
	ChromeDriver : 120
	Image: 120 
	Selenium Version: 4.15.0 , (and i tried 4.16.1 and 4.17.0 )
	Jdk : 17.0
	
	Actually, this problem has started after updated my mac :/
	By the way, same project works correctly on remote server which is windows10.
	How can i handle this? I tried upgrade or downgrade chrome version and also start selenoid with using cm file. (Normally I am using docker file.)

**Comment by vania-pooh** [comment]
@berkeroguz what is your Selenoid version?

**Comment by vania-pooh** [comment]
We may need to add `se:cdpVersion` support.

**Comment by berkeroguz** [comment]
Hi again, sorry for my late return.  
Selenoid version : latest. 
I don't use a particular version.

**Comment by aplanche** [comment]
I experience exact the same issue. Is there a workaround known for now?

**Comment by berkeroguz** [comment]
I couldn't find solution still. But for now, I use on windows. There is not problem on windows.  There is problem only on mac which is arm64 ( like M1 )

**Comment by vania-pooh** [comment]
@berkeroguz Chrome has no release for Linux ARM64 and will not work on Mac M1.

**Comment by vania-pooh** [comment]
@aplanche: not sure. If you provide some example source code to reproduce this - we could check.

**Comment by omez-702** [comment]
I have the same problem. use remoteDriver, selenium 4.21, `aerokube/selenoid-ui:latest `
There is no se:cdpVersion  in returned capabilities. I've tried to add it as capabilities to selenoid options throw driver, but it didn't help: 
```
selenoid_options['se:cdp'] = True
selenoid_options['se:cdpVersion'] = 125.0 # I use chrome 125
chrome_options.set_capability('selenoid:options', selenoid_options)
```
