### ISSUE TITLE
Selenoid in Restart mode

### ISSUE THREAD

**Issue by Lucifar2** [aerokube/selenoid#1406]
Hi, the selenoid docker contianer on my windows machine always remains in restart mode and doesn't work. Please check the "docker inspect selenoid" : 

[
    {
        "Id": "abfc5ebb268d4528896d09f9246babaac0f389f6f5dc23197d4e234ec4000c07",
        "Created": "2024-02-20T21:21:19.44938781Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-listen",
            ":4444",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-timeout",
            "500s",
            "-limit",
            "10",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-video-recorder-image",
            "selenoid/video-recorder:latest-release",
            "-log-output-dir",
            "/opt/selenoid/logs/",
            "-container-network",
            "selenoid"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2024-02-20T21:30:08.107502572Z",
            "FinishedAt": "2024-02-20T21:30:08.438576032Z"
            
 @vania-pooh Could you please help here. 
 P.S. I do not have docker desktop on my windows machine as its not a requirements from my organization and I just have Rancher Desktop.

**Comment by Lucifar2** [comment]
I have already reset docker mentioned here : https://github.com/aerokube/selenoid/issues/517#issuecomment-409991761 but still the same issue.

**Comment by vania-pooh** [comment]
@Lucifar2 we never tried with Rancher Desktop. But a desktop distribution is not a requirement for Selenoid. Any Docker distribution including free Docker for Linux will work. But anyway take a look at Selenoid container logs first:

```
$ docker logs selenoid # or similar Rancher command
```

**Comment by Lucifar2** [comment]
@vania-pooh Here are the logs : 
C:\WINDOWS\system32>docker logs selenoid
2024/02/21 08:24:15 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:15 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:16 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:16 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:16 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:16 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:17 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:17 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:18 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:18 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:20 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:20 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:24 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:24 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:30 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:30 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
2024/02/21 08:24:43 [-] [INIT] [Loading configuration files...]
2024/02/21 08:24:43 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]

**Comment by Lucifar2** [comment]
@vania-pooh Yes you are right. So it was working fine always until yesterday with desktop desktop. 
I deleted the desktop desktop which also deleted my existing containers and images. 
I installed rancher desktop and now trying to setup selenoid with it and facing this issue.

**Comment by Lucifar2** [comment]
![image](https://github.com/aerokube/selenoid/assets/22960342/91239a28-a901-446a-838b-9ee97b6eacc9)
Thats the error I see when I execute the selenoid commands.

**Comment by Lucifar2** [comment]
![image](https://github.com/aerokube/selenoid/assets/22960342/56f623db-bd5f-4a49-bcbc-34a615e80a3f)
Always restarting :(

**Comment by vania-pooh** [comment]
@Lucifar2 for some reason `browsers.json` from `c:\Users\<user>\.aerokube\selenoid\browsers.json` is not mounted to Selenoid container. Make sure with `docker inspect selenoid` that paths are correct in `Binds` section.

**Comment by Lucifar2** [comment]
@vania-pooh Here is the bind section below for me currently : 
```

"HostConfig": {
            "Binds": [
                "//c/users/saad.baig/.aerokube/selenoid/c/Users/Saad.Baig/.aerokube/selenoid:/etc/selenoid:ro,Z",
                "//c/users/saad.baig/.aerokube/selenoid/video/c/Users/Saad.Baig/.aerokube/selenoid/video:/opt/selenoid/video:Z",
                "//c/users/saad.baig/.aerokube/selenoid/logs/c/Users/Saad.Baig/.aerokube/selenoid/logs:/opt/selenoid/logs:Z",
                "//var/run/docker.sock:/var/run/docker.sock"
```

**Comment by Lucifar2** [comment]
Ohh yes it seems to be wrong. Do you know how can I fix the bind section. Any command will help. I am pretty new to it :) 
@vania-pooh

**Comment by Lucifar2** [comment]
Okay I removed the container and setup selenoid again. Its still in the restart mode and now I see te binds section as : 

```
"Binds": [
                "/c/Users/Saad.Baig/.aerokube/selenoid:/etc/selenoid:ro,Z",
                "/c/Users/Saad.Baig/.aerokube/selenoid/video:/opt/selenoid/video:Z",
                "/c/Users/Saad.Baig/.aerokube/selenoid/logs:/opt/selenoid/logs:Z",
                "//var/run/docker.sock:/var/run/docker.sock"
```

**Comment by vania-pooh** [comment]
@Lucifar2 seems to be correct if your Docker distribution supports Cygwin-style notation for Windows paths, e.g. `/c/Users` instead of `c:\Users\`.

**Comment by Lucifar2** [comment]
Hmmm not sure if it is. https://github.com/rancher-sandbox/rancher-desktop/issues/981

**Comment by Lucifar2** [comment]
I fixed it. Closing issue.

**Comment by VladSavrasov** [comment]
How did you fix it?

**Comment by Lucifar2** [comment]
@VladSavrasov Are you using Rancher Desktop as well ?

**Comment by VladSavrasov** [comment]
@Lucifar2  no, just trying run it with github.actions, a got windows 10 and starting it in yaml file

**Comment by Lucifar2** [comment]
I see. I havent tried it with githum actions before
