### ISSUE TITLE
Unable to run selenoid using docker under Rancher Desktop (windows)

### ISSUE THREAD

**Issue by StanislavKharchenko** [aerokube/selenoid#1409]
We're going to replace Docker Desktop for Windows with Rancher Desktop as last one is tool with open source licence
I've loaded to same images (latest versions): aerokube/selenoid, selenoid/chrome etc and cm.exe tool as helper to run process under Windows.
As selenoid downloaded  - config located at C:\users\...\.aerokube\selenoid\browser.json.
During run process, cm.exe shows that selenoid started.
However, docker logs demonstrate, that selenoid can't access browser.json since it not found

```
2024/03/01 14:27:11 [-] [INIT] [Loading configuration files...]
2024/03/01 14:27:11 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
```

I've inspected image, and saw that it mounted to C:\users\...\.aerokube\selenoid
```
            {
                "Type": "bind",
                "Source": "/c/Users/.../.aerokube/selenoid",
                "Destination": "/etc/selenoid",
                "Mode": "ro,Z",
                "RW": false,
                "Propagation": "rprivate"
            }
```

I also can't connect to container shell to observe it since it is always in restarting mode (trying to success start with existing config).

If stop Rancher, and start Docker desktop - everything will ok.

May you please assist what can be wrong here?

Thanks in advance

**Comment by vania-pooh** [comment]
@StanislavKharchenko we never tested Selenoid with Rancher, so no idea.
