### ISSUE TITLE
Bug: Selenoid/chrome 122.0 - downloaded files keep .crdownload suffix

### ISSUE THREAD

**Issue by th4m** [aerokube/selenoid#1410]
Containers for the latest chrome image (122.0) seem to not be able to complete downloads properly. The suffix .crdownload remains, but the file seems to be complete when copying it to host machine and removing the suffix.

If it's any help, we're using the bonigarcia/webdrivermanager for a Selenium project in Java Spring, which uses the latest image per default. Our tests fail on latest, but go green on 121.0.

**Comment by vania-pooh** [comment]
@th4m then probably this is a bug in Chrome itself or respective Chromedriver. In our images we are using official versions of both provided by Google.

**Comment by th4m** [comment]
@vania-pooh thanks, I've reported it to them now: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4737
