### ISSUE TITLE
Support Docker API 1.45

### ISSUE THREAD

**Issue by scaddenp** [aerokube/selenoid#1420]
Running selenoid/latest in portainer. Tests fail with this message:
Message: create container: Error response from daemon: {"message":"client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}

Docker API version on portainer is 1.45, Docker Compose version is v2.25.0

I dont get what that message is telling me.

**Comment by scaddenp** [comment]
Selenoid has been working fine for ages. I believe the issue may have started with a Portainer upgrade to CE 2.19.4

**Comment by nhanvolac** [comment]
Same issue with me, after upgrading the Docker Engine to v26.1.0 (API version:     1.45) and running selenoid:1.11.2 -> can not create the container. 

 {"message":"client version 1.12 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}

**Comment by scaddenp** [comment]
I notice a commit 3 months ago (Jan 25) meant address https://github.com/aerokube/selenoid/issues/1397 about the docker version. I am pulling /latest in the compose, but I am wondering if this has that fix.

**Comment by scaddenp** [comment]
Looking at the startup log, I see: 
"Did not manage to determine your Docker API version - using default version: 1.41"
@nhanvolac - do you see the same message?

**Comment by scaddenp** [comment]
Changed compose to aerokube/selenoid:1.11.2 and get message:
Did not manage to determine your Docker API version - using default version: 1.44

But now I get no longer get the minimum API version error message. It now cant find the browser image which is a more reasonable message, as in processing off updating browsers

**Comment by scaddenp** [comment]
Further. I updated Compose to specify the 1.11.2 image. And manually pushed a browser.json with updated chrome version, then downloaded the selenoid:chrome.123 version onto portainer. A run no longer produces that error message, and the chrome container is successfully started.  Now getting message: "Could not instantiate class org.openqa.selenium.chrome.ChromeDriver" which might be config at my end or something missing with config (I cant execute CM).

**Comment by alexander-tolstopyatov** [comment]
Same issue, I manually added environment variable DOCKER_API_VERSION with value "1.45" and error is gone. Looks like variable wasn't set somehow

**Comment by 21071988** [comment]
> Same issue, I manually added environment variable DOCKER_API_VERSION with value "1.45" and error is gone. Looks like variable wasn't set somehow

could you help me out? where do you specify it? i'm really dump on docker

**Comment by scaddenp** [comment]
Critical to this making you sure you are using the 1.11.2 or better selenoid version in your dockfile or compose.

**Comment by vania-pooh** [comment]
This was released a lot of time as Selenoid 1.11.3.
