### ISSUE TITLE
Pass output of python script to selenoid-ui view logs

### ISSUE THREAD

**Issue by dxwil** [aerokube/selenoid#1429]
Hi,
I am running a python script on the host and I would like to pass the output from that script into the logs shown in selenoid-ui, how can I achieve that?

**Comment by vania-pooh** [comment]
@dxwil not possible, logs are generated by respective webdriver binary.

**Comment by dxwil** [comment]
It is possible, I made my python program find the newly created docker container and then send all the logs to that docker container's logs
