### ISSUE TITLE
Add Chrome Devtools Protocol support for browsers/edge

### ISSUE THREAD

**Issue by Lucifar2** [aerokube/selenoid#1430]
@vania-pooh  Microsoft Edge [now also supports](https://learn.microsoft.com/en-us/microsoft-edge/devtools-protocol-chromium/) the Chrome DevTools Protocol. Could you add support for it in the `browsers/edge` images [like you have](https://github.com/aerokube/images/tree/ee8c9246e7249d8d216638c00d415e75851029fd/static/chrome/devtools) in the `selenoid/chrome` images?

**Comment by Lucifar2** [comment]
@vania-pooh Sorry for diverting your attention here on this again but its pretty high priority and we would be nice if we can get your feedback on this. Thanks :)

**Comment by vania-pooh** [comment]
@Lucifar2 this is open-source, so PRs are welcome.

**Comment by Lucifar2** [comment]
@vania-pooh Sure thanks but possible that it can be done by you as it can take us some time to get familiriaze with GO.
