### ISSUE TITLE
Question: Integrating a custom framework 

### ISSUE THREAD

**Issue by offdesk** [aerokube/selenoid#1436]
I run a keyword based automation framework that uses selenium. The framework executable runs json scripts that translate keywords into selenium commands. The framework is run as an executable. I would like to add the framework to my docker images. Two questions: 1)  can Selenoid launch my executable when Selenoid runs, and 2) is there a way my framework can communicate with Selenoid to inform it when a test starts and stops (e.g. API) so the Selenoid UI can display running tests? Programmatically setting capabilities as well?

**Comment by vania-pooh** [comment]
@offdesk Selenoid is just an API to launch browsers. It is not even aware you are launching tests. So everything outside of manipulating browsers is out of Selenoid scope. What you are describing is test automation report \ CI responsibility.
