### ISSUE TITLE
ERROR_PROCESSING_RESPONSE

### ISSUE THREAD

**Issue by AlexanderRyb82** [aerokube/selenoid#1437]
Good day! Please help with the error (Docker). An error appears when starting the session manually
2024/09/13 09:20:59 [-] [NEW_REQUEST_ACCEPTED] [unknown] []
2024/09/13 09:20:59 [372] [LOCATING_SERVICE] [chrome] [latest]
2024/09/13 09:20:59 [372] [USING_DOCKER] [chrome] [latest]
2024/09/13 09:20:59 [372] [CREATING_CONTAINER] [selenoid/chrome]
2024/09/13 09:20:59 [372] [STARTING_CONTAINER] [selenoid/chrome] [1e9a688744b18321847cb47dae0acc6928308d1a6c8c7785fd1a4175a834eda4]
2024/09/13 09:20:59 [372] [CONTAINER_STARTED] [selenoid/chrome] [1e9a688744b18321847cb47dae0acc6928308d1a6c8c7785fd1a4175a834eda4] [0.19s]
2024/09/13 09:20:59 [372] [SERVICE_STARTED] [selenoid/chrome] [1e9a688744b18321847cb47dae0acc6928308d1a6c8c7785fd1a4175a834eda4] [0.00s]
2024/09/13 09:20:59 [372] [PROXY_TO] [1e9a688744b18321847cb47dae0acc6928308d1a6c8c7785fd1a4175a834eda4] [http://172.17.0.4:4444]
2024/09/13 09:20:59 [372] [SESSION_ATTEMPTED] [http://172.17.0.4:4444] [1]
2024/09/13 09:20:59 [372] [ERROR_PROCESSING_RESPONSE] [parse body response: invalid character '<' looking for beginning of value]
2024/09/13 09:20:59 [372] [REMOVING_CONTAINER] [1e9a688744b18321847cb47dae0acc6928308d1a6c8c7785fd1a4175a834eda4]
2024/09/13 09:21:00 [372] [CONTAINER_REMOVED] [1e9a688744b18321847cb47dae0acc6928308d1a6c8c7785fd1a4175a834eda4]

There is an ajax error 403 error in the UI on the button

**Comment by vania-pooh** [comment]
@AlexanderRyb82 invalid image.
