### ISSUE TITLE
my python client cant establish connection via /wd/hub

### ISSUE THREAD

**Issue by rmros** [aerokube/selenoid#144]
hi

i run cm and selenoid-ui binaries with this commands:
cm selenoid start --vnc
selenoid-ui --listen localhost:8085

both of them are running and have not problem

my programming language is python
but when in using i have problems :

************************************************************************************************
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
					 
					 
driver = webdriver.Remote(
   command_executor="http://localhost:4444/wd/hub",
   desired_capabilities={
            "browserName": "firefox",
        })
print (driver.session_id)
  
try:
    driver.implicitly_wait(30)
    driver.get("http://www.python.org")
    assert "Python" in driver.title
    elem = driver.find_element_by_name("q")
    elem.send_keys("documentation")
    elem.send_keys(Keys.RETURN)
    assert "No results found." not in driver.page_source
finally:
    driver.quit()
*********************************************************

what is my problem?

have some example using code with python lang to give me?

thanks

**Comment by vania-pooh** [comment]
@rmros Selenoid is fully compatible with Selenium so your code seems to be correct. However when working with latest versions of Firefox you may encounter issues related to new Geckodriver used to drive the browser. This driver is still missing some features (take a look at [implementation status](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status)). By default `cm` is downloading 2 last versions of Firefox (currently 53 and 54) and these versions are using Geckodriver. You could try to download and use older versions with `--last-versions` flag:
```
$ ./cm selenoid start --last-versions 10
```
Then you could e.g. try with Firefox 46.0 capabilities:
```
browserName = firefox
version = 46.0
```
If this still does not work please provide more details about your error.

**Comment by rmros** [comment]
@vania-pooh 
its runned cm : 

![cm](https://user-images.githubusercontent.com/21344663/27825732-c85cae90-60c5-11e7-9003-29f65db8d753.jpg)

its runned ui : 


![ui](https://user-images.githubusercontent.com/21344663/27825768-f2d5de30-60c5-11e7-95ad-09b49a03a759.jpg)


its client.py : 


[client.txt](https://github.com/aerokube/selenoid/files/1121680/client.txt)


and its Error :(  : 

![error](https://user-images.githubusercontent.com/21344663/27825853-32b580e6-60c6-11e7-9f65-68854cb96de2.jpg)

**Comment by rmros** [comment]
i also modified client and append
browserName = firefox
version = 46.0

**Comment by vania-pooh** [comment]
@rmros ok, that's the Windows case. In that case only the latest Geckodriver is downloaded. Could you please check that when you start your tests a new process called geckodriver.exe starts?

**Comment by vania-pooh** [comment]
@rmros any more updates?

**Comment by rmros** [comment]
@vania-pooh  thanks for support , this issue solved

**Comment by vania-pooh** [comment]
Ok, then closing it.
