### ISSUE TITLE
Test failing possibly due to disabled hardware acceleration

### ISSUE THREAD

**Issue by diasdm** [aerokube/selenoid#1441]
Hi,

I have a test that fails when it is run with a containerized Chrome but passes when run on my local Chrome installation.
This test opens a webpage which contains a babylon.js canvas.

I can see that the test runs very slowly and there is a series of repeated warnings in the console:
`[.WebGL-0xeb803fcc700] GL_INVALID_OPERATION: Insufficient buffer size.`

I'm unsure what the issue is, but suspect it is related with hardware acceleration (I could confirm it is disabled on the containerized browser but not on the local one).

I have two questions, does this sound plausible? And, is there a way to enable hardware acceleration on a containerized browser?

Thank you

**Comment by aandryashin** [comment]
Hardware acceleration is not supported in docker containers. Sound is also
not supported.

ср, 6 нояб. 2024 г., 17:21 David Dias ***@***.***>:

**Comment by diasdm** [comment]
Alright, so for applications which require it would be better to look into other tools?
