### ISSUE TITLE
Telegram problem

### ISSUE THREAD

**Issue by rmros** [aerokube/selenoid#145]
i cant join to your channel because :

![1](https://user-images.githubusercontent.com/21344663/27827334-010a654c-60cc-11e7-9613-175d1f263f61.jpg)
![2](https://user-images.githubusercontent.com/21344663/27827335-01bb3bc4-60cc-11e7-83bc-c842fc666ea4.jpg)
![3](https://user-images.githubusercontent.com/21344663/27827337-037daffa-60cc-11e7-87bf-9d5262befec2.jpg)

**Comment by vania-pooh** [comment]
@rmros please add me to Telegram directly - @vaniaPooh and I will add you to channel manually.
