### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by SergeyPirogov** [aerokube/selenoid#163]
Hello, is there any technical limitations to use Selenoid with docker for windows?

**Comment by vania-pooh** [comment]
@SergeyPirogov not sure about native Docker on Windows Server (able to launch Windows images and binaries) but according to our user's experience it works well with Docker using Linux virtual machine inside (like under MacOS).

**Comment by vania-pooh** [comment]
@SergeyPirogov btw, found that CM tool has a bug preventing Selenoid to start because of wrong mount point (https://github.com/aerokube/cm/issues/55).

**Comment by temagi** [comment]
@vania-pooh Hello. As I know, Linux image include xvfb for run virtual desktop and every instance of running browser is independent. But Windows doesn't have X window system. So, is there any reason to use Selenoid with Windows, if there is no ability to run few browser instances independently?

**Comment by vania-pooh** [comment]
@temagi 
1) First of all you can just install Boot2Docker on Windows and have exactly the same features. 
2) Second even without Docker Selenoid is tiny and lightweight and consumes dozens of megabytes of RAM instead of gigabytes with standard Selenium server under load. Small 7 Mb binary is better than 100 Mb Java + 30 Mb Selenium server.

Also take a look at this article: https://medium.com/@aandryashin/selenium-on-windows-revisited-1ab8d51ccc06

**Comment by vania-pooh** [comment]
So far the mount path bug is fixes in CM tool and there is no more activity closing this issue.

**Comment by KathiresanRamkumar95** [comment]
@vania-pooh 

How can I get selenoid/vnc:chrome_67.0 with windows container ?

OS: Windows 10 Pro
Selenoid for windows: selenoid_windows_amd64.exe v1.7.1
chrome Version: 67.0

Thanks in advance !

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 all our images are based on Linux. So in order to use them on Windows - just switch Docker to Linux mode.

**Comment by KathiresanRamkumar95** [comment]
But I want to run chrome in windows based.

How do I get chrome in windows based container?

@vania-pooh

**Comment by aandryashin** [comment]
Unfortunately, Windows images does not support graphical applications
running within containers.

2018-07-31 8:29 GMT+03:00 KathiresanRamkumar95 <notifications@github.com>:

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 this is just not supported and we have no plans to do this.
