### ISSUE TITLE
Environment variables are not passed to driver process on Windows

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#166]
Need to check that environment variables from `browsers.json` get correctly passed to process.

**Comment by AnisimovAleksandr** [comment]
When I try to run Selenoid on win10 64x, I get this:
Failed to start: failed to create container: Error response from daemon: invalid environment variable: =::=::\
Does this apply to this bug?

**Comment by vania-pooh** [comment]
@AnisimovAleksandr no, this is https://github.com/aerokube/cm/issues/81. This one is about passing environment vars to driver process.

**Comment by vania-pooh** [comment]
Tested again using a binary printing environment variables. Works like a charm.
