### ISSUE TITLE
Extension with proxy in Chrome

### ISSUE THREAD

**Issue by Carniflex** [aerokube/selenoid#187]
1. Contaires work in Kubernets.

I have a container with proxy server. I have container with selenoid.
 
My tests create driver with next settings:

 base64_encode();

                 let chromeOptions = {
                 'extensions': [ext]
                 };
                 let chromeCapabilities = webdriver.Capabilities.chrome();
                 chromeCapabilities.set('chromeOptions', chromeOptions);

                 driver = new webdriver.Builder()
                 .usingServer(hub)
                 .withCapabilities(chromeCapabilities)
                 .build();*/

Chrome extension is:

var config = {
    mode: "fixed_servers",
    rules: {
        singleProxy: {
            scheme: "http",
            host: "MY_PROXY",
            port: parseInt(MY_PORT)
        },
        bypassList: ["MY_URL"]
    }
};

chrome.proxy.settings.set({value: config, scope: "regular"}, function () {
});

function callbackFn(details) {
    return {
        authCredentials: {

            username: "test",
            password: "test"
        }
    };
}

chrome.webRequest.onAuthRequired.addListener(
    callbackFn,
    {urls: ["<all_urls>"]},
    ['blocking']
);

This extension handles BASIC HTTP AUTH in browser.

On my local machine without selenoid all work very well.

But when i try to use selenoid i get 'NO INTERNET CONNECTION' on screnshots

**Comment by vania-pooh** [comment]
@Carniflex how could we try to reproduce this? Please provide more detailed instructions about building your extension.

**Comment by Carniflex** [comment]
I've  already fixed it. Thank you for aswer

**Comment by vania-pooh** [comment]
So closing?
