### ISSUE TITLE
Feature request: Appium docker android

### ISSUE THREAD

**Issue by rosolko** [aerokube/selenoid#197]
Hi there,
Appium has interesting [project](https://github.com/appium/appium-docker-android) about android emulators running in docker.
What do you think is it possible to integrate into this project?
Thanks.

**Comment by vania-pooh** [comment]
This issue duplicates https://github.com/aerokube/selenoid-images/issues/10. We already know how to create images with Android emulator inside. The main problem - is that they are very big (4 Gb) and slow (new session starts in 30+ seconds) to be started for every session.

**Comment by rosolko** [comment]
@vania-pooh By the way if we use emulator on local machine it's also take 4Gb of space. And in this case only image will take a lot of space, container will take a small space. 
And usually simulator start only one time before all test, and for each test you just reset/reinstall application. 
Also you can specify some flags to speed-up boot time, for example this set of parameters dramatically improve boot time: `-no-boot-anim -no-skin -no-audio -no-window`
Thanks.

**Comment by vania-pooh** [comment]
@rosolko I am aware about all these flags. However Selenoid approach is to lauch new isolated container for each session. In case of emulators containers can be dramatically smaller if common parts like Android SDK and Appium sources are on the host machine and you mount it during container startup. Selenoid can do this using volumes functionality.
