### ISSUE TITLE
Selenoid must add the sesssion id in the browser logs.

### ISSUE THREAD

**Issue by ersuniljoshi** [aerokube/selenoid#199]
As per the telegram conversation I had with @vania-pooh ,

browsers logs doesnot even contain session ids, how elastic search will add that logic
it has only container Id in it
at this point of time I can only see session created, deleted messages for that particular session in browsers logs
If I need to tell you in a command way , that what I need to achieve is
grep -iHrn '<session_id>' <logfile_where_all_the_logs_are_coming>
I should get that everything happened inside that selenoid box from session started - > Commands Executed -> Session Deleted

Let me know if anything else  is required from my side.

**Comment by vania-pooh** [comment]
Need to think about it. One possible solution is to add to every container a small proxy binary that will output correct logs suitable for Logstash processing.

**Comment by vania-pooh** [comment]
Will try to add https://docs.docker.com/engine/admin/logging/log_tags/.

**Comment by vania-pooh** [comment]
After some discussion - the simplest approach here is to use log tags in case when `name` capability is set. So when you mark your test case by name - you will be able to get all the logs. Session ID becomes available after launching container - so this is impossible to use it as a tag.

**Comment by vania-pooh** [comment]
@ersuniljoshi now passing `name` capability as logging tag. Available in `aerokube/selenoid:latest`.
