### ISSUE TITLE
Selenoid UI VNC connection lost after upgrade to 1.4.0

### ISSUE THREAD

**Issue by SergeyPirogov** [aerokube/selenoid#206]
Hello, after upgrade selenoid UI to v 1.4.0, VNC session is lost.

To help you clearly understand the problem I have recorded screencast

https://youtu.be/DiBCDj1kA_4

**Comment by vania-pooh** [comment]
@SergeyPirogov could you try with `aerokube/selenoid-ui:latest`?

**Comment by SergeyPirogov** [comment]
The issue is gone. Tried to restart selenoid and selenoid-ui. After that, it became to work normally.

**Comment by vania-pooh** [comment]
Good, closing?
