### ISSUE TITLE
adding new host entries in spawned container

### ISSUE THREAD

**Issue by DicksengA** [aerokube/selenoid#207]
Is it possible to add host entries to the chrome instances so that it looks up an url that does not exist in the DNS?

**Comment by aandryashin** [comment]
We just implemented this feature but not yen released:

https://github.com/aerokube/selenoid/pull/204

you can try selenoid:latest image which contains implementation.

2017-09-05 17:05 GMT+03:00 DicksengA <notifications@github.com>:

**Comment by DicksengA** [comment]
@aandryashin Woah Thanks!!! I test it out tomorrow.

**Comment by vania-pooh** [comment]
@DicksengA see more details in https://github.com/aerokube/selenoid/issues/201.
