### ISSUE TITLE
Is there any support for video recording for windows known

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#209]
Is there any support for video recording for windows known when using selenoid? We evaluated a solution that drastically uses cpu, which is a no go, but could find anything yet. we used grid extras before with java. any suggestions would be great.

**Comment by vania-pooh** [comment]
@benzman81 we are not using this functionality, but for example you could try Python-based [vnc2flv](http://www.unixuser.org/~euske/python/vnc2flv/index.html). According to docs it is cross-platform. There is a similar StackOverflow [question](https://stackoverflow.com/questions/45364429/selenoid-recording-video-of-a-running-session/45662657#45662657).

**Comment by vania-pooh** [comment]
@benzman81 any more stuff to discuss here?

**Comment by benzman81** [comment]
sorry, forgot about that issue. Thanks for the link. We dismissed the idea of capturing video as most/all solutions eat a lot of cpu/ram.
