### ISSUE TITLE
Session timed out or not found

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#210]
Hi,

moving from "selenium grid + grid extras" to "ggr + selenoid" I get a lot of "Session timed out or not found" errors like these:

```
org.openqa.selenium.WebDriverException: Session timed out or not found (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'somehost', ip: 'someip', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-111-generic', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=true, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=true, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=-private, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:51781/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 7f0bb8bda8e4148aefb8ad67531403afc3b8576f-d361-4792-bee9-140df26d86d9
*** Element info: {Using=xpath, value=//someXPath}
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:437)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:513)
	at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:398)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:882)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at our code doing fluent wait
```

Do you have any idea? Can I increase the timeout some how to not run into it?

Regards,
Markus

**Comment by vania-pooh** [comment]
@benzman81 according to this documentation [section](http://aerokube.com/selenoid/latest/#_selenoid_cli_flags) you can adjust several timeout values:
* `-service-startup-timeout 30s` - Docker container or driver process startup timeout
* `-session-attempt-timeout 30s` - New session attempt timeout, i.e. `POST /wd/hub/session` HTTP request timeout.
* `-session-delete-timeout 10s` - Session removal HTTP request timeout
* `-timeout 60s` - Session idle timeout, i.e. time between separate HTTP requests to Selenium API which automatically causes session to be closed.

You can obtain the same documentation via `$ selenoid -help` command.

**Comment by benzman81** [comment]
sorry about this issue. I already set "-timeout xxx" but I didnt push to remote :-D

**Comment by Programmer-Admin** [comment]
Hello @vania-pooh, my docker-compose.yml file looks like this : 
`services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: hub
    networks:
      - selenoid-net
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-conf /etc/selenoid/browsers.json -container-network selenoid-net -limit 50 -timeout 5m30s"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - selenoid-net
    ports:
      - "8080:8080"
    command: "--selenoid-uri http://hub:4444"
networks:
  selenoid-net:
    external: true
    name: selenoid-net
`
And pom.xml has forkcount set to 25
`
<plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>3.1.2</version>
                            <configuration>
                                <rerunFailingTestsCount>1</rerunFailingTestsCount>
                                <forkCount>25</forkCount>
                                <reuseForks>true</reuseForks>
                                
                                <includes>
                                    <include>**/*cumber.java</include>
                                </includes>
                            </configuration>
                        </plugin>
`
But I see max 16 sessions are executing in parallel,don't know why. But,  If I remove `-timeout`, everything working fine, it's starting 25 sessions in parallel. Am I missing something?

**Comment by vania-pooh** [comment]
@Programmer-Admin you have to check Selenoid logs and your test code logs to get an idea of the number of browser sessions being started. Trying to check the same in Selenoid UI is not a guarantee of showing correct number, because in Selenoid UI everything is refreshed every 5 seconds and short test cases can be executed faster.
