### ISSUE TITLE
where is the right place to set enableVNC = true

### ISSUE THREAD

**Issue by getmonyinfo** [aerokube/selenoid#214]
Hey , I just follow the guide in http://aerokube.com/selenoid/latest/#_getting_started

it all work as expected , but i can't find the right place to set enableVNC = true.
i config ~/.aerokube/selenoid/browsers.json as following
```bash
    "chrome": {
        "default": "61.0",
        "versions": {
            "60.0": {
                "image": "selenoid/vnc:chrome_60.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                },
                "enableVNC":"true"
            },
            "61.0": {
                "image": "selenoid/vnc:chrome_61.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                },
                "enableVNC":"true"
            }
        }
    }
```
vnc not working

i start docker using `docker run --rm                                   \
    -v /var/run/docker.sock:/var/run/docker.sock    \
    -v ${HOME}:/root                                \
    -e OVERRIDE_HOME=${HOME}                        \
    -e enableVNC=true                               \
    aerokube/cm:latest-release selenoid start       \
    --vnc --tmpfs 128`
still no luck

**Comment by sskorol** [comment]
It should be set in `DesiredCapabilities` you're passing to `RemoteWebDriver` instance.

**Comment by getmonyinfo** [comment]
```python
capabilities = {
    "browserName": "chrome",
    "version": "61.0",
    'chromeOptions': {
        'args': ['--disable-webgl=true','--disable-3d-apis=true']
      },
    'enableVNC':"true"
}
driver = webdriver.Remote(
            command_executor='http://localhost:4444/wd/hub',
            desired_capabilities = capabilities)
```
it raise an exception 
selenium.common.exceptions.WebDriverException: Message: json: cannot unmarshal string into Go struct field Caps.enableVNC of type bool

**Comment by aandryashin** [comment]
It should be boolean value and not a string "true", like the following:

'enableVNC':True


2017-09-12 12:17 GMT+03:00 getmonyinfo <notifications@github.com>:

**Comment by getmonyinfo** [comment]
Yep, it works , thanks man !
