### ISSUE TITLE
how to run multiple container simultaneously

### ISSUE THREAD

**Issue by getmonyinfo** [aerokube/selenoid#215]
I just try how many container selenoid can run .
and i get a lot of errors
```python
selenium.common.exceptions.WebDriverException: Message: wait: http://172.17.0.27:4444/wd/hub does not respond in 30s
```
```python
selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded
```
i start 20 remote request simultaneously,  only 3 container start, all of the rest fails
i config selenoid like this
```bash
docker run -d  --name selenoid                     \
    -p 4444:4444                                    \
    -v /Users/a/.aerokube/selenoid:/etc/selenoid:ro               \
    -v /var/run/docker.sock:/var/run/docker.sock    \
    aerokube/selenoid:latest              \
     -limit 600                                      \
     -timeout 500s                          \
     -disable-queue                         \
     -mem 512m                              \
```

so , what's the correct method to run multiple container simultaneously

**Comment by vania-pooh** [comment]
Please first of all check that you have correct storage driver.
```
$ docker info | grep Storage
```
Having `devicemapper` here can be the reason. Also take a look at: http://aerokube.com/selenoid/latest/#_recommended_docker_settings

**Comment by getmonyinfo** [comment]
```bash
$ docker info | grep Storage
Storage Driver: aufs
```
i check the status of selenoid  when total count reach 13, new request are all in pending status and then fails

**Comment by vania-pooh** [comment]
Please remove `-mem` option. It can cause browsers to be killed by OOM killer when having insufficient memory.

**Comment by getmonyinfo** [comment]
after several tests i realize that it's **cpu threads count**.

i run test on two pcs which  all contain a 4 core 8 thread cpu (one is 2th generation i7-2670QM CPU @ 2.20GHz, the other one is 6th generation  i7-6700HQ CPU @ 2.60GHz). 
when total number of containers between 4-6, everything works fine, after that every new request will raise cpu up to 70-90%, and then may be start fails(the new webdriver can't start, or other webdriver lost response). the test code is simple
```python
driver.get('https://www.google.com/')
time.sleep(randint(8,20))
driver.get('http://www.amazon.com')
```
i also run other  images, `selenoid/firefox, selenoid/nvc:firefox, selenium/standalone-firefox`,and,  the final result is similar.

so, since i don't have much experience of docker, i have several questions, may be off the topic:
1. does docker cpu sensitive over other virtual approach like vmware, virtualbox. i can also run several virtual machine simultaneously  on the same computer,  may be even more
2. does your test have a better performance in production environment? 
3. if i want to run 500 test case simultaneously, what's the best approach?

**Comment by vania-pooh** [comment]
@getmonyinfo 
1) Docker is just an isolation technique. It has the same properties as any operating system process. If your disk is slow - it will be slow inside container. There is no difference.
2) I can state that using AUFS we can easily run 50 or even more tests in parallel on 32-core server.
3) To run hundreds of tests you need to install several Selenoid instances on multiple hosts and load balance them with [Ggr](http://github.com/aerokube/ggr/). It is impossible to run 500 containers with browsers on just one server - not enough memory and CPU cores.

**Comment by lbonifazi** [comment]
@vania-pooh Hello!
I'm getting the same error. In my case, what I trying to do is to run more than one instance of the same image (_selenoid/vnc_chrome 69.0_). I meant, to run tests simultaneously with selenoid with the same browser and version.

I'm working with a docker toolbox inside a virtual machine (_mvware workstation_) with windows. I've run a new selenoid container with following parameters:
```
docker run -d --name selenoid 
-p 4444:4444 
-v //var/run/docker.sock:/var/run/docker.sock
 -v /c/Users/a/.aerokube/selenoid/config/:/etc/selenoid/:ro 
-v /c/selenoid/video/:/opt/selenoid/video/ 
-e OVERRIDE_VIDEO_OUTPUT_DIR=/c/selenoid/video/ 
aerokube/selenoid:latest-release 
-limit 10
-session-attempt-timeout 3m
```
Docker storage:
```
$ docker info | grep Storage
Storage Driver: aufs
```
When I run my first test, it run perfectly. Then if I try to run another test, using the same browser and version, I received this error:
> selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded

My browser.json looks like:
```
{
    "chrome": {
        "default": "69.0",
        "versions": {
            "68.0": {
                "image": "selenoid/vnc_chrome:68.0",
                "port": "4444",
                "path": "/"
            },
            "69.0": {
                "image": "selenoid/vnc_chrome:69.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}
```

When one test is running, the selenoid status looks like:
`{"total":10,"used":1,"queued":0,"pending":0,"browsers":{"chrome":{"68.0":{},"69.0":{"unknown":{"count":1,"sessions":[{"id":"90fad5c5dc93df96ab41caa21d34d907","container":"81d303a3a5fa175f14f94da732654a1fb7e564f7bc23365c59ecb4196a7061a2","containerInfo":{"id":"81d303a3a5fa175f14f94da732654a1fb7e564f7bc23365c59ecb4196a7061a2","ip":"172.17.0.4"},"vnc":true,"screen":"1280x1024x24","caps":{"browserName":"chrome","deviceName":"","version":"69.0","browserVersion":"","platform":"ANY","platformName":"","screenResolution":"1280x1024x24","enableVNC":true,"enableVideo":true,"videoName":"selenoid1d033af1a25554bdd4be0bfc6a6019a8.mp4","videoScreenSize":"1280x1024","videoFrameRate":0,"logName":"","name":"","timeZone":"America/Tijuana","containerHostname":"","env":null,"applicationContainers":null,"hostsEntries":null,"dnsServers":null,"labels":null,"sessionTimeout":120,"selenoid:options":null}}]}}}}}`

Do you have any idea of what I missed?

**Comment by vania-pooh** [comment]
@getmonyinfo `-limit 10` means Selenoid will run up to 10 parallel browsers. They require 5-10 CPU cores to work. Did you provide such number of CPUs in VMWare?
