### ISSUE TITLE
Sometimes Browser stays open

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#216]
Hi,
using selenoid on Windows with grr (if that matters). Running out tests, sometimes the browser doesn't close on a windows node and selenoid last logs are: [NEW REQUEST].

For the example below, I looked at the machine at 10:00 o'clock and the last [NEW REQUEST] ist from 06:43.

We are starting selenoid like this:
`selenoid_windows_386.exe -conf browsers.json -disable-docker -enable-file-upload -timeout 120s -session-attempt-timeout 120s -session-delete-timeout 120s -limit 1 -retry-count 10`

Maybe driver.quit() wasnt called under some circumstance, but I would assume, that selenoid has to timeout in such a case. Any ideas?

![selenoid_console](https://user-images.githubusercontent.com/14224592/30473471-defee6f8-9a00-11e7-8cc7-58904996ff61.png)

**Comment by aandryashin** [comment]
Selenoid timeouts session only if no new http requests come to browser. Is
there something like implicit waits in your tests? Also, there is project:

https://github.com/kybu/headless-selenium-for-win

it uses native windows api to start and stop ie driver, it may be more
reliably than using go api. Try to configure selenoid like this:

{
  "internet explorer": {
    "default": "11",
    "versions": {
      "11": {
        "image": ["./headless_ie_selenium.exe"]
      }
    }
  }

It will start ie driver on virtual desktop, and will use windows jobs to
stop process subtree.

2017-09-15 11:34 GMT+03:00 Markus Krüger <notifications@github.com>:

**Comment by benzman81** [comment]
Well, this window was still in this state after about 3 hours (see last NEW REQUEST). So I assume no new calls have been made to selenoid. Is there any flag to have some more detailed logging?

headless-selenium-for-win: We tried headless-selenium-for-win but we couldnt watch the tests using vnc beacue of virtual desktops (at least we couldnt find an easy way).

**Comment by vania-pooh** [comment]
@benzman81 could you check for process ID of running IE and send us all log entries containing this ID. Selenoid is logging when the process is launched and then terminated.

**Comment by benzman81** [comment]
@vania-pooh currently all machines have been destroyed an recreated. So I have to wait for the issue again. I will to so when it occures next time.

**Comment by benzman81** [comment]
Had this issue again. I also noticed that the test hangs in that case. Only continues if I close the browser manually.
I could get the PID out of the taskmanager but they did not occur in the selenium console out. Can you point me how to get the pid in the console out?

**Comment by vania-pooh** [comment]
@benzman81 what I mean is that you should get the process ID from the task manager (if you have `cygwin` you can also type `ps -W | grep iexplore`) and then try to find all entries in selenoid log.

**Comment by benzman81** [comment]
Yes, thats what I did, but no entries with this process ID in the selenium console out.

**Comment by vania-pooh** [comment]
There should be at least an entry about started process.

**Comment by benzman81** [comment]
@vania-pooh yes, I could see those, but they did not have a number anywhere that matched the process Id. The next run I get this issue, I will post the log anyway with the PID, maybe you can find some other useful info.

**Comment by vania-pooh** [comment]
@benzman81 agree.

**Comment by benzman81** [comment]
and here it is. a test just hung again. hope the files help

**Comment by benzman81** [comment]
[tasklist1.txt](https://github.com/aerokube/selenoid/files/1307554/tasklist1.txt)
[selenoid1.txt](https://github.com/aerokube/selenoid/files/1307553/selenoid1.txt)

**Comment by vania-pooh** [comment]
@benzman81 ok, will take a look tomorrow.

**Comment by vania-pooh** [comment]
And here are the interesting log lines:
```
2017/09/15 15:34:19 [117] [PROCESS_STARTED] [2232] [556.6406ms]
2017/09/15 15:34:19 [117] [PROXYING_REQUESTS] [http://127.0.0.1:59454]
2017/09/15 15:34:19 [117] [SESSION_ATTEMPTED] [test] [http://127.0.0.1:59454] [1]
2017/09/15 15:34:26 [117] [SESSION_CREATED] [test] [a1be16b6-3f43-4d9d-a706-84da7641d8a1] [http://127.0.0.1:59454] [1] [6.3818359s]
2017/09/15 15:35:20 [SESSION_DELETED] [a1be16b6-3f43-4d9d-a706-84da7641d8a1]
...
2017/09/15 15:35:21 [117] [TERMINATING_PROCESS] [2232]
2017/09/15 15:35:21 [117] [TERMINATED_PROCESS] [2232]
```
But in your tasklist you can see that IEDriverServer.exe process `2232` still exists.
```
Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
IEDriverServer.exe            2232 Console                    1     14,024 K
iexplore.exe                  2012 Console                    1    264,592 K
```
So I think the issue is somewhere in process killing logic. We are [logging](https://github.com/aerokube/selenoid/blob/master/service/driver.go#L68-L73) when Golang fails to kill the process. So this even could be a Golang issue.

@aandryashin any more thoughts?

**Comment by benzman81** [comment]
Just to maybe have more data I attach two more files. But looks the same.
[selenoid2.txt](https://github.com/aerokube/selenoid/files/1308166/selenoid2.txt)
[tasklist2.txt](https://github.com/aerokube/selenoid/files/1308167/tasklist2.txt)

**Comment by vania-pooh** [comment]
In that case IEDriverServer process has ID 3504 with the following Selenoid log entries:
```
2017/09/16 07:56:47 [24] [LOCATING_SERVICE] [internet explorer-11]
2017/09/16 07:56:47 [24] [USING_DRIVER] [internet explorer-11]
2017/09/16 07:56:47 [24] [ALLOCATING_PORT]
2017/09/16 07:56:47 [24] [ALLOCATED_PORT] [51892]
2017/09/16 07:56:47 [24] [STARTING_PROCESS] [[C:\Users\IEUser\Downloads\IEDriverServer.exe --log-level=DEBUG --log-file=C:\Users\IEUser\Downloads\IEDriverServer.log --port=51892]]
2017/09/16 07:56:47 [24] [PROCESS_STARTED] [3504] [571.2891ms]
2017/09/16 07:56:47 [24] [PROXYING_REQUESTS] [http://127.0.0.1:51892]
2017/09/16 07:56:47 [24] [SESSION_ATTEMPTED] [test] [http://127.0.0.1:51892] [1]
2017/09/16 07:56:54 [24] [SESSION_CREATED] [test] [3f3c4f5e-3ea7-4a99-b541-3e67d648d0ea] [http://127.0.0.1:51892] [1] [7.3076172s]
```
I don't see any process termination log entries, but I think this is because the lines above are the last ones in the log, so they should be present. Aren't they?

**Comment by benzman81** [comment]
Yes, they are the last lines in the log and the browser is open. 

Maybe the issue is on our side in the tests. As I close the dialog that is open in our webapp, then the tests continues but fails. Is it somehow possible to log the json calls from selenium using selenoid? Maybe there are endlees calls going to the browser so that selenoid doesnt run into timeout?

**Comment by benzman81** [comment]
Ok, now I found a while loop that keeps checking somthing in one test. After I change that, at least this was fixed. Anyway, is it somehow possible to log the json calls from selenium using selenoid? If so I would have found the issue better. Im using this configuration, but no driver log is written:

```
{
	"internet explorer": {
		"default": "11",
		"versions": {
			"11": {
				"image": [
					"C:\\Users\\IEUser\\Downloads\\IEDriverServer.exe", "--log-level=DEBUG --log-file=C:\\Users\\IEUser\\Downloads\\IEDriverServer.log"
				]
			}
		}
	}
}
```

**Comment by aandryashin** [comment]
We will check logging logic on Windows and keep you updated.

2017-09-16 12:14 GMT+03:00 Markus Krüger <notifications@github.com>:

**Comment by vania-pooh** [comment]
@benzman81 for logging there is https://github.com/aerokube/selenoid/issues/68.

**Comment by benzman81** [comment]
So, for now there are no more tests hanging, but I can still see that browsers stay open on some vms. Seems like they have been trying to be initialized. I attach the files of two machines, maybe it helps.
![openbrowsers1](https://user-images.githubusercontent.com/14224592/30639224-4c534c98-9dfe-11e7-85f8-7b69d0ef4e1b.png)
![openbrowsers2](https://user-images.githubusercontent.com/14224592/30639223-4c52d768-9dfe-11e7-90bd-80a1d1f72c44.png)
[Selenoid1.txt](https://github.com/aerokube/selenoid/files/1317408/Selenoid1.txt)
[Selenoid2.txt](https://github.com/aerokube/selenoid/files/1317410/Selenoid2.txt)
[TaskList1.txt](https://github.com/aerokube/selenoid/files/1317409/TaskList1.txt)
[TaskList2.txt](https://github.com/aerokube/selenoid/files/1317411/TaskList2.txt)

**Comment by vania-pooh** [comment]
On Windows you can tune two interesting settings:
1) Turn off TCP offloading (https://support.rackspace.com/how-to/disabling-tcp-offloading-in-windows-server-2012/)
2) Max TCP connections per host in IE (https://support.microsoft.com/ru-ru/help/183110/wininet-limits-connections-per-server)

Not sure whether it is related to your issue but according to our experience this can dramatically accelerate things.

**Comment by benzman81** [comment]
Well, that didn't help, but didn't make it worse ;-)

Today we had a similar issue, but with an existing browser AND IEDriverServer.exe running. The big problem here was, that our tests hung again. A browser kill didn't help, but after killing the IEDriverServer.exe they continued running. Irritating is, that the process of the running IEDriverServer.exe never occurs in the selenium log :-/ (see attachments). Maybe a release with passthrough of logs from IEDriverServer.exe would be helpful to investigate such issues (including documentation on how to do it).

[Selenoid3.txt](https://github.com/aerokube/selenoid/files/1332866/Selenoid3.txt)
[TaskList3.txt](https://github.com/aerokube/selenoid/files/1332865/TaskList3.txt)

**Comment by vania-pooh** [comment]
@benzman81 ok, will try to release Selenoid as soon as possible.

**Comment by vania-pooh** [comment]
@benzman81 released 1.3.7 with driver logs capturing support.

**Comment by vania-pooh** [comment]
@benzman81 sorry, forgot to ask - did detailed IEDriver logs help to find anything new regarding this issue?

**Comment by benzman81** [comment]
@vania-pooh yes, it helped a lot. I could find some issues in my code. If I have any further problems or notice the open windows again, I get back here and reopen.
