### ISSUE TITLE
Docker compose does not pull up the browser nodes in the same network

### ISSUE THREAD

**Issue by ablok** [aerokube/selenoid#224]
When using docker compose to pull up multiple services, it creates a network so that every service can talk to another via the internal ports. Currently, all browser instances that selenoid creates do not belong to the compose network. This means we have to expose the ports of the services we want to test against to the host, then retrieve the exposed port and dynamically use that in our tests.
This would not be necessary if the nodes would be added to the compose network.

**Comment by vania-pooh** [comment]
This was implemented in https://github.com/aerokube/selenoid/issues/87. You should start Selenoid with `-container-network my-network-name` in order to achieve this. Please check whether it works for you.

**Comment by ablok** [comment]
Thanks! Will try that out.

**Comment by fescobar** [comment]
@vania-pooh 
Could you give some example for docker-compose?
I'm trying to use custom network, but I have the same issue.
Maybe it's not implemented for docker-compose
`
version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  selenoid:
    image: "aerokube/selenoid:latest"
    ports:
      - "4444:4444"    
    volumes:
      - "$PWD:/etc/selenoid/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-container-network", "mynetwork"]
    networks:
      - mynetwork

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8888:8080"

    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - mynetwork
`

`
org.openqa.selenium.WebDriverException: start container: Error response from daemon: network mynetwork not found (WARNING: The server did not provide any stacktrace information)
`
