### ISSUE TITLE
Browser not use proxy with authorization by login/password

### ISSUE THREAD

**Issue by oneassasin** [aerokube/selenoid#231]
I am use selenoid@1.3.7, node.js and selenium-webdriver@3.5.0. Tryed on chrome 59-61 versions and firefox last version.
When I set proxy with authorization by login/password (login:password@host:port) into capabilities to selenium-driver, browser in container not use proxy. If I set proxy without login/password (host:port) with authorization by ip - all work fine.

**Comment by vania-pooh** [comment]
@oneassasin sorry, somehow skipped this issue. Is it still actual?

**Comment by oneassasin** [comment]
Yes, actually

**Comment by vania-pooh** [comment]
Ok.

**Comment by vania-pooh** [comment]
@cheesepaulo in fact proxy authentication is not implemented in Selenium at all.
