### ISSUE TITLE
Possibility to pass additional browser container host entries via desiredCapabilities

### ISSUE THREAD

**Issue by vgrigoruk** [aerokube/selenoid#236]
Ability to pass additional host entries (for browser containers) via capabilities (that override entries defined in browsers.json)? 
The use case:
- testing canary releases to production (application is accessible via production domain, but specific hosts need to be added to /etc/hosts file)
- these hosts IP addresses are changed between deployments. IP addresses need to be fetched from 3rd-party API (in our case AWS).
- updating browsers.json for each test run will be a pain in the ass in this case.

Required changes:
- add support additional capability (e.g. containerHosts="host:ip,host2:ip2,...")
- ignore the capability if browsers are not running under docker containers
- merge host entries from containerHosts capability with hosts defined in browsers.json (capability values should override values from browsers.json if there are duplicated entries for the same "host" key)

**Comment by vania-pooh** [comment]
How would you like to pass several entries in one string capability? E.g.:
```
hostEntries: "example.com:192.168.0.1;test.com:192.168.0.2"
```

**Comment by vgrigoruk** [comment]
comma- or semicolon-separated entries is ok.
