### ISSUE TITLE
Implement enableVNC property as a capability extension

### ISSUE THREAD

**Issue by ElijahCapricorn** [aerokube/selenoid#242]
After the discussion in the https://github.com/aerokube/selenoid/issues/198 thread. I continued to research Selenium capabilities.
The capabilities are described by W3C specification for WebDriver (https://w3c.github.io/webdriver/webdriver-spec.html). The section 6.7 Protocol Extensions introduces extension capabilities that are used to provide configuration or fulfill other vendor-specific needs. The extension capability key format is "vendor:option".
So, instead to use 
```
{
  "enableVNC" : true
} 
```
I offer to use 
```
{
  "selenoid:enableVNC" : true
}
```
 or 
```
{
  "selenoid:options" : 
  {
    "enableVNC" : true
  }
}
```
This change allows to be consistent with the official specification. Also, it allows to avoid errors from webdriver like 'enableVNC was not a the name of a known capability or a valid extension capability', because webdrivers don't try to parse vendor-specific options.

**Comment by vania-pooh** [comment]
@aandryashin thoughts?

**Comment by aandryashin** [comment]
Sounds good.

2017-10-17 17:14 GMT+03:00 Ivan Krutov <notifications@github.com>:

**Comment by vania-pooh** [comment]
@ElijahCapricorn ok, let's just support `selenoid:options` as altenative to currently implemented capabilities.

**Comment by unlimUA** [comment]
Hello, how can I start selenoid with vnc 
```
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128
```
But my test throw exception `create container: Error: No such image: selenoid/vnc:chrome_61.0`
How can I download chrome images?

**Comment by vania-pooh** [comment]
@unlimUA this issue is about supporting new capabilities format. However returning to your question - please try to add `--force` flag to your command:
```
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128 --force
```
It should download images automatically. I think it does not because you already have `~/.aerokube/selenoid/browsers.json` and this is why `cm` considers that Selenoid is already configured (there should be a log message about it).

**Comment by unlimUA** [comment]
@vania-pooh Thanks. You have a right, I have already browser.json

**Comment by vania-pooh** [comment]
@ElijahCapricorn regarding this error in Python tests:
```
enableVNC was not a the name of a known capability or a valid extension capability
```
I did some experiments with Python client versions and can state that this is only reproducing with versions `3.4.x` and does not reproduce in newer versions starting from `3.5.0`. If that's the only reason to implement protocol extensions support I would postpone this. Any thoughts?

**Comment by ElijahCapricorn** [comment]
@vania-pooh This problem is still reproduced on Selenium for .NET. We discussed it in https://github.com/aerokube/selenoid/issues/198 thread. As I understand, Selenium on different platforms may generate a little bit different capabilities.

**Comment by vania-pooh** [comment]
@ElijahCapricorn this was implemented and should work in `aerokube/selenoid:latest`.
