### ISSUE TITLE
Add custom servlet

### ISSUE THREAD

**Issue by rab2215** [aerokube/selenoid#249]
With Selenium Server there is an option to add custom servlets, which i currently use to manage video recordings. Is there any configuration options to perform a similar setup with selenoid?  This is currently my only holdback from implementing this and dropping selenium server.

**Comment by benzman81** [comment]
I am using vnc2flv for video recording with selenoid. This works pretty good.

**Comment by rab2215** [comment]
Is there any documentation you can provide for this integration?

**Comment by vania-pooh** [comment]
@rab2215 we plan to integrate video recording directly to Selenoid in next releases. However there is no Servlet functionality because it is not Java. Selenoid is 100% Golang project,

**Comment by benzman81** [comment]
@vania- pooh damn, just spent some days with vnc2flv integration :-D how is the integration planned? Will the cpu of the node/container be affected or the sytem executing the tests?

**Comment by benzman81** [comment]
@vania-pooh I see. So it would be no solution for selenoid on windows machines?

**Comment by vania-pooh** [comment]
@benzman81 at least no for the first implementation. If you have any proposals of how to do this - please go ahead.

**Comment by benzman81** [comment]
@rab2215 no documentation but code ;-) in the end I start the system process flyrec.py to start recording onTestStart and kill this process with kill -2 onTestEnd. But if you use selenoid with docker containers I would wait for their solution.

**Comment by benzman81** [comment]
@vania-pooh no proposals, but wouldn't it be better to adress this additionally in ggr? no clue how to solve it nicely, but in a big grid using ggr a solution is needed as well.

**Comment by vania-pooh** [comment]
@benzman81 Ggr already support proxying VNC by session ID. This works since release 1.3.0.

**Comment by SergeyPirogov** [comment]
@benzman81 can you share the solution with vnc2flv?

**Comment by vania-pooh** [comment]
@SergeyPirogov should be something like this: https://stackoverflow.com/questions/45364429/selenoid-recording-video-of-a-running-session/45662657#45662657
@rab2215 created https://github.com/aerokube/selenoid/issues/255 for video recording implementation. Let's continue and video-related discussion there. Closing this one.
