### ISSUE TITLE
Old Firefox versions not working with JS standard client

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#253]
Getting the following error with Firefox 4.0:
```
WebDriverError: Post http://172.17.0.4:4444/wd/hub/session: net/http: HTTP/1.x transport connection broken: malformed HTTP response "0"
    at WebDriverError (/Users/designer01/Documents/ganlanyuan/myCoolProject/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/designer01/Documents/ganlanyuan/myCoolProject/node_modules/selenium-webdriver/lib/error.js:546:15)
```

**Comment by ganlanyuan** [comment]
test.js:
```javascript
var fs = require('fs');
var path = require('path');

var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('firefox', '4.0')
    .usingServer('http://localhost:4444/wd/hub')
    .build();

driver.get('https://www.google.com');
driver.findElement(By.name('q')).sendKeys('webdriver');

driver.sleep(1000).then(function() {
  driver.findElement(By.name('q')).sendKeys(webdriver.Key.TAB);
});

driver.findElement(By.css('body')).takeScreenshot().then(function(data){
  var base64Data = data.replace(/^data:image\/png;base64,/,"")
  fs.writeFile('test.png', base64Data, 'base64', function(err) { if(err) { console.log(err); } });

});

driver.quit();
```

Command:
```
node test
```

**Comment by vania-pooh** [comment]
@ganlanyuan ok, will investigate soon.

**Comment by vania-pooh** [comment]
My initial statement about Java client was wrong. What I'm getting with `selenium-java 3.6.0` and `3.4.0` is:
```
org.openqa.selenium.WebDriverException: Unable to parse remote response: {"sessionId":"1509120893357","hCode":1430125949,"value":{"nativeEvents":false,"webdriver.remote.sessionid":"1509120893357","browserName":"firefox","takesScreenshot":true,"javascriptEnabled":true,"handlesAlerts":true,"version":"4.0.1","cssSelectorsEnabled":true,"platform":"LINUX"},"class":"org.openqa.selenium.remote.Response","status":0}

**Comment by vania-pooh** [comment]
After doing some experiments with different client versions I can confirm that this is just a client incompatibility issue. Will add client compatibility information to [browser images table](http://aerokube.com/selenoid/latest/#_browser_image_information).

**Comment by ganlanyuan** [comment]
I see,
Is there a way to solve it on my end?

-------- Original Message --------

**Comment by vania-pooh** [comment]
@ganlanyuan I will test with older JS clients and try to find which one works for you.

**Comment by ganlanyuan** [comment]
Great, thanks

-------- Original Message --------

**Comment by vania-pooh** [comment]
Added information about compatible client versions for Java, Python and Javascript to [documentation](http://aerokube.com/selenoid/latest/#_browser_image_information). I can state that your current client will only work with Firefox 23.0 and above (tried even very old versions). You could probably try with more advanced Javascript libraries like [wd](https://github.com/admc/wd) or [webdriver.io](https://github.com/webdriverio/webdriverio).

**Comment by ganlanyuan** [comment]
Thanks

**Comment by ganlanyuan** [comment]
Hey, 
I got the following errors when using with [Gemini](https://github.com/gemini-testing/gemini):
```
✘ jumbotron plain [opera]
Cannot launch browser opera:
[init({"browserName":"opera","version":"33"})] The environment you requested was unavailable..
Reason: {"sessionId":"db76f6a2373d24f0c751eb5faf68332f","status":13,"value":{"message":"unknown error: cannot find Opera binary\n  (Driver info: OperaDriver=0.2.0 (ba47709ed9e35ce26dbd960fb5d75be104290d96),platform=Linux 4.9.49-moby x86_64)"}}
✘ jumbotron plain [firefox]
Cannot launch browser firefox:
[init({"browserName":"firefox","version":"6"})] The environment you requested was unavailable..
Reason: {"status":13,"value":{"message":"Post http://172.17.0.4:4444/wd/hub/session: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"0\""}}
```
Is this the same issue with selenium case?

**Comment by vania-pooh** [comment]
```
✘ jumbotron plain [opera]
Cannot launch browser opera:
[init({"browserName":"opera","version":"33"})] The environment you requested was unavailable..
Reason: {"sessionId":"db76f6a2373d24f0c751eb5faf68332f","status":13,"value":{"message":"unknown error: cannot find Opera binary\n  (Driver info: OperaDriver=0.2.0 (ba47709ed9e35ce26dbd960fb5d75be104290d96),platform=Linux 4.9.49-moby x86_64)"}}
```
This one is because you should specify path to Opera binary (this is a bug in the driver) by passing capabilities like this (this is stated in docs):
```
{"browserName": "operablink", "operaOptions": {"binary": "/usr/bin/opera"}}
```

**Comment by ganlanyuan** [comment]
Got this Error:
```
✘ jumbotron plain [opera]
Cannot launch browser opera:
[init({"browserName":"operablink","version":"33","operaOptions":{"binary":"/usr/bin/opera"}})] The environment you requested was unavailable..
Reason: {"status":13,"value":{"message":"Requested environment is not available"}}
```
after updated the capabilities:
```yaml
  opera:
    windowSize: 1024x768
    desiredCapabilities:
      # os: 'WINDOWS'
      # os_version: '7'
      browserName: 'operablink'
      version: '33'
      operaOptions: 
        binary: '/usr/bin/opera'
```

**Comment by vania-pooh** [comment]
Oh, sorry! Should be `browserName = opera` (exactly like in `browsers.json`).

**Comment by ganlanyuan** [comment]
Thanks, it works

When I test on old firefox (6-9), sometimes they work, sometimes fail with the [same errors](#issuecomment-340420329).
Does this mean these browsers are not stable?

**Comment by vania-pooh** [comment]
@ganlanyuan: these browsers are using rather old Selenium version inside as well as completely different session startup logic. Not sure about the real reason but this can caused by both the browsers and your client issues.

**Comment by ganlanyuan** [comment]
I see, thanks

**Comment by AndreyMelnichenko** [comment]
I have a similar problem with run Opera. Explain please, how can I inject  needed addition parameters "operaOptions": {"binary": "/usr/bin/opera"}" into capability method?

**Comment by aandryashin** [comment]
You have to set capabilities instead of options like this:

operaCapabilities.setCapability("opera.binary", "/usr/bin/opera")

2018-03-04 0:21 GMT+03:00 Andrey Melnichenko <notifications@github.com>:
