### ISSUE TITLE
Video recording capability

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#255]
Ability to record and save session video when requested with capability:
```
enableVideo: true
```

**Comment by SergeyPirogov** [comment]
@vania-pooh Would be great, in case to debug some flaky tests. But I think this should have two endpoints /video/session/start and /video/session/stop?status=fail. This will allow to not save videos for successful tests

**Comment by vania-pooh** [comment]
@SergeyPirogov too much complicated. I would opt for saving video all the time when capability is specified. However you could decide whether or not to attach this video to test execution report (e.g. at least Allure 1.x provides such functionality, Allure 2.x is known to implement it sooner or later). More than that we plan to save video only on the same host where browser was actually started. So it's up to infrastructure developer to decide how to transfer this data to the host where report is actually built.

**Comment by SergeyPirogov** [comment]
@vania-pooh Ok, will be good enough

**Comment by benzman81** [comment]
two things:
1. would be gread to get this to work on windows nodes as well
2. using ggr it would be great to call urls on ggr that delegates the commands to the correct node

**Comment by vania-pooh** [comment]
@benzman81 
1) This will work on any operating system with Docker. Regarding Selenoid without Docker - let's place this to the backlog.
2) There is no need to implement anything on the Ggr side because it always passing all capabilities as is. So any request to save the video - will save it but to the host where Selenoid is actually installed. It's up to you to decide whether you need a centralized storage and somehow (e.g. via `rsync`) transfer all the files there. We mainly consider capturing the video as a local tests debugging tool.

**Comment by sherlock1982** [comment]
Not only flaky tests. Sometimes only video can help to understand what exactly happened during test execution. I used [aimmac](https://github.com/aimmac23/selenium-video-node) solution and it works great but too resource greedy. 

It just records 200 last videos and then you can download it or not. 

I switched to selenoid with no video for now.

**Comment by vania-pooh** [comment]
@sherlock1982 I still don't get the difference between using VNC (which is already supported out of the box) and recording video. When a test case is broken - you can just rerun it with VNC and see what happens. Why the video is better in that case?

**Comment by sherlock1982** [comment]
I had some randomly failing tests because of race conditions in a test or test system itself. It might fail ones in a blue moon but still you need to reproduce it somehow. 

Logs and final screenshot doesn't help. What it some element is not there? You might be on a login page for some reason already.

Having a capability to record video would be great. Also project I mentioned has two ways to record videos using X server. It might be more effective than recording video client-side through VNC.

**Comment by sherlock1982** [comment]
As a suggestion: I think the best way to do it is to record video in the browser image itself. Just record X server with a ffmpeg x11grab for example if capability is present.

**Comment by vania-pooh** [comment]
@sherlock1982 yes, that's what we are expecting to do. However we would like to have a separate container including only FFMpeg. Otherwise browser images will grow to 1 Gb very fast. Also not every user in big cluster needs this. So basically yes - we would like to use `x11grab` but with a separate video capture container attached to browsers container where needed.

**Comment by sskorol** [comment]
Btw, regarding VNC: personally I'd prefer video recording directly into .mp4 format, as it could be easily embedded into Allure reports out of the box. Why .mp4? Because html 5 supports only .webm, .ogg and .mp4.

Regarding video recording itself: I'd agree with @sherlock1982 points. Sometimes it's really hard to reproduce some issues just via tests' re-running. I also attach videos to Jira tickets in some tricky cases to help developers with root cause analysis. On the other hand, sometimes it's required to show someone a new feature, which is not yet deployed to staging environment. That's  where video recording perfectly works for me.

**Comment by vania-pooh** [comment]
@sskorol yes, we plan to output to `mp4` (currently using `h264` codec).

**Comment by vania-pooh** [comment]
How to use this stuff:
1) `$ docker pull selenoid/video-recorder`
2) Specify video output directory via `-video-output-dir /path/to/my/dir` flag. Directory is created automatically when not existing.
3) Add `enableVideo: true` capability to tests and run them. Videos are saved to specified directory.

**Comment by sherlock1982** [comment]
Would be nice to have the ability to download them with a session id.
Also would be nice if they were automatically rotated. Let's say you save 200 last videos.

**Comment by vania-pooh** [comment]
@sherlock1982 
1) We don't know session ID when starting video container.
2) I would do it with cron and shell scripts. Let's keep it simple.

**Comment by vania-pooh** [comment]
Ok, added saving video by session ID and `/video/` API to download the file. Need to test that it works on Windows and will close it.

**Comment by vania-pooh** [comment]
We consider this implemented.

**Comment by liulirun** [comment]
@vania-pooh , Can we add these info to the document?

Video works ONLY if you specify in test case: enableVideo: true
VNC works ONLY if you specify in test case: enableVNC: true

The current doc states they could be enabled. but actually they are ONLY enabled by this parameter in capability

I spend quite a few hours yesterday, trying to find the pamameters of enable VNC as CLI flag. It is kind of confusing for new comers.

**Comment by vania-pooh** [comment]
@liulirun added a note about it to docs. https://github.com/aerokube/selenoid/pull/358
