### ISSUE TITLE
Unable to navigate in IE

### ISSUE THREAD

**Issue by spiritofsim** [aerokube/selenoid#257]
Hello.
I'm trying to start and navigate internet explorer with selenoid.
Browser starts but navigation (Get) doesn't work.
My log is in attachment
[ielog.txt](https://github.com/aerokube/selenoid/files/1427869/ielog.txt)

Thanks!

**Comment by vania-pooh** [comment]
@SpiritOfSim your sessions are timing out. Could you check that no dialog window appears when IE is started?

**Comment by SpiritOfSim** [comment]
@vania-pooh There is only one dialog "Deleting browser history" before IE starts because of "ie.ensureCleanSession" capability.
When browser starts there are no any dialogs and popus. And it starts quite fast

**Comment by vania-pooh** [comment]
@SpiritOfSim can you check that you have all required IEDriver settings present? https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration

**Comment by SpiritOfSim** [comment]
@vania-pooh All settings of the IE are correct. btw, if you set something wrong, for example "Protected mode", it will be visible in logs

**Comment by vania-pooh** [comment]
@SpiritOfSim ok, please provide your environment (e.g. operating system and IEDriver version).

**Comment by SpiritOfSim** [comment]
@vania-pooh 
OS: windows 10
Ie version: 11.1770.14393.0
IeDriverServer.exe: 3.6.0.0
