### ISSUE TITLE
/execute command is not supported in Firefox

### ISSUE THREAD

**Issue by sherlock1982** [aerokube/selenoid#260]
Tried to execute some commands on Firefox and get errors:

POST /session/28d45f5f-3c7c-47a8-925e-9beb003189e5/execute did not match a known command
POST /session/ccdd87f3-4a9c-410a-9d33-e51bd46b4eb4/window/current/position did not match a known command
POST /session/a41c3c5a-291e-419a-b928-31eb4b42e5f6/window/current/size did not match a known command

On Chrome it works. 
On standard Selenium Firefox driver it works.

**Comment by vania-pooh** [comment]
Please provide your Firefox image version as well as Selenium client version and what is your programming language.

**Comment by sherlock1982** [comment]
Docker image: selenoid/vnc:firefox_56.0
I use this project [WebdriverIO project](http://webdriver.io/) with Typescript

Just switched to Selenoid from Selenium 3.6.0 + Geckodriver 0.19.0 + Firefox 56.0 and found out this issue.

**Comment by vania-pooh** [comment]
@sherlock1982 ok, will investigate. What is interesting - browser container has the same Geckodriver 0.19.0 inside.

**Comment by vania-pooh** [comment]
@sherlock1982 First fact - works like a charm with Java client 3.6.0. What is your `webdriver.io` version?

**Comment by sherlock1982** [comment]
The latest 4.8.0

**Comment by vania-pooh** [comment]
Ok, one more question - could you provide a small script to reproduce the issue? I have no experience with `webdriver.io`. I could install all dependencies via `npm` and then just run your script with `node`.

**Comment by sherlock1982** [comment]
Oops. For some reason I can't reproduce it with a simple script. So it might be because of my project settings somewhere. I will check more for myself.

**Comment by sherlock1982** [comment]
Ok here it is. Sorry, it was late night when I finally deleted all Selenium 👍 (save it as index.js)

    var webdriverio = require('webdriverio');
    var options = {
        host: 'selenium.3cx.test',
        desiredCapabilities: {
            browserName: 'firefox'
        }
    };
    webdriverio
        .remote(options)
        .init()
        .url('http://www.google.com')
        // Here's the issue
        .scroll(0, 0)
        .getTitle().then(function(title) {
            console.log('Title was: ' + title);
        })
        .end();


Also you need package.json:

    {
      "dependencies": {
        "webdriverio": "^4.8.0"
      }
    }

Please run "npm i" and then "node index.js"

**Comment by sherlock1982** [comment]
If you replace scrollTo with execute(scroll) you can analyze a bit more.
It's the return type that matters:

Works:

    var scroll = function scroll(x, y) {
      return 1;
    };

Doesn't work:

    var scroll = function scroll(x, y) {
      return undefined;
    };

In WebdriverIO scroll function for some reason is defined like this:

    var scroll = function scroll(x, y) {
      return window.scrollTo(x,y);
    };

Which works for Chrome but no for Firefox

**Comment by vania-pooh** [comment]
This is reproducing with 4.8.0. However I see a lot of fixes about it in master. For example:
* https://github.com/webdriverio/webdriverio/issues/2188
* https://github.com/webdriverio/webdriverio/pull/1933
With Firefox Selenoid is proxying directly to Geckodriver without changing the response. So I think this should work with `webdriver.io` from master (did not manage to install it correctly).

**Comment by sherlock1982** [comment]
Well these issues mostly about properly displaying and interpreting error message. I will check next release. In the meantime I'm thinking of a fallback to Selenium. 
Seems WebdriverIO is more suitable for this scenario. I'm having massive troubles with Firefox under Selenoid while with Selenium it was perfectly ok.
