### ISSUE TITLE
Can't localte by id when using Firefox with WebdriverIO

### ISSUE THREAD

**Issue by sherlock1982** [aerokube/selenoid#261]
Docker image: selenoid/vnc:firefox_56.0
I use this project [WebdriverIO project](http://webdriver.io/) with Typescript
Just switched to Selenoid from Selenium 3.6.0 + Geckodriver 0.19.0 + Firefox 56.0 and found out this issue.
Can be reproduced with Firefox only.

Expected behavior:

Can specify strategy "id". 

Actual behavior:

    COMMAND: POST http://selenium.3cx.test:4444/wd/hub/session/16a97393-0f64-4903-a596-2f2f9c6e7ca1/elements - {"using":"id","value":"btnAdd"}
    RESULT: {"message":"Unknown locator strategy id","type":"RuntimeError","seleniumStack":{"status":400,"type":"InvalidArgument","message":"The arguments passed to a command are either invalid or malformed.","orgStatusMessage":"Unknown locator strategy id"}}

**Comment by vania-pooh** [comment]
This is because locating elements by ID is a non-standard find element command. If you take a look at the [WebDriver spec](https://www.w3.org/TR/webdriver/#locator-strategies) - you will notice that there is no `id` strategy here. Geckodriver is following the spec and returns you an error. It works with Selenium because internally it is replacing `id` with supported strategy (`css selector` or `xpath`).

**Comment by sherlock1982** [comment]
Ok it's an issue with a client. Changed all '#btnSave' selectors to 'body #btnSave' and it works.

**Comment by tripleratamacue** [comment]
@sherlock1982 thanks for posting your workaround, but wondering if there is another solution to this, have a huge automation framework already defined, and was looking for a better/faster solution than updating all my page objects, any suggestion Ivan? @vania-pooh, thanks in advance.

**Comment by sherlock1982** [comment]
You can use patch-package to simply patch WebdriverIO for id regexp to be css selector regexp. That's very easy.
Also I saw a request or discussion that they wanted to do it it new version so it might be already working.
