### ISSUE TITLE
Ability to set timeout for a session

### ISSUE THREAD

**Issue by sherlock1982** [aerokube/selenoid#262]
It would be nice to have a timeout as a capability per session. Maybe there should be a system parameter for a maxTimeout.
Currently I can't debug with Selenoid. Default timeout 1 min is ok but not for debugging.

Unfortunately I can't use geckodriver standalone with WebdriverIO for now.

**Comment by vania-pooh** [comment]
@sherlock1982 timeout parameter is set via `-timeout` Selenoid flag. Default value is `1 min` but you can set any timeout you wish. Btw, we have Telegram support channel here: https://t.me/aerokube
@aandryashin any thoughts against this feature?

**Comment by sherlock1982** [comment]
There's one more motivation: unit tests. Sometimes it's convenient for me to run karma unit tests inside selenoid. But than during timeout tests should be finished. 

So I want to set a timeout for unit tests more than for ui.

**Comment by Alek5andr** [comment]
Vania, could please show a good example of setting up Selenoid's flag using Docker?
[Documentation](http://aerokube.com/selenoid/latest/#_selenoid_cli_flags) does not help.

My command is:
`docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release -timeout 3m0s`
The container starts, but immediately exits with code 1.

"Bind" section of `docker inspect selenoid` contains teh following:
`"Binds": [
                "/home/localadmin/.aerokube/selenoid/:/etc/selenoid/:ro",
                "/var/run/docker.sock:/var/run/docker.sock"
            ]`
If I start the container without Selenoid's flags, then it's up and running.

Advise please, how to set Selenoid's flasg correctly.

**Comment by aandryashin** [comment]
There should be $(pwd) instead of pwd, could you please chech it?

19 дек. 2017 г. 6:39 ПП пользователь "Alek5andr" <notifications@github.com>
написал:

**Comment by vania-pooh** [comment]
@Alek5andr you are passing arguments correctly. However take a look at the [Dockerfile](https://github.com/aerokube/selenoid/blob/master/Dockerfile). It contains the following lines:
```
ENTRYPOINT ["/usr/bin/selenoid"]

CMD ["-listen", ":4444", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/"]
```
That is to say - when you specify your own args, you have to specify required ones too. The only required arg is `-conf`. So to solve your issue just type the following:
```
docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release -timeout 3m0s -conf /etc/selenoid/browsers.json
```
If you wish to use video feature you have to also add an environment variable, one more volume and `-video-output-dir` flag.

**Comment by Alek5andr** [comment]
@aandryashin ,
Github didn't escape `-sign. Thanks for $(pwd) reference.

@vania-pooh ,
I have started to use Docker with Selenoid recently. So I'm new to it, and I didn't pay attention to directory with config file for "-conf" flag. Now I see that this directory should be within a container - _-conf **/etc/selenoid/browsers.json**_, not a host's one.
Thank you for the thorough explanation and the example.

By the way, I have been working with Selenium Grid most of the time. Could you please specify, what are equivalent Selenoid flags from the [documentation](http://aerokube.com/selenoid/latest/#_selenoid_cli_flags):
`-service-startup-timeout duration
    Service startup timeout in time.Duration format (default 30s)
-session-attempt-timeout duration
    New session attempt timeout in time.Duration format (default 30s)
-session-delete-timeout duration
    Session delete timeout in time.Duration format (default 30s)
-timeout duration
    Session idle timeout in time.Duration format (default 1m0s)`

to Selenium Grid ones:
`-browserTimeout
-timeout
-newSessionWaitTimeout`
?

**Comment by vania-pooh** [comment]
@Alek5andr 
1) `-timeout` is the same thing for both related to idle time between requsts.
2) `-browserTimeout` does not exist in Selenoid.
3) `-session-attempt-timeout` is the same as `-newSessionWaitTimeout`.

**Comment by vania-pooh** [comment]
Related to https://github.com/aerokube/ggr/issues/195.

**Comment by sunofsparda** [comment]
@sherlock1982 hello
could you please share you contacts
I want to ask you some questions about karma + selenoid setup
