### ISSUE TITLE
Browser missing when I use option "port" 

### ISSUE THREAD

**Issue by kenlma** [aerokube/selenoid#269]
I was started selenoid with default command & docker
./cm selenoid start --vnc
everything works well.

 when I start with option "port", the selenoid UI selenoid change to red, and browser always loading. I think I need change browser.json point to new port?
./cm selenoid start --vnc --port=8080

**Comment by vania-pooh** [comment]
When being run in containers - everything should continue to work. However when running without Docker you need to explicitly change Selenoid port when starting the UI:
```
$ ./cm selenoid-ui start --args "--selenoid-uri http://selenoid-host.example.com:8080" --port <any-custom-ui-port>
```
Selenoid UI default port is 8080, so you need to change it to something else, e.g. `8081`.

**Comment by kenlma** [comment]
Yes, i run selenoid in container. when I use default 4444, everything works well
![image](https://user-images.githubusercontent.com/11968455/32855002-51da77b8-c9f5-11e7-818a-4a27188d9cac.png)
browsers show up
![image](https://user-images.githubusercontent.com/11968455/32855026-6388d734-c9f5-11e7-811d-7abd1a5cd708.png)

when i change port like below
![image](https://user-images.githubusercontent.com/11968455/32855173-e1a1f04c-c9f5-11e7-8cc2-74b96f260ca3.png)
browsers missing 
![image](https://user-images.githubusercontent.com/11968455/32855272-10f8e620-c9f6-11e7-8ceb-cafb05b3049c.png)

check selenoid status, got result like this
{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"61.0":{},"62.0":{}},"firefox":{"55.0":{},"56.0":{}},"opera":{"47.0":{},"48.0":{}}}}

**Comment by kenlma** [comment]
just identify selenoid IP, run ui command like this, issue fixed
docker run -d --name selenoid-ui --link selenoid -p 8082:8080 aerokube/selenoid-ui --selenoid-uri=http://**hostIP**:8081

**Comment by vania-pooh** [comment]
Good. :)
