### ISSUE TITLE
 status code 500 (Selenium::WebDriver::Error::ServerError)

### ISSUE THREAD

**Issue by makorne** [aerokube/selenoid#284]
> 
docker run --rm                                   \
    -v /var/run/docker.sock:/var/run/docker.sock    \
    -v ${HOME}:/root                                \
    -e OVERRIDE_HOME=${HOME}                        \
    aerokube/cm:latest-release selenoid start       \
    --vnc --tmpfs 128`
`Unable to find image 'aerokube/cm:latest-release' locally
latest-release: Pulling from aerokube/cm
b1f00a6a160c: Pull complete 
9236b7f6a73f: Pull complete 
1cd226355d2a: Pull complete 
Digest: sha256:4bc7b5d9302318596e5d952ede5ccace9c486143593cde58544eab97bd2dbb3c
Status: Downloaded newer image for aerokube/cm:latest-release
> Using Docker
registry.ping url=https://registry.hub.docker.com/v2/
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.3.9
        [8b9b6e459ffb]: Verifying Checksum [=================================================> ]  2.768MB/        [8b9b6e459ffb]: Download complete [=================================================> ]  2.768MB/2        [d69b067512df]: Pull complete [=================================================> ]  2.768MB/2.784> Selenoid is alredy configured
> Starting Selenoid...
> Successfully started Selenoid

curl http://127.0.0.1:4444/status
{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"61.0":{},"62.0":{}},"firefox":{"56.0":{},"57.0":{}},"opera":{"48.0":{},"49.0":{}}}}

> 

`
ruby test.rb

/usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok': status code 500 (Selenium::WebDriver::Error::ServerError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:168:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:101:in `create_session'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:52:in `handshake'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/driver.rb:37:in `initialize'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:56:in `new'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:56:in `for'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver.rb:84:in `for'
        from test.rb:4:in `<main>'
`

test.rb 

`
require 'selenium-webdriver'

begin
  driver = Selenium::WebDriver.for :remote, :url => "http://127.0.0.1:4444/wd/hub",
   :desired_capabilities => #:chrome 
      :firefox
  driver.get "http://www.google.com"
  driver.save_screenshot "google.png"
ensure
 # driver.quit
end
`

**Comment by vania-pooh** [comment]
@makorne `Selenoid is alredy configured` - this message means there already was a `browers.json` file in configuration directory. Please first of all try to run the same `cm` command with `--force` flag - it redoes all from scratch: 
`$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128 --force`

**Comment by makorne** [comment]
Магия! Стоило появиться родителю, и чадо заработало! :1st_place_medal: 
Спасибище за труд!

**Comment by vania-pooh** [comment]
:) You can close the issue if it works.

**Comment by makorne** [comment]
Что-то перестало помогать и это.
```
`/usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok': status code 500 (Selenium::WebDriver::Error::ServerError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:168:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:101:in `create_session'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/bridge.rb:52:in `handshake'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/remote/driver.rb:37:in `initialize'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:56:in `new'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver/common/driver.rb:56:in `for'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.7.0/lib/selenium/webdriver.rb:84:in `for'
        from test.rb:4:in `<main>'
`
```

**Comment by vania-pooh** [comment]
@makorne точно с `--force` все делается? Вообще код 500 может означать, например, что селектор не найден.

**Comment by makorne** [comment]
Точно,и все докеры стерты. 
Селектор не ищется, простейший тест что тут сверху - скрин гугла.
`Deleted: sha256:d39d92664027be502c35cf1bf464c726d15b8ead0e3084be6e252a161730bc82
Untagged: selenoid/video-recorder:latest
Untagged: selenoid/video-recorder@sha256:0d94a27d1fe67bb51f436a4998f8edbac1171c8d344a81a3cd6eb61374b8a487
Deleted: sha256:ec1e39e38562823fb830b88f244e96322f21cc16a8438f0dc5b6606baddbfb5c
Deleted: sha256:bd287a94620141c4604bac3652c3c29df26c3f6a88b9f74a92ba6bddefed0ced
Deleted: sha256:c9ed22e319836dfc703e977750a5ac0fced070c1f8c112aefc1af633e5706df4
Deleted: sha256:771a3cc3d86ea5304dbea630b35ca2a6f2d75926f47423cb29ed43dd08ddc0a4
Deleted: sha256:9dfa40a0da3b1a8a7c34abc596d81ede2dba4ecd5c0a7211086d6685da1ce6ef
root@selenoid:/var/log# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128 --forceUnable to find image 'aerokube/cm:latest-release' locally
latest-release: Pulling from aerokube/cm
550fe1bea624: Pull complete
aa85b06af354: Pull complete
31332f731725: Pull complete
Digest: sha256:57c3ce4aa9462a2f8081e016eec1f392a05b1fbe274c455e93a8ab3f5d98b712
Status: Downloaded newer image for aerokube/cm:latest-release
> Using Docker
- Your Docker API version is 1.35
registry.ping url=https://registry.hub.docker.com/v2/
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.6.1
> Configuring Selenoid...
> Processing browser "opera"...
- Fetching tags for image selenoid/opera
registry.tags url=https://registry.hub.docker.com/v2/selenoid/opera/tags/list repository=selenoid/opera
- Requested to download VNC images...
- Pulling image selenoid/vnc:opera_52.0
- Pulling image selenoid/vnc:opera_51.0
> Processing browser "firefox"...
- Fetching tags for image selenoid/firefox
registry.tags url=https://registry.hub.docker.com/v2/selenoid/firefox/tags/list repository=selenoid/firefox
- Requested to download VNC images...
- Pulling image selenoid/vnc:firefox_60.0
- Pulling image selenoid/vnc:firefox_59.0
> Processing browser "chrome"...
- Fetching tags for image selenoid/chrome
registry.tags url=https://registry.hub.docker.com/v2/selenoid/chrome/tags/list repository=selenoid/chrome
- Requested to download VNC images...
- Pulling image selenoid/vnc:chrome_66.0
- Pulling image selenoid/vnc:chrome_65.0
> Pulling video recorder image...
- Pulling image selenoid/video-recorder
> Configuration saved to /root/.aerokube/selenoid/browsers.json
> Starting Selenoid...`

**Comment by aandryashin** [comment]
Проблема может быть в клиентской библиотеке, чтобы проверить это, можно
попробовать сделать скриншот другим языком или курлом.

2018-05-20 9:28 GMT+03:00 makorne <notifications@github.com>:

**Comment by makorne** [comment]
На другом сервере поставил - так же,  но даже статус не отвечает
```
wget http://localhost:4444/status
--2018-05-20 08:44:16--  http://localhost:4444/status
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:4444... connected.
HTTP request sent, awaiting response...
```

**Comment by vania-pooh** [comment]
@makorne это похоже на фаерволы. Тут нет даже кода возврата или connection refused.

**Comment by vania-pooh** [comment]
Сходу не знаю. Надо исследовать.

**Comment by makorne** [comment]
А как прокси в селеноид указать, чтобы например был дефолтом для ff ?

**Comment by vania-pooh** [comment]
Прокси указывается через капабилити, как обычно. Приходи в чатик лучше.
