### ISSUE TITLE
Video-recorder container appears to be not starting

### ISSUE THREAD

**Issue by evertsc** [aerokube/selenoid#292]
Hi,

I'm trying the new video feature (cool feature!), but I can't get it to work yet. It looks like the video-recorder container doesn't start (properly).

My docker images:
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
selenoid/video-recorder    latest              c199dfceb479        2 days ago          27.3MB
aerokube/selenoid          latest-release      0e5680868ab3        2 days ago          13.4MB
aerokube/selenoid-ui       latest              d514ea60cdf9        2 weeks ago         7.55MB
selenoid/vnc               chrome_62.0         faaf3f3ce248        6 weeks ago         742MB

My docker-compose.yml:
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    environment:
      - TZ=CET
      - OVERRIDE_VIDEO_OUTPUT_DIR=/tmp/video
    volumes:
      - "/opt/selenium:/etc/selenoid:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/video:/etc/selenoid/video"
    ports:
      - "4444:4444"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]

The logs:
2017/12/01 11:58:27 Loading configuration files...
2017/12/01 11:58:27 Loaded configuration from [/etc/selenoid/browsers.json]
2017/12/01 11:58:27 Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory
2017/12/01 11:58:27 Timezone: CET
2017/12/01 11:58:27 Video Dir: /opt/selenoid/video
2017/12/01 11:58:27 Listening on :4444
2017/12/01 11:59:34 [NEW_REQUEST]
2017/12/01 11:59:34 [NEW_REQUEST_ACCEPTED]
2017/12/01 11:59:34 [0] [LOCATING_SERVICE] [chrome-62]
2017/12/01 11:59:34 [0] [USING_DOCKER] [chrome-62.0]
2017/12/01 11:59:34 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_62.0]
2017/12/01 11:59:34 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_62.0] [b911ec0895e8f61cad4b332e919f7dcb6085f823dc9325590a40bf516e04f939]
2017/12/01 11:59:34 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_62.0] [b911ec0895e8f61cad4b332e919f7dcb6085f823dc9325590a40bf516e04f939] [256.665605ms]
2017/12/01 11:59:34 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder]
2017/12/01 11:59:34 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder] [da4c4e03569999ff6e1dc6022b7e81a2399f448dbb19fbbf6f2a591cdfa03cd9]
2017/12/01 11:59:35 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder] [da4c4e03569999ff6e1dc6022b7e81a2399f448dbb19fbbf6f2a591cdfa03cd9] [521.253446ms]
2017/12/01 11:59:35 [0] [SERVICE_STARTED] [selenoid/vnc:chrome_62.0] [b911ec0895e8f61cad4b332e919f7dcb6085f823dc9325590a40bf516e04f939] [1.025196ms]
2017/12/01 11:59:35 [0] [PROXY_TO] [selenoid/vnc:chrome_62.0] [b911ec0895e8f61cad4b332e919f7dcb6085f823dc9325590a40bf516e04f939] [http://172.17.0.4:4444]
2017/12/01 11:59:35 [0] [SESSION_ATTEMPTED] [unknown] [http://172.17.0.4:4444] [1]
2017/12/01 11:59:35 [0] [SESSION_CREATED] [unknown] [b34299a92a8fa3a739136d345ab14339] [http://172.17.0.4:4444] [1] [1.44162053s]
2017/12/01 11:59:46 [SESSION_DELETED] [b34299a92a8fa3a739136d345ab14339]
2017/12/01 11:59:47 [0] [STOPPING_VIDEO_CONTAINER] [da4c4e03569999ff6e1dc6022b7e81a2399f448dbb19fbbf6f2a591cdfa03cd9]
2017/12/01 11:59:47 [0] [FAILED_TO_STOP_VIDEO_CONTAINER] [da4c4e03569999ff6e1dc6022b7e81a2399f448dbb19fbbf6f2a591cdfa03cd9] [Error response from daemon: Cannot kill container: da4c4e03569999ff6e1dc6022b7e81a2399f448dbb19fbbf6f2a591cdfa03cd9: No such container: da4c4e03569999ff6e1dc6022b7e81a2399f448dbb19fbbf6f2a591cdfa03cd9]
2017/12/01 11:59:47 [0] [REMOVING_CONTAINER] [b911ec0895e8f61cad4b332e919f7dcb6085f823dc9325590a40bf516e04f939]
2017/12/01 11:59:47 [0] [CONTAINER_REMOVED] [b911ec0895e8f61cad4b332e919f7dcb6085f823dc9325590a40bf516e04f939]
2017/12/01 11:59:47 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoidcafee1e65b1f7f3186c7fb49e7a0c847.mp4 to /opt/selenoid/video/b34299a92a8fa3a739136d345ab14339.mp4: rename /opt/selenoid/video/selenoidcafee1e65b1f7f3186c7fb49e7a0c847.mp4 /opt/selenoid/video/b34299a92a8fa3a739136d345ab14339.mp4: no such file or directory]

Any idea?

Regards,
Charlie

**Comment by vania-pooh** [comment]
@evertsc I think there is an issue in your yml file:
```
- "/tmp/video:/etc/selenoid/video"
```
should be:
```
- "/tmp/video:/opt/selenoid/video"
```

**Comment by evertsc** [comment]
Ah yes, thanks, you are right, I've changed it, but the result is still the same:

Current yaml:
```
version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    environment:
      - TZ=CET
      - OVERRIDE_VIDEO_OUTPUT_DIR=/tmp/video
    volumes:
      - "/opt/selenium:/etc/selenoid:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/video:/opt/selenoid/video"
    ports:
      - "4444:4444"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
```

Log:

```
2017/12/01 12:27:25 Loading configuration files...
2017/12/01 12:27:25 Loaded configuration from [/etc/selenoid/browsers.json]
2017/12/01 12:27:25 Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory
2017/12/01 12:27:25 Timezone: CET
2017/12/01 12:27:25 Video Dir: /opt/selenoid/video
2017/12/01 12:27:25 Listening on :4444
2017/12/01 12:27:58 [NEW_REQUEST]
2017/12/01 12:27:58 [NEW_REQUEST_ACCEPTED]
2017/12/01 12:27:58 [0] [LOCATING_SERVICE] [chrome-62]
2017/12/01 12:27:58 [0] [USING_DOCKER] [chrome-62.0]
2017/12/01 12:27:58 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_62.0]
2017/12/01 12:27:58 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_62.0] [c9c099f8fcadd3dbcf48fe4548a2a2356549ab3506d55ce07b4744f9d5aaf831]
2017/12/01 12:27:58 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_62.0] [c9c099f8fcadd3dbcf48fe4548a2a2356549ab3506d55ce07b4744f9d5aaf831] [216.439532ms]
2017/12/01 12:27:58 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder]
2017/12/01 12:27:58 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder] [c03374a59b23e2be22a9c58bcf70f9d0b783479a08ae6f04a5b67bd7d961f8c1]
2017/12/01 12:27:58 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder] [c03374a59b23e2be22a9c58bcf70f9d0b783479a08ae6f04a5b67bd7d961f8c1] [289.476513ms]
2017/12/01 12:27:58 [0] [SERVICE_STARTED] [selenoid/vnc:chrome_62.0] [c9c099f8fcadd3dbcf48fe4548a2a2356549ab3506d55ce07b4744f9d5aaf831] [968.128Âµs]
2017/12/01 12:27:58 [0] [PROXY_TO] [selenoid/vnc:chrome_62.0] [c9c099f8fcadd3dbcf48fe4548a2a2356549ab3506d55ce07b4744f9d5aaf831] [http://172.17.0.3:4444]
2017/12/01 12:27:58 [0] [SESSION_ATTEMPTED] [unknown] [http://172.17.0.3:4444] [1]
2017/12/01 12:27:59 [0] [SESSION_CREATED] [unknown] [1d8f5eab3a713291167f69c8e80308a5] [http://172.17.0.3:4444] [1] [1.029616541s]
2017/12/01 12:28:08 [SESSION_DELETED] [1d8f5eab3a713291167f69c8e80308a5]
2017/12/01 12:28:08 [0] [STOPPING_VIDEO_CONTAINER] [c03374a59b23e2be22a9c58bcf70f9d0b783479a08ae6f04a5b67bd7d961f8c1]
2017/12/01 12:28:08 [0] [FAILED_TO_STOP_VIDEO_CONTAINER] [c03374a59b23e2be22a9c58bcf70f9d0b783479a08ae6f04a5b67bd7d961f8c1] [Error response from daemon: Cannot kill container: c03374a59b23e2be22a9c58bcf70f9d0b783479a08ae6f04a5b67bd7d961f8c1: No such container: c03374a59b23e2be22a9c58bcf70f9d0b783479a08ae6f04a5b67bd7d961f8c1]
2017/12/01 12:28:08 [0] [REMOVING_CONTAINER] [c9c099f8fcadd3dbcf48fe4548a2a2356549ab3506d55ce07b4744f9d5aaf831]
2017/12/01 12:28:09 [0] [CONTAINER_REMOVED] [c9c099f8fcadd3dbcf48fe4548a2a2356549ab3506d55ce07b4744f9d5aaf831]
2017/12/01 12:28:09 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid3148fd90e53fcb13bbdc47a4886437ed.mp4 to /opt/selenoid/video/1d8f5eab3a713291167f69c8e80308a5.mp4: rename /opt/selenoid/video/selenoid3148fd90e53fcb13bbdc47a4886437ed.mp4 /opt/selenoid/video/1d8f5eab3a713291167f69c8e80308a5.mp4: no such file or directory]
```

**Comment by vania-pooh** [comment]
@evertsc what happens here - video recorder container `ffmpeg` process for some reason exits. So far as it is started with `--rm` flag, it gets automatically deleted by Docker. When Selenoid tries to send `docker kill -s TERM <video-recorder>` to container, it is already deleted - thus an error in logs. So I think this is because of missing directories on your host filesystem. Could you try with this one: http://aerokube.com/selenoid/latest/#_selenoid_with_docker_compose ? It mounts everything to current directory.

**Comment by evertsc** [comment]
I've just tried that docker-compose.yml and also tried starting it from command line with the commands from the same page, but I'm still getting this same error:

```
2017/12/01 13:44:16 [NEW_REQUEST]
2017/12/01 13:44:16 [NEW_REQUEST_ACCEPTED]
2017/12/01 13:44:16 [1] [LOCATING_SERVICE] [chrome-]
2017/12/01 13:44:16 Using default version: 59.0
2017/12/01 13:44:16 [1] [USING_DOCKER] [chrome-59.0]
2017/12/01 13:44:16 [1] [CREATING_CONTAINER] [selenoid/vnc:chrome_59.0]
2017/12/01 13:44:16 [1] [STARTING_CONTAINER] [selenoid/vnc:chrome_59.0] [a39faadc8aa4976970ca6e468bc3d561f22ca9c11caba67e888601598aabeb0a]
2017/12/01 13:44:16 [1] [CONTAINER_STARTED] [selenoid/vnc:chrome_59.0] [a39faadc8aa4976970ca6e468bc3d561f22ca9c11caba67e888601598aabeb0a] [192.79378ms]
2017/12/01 13:44:16 [1] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder]
2017/12/01 13:44:16 [1] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder] [db64c1eba8e19673ba158ce8efbd9262ea76967a348708572b527a9d55a13656]
2017/12/01 13:44:16 [1] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder] [db64c1eba8e19673ba158ce8efbd9262ea76967a348708572b527a9d55a13656] [260.337802ms]
2017/12/01 13:44:16 [1] [SERVICE_STARTED] [selenoid/vnc:chrome_59.0] [a39faadc8aa4976970ca6e468bc3d561f22ca9c11caba67e888601598aabeb0a] [851.628Âµs]
2017/12/01 13:44:16 [1] [PROXY_TO] [selenoid/vnc:chrome_59.0] [a39faadc8aa4976970ca6e468bc3d561f22ca9c11caba67e888601598aabeb0a] [http://172.17.0.3:4444/]
2017/12/01 13:44:16 [1] [SESSION_ATTEMPTED] [unknown] [http://172.17.0.3:4444/] [1]
2017/12/01 13:44:17 [1] [SESSION_CREATED] [unknown] [83ca76fdbc1c160b8b0d916e2022d965] [http://172.17.0.3:4444/] [1] [1.05086037s]
2017/12/01 13:44:36 [SESSION_DELETED] [83ca76fdbc1c160b8b0d916e2022d965]
2017/12/01 13:44:36 [1] [STOPPING_VIDEO_CONTAINER] [db64c1eba8e19673ba158ce8efbd9262ea76967a348708572b527a9d55a13656]
2017/12/01 13:44:36 [1] [FAILED_TO_STOP_VIDEO_CONTAINER] [db64c1eba8e19673ba158ce8efbd9262ea76967a348708572b527a9d55a13656] [Error response from daemon: Cannot kill container db64c1eba8e19673ba158ce8efbd9262ea76967a348708572b527a9d55a13656: No such container: db64c1eba8e19673ba158ce8efbd9262ea76967a348708572b527a9d55a13656]
2017/12/01 13:44:36 [1] [REMOVING_CONTAINER] [a39faadc8aa4976970ca6e468bc3d561f22ca9c11caba67e888601598aabeb0a]
2017/12/01 13:44:36 [1] [CONTAINER_REMOVED] [a39faadc8aa4976970ca6e468bc3d561f22ca9c11caba67e888601598aabeb0a]
2017/12/01 13:44:36 [1] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoidcf7b8feec5737466e3daabc2b0982850.mp4 to /opt/selenoid/video/83ca76fdbc1c160b8b0d916e2022d965.mp4: rename /opt/selenoid/video/selenoidcf7b8feec5737466e3daabc2b0982850.mp4 /opt/selenoid/video/83ca76fdbc1c160b8b0d916e2022d965.mp4: no such file or directory]
```

During the test I keep checking docker ps -a and I can see the container for chrome, but I don't see the recorder containing coming up at any point.

I'm running on Ubuntu 16.04 b.t.w.
Docker version 17.05.0-ce, build 89658be

**Comment by vania-pooh** [comment]
@evertsc btw, do you have latest browser images? It is required to update them to work with video (new flags were added to the entrypoint script). Just try to:
```
$ docker pull selenoid/vnc:chrome_59.0
```
... without restarting Selenoid and try to run your test again.

**Comment by evertsc** [comment]
Yes, that did the trick!

**Comment by vania-pooh** [comment]
@evertsc closing?

**Comment by evertsc** [comment]
Yes, thanks again.
