### ISSUE TITLE
./cm selenoid start --port 4445 displays Error: unknown flag: --port

### ISSUE THREAD

**Issue by brian-menzies** [aerokube/selenoid#293]
Good morning. I was following the documentation to install a Selenoid Service on a different port as seen in your [documentation](http://aerokube.com/cm/latest/#_example_commands), and when trying to run `./cm selenoid start --port 4445` I received the following error message:
`Error: unknown flag: --port
Usage:
  cm selenoid start [flags]

Flags:
  -a, --architecture string       target architecture (drivers only) (default "amd64")
  -g, --args string               additional service arguments (e.g. "-limit 5")
  -w, --browser-env string        override container or driver environment variables (e.g. "KEY1=value1 KEY2=value2")
  -b, --browsers string           comma separated list of browser names to process
  -j, --browsers-json string      browsers JSON data URL (in most cases never need to be set manually) (default "https://raw.githubusercontent.com/aerokube/cm/master/browsers.json")
  -c, --config-dir string         directory to save files (default "/home/ec2-user/.aerokube/selenoid")
  -e, --env string                override service environment variables (e.g. "KEY1=value1 KEY2=value2")
  -f, --force                     force action
  -l, --last-versions int         process only last N versions (Docker only) (default 2)
  -n, --no-download               only output config file without downloading images or drivers
  -o, --operating-system string   target operating system (drivers only) (default "linux")
  -q, --quiet                     suppress output
  -r, --registry string           Docker registry to use (default "https://registry.hub.docker.com")
  -t, --tmpfs int                 add tmpfs volume sized in megabytes (Docker only)
  -v, --version string            desired version; default is latest release (default "latest")
  -s, --vnc                       download containers with VNC support (Docker only)`

This was attempted on an AWS Linux AMI 2017.09.1 (HVM), and I had run the previous commands without problem:
'sudo usermod -a -G docker ec2-user
sudo curl -L -o cm https://github.com/aerokube/cm/releases/download/1.2.4/cm_linux_amd64
sudo chmod +x ./cm'

**Comment by vania-pooh** [comment]
Please use the latest release (not 1.2.4): https://github.com/aerokube/cm/releases/latest/ We recently fixed this inconsistency in documentation.

**Comment by vania-pooh** [comment]
@brian-menzies did it help?

**Comment by brian-menzies** [comment]
@vania-pooh It did! Thanks so much!
