### ISSUE TITLE
Set custom DNS resolver for browser containers

### ISSUE THREAD

**Issue by sajal** [aerokube/selenoid#294]
I would like the browser containers to use a custom DNS resolver. How would I go about configuring it?

Docker has argument for it

```
--dns list                       Set custom DNS servers
```

To be clear I want to use a custom resolver, and not simply add entries into hosts file.

**Comment by vania-pooh** [comment]
@sajal yes, in order to use custom DNS server you should add it globally to Docker and because of that we do not provide such setting in Selenoid,

**Comment by sajal** [comment]
Would you be interested in making this configurable? 

There could be a new capability which if present would set the `ctr.HostConfig.DNS` field

**Comment by vania-pooh** [comment]
@sajal what is the use case for that? DNS servers are normally relatively stable and do not change every 5 minutes.

**Comment by sajal** [comment]
An important testing use-case for me has to do with [Resource Timing API](https://w3c.github.io/resource-timing/). 

I would like test my code against

1. Specific latency - I can control this with my own resolver with a sleep before replying.
2. Testing against failures.

I agree its not a common use-case for web development, but for us it is. Specifying a custom resolver for a test would allow me to run one on local network where it can simulate various things I want to test.

**Comment by vania-pooh** [comment]
@sajal 
So far as I know e.g. Chromedriver it latest releases has Network Throttling feature: https://stackoverflow.com/questions/40683810/google-chrome-throttling-with-selenium https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions It seems to emulate latency. 

I'm not against this feature. Just trying to understand whether we can get this without changing Selenod code.

@aandryashin any ideas?

**Comment by vania-pooh** [comment]
@sajal is this one is still needed?

**Comment by vania-pooh** [comment]
@sajal ok, let me think more about possible implementation.
