### ISSUE TITLE
How to set dns and dns-search for containers which were started by selenoid

### ISSUE THREAD

**Issue by dimastick** [aerokube/selenoid#297]
I also faced the issue described here https://github.com/aerokube/selenoid/issues/23. I mean the second part of the mentioned one: "Also, it is nice to know how to set dns and dns-search for containers which were started by selenoid?". Is there any way to pass dns settings into chrome container started by selenoid hub. We use browsermob-proxy server which is started on local machine. Then we create selenium proxy based on it and add selenium proxy to chrome profile. When chrome container is started browser has the following setting related to proxy ones: "... --proxy-server=http=ubuntuhost:38888;https=ubuntuhost:38888 ...".
ubuntuhost is my hostname which is taken by browsermob-proxy and then given to browser container via profile. Could you please advise?

**Comment by vania-pooh** [comment]
@dimastick what's not working? We also answer to questions in Telegram chat: https://t.me/aerokube.

**Comment by dimastick** [comment]
Hi, thanks for quick response. Unfortunately I encountered the following error "Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED". I think that browser in container can't understand what "ubuntuhost" in proxy settings is (can't resolve it to IP) so can't start loading resources through the proxy.

**Comment by vania-pooh** [comment]
@dimastick you can dynamically add `/etc/hosts` entries in test using `hostsEntries` capability: http://aerokube.com/selenoid/latest/#_hosts_entries_hostsentries

**Comment by dimastick** [comment]
Thank you.
"hostsEntries": "ubuntuhost:192.168.11.11" browser setting did not help me but "hosts": ["ubuntuhost:192.168.11.11"] works fine for me. Any difference?

**Comment by vania-pooh** [comment]
`hosts` should be specified in `browsers.json`, whereas `hostsEntries` in test code.

**Comment by dimastick** [comment]
Got it. Thank you for your help. You can close it
