### ISSUE TITLE
Add unique string to videoName to prevent getting overwritten

### ISSUE THREAD

**Issue by evertsc** [aerokube/selenoid#298]
Hi,

Is it possible to add a unique string (for example date-time-string) to the videoName when you set this capability (kinda like Zalenium does)? Or maybe as a feature in the future?
When I run for example a Test Suite with 3  Test Cases, I end up with one video of one of the test cases. And it's very handy to use a distinct name instead of the session-id.

Thanks,
Charlie

**Comment by vania-pooh** [comment]
@evertsc by default we are using `<sessionId>.mp4` which is always unique. When you set `videoName` capability it becomes your responsibility to provide unique names. You could e.g. use UUID generator or some date pattern - as you wish. So currently we do not plan to do any modifications here because we consider this user's responsibility.

**Comment by evertsc** [comment]
Ok, thanks anyway. In our case the users don't have much options to change this, but we have added some lines of code and build our own version that adds the date-time string in the name.
```
        if browser.Caps.Video && browser.Caps.VideoName != "" {
                browser.Caps.VideoName = browser.Caps.VideoName[:len(browser.Caps.VideoName)-4] + fmt.Sprintf(time.Now().Format("-20060102150405.000")) + browser.Caps.VideoName[len(browser.Caps.VideoName)-4:]
        }
```
Thanks again for the work you put in this project, love it.

**Comment by vania-pooh** [comment]
@evertsc yes, we initially planned to do this but anyway using time-based file name is not so reliable in general case. And also matching session to file name in that case becomes more difficult. So in final release we changed time-based name to sessionID with the option to override it.

Any more questions in this issue?

**Comment by evertsc** [comment]
No, more questions. Thank you. I will close this issue.
