### ISSUE TITLE
specify custom chrome binary location

### ISSUE THREAD

**Issue by rab2215** [aerokube/selenoid#302]
Selenoid is currently only able to run the open chrome from a default location, but there's situations where the user would need to specify a different location of the chrome browser binary.  One would be for Windows electron applications, which just uses chrome in the background.  I am run tests in this scenario with standard selenium/selenium grid.

**Comment by vania-pooh** [comment]
@rab2215 your statement is not correct. When working without Docker you can specify any binary location in `browsers.json` file. See this documentation section for more details: http://aerokube.com/selenoid/latest/#_using_selenoid_without_docker

**Comment by rab2215** [comment]
Ok sorry I must have overlooked that. But still, it seems as if selenoid
should support a custom binary location when it’s defined as part of
DesiredCapabilities just as standard selenium grid does.

**Comment by vania-pooh** [comment]
@rab2215 what is the use case for this feature? In Selenoid config you can define an unlimited number of versions using any driver binary you wish. We consider that driver binary path should be specified only in configuration. If you specify driver binary path in tests - then your tests become tightly coupled to testing infrastructure and in many cases not portable. This is a bad practice.

**Comment by rab2215** [comment]
I would not agree, I would say it would be bad practice to statically set
the binary path on the test machine. What if the path changes? Then I would
have to manually go to each machine that has it statically set and update
it. This scenario would actually happen a lot when the binary path contains
a version number as ours does.  If this configuration was able to be
injected via a ChromeOption to DesiredCapabilities, then the location can
be set at runtime via a system property.  Then this is a single one line
change to update the path and all the test modes can be generic.

**Comment by rab2215** [comment]
Regarding the link you provided: http://aerokube.com/selenoid/latest/#_using_selenoid_without_docker
I do not see any info on how to define the binary path of the browser, the only option in this example is how to set the location of the browser driver.  Am I missing something?

**Comment by vania-pooh** [comment]
@rab2215 you can only define Chromedriver binary in config only not in tests. Could you provide an example code snippet - how are you setting chromedriver binary in tests?

**Comment by rab2215** [comment]
Just to be clear I'm needing to be able to configure the binary location of the browser itself, not the driver for the browser.

```java
String browserLocation = “location of the browser exe“;

Map<String, Object> chromeOptions = new HashMap<>();
 chromeOptions.put("binary", browserLocation);

  DesiredCapabilities desiredCapabilities = new DesiredCapabilities(); 
desiredCapabilities.setCapability("platform", platform); 
desiredCapabilities.setCapability("browserName", browserType); 
desiredCapabilities.setCapability("version", browserVersion); 
desiredCapabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
```

**Comment by vania-pooh** [comment]
@rab2215 this should work because all this data is passed directly to the driver binary. Selenoid just proxies all capabilities to driver. What is the error?

**Comment by rab2215** [comment]
When attempting to create a session, a "org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary" exception is thrown, meaning that its trying to start chrome from its default location (chrome is actually not installed).

I went ahead and installed chrome to test and as i expected, it then opens chrome from the default location, instead of it starting the browser at the location defined in chromeOptions.

**Comment by vania-pooh** [comment]
@rab2215 what you can check is that Chromedriver is actually started by adding `-capture-driver-logs` Selenoid flag. With this flag in Selenoid logs you will see Chromedriver logs and the actual reason of the error. Couldn't it be because of too new Chromedriver binary? Selenoid configuration tool is always installing the latest version.

**Comment by rab2215** [comment]
Yes, I did enable the driver logs earlier to see if there was an error but there isn’t anything to note.  It does start the browser, but it’s starting the wrong one.  I wouldn’t suspect an issue with a too new chromedriver either as I have been using the latest chromedriver, 2.33, in my existing selenium grid for the past two months.  I can send the grid-router and selenoid client logs in the a.m.

**Comment by vania-pooh** [comment]
Sure please do that. Selenoid is in fact a thin proxy on top of webdriver binary.

**Comment by rab2215** [comment]
So after you mentioned it may be a chromedriver version issue that reminded me that I had in fact recently updated the Selenium java API version from 3.4.0 to 3.7.1.  I rolled back to 3.4.0 and now the selenoid client opens the application from the defined location as expected.  I opened an issue with SeleniumHQ, so it looks like this issue can be closed.

**Comment by vania-pooh** [comment]
Glad to hear. :)
