### ISSUE TITLE
Add Video Recording for non-container browsers.

### ISSUE THREAD

**Issue by qwez** [aerokube/selenoid#304]
There is a note in the documentation
> This feature only works when browsers are run in containers

But you cannot run IE in a container... Could you please add a feature to record video without container on Windows?
There is a example on Java - https://github.com/aimmac23/selenium-video-node

**Comment by vania-pooh** [comment]
Probably somewhere in the future...

**Comment by vgrigoruk** [comment]
Is it feasible to capture video from VNC (assuming that VNC server is installed on windows machine and tests are not running without "headless_ie_selenium") ?

**Comment by vania-pooh** [comment]
@vgrigoruk how would you expect to run recorder (`ffmpeg`) in this situation? Should we somehow download platform-dependent binary?

**Comment by SergeyPirogov** [comment]
For non-container browsers you could try https://github.com/SergeyPirogov/video-recorder-java

**Comment by rab2215** [comment]
Are there any plans to implement this request?

**Comment by vania-pooh** [comment]
@rab2215 not in the next release, but we could probably use ffmpeg in platform-dependent modes.

**Comment by vania-pooh** [comment]
Will be implemented as an additional command to start before webdriver and stop when it stops.

**Comment by manelpb** [comment]
any update about this?

**Comment by vania-pooh** [comment]
@manelpb what is your use case?

**Comment by manelpb** [comment]
Running edge and safari

**Comment by vania-pooh** [comment]
@manelpb I think will take a look during next 2 weeks.

**Comment by manelpb** [comment]
thank you!

**Comment by vania-pooh** [comment]
The new recommended way here is to use a proxy container for external host.
```
MicrosoftEdge": {
                "default": "77",
                "versions": {
                        "77": {
                                "image": "selenoid/external-host:1.0.0",
                                "port": "4444",
                                "path": "/",
    "env": ["URLS=[\"http://172.17.0.1:4444/\"]","VNC_PASSWORD=vncpassword","SCREEN_RESOLUTION=1921x1080x24"]
                        }
                }
        }
```
