### ISSUE TITLE
is "ping" page still exist?

### ISSUE THREAD

**Issue by ksiv** [aerokube/selenoid#310]
On the doc page one can see:
$ curl -s http://example.com:4444/ping
{"uptime":"<some-value>","lastReloadTime":"2017-05-12 12:33:06.322038542 +0300 MSK","numRequests":<some-number>}

this command returns 404 in my case.
but curl -s http://myhost.com:4444/status - return valid json

is ping page broken or deprecated?

selenoid v 1.3.1
 Ubuntu lts 16 04 64 bit

**Comment by vania-pooh** [comment]
@ksiv according to releases [page](https://github.com/aerokube/selenoid/releases/tag/1.3.4) `/ping` was added only in `1.3.4`. Our documentation URL: http://aerokube.com/selenoid/latest/ always points to master branch. For individual releases you can use URLs like this: http://aerokube.com/selenoid/1.3.1/

**Comment by ksiv** [comment]
@vania-pooh  thanks a lot I m closing this issue.
