### ISSUE TITLE
Return docker container id on driver creation.

### ISSUE THREAD

**Issue by addrians** [aerokube/selenoid#311]
Hi,
While debugging some problems, I run into an issue of getting the container id while starting the driver. Is there a way to get the container id, besides the session id when starting the driver?
Thank you

**Comment by vania-pooh** [comment]
@addrians yes, this is possible. Take a look at `/status` API, e.g. the following HTTP request (JSON was beautified for readability):
```
$ curl -s http://selenoid-host.example.com:4444/status
{
    "total": 80,
    "used": 10,
    "queued": 0,
    "pending": 1,
    "browsers": {
      "firefox": {
        "46.0": {
          "user1": {
            "count":1,
            "sessions":[
                {
                    "id": "a7a2b801-21db-4dae-a99b-4cbc0b81de96",
                    "container": "20c0f303dec60943c5779ad3f3af2b2b9cbe832b4a9c8d70745cf1533b848640",
                    "vnc": false,
                    "screen": "1920x1080x24",
                    //...
                 }
            ]
          },
         //....
}
```
Here `container` means Docker container ID.

**Comment by addrians** [comment]
Awesome. I was looking everywhere but the status page. Thank you.
