### ISSUE TITLE
Приоритет сессий

### ISSUE THREAD

**Issue by Kappasama** [aerokube/selenoid#312]
Кейс:
Запускаются "тяжелые" регрессионные тесты в параллели общей длительностью > часа. Естественно забивают всю очередь. После них запускается маленький смок-тест который необходимо выполнить срочно. Но он попадает в конец очереди.

Возможное решение:
Передать через capability приоритет теста (типа: "priority: 1"). Чем приоритет ниже, тем быстрее тест отдается на выполнение.

**Comment by aandryashin** [comment]
We do not have plans to implement prioritized queues, you can use quota
instead...

13 дек. 2017 г. 1:50 ПП пользователь "Kappasama" <notifications@github.com>
написал:

**Comment by vania-pooh** [comment]
@Kappasama already answered here: https://stackoverflow.com/questions/47746346/selenoid-query-priority/47765306#47765306

**Comment by vania-pooh** [comment]
Closing.
