### ISSUE TITLE
Docker File Chrome and Chromedriver Versions

### ISSUE THREAD

**Issue by ryan-levell-twc** [aerokube/selenoid#323]
Is this the latest Dockerfile: https://hub.docker.com/r/selenoid/chrome/~/dockerfile/? Also, is the Dockerfile located on GitHub somewhere? I couldn't find it.

It shows chromedriver 2.27 and chrome 63 - I think:

```
apt-get -qqy install google-chrome-stable && \
...
ARG CHROME_DRIVER_VERSION=2.27
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip && \
...
```

But 2.27 does not support `apt-get google-chrome-stable` which is 63 currently: https://chromedriver.storage.googleapis.com/2.27/notes.txt

```
----------ChromeDriver v2.27 (2016-12-23)----------
Supports Chrome v54-56
```

If I am not missing something, should both chrome and chromedriver be explicitly stated to ensure compatibility?

**Comment by vania-pooh** [comment]
@ryan-levell-twc sorry, this is confusing. But this Dockerfile on the Docker Hub page is an outdated one and unfortunately I can't delete it. Docker Hub has two type of repositories - with automated and manually built images. This one was initially created as automated and I can't find the way to convert it to manually built. So please just ignore this Dockerfile. Correct image build files are located here: http://github.com/aerokube/selenoid-images/ and real versions of browsers and drivers are present in documentation: http://aerokube.com/selenoid/latest/#_browser_image_information That's the only source of truth. :)

**Comment by ryan-levell-twc** [comment]
Ah good to know. Thanks for the clarification @vania-pooh.
