### ISSUE TITLE
Pending Tests Hanging

### ISSUE THREAD

**Issue by ryanlevell** [aerokube/selenoid#326]
I have 11 Selenoid hubs:
16 browsers per VM
8 cores
16 GB ram

They have seemed to work well until today. The tests begin with a high number of running tests and lower numbers of pending/queued, but in the middle of testing the pending grows much larger and execution slows down.

I created 11 all new hubs, but the issue came back:
<img width="416" alt="screen shot 2018-01-08 at 5 11 17 pm" src="https://user-images.githubusercontent.com/6411462/34697066-ffdcb440-f496-11e7-9eb6-da402fefa23f.png">

Any idea how to further debug?
I set docker0 to etho0.
I am using 2x containers to cores.
I am using overlayfs storage driver.
uptime: `23:06:23 up  4:57,  1 user,  load average: 13.06, 14.28, 14.42`

**Comment by vania-pooh** [comment]
Pending containers usually mean too many containers being started in parallel. Having `2 x num_cores` containers overall can be the reason for that. You could try to decrease `-limit` value and see whether it helps. Load average seems to be reasonable. However you could reach disk drive performance limits. Also how about memory usage?

**Comment by ryanlevell** [comment]
I'll lower the `limit` tomorrow. I know this is only a small peek into the hubs, but I did run `top` on just one of the hubs during the peak of the pending tests. Memory looked fine:

<img width="601" alt="screen shot 2018-01-08 at 11 14 33 pm" src="https://user-images.githubusercontent.com/6411462/34706012-2319bc54-f4ca-11e7-876e-d4616a0da7b1.png">

**Comment by vania-pooh** [comment]
@ryanlevell yes, memory is ok. But take a look at `wa` value - meaning IO wait. Normally it should be several percent max for short periods of time. In your case it is `40` meaning that 40% of CPU time if being spent waiting for I\O system (more probably your VM hard disk) to complete some work. I see here two possible reasons:
1) Your hard disk is a bottleneck.
2) Some other VM running on the same physical host (probably not yours) is doing IO-consuming operations. Please check whether your cloud provider gives any disk performance guarantees. Normally they guarantee only that VM CPUs are real hardware CPUs (without overcommit) and VM memory is real hardware memory. It is hard to divide one hard disk between several VMs so they don't "feel" each other.

**Comment by ryanlevell** [comment]
Things looked better at 12 per VM, specifically `wa`. However, the load was high. Is this still a hard drive issue, or cpu issue?

```
top - 14:01:19 up  8:24,  1 user,  load average: 25.99, 22.89, 16.34
Tasks: 368 total,  11 running, 357 sleeping,   0 stopped,   0 zombie
%Cpu(s): 79.7 us, 11.9 sy,  0.0 ni,  6.9 id,  0.8 wa,  0.0 hi,  0.7 si,  0.0 st
KiB Mem : 15842572 total,  8475320 free,  4188156 used,  3179096 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 10928332 avail Mem 
```

**Comment by vania-pooh** [comment]
Your load average is rather high - almost `3 x num_cores`. However I would first try to run tests with 12 parallel sessions.

**Comment by ryanlevell** [comment]
That `top` was with the 12 in parallel. I just ran about 1 hour ago.

**Comment by vania-pooh** [comment]
@ryanlevell yes, if you are still experiencing issues. Everything depends on what's inside tests.

**Comment by ryanlevell** [comment]
The test ran fine, the pending tests stayed very low, I am just curious if a load average of ~24 could cause problems and I should proactively limit to 10, or if I should just keep at 12 and only lower if additional issues arise.

**Comment by vania-pooh** [comment]
@ryanlevell I would check whether your cloud provider increases prices when the load is high and then choose the second option if not. Not sure how it works but I remember e.g. AWS previously had VMs for moderate loads and for high loads.

**Comment by ryanlevell** [comment]
I am using AWS and they offer many different configurations. I am currently using the compute optimized instance `r4.2xlarge` i.e. the cheapest type of VM per CPU core. I don't believe load changes price. As far as my original issue, it looks fine now. I will continue to keep an eye on the load average. Thanks for the help @vania-pooh.
