### ISSUE TITLE
Ability to log all network requests

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#335]
Something like Selenium server does.

**Comment by janwiemers** [comment]
That would be a great thing, I’m running into a use case where this could particular useful.

**Comment by vania-pooh** [comment]
@janwiemers what I'm speaking about in this feature is to log Selenium protocol requests, e.g.:
```
GET /session/{session id}/element/{element id}/selected
GET /session/{session id}/element/{element id}/attribute/{name}
GET /session/{session id}/element/{element id}/property/{name}
GET /session/{session id}/element/{element id}/css/{property name}
```
Do you need this or logging concrete browser network requests? Logging browser network requests is only doable inside browser container - because its implementation is browser-specific.

**Comment by vania-pooh** [comment]
Nobody needs this. All network traffic could be capture with `/devtools/` API. https://aerokube.com/selenoid/latest/#_accessing_browser_developer_tools
