### ISSUE TITLE
chrome.switches not respected

### ISSUE THREAD

**Issue by dforrest88** [aerokube/selenoid#339]
Using the Serenity BDD framework, we're passing in the following property, which should start Chrome as a maximized window, however in selenoid, the window is not maximized.

`chrome.switches=--start-maximized`

Doing the same thing pointing to a hub running in Zalenium produces the following capabilities string and results in a maximized window.

Capabilities [{chrome.switches=--start-maximized, record-screenshots=false, browserName=chrome, idle-timeout=180, chromeOptions={args=[test-type, --start-maximized, test-type], extensions=[]}, screenResolution=2880x1800, platformName=ANY, version=, platform=ANY, ACCEPT_SSL_CERTS=true}]

**Comment by aandryashin** [comment]
We have decided do not pack window manager into selenoid docker images,
that is why the switch does not work. Also
driver.manage().window().maximize() will not work, you can use
driver.manage().window().setSize() instead.

2018-01-24 21:11 GMT+03:00 dforrest88 <notifications@github.com>:

**Comment by vania-pooh** [comment]
@dforrest88 that means this will work with any browser image having window manager inside. This is not an issue in Selenoid code.

**Comment by leorush** [comment]
@dforrest88 if you wish to use chrome command line argument, try to use this one:
`--window-size=2880,1800`

**Comment by vania-pooh** [comment]
Window manager will be added: https://github.com/aerokube/selenoid-images/issues/54
