### ISSUE TITLE
Selenoid 1.5.0 + Docker 17.12.0-ce (SERVICE_STARTUP_FAILED)

### ISSUE THREAD

**Issue by mvlbarcelos** [aerokube/selenoid#341]
When I run selenoid 1.5.0 and Docker 17.12.0-ce I get this error:
[4] [SERVICE_STARTUP_FAILED] [test] [create container: Error response from daemon: client version 1.36 is too new. Maximum supported API version is 1.35]

Some informations: 
Docker version 17.12.0-ce, build c97c6d6

Selenoid(aerokube/selenoid:latest-release) - 1.5.0
{"uptime":"1m56.08916576s","lastReloadTime":"2018-01-26 15:52:52.512912983 +0000 UTC m=+0.005295034","numRequests":0,"version":"1.5.0"}

GGR(aerokube/ggr:latest-release)
{"uptime":"1m33.632658847s","lastReloadTime":"2018-01-26 15:52:53.057974128 +0000 UTC m=+0.002723063","numRequests":0,"version":"1.4.1-2-g0dae83a"}

**Comment by vania-pooh** [comment]
@mvlbarcelos yes, that's the expected behavior. To make it work either use the latest [cm release](https://github.com/aerokube/cm/releases/tag/1.4.0) or run Selenoid container with `DOCKER_API_VERSION=1.35` environment variable set:
```
docker run -e DOCKER_API_VERSION=1.35 ....
```
This is specified in documentation [section](http://aerokube.com/selenoid/latest/#_recommended_docker_settings).

**Comment by mvlbarcelos** [comment]
Hi @vania-pooh , 
It's working
Thank you

**Comment by vid-uo** [comment]
FYI: This occured for me with the docker-compose up example and a similar fix seemed to solve the problem: 
`environment:
      - DOCKER_API_VERSION=`docker version -f '{{json .Client.DefaultAPIVersion}}'`
`

Where `docker version -f '{{json .Client.DefaultAPIVersion}}'` retrieves the current Client API Version dynamically.

**Comment by vania-pooh** [comment]
@vid-uo yes, this environment variable should applied everywhere.
