### ISSUE TITLE
Not using `network_mode: bridge`?

### ISSUE THREAD

**Issue by kaygee** [aerokube/selenoid#356]
In the documentation for docker-compose I noticed the following...

> To avoid network problems between browser drivers inside containers and Selenoid when using Docker Compose for combining with another services (such as UI or ggr) you need to enable bridge network mode for all services:

As long as I don't use the ui or ggr should I be ok?

**Comment by vania-pooh** [comment]
Should be ok then.

**Comment by vania-pooh** [comment]
/@kaygee any more stuff to discuss here
