### ISSUE TITLE
throw video if successful test

### ISSUE THREAD

**Issue by O5ten** [aerokube/selenoid#361]
Possibly an unneccessary feature request. I'll let you guys be the judges of that. 

We really like the new recording feature of selenoid and use it quite extensively. 
As such i've discovered a pattern on how i configure their download.  

I always have to download and remove the video to our CI-system(Jenkins). Because i cannot select to run post-steps on failures only. See below image: 

![jenkins-post-steps](https://user-images.githubusercontent.com/3242379/36671851-89427f80-1afd-11e8-918e-5a13c82ecce3.png)

That means i cannot entirely rely on the build status in order to trigger the downloads. I always have to trigger them, period. Even though they are successful, and i don't really want the successful recordings at all. 

So i want to suggest a custom capability: 
```
videoOnFail: Boolean
```
That would remove the video if the test is completed successfully. 
I'm not even sure if it is possible to see from a selenoid-perspective. 

But i thought i should ask, at least. :)

**Comment by vania-pooh** [comment]
@O5ten how would Selenoid understand that your test has completed successfully? :) Any assertions are being done outside of Selenoid somewhere on you build agent or on you notebook.

**Comment by O5ten** [comment]
Yup, i feared as much. I was hoping for something like a TestContext that was being transmitted. 
But that answers my question if it is possible, with a resounding no to be the answer. :)
