### ISSUE TITLE
Register Appium server with Selenoid Hub

### ISSUE THREAD

**Issue by CosminGramada** [aerokube/selenoid#366]
Hi,

Using Selenium Grid it's possible to register an Appium server, as documented [here](https://appium.io/docs/en/advanced-concepts/grid/#grid-node-configuration-example-json-file) and use Real devices.
Also, based on the documentation, it seems that it's possible to use Selenoid without Docker as well, in case of Internet Explorer for example.

So, my question is whether it's possible to register an Appium server with Selenoid, so that we can also add REAL devices for our tests?

Thanks,
Cosmin

**Comment by vania-pooh** [comment]
@CosminGramada Selenoid has no `/grid` registration API. So the only way to use Selenoid with Appium is either launch it as a process every time or build a Docker container with Appium (e.g. [like this](https://github.com/aerokube/selenoid-images/tree/master/selenium/android)).

**Comment by CosminGramada** [comment]
@vania-pooh 
Not sure whether using a container with Appium would do the trick because it require a different port in order to support parallel execution on multiple devices. So, in case I'm not missing something, to start it everytime would be way to go.

Now, regarding the capabilities, what is required in the json file so that Selenoid can communicate with the Appium Server?

**Comment by vania-pooh** [comment]
@CosminGramada in Selenoid JSON file you have to specify either Appium startup command or a reference to Docker image with Appium.

**Comment by vania-pooh** [comment]
@CosminGramada any more things to discuss in this issue?

**Comment by CosminGramada** [comment]
@vania-pooh This was on hold from my side due to several internal reasons, so I guess it can be closed.
In case any other questions or issues arise, I'll open a new thread. Thank you.

**Comment by cyberbudy** [comment]
> @CosminGramada in Selenoid JSON file you have to specify either Appium startup command or a reference to Docker image with Appium.

Hi, how to specify appium startup command in browsers.json. If I understand correctly, only docker `image` parameter is supported?

**Comment by vania-pooh** [comment]
@cyberbudy Selenoid supports `[]`-syntax as follows:
```
"image": ["path/to/command/", "--arg", "value"]
```

**Comment by cyberbudy** [comment]
Oh, didn't know that. Thank you

**Comment by vania-pooh** [comment]
@cyberbudy this is documented here: https://aerokube.com/selenoid/latest/#_using_selenoid_without_docker
