### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#372]
Questions like `Where to find logs?` and so on.

**Comment by leorush** [comment]
Maximize window not work, cannot enable vnc, blank screen on vnc, cannot open browsers.json, driver.close() is bad.

**Comment by AlexKvasko** [comment]
where i can find video on my pc, how many CPU are used for 1 container with vnc and without

**Comment by lanwen** [comment]
> selenoid_1     | 2018/03/15 21:04:17 [0] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: client version 1.36 is too new. Maximum supported API version is 1.35]

**Comment by lanwen** [comment]
Why I have label VNC, but VNC is Disconnected?

**Comment by lanwen** [comment]
Why I have black screen with a cross instead of VNC?

> don't do webdriver.close()
