### ISSUE TITLE
Video :: no video list on the /video/ URL

### ISSUE THREAD

**Issue by ksiv** [aerokube/selenoid#373]
1. No videos shown on http://ip:4444/video/   url
2.  Some errors in selenium log present for renaming selenoidID.mp4 into seleniun session ID.mp4
"no such file or directory"
By the end of operation the file is present, but it's possible not yet exist in time of renaming attempt
Not sure yet if it relates to absence of files on the url /video

I m using docker-compose to run selenoid +UI +enableVNC +enableVideo.

`{"log":"2018/03/15 10:18:15 [-] [NEW_REQUEST] [unknown] [10.101.15.124]\n","stream":"stderr","time":"2018-03-15T10:18:15.156036375Z"}
{"log":"2018/03/15 10:18:15 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.101.15.124]\n","stream":"stderr","time":"2018-03-15T10:18:15.156241078Z"}
{"log":"2018/03/15 10:18:15 [13] [LOCATING_SERVICE] [firefox] []\n","stream":"stderr","time":"2018-03-15T10:18:15.156256128Z"}
{"log":"2018/03/15 10:18:15 [-] [DEFAULT_VERSION] [Using default version: 58.0]\n","stream":"stderr","time":"2018-03-15T10:18:15.156264689Z"}
{"log":"2018/03/15 10:18:15 [13] [USING_DOCKER] [firefox] [58.0]\n","stream":"stderr","time":"2018-03-15T10:18:15.156272476Z"}
{"log":"2018/03/15 10:18:15 [13] [CREATING_CONTAINER] [selenoid/vnc:firefox_58.0]\n","stream":"stderr","time":"2018-03-15T10:18:15.156280291Z"}
{"log":"2018/03/15 10:18:15 [13] [STARTING_CONTAINER] [selenoid/vnc:firefox_58.0] [0acdb406157aad2f995759d3187f480cdc9f29412413d64b138559b769d9e927]\n","stream":"stderr","time":"2018-03-15T10:18:15.279283712Z"}
{"log":"2018/03/15 10:18:15 [13] [CONTAINER_STARTED] [selenoid/vnc:firefox_58.0] [0acdb406157aad2f995759d3187f480cdc9f29412413d64b138559b769d9e927] [0.26s]\n","stream":"stderr","time":"2018-03-15T10:18:15.53606184Z"}
{"log":"2018/03/15 10:18:15 [13] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder]\n","stream":"stderr","time":"2018-03-15T10:18:15.536096671Z"}
{"log":"2018/03/15 10:18:15 [13] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder] [71ad099875da2066ebd064f10e7a0f0af77e070f084f685c6155f586fd97c77a]\n","stream":"stderr","time":"2018-03-15T10:18:15.579692972Z"}
{"log":"2018/03/15 10:18:15 [13] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder] [71ad099875da2066ebd064f10e7a0f0af77e070f084f685c6155f586fd97c77a] [0.27s]\n","stream":"stderr","time":"2018-03-15T10:18:15.809349124Z"}
{"log":"2018/03/15 10:18:15 [13] [SERVICE_STARTED] [selenoid/vnc:firefox_58.0] [0acdb406157aad2f995759d3187f480cdc9f29412413d64b138559b769d9e927] [0.00s]\n","stream":"stderr","time":"2018-03-15T10:18:15.80937188Z"}
{"log":"2018/03/15 10:18:15 [13] [PROXY_TO] [0acdb406157aad2f995759d3187f480cdc9f29412413d64b138559b769d9e927] [http://172.17.0.4:4444/wd/hub]\n","stream":"stderr","time":"2018-03-15T10:18:15.809377624Z"}
{"log":"2018/03/15 10:18:15 [13] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/wd/hub] [1]\n","stream":"stderr","time":"2018-03-15T10:18:15.809382178Z"}
{"log":"2018/03/15 10:18:19 [13] [SESSION_CREATED] [2aa53011-9150-4ba7-a55d-696d39536f97] [1] [4.21s]\n","stream":"stderr","time":"2018-03-15T10:18:19.361705862Z"}
{"log":"2018/03/15 10:20:09 [24] [SESSION_TIMED_OUT] [2aa53011-9150-4ba7-a55d-696d39536f97]\n","stream":"stderr","time":"2018-03-15T10:20:09.680651208Z"}
{"log":"2018/03/15 10:20:09 [25] [SESSION_DELETED] [2aa53011-9150-4ba7-a55d-696d39536f97]\n","stream":"stderr","time":"2018-03-15T10:20:09.681501406Z"}
{"log":"2018/03/15 10:20:09 [13] [STOPPING_VIDEO_CONTAINER] [71ad099875da2066ebd064f10e7a0f0af77e070f084f685c6155f586fd97c77a]\n","stream":"stderr","time":"2018-03-15T10:20:09.828205691Z"}
{"log":"2018/03/15 10:20:09 [13] [STOPPED_VIDEO_CONTAINER] [71ad099875da2066ebd064f10e7a0f0af77e070f084f685c6155f586fd97c77a]\n","stream":"stderr","time":"2018-03-15T10:20:09.829452326Z"}
{"log":"2018/03/15 10:20:09 [13] [REMOVING_CONTAINER] [0acdb406157aad2f995759d3187f480cdc9f29412413d64b138559b769d9e927]\n","stream":"stderr","time":"2018-03-15T10:20:09.829496395Z"}
{"log":"2018/03/15 10:20:10 [13] [CONTAINER_REMOVED] [0acdb406157aad2f995759d3187f480cdc9f29412413d64b138559b769d9e927]\n","stream":"stderr","time":"2018-03-15T10:20:10.070077266Z"}
{"log":"2018/03/15 10:20:10 [13] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid5ed162900e0c778b6d4fe96b3e2344a5.mp4 to /opt/selenoid/video/2aa53011-9150-4ba7-a55d-696d39536f97.mp4: rename /opt/selenoid/video/selenoid5ed162900e0c778b6d4fe96b3e2344a5.mp4 /opt/selenoid/video/2aa53011-9150-4ba7-a55d-696d39536f97.mp4: no such file or directory]\n","stream":"stderr","time":"2018-03-15T10:20:10.070172024Z"}
`

**Comment by vania-pooh** [comment]
@ksiv make sure that:
1) You have `OVERRIDE_VIDEO_OUTPUT_DIR` variable set pointing to host machine directory, e.g. `/host/dir`
2) Selenoid is launched with `-video-output-dir /opt/selenoid/video`
3) Selenoid has a volume: `/host/dir -> /opt/selenoid/video`

**Comment by ksiv** [comment]
thank you a lot, sorry for disturbing. Found my misconfig. finally got all pieces working :-)
/opt/selenoid/video was bound inside to /opt/sele*m*oid/video
Was hard to track for me since videos were written ok and all was good until renaming phase.
FYI works without -video-output-dir  in docker setup

**Comment by LiPhynd** [comment]
I have same issue, can you tell me how to renaming phase?
2020/01/08 05:48:52 [4] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoide508bb4c3eec747ba67d084a4752c7f8.mp4 to /opt/selenoid/video/ca8b1262e8c87d9c0d0bcbdcfe432e8d.mp4: rename /opt/selenoid/video/selenoide508bb4c3eec747ba67d084a4752c7f8.mp4 /opt/selenoid/video/ca8b1262e8c87d9c0d0bcbdcfe432e8d.mp4: no such file or directory]

**Comment by vania-pooh** [comment]
@LiPhynd check that everything was configured correctly as explained in my previous comment. https://github.com/aerokube/selenoid/issues/373#issuecomment-373341751

**Comment by LiPhynd** [comment]
@vania-pooh Thank you. I did check your previous notes. please, can you tell me where is wrong?
 I am using Docker container to start Selenoid. see below steps from Admin PowerShell
C:\selenoid>docker volume create selenoid-videos
C:\selenoid> $current =$PWD -replace "\\", "/" -replace "C", "c"
 C:\selenoid> docker run -d --name selenoid -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v ${current}/config/:/etc/selenoid/:ro -v ${current}/video/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_DIR=${current}/video/ aerokube/selenoid:latest-release -video-output-dir /opt/selenoid/video

I have tried without -video-output-dir /opt/selenoid/video, get the same error
2020/01/08 13:41:49 [0] [SESSION_CREATED] [a9ca97e5b19cdc52ad205432bd7aa19e] [1] [5.41s]
2020/01/08 13:41:57 [20] [CONTAINER_LOGS] [e7b848167e76f0a810d24c1c8074382b2cc6a53396215c032337f693998f5b27]
2020/01/08 13:41:57 [21] [VNC_ENABLED] [a9ca97e5b19cdc52ad205432bd7aa19e]
2020/01/08 13:47:38 [811] [SESSION_DELETED] [a9ca97e5b19cdc52ad205432bd7aa19e]
2020/01/08 13:47:38 [0] [STOPPING_VIDEO_CONTAINER] [31596f6362d46384d5063843ddb026466a481740a9d1b6ad4ac581265b70a7b1]
2020/01/08 13:47:40 [0] [REMOVING_CONTAINER] [31596f6362d46384d5063843ddb026466a481740a9d1b6ad4ac581265b70a7b1]
2020/01/08 13:47:40 [0] [FAILED_TO_REMOVE_CONTAINER] [31596f6362d46384d5063843ddb026466a481740a9d1b6ad4ac581265b70a7b1] [Error response from daemon: removal of container 31596f6362d46384d5063843ddb026466a481740a9d1b6ad4ac581265b70a7b1 is already in progress]
2020/01/08 13:47:40 [0] [REMOVING_CONTAINER] [e7b848167e76f0a810d24c1c8074382b2cc6a53396215c032337f693998f5b27]
2020/01/08 13:47:40 [21] [VNC_CLIENT_DISCONNECTED] [a9ca97e5b19cdc52ad205432bd7aa19e]
2020/01/08 13:47:40 [21] [VNC_SESSION_CLOSED] [a9ca97e5b19cdc52ad205432bd7aa19e]
2020/01/08 13:47:40 [20] [CONTAINER_LOGS_DISCONNECTED] [a9ca97e5b19cdc52ad205432bd7aa19e]
2020/01/08 13:47:41 [0] [CONTAINER_REMOVED] [e7b848167e76f0a810d24c1c8074382b2cc6a53396215c032337f693998f5b27]
2020/01/08 13:47:41 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoidd8314a830f116642081201d123373d10.mp4 to /opt/selenoid/video/a9ca97e5b19cdc52ad205432bd7aa19e.mp4: rename /opt/selenoid/video/selenoidd8314a830f116642081201d123373d10.mp4 /opt/selenoid/video/a9ca97e5b19cdc52ad205432bd7aa19e.mp4: no such file or directory]

**Comment by vania-pooh** [comment]
@LiPhynd variable name should be `OVERRIDE_VIDEO_OUTPUT_DIR` and not `OVERRIDE_VIDEO_DIR`.

**Comment by LiPhynd** [comment]
@vania-pooh, Thank you!. My issue has been resolved. Also, comments on https://github.com/aerokube/selenoid/issues/517 did help me to understand how to get any volumes to mount in Docker for Windows.

**Comment by ilitvinov-ellation** [comment]
Is any way to solve the same problem when use Configuration manager
I use this `./cm selenoid update -b firefox:90.0 -e OVERRIDE_VIDEO_OUTPUT_DIR=/tmp/videos -g "-video-output-dir /opt/selenoid/video"`

**Comment by vania-pooh** [comment]
@ilitvinov-ellation with default settings `cm` will configure everything automatically.

**Comment by shabanasarithala12** [comment]
I am getting the same error , I checked my configuration but not getting where I went wrong @vania-pooh can you help me on this please.
command I have used - **docker run -d --name selenoid -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v ${current}/config/:/etc/selenoid/:ro -v /c/Users/Shabana.Sarithala/selenoid/video/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/Shabana.Sarithala/selenoid/video/ aerokube/selenoid:latest-release**

logs -
2021/09/29 09:22:16 [-] [INIT] [Loading configuration files...]
2021/09/29 09:22:16 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2021/09/29 09:22:16 [-] [INIT] [Video Dir: /opt/selenoid/video]
2021/09/29 09:22:16 [-] [INIT] [Your Docker API version is 1.41]
2021/09/29 09:22:16 [-] [INIT] [Timezone: UTC]
2021/09/29 09:22:16 [-] [INIT] [Listening on :4444]
2021/09/29 10:04:42 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2021/09/29 10:04:42 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2021/09/29 10:04:42 [404] [LOCATING_SERVICE] [chrome] [93.0]
2021/09/29 10:04:42 [404] [USING_DOCKER] [chrome] [93.0]
2021/09/29 10:04:42 [404] [CREATING_CONTAINER] [selenoid/chrome:93.0]
2021/09/29 10:04:42 [404] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/chrome:93.0]
2021/09/29 10:18:26 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2021/09/29 10:18:26 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2021/09/29 10:18:26 [571] [LOCATING_SERVICE] [chrome] [93.0]
2021/09/29 10:18:26 [571] [USING_DOCKER] [chrome] [93.0]
2021/09/29 10:18:26 [571] [CREATING_CONTAINER] [selenoid/chrome:93.0]
2021/09/29 10:18:26 [571] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/chrome:93.0]
2021/09/29 10:22:25 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2021/09/29 10:22:25 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2021/09/29 10:22:25 [623] [LOCATING_SERVICE] [chrome] [93.0]
2021/09/29 10:22:25 [623] [USING_DOCKER] [chrome] [93.0]
2021/09/29 10:22:25 [623] [CREATING_CONTAINER] [selenoid/chrome:93.0]
2021/09/29 10:22:25 [623] [STARTING_CONTAINER] [selenoid/chrome:93.0] [5135c610f70ad0f9ece1dbca6f64be42d9c74d9c6fe50e08aaa0445db4f1b6de]
2021/09/29 10:22:26 [623] [CONTAINER_STARTED] [selenoid/chrome:93.0] [5135c610f70ad0f9ece1dbca6f64be42d9c74d9c6fe50e08aaa0445db4f1b6de] [0.87s]
2021/09/29 10:22:26 [623] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2021/09/29 10:22:26 [623] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [8b0ed24572f1a3e55111ac904e6634cc258c04a0e0c472a4d28cbc47ef64ecb8]
2021/09/29 10:22:27 [623] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [8b0ed24572f1a3e55111ac904e6634cc258c04a0e0c472a4d28cbc47ef64ecb8] [0.72s]
2021/09/29 10:22:28 [623] [SERVICE_STARTED] [selenoid/chrome:93.0] [5135c610f70ad0f9ece1dbca6f64be42d9c74d9c6fe50e08aaa0445db4f1b6de] [0.70s]
2021/09/29 10:22:28 [623] [PROXY_TO] [5135c610f70ad0f9ece1dbca6f64be42d9c74d9c6fe50e08aaa0445db4f1b6de] [http://172.17.0.4:4444/]
2021/09/29 10:22:28 [623] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2021/09/29 10:22:30 [623] [SESSION_CREATED] [63c7515b16ac10ff75a66b6c57a6c66a] [1] [5.00s]
2021/09/29 10:22:37 [632] [SESSION_DELETED] [63c7515b16ac10ff75a66b6c57a6c66a]
2021/09/29 10:22:37 [623] [STOPPING_VIDEO_CONTAINER] [8b0ed24572f1a3e55111ac904e6634cc258c04a0e0c472a4d28cbc47ef64ecb8]
2021/09/29 10:22:39 [623] [REMOVING_CONTAINER] [8b0ed24572f1a3e55111ac904e6634cc258c04a0e0c472a4d28cbc47ef64ecb8]
2021/09/29 10:22:39 [623] [FAILED_TO_REMOVE_CONTAINER] [8b0ed24572f1a3e55111ac904e6634cc258c04a0e0c472a4d28cbc47ef64ecb8] [Error response from daemon: removal of container 8b0ed24572f1a3e55111ac904e6634cc258c04a0e0c472a4d28cbc47ef64ecb8 is already in progress]
2021/09/29 10:22:39 [623] [REMOVING_CONTAINER] [5135c610f70ad0f9ece1dbca6f64be42d9c74d9c6fe50e08aaa0445db4f1b6de]
2021/09/29 10:22:39 [623] [CONTAINER_REMOVED] [5135c610f70ad0f9ece1dbca6f64be42d9c74d9c6fe50e08aaa0445db4f1b6de]
2021/09/29 10:22:39 [623] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid4a0835827e5aa2e8560d0a757c9b9d04.mp4 to /opt/selenoid/video/firstVideo: rename /opt/selenoid/video/selenoid4a0835827e5aa2e8560d0a757c9b9d04.mp4 /opt/selenoid/video/firstVideo: no such file or directory]

**Comment by vania-pooh** [comment]
@shabanasarithala12 how it your error related to video listing?

**Comment by shabanasarithala12** [comment]
@vania-pooh I am getting video error , failed to rename - no such file or directory

**Comment by vania-pooh** [comment]
@shabanasarithala12 please fix this one first.
```
2021/09/29 10:04:42 [404] [SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/chrome:93.0]

```

**Comment by shabanasarithala12** [comment]
@vania-pooh That is fixed. These are latest logs

_2021/09/30 05:54:41 [1618] [CONTAINER_STARTED] [selenoid/chrome:93.0] [fd1ae4d558685f97c48e220f4bb148e6b12960cb606f33a1b8793c3f2cc995f4] [1.51s]
2021/09/30 05:54:41 [1618] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2021/09/30 05:54:42 [1618] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [0a39eae27a31c9881d35ac84a2e328fe85ad1e5ac039674e3674ef3799e1e897]
2021/09/30 05:54:42 [1618] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [0a39eae27a31c9881d35ac84a2e328fe85ad1e5ac039674e3674ef3799e1e897] [0.83s]
2021/09/30 05:54:42 [1618] [SERVICE_STARTED] [selenoid/chrome:93.0] [fd1ae4d558685f97c48e220f4bb148e6b12960cb606f33a1b8793c3f2cc995f4] [0.00s]
2021/09/30 05:54:42 [1618] [PROXY_TO] [fd1ae4d558685f97c48e220f4bb148e6b12960cb606f33a1b8793c3f2cc995f4] [http://172.17.0.4:4444]
2021/09/30 05:54:42 [1618] [SESSION_ATTEMPTED] [http://172.17.0.4:4444] [1]
2021/09/30 05:54:43 [1618] [SESSION_CREATED] [ad9a1ae98750daaa9c2072b9895ad484] [1] [3.38s]
2021/09/30 05:56:50 [1759] [SESSION_DELETED] [ad9a1ae98750daaa9c2072b9895ad484]
2021/09/30 05:56:50 [1618] [STOPPING_VIDEO_CONTAINER] [0a39eae27a31c9881d35ac84a2e328fe85ad1e5ac039674e3674ef3799e1e897]
2021/09/30 05:56:51 [1618] [REMOVING_CONTAINER] [0a39eae27a31c9881d35ac84a2e328fe85ad1e5ac039674e3674ef3799e1e897]
2021/09/30 05:56:51 [1618] [FAILED_TO_REMOVE_CONTAINER] [0a39eae27a31c9881d35ac84a2e328fe85ad1e5ac039674e3674ef3799e1e897] [Error response from daemon: removal of container 0a39eae27a31c9881d35ac84a2e328fe85ad1e5ac039674e3674ef3799e1e897 is already in progress]
2021/09/30 05:56:51 [1618] [REMOVING_CONTAINER] [fd1ae4d558685f97c48e220f4bb148e6b12960cb606f33a1b8793c3f2cc995f4]
2021/09/30 05:56:52 [1618] [CONTAINER_REMOVED] [fd1ae4d558685f97c48e220f4bb148e6b12960cb606f33a1b8793c3f2cc995f4]
2021/09/30 05:56:52 [1618] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid0d46bebd0289a94b0193834575f35c36.mp4 to /opt/selenoid/video/ad9a1ae98750daaa9c2072b9895ad484.mp4: rename /opt/selenoid/video/selenoid0d46bebd0289a94b0193834575f35c36.mp4 /opt/selenoid/video/ad9a1ae98750daaa9c2072b9895ad484.mp4: no such file or directory]
PS C:\Users\aifadmin>_

**Comment by shabanasarithala12** [comment]
@vania-pooh now I am getting video error . Can you please help me in resolving this
`2021/09/30 05:56:52 [1618] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid0d46bebd0289a94b0193834575f35c36.mp4 to /opt/selenoid/video/ad9a1ae98750daaa9c2072b9895ad484.mp4: rename /opt/selenoid/video/selenoid0d46bebd0289a94b0193834575f35c36.mp4 /opt/selenoid/video/ad9a1ae98750daaa9c2072b9895ad484.mp4: no such file or directory]`

**Comment by ViswanthSanthosh** [comment]
@vania-pooh I'm getting the same error. Have you resolved this.?

2022/09/16 09:33:09 [2] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid3ec4d60f4cf4bb22917068ecc5b18702.mp4 to /opt/selenoid/video/87ba5e474294a3412656aa4e44318dac.mp4: rename /opt/selenoid/video/selenoid3ec4d60f4cf4bb22917068ecc5b18702.mp4 /opt/selenoid/video/87ba5e474294a3412656aa4e44318dac.mp4: no such file or directory]

**Comment by ViswanthSanthosh** [comment]
@vania-pooh I'm getting the same error. Have you resolved this.?
`2022/09/16 09:33:09 [2] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid3ec4d60f4cf4bb22917068ecc5b18702.mp4 to /opt/selenoid/video/87ba5e474294a3412656aa4e44318dac.mp4: rename /opt/selenoid/video/selenoid3ec4d60f4cf4bb22917068ecc5b18702.mp4 /opt/selenoid/video/87ba5e474294a3412656aa4e44318dac.mp4: no such file or directory]`

**Comment by vania-pooh** [comment]
@ViswanthSanthosh this is not an issue but Selenoid misconfiguration on your side.

**Comment by ViswanthSanthosh** [comment]
@vania-pooh Hi I hsve checked Selenoid configuration and I'm not able to track which config parameter is causing this issue. Would be of great assistance if you could help out with the same .Please find the logs and config set below

docker run -d --name selenoid -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v /c/Users/mervi/selenoid/config/:/etc/selenoid/:ro -v /c/Users/mervi/selenoid/videotemp/:/opt/selenoid/video/ -e OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/mervi/selenoid/videotemp/ aerokube/selenoid:latest-release


`2022/09/17 17:23:23 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2022/09/17 17:23:23 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2022/09/17 17:23:23 [4] [LOCATING_SERVICE] [chrome] []
2022/09/17 17:23:23 [-] [DEFAULT_VERSION] [Using default version: latest]
2022/09/17 17:23:23 [4] [USING_DOCKER] [chrome] [latest]
2022/09/17 17:23:23 [4] [CREATING_CONTAINER] [selenoid/vnc_chrome:105.0]
2022/09/17 17:23:23 [4] [STARTING_CONTAINER] [selenoid/vnc_chrome:105.0] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732]
2022/09/17 17:23:24 [4] [CONTAINER_STARTED] [selenoid/vnc_chrome:105.0] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732] [0.45s]
2022/09/17 17:23:24 [4] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2022/09/17 17:23:24 [4] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [820491f5216846d4978f3d7e7a660850b372455aa920a54d33b52bfb3b0d4694]
2022/09/17 17:23:24 [4] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [820491f5216846d4978f3d7e7a660850b372455aa920a54d33b52bfb3b0d4694] [0.50s]
2022/09/17 17:23:24 [4] [SERVICE_STARTED] [selenoid/vnc_chrome:105.0] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732] [0.05s]
2022/09/17 17:23:24 [4] [PROXY_TO] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732] [http://172.17.0.4:4444/]
2022/09/17 17:23:24 [4] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2022/09/17 17:23:25 [4] [SESSION_CREATED] [ddc344e3c2ba323f38f5df70e694167f] [1] [1.49s]
2022/09/17 17:23:33 [13] [CONTAINER_LOGS] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732]
2022/09/17 17:23:33 [14] [VNC_ENABLED] [ddc344e3c2ba323f38f5df70e694167f]
2022/09/17 17:24:33 [20] [SESSION_TIMED_OUT] [ddc344e3c2ba323f38f5df70e694167f]
2022/09/17 17:24:33 [33] [SESSION_DELETED] [ddc344e3c2ba323f38f5df70e694167f]
2022/09/17 17:24:33 [4] [STOPPING_VIDEO_CONTAINER] [820491f5216846d4978f3d7e7a660850b372455aa920a54d33b52bfb3b0d4694]
2022/09/17 17:24:33 [4] [FAILED_TO_STOP_VIDEO_CONTAINER] [820491f5216846d4978f3d7e7a660850b372455aa920a54d33b52bfb3b0d4694] [Error response from daemon: Cannot kill container: 820491f5216846d4978f3d7e7a660850b372455aa920a54d33b52bfb3b0d4694: No such container: 820491f5216846d4978f3d7e7a660850b372455aa920a54d33b52bfb3b0d4694]
2022/09/17 17:24:33 [4] [REMOVING_CONTAINER] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732]
2022/09/17 17:24:33 [14] [VNC_CLIENT_DISCONNECTED] [ddc344e3c2ba323f38f5df70e694167f]
2022/09/17 17:24:33 [14] [VNC_SESSION_CLOSED] [ddc344e3c2ba323f38f5df70e694167f]
2022/09/17 17:24:33 [13] [CONTAINER_LOGS_DISCONNECTED] [ddc344e3c2ba323f38f5df70e694167f]
2022/09/17 17:24:34 [4] [CONTAINER_REMOVED] [8b0afca281616e687a527a104850b18575f97a1bcad966746addc2b55daf5732]
2022/09/17 17:24:34 [4] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoidddfcab2db03eaa0a4f02b4bb0b18cf81.mp4 to /opt/selenoid/video/test1_video.mp4: rename /opt/selenoid/video/selenoidddfcab2db03eaa0a4f02b4bb0b18cf81.mp4 /opt/selenoid/video/test1_video.mp4: no such file or directory]`

**Comment by vania-pooh** [comment]
@ViswanthSanthosh try to get `video-recorder` container logs why it's running.

**Comment by ViswanthSanthosh** [comment]
@vania-pooh Here's the log:

`ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --prefix=/usr --enable-avfilter --enable-gpl --enable-libx264 --enable-libpulse --enable-static --enable-small --disable-ffplay --disable-ffprobe --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-w32threads --disable-alsa --disable-audiotoolbox --disable-cuda --disable-cuvid --disable-d3d11va --disable-dxva2 --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-librtmp --disable-devices --enable-indev=xcbgrab --enable-indev=pulse --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Waiting for display to open...
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, pulse, from 'default':
  Duration: N/A, start: 1663573475.944342, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
[x11grab @ 0x7f178b3ab080] Cannot get the image data event_error: response_type:0 error_code:1 sequence:9 resource_id:1293 minor_code:4 major_code:130.
[x11grab @ 0x7f178b3ab080] Continuing without shared memory.
[x11grab @ 0x7f178b3ab080] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #1, x11grab, from 'browser:99':
  Duration: N/A, start: 1663573476.038099, bitrate: 796262 kb/s
    Stream #1:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 796262 kb/s, 12 fps, 1000k tbr, 1000k tbn, 1000k tbc
/data/selenoid0a505e3acc09544417123876c8234b3a.mp4: Operation not permitted`

**Comment by vania-pooh** [comment]
@ViswanthSanthosh as you can see this is just a permissions issue. Container does not have permissions to write to `/c/Users/mervi/selenoid/config`.
