### ISSUE TITLE
Add Users section to README.md

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#375]
Add company logos.

**Comment by sidelnikovmike** [comment]
<img width="790" alt="propeller_logo" src="https://user-images.githubusercontent.com/10669327/37588563-9bb1f20a-2b73-11e8-8a2d-f49e5721cfe9.png">
Hope this image is OK :)

**Comment by vania-pooh** [comment]
@sidelnikovmike sure.

**Comment by SrinivasanTarget** [comment]
@vania-pooh You can also add ThoughtWorks into the list.  

![tw-logo](https://user-images.githubusercontent.com/8896549/37775195-4d142842-2e08-11e8-9637-9c1f758651f2.png)

**Comment by vania-pooh** [comment]
@SrinivasanTarget ok, will do.
