### ISSUE TITLE
Question: Set Batch file as Binary image

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#376]
Hi,

because of selenium or iedriver bug (https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/1486) we need so close all IE instances before running a new test case on our windows machines using selenoid.

Currently our browser.json looks like this:
`
{
	"internet explorer": {
		"default": "11",
		"versions": {
			"11": {
				"image": [
					"C:\\Users\\IEUser\\Downloads\\IEDriverServer.exe", "--log-level=DEBUG --log-file=C:\\Users\\IEUser\\Downloads\\IEDriverServer.log"
				]
			}
		}
	}
}
`

Can we just replace the IEDriverServer.exe with a batch file that uses taskkill to kill all instances and after that start IEDriver? Is there something special we need to imeplemnt in the batch file like returning something?
Maybe you have another option?

Regards,
Markus

**Comment by aandryashin** [comment]
Yes, of course. You can use any command.

2018-03-17 13:08 GMT+03:00 Markus Krüger <notifications@github.com>:

**Comment by benzman81** [comment]
No return value or something needed?

**Comment by vania-pooh** [comment]
@benzman81 Selenoid is running everything specified in `browsers.json` as a command. However it's your responsibility to correctly stop the entire process tree when your script finishes.

**Comment by benzman81** [comment]
@vania-pooh so if I put the following command in "image" in browser.json would I need to do something to stop IEDriver, or is it still handled by selenoid?

`"image": [ "taskkill /F /IM iexplore.exe & C:\\Users\\IEUser\\Downloads\\IEDriverServer.exe", "--log-level=DEBUG --log-file=C:\\Users\\IEUser\\Downloads\\IEDriverServer.log" ]`

If I need to close IEDriver, how could I do it after session closes?

**Comment by vania-pooh** [comment]
@benzman81 Selenoid just starts this command and after stopping the session - sends kill signal to the process.

**Comment by benzman81** [comment]
@vania-pooh ok, got it to work, first it didn't but then I looked through the log files and noticed, that the process is receiving a "--port" argument and I did not pass it to the driver. Maybe this should be documented.
