### ISSUE TITLE
Setting Timezone In Chrome Docker Image

### ISSUE THREAD

**Issue by ryanlevell** [aerokube/selenoid#382]
I am testing a website that is crashing when there is no timezone. It started to happen with Chrome 64 and continues with Chrome 65.

From what I could inspect it seems that Chrome returned `undefined` for no timezone in Chrome 63 and below. Starting with Chrome 64 no timezone began throwing a `RangeError: Unsupported time zone specified undefined`.

Although `undefined` is a [valid return value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions) from `Intl.DateTimeFormat().resolvedOptions().timeZone`, I am not sure if it is high enough priority to get fixed anytime soon on the website because no timezone seems to be pretty rare under normal user conditions and it is only happening on a single page.

I also cannot reproduce this locally because I can't figure out how to disable timezones on a Mac.

As a workaround to avoid this issue, I am wondering if it is possible to set the timezone on the selenoid browser containers? Or even just default to UTC.

**Comment by vania-pooh** [comment]
@ryanlevell default Docker timezone is UTC. However Selenoid has this feature: http://aerokube.com/selenoid/latest/#_per_session_time_zone_timezone

**Comment by ryanlevell** [comment]
Thanks I will try that. However I am not sure the default of UTC is working? Below is a screenshot of the timezone when executed through selenium-ui and VNC.

<img width="324" alt="screen shot 2018-03-20 at 9 47 13 am" src="https://user-images.githubusercontent.com/6411462/37720774-fe587392-2cf5-11e8-8c56-e10620624286.png">

**Comment by vania-pooh** [comment]
What we are setting in container when this capability is added is `TZ` environment variable. Need to investigate whether it's passed correctly to Chrome.

**Comment by ostsuper2009** [comment]
I had a same issue with JS Range error: (chrome: 66.0)
I just add capability to capability.setCapability("timeZone", "Europe/London");
It works!

**Comment by vania-pooh** [comment]
@ostsuper2009 btw,  this capability is setting `TZ` variable.

**Comment by vania-pooh** [comment]
Should be working. Feel free to reopen if something does not work.
