### ISSUE TITLE
Multiple sessions per single container

### ISSUE THREAD

**Issue by glisicivan** [aerokube/selenoid#396]
Is it possible to run multiple sessions (multiple tests) per single container?

**Comment by vania-pooh** [comment]
@glisicivan Selenoid has `-limit` flag to set how many parallel containers you can launch. How to run tests in parallel is up to you. Also you can reuse a session between tests if you wish - this is done in the code.

**Comment by glisicivan** [comment]
@vania-pooh , I meant is it possible to run multiple tests (multiple browser sessions) in parallel on single container? Similar like in selenium node containers you can specify max session count to a node.

**Comment by vania-pooh** [comment]
@glisicivan do you mean single browser container or single Selenoid container?

**Comment by glisicivan** [comment]
@vania-pooh, single browser container.

**Comment by vania-pooh** [comment]
@glisicivan you can create one session using your client and then use it in different tests.

**Comment by glisicivan** [comment]
@vania-pooh, I know but then I wouldn't be able to run those tests in parallel. Either way thanks for the prompt reply.
