### ISSUE TITLE
Open Chrome with empty screen

### ISSUE THREAD

**Issue by kenlma** [aerokube/selenoid#406]
ENV info:
OS: Centos 7.3
Kernel: 4.4
Browser: Chrome 65
Selenoid Version: 1.5.3
Run mode: Docker
Docker Version: 17.12.0-ce
VNC: enabled 

Issue:
Sometimes, I see chrome opened but stuck on the empty screen. if I reload the browser manually, Chrome will work again. 
screenshot: 
![image](https://user-images.githubusercontent.com/11968455/38062864-1180417e-32ab-11e8-8161-bff953fa1590.png)

container log:
[log.txt](https://github.com/aerokube/selenoid/files/1858214/log.txt)

**Comment by vania-pooh** [comment]
@kenlma couldn't it be because of missing or slowly loading static resources, e.g. CSS styles, images and so on?

**Comment by kenlma** [comment]
@vania-pooh I wanna to try firefox if still same issue. but i got 500 error
selenoid container log
2018/04/07 00:04:09 [3] [LOCATING_SERVICE] [firefox] []
2018/04/07 00:04:09 [-] [DEFAULT_VERSION] [Using default version: 59.0]
2018/04/07 00:04:09 [3] [USING_DOCKER] [firefox] [59.0]
2018/04/07 00:04:09 [3] [CREATING_CONTAINER] [selenoid/firefox:59.0]
2018/04/07 00:04:09 [3] [STARTING_CONTAINER] [selenoid/firefox:59.0] [34e29e6930ab0a0e9235bcfa26ef038ae696c405254a35e1cc3f7513293dc90b]
2018/04/07 00:04:09 [3] [CONTAINER_STARTED] [selenoid/firefox:59.0] [34e29e6930ab0a0e9235bcfa26ef038ae696c405254a35e1cc3f7513293dc90b] [0.15s]
2018/04/07 00:04:09 [3] [SERVICE_STARTED] [selenoid/firefox:59.0] [34e29e6930ab0a0e9235bcfa26ef038ae696c405254a35e1cc3f7513293dc90b] [0.05s]
2018/04/07 00:04:09 [3] [PROXY_TO] [34e29e6930ab0a0e9235bcfa26ef038ae696c405254a35e1cc3f7513293dc90b] [http://192.168.0.3:4444/wd/hub]
2018/04/07 00:04:09 [3] [SESSION_ATTEMPTED] [http://192.168.0.3:4444/wd/hub] [1]
2018/04/07 00:04:39 [3] [SESSION_FAILED] [http://192.168.0.3:4444/wd/hub] [500 Internal Server Error]
2018/04/07 00:04:39 [3] [REMOVING_CONTAINER] [34e29e6930ab0a0e9235bcfa26ef038ae696c405254a35e1cc3f7513293dc90b]
2018/04/07 00:04:39 [3] [CONTAINER_REMOVED] [34e29e6930ab0a0e9235bcfa26ef038ae696c405254a35e1cc3f7513293dc90b]

and
browser container log
2018/04/07 00:04:09 [-] [NEW_REQUEST] [unknown] [192.168.0.2]
2018/04/07 00:04:09 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.0.2]
2018/04/07 00:04:09 [0] [LOCATING_SERVICE] [firefox] []
2018/04/07 00:04:09 [-] [DEFAULT_VERSION] [Using default version: 59.0]
2018/04/07 00:04:09 [0] [USING_DRIVER] [firefox] [59.0]
2018/04/07 00:04:09 [0] [ALLOCATING_PORT]
2018/04/07 00:04:09 [0] [ALLOCATED_PORT] [32915]
2018/04/07 00:04:09 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --host :: --log debug --port=32915]]
1523059449595   geckodriver     INFO    geckodriver 0.20.0
1523059449595   webdriver::httpapi      DEBUG   Creating routes
1523059449599   geckodriver     ERROR   Address family not supported by protocol (os error 97)

any idea for this exception?

**Comment by vania-pooh** [comment]
Seems to be a bug in CentOS. https://bugs.centos.org/view.php?id=12407

**Comment by kenlma** [comment]
@vania-pooh downgrade to 7.2. no issue any more

**Comment by vania-pooh** [comment]
@kenlma great. 👍
