### ISSUE TITLE
can not start selenoid on Linux

### ISSUE THREAD

**Issue by liulirun** [aerokube/selenoid#413]
OS: Linux Ubuntu

browsers.json file is under /home/griduser/config

> {
>     "chrome": {
>         "default": "65.0",
>         "versions": {
>             "65.0": {
>                 "image": "selenoid/chrome:65.0",
>                 "port": "4444",
>                 "path": "/",
> 				"tmpfs": {"/tmp": "size=512m", "/var": "size=128m"},
> 				"env" : ["SCREEN_RESOLUTION=1600x1380x24"]
>             }
>         }
>     }
> }

when I use cmd to start docker: `docker run -d --name selenoid -e DOCKER_API_VERSION=1.35 -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /home/griduser/:/etc/selenoid/:ro aerokube/selenoid:latest-release -conf /home/griduser/config/browsers.json -limit 6 -retry-count 3 -session-attempt-timeout 1800s -session-delete-timeout 1800s`

I got this error:
2018/04/05 16:15:02 [-] [INIT] [Loading configuration files...]
2018/04/05 16:15:02 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /home/griduser/config/browsers.json: no such file or directory]

docker inspect returns: 
> [
>     {
>         "Id": "f321d3f70be719b365a17ec4ca13c901429fe4bf6c74d8b5fc82100eb3ebab7b",
>         "Created": "2018-04-05T16:15:01.86618228Z",
>         "Path": "/usr/bin/selenoid",
>         "Args": [
>             "-conf",
>             "/home/griduser/config/browsers.json",
>             "-limit",
>             "6",
>             "-retry-count",
>             "3",
>             "-session-attempt-timeout",
>             "1800s",
>             "-session-delete-timeout",
>             "1800s"
>         ],
>         "State": {
>             "Status": "exited",
>             "Running": false,
>             "Paused": false,
>             "Restarting": false,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 0,
>             "ExitCode": 1,
>             "Error": "",
>             "StartedAt": "2018-04-05T16:15:02.318781254Z",
>             "FinishedAt": "2018-04-05T16:15:02.365444135Z"
>         },
>         "Image": "sha256:e6dc703c1a3939c714f1426526f34291eb1a04ea8d7a19e17d695c087247f2ca",
>         "ResolvConfPath": "/var/lib/docker/containers/f321d3f70be719b365a17ec4ca13c901429fe4bf6c74d8b5fc82100eb3ebab7b/resolv.conf",
>         "HostnamePath": "/var/lib/docker/containers/f321d3f70be719b365a17ec4ca13c901429fe4bf6c74d8b5fc82100eb3ebab7b/hostname",
>         "HostsPath": "/var/lib/docker/containers/f321d3f70be719b365a17ec4ca13c901429fe4bf6c74d8b5fc82100eb3ebab7b/hosts",
>         "LogPath": "/var/lib/docker/containers/f321d3f70be719b365a17ec4ca13c901429fe4bf6c74d8b5fc82100eb3ebab7b/f321d3f70be719b365a17ec4ca13c901429fe4bf6c74d8b5fc82100eb3ebab7b-json.log",
>         "Name": "/selenoid",
>         "RestartCount": 0,
>         "Driver": "overlay2",
>         "Platform": "linux",
>         "MountLabel": "",
>         "ProcessLabel": "",
>         "AppArmorProfile": "docker-default",
>         "ExecIDs": null,
>         "HostConfig": {
>             "Binds": [
>                 "/home/griduser/:/etc/selenoid/:ro",
>                 "/var/run/docker.sock:/var/run/docker.sock"
>             ],
>             "ContainerIDFile": "",
>             "LogConfig": {
>                 "Type": "json-file",
>                 "Config": {}
>             },
>             "NetworkMode": "default",
>             "PortBindings": {
>                 "4444/tcp": [
>                     {
>                         "HostIp": "",
>                         "HostPort": "4444"
>                     }
>                 ]
>             },
>             "RestartPolicy": {
>                 "Name": "no",
>                 "MaximumRetryCount": 0
>             },
>             "AutoRemove": false,
>             "VolumeDriver": "",
>             "VolumesFrom": null,
>             "CapAdd": null,
>             "CapDrop": null,
>             "Dns": [],
>             "DnsOptions": [],
>             "DnsSearch": [],
>             "ExtraHosts": null,
>             "GroupAdd": null,
>             "IpcMode": "shareable",
>             "Cgroup": "",
>             "Links": null,
>             "OomScoreAdj": 0,
>             "PidMode": "",
>             "Privileged": false,
>             "PublishAllPorts": false,
>             "ReadonlyRootfs": false,
>             "SecurityOpt": null,
>             "UTSMode": "",
>             "UsernsMode": "",
>             "ShmSize": 67108864,
>             "Runtime": "runc",
>             "ConsoleSize": [
>                 0,
>                 0
>             ],
>             "Isolation": "",
>             "CpuShares": 0,
>             "Memory": 0,
>             "NanoCpus": 0,
>             "CgroupParent": "",
>             "BlkioWeight": 0,
>             "BlkioWeightDevice": [],
>             "BlkioDeviceReadBps": null,
>             "BlkioDeviceWriteBps": null,
>             "BlkioDeviceReadIOps": null,
>             "BlkioDeviceWriteIOps": null,
>             "CpuPeriod": 0,
>             "CpuQuota": 0,
>             "CpuRealtimePeriod": 0,
>             "CpuRealtimeRuntime": 0,
>             "CpusetCpus": "",
>             "CpusetMems": "",
>             "Devices": [],
>             "DeviceCgroupRules": null,
>             "DiskQuota": 0,
>             "KernelMemory": 0,
>             "MemoryReservation": 0,
>             "MemorySwap": 0,
>             "MemorySwappiness": null,
>             "OomKillDisable": false,
>             "PidsLimit": 0,
>             "Ulimits": null,
>             "CpuCount": 0,
>             "CpuPercent": 0,
>             "IOMaximumIOps": 0,
>             "IOMaximumBandwidth": 0
>         },
>         "GraphDriver": {
>             "Data": {
>                 "LowerDir": "/var/lib/docker/overlay2/c61bf46df7b596403f153b2c7ae548e9abbfbc65229bb8444c5b9bf9ef3eda0d-init/diff:/var/lib/docker/overlay2/73f4a9f745c4ae78fa178c2f390259cf8c9bfb8d0283b8b31ea3ae6d9432d448/diff:/var/lib/docker/overlay2/f238df36136d12a8c80570b97bc6362362b88c865c4e1382b8ef008a2e55adec/diff:/var/lib/docker/overlay2/c908043de8733a8171e1d3ffaeed3a470df63bbeeb9bb15d5ecc8fbc84453f38/diff",
>                 "MergedDir": "/var/lib/docker/overlay2/c61bf46df7b596403f153b2c7ae548e9abbfbc65229bb8444c5b9bf9ef3eda0d/merged",
>                 "UpperDir": "/var/lib/docker/overlay2/c61bf46df7b596403f153b2c7ae548e9abbfbc65229bb8444c5b9bf9ef3eda0d/diff",
>                 "WorkDir": "/var/lib/docker/overlay2/c61bf46df7b596403f153b2c7ae548e9abbfbc65229bb8444c5b9bf9ef3eda0d/work"
>             },
>             "Name": "overlay2"
>         },
>         "Mounts": [
>             {
>                 "Type": "bind",
>                 "Source": "/var/run/docker.sock",
>                 "Destination": "/var/run/docker.sock",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": "rprivate"
>             },
>             {
>                 "Type": "bind",
>                 "Source": "/home/griduser",
>                 "Destination": "/etc/selenoid",
>                 "Mode": "ro",
>                 "RW": false,
>                 "Propagation": "rprivate"
>             }
>         ],
>         "Config": {
>             "Hostname": "f321d3f70be7",
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": false,
>             "AttachStdout": false,
>             "AttachStderr": false,
>             "ExposedPorts": {
>                 "4444/tcp": {}
>             },
>             "Tty": false,
>             "OpenStdin": false,
>             "StdinOnce": false,
>             "Env": [
>                 "DOCKER_API_VERSION=1.35",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
>             ],
>             "Cmd": [
>                 "-conf",
>                 "/home/griduser/config/browsers.json",
>                 "-limit",
>                 "6",
>                 "-retry-count",
>                 "3",
>                 "-session-attempt-timeout",
>                 "1800s",
>                 "-session-delete-timeout",
>                 "1800s"
>             ],
>             "Image": "aerokube/selenoid:latest-release",
>             "Volumes": null,
>             "WorkingDir": "",
>             "Entrypoint": [
>                 "/usr/bin/selenoid"
>             ],
>             "OnBuild": null,
>             "Labels": {}
>         },
>         "NetworkSettings": {
>             "Bridge": "",
>             "SandboxID": "8ee9b6a716e8a6f876d136ced4e3aa3ca944f8859ab1159fe40f5d36c84fb812",
>             "HairpinMode": false,
>             "LinkLocalIPv6Address": "",
>             "LinkLocalIPv6PrefixLen": 0,
>             "Ports": {},
>             "SandboxKey": "/var/run/docker/netns/8ee9b6a716e8",
>             "SecondaryIPAddresses": null,
>             "SecondaryIPv6Addresses": null,
>             "EndpointID": "",
>             "Gateway": "",
>             "GlobalIPv6Address": "",
>             "GlobalIPv6PrefixLen": 0,
>             "IPAddress": "",
>             "IPPrefixLen": 0,
>             "IPv6Gateway": "",
>             "MacAddress": "",
>             "Networks": {
>                 "bridge": {
>                     "IPAMConfig": null,
>                     "Links": null,
>                     "Aliases": null,
>                     "NetworkID": "bdcbabadac3ffd433d3326ca56c74336a806c1c7e08cd3d2da25d3b2dbc16581",
>                     "EndpointID": "",
>                     "Gateway": "",
>                     "IPAddress": "",
>                     "IPPrefixLen": 0,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": "",
>                     "DriverOpts": null
>                 }
>             }
>         }
>     }
> ]
> 
> 

I am almost certain it caused by some config in my machine, but did not find the correct logs for it.   ` [/usr/bin/selenoid: browsers config: read error: open /home/griduser/config/browsers.json: no such file or directory]` is too ambigious

Please help

btw, if I use cm to start, it starts correctly : ./cm selenoid start --vnc --config-dir /home/griduser/config/ --args "-limit 6 -retry-count 3 -session-attempt-timeout 1800s -timeout 2m"

**Comment by vania-pooh** [comment]
@liulirun you are incorrectly specifying `-conf` parameter. Should be `/etc/selenoid/browsers.json` because `/home/griduser` is on the host machine (outside of container).

**Comment by liulirun** [comment]
it works, close this bug
