### ISSUE TITLE
HTMLUnitDriver support

### ISSUE THREAD

**Issue by slopy** [aerokube/selenoid#427]
Hello, 
Thanks for selenoid!
I would like to know if it's possible to use HTMLUnitDriver?

Regards.

**Comment by vania-pooh** [comment]
@slopy euh, so far as I know it was deprecated years ago. What's the purpose of that?

**Comment by slopy** [comment]
@vania-pooh not sure but seems like not deprecated http://htmlunit.sourceforge.net/changes-report.html . Well it's lightweight.

**Comment by leorush** [comment]
@slopy why don't you use it directly?

**Comment by slopy** [comment]
@leorush what do you mean by use it directly? The idea is to have selenoid grid under one url and have connection distributed properly.

Our selenium network have grown a little from time of my last comment. 
Now we have:
3 servers under load balancer, on each there are 1 selenoid (for chrome and FF with limit of connections 45) + 3 selenium-standalone ( for htmlunit with limit of 15 for each ) + ggr + selenoid-ui + ggr-ui
This is working quite well, however I see few things missing and maybe you guys can help with those. (I'm not sure if I should put this topic here as this is related to other services you have built)  
- ggr-ui is pointing to selenoid-ui and this is working fine, but there are stats for selenoids only. I'm wondering if there is any way we could grab stats also from selenium-standalone servers? 
- display stats for selenoids in the network but is it possible to make stats separated by IPs? - just to know if distribution so fine

Once again thanks for brilliant tools you are building!

**Comment by vania-pooh** [comment]
Summon @aandryashin.

**Comment by leorush** [comment]
@slopy i mean that it seems that there is no need for selenoid to run parallel tests on HTMLUnit.

**Comment by vania-pooh** [comment]
@slopy we did some investigation. It seems that any Selenium server standalone image has HTMLUnit included. Do you need more instructions on how to build such image?

**Comment by slopy** [comment]
Yep, true that selenium-standalone has HtmlUnit and we are using it. We have host in quota file pointing to selenium-standalone (and it is working) however would be nice to simply set proper image in browsers.json. That way all stats will be in one place and no need for additional dependencies.

@vania-pooh do you mean like create proper docker image?

**Comment by vania-pooh** [comment]
@slopy I mean create \ find an image with `java -jar selenium-server-standalone.jar` as an entrypoint and then specify it in `browsers.json`.

**Comment by slopy** [comment]
@vania-pooh I have docker-compose.yml to manage services on each server and I'm using this image there so will try this solutions - sounds promising. Thanks a lot!
Will update with results!

**Comment by slopy** [comment]
And it works.
Dockerfile 
```
FROM selenium/base
CMD java -jar /opt/selenium/selenium-server-standalone.jar
```
browsers.json
```
    "htmlunit": {
        "default": "2.30",
        "versions": {
            "2.30": {
                "image": "selenium_image:latest",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
```

Once again thanks a lot for help.

**Comment by slopy** [comment]
TBH I have not published this image - it's on machine. 
When it will go public I will try to remember to get back to this topic.

**Comment by vania-pooh** [comment]
@slopy any progress on this or closing?
