### ISSUE TITLE
Chrome container don't deleted if test was failed

### ISSUE THREAD

**Issue by senin24** [aerokube/selenoid#43]
log in container selenoid/chrome:latest

```
[305.992][SEVERE]: Timed out receiving message from renderer: 299.331
[305.993][INFO]: Timed out. Stopping navigation...
[305.993][DEBUG]: DEVTOOLS COMMAND Runtime.evaluate (id=31) {
   "expression": "window.stop();",
   "returnByValue": true
}
[305.997][DEBUG]: DEVTOOLS EVENT Page.frameStoppedLoading {
   "frameId": "104.1"
}
[305.997][DEBUG]: DEVTOOLS RESPONSE Runtime.evaluate (id=31) {
   "result": {
      "type": "undefined"
   }
}
[305.997][DEBUG]: DEVTOOLS COMMAND Runtime.evaluate (id=32) {
   "expression": "1"
}
[305.997][SEVERE]: Timed out receiving message from renderer: -0.006
[305.998][INFO]: Done waiting for pending navigations. Status: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.006
[305.998][INFO]: RESPONSE Navigate timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.006
  (Session info: chrome=56.0.2924.87)
```

my file browser.json:
```
{
  "firefox": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/firefox:latest",
        "port": "4444"
      }
    }
  },
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/chrome:latest",
        "port": "4444"
      }
    }
  }
}
```

2f21c1fae754 - faild container
Lines from log in aandryashin/selenoid:latest which consist text "2f21c1fae754":
```
2017/04/10 08:26:17 [CONTAINER_STARTED]
[2f21c1fae754985be1d061e5fb05a3033e8cb0508df4ee4241783962d01e3c49] [458.85045ms]
2017/04/10 08:26:18 [SERVICE_STARTED] [2f21c1fae754985be1d061e5fb05a3033e8cb0508df4ee4241783962d01e3c49] [665.877333ms]
```
and dont exist [CONTAINER_REMOVED]

**Comment by vania-pooh** [comment]
@senin24 could you please add more details about your Docker environment:
* Are you using local Docker via socket or some remote Docker API?
* What is your Docker version \ Docker API version?

**Comment by senin24** [comment]
- using local Docker (docker-host - VM on VirtualBox, OS - Ubuntu 16.04). 
- Docker version 17.03.0-ce, build 60ccb22

I got similar problem - run on docker-host to much containers (in my case more than 20-30 containers at host with 8 Gb RAM) and so you will see that some containers still runing after when test was failed and finished. In which case selenoid finish job with error in log "panic: send on closed channel".
I re-run docker with selenoid, but old containers with browser still working. And I can't see problem inside this containers and it logs.

May be needing some functional at selenoid which can stop and delete all containers at host except selenoid and selenoid-ui.

**Comment by vania-pooh** [comment]
@senin24 our experience shows that optimal number of containers depending on usage pattern is something like ```num_cores x 1.5-2```. Does the panic reproduce on release 1.1.0 we created today?

**Comment by senin24** [comment]
yes, I used about 4 hours ago "aandryashin/selenoid:latest"
and I used more than 20 containers on 4 cores ))
But in my case tests very simply.
I think this recommended pattern (number containers = num_cores x 1.5-2) will be very useful added in Readme ;)

**Comment by vania-pooh** [comment]
> I think this recommended pattern (number containers = num_cores x 1.5-2) will be very useful added in Readme ;)

Done. https://github.com/aandryashin/selenoid/blob/master/README.md#simultaneously-running-containers

**Comment by vania-pooh** [comment]
@senin24 anyway we'll look at the issue today.

**Comment by vania-pooh** [comment]
@senin24 I missed that you also get panic in Selenoid. Could you provide the stacktrace?

**Comment by vania-pooh** [comment]
@senin24 currently we consider that this is an issue in Chrome container. Will fix soon. You may want to try with older browser versions.

**Comment by vania-pooh** [comment]
@senin24 added containers for Chrome 56 and 57. Should work faster and seems to be an issue in Chrome. Could you check if it helps?

**Comment by vania-pooh** [comment]
Fixed container removal issues. https://github.com/aerokube/selenoid/issues/56
