### ISSUE TITLE
Reload Configuration for Windows

### ISSUE THREAD

**Issue by da-yaroslav-orel** [aerokube/selenoid#434]
It would be great if Selenoid could have reload configuration feature for Windows also as well as for Unix platforms. Something like "kill -HUP <pid>"

**Comment by vania-pooh** [comment]
@da-yaroslav-orel any ideas what could it be?

**Comment by yaroslav-orel** [comment]
@vania-pooh I guess it could be some kind of api request like POST /config/reload if there's no way to do it using terminal

**Comment by vania-pooh** [comment]
@da-yaroslav-orel providing an API is insecure because Selenoid has no authentication. In that case anybody can reload configuration.

**Comment by yaroslav-orel** [comment]
@vania-pooh well it seems there's no harm in reloading configs if no one else has access to config folder except owner user. In that case selenoid will just pick up the same file it has loaded at the start-up.

**Comment by aandryashin** [comment]
it could be implemented only for windows, because it does not have
signals...

2018-05-16 7:42 GMT+03:00 yaroslav-orel <notifications@github.com>:

**Comment by vania-pooh** [comment]
Makes no sense anymore as Windows browsers could also be packed to Docker containers. medium.com/@aandryashin/selenium-on-windows-docker-revolution-f5a7eab205ad
