### ISSUE TITLE
Problem adding browser image to selenoid-ui

### ISSUE THREAD

**Issue by MegganKate** [aerokube/selenoid#441]
Good Day, 

I'm currently having an issue with adding a browser option for testing. I've downloaded boot2docker and have successfully added the containers for selenoid and selenoid-ui. All of the latests browser versions are available in the browser dropdown supplied for chrome, firefox and opera. I'm running my tests using protractor and there is currently an issue running them in the latest version of firefox. To avoid the problem I'd like to 'downgrade' the firefox version to 58 or 57 (not the current 59 and 60 which are the latest ones available). I pulled the versions of firefox that I want using # docker pull selenoid/vnc:firefox_58.0 and the firefox image is added to my list of images. I'm not sure what to do after that. My apologies if I have missed something simple, this browser is not available in the list of browsers inside selenoid-ui. I'm just uncertain of the steps to take to get it there. Any assistance would be greatly appreciated.

**Comment by vania-pooh** [comment]
@MegganKate just restart Selenoid:
```
$ docker restart selenoid
```
or reload its configuration:
```
$ docker kill -s HUP selenoid
```
Then refresh UI page - it should show new browser.

**Comment by MegganKate** [comment]
@vania-pooh 

I did as instructed and the only firefox versions that display are 59 and 60 unfortunately

**Comment by vania-pooh** [comment]
@MegganKate make sure you are editing correct `browsers.json`. When installed with `cm` file location is usually: `~/.aerokube/selenoid/browsers.json`.

**Comment by MegganKate** [comment]
I had made no changes to the browser.json file. I've now edited it to include

 "firefox": {
        "default": "58.0",
        "versions": {
            "58.0": {
                "image": [
                    "path to geckodriver",
                    "--host",
                    "127.0.0.1",
                    "--log",
                    "debug"
                ],
                "port": "",
                "path": "/"
            }
        }
    } 

then restarted selenoid, reloaded it's configuration and refreshed the UI page. 59 and 60 are still my only available options.

**Comment by vania-pooh** [comment]
@MegganKate what you are showing is JSON syntax to start a standalone Geckodriver as a process instead of using all-in-one Docker containers (`image` should be Docker image reference, e.g. `selenoid/vnc:firefox_58.0`). So I think there should be another path where the real `browsers.json` is stored. You can check where it is by inspecting Selenoid container via `docker inspect selenoid`.

**Comment by MegganKate** [comment]
When I docker inspect selenoid it has the location as /etc/selenoid/browsers.json. If I cd to /etc no selenoid file exists. I tried ls -a to list all hidden files, but the selenoid file doesn't seem to exist there. I also can't cd directly into the browsers.json file.

**Comment by vania-pooh** [comment]
@MegganKate this path is inside Docker container. If you do the following:
```
$ docker exec -it selenoid bash
```
You will be able to see `/etc/selenoid/browsers.json`. If you take a look at `Binds` section in `docker inspect selenoid` you will see the real path on the host machine where config file resides.

**Comment by MegganKate** [comment]
@vania-pooh It's working perfectly now thank you so much for all your help :)

**Comment by vania-pooh** [comment]
@MegganKate feel free to close the issue if resolved.
