### ISSUE TITLE
Homepage not accessible when using McAfee

### ISSUE THREAD

**Issue by presidenten** [aerokube/selenoid#442]
When trying to access [https://aerokube.com/selenoid/latest/](https://aerokube.com/selenoid/latest/) McAfee warns for Spyware/Adware/Keyloggers.

![image](https://user-images.githubusercontent.com/3883897/40420591-1bec1016-5e89-11e8-9016-b5b95c5bd228.png)

Can you check if you have been hacked and someone has snuck in a malicious script on your homepage?

**Comment by vania-pooh** [comment]
@presidenten the only script we have on the page is https://metrica.yandex.com. That's an equivalent of Google Analytics. All the rest is static HTML. If you wish you can completely turn off the scripts on the page.

**Comment by presidenten** [comment]
Yeah, Im viewing it from a virtual machine now. So I can actually view it.
Just thought I should let you guys know that McAfee blocks it for some reason.

**Comment by vania-pooh** [comment]
@presidenten that's funny because all pages have just the same script.
