### ISSUE TITLE
Ability to start containers from CRIU snapshot

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#451]
We need to be able to specify [checkpoint](https://github.com/checkpoint-restore/criu) name and start browser container from this checkpoint. Something like this:
```
"46.0": {                                    
          "image": "selenoid/firefox:46.0",          
          "port": "4444",                            
          "checkpoint": "my-checkpoint"
        },
```

**Comment by leorush** [comment]
As a plus killer-feature, there will be nice to have an ability to create CRIU checkpoint at any time, by sending a command to Selenoid.
I think it will be a lot easier to debug with browser container restored to a checkpoint, and VNC )
