### ISSUE TITLE
selenoid exits in panic while running

### ISSUE THREAD

**Issue by oskarmurand** [aerokube/selenoid#46]
Running selenoid with default of 5 images or limit 10 using chromebrowser always exits with a panic.

This happens when directing my tests against selenoid directly bypassing ggr.

I've used the setup provided by another user:

```
docker run -d --name selenoid -p 4445:4444 -v /private/etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aandryashin/selenoid:latest -limit 10
ip=`docker inspect --format {{.NetworkSettings.IPAddress}} selenoid`
xml ed --inplace -u '//host/@name' -v "$ip" /etc/grid-router/quota/test.xml
docker run -d --name ggr -p 4444:4444 -v /private/etc/grid-router/:/etc/grid-router:ro aandryashin/ggr:latest
```

The error:
```
2017/04/11 11:35:58 [SESSION_CREATED] [107178798f7afca475e3d7866ff76c54] [http://172.17.0.1:32817]
2017/04/11 11:35:58 [SESSION_CREATED] [1323325895d1276f25a92593122bb40d] [http://172.17.0.1:32818]
2017/04/11 11:35:58 [SESSION_CREATED] [4b47890c76cd26751c3d147625a1a65b] [http://172.17.0.1:32819]
panic: close of closed channel

goroutine 4286 [running]:
main.proxy.func1.3(0xc4202d6500)
	/home/travis/gopath/src/github.com/aandryashin/selenoid/selenoid.go:181 +0x1d6
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc420391f70, 0x85d280, 0xc420404000, 0xc4202d6300)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/httputil/reverseproxy.go:159 +0x1be
main.proxy.func1(0xc4204ea780, 0x85d280, 0xc420404000, 0xc4202d6300)
	/home/travis/gopath/src/github.com/aandryashin/selenoid/selenoid.go:196 +0x117
created by main.proxy
	/home/travis/gopath/src/github.com/aandryashin/selenoid/selenoid.go:197 +0x7f
```

browsers.json:
```
{
  "chrome": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": "selenoid/chrome:latest",
        "port": "4444"
      }
    }
  }
}
```

**Comment by vania-pooh** [comment]
@oskarmurand does this reproduce with latest release (1.1.0), i.e. ```aandryashin/selenoid:1.1.0```?

**Comment by aandryashin** [comment]
I found possible issue, It will be fixed soon. Thank for report.

2017-04-11 15:47 GMT+03:00 Ivan Krutov <notifications@github.com>:

**Comment by aandryashin** [comment]
The issue should be fixed in this commit 4ca48cb13c6bc3c3c75c036a1139cc70b69d8ca7. Please check it with aandryashin/selenoid:latest image.

**Comment by vania-pooh** [comment]
@oskarmurand any updates?

**Comment by oskarmurand** [comment]
Same results unfortunately.

**Comment by vania-pooh** [comment]
@oskarmurand just to clarify, are you using ```aandryashin/selenoid:latest```?

**Comment by oskarmurand** [comment]
@vania-pooh yep, this is the command:
`docker run -d --name selenoid -p 4445:4444 -v /Users/oskar/selenium/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aandryashin/selenoid:latest`

**Comment by aandryashin** [comment]
Please try to delete and pull image again, may be some cache issues. I have
added session synchronization to avoid duplicated close.

2017-04-13 17:59 GMT+03:00 Oskar Murand <notifications@github.com>:

**Comment by vania-pooh** [comment]
@oskarmurand still can't reproduce. Just did new Selenoid release 1.1.1. Could you try with it?
```aerokube/selenoid:1.1.1```

**Comment by oskarmurand** [comment]
Seemingly the issue is resolved now, running >30 tests 4 at a time, no panics. All chromedriver containers were stopped as the tests finished with them.

**Comment by vania-pooh** [comment]
@oskarmurand thank you.
