### ISSUE TITLE
container can't fully access internal site

### ISSUE THREAD

**Issue by ed84** [aerokube/selenoid#462]
I have created a new hyper-v vm using Ubuntu 18.04. I've installed docker, and pulled the images for selenoid/selenoid-ui,ggr and created a docker-compose file. We currently have an internal firewall, so I installed the certificate onto the ubuntu vm. When I open Firefox inside of Ubuntu, I can access all of our internal websites. However, when I execute a test through selenoid/ggr, it can access some of the sites but I get the following error on chrome when it tries to navigate to one of our other internal sites: internaldomainx.com's server IP address could not be found.

err_name_not_resolved

Try:
- Checking the connection
- Checking the proxy, firewall, and DNS configuration.

Even though I can access all of our internal sites from the Ubuntu vm, I tried adding the DNS servers to the docker-compose file but still it breaks.

please advise

**Comment by aandryashin** [comment]
You have to configure docker daemon and pass to it dns list via --dns
option or daemon.json, please refer to docker docs:

https://docs.docker.com/engine/reference/commandline/dockerd/

2018-06-06 20:45 GMT+03:00 ed84 <notifications@github.com>:

**Comment by ed84** [comment]
thank you sir!

**Comment by Lucifar2** [comment]
@ed84 Were you able to resolve this issue ? I know its been long time but I am facing the same issue. 
Could you guide me as well. Thanks
