### ISSUE TITLE
Selenoid restarting in docker for windows

### ISSUE THREAD

**Issue by MegganKate** [aerokube/selenoid#469]
I'm currently trying to start a selenoid container using docker for windows with Windows 10 Pro. I seem to be having the exact same problem mentioned in #155, where selenoid is stuck in a restarting state. 

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root aerokube/cm:latest-release selenoid start --vnc --tmpfs 128` is the command I run in powershell to start the selenoid container. When I inspect the logs the issue is the same as the one mentioned in #155 :read error: open etc/selenoid/browsers.json: no such file or directory. 

I'm using the latest cm and selenoid images.

**Comment by vania-pooh** [comment]
@MegganKate take a look at `docker inspect selenoid` and find `Binds` section. There should be a mount of host machine directory with `browsers.json` to `/etc/selenoid/`. Make sure `browsers.json` exists in specified dir.

**Comment by MegganKate** [comment]
@vania-pooh thanks for your quick response. the `Binds` section contains 

```
 "/root/.aerokube/selenoid:/etc/selenoid:ro",
 "/root/.aerokube/selenoid/video:/opt/selenoid/video",
 "//var/run/docker.sock:/var/run/docker.sock"
```
but no `browsers.json`. I can access the `browsers.json `file inside `.aerokube/selenoid/browsers.json` and it seems to have the correct content for browsers.

**Comment by vania-pooh** [comment]
@MegganKate Seems to be permissions issue then. And also you are using Docker Toolbox for Windows. In that case the last bind should be:
```
/var/run/docker.sock:/var/run/docker.sock # without the double slash
```

**Comment by MegganKate** [comment]
@vania-pooh I'm not currently using the docker toolbox for windows, I have Docker for Windows installed and am using PowerShell in combination. 
I downloaded it from https://docs.docker.com/docker-for-windows/. 

I'm not sure I understand correctly, I thought docker toolbox for windows was for older versions of windows, and so I have not used it. I'm still learning how to use docker and selenoid so I apologize if the problem is simple and I'm not understanding. Is there a different command I am meant to be using to start selenoid using docker for windows?

**Comment by vania-pooh** [comment]
@MegganKate could you check what's in `Cmd` section. The following erorr message is suspicious:
```
open etc/selenoid/browsers.json: no such file or directory
```
Normally path should start with `/`, e.g. `/etc/selenoid/browsers.json`.

**Comment by MegganKate** [comment]
when I try to `cd` to `/etc` the error returned in powershell is `the path "C:\etc" cannot be found because it does not exist`

**Comment by vania-pooh** [comment]
@MegganKate I think correct mount in Windows should be something like:
```
/c/Users/<user>/.aerokube/selenoid:/etc/selenoid:ro
```
And the same stuff for video.

**Comment by vania-pooh** [comment]
@MegganKate did it help?

**Comment by MegganKate** [comment]
@vania-pooh Hey :) unfortunately not. I changed to use Docker Toolbox to run it and that worked fine. Thanks for your help

**Comment by vania-pooh** [comment]
@MegganKate ok, closing then.

**Comment by mpanin** [comment]
I'm having exactly the same issue, is there is a way to fix it? I mean without using Docker Toolbox obviously

**Comment by mpanin** [comment]
@vania-pooh 
It looks like this:

```
2018/12/11 01:51:50 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]

2018/12/11 01:52:51 [-] [INIT] [Loading configuration files...]

2018/12/11 01:52:51 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]

2018/12/11 01:53:52 [-] [INIT] [Loading configuration files...]

2018/12/11 01:53:52 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
```

**Comment by vania-pooh** [comment]
@mpanin `browsers.json` is incorrectly mounted inside Selenoid container.

**Comment by mpanin** [comment]
@vania-pooh any ideas on how could I fix that?

**Comment by vania-pooh** [comment]
@mpanin make sure that volumes are mounted like `-v /some/dir:/etc/selenoid` and this `/some/dir` contains `browsers.json`.

**Comment by manikesh** [comment]
@vania-pooh  I am facing same issue since last 3 days. not sure how to get in.. I tried to setup in same way as you gave but still giving error.. 

docker run -d --name sd -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock -v /c/selenoid/config/browsers.json:etc/selenoid/:ro xxxxxxxx

**Comment by vania-pooh** [comment]
@manikesh just yesterday one of our support channel participants faced the same issue. Not sure why but was fixed by reinstalling Docker.

**Comment by manikesh** [comment]
@vania-pooh   had done already today when every thing else failed.. try one more time.. have read every article about this available on google but not getting help..

**Comment by manikesh** [comment]
I used docker toolbox, this took me to the actual VM, there I created folder /etc/selenoid and copied browsers.json to it.. post this I was able to run container without any issue.. is that right step to do ?

**Comment by vania-pooh** [comment]
@manikesh yep.

**Comment by manikesh** [comment]
basically I deployed, selenoid and selenoid-UI on my local docker containers... now I have a test case where I need to spin off new container on different browser hitting selenoid hub locally.. but I am not able to access it outside of container... when hitting on browser or  passing in below code snippet ..
how to access that running hub outside of containers.. 
@Test
    public void launchTestDocsInChrome() throws MalformedURLException {
        WebDriver driver = new DriverManager().getDriver("chrome");
        driver.get("http://192.168.205.101/");
        log.info("Page Title: "+driver.getTitle());
        driver.quit();
    }

**Comment by vania-pooh** [comment]
@manikesh either use Docker links or run containers in custom Docker network and use their names as domain names.

**Comment by manikesh** [comment]
any supporting wiki as not aware about any of these... thanks in advance.

**Comment by vania-pooh** [comment]
E.g. https://runnable.com/docker/basic-docker-networking

**Comment by manikesh** [comment]
I solved the issue related to browsers.json file not found, that too without using tool box.
basically I used below command, please note the bold text, on docker container, our C:/Users is readable, so we have to make sure we keep browsers.json filer under this and it can be easily mounted to /etc/selenoid which docker access to read the file.

in my case, I copied selenoid folder under path "c:/User/manikesh" and gave same location as "/c/User/manikesh/selenoid/config", please note the syntax here.

docker run -d --name selenoid  -v //var/run/docker.sock:/var/run/docker.sock -v **/c/Users/manikesh/selenoid/config:/etc/selenoid/:ro** registry-na.cntr.gaia.jpmchase.net/vendors/selenoid:1.7.2


this works like charm.

**Comment by manikesh** [comment]
> @manikesh either use Docker links or run containers in custom Docker network and use their names as domain names.

This magically worked for me, all I did is just deleted everything and started fresh... not sure what was the issue.. this is really bad when we dont know how issue got resolved.. :)

**Comment by Sree9120** [comment]
Follow these steps also
1.stop and remove the container where selenoid is running (docker container stop <>,docker container rm <>)
2.Navigate to cm_windows_amd64.exe in cmd and type selenoid cleanup
3. Run in powershell > docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start
4.If it says still failed try running ----.\cm_windows_amd64.exe selenoid start --vnc --browsers "chrome:75.0" --force.

It should help :-)

**Comment by sonamqaautomation** [comment]
Create this docker-compose.yml file and it is working fine:-
version: '3'
services:
  selenoid:
   network_mode: bridge
   image: aerokube/selenoid
   volumes:
     - "/C/Users/sonam/Documents/newselenoid:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/C/Users/sonam/Documents/newselenoid/video:/opt/selenoid/video"
   environment:
     - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/sonam/Documents/newselenoid/video
     - TZ=Europe/Amsterdam
   command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
   ports:
     - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

**Comment by HetalRamani2** [comment]
@sonamqaautomation yes, the above .yml works great. Thanks
