### ISSUE TITLE
How I can add ssl self sign ssl certificate to chrome when running seleniod on docker 

### ISSUE THREAD

**Issue by saiedtrife** [aerokube/selenoid#472]
I have self signed ssl certificate which its installed on my chrome driver 
When open the website that is using the certificate I get 
`403 Forbidden `
of course because the certificate is not installed on the browser  

is there someway that we can pull chrome profile or add the certificate (using curl for instance with selenoid)

**Comment by aandryashin** [comment]
Try to create session with custom profile that contains installed cert,
more about here:
https://seleniummonk.blogspot.com/p/how-to-handle-ssl-cerificates.html?m=1

пт, 6 июл. 2018 г., 18:46 saiedtrife <notifications@github.com>:

**Comment by vania-pooh** [comment]
@saiedtrife did it help? Can we close the issue?
