### ISSUE TITLE
Protractor unable to start a webdriver session

### ISSUE THREAD

**Issue by bhoppeadoy** [aerokube/selenoid#473]
I have the latest selenoid and selenoid-ui installed with docker. From the UI interface I have green lights for SSE and SELENOID.

I have protractor config using the selenoid server:
seleniumAddress: 'http://10.180.168.192:4444/wd/hub',

When I run protractor, I get an error that WebDriver from the newly started container didn't respond. From docker I can see the new container started up.

$ protractor e2e/protractor.conf.js
(node:16928) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:47:04] I/launcher - Running 1 instances of WebDriver
[16:47:04] I/hosted - Using the selenium server at http://10.180.168.192:4444/wd/hub
[16:47:34] E/runner - Unable to start a WebDriver session.
(node:16928) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: wait: http://192.168.196.4:4444/ does not respond in 30s
(node:16928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[16:47:34] E/launcher - Error: WebDriverError: wait: http://192.168.196.4:4444/ does not respond in 30s
    at Object.checkLegacyResponse (C:\Users\me\repos\wbhtml5\power-designer\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\me\repos\wbhtml5\power-designer\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\me\me\repos\wbhtml5\power-designer\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[16:47:34] E/launcher - Process exited with error code 100
error Command failed with exit code 100.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Anyone able to get protractor to run with selenoid?

**Comment by vania-pooh** [comment]
@bhoppeadoy sure, a lot of persons are using Protractor with Selenoid. This error can mean that Selenoid container is started in one Docker network and its containers in another network. If you are launching Selenoid manually with `--network` flag or with Docker compose (which is creating custom network automaticall) - then make sure you are also adding `-container-network <network-name>` flag to Selenoid command line arguments.

**Comment by bhoppeadoy** [comment]
I'm launching selenoid using 'cm selenoid start'. Looking at the network settings they appear to be on the same network.

**Here's the network for the selenoid container:**
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2b5fe3593b73548e5bece8c214f3c181c60cf612f48b1f9c52dab39c8769c083",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/2b5fe3593b73",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "97fc2a9ca33ebbdd695fcaf40bf9a42ac88e734335081500586e8501f8b72460",
            "Gateway": "192.168.196.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "192.168.196.2",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "MacAddress": "02:42:c0:a8:c4:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "e10fdc450766bfbebd1feecbee0818b20eb5b6e76d161a6c3c86fc545f1b9d31",
                    "EndpointID": "97fc2a9ca33ebbdd695fcaf40bf9a42ac88e734335081500586e8501f8b72460",
                    "Gateway": "192.168.196.1",
                    "IPAddress": "192.168.196.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:c4:02"
                }
            }
        }

**Here's the network for the started test container:**
 "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "27f76a638d1a22ab87e39f9754bcf6290ae93d7751f40fb3005632cf8619694b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/27f76a638d1a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "8f0aad7f4131b15b5c6391599ce228db065d5f9ccda45ca338652026611397fd",
            "Gateway": "192.168.196.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "192.168.196.4",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "MacAddress": "02:42:c0:a8:c4:04",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "e10fdc450766bfbebd1feecbee0818b20eb5b6e76d161a6c3c86fc545f1b9d31",
                    "EndpointID": "8f0aad7f4131b15b5c6391599ce228db065d5f9ccda45ca338652026611397fd",
                    "Gateway": "192.168.196.1",
                    "IPAddress": "192.168.196.4",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:c4:04"
                }
            }
        }

**Comment by bhoppeadoy** [comment]
Also I forgot to mention that my selenoid is on a remote server. I'm running tests from one machine and selenoid on another. Since 192.168.196.4 is local network to the selenoid host obviously i can't see that from another machine. 

So I guess the real question is how do I run against a remote selenoid server?

**Comment by vania-pooh** [comment]
@bhoppeadoy should work on any remote server. Couldn't it be a Windows-specific Docker firewall issue? At least on Linux Docker is using a bridge network interface to provide network communication between containers. Here `192.168.196.4` is a browser container internal IP address inside this custom Docker network. Take a look at the following troubleshooting guide: https://success.docker.com/article/troubleshooting-container-networking

**Comment by vania-pooh** [comment]
@bhoppeadoy you could try to start two containers manually and try to `telnet` port `4444` from one container to another. If it timeouts - then you have issues in Docker.

**Comment by bhoppeadoy** [comment]
@vania-pooh looks like the issue is with my bridge network. Running 'docker network inspect bridge' I see this option:

            "com.docker.network.bridge.enable_icc": "false",

This Enables or Disables Inter Container Connectivity. I'm going to try to get this set to true and see if it solves my issue.

**Comment by bhoppeadoy** [comment]
@vania-pooh I might not be able to change the above setting, so would I be able to configure selenoid to always pass the '--link selenoid' option to docker run command when it starts a browser container?

**Comment by vania-pooh** [comment]
@bhoppeadoy no, linking is not supported.

**Comment by bhoppeadoy** [comment]
@vania-pooh Just FYI, I was able to configure icc=true and now I'm able to run tests against Selenoid remotely. Thanks for all your help with tracking this issue.

**Comment by vania-pooh** [comment]
@bhoppeadoy great!
