### ISSUE TITLE
How to start android images

### ISSUE THREAD

**Issue by ViljarVoidula** [aerokube/selenoid#476]
Added to browsers.json 
pulled image docker pull selenoid/android:7.1

 "android": {
        "default": "7.1",
        "versions": {
            "7.1": {
                "image": "selenoid/android:7.1",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
 }

Also tried to use:  
./cm selenoid cleanup
./cm selenoid configure [--browsers firefox:45.0;opera:53.0;android:7.1] [--last-versions 2] [--tmpfs 128]

Still no luck. Probably mistake in my end but cant quite figure it our just via documentation.

**Comment by vania-pooh** [comment]
@ViljarVoidula at least check that you have KVM support on your host machine. Also in this command:
```
$ ./cm selenoid configure [--browsers firefox:45.0;opera:53.0;android:7.1] [--last-versions 2] [--tmpfs 128]
```
... square brackets mean optional arguments. No need to type `[` or `]` symbols.

**Comment by vania-pooh** [comment]
@ViljarVoidula only works with latest CM release. Please make sure you have this one: https://github.com/aerokube/cm/releases/tag/1.5.0

**Comment by ViljarVoidula** [comment]
@vania-pooh Original issue solved , bad user , change user problem for sure. Thank you for this  great solution!
 Impacted new one probably not selenoid problem, perhaps you have any ideas. Trying to switch to webview but getting following error, same appium version same driver version combination works on local mahcine without docker . 
Only difference manner of installation - in local setup i use CHROMEDRIVER_VERSION=2.20 npm install appium -g :(

http://appium.io/docs/en/writing-running-appium/web/chromedriver/ 

2018-07-12 12:36:59:229 - [Chromedriver] Spawning chromedriver with: /usr/bin/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
2018-07-12 12:36:59:305 - [Chromedriver] Chromedriver exited unexpectedly with code 127, signal null
2018-07-12 12:36:59:306 - [debug] [Chromedriver] Changed state to 'stopped

**Comment by vania-pooh** [comment]
@ViljarVoidula  no idea, what it could be. You can run Android image as follows:
```
# docker run -d --name emulator-test -e ENABLE_VNC=true -e SKIN=WXGA800 --privileged -p 5900:5900 -p 8888:4444 selenoid/android:7.1
```
Then you can connect to VNC `vnc://localhost:5900` with password `selenoid` and try to run the test. You will see what happens in real-time. Alternatively you can use Selenoid UI and VNC feature with this image. https://www.youtube.com/watch?v=t29xjZ_Lo3I&list=PLW7WVf1LXeWrCBv_48hOR-eWtshGBet9a&index=5

**Comment by ViljarVoidula** [comment]
@vania-pooh Was not aware about youtube channel, gonna educate myself further there. I think its safe to close this issue :)

**Comment by ViljarVoidula** [comment]
@vania-pooh Found the problem - Android images need libx11-dev and libgconf-2-4 \ if testing hybrid apps with Webview (my setup used Android 25 SDK and 2.28 chromedriver) .
Found remedy from : https://forums.aws.amazon.com/thread.jspa?threadID=216939 .

**Comment by vania-pooh** [comment]
@ViljarVoidula I can add this stuff to images, but shouldn't these libraries be present inside Android emulator?

**Comment by vikramnagaraju31** [comment]
@vania-pooh Am running below command on ubuntu VM on MAC enabled with nested virtualisation, once i run my virtual is hanged also container crashes can you please help me on this if am missing something.
docker run -d --name emulator-test -e ENABLE_VNC=true -e SKIN=WXGA800 --privileged -p 5900:5900 -p 8888:4444 selenoid/android:7.1
