### ISSUE TITLE
SESSION_FAILED for Firefox

### ISSUE THREAD

**Issue by bhoppeadoy** [aerokube/selenoid#478]
I have selenoid (docker) v1.6.2 running against chrome just fine. I then wanted to try against firefox. This is what I get in the selenoid logs:

2018/07/12 17:12:49 [-] [NEW_REQUEST] [unknown] [128.247.37.31]
2018/07/12 17:12:49 [-] [NEW_REQUEST_ACCEPTED] [unknown] [128.247.37.31]
2018/07/12 17:12:49 [2] [LOCATING_SERVICE] [firefox] []
2018/07/12 17:12:49 [-] [DEFAULT_VERSION] [Using default version: 61.0]
2018/07/12 17:12:49 [2] [USING_DOCKER] [firefox] [61.0]
2018/07/12 17:12:49 [2] [CREATING_CONTAINER] [selenoid/vnc_firefox:61.0]
2018/07/12 17:12:49 [2] [STARTING_CONTAINER] [selenoid/vnc_firefox:61.0] [7eaf0b6158bd16647f8f7ca29f0dd3096f963a47eba0f777120bbe3703876f70]
2018/07/12 17:12:50 [2] [CONTAINER_STARTED] [selenoid/vnc_firefox:61.0] [7eaf0b6158bd16647f8f7ca29f0dd3096f963a47eba0f777120bbe3703876f70] [0.33s]
2018/07/12 17:12:50 [2] [SERVICE_STARTED] [selenoid/vnc_firefox:61.0] [7eaf0b6158bd16647f8f7ca29f0dd3096f963a47eba0f777120bbe3703876f70] [0.45s]
2018/07/12 17:12:50 [2] [PROXY_TO] [7eaf0b6158bd16647f8f7ca29f0dd3096f963a47eba0f777120bbe3703876f70] [http://192.168.196.4:4444/wd/hub]
2018/07/12 17:12:50 [2] [SESSION_ATTEMPTED] [http://192.168.196.4:4444/wd/hub] [1]
2018/07/12 17:13:20 [2] [SESSION_FAILED] [http://192.168.196.4:4444/wd/hub] [500 Internal Server Error]
2018/07/12 17:13:20 [2] [REMOVING_CONTAINER] [7eaf0b6158bd16647f8f7ca29f0dd3096f963a47eba0f777120bbe3703876f70]
2018/07/12 17:13:20 [2] [CONTAINER_REMOVED] [7eaf0b6158bd16647f8f7ca29f0dd3096f963a47eba0f777120bbe3703876f70]

Not sure where to look now to why the session is failing to start.

**Comment by vania-pooh** [comment]
@bhoppeadoy make sure you are using a recent Selenium client library. It should support the W3C Webdriver specification. E.g for Java version should be 3.4.0 and above.

**Comment by bhoppeadoy** [comment]
@vania-pooh Sorry, can you explain how I verify selenium client library? Where is the client library? 

For java, are you referring to java on my docker host or in the container?

**Comment by bhoppeadoy** [comment]
I'm running tests using Protractor with all the latest versions:

Protractor v5.3.2
selenium-webdriver v4.0.0-alpha.1
webdriver-manager v12.1.0

**Comment by bhoppeadoy** [comment]
@vania-pooh Ah, it looks like its an issue with how I defined the proxy. For chrome, this is what I had:

`   proxy: {
      proxyType: 'manual',
      httpProxy: 'webproxy.ext.ti.com:80',
      sslProxy: 'webproxy.ext.ti.com:80',
      noProxy: 'localhost.ti.com,*.dhcp.ti.com'
    },
    'selenoid:options': {
      'enableVNC': true,
      'screenResolution': '1200x1600x24'
    },
`

If I remove the proxy {} the container starts and runs the test, but then it can't reach the application. So looks to be an issue with proxy definition.

**Comment by vania-pooh** [comment]
@bhoppeadoy yes, I'm meaning `selenium-webdriver` version.

**Comment by bhoppeadoy** [comment]
The issue turns out to be noProxy. Chrome works fine when noProxy is a string. Firefox expects noProxy to be an array.
