### ISSUE TITLE
How to create safari, ie, edge images for selenoid framework?

### ISSUE THREAD

**Issue by NazarSilchenko** [aerokube/selenoid#479]
In docs I see you are saying there is a way to create a custom images. But there is no info about how to do it. Could you please point me to the right direction?

I want to create images to test on safari, ie, edge.

**Comment by vania-pooh** [comment]
@NazarSilchenko currently neither MacOS nor Windows can be run inside Docker container. So there is no way to do this for the moment.

**Comment by leorush** [comment]
@NazarSilchenko you can try to create a vm inside Docker container. For ex. look here - https://github.com/jgoerzen/docker-qemu
https://github.com/kholia/OSX-KVM

**Comment by derek-adair** [comment]
I know its not a "container" but you can test vs safari like [this](https://medium.com/@aandryashin/selenium-an-apple-story-ab0c0b68cd35). Basically, runing selenoid on a VM of the desired OS with SafariDriver and -disabled-docker.

**Comment by derek-adair** [comment]
The same could work w/ theoretically any browser/OS combo.

**Comment by vania-pooh** [comment]
This was described in detail in github.com/aerokube/windows-images
