### ISSUE TITLE
Possibility to use reduced-redundancy s3 storage class for uploaded files

### ISSUE THREAD

**Issue by vgrigoruk** [aerokube/selenoid#495]
https://aws.amazon.com/s3/reduced-redundancy/

Basically, additional options should be passed when uploading files to s3
see `StorageClass` here: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#PutObjectInput

**Comment by vania-pooh** [comment]
@vgrigoruk take a look at https://github.com/aerokube/selenoid/pull/496. Is is what you were expecting to obtain in this issue?

**Comment by vgrigoruk** [comment]
Looking forward to #496 being merged.
