### ISSUE TITLE
Support for Userns-remap for docker containers

### ISSUE THREAD

**Issue by MitRandi** [aerokube/selenoid#503]
It will be great to find a way to run selenoid container with additional docker parameters.
For the most for me it is "--userns=host " to allow solenoid container to bypass users-remap restrictions.

**Comment by MitRandi** [comment]
I run cm as a Docker container on my host. My host dockerd is running using user namespace, so user inside the container are mapped to a different of user ID on the host, this avoids the root user sharing the same ID as the host one. In this context, it is not possible to use the selenoid contaner with docker.

What is happening is, first to run selenoid container we need to share the docker.sock, but it will not have the necessary right because it is running in a different user namespace. One work around is to run the selenoid container on the host namespace by using --user_ns=host.

**Comment by aandryashin** [comment]
We will investigate the issue and provide you with further recommendations.
Another workaround is that to run selenoid as binary with regular users
permissions that can access docker socket.

2018-07-26 22:02 GMT+03:00 MitRandi <notifications@github.com>:

**Comment by aandryashin** [comment]
Looks good to me to implement that option to avoid such issues. Most
probably that should be default behavior for  cm.

2018-07-26 22:10 GMT+03:00 Alexander Andryashin <aandryashin@gmail.com>:

**Comment by vania-pooh** [comment]
@aandryashin @MitRandi this should be a global Selenoid flag, right? Not per-image option.

**Comment by aandryashin** [comment]
it is docker flag, so cm should set that flag when starts selenoid in
docker.

2018-07-27 6:17 GMT+03:00 Ivan Krutov <notifications@github.com>:

**Comment by vania-pooh** [comment]
Moved to https://github.com/aerokube/cm/issues/182 as it is a CM issue.
