### ISSUE TITLE
Selenoid container status restarting

### ISSUE THREAD

**Issue by gusacinschi** [aerokube/selenoid#517]
I am using Windows 10 machine with Docker 18.06.0-ce-win72 (19098) on it using Linux containers.
Steps I took to run selenoid:
1.  Command ".\cm_windows_amd64.exe selenoid start --vnc --browsers chrome";
2, Then it said: "Failed to start: failed to create container: Error response from daemon: Mount denied:
The source path "C:/Users/{USER}/.aerokube/selenoid/video" doesn't exist and is not known to Docker"
3. I created video subdirectory in my user's selenoid directory;
4. The same happened with logs folder. I created logs folder in the selenoid directory.
5. Running docker ps -a returns:
![selenoid](https://user-images.githubusercontent.com/20762793/43551141-d096787e-959a-11e8-91f2-58a2920a48e6.JPG)

Comments:
1. This is strongly related to the closed issue: https://github.com/aerokube/selenoid/issues/469
2. In my user's directory there is .aerokube\selenoid directory containing logs and video subdirectories created by me. Also browsers.json with the following content:
{
    "chrome": {
        "default": "68.0",
        "versions": {
            "67.0": {
                "image": "selenoid/vnc_chrome:67.0",
                "port": "4444",
                "path": "/"
            },
            "68.0": {
                "image": "selenoid/vnc_chrome:68.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

3. This is the docker inspect Binds output for the selenoid container
 "Binds": [
                "/host_mnt/c/Users/{USER}/.aerokube/selenoid:/etc/selenoid:ro",
                "/host_mnt/c/Users/{USER}/.aerokube/selenoid/video:/opt/selenoid/video",
                "/host_mnt/c/Users/{USER}/.aerokube/selenoid/logs:/opt/selenoid/logs",
                "/var/run/docker.sock:/var/run/docker.sock"
            ]
*Note: The {USER} part is edited by me

4. When I run "docker run aerokube/selenoid:1.7.1", gives me:
"[INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]"

The status keep saying restarting all the time. The container can not be used. Please help!

**Comment by vania-pooh** [comment]
@gusacinschi you can type `docker logs selenoid` and see the exact error reason. But so far as I know Docker for Windows by default allows to mount only user directory paths like this: `/c/Users/user/...`, not sure whether `/host_mnt` part influences.

**Comment by gusacinschi** [comment]
Thank you for quick reply...

docker logs selenoid returns:
[INIT] [Loading configuration files...]
[INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]"

**Comment by vania-pooh** [comment]
@gusacinschi I think the issue is in volume specifications. You could try to run another container and see what's inside mounted directory, e.g.:
```
docker run --rm -it  -v /host_mnt/c/Users/{USER}/.aerokube/selenoid:/etc/selenoid:ro alpine:3.7 ls -la /etc/selenoid
```

**Comment by gusacinschi** [comment]
After running that command it returns:

Status: Downloaded newer image for alpine:3.7
total 8
drwxrwxrwx    2 root     root             0 Aug  1 23:11 .
drwxr-xr-x    1 root     root          4096 Aug  2 16:01 ..
-rwxrwxrwx    1 root     root          1133 Aug  1 23:11 browsers.json
drwxrwxrwx    2 root     root             0 Aug  1 23:09 config
drwxrwxrwx    2 root     root             0 Aug  1 21:51 logs
drwxrwxrwx    2 root     root             0 Aug  1 21:39 video

**Comment by vania-pooh** [comment]
@gusacinschi could you then paste `docker inspect selenoid` here?

**Comment by gusacinschi** [comment]
Finally I was able to start it. Works perfectly. All I did is reset Docker to factory defaults and re-pulling all selenoid images. You were right. This was a Docker(Windows) issue.

   "Binds": [
                "/host_mnt/c/Users/alex.gusacinschi/.aerokube/selenoid:/etc/selenoid:ro",
                "/host_mnt/c/Users/alex.gusacinschi/.aerokube/selenoid/video:/opt/selenoid/video",
                "/host_mnt/c/Users/alex.gusacinschi/.aerokube/selenoid/logs:/opt/selenoid/logs",
                "/var/run/docker.sock:/var/run/docker.sock"
            ],
 "Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/alex.gusacinschi/.aerokube/selenoid",
                "Destination": "/etc/selenoid",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/alex.gusacinschi/.aerokube/selenoid/video",
                "Destination": "/opt/selenoid/video",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/alex.gusacinschi/.aerokube/selenoid/logs",
                "Destination": "/opt/selenoid/logs",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

Binds and mounts are the same as before. Thanks for your quick replies and help!
спасибо вам за вашу поддержку! )

**Comment by vania-pooh** [comment]
@gusacinschi great, feel free to close if the issue is resolved.

**Comment by gusacinschi** [comment]
OK, thanks, maybe you could add this issue solution to the documentation.

**Comment by Sree9120** [comment]
Follow these steps also 
1.stop and remove the container where selenoid is running (docker container stop <>,docker container rm <>)
2.Navigate to cm_windows_amd64.exe in cmd and type selenoid cleanup
3. Run in powershell > docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start
4.If it says still failed try running .\cm_windows_amd64.exe selenoid start --vnc --browsers "chrome:75.0" --force.

It should help :-)
