### ISSUE TITLE
Add ability to proxy VNC port

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#52]
Should be able to proxy vnc port by session ID like the following:
```
/vnc/<uuid>
```
The request like this...
```
GET /vnc
```
... should return a list of currently available videos.

**Comment by sskorol** [comment]
@vania-pooh would video files be available for pulling out from containers, or it'd be just a live streaming via `selenoid-ui`?

**Comment by vania-pooh** [comment]
@sskorol this is one is about streaming only to Selenoid UI. Regarding video - this is a more complicated task. In my current understanding we can't capture video directly from VNC. In order to capture video we need to use something like [this](http://afterdesign.net/2016/02/07/recording-headless-selenium-tests-to-mp4.html). The method described in the article requires installing ffmpeg and using x11grab driver. Installing all this software to every container will dramatically increase their size. So if you know a better way to capture video (e.g. directly from VNC) - please tell us.

**Comment by vania-pooh** [comment]
So unless you know very simple way to capture video from VNC, video feature will be one of the next.

**Comment by sskorol** [comment]
@vania-pooh personally I have used ffmpeg for video recording in containers. It was chosen for Allure compatibility (as it supports only html5-video formats at moment).
