### ISSUE TITLE
Add skin and videoCodec capabilities

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#528]
Should set respective environment variables.

**Comment by swifty-team** [comment]
+1

**Comment by swifty-team** [comment]
Hi
Can you add PRESET an CRF?
For implementing Lossless H.264

like:
`ffmpeg -i input -c:v libx264 -preset ultrafast -crf 0 output.mkv`

doc:
https://trac.ffmpeg.org/wiki/Encode/H.264

**Comment by vania-pooh** [comment]
@swifty-team please create a separate issue.
