### ISSUE TITLE
Support deleting files form browser download folder

### ISSUE THREAD

**Issue by BorisOsipov** [aerokube/selenoid#533]
Now selenoid supports getting file from browser download folder by internal http server from url `GET http://${selenoidHost}:4444/download/${sessionId}/${filename}`

It will be nice to allow remove file by
`DELETE http://${selenoidHost}:4444/download/${sessionId}/${filename}`

**Comment by StepanTuchin98** [comment]
From my point of view, it will be nice to document this feature here:
https://aerokube.com/selenoid/latest/

**Comment by vania-pooh** [comment]
Done. https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser
