### ISSUE TITLE
Unable to access external/internal websites when I launch a browser

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/selenoid#536]
I have set up selenoid in docker machine . I am able to poll the status using http://host:4444/status
Also I am able to launch a chrome instance (vnc_65) and see it in selenoid-ui  . But when it is unable to navigate to the website in this step -

driver.get("https://www.google .com");

Any thoughts ? Seems I have to make some config changes but not sure what ?

**Comment by rohitpatwari84** [comment]
Just to mention, I am unable to access even internal sites :/

**Comment by vania-pooh** [comment]
@rohitpatwari84 do you have to configure any proxies to access the Internet?

**Comment by rohitpatwari84** [comment]
On my local , yes I have to . So where do I mention these proxies  in docker-compose yaml file ?

**Comment by vania-pooh** [comment]
@rohitpatwari84 so far as I know you have to configure Docker itself to work with proxies. https://docs.docker.com/network/proxy/

**Comment by rohitpatwari84** [comment]
I used chrome image v65 , v64 , v64 . All are having issues . The chrome browsers shows establishing secure connection and connecting at the bottom left for a long time . After that my home page displays but the connecting mesage at bottom is still displayed and the loading icon doesnt go . So its unable to perform any steps after that . Can you please help ?

**Comment by vania-pooh** [comment]
@rohitpatwari84 did you configure Docker to work with proxies?

**Comment by rohitpatwari84** [comment]
But , if it was a proxy issue then my site wouldnt have opened up at all , Right ? . It shows the home page after a long time . In few seconds after opening my url , it shows "SITE CANT BE REACHED .. TIME ERR" on Chrome , But soon after it shows me the HOME Page of my site .

On FF though , the page loads pretty fast.

**Comment by vania-pooh** [comment]
@rohitpatwari84 timeout can be increased either with Selenoid `-timeout` flag or with `sessionTimeout` capability specified in seconds.

**Comment by rohitpatwari84** [comment]
@vania-pooh , thanks . But it seems that this doesnt work . My page gives time out msg within 20 sec after I do a get and then after a long time shows my home page .

I see the following debug statements initially (when Chrome shows ERR_TIMED OUT) - 
[1535723018.294][DEBUG]: DEVTOOLS RESPONSE DOM.getDocument (id=16) {
   "root": {
      "backendNodeId": 1,
      "baseURL": "**chrome-error://chromewebdata**/",
      "childNodeCount": 2,
      "children": [ {
         "backendNodeId": 2,
         "localName": "",
         "nodeId": 7,
         "nodeName": "html",
         "nodeType": 10,
         "nodeValue": "",
         "parentId": 6,
         "publicId": "",
         "systemId": ""
      }, {

**Comment by rohitpatwari84** [comment]
@vania-pooh  , The below Logs might help you to give some clue -

Initialize...

Connecting to ws://dockerhost:9090/ws/logs/873870c9dc38373921948458e2ec8cb5...
Connected!
Waiting xvfb...

 --- x11vnc loop: 1 ---

Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Starting ChromeDriver 2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881) on port 4444
All remote connections are allowed. Use a whitelist instead!
[1535726707.426][INFO]: COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "start-maximized", "--disable-extensions", "test-type", "--timeout=120", "--disable-web-security", "--allow-running-insecure-content", "--unsafely-treat-insecure-origin-as-secure=https://adpvantage-fit.nj.adp.com" ],
            "extensions": [  ]
         }
      } ]
   },
   "desiredCapabilities": {
      "browserName": "chrome",
      "enableVNC": true,
      "goog:chromeOptions": {
         "args": [ "start-maximized", "--disable-extensions", "test-type", "--timeout=120", "--disable-web-security", "--allow-running-insecure-content", "--unsafely-treat-insecure-origin-as-secure=https://adpvantage-fit.nj.adp.com" ],
         "extensions": [  ]
      },
      "javascriptEnabled": true,
      "platform": "ANY",
      "sessionTimeout": 200,
      "version": "64.0"
   }
}
[1535726707.441][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1535726707.441][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1535726707.462][INFO]: Launching chrome: /usr/bin/google-chrome --allow-running-insecure-content --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-extensions --disable-extensions-except=/tmp/.org.chromium.Chromium.K2azKR/internal --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --disable-web-security --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12206 --start-maximized --test-type --timeout=120 --unsafely-treat-insecure-origin-as-secure=https://adpvantage-fit.nj.adp.com --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.mqIm5g data:,
[1535726707.463][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.603][DEBUG]: DevTools request failed
[1535726707.653][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.653][DEBUG]: DevTools request failed
[1535726707.704][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.704][DEBUG]: DevTools request failed
[1535726707.754][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.754][DEBUG]: DevTools request failed
[1535726707.804][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.805][DEBUG]: DevTools request failed
 --- x11vnc loop: waiting for: 66

[1535726707.855][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.855][DEBUG]: DevTools request failed
[1535726707.905][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.905][DEBUG]: DevTools request failed
[1535726707.955][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726707.956][DEBUG]: DevTools request failed
[1535726708.006][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.006][DEBUG]: DevTools request failed
[1535726708.056][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.056][DEBUG]: DevTools request failed
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.maxIgnoreIncrement
Setting default value
Failed to read: session.screen0.maxDisableMove
Setting default value
Failed to read: session.screen0.maxDisableResize
Setting default value
Failed to read: session.screen0.workspacewarping
Setting default value
Failed to read: session.screen0.showwindowposition
Setting default value
Failed to read: session.screen0.autoRaise
Setting default value
Failed to read: session.screen0.clickRaises
Setting default value
Failed to read: session.screen0.defaultDeco
Setting default value
Failed to read: session.screen0.tab.placement
Setting default value
Failed to read: session.screen0.windowMenu
Setting default value
Failed to read: session.screen0.noFocusWhileTypingDelay
Setting default value
Failed to read: session.screen0.workspaces
Setting default value
Failed to read: session.screen0.edgeSnapThreshold
Setting default value
Failed to read: session.screen0.window.focus.alpha
Setting default value
Failed to read: session.screen0.window.unfocus.alpha
Setting default value
Failed to read: session.screen0.menu.alpha
Setting default value
Failed to read: session.screen0.menuDelay
Setting default value
Failed to read: session.screen0.tab.width
Setting default value
Failed to read: session.screen0.tooltipDelay
Setting default value
Failed to read: session.screen0.allowRemoteActions
Setting default value
Failed to read: session.screen0.clientMenu.usePixmap
Setting default value
Failed to read: session.screen0.tabs.usePixmap
Setting default value
Failed to read: session.screen0.tabs.maxOver
Setting default value
Failed to read: session.screen0.tabs.intitlebar
Setting default value
Failed to read: session.screen0.focusModel
Setting default value
Failed to read: session.screen0.tabFocusModel
Setting default value
Failed to read: session.screen0.focusNewWindows
Setting default value
Failed to read: session.screen0.focusSameHead
Setting default value
Failed to read: session.screen0.rowPlacementDirection
Setting default value
Failed to read: session.screen0.colPlacementDirection
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
[1535726708.107][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.107][DEBUG]: DevTools request failed
PORT=5900
[1535726708.157][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.157][DEBUG]: DevTools request failed
Failed to read: session.screen0.slit.acceptKdeDockapps
Setting default value
Failed to read: session.screen0.slit.autoHide
Setting default value
Failed to read: session.screen0.slit.maxOver
Setting default value
Failed to read: session.screen0.slit.placement
Setting default value
Failed to read: session.screen0.slit.alpha
Setting default value
Failed to read: session.screen0.slit.onhead
Setting default value
Failed to read: session.screen0.slit.layer
Setting default value
[1535726708.208][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.208][DEBUG]: DevTools request failed
[1535726708.258][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.258][DEBUG]: DevTools request failed
Failed to read: session.screen0.toolbar.autoHide
Setting default value
Failed to read: session.screen0.toolbar.maxOver
Setting default value
Failed to read: session.screen0.toolbar.widthPercent
Setting default value
Failed to read: session.screen0.toolbar.alpha
Setting default value
Failed to read: session.screen0.toolbar.layer
Setting default value
Failed to read: session.screen0.toolbar.onhead
Setting default value
Failed to read: session.screen0.toolbar.placement
Setting default value
Failed to read: session.screen0.toolbar.height
Setting default value
[1535726708.308][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.309][DEBUG]: DevTools request failed
[1535726708.359][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.359][DEBUG]: DevTools request failed
[1535726708.409][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.410][DEBUG]: DevTools request failed
[1535726708.460][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.460][DEBUG]: DevTools request failed
[1535726708.510][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.510][DEBUG]: DevTools request failed
[1535726708.561][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.561][DEBUG]: DevTools request failed
[1535726708.611][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.611][DEBUG]: DevTools request failed
[1535726708.661][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.662][DEBUG]: DevTools request failed
[57:101:0831/104508.663241:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1535726708.712][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.712][DEBUG]: DevTools request failed
[1535726708.762][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.762][DEBUG]: DevTools request failed
[1535726708.813][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.813][DEBUG]: DevTools request failed
[57:302:0831/104508.816949:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

DevTools listening on ws://127.0.0.1:12206/devtools/browser/33c8286c-1152-4732-9225-410c5b98e544
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Failed to read: session.screen0.titlebar.left
Setting default value
Failed to read: session.screen0.titlebar.right
Setting default value

(google-chrome:57): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown orunsupported transport 'disabled' for address 'disabled:'
[1535726708.863][DEBUG]: DevTools request: http://localhost:12206/json/version
[1535726708.869][DEBUG]: DevTools response: {
   "Browser": "Chrome/64.0.3282.119",
   "Protocol-Version": "1.2",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36",
   "V8-Version": "6.4.388.40",
   "WebKit-Version": "537.36 (@5e944b2d79bce5f96dc35a05a76b03d65a6e9a0a)",
   "webSocketDebuggerUrl": "ws://localhost:12206/devtools/browser/33c8286c-1152-4732-9225-410c5b98e544"
}

[1535726708.872][DEBUG]: DevTools request: http://localhost:12206/json
[1535726708.874][DEBUG]: DevTools response: [ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:12206/devtools/page/(F0B06F77DFACDA5E3CBDD0ADE872F3A9)",
   "id": "(F0B06F77DFACDA5E3CBDD0ADE872F3A9)",
   "title": "Chrome Automation Extension",
   "type": "background_page",
   "url": "chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:12206/devtools/page/(F0B06F77DFACDA5E3CBDD0ADE872F3A9)"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:12206/devtools/page/(D2D39841B0FAA1C3E49DB7A181467C)",
   "id": "(D2D39841B0FAA1C3E49DB7A181467C)",
   "title": "",
   "type": "page",
   "url": "data:,",
   "webSocketDebuggerUrl": "ws://localhost:12206/devtools/page/(D2D39841B0FAA1C3E49DB7A181467C)"
} ]

[1535726708.875][DEBUG]: DevTools request: http://localhost:12206/json
[1535726708.875][DEBUG]: DevTools response: [ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:12206/devtools/page/(F0B06F77DFACDA5E3CBDD0ADE872F3A9)",
   "id": "(F0B06F77DFACDA5E3CBDD0ADE872F3A9)",
   "title": "Chrome Automation Extension",
   "type": "background_page",
   "url": "chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:12206/devtools/page/(F0B06F77DFACDA5E3CBDD0ADE872F3A9)"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:12206/devtools/page/(D2D39841B0FAA1C3E49DB7A181467C)",
   "id": "(D2D39841B0FAA1C3E49DB7A181467C)",
   "title": "",
   "type": "page",
   "url": "data:,",
   "webSocketDebuggerUrl": "ws://localhost:12206/devtools/page/(D2D39841B0FAA1C3E49DB7A181467C)"
} ]

[1535726708.876][INFO]: resolved localhost to ["127.0.0.1","172.17.0.13","::1"]
[1535726708.876][DEBUG]: DEVTOOLS COMMAND Log.enable (id=1) {

}
[1535726708.876][DEBUG]: DEVTOOLS COMMAND DOM.getDocument (id=2) {

}
[1535726708.876][DEBUG]: DEVTOOLS COMMAND Runtime.enable (id=3) {

}
[1535726708.876][DEBUG]: DEVTOOLS COMMAND Page.enable (id=4) {

}
[1535726708.877][DEBUG]: DEVTOOLS COMMAND Page.enable (id=5) {

}
[256:256:0831/104508.877099:ERROR:sandbox_linux.cc(375)] InitializeSandbox() called with multiple threads in process gpu-process.
[57:57:0831/104508.879832:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI sharedcontext.
[1535726708.909][DEBUG]: DEVTOOLS RESPONSE Log.enable (id=1) {

}
[1535726708.909][DEBUG]: DEVTOOLS RESPONSE DOM.getDocument (id=2) {
   "root": {
      "backendNodeId": 1,
      "baseURL": "about:blank",
      "childNodeCount": 1,
      "children": [ {
         "attributes": [  ],
         "backendNodeId": 2,
         "childNodeCount": 2,
         "children": [ {
            "attributes": [  ],
            "backendNodeId": 3,
            "childNodeCount": 0,
            "localName": "head",
            "nodeId": 3,
            "nodeName": "HEAD",
            "nodeType": 1,
            "nodeValue": "",
            "parentId": 2
         }, {
            "attributes": [  ],
            "backendNodeId": 4,
            "childNodeCount": 0,
            "localName": "body",
            "nodeId": 4,
            "nodeName": "BODY",
            "nodeType": 1,
            "nodeValue": "",
            "parentId": 2
         } ],
         "frameId": "(D2D39841B0FAA1C3E49DB7A181467C)",
         "localName": "html",
         "nodeId": 2,
         "nodeName": "HTML",
         "nodeType": 1,
         "nodeValue": "",
         "parentId": 1
      } ],
      "documentURL": "",
      "localName": "",
      "nodeId": 1,
      "nodeName": "#document",
      "nodeType": 9,
      "nodeValue": "",
      "xmlVersion": ""
   }
}
[1535726708.909][DEBUG]: DEVTOOLS RESPONSE Runtime.enable (id=3) {

}
[1535726708.909][DEBUG]: DEVTOOLS RESPONSE Page.enable (id=4) {

}
[1535726708.909][DEBUG]: DEVTOOLS RESPONSE Page.enable (id=5) {

}
[1535726708.909][DEBUG]: DEVTOOLS COMMAND Page.enable (id=6) {

}
[7:16:0831/104508.917849:ERROR:command_buffer_proxy_impl.cc(134)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[1535726708.919][DEBUG]: DEVTOOLS EVENT Page.frameNavigated {
   "frame": {
      "id": "(D2D39841B0FAA1C3E49DB7A181467C)",
      "loaderId": "(7972B0F75F36EFD51D07FF4D2A99FA99)",
      "mimeType": "text/plain",
      "securityOrigin": "://",
      "url": "data:,"
   }
}
[1535726708.919][DEBUG]: DEVTOOLS EVENT DOM.documentUpdated {

}
[1535726708.919][DEBUG]: DEVTOOLS COMMAND DOM.getDocument (id=7) {

}
[1535726708.919][DEBUG]: DEVTOOLS EVENT Runtime.executionContextCreated {
   "context": {
      "auxData": {
         "frameId": "(D2D39841B0FAA1C3E49DB7A181467C)",
         "isDefault": true
      },
      "id": 1,
      "name": "",
      "origin": "://"
   }
}
[1535726708.919][DEBUG]: DEVTOOLS RESPONSE Page.enable (id=6) {

}
[1535726708.922][DEBUG]: DEVTOOLS EVENT Page.loadEventFired {
   "timestamp": 4266148.782107
}
[1535726708.922][DEBUG]: DEVTOOLS EVENT Page.frameStoppedLoading {
   "frameId": "(D2D39841B0FAA1C3E49DB7A181467C)"
}
[1535726708.922][DEBUG]: DEVTOOLS EVENT Page.domContentEventFired {
   "timestamp": 4266148.782576
}
[1535726708.922][DEBUG]: DEVTOOLS EVENT DOM.documentUpdated {

}
[1535726708.922][DEBUG]: DEVTOOLS COMMAND DOM.getDocument (id=8) {

}
[1535726708.922][DEBUG]: DEVTOOLS RESPONSE DOM.getDocument (id=7) {
   "root": {
      "backendNodeId": 5,
      "baseURL": "data:,",
      "childNodeCount": 1,
      "children": [ {
         "attributes": [  ],
         "backendNodeId": 6,
         "childNodeCount": 2,
         "children": [ {
            "attributes": [  ],
            "backendNodeId": 7,
            "childNodeCount": 0,
            "localName": "head",
            "nodeId": 7,
            "nodeName": "HEAD",
            "nodeType": 1,
            "nodeValue": "",
            "parentId": 6
         }, {
            "attributes": [  ],
            "backendNodeId": 8,
            "childNodeCount": 1,
            "localName": "body",
            "nodeId": 8,
            "nodeName": "BODY",
            "nodeType": 1,
            "nodeValue": "",
            "parentId": 6
         } ],
         "frameId": "(D2D39841B0FAA1C3E49DB7A181467C)",
         "localName": "html",
         "nodeId": 6,
         "nodeName": "HTML",
         "nodeType": 1,
         "nodeValue": "",
         "parentId": 5
      } ],
      "documentURL": "data:,",
      "localName": "",
      "nodeId": 5,
      "nodeName": "#document",
      "nodeType": 9,
      "nodeValue": "",
      "xmlVersion": ""
   }
}
[1535726708.924][DEBUG]: DEVTOOLS RESPONSE DOM.getDocument (id=8) {
   "root": {
      "backendNodeId": 5,
      "baseURL": "data:,",
      "childNodeCount": 1,
      "children": [ {
         "attributes": [  ],
         "backendNodeId": 6,
         "childNodeCount": 2,
         "children": [ {
            "attributes": [  ],
            "backendNodeId": 7,
            "childNodeCount": 0,
            "localName": "head",
            "nodeId": 11,
            "nodeName": "HEAD",
            "nodeType": 1,
            "nodeValue": "",
            "parentId": 10
         }, {
            "attributes": [  ],
            "backendNodeId": 8,
            "childNodeCount": 1,
            "localName": "body",
            "nodeId": 12,
            "nodeName": "BODY",
            "nodeType": 1,
            "nodeValue": "",
            "parentId": 10
         } ],
         "frameId": "(D2D39841B0FAA1C3E49DB7A181467C)",
         "localName": "html",
         "nodeId": 10,
         "nodeName": "HTML",
         "nodeType": 1,
         "nodeValue": "",
         "parentId": 9
      } ],
      "documentURL": "data:,",
      "localName": "",
      "nodeId": 9,
      "nodeName": "#document",
      "nodeType": 9,
      "nodeValue": "",
      "xmlVersion": ""
   }
}
[1535726708.924][DEBUG]: DEVTOOLS COMMAND Runtime.enable (id=9) {

}
[1535726708.925][DEBUG]: DEVTOOLS EVENT Page.frameResized {

}
[1535726708.925][DEBUG]: DEVTOOLS RESPONSE Runtime.enable (id=9) {

}
[1535726708.926][DEBUG]: DEVTOOLS COMMAND Runtime.evaluate (id=10) {
   "expression": "(function() { // Copyright (c) 2012 The Chromium Authors. All rightsreserved.\n// Use of this source code is governed by a BSD-style license that can be\n// found in the LICENSE file.\n\n/**\n * Enum f...",
   "returnByValue": true
}
[1535726708.929][DEBUG]: DEVTOOLS RESPONSE Runtime.evaluate (id=10) {
   "result": {
      "type": "object",
      "value": {
         "status": 0,
         "value": 1
      }
   }
}
[1535726708.930][INFO]: RESPONSE InitSession {
   "acceptInsecureCerts": false,
   "acceptSslCerts": false,
   "applicationCacheEnabled": false,
   "browserConnectionEnabled": false,
   "browserName": "chrome",
   "chrome": {
      "chromedriverVersion": "2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881)",
      "userDataDir": "/tmp/.org.chromium.Chromium.mqIm5g"
   },
   "cssSelectorsEnabled": true,
   "databaseEnabled": false,
   "handlesAlerts": true,
   "hasTouchScreen": false,
   "javascriptEnabled": true,
   "locationContextEnabled": true,
   "mobileEmulationEnabled": false,
   "nativeEvents": true,
   "networkConnectionEnabled": false,
   "pageLoadStrategy": "normal",
   "platform": "Linux",
   "rotatable": false,
   "setWindowRect": true,
   "~~~": "..."
}
[1535726709.251][INFO]: COMMAND Navigate {

**Comment by vania-pooh** [comment]
@rohitpatwari84 the only conclusion I can made from these logs is that session was created successfully.

**Comment by rohitpatwari84** [comment]
Thanks @vania-pooh  . What are these bus related Errors then -
`[57:302:0831/104508.816949:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`

Are they causing this extreme slowness ?

**Comment by vania-pooh** [comment]
@rohitpatwari84 for example that there is no DBUS daemon installed inside browser container. This daemon is mainly used for sending various messages to another processes in Linux supporting DBUS, so not needed for Firefox to work properly.

**Comment by rohitpatwari84** [comment]
Hmm...since on firefox the page opens fine without timeout , So I think something to do with Chrome image ?

**Comment by vania-pooh** [comment]
@rohitpatwari84 sorry for the delay. Was this issue resolved?

**Comment by rohitpatwari84** [comment]
Not yet..My browser shows the login page and then take a long time to connect to googletagmanager.com.  Same thing happens on my local , But on when I add Proxy address in my local browser , it works . But I am not sure how to add the proxy to browser container in selenoid ?

**Comment by rohitpatwari84** [comment]
Also Browser (FF) shows the below address bar And at the bottom it shows connecting to googletagmanager.com....And then before arrying out further action it times out -

![image](https://user-images.githubusercontent.com/41872833/46957560-74152180-d0b5-11e8-8491-55d51d9a8af8.png)
