### ISSUE TITLE
Video/Log file overridden when resetSession used

### ISSUE THREAD

**Issue by prasadasokan** [aerokube/selenoid#542]
When we specify the capability to save the video/log with the desired filename, the file gets overridden when resetSession is used. This doesn't happen when no file name is specified as Selenoid's default behaviour is to save the file with the session ID, which will be different for the second execution done after the resetSession is issued. Is there a workaround for this?

**Comment by prasadasokan** [comment]
The reason we have to rely on the capability to name the file is, the session id's aren't following the same pattern all the time. 

We have seen the following three types of id's. Can you help us understand when this happens and how to make them follow a particular pattern all the time?

1. 9f3a40ef-69f6-4f34-86d1-0151aab02016.mp4
2. 9ff6a92f168d466eee002c1ef06cb06a.mp4
3. selenoid61c83d6f4b3b831e4c63d808cba00960.mp4

**Comment by vania-pooh** [comment]
@prasadasokan 
1) Selenoid does not process `resetSession` capability at all.
2) Selenoid always saves files as `<session-id>.mp4`. However Chromedriver (and probably Operadriver) generates sessions as `9ff6a92f168d466eee002c1ef06cb06a` whereas other drivers (Geckodriver, Appium, etc.) return `9f3a40ef-69f6-4f34-86d1-0151aab02016`.
3) `selenoid61c83d6f4b3b831e4c63d808cba00960.mp4` is a temporary file name renamed to final name when the session is closed. When no sessions are running no such files should exist.

**Comment by prasadasokan** [comment]
Thanks @vania-pooh 

So we can go ahead with the video name capability then as there is no possibility of the video being overridden.

**Comment by vania-pooh** [comment]
@prasadasokan we consider user responsibility to provide unique video file names when using `videoName` capability.
