### ISSUE TITLE
Error on running FF - (/usr/lib/firefox/firefox:180): dconf-CRITICAL **: unable to create directory '/home/selenium/.cache/dconf': Permission denied.  dconf will not work properly.

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/selenoid#543]
Getting below Errors while running FF (58.0) -
(/usr/lib/firefox/firefox:180): dconf-CRITICAL **: unable to create directory '/home/selenium/.cache/dconf': Permission denied.  dconf will not work properly.

Not sure what should be changed to get this working ?

**Comment by rohitpatwari84** [comment]
When I open the Firefox container(while it is running) , I can see the directory is already present there -

$ cd selenium/.cache
$ ls -lrt
total 0
drwx------ 3 selenium nogroup  21 Sep  6 10:28 mozilla
drwxr-xr-x 2 selenium nogroup 132 Sep  6 10:28 fontconfig
drwx------ 2 selenium nogroup  18 Sep  6 10:28 dconf

**Comment by vania-pooh** [comment]
@rohitpatwari84 any details about your environment? All images are using non-root user `selenium`. Are you receiving these errors as a Selenium error message or just seeing them in Docker container logs?

**Comment by rohitpatwari84** [comment]
No I am seeing these in the browser container ( on Selenoid UI logs section) .

**Comment by vania-pooh** [comment]
@rohitpatwari84 if your tests work then you can ignore these messages.

**Comment by rohitpatwari84** [comment]
ok for now I will ignore . If I get any issues in future will drop a note here .Thanks @vania-pooh

**Comment by aditya2020** [comment]
I get the same issue running selenium tests using geckodriver. My docker version is :
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:57:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Using selenium/standalone-firefox in the Dockerfile.

Please help in how to solve this

**Comment by vania-pooh** [comment]
@aditya2020 these images have no relation to `selenium/standalone-firefox`.
