### ISSUE TITLE
Getting Error while running IE 11 remotely through Selenoid

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/selenoid#545]
I have set up Selenoid on one of my VM(Win 7 , IE 11) .It is up and running - 

```
018/09/09 02:40:01 [-] [INIT] [Loading configuration files...]
2018/09/09 02:40:01 [-] [INIT] [Loaded configuration from C:\IEDriver\browsers.json]
2018/09/09 02:40:01 [-] [INIT] [Using default containers log configuration because of: read error: open config/container-logs.json: The system cannot find the path specified.]
2018/09/09 02:40:01 [-] [INIT] [Timezone: Local]
2018/09/09 02:40:01 [-] [INIT] [Listening on :4444]
2018/09/09 02:40:01 listen tcp :4444: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

Now when I try to launch this from my windows 10 machine
```
       DesiredCapabilities dcap = DesiredCapabilities.internetExplorer();
        URL url = new URL("http://<host_name_of_selenoid>:4444/wd/hub");
        WebDriver driver = new RemoteWebDriver(url, dcap);
........
```

I see the below Error  on my idea console (on local , from where I try to launch the test)-

```
Exception in thread "main" org.openqa.selenium.WebDriverException: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
Command duration or timeout: 1.11 seconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'mylocalhost', ip: 'x.x.x.x', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
```

**Comment by aandryashin** [comment]
It looks like windows related issue...

вс, 9 сент. 2018 г. в 12:04, rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
Should this command work to make sure selenoid is running properly  http://myhost:4444/status ?
It is giving page not found

**Comment by aandryashin** [comment]
Yes it should work, also please make sure than 4444 is not listening by
another process.

вс, 9 сент. 2018 г. в 12:41, rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
I dont know how and why ..But it started working now . I made no changes at all :P..
BTW ..Thanks Alex!!!!

So I can mention this IE host in my user.xml property in the docker host running ggr and it will show up in selenoid UI as well as run if i send requests to ggr ? Am I right ?

**Comment by aandryashin** [comment]
Please take a look on ggr-ui project, It aggregates statuses from all
underlying ggr hosts.

https://github.com/aerokube/ggr-ui


вс, 9 сент. 2018 г. в 12:52, rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
Ok cool.. Thanks Alex ..And can we have VNC for this IE machine ?Is there any any way ?
