### ISSUE TITLE
Selenoid/Grr + Appium iOS

### ISSUE THREAD

**Issue by benzman81** [aerokube/selenoid#547]
Hi,
I am not sure how to connect Appium for iOS testing to our GGR grid. So I need to run selenoid to connect to appium, or just put the appium url into GGR? What would the config look like? Most documentionnis referenced for browser usage.

Ragards,
Markus

**Comment by vania-pooh** [comment]
@benzman81 sorry for the delay. You need put Appium host and port behind Ggr. Ggr matches either `browserName` or `deviceName` capability against browser name specified in XML quota.

**Comment by vania-pooh** [comment]
@benzman81 did it help?

**Comment by benzman81** [comment]
Sorry, forgot to close. Yes it helped. Thank you very much.
