### ISSUE TITLE
Any way for selenoid to send status of a test as pass or fail

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/selenoid#548]
This is not an issue.Wanted to know if this can be done. I want to save history of pass fail for tests for reporting purposes.

**Comment by vania-pooh** [comment]
@rohitpatwari84 Selenoid is just a Selenium-compatible HTTP API. It knows nothing about your tests including whether they fail or pass. I would recommend to take a look at [Allure](https://github.com/allure-framework/allure2) report. Allure can save some history information.

**Comment by rohitpatwari84** [comment]
Thanks @vania-pooh . I will take a look at it .

**Comment by rohitpatwari84** [comment]
Also @vania-pooh , is there any way to save custom messages to the log file which is finally saved in docker host ? One file is generated which we can name through capability. Is there any way to save our own messages in that ?

**Comment by vania-pooh** [comment]
@rohitpatwari84 currently this is not possible. But again Allure allows to add custom attachments to any test steps. I think such feature is out of Selenoid scope.

**Comment by vania-pooh** [comment]
Closing because this feature is out of scope of Allure framework.
