### ISSUE TITLE
WebDriverException: Message: json: cannot unmarshal string into Go struct field Caps.enableVideo of type bool

### ISSUE THREAD

**Issue by DmitryNaumovA1qa** [aerokube/selenoid#554]
Using robot framework with python selenium2Library

code 
`
*** Settings ***
Documentation    Test 
Library    String
Library    Selenium2Library
Test Teardown               Close All Browsers

*** Variables ***
${URL}                      https://tut.by
${BROWSER}                  chrome
${ALIAS}                    None
${REMOTE_URL}               http://localhost:4444/wd/hub
${DESIRED_CAPABILITIES}     name:browserTest,enableVideo:true

*** Test Cases ***
Open browser
    [Documentation]    Check tat browser can be opened
    ...                and assert is
    Open Browser    ${URL}   ${BROWSER}   ${ALIAS}   ${REMOTE_URL}    ${DESIRED_CAPABILITIES}
    Wait Until Element Is Visible    xpath://div[@id="example"]    10
    Capture Page Screenshot

*** Keywords ***
`

It transformes to
POST http://127.0.0.1:4444/wd/hub/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any"}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "name": "browserTest", "enableVideo": "true"}}

**Comment by vania-pooh** [comment]
@DmitryNaumovA1qa should be `"enableVideo": True` - boolean, not a string.

**Comment by DmitryNaumovA1qa** [comment]
"enableVideo": "true" 
this string creates robot framework and I can't influence on it as I set it as name:browserTest,enableVideo:true
Is there a workaround for it?

**Comment by vania-pooh** [comment]
@DmitryNaumovA1qa take a look at this: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Boolean%20arguments

**Comment by vania-pooh** [comment]
@DmitryNaumovA1qa did it help?

**Comment by DmitryNaumovA1qa** [comment]
nope, make a workaround, create a custom keyword that initializes browser. Did not succeed with Selenium2Library and Selenoid

**Comment by JaPyR** [comment]
@DmitryNaumovA1qa Hi, you are using incorrect syntax. It's possible to force boolean in Robot Framework. Look at this example:

```
*** Settings ***
Library           Selenium2Library

*** Variables ***
&{DESIRED_CAPABILITIES}    name=browserTest    enableVideo=${True}

*** Test Cases ***
Issue554
    Open Browser     https://tut.by    gc    remote_url=http://localhost:4444/wd/hub    desired_capabilities=${DESIRED_CAPABILITIES}
    Sleep    30
```

![issue554](https://user-images.githubusercontent.com/7773301/47425039-6df40480-d789-11e8-810c-a149bb5ae390.png)

**Comment by vania-pooh** [comment]
@DmitryNaumovA1qa seems to be resolved. Closing. Feel free to reopen is still having this issue.

**Comment by edsherwin** [comment]
> @DmitryNaumovA1qa Hi, you are using incorrect syntax. It's possible to force boolean in Robot Framework. Look at this example:
> 
> ```
> *** Settings ***
> Library           Selenium2Library
> 
> *** Variables ***
> &{DESIRED_CAPABILITIES}    name=browserTest    enableVideo=${True}
> 
> *** Test Cases ***
> Issue554
>     Open Browser     https://tut.by    gc    remote_url=http://localhost:4444/wd/hub    desired_capabilities=${DESIRED_CAPABILITIES}
>     Sleep    30
> ```
> 
> ![issue554](https://user-images.githubusercontent.com/7773301/47425039-6df40480-d789-11e8-810c-a149bb5ae390.png)

Hi, I was trying this on my end also but I encountered this error.
AttributeError: 'NoneType' object has no attribute 'to_capabilities'

Is there any config/setting do I need to setup first? 

Thanks

**Comment by madb1ker** [comment]
Trying to run Selenoid on my Robot Framework tests but I am unable to view Video or record it.

![image](https://github.com/aerokube/selenoid/assets/79003568/9d76cbe5-7bb5-4d74-bba4-291d25777f20)

![image](https://github.com/aerokube/selenoid/assets/79003568/4e4425ab-b7c7-4bfe-9fc7-465ed9e5c0ca)

What am I doing wrong?

**Comment by madb1ker** [comment]
> > @DmitryNaumovA1qa Hi, you are using incorrect syntax. It's possible to force boolean in Robot Framework. Look at this example:
> > ```
> > *** Settings ***
> > Library           Selenium2Library
> > 
> > *** Variables ***
> > &{DESIRED_CAPABILITIES}    name=browserTest    enableVideo=${True}
> > 
> > *** Test Cases ***
> > Issue554
> >     Open Browser     https://tut.by    gc    remote_url=http://localhost:4444/wd/hub    desired_capabilities=${DESIRED_CAPABILITIES}
> >     Sleep    30
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![issue554](https://user-images.githubusercontent.com/7773301/47425039-6df40480-d789-11e8-810c-a149bb5ae390.png)
> 
> Hi, I was trying this on my end also but I encountered this error. AttributeError: 'NoneType' object has no attribute 'to_capabilities'
> 
> Is there any config/setting do I need to setup first?
> 
> BTW. I have running Selenoid and Selenoid UI on my local machine.
> 
> Thanks

I'm having same error now: AttributeError: 'NoneType' object has no attribute 'to_capabilities'

Have you been able to fix this?

Thx
