### ISSUE TITLE
Priority in the Queue

### ISSUE THREAD

**Issue by getuliojr** [aerokube/selenoid#555]
Is there any options where I could set a priority in the queues. Sometime I have a large queue and I need to process one item fast and it gets in the bootle of the queue. Would like to know if such an option is possible where it would to go the top and be next.

**Comment by vania-pooh** [comment]
@getuliojr no, this is not possible. We consider queues an exceptional situation needed only in case when cluster is temporarily overloaded. In normal operation mode there should be no queues.

**Comment by getuliojr** [comment]
If you think selenoid running test cases I imagine that. But when it is used to crawl data in internet and other systems your start to take cases where one item in queue can take from 30seconds to 10 minutes processing time and with that in mind priority in queues make sense. Thats is our case.

**Comment by getuliojr** [comment]
I will try with GGR and quotas for user. That might work as an alternative. Thanks.

**Comment by vania-pooh** [comment]
@getuliojr JFYI Ggr distributes requests randomly over a set of hosts and also has no queues. So it does not prevent the cluster from overloading.
