### ISSUE TITLE
Plugin-based approach for session artifact storage

### ISSUE THREAD

**Issue by nebehr** [aerokube/selenoid#559]
Currently Selenoid is able to upload recorded video and log files to S3 storage. Supposing this functionality were made configurable to enable user to upload artifact to *any* storage, not just S3? This could work either through some kind of custom module plugged into main Selenoid executable, or perhaps as an external service deployed in a separate Docker container. This would also eliminate necessity to rebuild Selenoid with any custom tags. Does this suggestion make sense?

**Comment by vania-pooh** [comment]
@nebehr your idea makes sense except rebuilding note. Golang is a language with static linking and build artifact is always `single` binary. This is why we can implement plugins either as standalone binaries or as built-in features which can be enabled with flags. Right now we use second approach.

**Comment by vania-pooh** [comment]
@nebehr btw, any ideas what can be added except S3?

**Comment by nebehr** [comment]
Doesn't [this](https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9) approach imply dynamic linking?

I do not have specific list of possible implementations. The idea is to have users create their own plugins according to the contract set by Selenoid because obviously one can't expect Selenoid team to cover all possible permutations. One option might be plain upload to a file system storage over SFTP or whatever.  Or perhaps something for Azure users.

**Comment by vania-pooh** [comment]
@nebehr dynamic linking seems to be more complicated than static one. Btw, Azure supports S3.
