### ISSUE TITLE
Issues with SSL Support with BrowserMobProxy to capture HAR 

### ISSUE THREAD

**Issue by prasadasokan** [aerokube/selenoid#560]
@vania-pooh We were exploring Browsermobproxy as suggested, to capture HAR. But when loading a website with SSL, we are facing issues. Further reading the BrowserMobProxy documentation, we understand a CA cert has to be trusted on the browser. There seem to be no automated way of importing this to a browser node. Are you aware of a workaround for the same?

Docs reference from the proxy's documentation:

> _If you're doing testing with Selenium, you'll want to make sure that the browser profile that gets set up by Selenium not only has the proxy configured, but also has the CA installed. Unfortunately, there is no API for doing this in Selenium; it must be done manually for each browser and environment._

**Comment by vania-pooh** [comment]
@prasadasokan e.g. adding `acceptInsecureCerts = true` or `acceptSSLCerts = true` capability (first is W3C standard capability).

**Comment by prasadasokan** [comment]
@vania-pooh The W3C standard capability worked. Thanks.
