### ISSUE TITLE
Empty file upload causes error "unknown error: unable to unzip 'file'"

### ISSUE THREAD

**Issue by olegbaslak** [aerokube/selenoid#568]
When  I upload empty file (0 bytes size) using input element (and SendKeys command), following exception is thrown:

> Message: OpenQA.Selenium.WebDriverException : unknown error: unable to unzip 'file'
from unknown error: archive error: (unknown error: could not unzip archive), entry error: (unknown error: could not unzip archive)
  (Session info: chrome=69.0.3497.81)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-130-generic x86_64)

**Comment by vania-pooh** [comment]
@olegbaslak what is the use case of uploading zero byte file?

**Comment by olegbaslak** [comment]
> @olegbaslak what is the use case of uploading zero byte file?

It is one of the cases to test on client's file uploading

**Comment by olegbaslak** [comment]
Looks like it can be a poblem of ZipStorer that is used in RemoteWebDriver for transferring files to upload

**Comment by olegbaslak** [comment]
I have created an issue in selenium's repo: https://github.com/SeleniumHQ/selenium/issues/6529
