### ISSUE TITLE
Add support for S3 folder prefixes

### ISSUE THREAD

**Issue by nebehr** [aerokube/selenoid#580]
Currently there seems to be no way to automatically place recorded files into S3 "folders" with dynamic names, for example {test launch id}/{test item id}/{file name}. Obviously {test launch id} and {test item id} are generated on runtime and therefore cannot be passed to Selenoid containers via s3-key-pattern flag. On the other hand, path containing forward slashes cannot be specified in videoName capability either because Selenoid tries to create file with such name and fails (actually it may also fail with other shell special characters).

What if file name passed through videoName capability was in some way escaped (either by URL Encode or something else) and then decoded during S3 upload? Or perhaps handling of forward slashes would be sufficient?

**Comment by vania-pooh** [comment]
@nebehr could you show final pattern you wish to obtain?

**Comment by nebehr** [comment]
Basically this *was* the pattern: {test launch id}/{test item id}/{file name}. The first two parts are generated during execution, and it would be natural to use such id's as prefixes in S3 storage to emulate folders. It is possible to build such name and pass it via videoName capability but Selenoid will not be able to create such file because the name contains forward slashes. It means that forward slashes can only be present in the "static" part of the pattern (s3-key-pattern) but this pattern does not change once Selenoid node is deployed. In other words, what's missing is the way to transform "slashless" videoName into "slashed" S3 object key, or to accept "slashed" videoName as is.

**Comment by vania-pooh** [comment]
@nebehr ok, I got the issue. Let me think a bit more about it.

**Comment by vania-pooh** [comment]
@nebehr how about adding a new capability `s3KeyPattern` allowing to override `-s3-key-pattern` flag in runtime?

**Comment by vania-pooh** [comment]
@nebehr should work in `aerokube/selenoid:latest`. Capability name is `s3KeyPattern`. The same `$placeholders` work.
