### ISSUE TITLE
control of logs outed

### ISSUE THREAD

**Issue by jsa34** [aerokube/selenoid#591]
Hello,

I have been successfully using selenoid as replacement for selenium grid for a few days, but suddently encountered an issue - we run hundreds of tests a day, and the logs files are being outed to /selenoid/logs and it rapidly fills up the disk space.  Is there any way of a) turning off this logging or b) setting the logging level so that it only outs a log in the cases of error.  I am manually deleting the logs at the moment and I could create a cronjob to purge the directory, but it seems a short-sighted solution.  I'm sure I'm just missing something, but I couldn't see anything about this in the documentation.

Many thanks!

**Comment by vania-pooh** [comment]
@jsa34 yes, right now `cm` tool is always launching Selenoid with `-log-output-dir` flag. Launching Selenoid without this flag (but manually) should stop saving log files. Will add a flag in `cm`: https://github.com/aerokube/cm/issues/197

**Comment by jsa34** [comment]
Thank you for the update!

I will wait for the cm fix to be applied :)

**Comment by jsa34** [comment]
Fixed now in cm
