### ISSUE TITLE
Abort handler 

### ISSUE THREAD

**Issue by potapovDim** [aerokube/selenoid#598]
Env 
Windows 10 Pro. Version 1809
RAM 32 gb
Proc Intel (R) Xeon(R) cpu E5-2686 v4 2.30GHz

Selenoid:  selenoid_windows_amd64.exe
Git Revision: 1.7.2
UTC Build Time: 2018-08-11_08:39:59AM

browsers 18 chrome 70 v, chromedriver 2.43

<img width="862" alt="screen shot 2018-11-02 at 11 23 06 am" src="https://user-images.githubusercontent.com/19333856/47914274-a68d8f80-dea7-11e8-8efd-73f08f650678.png">

**Comment by vania-pooh** [comment]
@potapovDim shit. :) Will fix in next release.

**Comment by vania-pooh** [comment]
Now reproducing on Linux too (at least in `1.8.1`).
```
2018/12/14 15:48:21 httputil: ReverseProxy read error during body copy: unexpected EOF
panic: net/http: abort Handler

goroutine 78808798 [running]:
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc0055d8280, 0x821b60, 0xc0051ac620, 0xc00158f700)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/httputil/reverseproxy.go:284 +0x1058
main.proxy.func1(0xc00298ed20, 0x821b60, 0xc0051ac620, 0xc00158f700)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:445 +0xfb
created by main.proxy
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:403 +0x7a
```

**Comment by vania-pooh** [comment]
Related to https://github.com/golang/go/commit/eab57b27f5460a7e6b87fff95ce2948b7812ce05.
