### ISSUE TITLE
Webdriver launching with white screen

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid#601]
My team is having this issue where running our regression tests using the selenoid architecture on AWS EC2 results in a white screen when the web browser is launched.

This is on a corporate environment, and we have already opened the firewall to the web applications we are testing, so connectivity is not an issue. We are also able to successfully run selenium grid tests on the same EC2 with no issues. Just that when we are trying to run the same tests using selenoid, the above issue occurs.

Any help in the right direction would be much appreciated, thank you!

The logs seem to show that the container was successfully created and removed. Could this be a proxy issue?

Docker Container LOGS:

`2018/11/07 03:55:38 [NEW_REQUEST]

2018/11/07 03:55:38 [NEW_REQUEST_ACCEPTED]

2018/11/07 03:55:38 [0] [LOCATING_SERVICE] [chrome-]

2018/11/07 03:55:38 Using default version: 60.0

2018/11/07 03:55:38 [0] [USING_DOCKER] [chrome-60.0]

2018/11/07 03:55:38 [0] [CREATING_CONTAINER] [selenoid/vnc:chrome_60.0]

2018/11/07 03:55:38 [0] [STARTING_CONTAINER] [selenoid/vnc:chrome_60.0] [1e0a9ad58fe246473d14847f12614c1c8049b74ec41d5493b883afa5a2d3faba]

2018/11/07 03:55:38 [0] [CONTAINER_STARTED] [selenoid/vnc:chrome_60.0] [1e0a9ad58fe246473d14847f12614c1c8049b74ec41d5493b883afa5a2d3faba] [236.581726ms]

2018/11/07 03:55:38 [0] [SERVICE_STARTED] [selenoid/vnc:chrome_60.0] [1e0a9ad58fe246473d14847f12614c1c8049b74ec41d5493b883afa5a2d3faba] [51.221405ms]

2018/11/07 03:55:38 [0] [PROXY_TO] [selenoid/vnc:chrome_60.0] [1e0a9ad58fe246473d14847f12614c1c8049b74ec41d5493b883afa5a2d3faba] [http://172.17.0.3:4444/]

2018/11/07 03:55:38 [0] [SESSION_ATTEMPTED] [unknown] [http://172.17.0.3:4444/] [1]

2018/11/07 03:55:38 [0] [SESSION_CREATED] [unknown] [bbe54a38c30e33250738a57b50df06af] [http://172.17.0.3:4444/] [1] [485.67873ms]

2018/11/07 03:55:49 [SESSION_DELETED] [bbe54a38c30e33250738a57b50df06af]

2018/11/07 03:55:49 [0] [REMOVE_CONTAINER] [1e0a9ad58fe246473d14847f12614c1c8049b74ec41d5493b883afa5a2d3faba]

2018/11/07 03:55:50 [0] [CONTAINER_REMOVED] [1e0a9ad58fe246473d14847f12614c1c8049b74ec41d5493b883afa5a2d3faba]
`

**Comment by vania-pooh** [comment]
@timothyjmtan you could e.g. record a video of running session and see what happens in browser. Just add `enableVideo = true` (as boolean, not string) capability to your tests and then open video by session ID on the following URL: `http://selenoid.example.com:4444/video/`.

**Comment by timothyjmtan** [comment]
Hi @vania-pooh  thanks for the quick reply. Do I follow the instructions here? https://github.com/aerokube/selenoid/blob/master/docs/video.adoc

**Comment by vania-pooh** [comment]
@timothyjmtan yes, but it's better to use generated documentation: https://aerokube.com/selenoid/latest/#_video_recording You may want to build video recorder image yourself: https://github.com/aerokube/selenoid-images/tree/master/selenium/video

**Comment by timothyjmtan** [comment]
@vania-pooh  Okay, let me check if I am able to build this on another computer that has access to the internet.

Something I've also noticed is that if I were to `curl localhost:4444/wd/hub`, I get the following:
`<a href="/wd/hub/">Moved Permanently</a>.`.

From what I've read in the other threads, the expected response should instead be a 404?

In the meantime, here are some more info that may hopefully shed some light:

`$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Wed Sep 26 23:00:19 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Wed Sep 26 23:01:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false`


`
$ docker inspect selenoid
[
    {
        "Id": "7d691aaeff55ac978e677915f0e455af7dfe4af1ac854aa263cd5e0545d709f2",
        "Created": "2018-11-07T07:49:35.778580524Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-listen",
            ":4444",
            "-conf",
            "/etc/selenoid/browsers.json"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10728,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-11-07T07:49:36.140766555Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:3ebb9c9ee0cd5c0ab4a9b92afd92303d8be204f543a8eb448cd0f2277273e6ef",
        "ResolvConfPath": "/var/lib/docker/containers/7d691aaeff55ac978e677915f0e455af7dfe4af1ac854aa263cd5e0545d709f2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/7d691aaeff55ac978e677915f0e455af7dfe4af1ac854aa263cd5e0545d709f2/hostname",
        "HostsPath": "/var/lib/docker/containers/7d691aaeff55ac978e677915f0e455af7dfe4af1ac854aa263cd5e0545d709f2/hosts",
        "LogPath": "/var/lib/docker/containers/7d691aaeff55ac978e677915f0e455af7dfe4af1ac854aa263cd5e0545d709f2/7d691aaeff55ac978e677915f0e455af7dfe4af1ac854aa263cd5e0545d709f2-json.log",
        "Name": "/selenoid",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock",
                "/home/ec2-user/config/:/etc/selenoid/:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "4444/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4444"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
           "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": [
                {
                    "Name": "nofile",
                    "Hard": 4096,
                    "Soft": 1024
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/asound",
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/b7e3aa190a85bd113b74b5ca89992c6babd61cb7c446dd9448b17afc745528ed-init/diff:/var/lib/docker/overlay2/71662e94e17e5ed43872df742b3dfdba62af119700835320332713fcc5ec6272/diff:/var/lib/docker/overlay2/f6d3fd4fb1e4d369e20ef5778e83b62a7c10a1bd9976ef82a8e0a77a12fc3f1b/diff:/var/lib/docker/overlay2/c123fed5a9beba7ebfea21ecc6403cc070709216e06d71a0e2929136ff17be05/diff",
                "MergedDir": "/var/lib/docker/overlay2/b7e3aa190a85bd113b74b5ca89992c6babd61cb7c446dd9448b17afc745528ed/merged",
                "UpperDir": "/var/lib/docker/overlay2/b7e3aa190a85bd113b74b5ca89992c6babd61cb7c446dd9448b17afc745528ed/diff",
                "WorkDir": "/var/lib/docker/overlay2/b7e3aa190a85bd113b74b5ca89992c6babd61cb7c446dd9448b17afc745528ed/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
               "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ec2-user/config",
                "Destination": "/etc/selenoid",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "7d691aaeff55",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "aerokube/selenoid:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d06cd73ed8d3be0752f692edcabd8b86f7e21f43617c6e313f01c15a625e098b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/d06cd73ed8d3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "b61796823876e67d0bd5552a982733fbad7dda16caef59431e65b7e9b7136bac",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ab77d5834490b6f8a6d51f1883145d8c40f77996013cbe8389f501fc35015d74",
                    "EndpointID": "b61796823876e67d0bd5552a982733fbad7dda16caef59431e65b7e9b7136bac",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }

`

**Comment by vania-pooh** [comment]
@timothyjmtan yes, this should return 404. To check that Selenoid works use one of the following:
```
$ curl -s http://localhost:4444/status
$ curl -s http://localhost:4444/wd/hub/status
$ curl -s http://localhost:4444/ping
```

**Comment by timothyjmtan** [comment]
@vania-pooh Thanks. Here are the outputs:

`$ curl -s http://localhost:4444/status`
`{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"60.0":{}},"firefox":{"46.0":{}}}}`

`$ curl -s http://localhost:4444/wd/hub/status`
`404 page not found`

`$ curl -s http://localhost:4444/ping`
`{"uptime":"9m29.888363051s","lastReloadTime":"2018-11-07 10:36:48.640004621 +0000 UTC"}`

**Comment by vania-pooh** [comment]
@timothyjmtan did it help?
