### ISSUE TITLE
Restarting dockerd makes Selenoid unable to connect to Docker using Unix socket

### ISSUE THREAD

**Issue by jadonn** [aerokube/selenoid#606]
If I restart dockerd after starting Selenoid through the Configuration Manager or directly using Docker, Selenoid is no longer able to connect to the Docker API. Selenoid attempts to start a container using the Docker API, but it returns the following error:

2018/11/12 20:36:47 [28] [SERVICE_STARTUP_FAILED] [create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]

The Docker daemon is running and listening at /var/run/docker.sock.

If I restart Selenoid after restarting dockerd, Selenoid can connect to the API again until dockerd is restarted.

I am using Configuration Manager Git Revision: 1.5.5 UTC Build Time: 2018-10-30_12:20:49PM and Selenoid image: aerokube/selenoid:latest (sha256:3d0f70b60bc0fead0946051995ed57c9d52e9138babb3a444e8947639e6cb2e4).

I am running Docker 1.39. I tried running a Selenoid container using the run command from the documentation to specify Docker to use the 1.24 version API (docker run -e DOCKER_API_VERSION=1.24 -d --name selenoid -p 4444:4444 -v /etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aerokube/selenoid:latest) and Selenoid was not able to connect to the Docker daemon even.

What can I do to resolve this issue? 

I really like Selenoid, and I am excited to use it since it resolves several issues I was going to have using Selenium Grid.

**Comment by vania-pooh** [comment]
@jadonn Right now Selenoid automatically determines Docker API version and is known to work without any issues with Docker API 1.39. Could you clarify - what platform we are talking about? Is it Docker for Linux or for Mac or some kind of Docker for Windows? Currently it seems that this is some platform-specific Docker bug. Have never seen such behavior.

**Comment by jadonn** [comment]
Thank you for the response @vania-pooh ! I apologize for not including that information. I am running Docker 1.39 on CentOS 7.5. If you think it sounds environment specific, I will try out Selenoid on a few different Linux environments and report back what I find out in case it might be helpful. Thanks again!

**Comment by vania-pooh** [comment]
@jadonn we usually recommend starting with Ubuntu. CentOS has some security-specific stuff like SELinux which is sometimes causing strange Docker bugs.

**Comment by jadonn** [comment]
I'll give that a try @vania-pooh. Thanks for the suggestion! I wasn't able to replicate this on a very plain CentOS 7.5 server. I think you are right about there being a problem with the one server I was originally testing Selenoid on. I'm going to close this issue. Thank you again for your help and for the work you do on Selenoid!
