### ISSUE TITLE
Add possibility to forward VNC traffic from Safari browsers to selenoid-ui

### ISSUE THREAD

**Issue by yurii-tikhonenko** [aerokube/selenoid#613]
I have GGR instance which includes several Mac mini’s with selenoid binaries and safari browsers.
On all of them VNC is turned on but I have no possibility to view browser’s image inside selenoid-ui.
It would be great if it was possible.

Thanks!

**Comment by jsa34** [comment]
I have just started this arrangement, too, and encountered the same issues.

**Comment by vania-pooh** [comment]
@yurii-tikhonenko several news:
1) You can proxy VNC with Ggr: https://aerokube.com/ggr/latest/#_proxying_vnc_traffic
2) MacOS is using non-standard VNC implementation, so not sure if this will work with non-Mac clients.

**Comment by yurii-tikhonenko** [comment]
I've tried to proxy vnc with ggr but I had no success with it.
Also I started x11vnc on Mac on different port and proxy it's vnc traffic through ggr but it's also wasn't working. Maybe I'm doing smth wrong, I do not know. 
I would appreciate any information that can help :)

**Comment by vania-pooh** [comment]
@yurii-tikhonenko when proxying VNC URL should be something like: `vnc://<remote-host>:<new-port>`.
