### ISSUE TITLE
Ability to access application in another Docker network

### ISSUE THREAD

**Issue by ivanych** [aerokube/selenoid#619]
Ситуация:

Селеноид и тестируемое приложение запущены в разных подсетях. Селеноиду передается опция `-container-network сеть_селеноида`. Соответственно, брузеры запускаются в сети `сеть_селеноида` и Селеноид их видит.

Проблема:

Браузеры при этом не видят приложение, потому что приложение находится в сети `сеть_приложения`.

Предлагаемое решение:

Добавить в Capabilities опцию `networks`, в которой можно будет указать `сеть_приложения` (или даже список сетей).  Селеноид запустит браузер в сети, переданной в опции `-container-network`, а также в сети, переданной в Capabilities. В результате Селеноид будет видеть браузер, а браузер будет видеть приложение.

**Comment by vania-pooh** [comment]
Will be implemented as a capability `additionalNetworks` and an equivalent of the following Docker command:
```
$ docker network connect <network-id> <container-id>
```

**Comment by ivanych** [comment]
@vania-pooh 

> @ivanych в следующий раз по-английски только тикеты пожалуйста делайте, ок? Иначе иностранные пользователи не смогут найти такой тикет.

Я не знаю английский, простите. Могу гугл-переводчиком перевести, но думаю, что это будет еще хуже. По-русски я могу внятно сформулировать.

**Comment by vania-pooh** [comment]
@ivanych released in Selenoid 1.8.4. Docs: https://aerokube.com/selenoid/latest/#_more_docker_networks_additionalnetworks

**Comment by ivanych** [comment]
@vania-pooh Вот это подарочек под Новый год:) Спасибо!
