### ISSUE TITLE
Add dynamic proxy support as special capabilities

### ISSUE THREAD

**Issue by vdelendik** [aerokube/selenoid#625]
In web testing using per session proxy server for sniffering web traffic via browsermob is very useful.
According to the documentation we can provide proxy settings on selenoid level but I'd like to be able to provide it per each container.
Thanks.

**Comment by vania-pooh** [comment]
@vdelendik Selenoid supports any standard capabilities that Selenium does. E.g. `proxy` capability should work just because it will be proxied to driver instance.

**Comment by vdelendik** [comment]
@vania-pooh wanted to submit to GGR:) But root cause is on our own side. By default basic auth is not supported by embedded proxy. closing as not a defect.
thanks!
