### ISSUE TITLE
Chrome and maximize window

### ISSUE THREAD

**Issue by evertsc** [aerokube/selenoid#626]
Hi,

I noticed that for the 'problem' with 'maximizing' the window appeared to be solved in the Chrome images: 65.0, 66.0 and 67.0, but since Chrome image 68.0 I have to use the setSize again to 'maximize' my Chrome browser. Is there a reason for this?

Kind Regards,
Charlie

**Comment by vania-pooh** [comment]
@evertsc we are going to rebuild all images with the fix. Right now you can fix this in latest images by setting `ENABLE_WINDOW_MANAGER` environment variable.

**Comment by vania-pooh** [comment]
In latest Chrome images maximize operation works as we managed to deliver reliable Fluxbox startup logic.
