### ISSUE TITLE
Limit number of instances of individual browsers

### ISSUE THREAD

**Issue by estk** [aerokube/selenoid#642]
I've been using the `-limit 1` [cli flag](https://aerokube.com/selenoid/1.5.2/#_selenoid_cli_flags) so that MicrosoftEdge will not error. It would be great if the limit could be set in the `browsers.json` file instead so that a limit could be set on the individual browsers.

**Comment by vania-pooh** [comment]
Will be implemented as browser weight that will add up to total.

**Comment by canalptekin** [comment]
@vania-pooh Ok understand. But I do not pay any fee if I do 10 limit on docker. It seems closer to use solenoid and solenoid-ui on the docker. Thanks

**Comment by vania-pooh** [comment]
@canalptekin your comment seems to be posted to a wrong issue.
