### ISSUE TITLE
Temp selenoid*.mp4 video doesn't get processed after test run if selenoid starts with docker-compose

### ISSUE THREAD

**Issue by arustamov** [aerokube/selenoid#648]
arustamov2-wf:~ arustamov$ docker --version
Docker version 18.09.0, build 4d60db4

Running with CM:
./cm selenoid start --vnc
works fine and I can see video processed and accessible with http://localhost:4444/video/

While running with similar docker-compose:
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    network_mode: bridge
    ports:
      - 4444:4444
    volumes:
      - $HOME/.aerokube/selenoid:/etc/selenoid
      - $HOME/.aerokube/selenoid/video:/etc/selenoid/video
      - $HOME/.aerokube/selenoid/logs:/etc/selenoid/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$HOME/.aerokube/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-video-recorder-image", "selenoid/video-recorder:latest-release", "-log-output-dir", "/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - 8080:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]

I can see video temp file doesn't get processed so that I can't access it with http://localhost:4444/video/

arustamov2-wf:~ arustamov$ ll .aerokube/selenoid/video/
total 2080
drwxr-xr-x  3 arustamov  staff       96 Jan 13 19:33 .
drwxr-xr-x  7 arustamov  staff      224 Jan 13 19:31 ..
-rw-r--r--  1 arustamov  staff  1002656 Jan 13 19:34 selenoid9a3f92600984d19c13fa4dfff7411332.mp4

I can't find any diff between those two runs with docker inspect selenoid, so what might be the issue here?

**Comment by vania-pooh** [comment]
@arustamov what's inside Selenoid logs? There should be `VIDEO_ERROR` message.

**Comment by arustamov** [comment]
@vania-pooh 
2019/01/13 17:34:16 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid9a3f92600984d19c13fa4dfff7411332.mp4 to /opt/selenoid/video/fe099c3f0ba3aeb96f8f1b7f0d4a038a.mp4: rename /opt/selenoid/video/selenoid9a3f92600984d19c13fa4dfff7411332.mp4 /opt/selenoid/video/fe099c3f0ba3aeb96f8f1b7f0d4a038a.mp4: no such file or directory]

**Comment by vania-pooh** [comment]
@arustamov could you check whether `video-recorder` container is running during all the session? This container is starting with `--rm` flag by default so any error in startup will automatically remove it. There also should be an error in removing video container then.

**Comment by arustamov** [comment]
@vania-pooh 
video-recorder container is up and running during the all session:

arustamov2-wf:~ arustamov$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                    NAMES
417b47c3a4a8        selenoid/video-recorder:latest-release   "/entrypoint.sh"         22 seconds ago      Up 21 seconds                                                serene_wu
f119292f244e        selenoid/vnc_chrome:71.0                 "/entrypoint.sh"         23 seconds ago      Up 22 seconds       4444/tcp, 5900/tcp, 8080/tcp, 9090/tcp   wonderful_snyder
50c41449838b        aerokube/selenoid-ui:latest              "/selenoid-ui --sele…"   4 minutes ago       Up 4 minutes        0.0.0.0:8080->8080/tcp                   selenoid-ui
6d356176fb97        aerokube/selenoid:latest                 "/usr/bin/selenoid -…"   4 minutes ago       Up 4 minutes        0.0.0.0:4445->4444/tcp                   selenoid

There is no any error in selenoid logs other then VIDEO_ERROR:
arustamov2-wf:~ arustamov$ docker logs selenoid
2019/01/14 14:26:05 [-] [INIT] [Loading configuration files...]
2019/01/14 14:26:05 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2019/01/14 14:26:05 [-] [INIT] [Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory]
2019/01/14 14:26:05 [-] [INIT] [Video Dir: /opt/selenoid/video]
2019/01/14 14:26:05 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2019/01/14 14:26:05 [-] [INIT] [Your Docker API version is 1.39]
2019/01/14 14:26:05 [-] [INIT] [Timezone: Local]
2019/01/14 14:26:05 [-] [INIT] [Listening on :4444]
2019/01/14 14:29:45 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2019/01/14 14:29:45 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2019/01/14 14:29:45 [0] [LOCATING_SERVICE] [chrome] []
2019/01/14 14:29:45 [-] [DEFAULT_VERSION] [Using default version: 71.0]
2019/01/14 14:29:45 [0] [USING_DOCKER] [chrome] [71.0]
2019/01/14 14:29:45 [0] [CREATING_CONTAINER] [selenoid/vnc_chrome:71.0]
2019/01/14 14:29:45 [0] [STARTING_CONTAINER] [selenoid/vnc_chrome:71.0] [f119292f244e512fa68c4e36e4fced090a92879f22583cccbb53d97d37bdff92]
2019/01/14 14:29:46 [0] [CONTAINER_STARTED] [selenoid/vnc_chrome:71.0] [f119292f244e512fa68c4e36e4fced090a92879f22583cccbb53d97d37bdff92] [0.45s]
2019/01/14 14:29:46 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2019/01/14 14:29:46 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [417b47c3a4a8c29461dc3e67cd213cbe46957bba83808a8686b4a673a434d675]
2019/01/14 14:29:46 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [417b47c3a4a8c29461dc3e67cd213cbe46957bba83808a8686b4a673a434d675] [0.70s]
2019/01/14 14:29:46 [0] [SERVICE_STARTED] [selenoid/vnc_chrome:71.0] [f119292f244e512fa68c4e36e4fced090a92879f22583cccbb53d97d37bdff92] [0.00s]
2019/01/14 14:29:46 [0] [PROXY_TO] [f119292f244e512fa68c4e36e4fced090a92879f22583cccbb53d97d37bdff92] [http://172.17.0.4:4444/]
2019/01/14 14:29:46 [0] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2019/01/14 14:29:49 [0] [SESSION_CREATED] [aff2b81eb261ee530fb19ff847490207] [1] [3.38s]
2019/01/14 14:30:07 [16] [SESSION_DELETED] [aff2b81eb261ee530fb19ff847490207]
2019/01/14 14:30:07 [0] [STOPPING_VIDEO_CONTAINER] [417b47c3a4a8c29461dc3e67cd213cbe46957bba83808a8686b4a673a434d675]
2019/01/14 14:30:09 [0] [STOPPED_VIDEO_CONTAINER] [417b47c3a4a8c29461dc3e67cd213cbe46957bba83808a8686b4a673a434d675]
2019/01/14 14:30:09 [0] [REMOVING_CONTAINER] [f119292f244e512fa68c4e36e4fced090a92879f22583cccbb53d97d37bdff92]
2019/01/14 14:30:10 [0] [CONTAINER_REMOVED] [f119292f244e512fa68c4e36e4fced090a92879f22583cccbb53d97d37bdff92]
2019/01/14 14:30:10 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoid08139f9a002bc8499bf7a02095669ad3.mp4 to /opt/selenoid/video/aff2b81eb261ee530fb19ff847490207.mp4: rename /opt/selenoid/video/selenoid08139f9a002bc8499bf7a02095669ad3.mp4 /opt/selenoid/video/aff2b81eb261ee530fb19ff847490207.mp4: no such file or directory]

**Comment by vania-pooh** [comment]
@arustamov ok, found an issue:
```
- $HOME/.aerokube/selenoid/video:/etc/selenoid/video
- $HOME/.aerokube/selenoid/logs:/etc/selenoid/logs
```
But should be:
```
- $HOME/.aerokube/selenoid/video:/opt/selenoid/video
- $HOME/.aerokube/selenoid/logs:/opt/selenoid/logs
```
So that's a misconfiguration.

**Comment by arustamov** [comment]
I seeeee...)
You saved my day. I was really just stuck with this having no idea what is wrong. Thanks a lot @vania-pooh ! Hope someone will benefit from my docker-compose config with video recording enabled (since in selenoid-ui docs you have one without it)
