### ISSUE TITLE
The requested service provider could not be loaded or initialized.

### ISSUE THREAD

**Issue by jjballesteros69** [aerokube/selenoid#657]
I am starting to use Selenoid, but I have not been able to start it.

We are running it on windows with the following command
cm selenoid start

The output it produces is:

> Docker is not supported - using binaries...
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid

D:\Selenoid>2019/01/23 07:41:25 [-] [INIT] [Loading configuration files...]
2019/01/23 07:41:25 [-] [INIT] [Loaded configuration from C:\Users\Administrator\.aerokube\selenoid\browsers.json]
2019/01/23 07:41:25 [-] [INIT] [Logs Dir: D:\c\Users\Administrator\.aerokube\selenoid\logs]
2019/01/23 07:41:25 [-] [INIT] [Timezone: Local]
2019/01/23 07:41:25 [-] [INIT] [Listening on :4444]
2019/01/23 07:41:25 listen tcp :4444: socket: The requested service provider could not be loaded or initialized.

I've been trying to find what that socket message means, but no luck.  Some links found searching in google suggest that I need to have the SYSTEMROOT environment variable set, but it is already configured to C:\windows.

Any Help would be appreciate.

**Comment by vania-pooh** [comment]
@jjballesteros69 this is Windows security issue. Just start Selenoid as follows:
```
> C:\Users\<user>\.aerokube\selenoid\selenoid_windows_amd64.exe -conf C:\Users\<user>\.aerokube\selenoid\browsers.json -disable-docker
```

**Comment by jjballesteros69** [comment]
@vania-pooh thank you very much.

It worked like that.  I suggest if it is not there, to write that in the documentation.

Thanks a lot

**Comment by jjballesteros69** [comment]
Worked with the command that @vania-pooh suggested.

**Comment by tCode255** [comment]
> this is Windows security issue. Just start Selenoid as follows:

Is there a solution to this problem in Windows to use cm selenoid start?
If i use your solution I don’t understand how to run a selenoid-ui...

**Comment by vania-pooh** [comment]
@tCode255 is should work when Docker is available. Currently not sure how to fix this when Docker is not available.
