### ISSUE TITLE
Selenoid did not delete running containers when exits with panic

### ISSUE THREAD

**Issue by mdolinin** [aerokube/selenoid#66]
I use GGR 1.1.3 and Selenoid 1.1.1
And periodically Selenoid stops with this error:
```
panic: send on closed channel

goroutine 426219 [running]:
github.com/aerokube/selenoid/service.wait.func1(0xc4201df940, 0x16, 0xc42041b080)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/service.go:62 +0x115
created by github.com/aerokube/selenoid/service.wait
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/service.go:68 +0x8c
```
After this Selenoid stops and left all containers with browsers as is.
As i understand, this could happen because of network issues.

Expected behavior:
* Selenoid delete all browser containers after it exits with error.

If you need some more information, please ask.
I will try to provide as much information as needed.

**Comment by vania-pooh** [comment]
@mdolinin could you please provide your config.json? Or at least what is your browser name and version?

**Comment by mdolinin** [comment]
Here is browsers.json that i use.
```javascript
{
    "chrome": {
        "default": "latest",
        "versions": {
            "latest": {
                "image": "selenoid/chrome:53.0",
                "port": "4444"
            }
        }
    }
}
```

**Comment by vania-pooh** [comment]
@mdolinin thanks. Will investigate soon.

**Comment by vania-pooh** [comment]
@mdolinin please try ```aerokube/selenoid:latest``` to see if the issue is fixed.

**Comment by vania-pooh** [comment]
@mdolinin any updates?

**Comment by mdolinin** [comment]
@vania-pooh I started to use latest version yesterday. Looks like working great.
But i couldn't reproduce those network issues. 
Thinks that our IT's fixed them. Now trying come up with how to reproduce this locally.
May be you have some ideas?

**Comment by aandryashin** [comment]
It is hard to reproduce such issues locally, that is why we missed that
bug... Thank you for pointed to it.

2017-05-05 9:44 GMT+03:00 Mikhail Dolinin <notifications@github.com>:

**Comment by mdolinin** [comment]
Thanks guys for this great tool. I think we can close this bug. I will reopen it, if it reproduced again.
