### ISSUE TITLE
Creating Docker image from tarball

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid#660]
Hello.

I am on an enterprise network that doesn't allow me to connect to the Docker repository. As such I am unable to `docker pull` the image, and instead may have to create it myself. I would like to ask if its possible to create the Docker image from the tarball file, and if there are any existing documentation on how to do it?

Many thanks in advance!

**Comment by vania-pooh** [comment]
@timothyjmtan how about saving and and loading Docker images as shown here: https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository ?

**Comment by timothyjmtan** [comment]
Hey @vania-pooh , thanks for the article.

Unfortunately, within our company there isn't any way to pull from the repository at all. All laptops and computers are blocked from doing so. In addition, portable media like thumbdrive or external HDD do not work on our laptops even if we are able to save them at home using our personal laptops. Social media and file sharing websites are also blocked by the firewall so we can't do cloud transfers. In other words it's a pretty safe environment :-)

I was able to circumvent this issue previously for our MongoDB use-case, by creating the MongoDB docker image myself using the tarball file, and was wondering if its possible to do the same for selenoid as well:

https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-linux/

**Comment by vania-pooh** [comment]
@timothyjmtan Selenoid itself is a binary. Release binaries a published here: https://github.com/aerokube/selenoid/releases The main problem is how to build Docker images with browsers. Do you have an internal Debian packages repository mirroring public repositories?

**Comment by timothyjmtan** [comment]
Thanks for the answer. Yeah that is tricky. Hmm, I'll give a think about it. Closing ticket for now. Thanks again!
