### ISSUE TITLE
selenoid + docker + safari

### ISSUE THREAD

**Issue by gadgadskiy** [aerokube/selenoid#663]
I'm trying to run tests on safari with docker.
When I setup selenoid on pure macos (with safari) all works fine.
But when I run it as a docker container, tests fail with error - could not find environment (and it is logically, because there's no safari in docker, but I didn't find any images for them).
I've run container by following command:
```
$ curl -Lo ~/cm https://github.com/aerokube/cm/releases/download/1.5.7/cm_darwin_amd64 && \
    chmod +x ~/cm && \
    ~/cm selenoid start --browsers safari
```
Is there any way to pre-install safari to docker? or maybe did I wrong something other?

**Comment by vania-pooh** [comment]
@gadgadskiy unfortunately this is not currently possible as there is no Safari built for Linux and Docker currently mainly support Linux (an a bit Windows).

**Comment by gadgadskiy** [comment]
@vania-pooh thank you for response.

**Comment by aloha-cloud** [comment]
is it possible to connect a safari vm browser to selenium hub?

**Comment by vania-pooh** [comment]
@aloha-cloud Selenoid is not compatible with Selenium hub.

**Comment by rhoit** [comment]
is this some new development https://hub.docker.com/r/browsers/safari

**Comment by vania-pooh** [comment]
@rhoit this is an experimental image with webkit inside.

**Comment by rhoit** [comment]
@vania-pooh i was trying to run it independently is there any documentation to do so.

**Comment by vania-pooh** [comment]
@rhoit not yet.

**Comment by Download** [comment]
@vania-pooh I see you recently updated it. Is it less experimental now? Anything interesting to tell us about it?

**Comment by vania-pooh** [comment]
@Download `browsers/safari:14.0` contains simply more recent WebKit version.

**Comment by sebaKwiat** [comment]
is it possible to run safari test on it ?

**Comment by vania-pooh** [comment]
@sebaKwiat that's a regular Selenium image.

**Comment by sebaKwiat** [comment]
@vania-pooh I M trying to register this as a node with selenium/hub is it possible, I M having problems with it ?

**Comment by vania-pooh** [comment]
@sebaKwiat our images do not support /grid/ API and can't be used as Selenium nodes.

**Comment by sebaKwiat** [comment]
@vania-pooh how do you use it with selenium? does it run selenium server ?

**Comment by vania-pooh** [comment]
@sebaKwiat these images will work with Selenoid / Moon and any other implementation that is launching containers without grid API.

**Comment by uddhavchopade** [comment]
@vania-pooh 
How the image for Safari browser is packed? It is using Mac OS or Linux OS?
And which version of safari is there?

**Comment by vania-pooh** [comment]
@uddhavchopade see https://github.com/aerokube/images/tree/master/static/safari. It's a WebKit-based browser for Linux, not real Safari.

**Comment by GolubNick** [comment]
Hi, @vania-pooh Could you help, please? I've pulled the image from https://hub.docker.com/r/browsers/safari/tags. And my browser.json file has a section for the safari browser.

  "safari": {
    "default": "15.0",
    "versions": {
      "15.0": {
        "image": "browsers/safari:15.0",
        "port": "4444",
        "tmpfs": {"/tmp":"size=512m"}
      }
    }
  }
Is it a correct configuration?

There is no a safari browser item on Selenoid UI in a capabilities section and I can not select the safari browser manually.

**Comment by vania-pooh** [comment]
@GolubNick seems to be correct. Once you add this section to `browsers.json`, it will appear in UI.

**Comment by GolubNick** [comment]
@vania-pooh My browser.json includes this section but this is absent on Selenoid UI.

**Comment by vania-pooh** [comment]
@GolubNick then you did not reload browsers.json in Selenoid.

**Comment by GolubNick** [comment]
I've used the command 'docker-compose up -d'

**Comment by GolubNick** [comment]
Is another command existed to reload browser.json?

**Comment by vania-pooh** [comment]
@GolubNick https://aerokube.com/selenoid/latest/#_reloading_configuration

**Comment by GolubNick** [comment]
@vania-pooh I did it but the result is the same. There is no Safari browser in capabilities of Selenoid UI.

**Comment by vania-pooh** [comment]
@GolubNick then you are editing wrong `browsers.json` file.

**Comment by GolubNick** [comment]
Hi @vania-pooh. Thank yo for your help. I've solved my issue. After docker-compose up -d --force-recreate command Safari browser was appeared in a list of browsers.

**Comment by premsingh19** [comment]
Hi All,
Do we still not solved this ? or can someone please let me know can I run my tests in Safari on docker?
