### ISSUE TITLE
can not start session on Centos7

### ISSUE THREAD

**Issue by DmytroPazykov** [aerokube/selenoid#665]
Hey there,

Env:
- Centos7 os
- latest docker
- selenoid 1.9.0

Steps to reproduce:
- Install non UI selenoid by default command 
> `curl -s https://aerokube.com/cm/bash | bash \
>     && ./cm selenoid start --vnc --tmpfs 128`
- A session has been started correctly and hud had been available on 4444
> 2019/02/06 09:37:52 [-] [INIT] [Loaded configuration from  /home/dmytro_pazykov@***.com/.aerokube/selenoid/browsers.json]
> 2019/02/06 09:37:52 [-] [INIT] [Logs Dir: /home/dmytro_pazykov@***.com/.aerokube/selenoid/logs]
> 2019/02/06 09:37:52 [-] [INIT] [Timezone: Local]
> 2019/02/06 09:37:52 [-] [INIT] [Listening on :4444]
- Connecting to the Selenoid Hub via RemoteWebDriver, but receiving error in tests
> UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
- Also selenoid console throwing:
>2019/02/06 09:39:14 [-] [NEW_REQUEST] [unknown] [10.6.62.158]
>2019/02/06 09:39:14 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.6.62.158]
>2019/02/06 09:39:14 [0] [LOCATING_SERVICE] [chrome] []
>2019/02/06 09:39:14 [-] [DEFAULT_VERSION] [Using default version: latest]
>2019/02/06 09:39:14 [0] [USING_DRIVER] [chrome] [latest]
>2019/02/06 09:39:14 [0] [ALLOCATING_PORT]
>2019/02/06 09:39:14 [0] [ALLOCATED_PORT] [35169]
>2019/02/06 09:39:14 [0] [STARTING_PROCESS] [[/home/dmytro_pazykov@***.com/.aerokube/selenoid/chromedriver --whitelisted-ips='' --verbose --port=35169]]
>2019/02/06 09:39:44 [0] [TERMINATING_PROCESS] [669]
>2019/02/06 09:39:44 http: panic serving 10.6.62.158:50030: interface conversion: io.Writer is nil, not *os.File
goroutine 9 [running]:
>net/http.(*conn).serve.func1(0xc0002a0d20)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1746 +0xd0
>panic(0x767360, 0xc0001c8630)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/panic.go:513 +0x1b9
>github.com/aerokube/selenoid/service.(*Driver).stopProcess(0xc0002a2f00, 0xc0000c4f20)
        /home/travis/gopath/src/github.com/aerokube/selenoid/service/driver.go:92 +0x3d5
>github.com/aerokube/selenoid/service.(*Driver).StartWithCancel(0xc0002a2f00, 0xc0002b8c50, 0x6, 0x0)
        /home/travis/gopath/src/github.com/aerokube/selenoid/service/driver.go:75 +0xdf8
>main.create(0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:174 +0x80b
>net/http.HandlerFunc.ServeHTTP(0x7eb6f8, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
>main.post.func1(0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/gopath/src/github.com/aerokube/selenoid/main.go:308 +0x9e
>net/http.HandlerFunc.ServeHTTP(0xc00025fba0, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
>github.com/aerokube/selenoid/protect.(*Queue).Protect.func1(0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:76 +0x3c2
>net/http.HandlerFunc.ServeHTTP(0xc0001ef3c0, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
>github.com/aerokube/selenoid/protect.(*Queue).Check.func1(0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:53 +0x9a
>net/http.HandlerFunc.ServeHTTP(0xc0001ef3e0, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
>github.com/aerokube/selenoid/protect.(*Queue).Try.func1(0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:35 +0xd4
>net/http.HandlerFunc.ServeHTTP(0xc0001ef400, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
>net/http.(*ServeMux).ServeHTTP(0xc0002da300, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2361 +0x127
>main.handler.func1(0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/gopath/src/github.com/aerokube/selenoid/main.go:370 +0x157
>net/http.HandlerFunc.ServeHTTP(0x7eb720, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1964 +0x44
>net/http.(*ServeMux).ServeHTTP(0xc00014ff50, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2361 +0x127
>net/http.serverHandler.ServeHTTP(0xc000067e10, 0x83a460, 0xc0002be0e0, 0xc0000f1100)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2741 +0xab
>net/http.(*conn).serve(0xc0002a0d20, 0x83a7e0, 0xc000294a40)
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:1847 +0x646
>created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/server.go:2851 +0x2f5`

**Comment by luker2** [comment]
@aandryashin @vania-pooh how should I work around this? Can I still use the curl method? Or how can I run with this latest bug fix?

**Comment by vania-pooh** [comment]
@luker2 this should just work in `aerokube/selenoid:latest` image. Will be released soon.

**Comment by vania-pooh** [comment]
@luker2 that was a bug in code (an unchecked cast which is only reproducing under RedHat \ CentOS) and we fixed it.

**Comment by prasanth-G24** [comment]
> @luker2 that was a bug in code (an unchecked cast which is only reproducing under RedHat \ CentOS) and we fixed it.

@vania-pooh are you sure the bus has been fixed? Because yesterday was the first time I decided to try selenoid and I configured it within 30 minutes on my ubuntu. But I've been trying to start the docker image in my centos machine for mor than 2 hours and still no luck. :(

**Comment by vania-pooh** [comment]
@prasanth-G24 please provide your Selenoid version and `browsers.json` contents.

**Comment by prasanth-G24** [comment]
> @prasanth-G24 please provide your Selenoid version and `browsers.json` contents.

@vania-pooh here's my browsers.json file:
```
{
    "chrome": {
        "default": "78.0",
        "versions": {
           "78.0": {
                "image": "selenoid/vnc_chrome:78.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "firefox": {
        "default": "70.0",
        "versions": {
            "70.0": {
                "image": "selenoid/vnc_firefox:70.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "opera": {
        "default": "64.0",
        "versions": {
            "64.0": {
                "image": "selenoid/vnc_opera:64.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    }
}
```
Selenoid version: aerokube/selenoid:1.9.3. And my docker API version is 1.40

**Comment by vania-pooh** [comment]
@prasanth-G24 this bug is about running Selenoid with standalone driver binaries. You have Docker images in your `browsers.json`. If you are still receiving a panic message like in issue description - please create a separate issue so we could investigate.
