### ISSUE TITLE
deleting file from download dir doesn't work

### ISSUE THREAD

**Issue by djordje-petrovic** [aerokube/selenoid#668]
So I try something like this:

```
`curl -vL -X DELETE -u test:test-password http://10.150.7.57:4445/download/548eba3d2534abeb03b7e6162388415c/image.jpg
*   Trying 10.150.7.57...
* TCP_NODELAY set
* Connected to 10.150.7.57 (10.150.7.57) port 4445 (#0)
* Server auth using Basic with user 'test'
> DELETE /download/548eba3d2534abeb03b7e6162388415c/image.jpg HTTP/1.1
> Host: 10.150.7.57:4445
> Authorization: Basic dGVzdDp0ZXN0LXBhc3N3b3Jk
> User-Agent: curl/7.63.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 38760
< Content-Type: image/jpeg
< Date: Fri, 08 Feb 2019 12:03:10 GMT
< Last-Modified: Thu, 07 Feb 2019 15:42:24 GMT
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 3923)`
```

But nothing happens. And you can see the output. So what am I doing wrong here?

**Comment by vania-pooh** [comment]
@djordje-petrovic this feature is partially implemented on browser images side and only recent browser versions should contain a binary that supports deleting.

**Comment by djordje-petrovic** [comment]
@vania-pooh Could you be please more speficic? Which images have fileserver bin that can delete files? I'm using selenoid/chrome:72.0 and this one should have it right? Of built opon base_4, right?

https://github.com/aerokube/selenoid-images/blob/master/selenium/base/base_4/fileserver/main.go#L16-L41

**Comment by BorisOsipov** [comment]
Ran into the same issue with `"browsers":{"chrome":{"73.0":{}}`

**Comment by vania-pooh** [comment]
@djordje-petrovic unfortunately this was implemented but never built into images.
