### ISSUE TITLE
Issue with file uploads with specific characters

### ISSUE THREAD

**Issue by pdruzhinin** [aerokube/selenoid#669]
Unable to upload a file called 'PDF_ùâàæ.pdf'.

03:17:33 org.openqa.selenium.WebDriverException: unknown error: unable to unzip 'file'
03:17:33 from unknown error: archive error: (unknown error: could not unzip archive), entry error: (unknown error: invalid data descriptor signature)
03:17:33   (Session info: chrome=70.0.3538.67)
03:17:33   (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 3.16.0-4-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
03:17:33 Command duration or timeout: 0 milliseconds
03:17:33 Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
03:17:33 System info: host: '-', ip: '-', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_181'
03:17:33 Driver info: org.openqa.selenium.remote.RemoteWebDriver
03:17:33 Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600233 (523efee95e3d68..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:45389}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 70.0.3538.67, webStorageEnabled: true}

**Comment by vania-pooh** [comment]
@pdruzhinin seems to be images-specific issue.

**Comment by pdruzhinin** [comment]
@vania-pooh as in 'issue specific to Chrome image'?
Is there anything I can do to provide more information and get this resolved?

**Comment by vania-pooh** [comment]
@pdruzhinin could you try whether the same stuff is reproducing when uploading directly to Docker image port. E.g. run Chrome image instead of Selenoid as follows:
```
$ docker run -d --name chrome-test -p 4444:4444 selenoid/chrome:71.0
```
And then use `http://localhost:4444/` as Selenium URL of the same test. If it does - then we'll take a look what's happening inside the image.

**Comment by pdruzhinin** [comment]
@vania-pooh the error is different when I do it locally:

org.openqa.selenium.WebDriverException: invalid argument: File not found : E:\-\testautomation\-\testdata\content\pdf\unique-character PDF_ÃƒÂ¹ÃƒÂ¢ÃƒÂ ÃƒÂ¦.pdf
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.9.125-linuxkit x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: '-', ip: '-', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.44.609551 (5d576e9a44fe4c..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:38927}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 71.0.3578.80, webStorageEnabled: true}
Session ID: b33341da6f502fdf763852ef42e9e477

**Comment by vania-pooh** [comment]
@pdruzhinin seems to be space characher escaping issue in this case.

**Comment by pdruzhinin** [comment]
@vania-pooh actually it was an issue with encoding, once I fixed it I get the same error as before:

```
org.openqa.selenium.WebDriverException: unknown error: unable to unzip 'file'
from unknown error: archive error: (unknown error: could not unzip archive), entry error: (unknown error: invalid data descriptor signature)
  (Session info: chrome=71.0.3578.80)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.9.125-linuxkit x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:22.379Z'
System info: host: '-', ip: '-', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.44.609551 (5d576e9a44fe4c..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:38867}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 71.0.3578.80, webStorageEnabled: true}
Session ID: 860c48aabf0069221105c0a4b0348055
```

Once I rename the file from 'unique-character PDF_ùâàæ.pdf' to 'unique-character PDF.pdf' the error is gone.
