### ISSUE TITLE
screenResolution example

### ISSUE THREAD

**Issue by SergeyPirogov** [aerokube/selenoid#67]
There is no clear understanding how to pass screenResolution: 1280x1024x24 value. Should I pass them via desired capabilities or put them in config.json file. The same with enableVNC

**Comment by vania-pooh** [comment]
@SergeyPirogov regarding screen resolution see https://github.com/aerokube/selenoid#custom-screen-resolution. Regarding VNC docs - will be added in https://github.com/aerokube/selenoid/issues/65.

**Comment by vania-pooh** [comment]
@SergeyPirogov btw, in your opinion is documentation large enough to be moved to wiki from README.md? I think currently we need good table of contents.

**Comment by SergeyPirogov** [comment]
Actually this link https://github.com/aerokube/selenoid#custom-screen-resolution says **pass screenResolution capability in your tests**. Is it should look like below?

```
chrome_capabilities=DesiredCapabilities.CHROME
chrome_capabilties['screenResolution']='1980x2014x24'
driver = webdriver.Remote()
```

**Comment by SergeyPirogov** [comment]
@vania-pooh Regarding documentation, I think will be nice to have singe place in Github Wiki, where people can find all the required information about set up and configuration for selenoid and selenoid-ui

**Comment by vania-pooh** [comment]
@SergeyPirogov yes, just pass this capability. Your code seems to be correct. Default value is 1920x1080x24.

**Comment by vania-pooh** [comment]
@SergeyPirogov did it help? Do you consider the issue resolved?

**Comment by SergeyPirogov** [comment]
Yes, but still waiting for example with VNC

**Comment by aandryashin** [comment]
Could you please check it with screenshot? Just point browser to
http://yandex.ru/internet/ and see that screen resolution is changed.

2017-05-05 9:52 GMT+03:00 Serhii Pirohov <notifications@github.com>:

**Comment by vania-pooh** [comment]
@SergeyPirogov sure, will create docs during this weekend.

**Comment by vania-pooh** [comment]
http://aerokube.com/selenoid/latest/#_live_browser_screen Done.
