### ISSUE TITLE
Chrome in docker cannot transform large xml  

### ISSUE THREAD

**Issue by dr29bart** [aerokube/selenoid#675]
docker images:
aerokube/selenoid:1.9.0
selenoid/vnc_chrome:72.0

config:
```
{
    "chrome": {
        "default": "72.0",
        "versions": {
            "72.0": {
                "image": "selenoid/vnc_chrome:72.0",
                "port": "4444",
                "path": "/",
                "env": [
                    "ENABLE_WINDOW_MANAGER=true"
                ],
                "tmpfs": {"/tmp": "size=1024m", "/var": "size=512m"},
                "shmSize" : 968435456
            }
        }
    }
}
```

```Java
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.MalformedURLException;
import java.net.URL;

public class T {

    private static RemoteWebDriver iniDriver() throws MalformedURLException {
        ChromeOptions capabilities = new ChromeOptions();
        capabilities.setCapability("screenResolution", "1920x1080");
        capabilities.setCapability("enableVNC", true);
        return new RemoteWebDriver(new URL("http://selenoidhost.com:4444/wd/hub"), capabilities);
    }

    public static void main(String[] args) throws MalformedURLException {
        RemoteWebDriver remoteWebDriver = iniDriver();
        try {
            remoteWebDriver.get("https://dr29bart.github.io/");
            remoteWebDriver.findElement(By.cssSelector("input")).click();
            Alert alert = new WebDriverWait(remoteWebDriver, 20)
                    .until(ExpectedConditions.alertIsPresent());
            System.out.println(alert.getText());
            alert.dismiss();
        } finally {
            remoteWebDriver.quit();
        }
    }
}
```
Actual console output:
```TypeError: Cannot read property 'firstChild' of null```

Expected output:
```[object Text]```

The same code works fine with local chrome driver instance.
[chrome_container.log](https://github.com/aerokube/selenoid/files/2880060/chrome_container.log)
[selenoid.log](https://github.com/aerokube/selenoid/files/2880042/selenoid.log)

**Comment by BorisOsipov** [comment]
@dr29bart It will be nice if you describe\add stacktrace what happened when you ran this test against selenoid.

**Comment by dr29bart** [comment]
There is only one issue, which is a failure of js snippet in dockerized Chrome :
```
var p = new XSLTProcessor;
p.importStylesheet(xsl);
var c = p.transformToFragment(xml, document)
```

_transformToFragment_ returns **null** if xml is very large.

I was not able to reproduce this issue on Mac/Win 10/(Ubuntu in Virtual VM)
Also tuning tmpfs or shmSize parameters didn't allow me to work around the issue.

**Comment by vania-pooh** [comment]
@dr29bart what is XSLTProcessor?

**Comment by dr29bart** [comment]
It is [Blink implementation](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/xml/xslt_processor.cc?rcl=2c9e45e5e509473a935a198652628c58e9b99d5b&l=135) of the [WEB API: XSLTProcessor](https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor).

**Comment by vania-pooh** [comment]
@dr29bart ah ok, an internal JS API.
