### ISSUE TITLE
Testing with MicrosoftEdge target times out

### ISSUE THREAD

**Issue by jjballesteros69** [aerokube/selenoid#677]
Hello,

We are starting to use selenoid and so far we have finished our setup.  All browsers works fine but Microsoft Edge.    The process starts but for some unknown reason, selenoid can not start the browser.

This is the console output:

2019/02/21 09:04:00 [-] [NEW_REQUEST] [unknown] [192.168.21.130]
2019/02/21 09:04:00 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.21.130]
2019/02/21 09:04:00 [2873] [LOCATING_SERVICE] [MicrosoftEdge] []
2019/02/21 09:04:00 [-] [DEFAULT_VERSION] [Using default version: latest]
2019/02/21 09:04:00 [2873] [USING_DRIVER] [MicrosoftEdge] [latest]
2019/02/21 09:04:00 [2873] [ALLOCATING_PORT]
2019/02/21 09:04:00 [2873] [ALLOCATED_PORT] [53759]
2019/02/21 09:04:00 [2873] [STARTING_PROCESS] [[C:\Windows\syswow64\MicrosoftWebDriver.exe --host=127.0.0.1 --verbose --port=53759]]
2019/02/21 09:04:30 [2873] [TERMINATING_PROCESS] [7036]
2019/02/21 09:04:30 [2873] [FAILED_TO_TERMINATE_PROCESS] [7036] [TerminateProcess: Access is denied.]
2019/02/21 09:04:30 [2873] [SERVICE_STARTUP_FAILED] [http://127.0.0.1:53759/ does not respond in 30s]

The Microsoft Web Driver version is 10.0.10240.0

Any help will be highly appreciated.

Thanks

**Comment by vania-pooh** [comment]
@jjballesteros69 you could try to start the command directly and see what happens:
```
C:\Windows\syswow64\MicrosoftWebDriver.exe --host=127.0.0.1 --verbose --port=53759
```
You should then access Selenium using the following URL:
```
http://localhost:53759/ (or probably http://localhost:53759/wd/hub)
```

**Comment by jjballesteros69** [comment]
Hello @vania-pooh 

I guess I found the reason it does not start. Look at the output. It seems the version of MicrosoftWebDriver does not support the supplied options.

```
C:\Users\calidad\.aerokube\selenoid>C:\Windows\syswow64\MicrosoftWebDriver.exe --host=127.0.0.1 --verbose --port=53759
Usage:
 MicrosoftWebDriver.exe --host=<HostName> --port=<PortNumber> --package=<Package>
```

How should I configure browser.json to make it work?

Thanks

**Comment by vania-pooh** [comment]
@jjballesteros69 just open `browsers.json` (default location is `C:\Users\<your-user>\.aerokube\selenoid\browsers.json`) in text editor and remove `--verbose` flag. Then restart Selenoid process.

**Comment by jjballesteros69** [comment]
Hello @vania-pooh

I am so sorry.  When I saw the output of the command I realized that maybe it was a version mismatch.

I upgraded Windows 10 to 1803 version and upgraded MicrosoftWebDriver to 10.0.1734.0 and now it works like a charm.

Thanks for the support that lead us to solve this issue.
