### ISSUE TITLE
VNC capability on windows

### ISSUE THREAD

**Issue by jjballesteros69** [aerokube/selenoid#679]
Hello,

More than an issue, this is a question.

Is there a way to record the tests on Windows and Mac?

In advance, thank you very much.

**Comment by vania-pooh** [comment]
@jjballesteros69 video recording does not work. The only way to have VNC right now is by starting VNC server on Windows \ Mac machine manually and then proxy their traffic using Ggr feature: https://aerokube.com/ggr/latest/#_proxying_vnc_traffic

**Comment by jjballesteros69** [comment]
@vania-pooh thanks for the reply.

is there a way to capture png files or bmp files with the pages displayed during the test?

Thanks.

**Comment by vania-pooh** [comment]
@jjballesteros69 taking screenshots is a built-in Selenium feature and will work. Screenshots are taken to png format.

**Comment by jjballesteros69** [comment]
@vania-pooh thanks.

I guess now I have to figure out how to make it work from selenium-side-runner.

**Comment by vania-pooh** [comment]
@jjballesteros69 a typical Java screenshot test looks like the following: https://github.com/aerokube/demo-tests/blob/master/src/test/java/com/aerokube/selenoid/DemoTest.java
