### ISSUE TITLE
selenoid-ui not loading running sessions with error

### ISSUE THREAD

**Issue by amitverma12** [aerokube/selenoid#681]
Hi, 
I have both selenoid & selenoid-ui running as docker container on RHEL7.6. When I connect to the selenoid-ui remotely, it displays the UI but it is not loading any running session. Following 
messages about status are logged in the container-log. 

How can I resolve this issue?

$ docker logs -f selenoid-ui
2019/02/26 19:22:13 Listening on :8080
2019/02/26 19:22:41 can't get status (invalid character '<' looking for beginning of value)
2019/02/26 19:22:41 Client added. 1 registered clients
2019/02/26 19:22:43 can't get status (invalid character '<' looking for beginning of value)
2019/02/26 19:22:43 Removed client. 0 registered clients
2019/02/26 19:22:45 Client added. 1 registered clients
2019/02/26 19:22:45 can't get status (invalid character '<' looking for beginning of value)
2019/02/26 19:22:48 can't get status (invalid character '<' looking for beginning of value)
2019/02/26 19:22:48 Removed client. 0 registered clients

Thanks!
Amit

**Comment by vania-pooh** [comment]
@amitverma12 this error message means Selenoid UI is receiving non-JSON content (e.g. HTML or XML) from Selenoid `/status` API. Try to do the following request:
```
$ curl http://selenoid-host.example.com:4444/status
```
And make sure that is returns JSON.

**Comment by amitverma12** [comment]
@vania-pooh - Thanks for your response. I am starting both selenoid & selenoid-ui as docker containers.
if I do curl for status on localhost I get xml with error but if I give the hostname, it returns a json.

I tried starting selenoid-ui with hostname as argument & it started giving 

$  ./cm selenoid-ui start --args "--selenoid-uri=http://hostname:4444"

[tvisadm@da3d-gen-tvz-app005 ~]$ docker logs -f selenoid-ui
2019/02/27 16:21:42 Listening on :8080
2019/02/27 16:21:44 Client added. 1 registered clients
2019/02/27 16:21:50 can't get status (context deadline exceeded)
2019/02/27 16:21:55 can't get status (context deadline exceeded)
2019/02/27 16:22:00 can't get status (context deadline exceeded)

Do I need to give the hostname argument for starting selenoid-ui when I am using `cm` for starting both containers?

**Comment by amitverma12** [comment]
@vania-pooh - Thanks for your response. I am starting both selenoid & selenoid-ui as docker containers.
if I do curl for status on localhost I get xml with error but if I give the hostname, it returns a json.

I tried starting selenoid-ui with hostname as argument & it started giving

$ ./cm selenoid-ui start --args "--selenoid-uri=http://hostname:4444"

[user@hostname ~]$ docker logs -f selenoid-ui
2019/02/27 16:21:42 Listening on :8080
2019/02/27 16:21:44 Client added. 1 registered clients
2019/02/27 16:21:50 can't get status (context deadline exceeded)
2019/02/27 16:21:55 can't get status (context deadline exceeded)
2019/02/27 16:22:00 can't get status (context deadline exceeded)

Do I need to give the hostname argument for starting selenoid-ui when I am using `cm` for starting both containers?

**Comment by vania-pooh** [comment]
@amitverma12 if both containers are running on the same host then defaults (`http://selenoid:4444/`) should work because `CM` automatically links Selenoid UI to Selenoid container and Selenoid container name is `selenoid`. So basically you need to somehow point Selenoid UI to Selenoid.

**Comment by amitverma12** [comment]
@vania-pooh - based on the `ps` output it seems to be linking correctly 

`root     13604 13581  1 16:46 ?        00:00:00 /selenoid-ui --selenoid-uri=http://selenoid:4444`

But I'm getting the original issue with it

2019/02/27 16:46:37 Listening on :8080
2019/02/27 16:47:47 can't get status (invalid character '<' looking for beginning of value)
2019/02/27 16:47:48 Client added. 1 registered clients

Thanks!
Amit

**Comment by vania-pooh** [comment]
@amitverma12 couldn't it be because of some proxies configured on your host?

**Comment by amitverma12** [comment]
@vania-pooh Yes, I do see a proxy configured on the vm to reach docker-hub. How can I work around it.
Thanks!

**Comment by vania-pooh** [comment]
@amitverma12 not sure but Selenoid UI don't need any external Internet access.

**Comment by amitverma12** [comment]
@vania-pooh Ok, thanks for your help. We can close this issue.
