### ISSUE TITLE
Selenoid/video-recorder subtitles functionality

### ISSUE THREAD

**Issue by SandRocks99** [aerokube/selenoid#685]
Hi guys,

Selenoid/video-recorder functionality is super nice, all the stakeholders are super happy to see what's actually happening with the testCase executions and also, that could also be used to debug/ demo our product to the customers. A big thanks to you guys :)

**Issue/ new feature** : Do we have "adding subtitles to video" functionality already, Would it be possible to add this as a new feature, please?

**Use Case** : Instead of watching just a muted video, It would make a complete sense to add customized subtitles to the video while the testscase execution happens.

**reference** : something like this : _Referencing test steps in the recorded video_
https://opensource.zalando.com/zalenium/#usage

Thanks so much in advance,
Sandy

**Comment by vania-pooh** [comment]
@SandRocks99 currently Selenoid video recording captures everything on the screen where the browser is actually executing. So far as I understood this works by executing a shell command inside browser image. Let me see what can be done with it.

**Comment by SandRocks99** [comment]
@vania-pooh , thanks so much for your quick response. We love Selenoid and wanna keep using it. Adding the feature would be cherry on top !

**Comment by SandRocks99** [comment]
@vania-pooh , do we have any ETA for the feature or is that targeted for any upcoming release ?
Kindly advise.

Thanks so much in advance,
Sandy

**Comment by vania-pooh** [comment]
@SandRocks99 we will add a milestone to issue one this is planned.

**Comment by leorush** [comment]
@SandRocks99 Why don't you use external subtitles? For ex. https://matroska.org/technical/specs/subtitles/srt.html
