### ISSUE TITLE
android container issue

### ISSUE THREAD

**Issue by jsa34** [aerokube/selenoid#687]
After creating android / chrome image using the video on your YouTube channel, I have got the following error when sending tests to this newly-created container:

```
/bin/bash:
 warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
* daemon not running; starting now at tcp:****
emulator: Android virtual device file at: /root/.android/avd/android8.0-1.ini
emulator: virtual device content at /root/.android/avd/android8.0-1.avd
emulator: virtual device config file: /root/.android/avd/android8.0-1.avd/config.ini
emulator: using core hw config path: /root/.android/avd/android8.0-1.avd/hardware-qemu.ini
emulator: using snapshot lock path: /root/.android/avd/android8.0-1.avd/snapshot.lock
emulator: using multi-instance lock path: /root/.android/avd/android8.0-1.avd/multiinstance.lock
emulator: Found AVD target API level: 26
emulator: Read property file at /opt/android-sdk-linux/system-images/android-26/google_apis/x86//build.prop
emulator: No boot.prop property file found.
emulator: autoconfig: -kernel /opt/android-sdk-linux/system-images/android-26/google_apis/x86//kernel-ranchu
emulator: Target arch = 'x86'
emulator: Auto-config: -qemu -cpu qemu32
emulator: Auto-detect: Kernel image requires new device naming scheme.
emulator: Auto-detect: Kernel does not support YAFFS2 partitions.
emulator: autoconfig: -ramdisk /opt/android-sdk-linux/system-images/android-26/google_apis/x86//ramdisk.img
emulator: Using initial system image: /opt/android-sdk-linux/system-images/android-26/google_apis/x86//system.img
emulator: Using initial vendor image: /opt/android-sdk-linux/system-images/android-26/google_apis/x86//vendor.img
emulator: autoconfig: -data /root/.android/avd/android8.0-1.avd/userdata-qemu.img
emulator: autoconfig: -initdata (null)
emulator: autoconfig: -cache /root/.android/avd/android8.0-1.avd/cache.img
emulator: Increasing RAM size to 1536MB
emulator: VM heap size 0MB is below hardware specified minimum of 192MB,setting it to that value
emulator: WARNING: System image is writable
emulator: Found 3 DNS servers: ******, ******, ******
emulator: there is no '1080x1920' skin in '/opt/android-sdk-linux/platforms/android-26/skins/'
emulator: found magic skin width=1080 height=1920 bpp=16

emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
* daemon started successfully
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found
```

Any help would be much appreciated!

**Comment by vania-pooh** [comment]
@jsa34 the reason in inside your log:
```
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
```
These images will only work on hardware server or on a VM with nested virtualization support.

**Comment by jsa34** [comment]
Aha - such a quick response!  Thank you!  I will have to see if I can sort this out.

**Comment by jsa34** [comment]
Ah - alas, not possible :(  Just spoken to VM team who have said we are using VM ware and this is not supported by them (VMware) and they have not implemented it :(

**Comment by jsa34** [comment]
Thank you for your help - I will investigate other options (looks like running on bare metal)

**Comment by aandryashin** [comment]
Actually VMWare allows nested virtualization, i can confirm it. Please ask
your vm team enable nested virtualization for you vm.

чт, 7 мар. 2019 г., 14:47 jsa34 <notifications@github.com>:

**Comment by jsa34** [comment]
Hello!

You are right... However, what is possible and what is allowed are two different things - unfortunately, this one is only the forme rand not the latter :(

On a side note, I tried implementing this solution on a Mac, but when I try and run the tests I get:
WebDriverException: cannot start process... fork/exec ... no such file or directory.

When I look in docker image ls, it is definitely there with the correct version and name.

Is it supposed to work on Macs?

**Comment by julialiuliu** [comment]
I have exactly the same issue when trying to launch the Android docker image on Mac OS.

emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!

Does any know how to make it work on Mac OS ?  Or do I have to use linux system to run the Android docker image?

**Comment by vania-pooh** [comment]
@julialiuliu Docker for Mac does not forward KVM so it will not work. It is Docker limitation.

**Comment by julialiuliu** [comment]
@vania-pooh , thank you for the quick response. 
So I have to switch to Linux?  No solution on Mac, right?

**Comment by aandryashin** [comment]
On mac it is possible to install VMWare Fusion, create vm with nested
virtualization enabled and install linux on it. Such vm is able to run
android within docker container...

чт, 16 мая 2019 г., 10:14 Julia Liu <notifications@github.com>:

**Comment by julialiuliu** [comment]
Thank you @aandryashin for your reply. Got it.

**Comment by julialiuliu** [comment]
Did anyone try to run the Android docker image on AWS EC2 instance?  
I am facing 3 layers nested virtualisation issue.  The docker log on EC2 is the same as I run it on Mac OS.  :)

**Comment by aandryashin** [comment]
The only way to run android images on AWS is to use bare-metal instances..

пн, 20 мая 2019 г., 0:46 Julia Liu <notifications@github.com>:

**Comment by julialiuliu** [comment]
Appreciate your quick response. 

I am trying to build an Android arm emulator using "automate_android.sh" now (try to avoid 3 layers nested virtualisation on EC2)

I modified "x86" to "arm64" in automation_android.sh and Dockerfile.  Does it sound doable to build an Android arm emulator instead of "x86"?

**Comment by vania-pooh** [comment]
@julialiuliu it should be doable however all these scripts were tested on x86 only. And the most annoying this with arm - they are very very very slow compared to x86.

**Comment by julialiuliu** [comment]
@vania-pooh  thank you very much for your following up. 
So all the testing you guys did are on the Linux or Ubuntu server? 
It would be great if we could specify the test environment in the readme file for selenoid android image. 
I tried on MacOS, then AWS EC2 (m5.large).  All got the bottleneck - the nested virtualization.  
I will try selenoid android docker image on a physical Linux server tomorrow.

**Comment by vania-pooh** [comment]
@julialiuliu yes, we are testing everything on hardware Linux servers.

**Comment by Grosha** [comment]
@vania-pooh I tried to use VirtualBox instead of WMware tool but I have the same error in android container:

```
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm

PORT=5900
* daemon started successfully
error: no devices/emulators found
```

If talk about vm - is it posible only with WMWare tool?

**Comment by Grosha** [comment]
@vania-pooh I find unswer - it doesn't support for that moment
https://askubuntu.com/questions/328748/how-to-enable-nested-virtualization-in-ubuntu

**Comment by vania-pooh** [comment]
@Grosha yes, VMWare is known to work with nested KVM.

**Comment by iblfw** [comment]
@vania-pooh hi, I meet the issue "ERROR: x86 emulation currently requires hardware acceleration!" in windows 1809 too. Hyper-V Android Emulator in windows need to Update to Android emulator version 27.2.7 or newer versions. Does  Selenoid/android:8.1 image work in windows by Hyper-v? Which version is Android Api in the image?

**Comment by vania-pooh** [comment]
@iblfw Android images will not work in Windows just because Docker for Windows does not forward `/dev/kvm`.
