### ISSUE TITLE
Need Help:  Is there a way to set credentials for selenoid to secure it in public cloud?

### ISSUE THREAD

**Issue by ghost** [aerokube/selenoid#689]
I have selenoid on VM which are present in public cloud, 

I would like to secure selenoid nodes to avoid execution apart form my script. 

Is there any way like a GGR we can set username/password for selenoid nodes. 

Appreciate help. Thanks in Advance.

**Comment by aandryashin** [comment]
There is another our project that:
https://github.com/aerokube/ggr
Ggr allows group many selenoids in cluster and assign quota to users...

чт, 7 мар. 2019 г., 23:45 vikas-thange-twc <notifications@github.com>:

**Comment by vikas-thange-twc** [comment]
Thanks @aandryashin but my Questions without using GGR. I only wants to use Selenoid standalone node with security.

**Comment by aandryashin** [comment]
You can secure standalone selenoid by nginx...

пн, 11 мар. 2019 г., 7:55 vikas-thange-twc <notifications@github.com>:
