### ISSUE TITLE
Unable to access downloaded files inside docker container volume

### ISSUE THREAD

**Issue by gthavaprasad** [aerokube/selenoid#695]
While Selenoid provides the API's to download the files, we were trying to map the Downloads folder inside the container, to the local machine's file system.

We are able to see the files through the download API, but we were unable to find the same files in the container volumes

It would help, if someone can let us know where the files are being stored in the container volume, so that we can map to local machines volume.

docker run -d --name selenoid                     \
-p 4444:4444                                    \
-v ~/.aerokube/selenoid/:/etc/selenoid/:ro      \
-v /var/run/docker.sock:/var/run/docker.sock    \
aerokube/selenoid:latest-release                \
**-v /Users/username/Download/:/home/selenium/Downloads/**   \
-video-output-dir /opt/selenoid/video/ -mem 1g -cpu 1.0

Thanks in advance.

**Comment by aandryashin** [comment]
It is already implemented in selenoid, please check this:
https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser

ср, 13 мар. 2019 г., 9:08 gthavaprasad <notifications@github.com>:

**Comment by gthavaprasad** [comment]
Hi @aandryashin ..  Thanks for replying. I agree we do have this feature..  but i was unable to find the folder within the container where i can fetch the downloaded files

We have checked the /home/selenium/Downloads/  folder inside the container, but were unable to find any downloaded files there.
-v /Users/username/Download/:/home/selenium/Downloads/

**Comment by aandryashin** [comment]
You can access downloaded files via http, use urls like this:
http://selenoid-host.example.com:4444/download/f2bcd32b-d932-4cdc-a639-687ab8e4f840/myfile.txt
You do not have to mount directory, selenoid already hosts downloads folder
for you.

ср, 13 мар. 2019 г., 10:01 gthavaprasad <notifications@github.com>:

**Comment by gthavaprasad** [comment]
Thanks @aandryashin..  we are able to access  it through url's, as you had mentioned, for some of the projects..  We were checking on the path of the selenoid hosted downloads folder inside the container, which we were unable to find.
We will continue to use download API's, for accessing the downloaded files. It would help if we know the selenoid hosted downloads folder inside the contianer.

**Comment by vania-pooh** [comment]
@gthavaprasad correct path is `/home/selenium/Dowloads`.

**Comment by gthavaprasad** [comment]
@vania-pooh..  We do not see the files downloaded to the mentioned folder, though we are able to see the files through download API's. Am i missing anything in the configuration?

 _/home/selenium/Downloads_

**Comment by vania-pooh** [comment]
@gthavaprasad this directory is inside browser image.

**Comment by gthavaprasad** [comment]
Thanks @vania-pooh...  We do see the downloads in the browser container..  We were searching them in the selenoid container.

Thanks again for clarifying!!

**Comment by timothyjmtan** [comment]
Hello, sorry for the hijack but I would like to ask a related question -- in the following setup:

`local machine (windows) --> host container (linux) --> browser container`

When a file is downloaded, the downloaded file resides in the browser container (`~/Downloads` or `/home/selenoid/Downloads`). In order to 'retrieve' this file, we can curl the API endpoint to download the file.

I would like to check where does this downloaded file reside in -- the host container? If so, how does the local machine which triggered the test access this file, since the paths to store downloaded files in windows (`C:\Users\foo\bar`) and linux (`/home/foo/bar`) will be different?

**Comment by gthavaprasad** [comment]
@timothyjmtan, the downloaded files reside in the `browser container`, and the correct path as mentioned in this thread is `/home/selenium/Downloads`

We leveraged the Download API's provided by Selenoid to download the files to our desired folder, rather than working with the file system. I believe this should work for your setup as well.

**Comment by timothyjmtan** [comment]
@girish-tp  Thanks for the quick response.

From my understanding, if we try to execute a curl command from within our automation script, it will still eventually be executed by the host container, and as such the file will be downloaded to the host container instead of the local machine, is that correct? Are you guys calling the API manually from outside the selenoid stack?

**Comment by girish-tp** [comment]
@timothyjmtan, if the automation script is being run in the local machine(Windows), then the Curl command would be executed in local machine, downloading the files to local machine itself. We would just need Curl to be installed in the local windows machine.

We leveraged Java HTTP libraries to download the files, through Selenoid Download API, to the local machine. Yes, we are calling API, outside of the Selenoid stack.

**Comment by Prasad1982-CTR** [comment]
@girish-tp , It would be great if you  share  how you have written the the java http libraries to download the files through Selenoid Download API, to the local machine.

**Comment by Viraaelka** [comment]
Guys, could you please help me?

I cannot read file Files.readAllBytes(Paths.get("/home/selenium/Downloads/" + fileName + "." + fileType));

It wrote me:
java.io.FileNotFoundException: \home\selenium\Downloads\24_12_2020.docx (The system cannot find the path specified)
however, the path to the file is /home/selenium/Downloads/24_12_2020.docx
I tried to use File.separator and System.getProperty("file.separator") but it did not help out.

I need to read the file and check that it is not empty...

**Comment by vania-pooh** [comment]
@Viraaelka this directory is inside browser container whereas your testing could be running in a separate container \ host.

**Comment by Viraaelka** [comment]
Hi Ivan, 
 
Thank you very much for your answer.
Could you please advise how I can extract this file or get into within test session? I just wanna check that it is not empty..
 
Thank you in advance,
Elvira 
>Четверг, 24 декабря 2020, 19:44 +03:00 от Ivan Krutov <notifications@github.com>:
> 
> 
>@Viraaelka this directory is inside browser container whereas your testing could be running in a separate container \ host.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Эльвира

**Comment by vania-pooh** [comment]
@Viraaelka see https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser.
