### ISSUE TITLE
Videos don't upload to AWS

### ISSUE THREAD

**Issue by Cdooom** [aerokube/selenoid#698]
I manually pulled your code and spun an ec2 instance. I ran this command inside the spun up docker container. Can't seem to get videos to upload to AWS correctly. I know permissions are correct since, I am pulling configs from my s3 bucket. Can you tell me what i'm missing?

/usr/bin/selenoid -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -log-output-dir /opt/selenoid/logs -s3-region 'us-east-1' -s3-bucket-name 'qa1-selenium-videos'

**Comment by vania-pooh** [comment]
@Cdooom what's inside Selenoid logs? There should be a line about failed file upload in the logs? According to documentation more flags are needed:
```
$ ./selenoid -s3-endpoint https://s3.us-east-2.amazonaws.com -s3-region us-east-2 -s3-bucket-name my-bucket -s3-access-key <your-access-key> -s3-secret-key <your-secret-key>
```
Access and secret keys are optional, as internally we are using official Amazon Golang client (it is able to read credentials from environment variables or configuration file in home directory). Probably you are using incorrect S3 endpoint URL. Full list of S3 endpoints for every region is here: https://docs.aws.amazon.com/general/latest/gr/rande.html (need to scroll a bit to section related to S3).

**Comment by Cdooom** [comment]
So I passed through the s3 endpoints... Here's the error i'm getting from my cloudwatch logs for my selenoid container....

![image](https://user-images.githubusercontent.com/24485546/54467690-06445300-4744-11e9-9e3c-35e6e1643084.png)

**Comment by vania-pooh** [comment]
@Cdooom this is because you did not specify an S3 endpoint explicitly using `-s3-endpoint` flag. Just try to add this flag as shown above.

**Comment by Cdooom** [comment]
Problem fixed! I passed through the s3 endpoint and AWS access and secret keys specifically.

**Comment by vania-pooh** [comment]
@Cdooom good, closing then.
