### ISSUE TITLE
Unable to docker pull selenoid/vnc_chrome

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid#701]
Hello. I am unable to execute the docker command to grab the latest vnc_chrome image from: 
https://hub.docker.com/r/selenoid/vnc_chrome

`docker pull selenoid/vnc_chrome`

The below response is returned:
```
Using default tag: latest
Error response from daemon: manifest for selenoid/vnc_chrome:latest not found
```

Could I ask if this is expected behaviour?

**Comment by aandryashin** [comment]
There is no latest tag for that image, please use tag 73.0.

ср, 20 мар. 2019 г., 9:29 timothyjmtan <notifications@github.com>:

**Comment by timothyjmtan** [comment]
Thanks for the quick reply, it works!

**Comment by rvvincelli** [comment]
@timothyjmtan Why there's no `latest` tag, actually? This way we have to keep up with the release tags, if we want to run only on, say, the latest three or four releases. I might be missing something though. Could you elaborate? Thanks,

**Comment by vania-pooh** [comment]
@rvvincelli because on some browsers like Firefox `latest` will simply not work.

**Comment by rvvincelli** [comment]
> @rvvincelli because on some browsers like Firefox `latest` will simply not work.

Ok @vania-pooh ! Say that we want to run our tests only on the latest supported browser version, for each browser. Right now it is `96.0` for Chrome. I thought to get smart with the tag, but I see this is not possible. How would you suggest to go about it? Is manually bumping up to `96.0` in the user section in the config map the best option, or do you see a better way?

Thank you,

**Comment by vania-pooh** [comment]
@rvvincelli e.g. CM tools is fetching image tags from Docker Hub. So doing something like this could help:

```
$ cm selenoid configure --force --last-versions 2 --browsers "firefox;chrome"
$ docker kill -s HUP selenoid
```

**Comment by rvvincelli** [comment]
@vania-pooh Thank you for this oneliner! We are actually using Moon on DigitalOcean (free plan), as managing our own grid was too much work really :) I guess I can automate out some `kubectl apply` to update the map with the desired versions.

**Comment by vania-pooh** [comment]
@rvvincelli next Moon version will have versions auto-update. E.g. for Chrome version X it will automatically try to pull image like `browsers/chrome:X`.

**Comment by rvvincelli** [comment]
@vania-pooh Sorry for the repo confusion, I just piggybacked the first issue from the search. Awesome news! Last question: will we have to reinstall the Moon cluster? Coming from Azure, not sure how "managed" is a managed solution in Digitalocean.
Many thanks for Moon and your team contributions to the community.

**Comment by vania-pooh** [comment]
@rvvincelli yes, new version will be a major upgrade and will require configuration.`
