### ISSUE TITLE
Unable to download files

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid#702]
**Issue overview**
Whenever the script attempts to download a file, the user is unable to do so, and the downloaded file (as seen from the selenoid-ui session) returns a status of `Failed - Download error`.

**What steps were done**
1. Download selenoid docker image
2. Download selenoid/vnc:chrome_71.0 image
3. Start up selenoid and selenoid-ui with vnc enabled
4. Create a test with the following steps:
    i. Navigate to any website
    ii. Find a hyperlink that when clicked, downloads a file (it was a pdf in my instance)
5. Run the test from a windows machine
6. Notice that the script is able to navigate to the website, but when the hyperlink is clicked, the status as seen from the selenoid-ui session is `Failed - Download error`.

I have tried to look through the documentation below, but this was more for accessing files that has been successfully downloaded: 
https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser

**Expectation**
The file should be downloaded into the browser container properly without any issue.

**Comment by vania-pooh** [comment]
@timothyjmtan do you suppress file download dialog? https://stackoverflow.com/questions/46937319/how-to-use-chrome-webdriver-in-selenium-to-download-files-in-python

**Comment by timothyjmtan** [comment]
That's a great question. I thought I did, but I'm currently re-checking the settings to make sure it really is. I'm guessing the error message implies that the pop-up is enabled but runs into an error since the tests are being executed on a linux distro.

**Comment by timothyjmtan** [comment]
@vania-pooh Just to clarify when I set the download directory of the chromedriver, should this value be the path:

a) in the local machine calling the test (a windows machine), or
b) in the host machine (hosting the selenoid images), or
c) the browser container ('/home/selenium/Downloads')?

**Comment by vania-pooh** [comment]
@timothyjmtan somewhere in browser container, but if you wish to use Selenoid `/download` API, then it should be `/home/selenium/Downloads`.

**Comment by timothyjmtan** [comment]
@vania-pooh  Finally solved my issue. I was actually using the below function to set the download directory, as I had previously successfully used it as a workaround for an issue faced by selenium grid setup in AWS. Once I removed this and did it the de-facto way of `chromePrefs.put("download.default_directory", "/home/selenium/Downloads");`, the download got through. Phew, thanks!

```
private void sendRemoteCommandForDownloads() {
        this.downloadFolder = new File("/home/selenium/Downloads");
        Map<String, Object> commandParams = new HashMap();
        commandParams.put("cmd", "Page.setDownloadBehavior");
        Map<String, String> params = new HashMap();
        params.put("behavior", "allow");
        params.put("downloadPath", this.downloadFolder.getPath());
        logger.info("Download Path: " + this.downloadFolder.getPath());
        commandParams.put("params", params);

        try {
            String u = <selenoid_host_ip>:<selenoid_host_port> + "/wd/hub/session/" + super.getSessionId() + "/chromium/send_command";
            logger.info(u);
            Response post = (Response)RestAssured.given().baseUri(u).contentType(ContentType.JSON).body(commandParams).when().post();
            ((ValidatableResponse)post.then()).statusCode(200);
            logger.info("Response Status: " + post.getStatusCode());
            logger.info("Response Line: " + post.statusLine());
        } catch (Throwable var5) {
            logger.error("Unable to initiate downloading session", var5);
        }
```

**Comment by vania-pooh** [comment]
@timothyjmtan great!

**Comment by Prasad1982-CTR** [comment]
Hello Vania-pooh, It would be great if you  tell how can we achieve the downloading files with Selenoid by using docker compose file. Though i mounted i am not able to get the files to the mounted location.Below is my docker compose file. Please correct me if some thing is wrong on it.
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4447:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /home/docker/Downloads/ABC_PDF_DOWNLOAD:/home/selenium/Downloads
    command: ["-limit","6"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "9009:8080"
    command: ["--selenoid-uri", "http://selenoid:4444" ]
    volumes:
      - /home/docker/Downloads/IL_PDF_DOWNLOAD:/home/selenium/Downloads

**Comment by vania-pooh** [comment]
@Prasad1982-CTR yes, `/home/selenium/Downloads` is a correct directory to mount.

**Comment by Prasad1982-CTR** [comment]
@vania-pooh  But  the files are not coming  to this location  /home/docker/Downloads/IL_PDF_DOWNLOAD. It would be great if your provide any links where i can get more details about this. I am struck with this file downloading feature. I try to do with API but in my application PDF names are generating with random numbers so no luck on this way.

**Comment by aandryashin** [comment]
You do not have to mount volumes, downloaded files can be accessed via api:

https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser

ср, 2 окт. 2019 г., 18:38 Prasad1982-CTR <notifications@github.com>:
