### ISSUE TITLE
Using Download API for dynamically generated filenames

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid#708]
Hello,

**Issue Overview**
I am able to use the Download API to retrieve files from the browser container. However, I am running into a use-case where I do not actually know the filename being downloaded. The filename is dynamically generated with a timestamp on the server side (i.e. File_26032019_110153.zip).

Would the Download API not be feasible in such use-cases? If not, would there be alternatives?

Thanks so much.

**Comment by vania-pooh** [comment]
@timothyjmtan download API just shows which files you have inside container. I would solve this issue by mocking the timestamp generation algorithm so it always generates the same value.

**Comment by timothyjmtan** [comment]
Thanks. Would volume mapping work in this case? If I understand correctly, volume mapping only happens between the docker host machine and the selenoid container. Is there a way to volume map between the docker host machine and the browser container, or a way to map between the selenoid container and browser container ?

**Comment by aandryashin** [comment]
You can retrieve list of files pointing to http://<selenoid>:4444/download

вт, 26 мар. 2019 г., 6:03 timothyjmtan <notifications@github.com>:

**Comment by vania-pooh** [comment]
@timothyjmtan you can mount volumes to browser containers using `volumes` section of `browsers.json` as shown here: https://aerokube.com/selenoid/latest/#_other_optional_fields

**Comment by timothyjmtan** [comment]
@vania-pooh  Oh thanks! Very useful, I missed that section out.
@aandryashin  Thanks for the link, that is much appreciated too.
