### ISSUE TITLE
Firefox throwing errors with JSON input

### ISSUE THREAD

**Issue by jsa34** [aerokube/selenoid#713]
Running Firefox tests gives this result every so often:

org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '3.141.59', revision: 'xxxxx', time: 'xxxxx'
System info: host: 'xxxxx', ip: 'xxxxx', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.el7.x86_64', java.version: '1.8.0_191'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:290)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:220)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:145)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:87)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at uk.ac.cam.automation.seleniumframework.site.Site.goToURL(Site.java:132)

The tests that error appear random but significant (about 10% of test cases), and they are all doing the same set up for over 300 tests and it is always at .get() command for URL.  I cannot find a single test that consistently fails with this error - it happens once and then the next time is fine.

Any ideas?  I have checked selenoid logs and all I can see is:
Error: context canceled

Note: ONLY happens with Firefox/Geckodriver, not any Chromium-based browsers

Any pointers would be much appreciated!

**Comment by vania-pooh** [comment]
@jsa34 make sure first you are using a recent Selenium client version.

**Comment by jsa34** [comment]
Hello,

I am using the latest selenium client (3.141.59) and latest selenoid.

**Comment by vania-pooh** [comment]
@jsa34 btw, `context canceled` means in the majority of cases a timeout. Couldn't it be that Firefox just crashes?

**Comment by jsa34** [comment]
I have just watched the sessions and got a bit deeper into what is happening.
It looks like the page load is stuck - it won't even let me refresh the page manually and intervene, but I can click on a link to navigate away from this page and then return and it seems to load fine.
I have attached the offending time's geckodriver logs.  I suspect this might be geckodriver related more than selenoid now, but possibly not....
![image](https://user-images.githubusercontent.com/31512041/55143083-e9d9ea80-5135-11e9-85b2-a739da0e56ea.png)

**Comment by vania-pooh** [comment]
@jsa34 could you also try to increase `shmSize` in `browsers.json`. When missing default value is 256 Mb and here Mozilla guys recommend to increase it: https://github.com/mozilla/geckodriver/issues/1531 How to do this: https://aerokube.com/selenoid/latest/#_other_optional_fields

**Comment by jsa34** [comment]
Hello - good point.  I have updated the browsers.json to include the line: 
                "shmSize":2147483648
(2gb)

and did a docker kill -s HUP <pid>

But still getting the same issues :(

**Comment by vania-pooh** [comment]
@jsa34 need to investigate Geckodriver \ Firefox issues then. Not sure about the reason.

**Comment by jsa34** [comment]
Thank you!  Really appreciate the help :)

**Comment by stalker-detected** [comment]
> Спасибо! Очень ценю помощь :)


I have the same problem. Did you find a solution?

**Comment by jsa34** [comment]
Hello,

No - still waiting for any feedback from Geckodriver, but nothing so far...  Just failing at the moment and have no way of correcting this that I can see...

**Comment by stalker-detected** [comment]
Hello

can you give me a link to the question to Geckodriver? I want to follow the answer)

**Comment by kaygee** [comment]
I'm seeing the same thing on Chrome. Initially, I thought it was something to do with Selenoid, but I reproduced the issue locally while watching the VNC session. @jsa34 could you link the Geckodriver issue?

**Comment by kaygee** [comment]
Nevermind, https://github.com/mozilla/geckodriver/issues/1555

**Comment by jacattau** [comment]
I just had this happen today with Chrome also.  It was 1 out of 600 tests but still not sure why it happened.

**Comment by kaygee** [comment]
@jacattau I still get it using Chrome and haven't figured out why either. It's happened locally, remotely, etc... I haven't had a moment to really dig into it to assist debugging.

**Comment by jacattau** [comment]
I see it mostly on Firefox but have seen it on Chrome.  I have never seen this error before locally or remotely before using Selenoid.

**Comment by jacattau** [comment]
@kaygee what did you mean by "Initially, I thought it was something to do with Selenoid, but I reproduced the issue locally while watching the VNC session."  Wouldn't watching a VNC session mean it IS Selenoid?  

I just had this happen again today with several chrome tests.  So now I have seen it on Firefox and Chrome with Selenoid after never seeing these before.

**Comment by kaygee** [comment]
@jacattau I was using the `selenium/standalone-chrome-debug` docker image. :)

**Comment by jacattau** [comment]
Have you put in an issue on their board maybe?
