### ISSUE TITLE
Clipboard\files getting with firefox images

### ISSUE THREAD

**Issue by BorisOsipov** [aerokube/selenoid#715]
I have selenoid instance with `firefox:66.0` image and do
```
###
POST http://localhost:4444/wd/hub/session
Content-Type: application/json
{"desiredCapabilities":{"browserName":"firefox"}}
###
GET http://localhost:4444/clipboard/f31d8957-0145-4a0b-a15d-ee1dadc65cde/
###
```

And receive
```
GET http://localhost:4444/clipboard/f31d8957-0145-4a0b-a15d-ee1dadc65cde/

HTTP/1.1 502 Bad Gateway
Date: Thu, 28 Mar 2019 13:35:14 GMT
Content-Length: 0

<Response body is empty>

Response code: 502 (Bad Gateway); Time: 106ms; Content length: 0 byte
```

The same for `http://localhost:4444/download/{sessionId}/{filename}` endpoint.

At the same time for chrome 73 image I get correct response
```
GET http://localhost:4444/clipboard/3aaf3940314271c7825162ec97723805/

HTTP/1.1 200 OK
Content-Length: 0
Date: Thu, 28 Mar 2019 13:37:48 GMT

<Response body is empty>

Response code: 200 (OK); Time: 110ms; Content length: 0 bytes
```

Does clipboard\files getting work with firefox images?

**Comment by vania-pooh** [comment]
@BorisOsipov does it reproduce with older Firefox version (e.g. 65.0)?

**Comment by BorisOsipov** [comment]
@vania-pooh yes

**Comment by vania-pooh** [comment]
@BorisOsipov probably we forgot to add respective binaries.

**Comment by anastasijabulatova-toast** [comment]
@vania-pooh it is still repro with the latest firefox image? do you have plans to fix it?

**Comment by vania-pooh** [comment]
@anastasijabulatova-toast for recent images we launch everything. https://github.com/aerokube/images/blob/master/static/firefox/selenoid/entrypoint.sh#L41
