### ISSUE TITLE
CLIENT_DISCONNECTED Error: context canceled

### ISSUE THREAD

**Issue by f-dg** [aerokube/selenoid#716]
Hi everyone, I'm struggling to cope with an issue and asking for a help
There is a problem when a page opens too long. It seems that a docker container has gone away when I send a request to open a page, if it takes more than a minute to be loaded completely. 
Selenoid is launched as beneath 
`go run . -log-output-dir logs -listen :5000 -retry-count 5 -timeout 120s -conf /var/app/current/config/browsers.json`

The output
`2019/04/01 15:48:19 [-] [INIT] [Loading configuration files...]
2019/04/01 15:48:19 [-] [INIT] [Loaded configuration from /var/app/current/config/browsers.json]
2019/04/01 15:48:19 [-] [INIT] [Video Dir: /var/app/selenoid/video]
2019/04/01 15:48:19 [-] [INIT] [Logs Dir: /var/app/selenoid/logs]
2019/04/01 15:48:19 [-] [INIT] [Your Docker API version is 1.38]
2019/04/01 15:48:19 [-] [INIT] [Timezone: Local]
2019/04/01 15:48:19 [-] [INIT] [Listening on :5000]
2019/04/01 15:48:24 [-] [NEW_REQUEST] [selenoid] 
2019/04/01 15:48:24 [-] [NEW_REQUEST_ACCEPTED] [selenoid] 
2019/04/01 15:48:24 [0] [LOCATING_SERVICE] [chrome] [72.0-f1]
2019/04/01 15:48:24 [0] [USING_DOCKER] [chrome] [72.0-f1]
2019/04/01 15:48:24 [0] [CREATING_CONTAINER] [selenoid/chrome:72.0]
2019/04/01 15:48:25 [0] [STARTING_CONTAINER] [selenoid/chrome:72.0] [16fad3b41afba882fe54aec20ea090129f7011cb27a60e62c6fab19e5db20c61]
2019/04/01 15:48:25 [0] [CONTAINER_STARTED] [selenoid/chrome:72.0] [16fad3b41afba882fe54aec20ea090129f7011cb27a60e62c6fab19e5db20c61] [0.29s]
2019/04/01 15:48:25 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2019/04/01 15:48:25 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [15ea6aaf9e602c0c1f4637dc118c67859f1a6e2c4e0d8b6b696faac068a69512]
2019/04/01 15:48:25 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [15ea6aaf9e602c0c1f4637dc118c67859f1a6e2c4e0d8b6b696faac068a69512] [0.37s]
2019/04/01 15:48:25 [0] [SERVICE_STARTED] [selenoid/chrome:72.0] [16fad3b41afba882fe54aec20ea090129f7011cb27a60e62c6fab19e5db20c61] [0.00s]
2019/04/01 15:48:25 [0] [PROXY_TO] [16fad3b41afba882fe54aec20ea090129f7011cb27a60e62c6fab19e5db20c61] [http://127.0.0.1:33900]
2019/04/01 15:48:25 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:33900] [1]
2019/04/01 15:48:26 [0] [SESSION_CREATED] [a77f2bbf2c682bc8d021d6bd66990a77] [1] [1.65s]
2019/04/01 15:49:26 [2] [CLIENT_DISCONNECTED] [selenoid] [127.0.0.1] [Error: context canceled]
2019/04/01 15:49:26 [3] [SESSION_DELETED] [a77f2bbf2c682bc8d021d6bd66990a77]
2019/04/01 15:49:31 [0] [STOPPING_VIDEO_CONTAINER] [15ea6aaf9e602c0c1f4637dc118c67859f1a6e2c4e0d8b6b696faac068a69512]
2019/04/01 15:49:31 [0] [STOPPED_VIDEO_CONTAINER] [15ea6aaf9e602c0c1f4637dc118c67859f1a6e2c4e0d8b6b696faac068a69512]
2019/04/01 15:49:31 [0] [REMOVING_CONTAINER] [16fad3b41afba882fe54aec20ea090129f7011cb27a60e62c6fab19e5db20c61]
2019/04/01 15:49:31 [0] [CONTAINER_REMOVED] [16fad3b41afba882fe54aec20ea090129f7011cb27a60e62c6fab19e5db20c61]
^C2019/04/01 15:58:34 [-] [SHUTTING_DOWN] [5m0s]`

Here, CLIENT_DISCONNECTED happens right after a minute in spite of the timeout.
I debugged golang guts and "Error: context canceled" occurs due to "read tcp 127.0.0.1:35370->127.0.0.1:33900: use of closed network connection"
Suppose 127.0.0.1:33900 is a docker container. Is any workaround to approach this issue?

**Comment by vania-pooh** [comment]
@f-dg I think 1 minute is your client HTTP request timeout. Because `CLIENT_DISCONNECTED` means that connection was closed from the client side.

**Comment by f-dg** [comment]
@vania-pooh HTTP client is used with default timeouts, HTTP transport as well. I've just double checked that. `CLIENT_DISCONNECTED` pops up right after `use of closed network connection` error. The error happens when a socket between selenoid and docker container has been closed, then `CLIENT_DISCONNECTED`
This is strange, because selenoid is run with timeout flag which is set to 120s but the socket is closed after 60s
I'm using ggr, in case if this info can help

**Comment by vania-pooh** [comment]
@f-dg Yes, and your default client timeout I think is 1 minute. Check first that you don't have any firewall rules blocking access to tested pages or their static resources (CSS\JS).

**Comment by f-dg** [comment]
@vania-pooh yeah, you were right. The cause of timeout was an aws load balancer, it has default idle timeout of 60 seconds
Thanks.

**Comment by vania-pooh** [comment]
@f-dg closing then?

**Comment by f-dg** [comment]
Sure

**Comment by manikesh** [comment]
@f-dg  how was this fixed? as I am also getting same error..

**Comment by vania-pooh** [comment]
@manikesh you should adjust you AWS load balancer timeout settings via UI.

**Comment by f-dg** [comment]
> @f-dg how was this fixed? as I am also getting same error..
As @vania-pooh mentioned above, the load balancer had caused the disconnection

**Comment by manikesh** [comment]
@vania-pooh mine is simple cluster.. there is no load balancer as well.. its simple service URL thru which I am accessing the hub.. tried to override the Timeout in and transport in httpClient but did not help..  something like below..

Tripper http.RoundTripper = &http.Transport{
	Proxy: http.ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   300 * time.Second,
		KeepAlive: 300 * time.Second,
	}).DialContext,
	TLSHandshakeTimeout: 300 * time.Second,
}
	httpClient = &http.Client{
		Timeout: 300*time.Second,
		Transport: Tripper,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse

		},
	}

**Comment by f-dg** [comment]
try to trace a request, most likely there's something between client and hub that causes the timeout error

**Comment by manikesh** [comment]
just wanted to understand it better.. for me client_disconnected is happening after session_attempted.. this means that client could not talk to hub itself and due to less timeout setup it got disconnected?

**Comment by f-dg** [comment]
I had the same pattern. Selenoid successfully created a session and transmitted it to the docker container. Since the session is being executed more than 60 seconds the load balancer caused disconection between the client and selenoid. Then selenoid threw the error client_disconected

**Comment by srinathbharadwaj** [comment]
@f-dg, @vania-pooh  

I am getting the same issue but I am not quite sure, I understood your solution. <br\>

Here is my set up. <br/>

1. We are running tests via Jenkins which is hosted on either EC2\ECS(not sure as it is maintained by a different group within our company). <br\>
2. The jenkins job creates a NightwatchJS container and copies over our test scripts from Git into this container. <br\>
3. Our tests are triggered from this container. <br\>
4. We have selenoid running on another EC2 instance and our tests are running against this Selenoid grid <br\>

What I see is, when the tests longer than 60 secs, I start seeing CLIENT_DISCONNECTED, socket hang up exceptions. <br\>
I had to break my tests into smaller tests so that it can execute within 60 secs but this approach is not feasible all the time. I need a way for session to be active for more than 60 secs. <br\>
I did not quite understand the solution involving load balancer. Based on little knowledge around load balancers in AWS, they are of 3 types. Which one are you referring to? Is it Network Load Balancer? And when you say 'between client and selenoid', what is client referring to? In my case, is it my nightwatchjs docker container?

**Comment by vania-pooh** [comment]
@srinathbharadwaj we are speaking about network connectivity between the host where tests are executed and where Selenoid is running. If your case adding `sessionTimeout = 2m` capability could help.

**Comment by srinathbharadwaj** [comment]
@vania-pooh Thank you. Just to be clear, I started Selenoid with command: ./selenoid -conf /home/ec2-user/browsers.json -limit 10 -retry-count 3 -session-attempt-timeout 2m -log-output-dir /home/ec2-user/selenoid-logs -timeout 2m

But it did not help. I tried with 4m and upto 10m but even then, tests fail randomly unless my tests are small enough to complete before 60 secs.

**Comment by vania-pooh** [comment]
@srinathbharadwaj in that case network load balancer settings with your AWS maintenance team.
