### ISSUE TITLE
C# deprecated capabilities 

### ISSUE THREAD

**Issue by gusacinschi** [aerokube/selenoid#718]
Platform: Linux Ubuntu;
Docker: version 18.09.2, build 6247962;
.NET framework 4.6.1
Selenium.WebDriver package : version 3.141.0
browsers.json:
{
    "chrome": {
        "default": "73.0",
        "versions": {
            "73.0": {
                "image": "selenoid/vnc_chrome:73.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

**docker images:**
REPOSITORY                      TAG                         IMAGE ID            CREATED             SIZE
aerokube/selenoid-ui       1.6.6                      9fc8838e12e6        8 days ago           9.35MB
aerokube/selenoid            1.9.1                     531cd150ccb6        2 weeks ago        13.2MB
selenoid/vnc_chrome        73.0                      f902fb2f5d42         3 weeks ago         975MB
selenoid/video-recorder    latest-release      c8018c23fcb7         6 months ago       30.4MB

**docker ps**
cbbff91754c3          aerokube/selenoid-ui:1.6.6   "/selenoid-ui --sele…"   .....
6789d59aa3ea        aerokube/selenoid:1.9.1       "/usr/bin/selenoid -…"   .....

I want to build a remoteWebDriver with capabilities:
var capabilities = new DesiredCapabilities("chrome", "73.0", new Platform(PlatformType.Any));
var driver = new RemoteWebDriver(new Uri("http://selenoid:4444/wd/hub"), capabilities);

This gives me a warning: "Warning	CS0618	'DesiredCapabilities.DesiredCapabilities(string, string, Platform)' is obsolete: 'Use of DesiredCapabilities has been deprecated in favor of browser-specific Options classes'"

Running this code is error free. but it does not enable VNC feature

If I use:
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.AddArgument("test-type=browser");
chromeOptions.AddAdditionalCapability("enableVNC", true);
var driver = new RemoteWebDriver(new Uri("http://selenoid:4444/wd/hub"), chromeOptions.ToCapabilities());

I get a run-time error: {"invalid argument: cannot parse capability: goog:chromeOptions\nfrom invalid argument: unrecognized chrome option: enableVNC\n  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-47-generic x86_64)"}

I need to enable VNC feature. What is the proper way to do it?

**Comment by vania-pooh** [comment]
@gusacinschi I'm not a C# specialist but a Java equivalent would be:
```
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("selenoid:options", new HashMap<String, Object>(){
            {
                put("enableVNC", true);
            }
        });
```
So in C# you should have a similar `setCapability` method and pass a C# dictionary as a value.

**Comment by gusacinschi** [comment]
The code I tried:
ChromeOptions chromeOptions = new ChromeOptions();
var dict = new Dictionary<string, object>{{ "enableVNC", true }};
chromeOptions.AddAdditionalCapability("selenoid:options", dict);

The error I get in Visual studio once creating the remoteWebDriver object:
{"invalid argument: cannot parse capability: goog:chromeOptions\nfrom invalid argument: unrecognized chrome option: selenoid:options\n  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-47-generic x86_64)"}

It starts the chrome vnc container, here are the logs:
Initialize...

Connecting to ws://192.168.63.114:8080/ws/logs/b71f19f7ec0b59b61b32c7a040f15a2f...
Connected!
Waiting xvfb...
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 4444
All remote connections are allowed. Use a whitelist instead!
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1554396205.179][INFO]: [b71f19f7ec0b59b61b32c7a040f15a2f] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "test-type", "test-type=browser", "--start-maximized", "--window-size=1920,1080", "--js-flags=--expose-gc", "--enable-precise-memory-info", "--disable-popup-blocking", "--disable-default-apps", "--disable-infobars", "--no-sandbox", "--ignore-certificate-errors", "--disable-web-security", "--allow-insecure-localhost", "--allow-running-insecure-content", "--proxy-server='direct://'", "--proxy-bypass-list=*", "--disable-extensions", "--log-level=ALL", "--verbose" ],
            "selenoid:options": {
               "enableVNC": true
            }
         }
      } ]
   },
   "desiredCapabilities": {
      "browserName": "chrome",
      "goog:chromeOptions": {
         "args": [ "test-type", "test-type=browser", "--start-maximized", "--window-size=1920,1080", "--js-flags=--expose-gc", "--enable-precise-memory-info", "--disable-popup-blocking", "--disable-default-apps", "--disable-infobars", "--no-sandbox", "--ignore-certificate-errors", "--disable-web-security", "--allow-insecure-localhost", "--allow-running-insecure-content", "--proxy-server='direct://'", "--proxy-bypass-list=*", "--disable-extensions", "--log-level=ALL", "--verbose" ],
         "selenoid:options": {
            "enableVNC": true
         }
      }
   }
}
[1554396205.180][INFO]: [b71f19f7ec0b59b61b32c7a040f15a2f] RESPONSE InitSession ERROR invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: selenoid:options
[1554396205.181][DEBUG]: Log type 'driver' lost 1 entries on destruction

It looks like the capabilities are not recognized by the container.

**Comment by arst** [comment]
There is an optional parameter for AddAdditionalCapability method - isGlobalCapability, according to XMLdoc: "Indicates whether the capability is to be set as a global capability for the driver instead of a Chrome-specific option.", so you need to rewrite your code to something like this(note third parameter for AddAdditionalCapability):

 var options = new ChromeOptions();
options.AddAdditionalCapability("enableVNC", true, true);

This should help.

**Comment by gusacinschi** [comment]
Thank you! Works as expected. The issue is resolved.
