### ISSUE TITLE
Endpoint to serve supported browsers and container limit

### ISSUE THREAD

**Issue by nebehr** [aerokube/selenoid#720]
How were it if there was an additional endpoint returning stripped down version of browsers.json and the value of ```limit``` flag? This might be useful for cluster maintenance, to quickly query Selenoid nodes' capabilities. For example, GET /browsers yielding something like:

```
{"browsers":{"chrome":{"default":"67","versions":["67", "68"]},"firefox":{"default":"45","versions":["45", "57"]},"internet explorer":{"default":"9","versions":["9"]}},"limit":5}
```
In fact it could be done in /ping but perhaps that would be overkill.

If you think this is a reasonable feature I can make a PR.

**Comment by aandryashin** [comment]
Ggr has flag to set response timeout, could you please check it.

пн, 15 апр. 2019 г., 10:52 nebehr <notifications@github.com>:

**Comment by nebehr** [comment]
@aandryashin, wrong issue?

**Comment by vania-pooh** [comment]
@nebehr have you seen Selenoid `/status` API?

**Comment by nebehr** [comment]
Aye I have. But for some reason it seemed not sufficient at the time. But then perhaps you are right, the only thing missing is the default browser version.

**Comment by vania-pooh** [comment]
@nebehr we can consider adding it to this API.

**Comment by vania-pooh** [comment]
@nebehr do you still need this?

**Comment by nebehr** [comment]
I think if `defaultVersion ` could be added to `/status` without too much hassle, that would be enough.
