### ISSUE TITLE
Support browsermob with new image

### ISSUE THREAD

**Issue by jayden-xie** [aerokube/selenoid#723]
Feature required:
In order to record network deatils, I'm running standalone proxy by browsermob, works great with selenoid. Can Selenoid support creating proxy image on the fly? Like the way you're doing with video recording. Create new proxy image for per session, destroy it when session is over.
Thank you.

**Comment by vania-pooh** [comment]
@jayden-xie we consider such feature outside of Selenoid scope. This should be usually done by tests code. Also locking to browsermob is not a good idea as other users may require features not supported by browsermob.

**Comment by jayden-xie** [comment]
Indeed, there're other options, do you have any suggestion about which one is better?

I tried to find some... 
1.python [https://github.com/mitmproxy/mitmproxy](https://github.com/mitmproxy/mitmproxy)
2.nodejs [https://github.com/nodejitsu/node-http-proxy](https://github.com/nodejitsu/node-http-proxy)

**Comment by vania-pooh** [comment]
@jayden-xie I personally have more Java experience, so browsermob is one of the best options for me. The majority of my colleagues are using it.
