### ISSUE TITLE
seeing error : driver failed programming external connectivity on endpoint

### ISSUE THREAD

**Issue by mmraghavendra** [aerokube/selenoid#727]
I am trying to run selenium tests using selenoid in Ubuntu and CentOS machines. I am seeing below in selenoid logs as soon as tests start to launch the browser. Please let me know how to fix this issue. using selenoid_linux_amd64 latest file to start selenoid at 4444  port.

2019/04/30 13:16:01 [1] [CREATING_CONTAINER] [selenoid/vnc:chrome_74.0]
2019/04/30 13:16:01 [1] [STARTING_CONTAINER] [selenoid/vnc:chrome_74.0] [a99257d1e59faaad844714cbe8088a075dcfae1ef896761bab31cb04a4bc8c76]
2019/04/30 13:16:02 [1] [REMOVING_CONTAINER] [a99257d1e59faaad844714cbe8088a075dcfae1ef896761bab31cb04a4bc8c76]
2019/04/30 13:16:02 [1] [FAILED_TO_REMOVE_CONTAINER] [a99257d1e59faaad844714cbe8088a075dcfae1ef896761bab31cb04a4bc8c76] [Error: No such container: a99257d1e59faaad844714cbe8088a075dcfae1ef896761bab31cb04a4bc8c76]
2019/04/30 13:16:02 [1] [SERVICE_STARTUP_FAILED] [start container: Error response from daemon: driver failed programming external connectivity on endpoint recursing_ardinghelli (3e7bef32cdebdf67977856a4cd6abfe461772fa4e5e026ecf5c3952c529097eb):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32793 -j DNAT --to-destination 172.17.0.2:0 ! -i docker0: iptables v1.6.0: Port `0' not valid

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))]

**Comment by vania-pooh** [comment]
@mmraghavendra this seems to Docker \ CentOS issue, not Selenoid one. Make sure you are able to start containers with `docker run` manually. This could also be caused by SeLinux restrictions. Try to turn it off.

**Comment by mmraghavendra** [comment]
Thank you for your response. Reinstalling the docker solved the issue.
