### ISSUE TITLE
Passing Chrome version through pom.xml

### ISSUE THREAD

**Issue by trdgit1** [aerokube/selenoid#728]
I have to pass params to Selenoid from pom.xml (Surefire plugin) but seem to be unable do that for Chrome version. Whatever I do it doesn't get recognized by Selenoid making it fall back to default Chrome version specified in browsers.json.

Here is what I have in logs:
![image](https://user-images.githubusercontent.com/11870372/57391601-8973a980-71c7-11e9-9c07-df243ae27c0b.png)

Here is what I have in pom.xml (<> replaced with []):
![image](https://user-images.githubusercontent.com/11870372/57391505-57fade00-71c7-11e9-9b4d-edd41b1fc277.png)

Any clues on how to do that? I failed to find any useful info on the Internet.

**Comment by aandryashin** [comment]
As i can see version did not set, it comes as empty string, that is why
selenoid using default from browsers.json...

ср, 8 мая 2019 г., 19:21 Roman Titov <notifications@github.com>:

**Comment by trdgit1** [comment]
Yes, and the question is how to set it in pom.xml?

**Comment by trdgit1** [comment]
<chrome.capabilities.version>${chrome.version}</chrome.capabilities.version>
