### ISSUE TITLE
Query to increase the limit for parallel sessions

### ISSUE THREAD

**Issue by qatestingravi** [aerokube/selenoid#741]
Hi @vania-pooh, 
In my linux machine  I have installed docker and perform following steps. selenoid is started succsesfully and running. 
1. wget -O cm https://github.com/aerokube/cm/releases/download/1.5.7/cm_linux_amd64
2. chmod +x ./cm
3. ./cm selenoid start --vnc

Now my question is how to increase parallel sessions .
I tried with below command, but it was not working. can you please help me, how to increase the limit
./cm selenoid start -limit 10 --vnc 

One more question.
How to stop the selenoid?

**Comment by vania-pooh** [comment]
@qatestingravi you should add `-limit` flag to Selenoid arguments (default is 5). With CM this is done as follows:
```
$ ./cm selenoid start --vnc --args "-limit 10"
```

**Comment by qatestingravi** [comment]
Thanks @vania-pooh ... I will check and close the issue..

**Comment by vania-pooh** [comment]
@qatestingravi having an already installed Selenoid you have to use `--force` flag.

**Comment by vania-pooh** [comment]
@qatestingravi did it help?

**Comment by makamravikumar** [comment]
@vania-pooh Due to some other work I came out of station and could not get time to work on it... Once I check I will update you....

**Comment by qatestingravi** [comment]
Thanks @vania-pooh , its working with following command 
./cm selenoid start --vnc --force --args "-limit 10"

I am closing the issue as it is working..
