### ISSUE TITLE
Container is not killed on test failure and keep running for a long time

### ISSUE THREAD

**Issue by kirillbilchenko** [aerokube/selenoid#744]
HI guys,

The problem there I already reached you in telegram channel, but will also describe it there. Happening on container with firefox, I run lates ff vnc image, but test is running in headless mode without vnc 

Details about container:
`944dfd8797c6        selenoid/vnc_firefox:67.0   "/entrypoint.sh"    3 hours ago         Up 3 hours          0.0.0.0:32816->4444/tcp, 0.0.0.0:32815->7070/tcp, 0.0.0.0:32814->8080/tcp, 0.0.0.0:32813->9090/tcp   unruffled_dijkstra`

Details about selenoid run:
`/usr/local/bin/selenoid -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -log-output-dir /opt/selenoid/logs/ -video-recorder-image selenoid/video-recorder:latest-release -limit 1 -timeout 5m`

Error message:
`Jun 13 09:47:42 ip-172-16-2-69 selenoid[1386]: 2019/06/13 09:47:33 [1629] [DELETE_FAILED] [1e826639-6889-4b72-ad31-50c5e6f4fe83] [Delete http://127.0.0.1:4444/wd/hub/session/1e826639-6889-4b72-ad31-50c5e6f4fe83: context deadline exceeded]`
Selenoid logs: 
[https://gist.github.com/kirillbilchenko/5b34a80781aa5a37c85dc03084dbb5a3](logs)

Docker logs:
[https://gist.github.com/kirillbilchenko/aa3835be243545b5b30d6aae35672a87](logs)

Selenoid version: 1.9.1

Docker version:

> Client:
>  Version:           18.09.6
>  API version:       1.39
>  Go version:        go1.10.8
>  Git commit:        481bc77
>  Built:             Sat May  4 02:35:57 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.6
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.8
>   Git commit:       481bc77
>   Built:            Sat May  4 01:59:36 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false

**Comment by vania-pooh** [comment]
* https://github.com/aerokube/selenoid/blob/master/service/docker.go#L232 context should be copied
* https://github.com/aerokube/selenoid/blob/master/service/docker.go#L236 should use new context (Background / WithTimeout)
