### ISSUE TITLE
CPU limit is not working in video image

### ISSUE THREAD

**Issue by jayden-xie** [aerokube/selenoid#746]
I tried to limit video recording CPU, but the -cpu command is only working in browser image, not working in video recording image.  "NanoCpus" value is still 0.

**Comment by vania-pooh** [comment]
@jayden-xie correct, it is only working for browser images. What is the use case?

**Comment by jayden-xie** [comment]
@vania-pooh After the test running for some hours, the tests became really slow, I can see ffmpeg is taking more than 300% cpu at max(normally under 100% when everything is cool), the timing returned to normal after I disabled the video recording feature.

**Comment by vania-pooh** [comment]
@jayden-xie we don't expect videos to be recorded for every test case. This is mainly a debugging feature. Video recording will certainly take a lot of CPU (approximately 1 CPU per parallel browser session).
