### ISSUE TITLE
DesiredCapabilities for mobileEmulation & always_open_pdf_externally ignored on Chrome

### ISSUE THREAD

**Issue by tnoor-co** [aerokube/selenoid#752]
We are running into this issue of the Selenoid docker ignoring certain DesiredCapabilities which include always_open_pdf_externally (set to true) and mobileEmulation (set to "deviceName", "iPhone X"). 

Using SelenoidUI, we were able to verify that Chrome opens the page without mobile emulation & opens PDFs using the built-in PDF reader.

When similar capabilities (using ChromeOptions, since DesiredCapabilities is marked as deprecated) are used with the regular ChromeDriver, PDF's are not opened by Chrome's built-in PDF reader and the website is opened in a mobile emulation mode with the respective mobile device.

Docker API version:
- 1.39

Images:
- aerokube/selenoid:1.9.1
- aerokube/selenoid-ui

Browsers Tested on:
- Chrome 75.0
- Chrome 71.0

Language:
- C#

```
var capabilities = new DesiredCapabilities("chrome", "75.0", new Platform(PlatformType.Any));
capabilities.SetCapability("enableVNC", true);
capabilities.SetCapability("download.prompt_for_download", "false");
capabilities.SetCapability("always_open_pdf_externally", "true");
capabilities.SetCapability("profile.default_content_setting_values.automatic_downloads", 1);
capabilities.SetCapability("timeZone", "US/Eastern");
capabilities.SetCapability("mobileEmulation", new Dictionary<string, string> {{"deviceName", "iPhone X" } });

driver = new RemoteWebDriver(new Uri($"http://{Config.HubIp}/wd/hub"), capabilities, TimeSpan.FromMinutes(10));
```

**Comment by vania-pooh** [comment]
@tnoor-co Selenoid just proxies all the capabilities to Chromedriver inside running container. I think you should just use ChromeOptions with Selenoid, too.

**Comment by tnoor-co** [comment]
Thank you for that suggestion! For some reason, I thought it wasn't compatible but ChromeOptions definitely worked after a bit of playing around.

Here's a snippet, if anyone else was wondering ->

```
ChromeOptions options = new ChromeOptions();
options.AddUserProfilePreference("download.prompt_for_download", "false");
options.AddUserProfilePreference("download.extensions_to_open", "");
options.AddUserProfilePreference("plugins.always_open_pdf_externally", true);
options.EnableMobileEmulation("iPhone X");
```

Since, we are using ChromeOptions, the BrowserName is set to "chrome" by default. The version is specified below:
```
options.BrowserVersion = "75.0";
options.PlatformName = "Any";
```

The third parameter (true) is to identify the capabiliity as Global:
```
options.AddAdditionalCapability("enableVNC", true, true);
options.AddAdditionalCapability("timeZone", "US/Eastern", true);
```
RemoteWebDriver accepts ICapabilities, hence the conversion:
```
IWebDriver driver = new RemoteWebDriver(new Uri($"http://{Config.HubIp}/wd/hub"), options.ToCapabilities(), TimeSpan.FromMinutes(20));
```
