### ISSUE TITLE
Add default browsers.json to image

### ISSUE THREAD

**Issue by ghost** [aerokube/selenoid#768]
Hello,

Please add default browsers.json to its default path /etc/selenoid/browsers.json

**Comment by vania-pooh** [comment]
@sunofsparda makes no sense, it changes every 2-3 weeks.

**Comment by sunofsparda** [comment]
what about latest browser images with default configuration? 
just like you have here https://github.com/aerokube/selenoid/blob/master/config/browsers.json

**Comment by vania-pooh** [comment]
@sunofsparda what is the use case?

**Comment by sunofsparda** [comment]
em.. not a big use case, just to have an image which will definitely run with 100% correct browsers.json without any additional volume mounts

**Comment by aandryashin** [comment]
In that case we have to rebuild image when new browser version has
released... Let us take software and configuration separately...

чт, 11 июл. 2019 г., 17:28 Anton Cherlyonok <notifications@github.com>:

**Comment by darthghandi** [comment]
The main use case is getting this up and going quickly. For example, if using a private cloud like DC/OS, I have to either mount the config on a volume which I may or may not have access to do or create a private image with the config file included. That might be trivial for some but for others, it might take a while. 
In contrast, if there was a default, I could use the dockerfile and be on my way.

**Comment by vania-pooh** [comment]
@darthghandi CM tools installs everything in 2 minutes.
