### ISSUE TITLE
Always drop selenoid:options when proxying to upstream webdriver binary

### ISSUE THREAD

**Issue by megalan247** [aerokube/selenoid#771]
Due to some checking on the side of the Selenium IEDriver
https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriver/CommandHandlers/NewSessionCommandHandler.cpp#L613
It reports that selenoid:options is an invalid option and prevents VNC, video, or other selenoid specific actions being enabled when using this driver, returning an error:

```
session not created: No matching capability sets found.
Unable to match capability set 0: selenoid:options is an unknown extension capability for IE
```

It would be good to enable an option that will drop the selenoid:options key from the payload that is sent towards the webdriver when using -disable-docker to allow all the selenoid instances to react accordingly to the desired options, but also allow for very strict webdrivers to be used with the software.

**Comment by vania-pooh** [comment]
@megalan247 I think we could always drop it.

**Comment by megalan247** [comment]
That could also work
