### ISSUE TITLE
When trying reach Selenoid from another service in same docker network get an error 'No host specified'.

### ISSUE THREAD

**Issue by itaymelamed** [aerokube/selenoid#772]
I have dealt with the following scenario:

I have selenoid running in a docker container attached to network 'tests'.
I have used the following command to start it up:

docker run -d --name selenoid \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    --network tests \
                    --net-alias selenoid \
                    aerokube/selenoid"

I have another container with a python-based image which is also attached to docker network 'tests'.
I'm trying to create an instance of a remote Webdriver by passing the following host:
"selenoid:4444/wd/hub"
  
        chrome_options = Options()
        desired_cap_desktop = chrome_options.to_capabilities()
        driver = webdriver.Remote(
            command_executor="selenoid:4444/wd/hub",
            desired_capabilities=desired_cap_desktop)

But when I run the tests I get following error:
if not host:
>           raise LocationValueError("No host specified.")
E           urllib3.exceptions.LocationValueError: No host specified.

I have tried to execute curl to "http://selenoid:4444/wd/hub" on the python container and get an OK response. But still, when I running the tests I'm getting the above error.

**Comment by vania-pooh** [comment]
@itaymelamed I think this one is incorrect:
```
command_executor="selenoid:4444/wd/hub"
```
I would replace with an URL by adding `http://`:
```
command_executor="http://selenoid:4444/wd/hub"
```

**Comment by itaymelamed** [comment]
Thank you!
This solved my problem.

**Comment by vania-pooh** [comment]
@itaymelamed closing then.
