### ISSUE TITLE
Context getting done

### ISSUE THREAD

**Issue by manikesh** [aerokube/selenoid#776]
Just wanted to understand below line of code..

ctx, done := context.WithTimeout(r.Context(), newSessionAttemptTimeout)

as far I can understand the intention of the withTimeout() is to update the deadline in context.
wanted to understand, when will it return the done() as dont see any such implementation in it?

can someone please help me with this?

**Comment by vania-pooh** [comment]
@manikesh done should be called explicitly if you wish to close the context before timeout expires.

**Comment by manikesh** [comment]
One thing I am noticing is, when the context is cancelled due to time out form controller side.. even retries are not helping, it straight away goes to same timeout and prints client disconnected.. any way to get in to that? I dont want to increase the time out as its already 3 mins.. I want to give  retry. Please advise.

**Comment by vania-pooh** [comment]
@manikesh take a look at the following flag:
```
-retry-count int
    New session attempts retry count (default 1)
```

**Comment by manikesh** [comment]
basically there are two cases when it fails..
1. Session attempt timed out ==>retry work in this case, mostly in second or third attempts it connects
2. Client Disconnected ==> in this retry does not work as context is cancelled.. even trying for new session is also not working.
