### ISSUE TITLE
Page crash issues on chrome 75.0

### ISSUE THREAD

**Issue by Kumar-IND** [aerokube/selenoid#784]
Hi Team,
Till recently we are able to execute the test successfully without any issues on selenoid chrome 73.0 with 0.35 core and 350 mb ram.  Same test after upgrading to 75.0 started failing with page crash issues. I saw OOM error in the logs. So we increased the memory to 500MB  and saw the same OOM error. Does chrome 75.0 of selenoid using more memory than chrome 73.0 and also is there any known issue with chrome 75.0?

**Comment by vania-pooh** [comment]
@sharathmankala this is not a known issue but you can also try to increase `shmSize` in `browsers.json`.
