### ISSUE TITLE
Update docs/code to reflect W3C capability extension format

### ISSUE THREAD

**Issue by matthewdoerksen** [aerokube/selenoid#786]
Selenoid already supports the W3C spec for capability extension but in many places, properties are still shown using the old format (directly being added to the capabilities object such as the screenshot below from the linked issue). The docs and codebase should be updated to follow the W3C format.

https://user-images.githubusercontent.com/20769519/49369999-e058ec80-f718-11e8-916e-7671be503b48.JPG

https://github.com/aerokube/selenoid/issues/622

**Comment by vania-pooh** [comment]
@matthewdoerksen not all browsers currently support W3C. I think we could update code snippets for W3C in Selenoid UI.
