### ISSUE TITLE
Selenoid <-> Selenium compatibility

### ISSUE THREAD

**Issue by pavelsr** [aerokube/selenoid#788]
E.g. I have ready-to-use Perl Selenium driver.
https://metacpan.org/release/Selenium-Remote-Driver

How to make it compatible with Selenoid and use Selenoid-UI ?

As far as I understand, Selenium and Selenoid APIs are not compatible out-the-box. 
E.g. http://localhost:4444/status route is very different.

**Comment by vania-pooh** [comment]
@pavelsr Selenoid is 100% compatible with Selenium protocol. All Selenium stuff is under `/wd/hub`. So status API you are searching for is `/wd/hub/status`. Just use `http://localhost:4444/wd/hub` as Selenium URL for your tests and it should work.

**Comment by pavelsr** [comment]
@vania-pooh, seems like all Selenium stuff no under `/wd/hub`

Please take a look

![selenoid problem](https://i.imgur.com/02zSMg4.png)

https://i.imgur.com/02zSMg4.png

**Comment by vania-pooh** [comment]
@pavelsr according to [w3c spec](https://www.w3.org/TR/webdriver1/#dfn-status) only two fields: message and ready are required.

**Comment by pavelsr** [comment]
Ok, got it. Closed the issue and closed appropriate [Stackoverflow question](https://stackoverflow.com/questions/57571569/is-it-possible-to-adapt-selenium-driver-for-usage-with-selenoid)

Thank you so much.

Please have a look at #789 also
