### ISSUE TITLE
selenoid/vnc:chrome_76.0 - Cannot resolve servers from /etc/hosts or DNS

### ISSUE THREAD

**Issue by jdelzor** [aerokube/selenoid#798]
Hello,

When I launch a container with Chrome I'm not able to access my dev VM. The URL is set up in /etc/hosts with HostEntries Capabilities. To start the container I'm using a robot test.

I'm also not able to access the URL of my production or so from DNS resolution.

If I start manually the container and install 'ping' package, I'm able to resolve and ping all the corresponding VMs.

What do I miss in my settings? I found out that there are some 'bug' using /etc/hosts from Chrome/Chromium.

Thanks for you support,
Jérôme

**Comment by vania-pooh** [comment]
@jdelzor if ping is working and pages are not open - this could be a firewall issue, just because ping is using ICMP protocol whereas firewalls are usually blocking TCP/UDP.

**Comment by jdelzor** [comment]
Hi @vania-pooh, sorry I missed your answer.
I should not have firewall activated on this environment. I'll check it. I'll be able to get back in this topic by tomorrow.
I let you know if I find a reproducible solution.
