### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by HarikaSuman** [aerokube/selenoid#803]
I have tried to do the setup in windows 10 machine from docker but unfortunately not able to start the containers so I have downloaded .exe and run the given commands. Those commands made my containers up and running but when I tried to run the selenium script it is giving following error.

org.openqa.selenium.WebDriverException: create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 96 milliseconds

**Comment by vania-pooh** [comment]
@HarikaSuman were you using CM tool for installation? Are your using Docker Toolbox or Docker for Windows?

**Comment by HarikaSuman** [comment]
@vania-pooh First I tried with docker for windows but all the images are pulled successfully but got mount issue while spin up the containers. So I downloaded cm_windows_amd64.exe and ran ./cm.exe selenoid start --vnc. This command made my containers up and running.

**Comment by HarikaSuman** [comment]
![image](https://user-images.githubusercontent.com/46474927/65268424-c025dd00-db34-11e9-927a-27a389627f9d.png)

**Comment by vania-pooh** [comment]
@HarikaSuman try to add `--force` flag to CM and it will regenerate configs.

**Comment by HarikaSuman** [comment]
@vania-pooh 
After adding --force flag to CM it has downloaded new images but it was shown same restarting status for selenoid in docker but after docker restart selenoid is up but still getting below exception when I tried to launch remotewebdriver instance.
**org.openqa.selenium.WebDriverException: create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 131 milliseconds**

I am using below code for testing purpose:
 DesiredCapabilities capabilities = new DesiredCapabilities();
	  capabilities.setBrowserName("chrome");
	  capabilities.setVersion("77.0");
	  capabilities.setCapability("enableVNC", true);
	  capabilities.setCapability("enableVideo", false);

	  RemoteWebDriver driver = new RemoteWebDriver(
	      URI.create("http://localhost:4444/wd/hub").toURL(), 
	      capabilities
	  );
	  
	  driver.get("http://google.com");
	  Thread.sleep(25000);
	  driver.quit();

**Comment by vania-pooh** [comment]
@HarikaSuman take a look at `docker logs selenoid` to understand the reason.

**Comment by istvandesign** [comment]
You are using an old version of CM, get the latest one. 
If you use: `cm_windows_amd64.exe version` you should receive:
Git Revision: 1.7.0
UTC Build Time: 2019-09-11_07:20:23AM

and after running cm_windows_amd64.exe selenoid update the issue should go away. 

Next if you have other issues than you probably have to give permissions to C: in docker.

**Comment by LiPhynd** [comment]
I have the same issue after Docker desktop version upgraded to 2.2.0.0. 
Facing the same issue trying Start Selenoid with CM or Start Selenoid with Docker. a week ago, Ggr was working well. After removing all containers, I could not even start Selenoid alone.

![image](https://user-images.githubusercontent.com/45089149/73586998-84f0ce80-4483-11ea-8251-2636be789662.png)
PS C:\selenoid> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

I am using Windows for Linux Container.  Do I need to turn on WSL2?

**Comment by vania-pooh** [comment]
@LiPhynd interesting they could have changed API socket path.

**Comment by LiPhynd** [comment]
@vania-pooh thank you for you quickly reply.  What next step I can do? Uninstall Docker and reinstall Docker will help?

**Comment by vania-pooh** [comment]
@LiPhynd show me `docker inspect selenoid` output.

**Comment by LiPhynd** [comment]
Vania-pooh, please see below logs and inspect selenoid. thank you.
PS C:\selenoid> docker logs selenoid
2020/02/02 06:33:57 [-] [INIT] [Loading configuration files...]
2020/02/02 06:33:57 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/02/02 06:33:57 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/02/02 06:33:57 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2020/02/02 06:33:57 [-] [INIT] [Using Docker API version: 1.40]
2020/02/02 06:33:57 [-] [INIT] [Timezone: UTC]
2020/02/02 06:33:57 [-] [INIT] [Listening on :4444]
2020/02/02 06:37:37 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2020/02/02 06:37:37 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2020/02/02 06:37:37 [29] [LOCATING_SERVICE] [chrome] []
2020/02/02 06:37:37 [-] [DEFAULT_VERSION] [Using default version: 79.0]
2020/02/02 06:37:37 [29] [USING_DOCKER] [chrome] [79.0]
2020/02/02 06:37:37 [29] [CREATING_CONTAINER] [selenoid/vnc:chrome_79.0]
2020/02/02 06:37:37 [29] [SERVICE_STARTUP_FAILED] [create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
PS C:\selenoid> docker inspect selenoid selenoid
[
    {
        "Id": "c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259",
        "Created": "2020-02-02T06:33:57.253208795Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-listen",
            ":4444",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-video-recorder-image",
            "selenoid/video-recorder:latest-release",
            "-log-output-dir",
            "/opt/selenoid/logs/"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 66037,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-02-02T06:33:57.649886348Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c349d7b3e7e421496b2f2867c1d4306d79f221ebfdd75539e7b93fa02d4272fd",
        "ResolvConfPath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/hostname",
        "HostsPath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/hosts",
        "LogPath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259-json.log",
        "Name": "/selenoid",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/host_mnt/c/Users/Phynd/.aerokube/selenoid:/etc/selenoid:ro,Z",
                "/host_mnt/c/Users/Phynd/.aerokube/selenoid/video:/opt/selenoid/video:Z",
                "/host_mnt/c/Users/Phynd/.aerokube/selenoid/logs:/opt/selenoid/logs:Z"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c-init/diff:/var/lib/docker/overlay2/295a04b9854f90cfab707a791a7f6829fb4281ce838be8a9124706c91fb2d392/diff:/var/lib/docker/overlay2/93ef9b3433d40cef73b9374313164228f90abc723f9a4884ba7e439b048e7bdf/diff:/var/lib/docker/overlay2/d8303ee4b269c8bfc14c3d0b801d2c81aa51379ca96ef8bd5d77e460048a438e/diff",
                "MergedDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c/merged",
                "UpperDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c/diff",
                "WorkDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/Phynd/.aerokube/selenoid/logs",
                "Destination": "/opt/selenoid/logs",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/Phynd/.aerokube/selenoid",
                "Destination": "/etc/selenoid",
                "Mode": "ro,Z",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/Phynd/.aerokube/selenoid/video",
                "Destination": "/opt/selenoid/video",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "localhost",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/Phynd/.aerokube/selenoid/video",
                "DOCKER_API_VERSION=1.40",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/",
                "-video-recorder-image",
                "selenoid/video-recorder:latest-release",
                "-log-output-dir",
                "/opt/selenoid/logs/"
            ],
            "Image": "aerokube/selenoid:latest-release",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "58110e659661bcd386b403d6f4d4484af4e512c36b0dfce3cdeb7b7898409337",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/58110e659661",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "985d24bcbf7dcd44dd378a7c9af50306194b5b385932da0b0aea48258e41c052",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "bc9c60a816279f87825db78b630116ca01557cf803a647b46a5b23172c338082",
                    "EndpointID": "985d24bcbf7dcd44dd378a7c9af50306194b5b385932da0b0aea48258e41c052",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    },
    {
        "Id": "c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259",
        "Created": "2020-02-02T06:33:57.253208795Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-listen",
            ":4444",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/",
            "-video-recorder-image",
            "selenoid/video-recorder:latest-release",
            "-log-output-dir",
            "/opt/selenoid/logs/"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 66037,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-02-02T06:33:57.649886348Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c349d7b3e7e421496b2f2867c1d4306d79f221ebfdd75539e7b93fa02d4272fd",
        "ResolvConfPath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/hostname",
        "HostsPath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/hosts",
        "LogPath": "/var/lib/docker/containers/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259/c6dc8a4ffc8ef5f397b8a620caab0b3e86b08e73d919150c97255fd8aa877259-json.log",
        "Name": "/selenoid",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/host_mnt/c/Users/Phynd/.aerokube/selenoid:/etc/selenoid:ro,Z",
                "/host_mnt/c/Users/Phynd/.aerokube/selenoid/video:/opt/selenoid/video:Z",
                "/host_mnt/c/Users/Phynd/.aerokube/selenoid/logs:/opt/selenoid/logs:Z"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c-init/diff:/var/lib/docker/overlay2/295a04b9854f90cfab707a791a7f6829fb4281ce838be8a9124706c91fb2d392/diff:/var/lib/docker/overlay2/93ef9b3433d40cef73b9374313164228f90abc723f9a4884ba7e439b048e7bdf/diff:/var/lib/docker/overlay2/d8303ee4b269c8bfc14c3d0b801d2c81aa51379ca96ef8bd5d77e460048a438e/diff",
                "MergedDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c/merged",
                "UpperDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c/diff",
                "WorkDir": "/var/lib/docker/overlay2/b6f9d8371fd6552277859665a52922ee096fe5fd956b82f803210ba434c05c0c/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/Phynd/.aerokube/selenoid/video",
                "Destination": "/opt/selenoid/video",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/Phynd/.aerokube/selenoid/logs",
                "Destination": "/opt/selenoid/logs",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/host_mnt/c/Users/Phynd/.aerokube/selenoid",
                "Destination": "/etc/selenoid",
                "Mode": "ro,Z",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "localhost",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/Phynd/.aerokube/selenoid/video",
                "DOCKER_API_VERSION=1.40",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/",
                "-video-recorder-image",
                "selenoid/video-recorder:latest-release",
                "-log-output-dir",
                "/opt/selenoid/logs/"
            ],
            "Image": "aerokube/selenoid:latest-release",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "58110e659661bcd386b403d6f4d4484af4e512c36b0dfce3cdeb7b7898409337",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4444/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4444"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/58110e659661",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "985d24bcbf7dcd44dd378a7c9af50306194b5b385932da0b0aea48258e41c052",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "bc9c60a816279f87825db78b630116ca01557cf803a647b46a5b23172c338082",
                    "EndpointID": "985d24bcbf7dcd44dd378a7c9af50306194b5b385932da0b0aea48258e41c052",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by vania-pooh** [comment]
@HarikaSuman it seems that for some reason Docker socket is not mounted correctly.
```
"Binds": [
"/host_mnt/c/Users/Phynd/.aerokube/selenoid:/etc/selenoid:ro,Z",
"/host_mnt/c/Users/Phynd/.aerokube/selenoid/video:/opt/selenoid/video:Z",
"/host_mnt/c/Users/Phynd/.aerokube/selenoid/logs:/opt/selenoid/logs:Z"
]
```
There should be an entry with `docker.sock` here. Please try to reinstall Selenoid with CM as follows (and copy-paste the log here):
```
$ ./cm selenoid update
```

**Comment by LiPhynd** [comment]
@vania-pooh After i run ./cm selenoid update, i am still unable to start run the Test case. I do not have an issue with using Docker Desktop previous version.

780d53be4472        aerokube/selenoid-ui       "/selenoid-ui --sele…"   19 hours ago        Up 7 seconds (healthy)   0.0.0.0:8080->8080/tcp   selenoid-ui
657218342e96        aerokube/selenoid:1.10.0   "/usr/bin/selenoid -…"   19 hours ago        Up About a minute        0.0.0.0:4444->4444/tcp   selenoid
PS C:\selenoid> docker logs -f selenoid
2020/02/02 09:24:06 [-] [INIT] [Loading configuration files...]
2020/02/02 09:24:06 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/02/02 09:24:06 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/02/02 09:24:06 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2020/02/02 09:24:06 [-] [INIT] [Using Docker API version: 1.40]
2020/02/02 09:24:06 [-] [INIT] [Timezone: UTC]
2020/02/02 09:24:06 [-] [INIT] [Listening on :4444]
2020/02/02 09:26:19 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2020/02/02 09:26:19 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2020/02/02 09:26:19 [25] [LOCATING_SERVICE] [chrome] []
2020/02/02 09:26:19 [-] [DEFAULT_VERSION] [Using default version: 79.0]
2020/02/02 09:26:19 [25] [USING_DOCKER] [chrome] [79.0]
2020/02/02 09:26:19 [25] [CREATING_CONTAINER] [selenoid/vnc:chrome_79.0]
2020/02/02 09:26:19 [25] [SERVICE_STARTUP_FAILED] [create container: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]

**Comment by vania-pooh** [comment]
@LiPhynd what is your CM version? (`cm --version`)

**Comment by LiPhynd** [comment]
@vania-pooh 
PS C:\selenoid> ./cm version
Git Revision: 1.5.7
UTC Build Time: 2018-12-20_08:27:58AM
PS C:\selenoid>

**Comment by vania-pooh** [comment]
@LiPhynd try to use latest release. https://github.com/aerokube/cm/releases/tag/1.7.1

**Comment by LiPhynd** [comment]
@vania-pooh, Thank you so much for immediately supported me. it is working now after got the CM version 1.7.1. i am able to continue working on Ggr; and Ggr-ui integration with Selenoid and selenoid-ui.

**Comment by vania-pooh** [comment]
Ok, closing then.
