### ISSUE TITLE
The container is deleted and in the state of pending does not go away

### ISSUE THREAD

**Issue by dedulay** [aerokube/selenoid#810]
http://localhost:4444/status
{"total":5,"used":0,"queued":0,"pending":2,"browsers":{"chrome":{"76.0":{},"77.0":{}},"firefox":{"68.0":{},"69.0":{}},"opera":{"62.0":{},"63.0":{}}}}

As I understood this happened from for mistakes:
2019/09/30 14:01:54 [384] [SESSION_DELETED] [2a3a66e2984801c146012fafe793f1fa]
2019/09/30 14:02:24 [370] [DELETE_FAILED] [2a3a66e2984801c146012fafe793f1fa] [Delete http://127.0.0.1:4444/wd/hub/session/2a3a66e2984801c146012fafe793f1fa: context deadline exceeded]
2019/09/30 14:02:24 [384] [CLIENT_DISCONNECTED] [unknown] [127.0.0.1] [Error: context canceled]
2019/09/30 14:02:24 [367] [REMOVING_CONTAINER] [9722593ee146d91fb99bc86f719d8870b50f5c5d7f831bc3cb3e8001f508d15b]
2019/09/30 14:02:24 [370] [CLIENT_DISCONNECTED] [unknown] [172.17.0.1] [Error: EOF]
2019/09/30 14:02:25 [367] [CONTAINER_REMOVED] [9722593ee146d91fb99bc86f719d8870b50f5c5d7f831bc3cb3e8001f508d15b]
2019/09/30 15:17:39 [1314] [CONTAINER_LOGS_DISCONNECTED] [1a67453a21c996a591246c7d6a264054]
2019/09/30 15:18:03 [1310] [DELETE_FAILED] [1a67453a21c996a591246c7d6a264054] [Delete http://127.0.0.1:4444/wd/hub/session/1a67453a21c996a591246c7d6a264054: context deadline exceeded]
2019/09/30 15:18:03 [1327] [CLIENT_DISCONNECTED] [unknown] [127.0.0.1] [Error: context canceled]
2019/09/30 15:18:03 [1309] [REMOVING_CONTAINER] [61bd14a88ccd0045d1d7c650b5ec140179d52bf7816d87be8991ec1a52a5f3b9]
2019/09/30 15:18:03 [1310] [CLIENT_DISCONNECTED] [unknown] [172.17.0.1] [Error: EOF]
2019/09/30 15:18:04 [1309] [CONTAINER_REMOVED] [61bd14a88ccd0045d1d7c650b5ec140179d52bf7816d87be8991ec1a52a5f3b9]
2019/09/30 15:24:05 [1425] [CONTAINER_LOGS_DISCONNECTED] [8bb38307e73008c5bad9faa99385b245]
2019/09/30 15:24:25 [1418] [DELETE_FAILED] [8bb38307e73008c5bad9faa99385b245] [Delete http://127.0.0.1:4444/wd/hub/session/8bb38307e73008c5bad9faa99385b245: context deadline exceeded]
2019/09/30 15:24:25 [1437] [CLIENT_DISCONNECTED] [unknown] [127.0.0.1] [Error: context canceled]
2019/09/30 15:24:25 [1416] [REMOVING_CONTAINER] [f09144b96f6a97e8c653e017c1e13391217d43303bcc7a06544bfdf8178f2607]
2019/09/30 15:24:25 [1418] [CLIENT_DISCONNECTED] [unknown] [172.17.0.1] [Error: EOF]
2019/09/30 15:24:25 [1416] [CONTAINER_REMOVED] [f09144b96f6a97e8c653e017c1e13391217d43303bcc7a06544bfdf8178f2607]

Versions:
Docker version 19.03.2, build 6a30dfc
aerokube/selenoid: 1.9.2
aerokube/selenoid-ui: 1.8.1

docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                    NAMES
3ad176492bd4        aerokube/selenoid-ui:1.8.1   "/selenoid-ui --sele…"   19 hours ago        Up 19 hours         0.0.0.0:8080->8080/tcp   selenoid-ui
693ac88cb0a7        aerokube/selenoid:1.9.2      "/usr/bin/selenoid -…"   22 hours ago        Up 22 hours         0.0.0.0:4444->4444/tcp   selenoid

**Comment by vania-pooh** [comment]
@dedulay take a look at system metrics such as load average, iowait and memory usage. This can be a sign that you created too many parallel sessions on your machine.

**Comment by vania-pooh** [comment]
Closing as it Docker bug or overloaded server symptoms.
