### ISSUE TITLE
Error "The application at 'apk path' does not exist or is not accessible" while selenoid starts tests in the Android container

### ISSUE THREAD

**Issue by Grosha** [aerokube/selenoid#811]
Can't run tests in android container, there is fails with an error that apk does not exist or is not accessible.
When I run tests via Appium - apk installs to the device correctly.

I set up Linux VM (hosts on the amazon), android container is pulled to the docker and runs. Container selenoid started with timeout of 3 min. Docker works only from root.

Maybe you the reason why driver/container has a problem with downloading apk?
@vania-pooh Maine question - how to install apk to the selenoid container?

`/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=50800:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/testng-plugin.jar:/Volumes/Second/automation/privacy_mobile_automation/android-tests/out/test/classes:/Volumes/Second/automation/privacy_mobile_automation/android-tests/out/test/resources:/Volumes/Second/automation/privacy_mobile_automation/android-tests/page-objects/out/production/classes:/Volumes/Second/automation/privacy_mobile_automation/android-tests/page-
...
...
....
...
...
16:54:36.829 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "0[\r][\n]"
16:54:36.829 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
16:54:36.830 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://api.github.com:443] can be kept alive indefinitely
16:54:36.830 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 0
16:54:36.830 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://api.github.com:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
16:54:36.888 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of wires, geckodriver is 0.25.0
16:54:36.899 [main] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
16:54:36.900 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.gecko.driver as /Users/groshkka/.m2/repository/webdriver/geckodriver/macos/0.25.0/geckodriver
`

Error:
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/groshkka/app-forTest-debug.apk' does not exist or is not accessible
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'groshkka-m-nb', ip: 'fe80:0:0:0:103a:11a2:2389:a4cb%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.1'
Driver info: driver.version: RemoteWebDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/groshkka/app-forTest-debug.apk' does not exist or is not accessible
    at getResponseForW3CError (/opt/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/opt/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)`

`       DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("noReset", false);
        capabilities.setCapability("newCommandTimeout", 90);
        capabilities.setBrowserName("android");
        capabilities.setVersion("8.1");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", false);`

**Comment by vania-pooh** [comment]
@Grosha this path `/Users/groshkka/app-forTest-debug.apk` does not exist inside container. You have to use paths inside container.

**Comment by Grosha** [comment]
I didn't find a way to put apk to the selenoid android container so I wrote a little server (python + flask + docker -> example is [here](https://docs.faculty.ai/user-guide/apis/flask_apis/flask_file_upload_download.html)) which has GET service for downloading the file.

**Comment by vania-pooh** [comment]
@Grosha closing then?
