### ISSUE TITLE
getAttribute does throws an exception when using mobile chrome images

### ISSUE THREAD

**Issue by boris779** [aerokube/selenoid#812]
If trying to getAttribute on an WebElement when using mobie-chrome Images this will occur in an javascript Exception

```webelement.getAttribute("alt")``` 

throws:

```org.openqa.selenium.JavascriptException: [object Object] javascript error: a.getAttributeNode is not a function (Session info: chrome=75.0.3770.89)```

**Comment by vania-pooh** [comment]
@boris779 here Appium guys say you have to update your Appium client library: https://github.com/appium/appium/issues/11774

**Comment by boris779** [comment]
I got it. The Problem was that I used RemoteWebdriver instead of AppiumDriver.
