### ISSUE TITLE
alwaysMatch for W3C spec

### ISSUE THREAD

**Issue by emilorol** [aerokube/selenoid#815]
Working on making Microsoft Edge VM in a container work with Selenoid I discover the issue of W3C and digging on the code I can see the current version of Selenoid support it.

I was able to run the following test and the Edge browser open up in the dockerized Windows VM in Selenoid

```
curl -X POST http://127.0.0.1:4444/wd/hub/session -d '{"capabilities":{"alwaysMatch":{"browserName": "MicrosoftEdge", "selenoid:options":{"enableVNC": true}}}}'
```

I was able to pass more commands like to load the url, click and close the browser like a charm too.

The question is how do I pass the `alwaysMatch` so that Selenoid can work with the Edge browser like it does with the other browsers?

**Comment by aandryashin** [comment]
Selenoid supports w3c alwaysMatch...

пт, 18 окт. 2019 г., 8:01 Emil Orol <notifications@github.com>:

**Comment by emilorol** [comment]
I know it does, but how do I pass it is my question?

Protractor Example:

```
// An example configuration file
exports.config = {
  // The address of a running selenoid server.
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    browserName: 'chrome',
    browserVersion: '75.0',
    enableVNC: true
  }
};
```

**Comment by vania-pooh** [comment]
@emilorol Protractor should handle these low-level protocol details itself. Just replace `browserName` and `browserVersion`:
```
capabilities: {
    browserName: 'chrome',
    browserVersion: '75.0',
    "selenoid:options": {
      enableVNC: true
    }
  }
```

**Comment by emilorol** [comment]
Unfortunately it does not.

Even after passing something like this:

```
multiCapabilities: [
    {
      browserName: "MicrosoftEdge",
      "firstMatch": [{
        browserName: "MicrosoftEdge",
        "selenoid:options": {
          enableVNC: true,
          enableVideo: false,
          enableLog: true,
          logName: "edge-18.0.log"
        }
      }]
    }
  ]
```
The posted JSON is:
```
{
	"desiredCapabilities": {
		"browserName": "MicrosoftEdge",
		"count": 1,
		"firstMatch": [{
			"browserName": "MicrosoftEdge",
			"selenoid:options": {
				"enableVNC": true,
				"enableVideo": false,
				"enableLog": true,
				"logName": "edge-18.0.log"
			}
		}]
	}
}
```
Thank you for your help
