### ISSUE TITLE
Is there a possibility to run not rooted selenoid android container?

### ISSUE THREAD

**Issue by Grosha** [aerokube/selenoid#816]
Running tests with selenoid android containers is a very profitable way but I find that davice in the container is rooted. As you know in the world there are not many people who has rooted devices so you actually don't know how works your application in almost all people.

@vania-pooh Is there a possibility to run not rooted selenoid android container?

**Comment by vania-pooh** [comment]
@Grosha it should be already rooted: https://github.com/aerokube/selenoid-images/blob/master/selenium/android/emulator-snapshot.sh#L3

Or just add `adb root` to `entrypoint.sh` and rebuild the image.

**Comment by Grosha** [comment]
Actually I need NOT rooted android. So if I remove `adb root` from `entrypoint.sh` the container will be with NOT rooted android?

**Comment by vania-pooh** [comment]
@Grosha yep, should be.
