### ISSUE TITLE
WebDriverException: Message: start container: Error response from daemon: endpoint with name jolly_colden already exists in network my_network

### ISSUE THREAD

**Issue by asfaltboy** [aerokube/selenoid#819]
Selenoid v1.9.0 running via docker container (aerokube/selenoid:1.9.0)

It seems this is a pretty rare condition, we've been running selenoid for about 1.5 years and this is the first occurance.

We can probably mock this edge case in go for a test. Let me know if you'd like to see a contribution.

**Comment by vania-pooh** [comment]
@asfaltboy yeah, such collision is very very rare. And this is Docker responsibility to assign unique names. One possible option we could implement is to use UUIDs as container names instead of default Docker names.
