### ISSUE TITLE
Is it possible to run a remote profile for Firefox?

### ISSUE THREAD

**Issue by SHELA** [aerokube/selenoid#821]
Hello,
Is it possible to run a remote profile for Firefox?
also to install remote extension?
install_addon return error
Thank you

**Comment by vania-pooh** [comment]
@SHELA yes, this is possible. Just set `profile` capability to RemoteWebDriver.

**Comment by u9O** [comment]
@vania-pooh what about chrome profile, is it possible ?

**Comment by vania-pooh** [comment]
Closing in favor to #930.
