### ISSUE TITLE
Selenoid allows less sessions than specified with -limit

### ISSUE THREAD

**Issue by khaelou** [aerokube/selenoid#822]
I have both Selenoid & Selenoid-UI deployed via Docker with the command "-limit 10" in my docker-compose.yaml file, yet I'll later run my application and when it attempts to request more than 3 browsers at a time the connection refuses. To verify I navigate to http://127.0.0.1:4444/status in my browser with the total value correctly reading 10, is there any reason for this or a simple fix?

**Comment by vania-pooh** [comment]
@khaelou if you are running everything on your workstation and having Mac \ Windows - then check that your Docker instance has sufficient resources allocated. For every browser you need to have 1 CPU and 1 Gb RAM. Refused connections could be just because of overloaded machine.

**Comment by khaelou** [comment]
That makes sense, thank you.
