### ISSUE TITLE
Exposing Selenoid host/port to other Docker containers

### ISSUE THREAD

**Issue by khaelou** [aerokube/selenoid#823]
I have Selenoid & Selenoid-UI successfully deployed via my docker-compose.yaml file, yet when I attempt to do "docker run MY_APP" instead of the traditional "go run main.go" my application (Goland project) is refused connection to http://127.0.0.1:4444/wd/hub. Considering "go run main.go" successfully connects to Selenoid server, I'm a little confused. I have a feeling I just need to tell my host to interact with the Docker ports somehow but how would I go about this?

Error when "docker run MY_APP":

panic: Post http://127.0.0.1:4444/wd/hub/session: dial tcp 127.0.0.1:4444: connect: connection refused

**Comment by aandryashin** [comment]
When application runs within container it has isolated network, so
127.0.0.1 is not a host ip address, it is container's localhost... Could
you please try to use docker option --nerwork=host...

ср, 23 окт. 2019 г., 7:26 KHAEL <notifications@github.com>:

**Comment by khaelou** [comment]
As in "docker run MY_APP --network=host.." or would I use "docker-machine ls" and use a url from there? Could you broaden the example a bit .. kinda new to Docker

**Comment by khaelou** [comment]
Okay so I ran "docker run --network "host" MY_APP" as you suggested and it successfully connected to Selenoid. Much appreciated!
