### ISSUE TITLE
Browsers and containers naming convention

### ISSUE THREAD

**Issue by emilorol** [aerokube/selenoid#824]
I added IE and Edge to Selenoid and it is working great. 

I just noticed something that I think should be improved the user experience in the future:

When looking at the available browsers I see:
```
0% | 0 | MicrosoftEdge
0% | 0 | android
0% | 0 | chrome
0% | 0 | firefox
0% | 0 | internet explorer
0% | 0 | opera
```

I think it will look better if it is like this:

```
0% | 0 | edge
0% | 0 | android
0% | 0 | chrome
0% | 0 | firefox
0% | 0 | ie
0% | 0 | opera
```
I know how picky are IE and Edge about calling them with the right name, but maybe an extra key on the `browsers.json` config can fix this.

```
    "internet explorer": {
        "display": "ie",  <=========// custom new key to display in the selenoid screen
        "default": "11.0",
        "versions": {
            "11.0": {
                "image": "windows:ie-11",
                "port": "4444",
                "path": "/",
                "privileged": true
            }
        }
    },
```
Again, this is just my opinion and an idea. 

Thank you for the great job you guys have done.

**Comment by vania-pooh** [comment]
@lanwen any simpler solutions?

**Comment by lanwen** [comment]
whats the point of doing that?

**Comment by emilorol** [comment]
The only point is to make happy all the QA, Developers and Testers with an OCD tendency, lol.

**Comment by lanwen** [comment]
I mean what's the difference between original "MicrosoftEdge" and "edge"? Just want to understand the usecase - you want shorter names, all lowercase? Is that only for the stats?

**Comment by emilorol** [comment]
This is just a user experience case. All you available browser/container that are not from Microsoft are in small letters and there comes Microsoft with its camel case for Edge and space in internet explorer. The main idea is to keep the name look about the same and also to give you the user the possibility of making them your own.

**Comment by megalan247** [comment]
The issue I see is if you send the Edge 18 webdriver a session request with the browserName "edge" it will refuse it, and having the browser name be different in the UI may lead to confusion within your QA and Dev teams about what exactly the correct capabilities are.

**Comment by vania-pooh** [comment]
I would leave as is as it could really confuse users. Let's leave things consistent.

**Comment by emilorol** [comment]
I understand the possibility of confusions, but you also have a section where you display the basic setup of the capabilities where you can show the right name of the driver regardless of what the display name is.

You can also have this feature as a dark feature that only if use will overwrite the display otherwise it will behave as it currently does.
