### ISSUE TITLE
./cm selenoid not connecting to ./cm selenoid-ui

### ISSUE THREAD

**Issue by khaelou** [aerokube/selenoid#825]
I was running Selenoid & Selenoid-UI initially with Docker Compose yet I switched to ./cm and managed to get both Selenoid & Selenoid-UI running yet they were not connected to each other. What's the issue in this case? The initial reason for my switch from Docker Compose to ./cm was that Selenoid-UI no longer wanted to run to a "non running container", in this case being Selenoid...

**Comment by vania-pooh** [comment]
@khaelou could you please show logs for your CM command. The following usually resolves 90% of issues:
```
$ ./cm selenoid start --vnc --force
```

**Comment by khaelou** [comment]
How would I see the logs for CM? 

$ ./cm selenoid start --vnc force
> Using Docker
- Your Docker API version is 1.40
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid

$ ./cm selenoid-ui start
> Using Docker
- Your Docker API version is 1.40
> Selenoid UI is already downloaded
> Starting Selenoid UI...
> Successfully started Selenoid UI

Yet when I go to http://127.0.0.1:8080/ Selenoid-UI states there is an "issue" under Selenoid. Unknown under SSE and 0% used. Queued is empty and Quota is just +/

**Comment by vania-pooh** [comment]
@khaelou then try to add `--force` flag as follows:
```
$ ./cm selenoid-ui start --force
```

**Comment by khaelou** [comment]
Just ran both commands, neither fixing the issue.

$ ./cm selenoid start --vnc --force
> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.9.2
> Configuring Selenoid...
> Processing browser "opera"...
- Fetching tags for image selenoid/opera
registry.tags url=https://registry.hub.docker.com/v2/selenoid/opera/tags/list repository=selenoid/opera
- Requested to download VNC images...
- Pulling image selenoid/vnc_opera:63.0
- Pulling image selenoid/vnc_opera:62.0
> Processing browser "firefox"...
- Fetching tags for image selenoid/firefox
registry.tags url=https://registry.hub.docker.com/v2/selenoid/firefox/tags/list repository=selenoid/firefox
- Requested to download VNC images...
- Pulling image selenoid/vnc_firefox:70.0
- Pulling image selenoid/vnc_firefox:69.0
> Processing browser "chrome"...
- Fetching tags for image selenoid/chrome
registry.tags url=https://registry.hub.docker.com/v2/selenoid/chrome/tags/list repository=selenoid/chrome
- Requested to download VNC images...
- Pulling image selenoid/vnc_chrome:78.0
- Pulling image selenoid/vnc_chrome:77.0
> Pulling video recorder image...
- Pulling image selenoid/video-recorder:latest-release
> Configuration saved to /Users/khaelou/.aerokube/selenoid/browsers.json
> Starting Selenoid...
> Successfully started Selenoid

$ ./cm selenoid-ui start --force
> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid UI...
- Fetching tags for image aerokube/selenoid-ui
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid-ui/tags/list repository=aerokube/selenoid-ui
- Pulling image aerokube/selenoid-ui:1.9.0
> Starting Selenoid UI...
> Successfully started Selenoid UI

**Comment by khaelou** [comment]
<img width="1528" alt="Screen Shot 2019-10-24 at 11 52 48 AM" src="https://user-images.githubusercontent.com/28240459/67502989-de5f8b00-f654-11e9-80a6-1febaaeed7f4.png">

**Comment by khaelou** [comment]
<img width="1528" alt="Screen Shot 2019-10-24 at 11 53 45 AM" src="https://user-images.githubusercontent.com/28240459/67503038-f20af180-f654-11e9-9465-c59081c8ea86.png">

**Comment by vania-pooh** [comment]
@khaelou show me Selenoid UI logs then:
```
$ docker logs selenoid-ui
```
And also contents of `docker inspect selenoid-ui`.

**Comment by khaelou** [comment]
`$ docker logs selenoid-ui`

After the above command, this was the output:

2019/10/24 15:48:18 [INIT] [Listening on :8080]
2019/10/24 15:48:26 Client added. 1 registered clients
2019/10/24 15:48:26 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.202.231.169:4444: connect: connection refused]
2019/10/24 15:48:28 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.202.231.169:4444: connect: connection refused]
2019/10/24 15:48:33 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.202.231.169:4444: connect: connection refused]
2019/10/24 15:48:38 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.202.231.169:4444: connect: connection refused]
2019/10/24 15:48:43 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.217.138.110:4444: connect: connection refused]
2019/10/24 15:48:48 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.217.138.110:4444: connect: connection refused]
2019/10/24 15:48:53 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.217.138.110:4444: connect: connection refused]
2019/10/24 15:48:58 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.217.138.110:4444: connect: connection refused]
2019/10/24 15:49:03 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.217.138.110:4444: connect: connection refused]
2019/10/24 15:49:08 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 23.217.138.110:4444: connect: connection refused]
2019/10/24 15:49:13 [ERROR] [Can't get status: Get http://selenoid:4444/status: dial tcp 
etc.....

`docker inspect selenoid-ui`

After the above command, this was the output:

[
    {
        "Id": "2addc4c77fe53d80554ca77c560944c361fd44dc002f5fd003e5f0a97c21f6d1",
        "Created": "2019-10-24T15:48:17.08874463Z",
        "Path": "/selenoid-ui",
        "Args": [
            "--selenoid-uri=http://selenoid:4444"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 77370,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-10-24T15:48:18.137471318Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:aba525f4c071b7e5e821b15e1893e8a86c311a3de00d822610ed8b6eab5d7c73",
        "ResolvConfPath": "/var/lib/docker/containers/2addc4c77fe53d80554ca77c560944c361fd44dc002f5fd003e5f0a97c21f6d1/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/2addc4c77fe53d80554ca77c560944c361fd44dc002f5fd003e5f0a97c21f6d1/hostname",
        "HostsPath": "/var/lib/docker/containers/2addc4c77fe53d80554ca77c560944c361fd44dc002f5fd003e5f0a97c21f6d1/hosts",
        "LogPath": "/var/lib/docker/containers/2addc4c77fe53d80554ca77c560944c361fd44dc002f5fd003e5f0a97c21f6d1/2addc4c77fe53d80554ca77c560944c361fd44dc002f5fd003e5f0a97c21f6d1-json.log",
        "Name": "/selenoid-ui",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": [
                "/selenoid:/selenoid-ui/selenoid"
            ],
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/fd8d2c17954b6f55bf4a3b3eece74290a3a0e8235f9074bc46d6a54d2f1ef88f-init/diff:/var/lib/docker/overlay2/9c162137b8dbba4d677f7b4ecddd38c080724634055611a89a7d61664b5a6790/diff:/var/lib/docker/overlay2/cf27ee5e1b62b433bbe6b25b3aec7b45352129988e2e5c2115480fe979cbffcb/diff",
                "MergedDir": "/var/lib/docker/overlay2/fd8d2c17954b6f55bf4a3b3eece74290a3a0e8235f9074bc46d6a54d2f1ef88f/merged",
                "UpperDir": "/var/lib/docker/overlay2/fd8d2c17954b6f55bf4a3b3eece74290a3a0e8235f9074bc46d6a54d2f1ef88f/diff",
                "WorkDir": "/var/lib/docker/overlay2/fd8d2c17954b6f55bf4a3b3eece74290a3a0e8235f9074bc46d6a54d2f1ef88f/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "localhost",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TERM_PROGRAM=iTerm.app",
                "TERM=xterm-256color",
                "SHELL=/bin/bash",
                "TMPDIR=/var/folders/kl/xtg3gcd90_q74j7w86_l8fgm0000gn/T/",
                "Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.eaw78JqbGG/Render",
                "TERM_PROGRAM_VERSION=3.3.4",
                "TERM_SESSION_ID=w0t2p0:93B577D2-7C96-4052-86F4-7890083C6738",
                "USER=khaelou",
                "SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.myhCjtYJpK/Listeners",
                "__CF_USER_TEXT_ENCODING=0x0:0:0",
                "PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Users/khaelou/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/khaelou/bin:/usr/local/go/bin:/Users/khaelou/Flutter/flutter/bin",
                "PWD=/Users/khaelou",
                "LANG=en_US.UTF-8",
                "ITERM_PROFILE=Default",
                "XPC_FLAGS=0x0",
                "XPC_SERVICE_NAME=0",
                "SHLVL=1",
                "HOME=/Users/khaelou",
                "COLORFGBG=7;0",
                "LC_TERMINAL_VERSION=3.3.4",
                "ITERM_SESSION_ID=w0t2p0:93B577D2-7C96-4052-86F4-7890083C6738",
                "LOGNAME=khaelou",
                "GOPATH=/Users/khaelou/Go",
                "LC_TERMINAL=iTerm2",
                "COLORTERM=truecolor",
                "_=./cm",
                "DOCKER_API_VERSION=1.40",
                "TZ=Local"
            ],
            "Cmd": [
                "--selenoid-uri=http://selenoid:4444"
            ],
            "Image": "aerokube/selenoid-ui:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/selenoid-ui"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "1805769c9037da2bd494a4543a568f7b0cbda6c0f1cbdc35dc91f0f844d2fd5a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/1805769c9037",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "eb89afc740d471d1727b14c13f094fd5bb761a16cef6ff2e0291418cb2fa8cf8",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.5",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:05",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "733ceab37be00d384174b742de311990236e0e1567d4e4ae6575a72e6e3e49e3",
                    "EndpointID": "eb89afc740d471d1727b14c13f094fd5bb761a16cef6ff2e0291418cb2fa8cf8",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:05",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by vania-pooh** [comment]
@khaelou 
1) Selenoid is expected to be running in container named Selenoid.
2) Also if you are having RedHat / CentOS - this could be a firewall or SELinux issue.

**Comment by khaelou** [comment]
I'll consider renaming the running Selenoid container to "Selenoid". I'm on a Mac though with firewall enabled so this may also be the issue, thanks.
