### ISSUE TITLE
Unable to modify docker image

### ISSUE THREAD

**Issue by prasanth-G24** [aerokube/selenoid#837]
I am trying to modify the firefox browser present inside the selenoid/vnc_firefox container. I am trying to replace the one that is already present with a developer edition. 

The reason why I am doing this is because, I am trying to run an unsigned firefox extension for my tests, which obviously will not work with the normal firefox. I am trying to reach the shell of the vnc_firefox and find the path of firefox browser by running the command: `docker run -it selenoid/vnc_firefox:70.0 bash`. Unfortunately it is starting the firefox browser.

Can anyone guide how to access the terminal?

![Screenshot](https://user-images.githubusercontent.com/35618065/68481013-23daa580-025c-11ea-8067-a7df0c153160.png)

Or please provide the path for firefox

**Comment by vania-pooh** [comment]
@prasanth-G24 `docker run -it --entrypoint /bin/bash selenoid/vnc_firefox:70.0`
