### ISSUE TITLE
Facing unknown issue when using with centos 7

### ISSUE THREAD

**Issue by prasanth-G24** [aerokube/selenoid#838]
When starting the selenoid using `./cm selenoid start --vnc`, I am getting 
> Using Docker
- Your Docker API version is 1.40
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid

Similarly I face no issues when starting the selenoid UI: `./cm selenoid-ui start --port 9080`
> Using Docker
- Your Docker API version is 1.40
> Selenoid UI is already downloaded
> Starting Selenoid UI...
> Successfully started Selenoid UI

But when I go to the browser and reach the 9080 port, I am seeing this error:
![Screenshot from 2019-11-11 17-17-30](https://user-images.githubusercontent.com/35618065/68585236-aefbab80-04a7-11ea-94ab-1915ce5f8467.png)

System configuration:
- centos version: 7
- docker version: 19.03.2
- selenoid version: 1.9.3
- browser image versions: chrome(78.0), firefox(70.0), opera(64.0)
Here's my browsers.json file:
```
{
    "chrome": {
        "default": "78.0",
        "versions": {
           "78.0": {
                "image": "selenoid/vnc_chrome:78.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "firefox": {
        "default": "70.0",
        "versions": {
            "70.0": {
                "image": "selenoid/vnc_firefox:70.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "opera": {
        "default": "64.0",
        "versions": {
            "64.0": {
                "image": "selenoid/vnc_opera:64.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    }
}
```
#### Also the browser images did not get downloaded while running `./cm selenoid start --vnc`. I downloaded the images in my ubuntu and transferred it to centos. Likewise the browsers.json did not get created automatically. I wrote it by myself.

**Comment by vania-pooh** [comment]
@prasanth-G24 everything should be automatically downloaded and installed with `--force` flag.

**Comment by prasanth-G24** [comment]
> @prasanth-G24 everything should be automatically downloaded and installed with `--force` flag.

Thank you so much. I did not know this because in my ubuntu all the images got downloaded automatically without the --force flag.

**Comment by prasanth-G24** [comment]
> @prasanth-G24 everything should be automatically downloaded and installed with `--force` flag.

I have a small problem @vania-pooh. Instead of downloading two versions of a browser, can I make it download only one version?

**Comment by vania-pooh** [comment]
@prasanth-G24 sure, just add `--last-versions 1` to download only 1 latest version of specify which exact versions do you need with `--browsers chrome:76.0`. https://aerokube.com/cm/latest/#_downloading_only_some_browser_versions
