### ISSUE TITLE
vnc not working properly in centos

### ISSUE THREAD

**Issue by prasanth-G24** [aerokube/selenoid#841]
I've been using selenoid for more than a week and only in the last 2 days this issue keeps happening.

![Screenshot from 2019-11-19 14-41-30](https://user-images.githubusercontent.com/35618065/69244951-f979d800-0bcb-11ea-9d83-e41c8c585c24.png)

When trying to view the test case actions on selenoid-ui, only the logs screen appears. The video screen is getting hidden. Happens for both firefox 70 and chrome 78. Never faced this issue earlier. Also I didn't update or modify any images. The selenoid version is 1.9.3

**Comment by vania-pooh** [comment]
@prasanth-G24 
1) Videos tab is only shown when you already have recorded videos.
2) VNC is shown only when `enableVNC: true` capability is set.
