### ISSUE TITLE
Volume Mount not working

### ISSUE THREAD

**Issue by success-stha** [aerokube/selenoid#842]
`docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /dev/shm:/dev/shm -v /opt/docker/fileDownloadLocation:/home/selenium/Downloads -v /opt/docker/selenoid/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release -limit 8 -timeout 10m0s`
Above is the code i've tried to mount /home/selenium/Downloads to host. I've have also tried editing browser.json by adding `"volumes": ["/home/selenium/Downloads:/opt/docker/fileDownloadLocation"]` with no success.

**Comment by vania-pooh** [comment]
@success-stha `/home/selenium/Downloads` directory is inside **browser** container, not **selenoid** container.

**Comment by success-stha** [comment]
> @success-stha `/home/selenium/Downloads` directory is inside **browser** container, not **selenoid** container.
Thank you for your reply. Is there anyway I can access the file from browser container directly to my host machine(where docker is installed). Also, I would prefer to do so without using selenoid's download API.

**Comment by vania-pooh** [comment]
@success-stha Adding `"volumes": ["/home/selenium/Downloads:/opt/docker/fileDownloadLocation"]` to `browsers.json` and restarting Selenoid should work.

**Comment by success-stha** [comment]
It didn't work. My browser.json looks like this.
```
{
    "chrome": {
        "default": "78.0",
        "versions": {
            "78.0": {
                "image": "selenoid/vnc:chrome_78.0",
                "port": "4444",
                "volumes": ["/home/selenium/Downloads:/opt/docker/fileDownloadLocation"]
            }
        }
    }
}
```

**Comment by vania-pooh** [comment]
@success-stha any error messages?

**Comment by success-stha** [comment]
No, i tried viewing the log but it's not generated. I used this command.
`docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /dev/shm:/dev/shm -v /opt/docker/selenoid/config/:/etc/selenoid/:ro -v /opt/docker/selenoid/:/opt/selenoid/logs/  aerokube/selenoid:latest-release -limit 8 -timeout 10m0s -log-output-dir /opt/docker/selenoid/logs`

**Comment by vania-pooh** [comment]
@success-stha Selenoid logs are being written to stdout, i.e. you view then with:
```
$ docker logs selenoid
```

**Comment by success-stha** [comment]
`"volumes": ["/opt/docker/fileDownloadLocation:/home/selenium/Downloads"]`
This solved my problem.

**Comment by vania-pooh** [comment]
@success-stha great!

**Comment by Lucifar2** [comment]
@vania-pooh I am having an issue on Windows regarding the same problem. I just want to mount the volume from the host machine to selenoid docker container. Whenever I run the command : 
docker run -d --name selenoid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /dev/shm:/dev/shm -v /opt/docker/fileDownloadLocation:/home/selenium/Downloads -v /opt/docker/selenoid/config/:/etc/selenoid/:ro aerokube/selenoid:latest-release -limit 8 -timeout 10m0s
on cmd then it returns me some error. Please note that I am very new to docker container. Any help will be much appreciated.

**Comment by Lucifar2** [comment]
@success-stha Can you please help me here too.

**Comment by vania-pooh** [comment]
@Lucifar2 so far as I know on Windows by default you can mount only from `c:\Users\user` directory.

**Comment by Lucifar2** [comment]
@vania-pooh Thanks for the reply. So I have a .y4m file in my c:\Users\ directory on windows. I want to expose this file to the container. For this purpose, can I just edit my browser.json file? If yes, then what should be the path to the container directory ? I am really confused about this

**Comment by Lucifar2** [comment]
@vania-pooh Can you tell me some steps that I can follow to make it easier for me to mount the host to the selenoid docker container. I shall be really grateful to you :)

**Comment by Lucifar2** [comment]
@vania-pooh my video file is in the location C:\Users\username\Downloads\abc.y4m. And I want to mount this file to Selenoid docker container. What changes should I make to browser.json and also what should be the format. @success-stha Also if you can help here too would be great.

**Comment by vania-pooh** [comment]
@Lucifar2 yes, use `volumes` in browsers.json.

**Comment by Lucifar2** [comment]
@vania-pooh Thanks for the reply. I have read the documentation for the notation that we can use for Windows. so if my file location is in C:\Users\username\Downloads\ then I should use something like /c/Users/username/Downloads. Is this correct ? Does this notation also applies in browser.json ? Also I am confused what should be the destination path when using volumes in browsers.json.
 C:\Users\username\Downloads\"DestinationPath" . And how can I find the destination path ?

**Comment by Lucifar2** [comment]
@vania-pooh I am doing something like this in the browsers,json file : "volumes":["/c/Users/baig-sa:/tmp/new:rw"]

Is this correct ?

**Comment by Lucifar2** [comment]
@vania-pooh I was able to resolve the issue with volumes. Thanks :)
