### ISSUE TITLE
[SERVICE_STARTUP_FAILED] [wait: http://xxx.xxx.xxx.xxx:xxxxx/ does not respond in 30s]

### ISSUE THREAD

**Issue by KristianLake** [aerokube/selenoid#845]
Hi @vania-pooh 

Been racking my brains over this for a bit trying everything i know to solve this.

I have a GGR in Kubernetes that talks to Selenoid that is also in Kubernetes - this seems to work fine (I know the disadvantages of doing it this way over moon :) )

When my Selenoid container attempts to communicate with the browser image, It is not able to.

The image exists in docker ready to be created and Selenoid finds it and starts the container. but i always get 
[SERVICE_STARTUP_FAILED] [wait: http://xxx.xxx.xxx.xxx:xxxxx/ does not respond in 30s]

The problem I have is this is quite a cryptic error to me, It looks to me like the docker browser container is trying to communicate back to my Selenoid container on the wrong IP. or there is some communication failure along that trajectory.

Do you have any advice on this problem? is there a setting i should look at to fix this? What is it actually trying to do?

Thanks

**Comment by vania-pooh** [comment]
@topproto Selenoid has `-container-network` flag allowing to specify in which network your containers are running.

**Comment by topproto** [comment]
Thanks for the quick reply, I have tried default, bridge and host, and they did not seem to work for me, do i need to specify the Kubernetes network container?

**Comment by topproto** [comment]
Also if it helps My cluster is using the Flannel network, although i have not done anything in docker with Flannel, perhaps i need to configure docker to use cbr?

**Comment by aandryashin** [comment]
Are you trying to run selenoid in Kubernetes?

пт, 6 дек. 2019 г., 19:17 topproto <notifications@github.com>:

**Comment by topproto** [comment]
@aandryashin I have Selenoid running in Kubernetes already (and the GGR), When it creates the browser container it can't communicate back to the Selenoid container in Kubernetes.

Unless there is a way I can create the browser container inside Kubernetes and have Selenoid call it from there.

Its literally the last piece of the puzzle im stuck on :(

**Comment by aandryashin** [comment]
We do not support selenoid installation in kubernetes, because it is very
dangerous to grant direct access to kubernetes docker, cluster can become
unstable. Please consider this solution developed for kubernetes:

https://aerokube.com/moon/latest/

пт, 6 дек. 2019 г., 19:22 topproto <notifications@github.com>:

**Comment by topproto** [comment]
@aandryashin thanks for the reply.

What direct access needs to be granted?
Why would the cluster become unstable?

**Comment by vania-pooh** [comment]
@topproto described all this stuff in docs: https://aerokube.com/selenoid/latest/#_selenoid_in_kubernetes
