### ISSUE TITLE
Video file name is not changing if CM is used

### ISSUE THREAD

**Issue by koushikmohan1996** [aerokube/selenoid#858]
I am trying to start selenoid using CM. with following configuration

```
docker run --rm                                   \
    -v /var/run/docker.sock:/var/run/docker.sock    \
    -v `pwd`/output/video/:/opt/selenoid/video/            \
    aerokube/cm:latest selenoid start    -c `pwd`/  \
    -e OVERRIDE_VIDEO_OUTPUT_DIR=`pwd`/output/video/       \
    -g "-video-output-dir /opt/selenoid/video" \
    --vnc --tmpfs 128 --args "-limit 10"
```

Now the file is available in `/output/video` but it is not renaming the file name.

Note: If I did not configure `OVERRIDE_VIDEO_OUTPUT_DIR`, the file is available in `/video` and file name is changing correctly. But I need the video file to be in the output folder.

Any help would be appreciated. Thanks :)

**Comment by vania-pooh** [comment]
@koushikmohan1996 You are overcomplicating things. First of all we recommend to use CM as a binary just because thus you get simpler commands. With CM you are intended to use `--config-dir` flag only. E.g. you set this flag as follows:
```
$ ./cm selenoid start --vnc --tmpfs 128 --args "-limit 10" --config-dir /some/dir
```
In that case video output dir as well as configuration files will be located in `/some/dir`.

**Comment by koushikmohan1996** [comment]
@vania-pooh Initially I tried to use selenoid using docker directly
```
docker run -d
--name selenoid                                 \
-p 4444:4444                                    \
-v /var/run/docker.sock:/var/run/docker.sock    \
-v `pwd`/config/:/etc/selenoid/:ro              \
-v `pwd`/video/:/opt/selenoid/video/            \
-e OVERRIDE_VIDEO_OUTPUT_DIR=`pwd`/video/       \
aerokube/selenoid:latest-release
```

But for this to work I need to pull browser image and video-recorder manually. That is why I used cm. 
If the output directory cannot be configured by cm I will switch back to the old method.

**Comment by vania-pooh** [comment]
@koushikmohan1996 only configuration directory (directory with browsers.json, logs and video at the same time, e.g. `~/.aerokube/selenoid` by default) can be easily configured.

**Comment by koushikmohan1996** [comment]
Got it, thanks for the help. I'll will close the issue
