### ISSUE TITLE
Tests fails when running more containers in parallel

### ISSUE THREAD

**Issue by success-stha** [aerokube/selenoid#862]
We are currently using a machine with 16 GB of RAM and 16 cores CPU. When container limit is set to 18 the tests runs fine but when increased to 27 the tests fail. The screenshot shows the tests failing with a loading icon. Here is the browser.json.
```
{
    "chrome": {
        "default": "78.0",
        "versions": {
            "78.0": {
                "image": "selenoid/vnc:chrome_78.0",
                "port": "4444",
                "volumes": ["/opt/docker/fileDownloadLocation:/home/selenium/Downloads"],
                "shmSize" : 1073741824,
                "tmpfs": {"/tmp": "size=768m"}
            }
        }
    }
}
```

**Comment by vania-pooh** [comment]
@success-stha according to our [docs](https://aerokube.com/selenoid/latest/#_recommended_docker_settings) we recommend to have no more than 1.5-2 browsers per CPU core. However sometimes only 1 CPU per browser works correctly. With 16 CPUs and 27 parallel sessions you have `27 / 16 = 1.69` browsers per core which seems to be a reasonable ratio. If you tested application has a lot of Javascript - then you could be running out of memory or CPU is getting overloaded by Javascript processing. So take a look at system metrics such as `load average`, `memory consumption` and `iowait` of the host machine to understand the reason.

**Comment by success-stha** [comment]
```
[  ~]# uptime
 02:42:31 up 11 days, 19:33,  2 users,  load average: 1.40, 1.63, 1.09
[  ~]# uptime
 02:42:33 up 11 days, 19:33,  2 users,  load average: 1.40, 1.63, 1.09
[  ~]# uptime
 02:42:35 up 11 days, 19:33,  2 users,  load average: 1.37, 1.62, 1.09
[  ~]# uptime
 02:42:36 up 11 days, 19:33,  2 users,  load average: 1.37, 1.62, 1.09
[  ~]# uptime
 02:42:37 up 11 days, 19:33,  2 users,  load average: 1.37, 1.62, 1.09
[  ~]# uptime
 02:45:22 up 11 days, 19:35,  2 users,  load average: 2.86, 2.21, 1.41
[  ~]# uptime
 02:45:23 up 11 days, 19:35,  2 users,  load average: 2.86, 2.21, 1.41
[  ~]# uptime
 02:45:24 up 11 days, 19:35,  2 users,  load average: 2.71, 2.19, 1.41
[  ~]# uptime
 02:45:24 up 11 days, 19:36,  2 users,  load average: 2.71, 2.19, 1.41
[  ~]# uptime
 02:45:25 up 11 days, 19:36,  2 users,  load average: 2.71, 2.19, 1.41
```

Here's the load average. The memory consumption is also fine. The tests fail right after the setup which takes a lot of time to complete (around 10 mins).

**Comment by vania-pooh** [comment]
@success-stha check that you have recommended Docker settings. https://aerokube.com/selenoid/latest/#_recommended_docker_settings

**Comment by success-stha** [comment]
I used the recommended settings. But i was unable to change docker0 mac-address as eth0 was not showing. I guess this might be the problem. There's one named ens192. I have used its mac-address for now but the problem still exists, Also if i reduce containers to 13 all tests passes.

```
ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.48.23.154  netmask 255.255.255.0  broadcast 10.48.23.255
        ether 00:50:56:bd:de:ff  txqueuelen 1000  (Ethernet)
        RX packets 14399286  bytes 7689433723 (7.1 GiB)
        RX errors 0  dropped 1861  overruns 0  frame 0
        TX packets 2127460  bytes 301368239 (287.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


```

**Comment by vania-pooh** [comment]
@success-stha what is your Docker storage driver? Do you have `overlay2`.

**Comment by success-stha** [comment]
> @success-stha what is your Docker storage driver? Do you have `overlay2`?

yes

**Comment by success-stha** [comment]
Any updates?

**Comment by success-stha** [comment]
The app we are testing is made using Angular. I have already shared all the info about cpu and memory consumption above. I am really struggling to run more than 16 containers in parallel. Any help from you would be highly appreciated.

**Comment by vania-pooh** [comment]
@aandryashin any ideas?

**Comment by aandryashin** [comment]
What are errors in tests? Could you please try to run synthetic tests in 16
parallel sessions?

пн, 17 февр. 2020 г., 14:43 Ivan Krutov <notifications@github.com>:

**Comment by success-stha** [comment]
What do you mean by synthetic tests? The screenshots shows the test failing with a loading icon. The log shows null pointer exception.

**Comment by aandryashin** [comment]
Please provide us with exact error you are receiving? I cannot see any null
pointer error...

вт, 18 февр. 2020 г., 16:23 success-stha <notifications@github.com>:

**Comment by success-stha** [comment]
Since the page keeps on loading for unknown reason, No such element exception is shown.
```
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.xpath: //*[contains(@class,'nodata ng-star-inserted')]
build	19-Feb-2020 04:11:34	For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
build	19-Feb-2020 04:11:34	Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
build	19-Feb-2020 04:11:34	System info: host: 'nvbmblinp6', ip: '10.48.23.150', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-754.11.1.el6.x86_64', java.version: '1.8.0_131'
build	19-Feb-2020 04:11:34	Driver info: driver.version: unknown
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
build	19-Feb-2020 04:11:34		at java.util.Optional.orElseThrow(Optional.java:290)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1427)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1421)
build	19-Feb-2020 04:11:34		at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
build	19-Feb-2020 04:11:34		... 19 common frames omitted
```
The same tests passes when the number of container is reduced.

**Comment by vania-pooh** [comment]
@success-stha could be because of overloaded tested application server then.
