### ISSUE TITLE
Creating browsers only if enough memory and cpu available

### ISSUE THREAD

**Issue by ismailazerty** [aerokube/selenoid#863]
It would be nice if selenoid wait for cpu and memory before creating a docker container, it would prevent the crash of tests.
we can for example add a threshold for cpu and another one for memory. for example 75% of cpu and memory. if it's above that, selenoid will keep the session in the queue until the system is relaxed.

**Comment by vania-pooh** [comment]
@ismailazerty getting CPU and memory consumption is platform-specific operation. Selenoid already has the following flags:
```
-cpu value
    Containers cpu limit as float e.g. 0.2 or 1.0

-mem value
    Containers memory limit e.g. 128m or 1g
```
This allows to limit CPU and memory consumption per container.

**Comment by ismailazerty** [comment]
what happen if those limits are reached ? the container will crash ? the browser will crash ?

**Comment by vania-pooh** [comment]
@ismailazerty if memory limit is reached then respective process will be killed by OOM killer. All applied memory and CPU limits are available via `docker inspect` and Docker API.

**Comment by ismailazerty** [comment]
why not using docker stats  to calculate used memory and cpu for all containers, before creating the docker container, it would provide selenoid the information needed to know if the system is full or not. And keep the sessions in the queue until the memory and cpu is below the configured limit.

**Comment by vania-pooh** [comment]
@ismailazerty because Docker stats does not consider any system processes that could be running outside of Docker. This is systems administrator responsibility to control all this stuff.

**Comment by ismailazerty** [comment]
100 percent true, but usually we have dedicated machines for selenoid.
You can give the administrator the possibility to choose between two modes: first one is giving  selenoid the possibility to create containers based on available ressources. The second mode, and it's the actual working mode: it's up to the administrator to configure that.
this will certainly give selenoid more elasticity and make it more robust to failing tests due to unavailable ressources.

**Comment by vania-pooh** [comment]
@ismailazerty here the problem is that Selenoid has a static queue size (Golang channel with fixed length) configured on startup and it is complicated to configure this dynamically.

**Comment by ismailazerty** [comment]
The number of browsers will remain static at startup, with a value large enough, slightly superior to the actual capacity of the physical machine (configured by the administrator).
The idea is just to not create new containers if no memory or cpu is available for a period of time.
Some tests needs more ressources than others and we cannot predict or foresee that, and developpement of tests are always subject to modifications. So finding a perfect setting is very time consumming and not always stable over time.

**Comment by vania-pooh** [comment]
@ismailazerty will investigate whether this is somehow supported in Docker API.

**Comment by HarryFree** [comment]
@vania-pooh what is the default cpu and mem value consumed for containers?

```
-cpu value
    Containers cpu limit as float e.g. 0.2 or 1.0

-mem value
    Containers memory limit e.g. 128m or 1g
```

**Comment by vania-pooh** [comment]
@HarryFree by default there is no limitation.
