### ISSUE TITLE
Accessing a jetty website launched from selenoid

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/selenoid#864]
Hello,

I currently have a test class which consists of:

1. Code that starts up a Jetty server on port 8080, that hosts a index.html file
2. A unit test that launches this website and attempts to interact with it

From my understanding, the Jetty server will start up in, and serve the `index.html` in the host container and not in the browser container, and as such I won't be able to do a `driver.get("http://localhost:8080/index.html")`.

Using the below snippet I am able to retrieve the IP address of the server hosting Jetty:

```
String addr = InetAddress.getLocalHost().toString().split("/")[1]; 
// this will return a 10.172.46.70 IP address
```
However, when the unit tests executes a `driver.get("http:// + addr + ":8080/index.html");` , via VNC, I noticed that the browser is not able to properly resolve the website, instead showing the 'spinning' icon on the top left corner of the browser window until it eventually times out.

I am able to access the website successfully from my own browser.

Is there a configuration that I am missing out? 
Thanks!

**Comment by vania-pooh** [comment]
@timothyjmtan every Docker container has its own `localhost` - you have to use host machine IP address in order to make it work.

**Comment by timothyjmtan** [comment]
hi @vania-pooh, when you mentioned host machine, do you mean:
- the linux machine hosting Docker, or
- the the host container (i.e. the aerokube/selenoid container)?

Also to elaborate further, using the code I mentioned above, I am getting the following output:
Docker Container IP: 172.17.0.8
Host Container IP: 10.82.235.187

The docker container is not able to access `http://10.85.234.189:8080/index.html`, but I am able to do so from my own personal laptop.

Could it be some a docker config for the network interface that I'm missing? Thanks for the advice as I'm still learning about how docker networks function.

**Comment by vania-pooh** [comment]
@timothyjmtan I mean Linux machine hosting Docker.
