### ISSUE TITLE
Issue connecting to WebDriver

### ISSUE THREAD

**Issue by LordPato** [aerokube/selenoid#868]
I'm using the default selenoid installation (just changed the default browser) by https://aerokube.com/cm/latest/

./cm selenoid start --vnc --port 80 --args "-limit=5 -session-attempt-timeout 2m -service-startup-timeout 2m"

curl -s http://localhost/status
{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"79.0":{}}}}

and when trying to actually use it I'm getting the following error :

Using selenoid
WebDriverError: wait: http://172.17.0.6:80/ does not respond in 2m0s

I can't provide much additional information since it's the default installation

Any clues on what to look at?

**Comment by vania-pooh** [comment]
@LordPato take a look at Selenoid logs as well as started browser container logs using `docker logs` command.

**Comment by LordPato** [comment]
In Selenoid Logs I have the following (I'll use just one container as example)

2020/02/03 14:10:16 [79] [CONTAINER_STARTED] [selenoid/vnc_chrome:79.0] [3444061ef3276322983fb8db75cf1e733c5200b65cbb3f6651e10191f226aa2a] [1.07s]

In that container logs:
Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 4444
All remote connections are allowed. Use a whitelist instead!
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

And then in Selenoid logs (after 2 min)
2020/02/03 14:12:17 [79] [CONTAINER_REMOVED] [3444061ef3276322983fb8db75cf1e733c5200b65cbb3f6651e10191f226aa2a]
2020/02/03 14:12:17 [79] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.7:80/ does not respond in 2m0s]


For some reason Selenoid doesn't connect to the browser container after starting it.

**Comment by vania-pooh** [comment]
@LordPato in `browsers.json` you should have `port` equal to 4444 as this port is hard-coded to browser containers. You have port 80 so far as I can see.
