### ISSUE TITLE
Unable to launch browser when Selenoid is started in custom network

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid#87]
```
2017/05/18 12:12:23 [12] [SERVICE_STARTUP_FAILED] [unknown] [wait: http://172.17.0.2:4444/ does not respond in 30s]
```

**Comment by MissiaL** [comment]
How can this be fixed?
I'm using a ggr in a bundle in with several hubs and I'm getting this error (
Can there be a workaround?

**Comment by vgrigoruk** [comment]
Hope this helps, @MissiaL : http://aerokube.com/selenoid/latest/#_selenoid_with_docker_compose

**Comment by vania-pooh** [comment]
@MissiaL a workaround is to start Selenoid in network named `default`.

**Comment by MissiaL** [comment]
Thanks for the help. The problem was resolved after installation `selenoid latest` version

**Comment by vgrigoruk** [comment]
It is possible to specify a network name that container should join when it is launched. From a CLI it is done like this: `docker run --network=$network_name $image`. I believe the same can be easily done from a golang code. 
To make a solution simple, we can introduce a `--docker-network $your_network_name` selenoid flag and pass it to browser containers when they're being launched. 
This approach will allow docker-compose users to specify a custom network in docker-compose.yml and pass its name as an argument to selenoid.

@vania-pooh what do you think?

**Comment by vania-pooh** [comment]
@vgrigoruk seems to be simple.

**Comment by vania-pooh** [comment]
@vgrigoruk you can test this with `aerokube/selenoid:latest`.

**Comment by vgrigoruk** [comment]
Unfortunately, it doesn't work.
Docker network was created via the following command
```
docker network create --attachable=true --driver=bridge selenoid-test
```

Selenoid started with the following command:
```
docker run -d --name selenoid -p 4444:4444 -v $PWD/browsers.json:/etc/selenoid/browsers.json:ro -v /var/run/docker.sock:/var/run/docker.sock --network selenoid-test aerokube/selenoid:latest -container-network selenoid-test
```

Selenoid logs:
```
2017/07/31 08:00:27 [NEW_REQUEST]
2017/07/31 08:00:27 [NEW_REQUEST_ACCEPTED]
2017/07/31 08:00:27 [1] [LOCATING_SERVICE] [chrome-]
2017/07/31 08:00:27 Using default version: 59.0
2017/07/31 08:00:27 [1] [USING_DOCKER] [chrome-59.0]
2017/07/31 08:00:27 [1] [CREATING_CONTAINER] [selenoid/chrome:59.0]
2017/07/31 08:00:27 [1] [STARTING_CONTAINER] [selenoid/chrome:59.0] [e09274bad7118f6b28ec843777eab212425166038542e638a43e1da510f4ab4b]
2017/07/31 08:00:28 [1] [CONTAINER_STARTED] [selenoid/chrome:59.0] [e09274bad7118f6b28ec843777eab212425166038542e638a43e1da510f4ab4b] [494.068891ms]
2017/07/31 08:00:28 [1] [SERVICE_STARTED] [selenoid/chrome:59.0] [e09274bad7118f6b28ec843777eab212425166038542e638a43e1da510f4ab4b] [51.050657ms]
2017/07/31 08:00:28 [1] [PROXY_TO] [selenoid/chrome:59.0] [e09274bad7118f6b28ec843777eab212425166038542e638a43e1da510f4ab4b] [http://:4444/]
2017/07/31 08:00:28 [1] [SESSION_ATTEMPTED] [unknown] [http://:4444/] [1]
2017/07/31 08:00:28 [1] [SESSION_FAILED] [unknown] [Bad response from http://:4444/ - 404 Not Found]
2017/07/31 08:00:28 [1] [REMOVE_CONTAINER] [e09274bad7118f6b28ec843777eab212425166038542e638a43e1da510f4ab4b]
2017/07/31 08:00:28 [1] [CONTAINER_REMOVED] [e09274bad7118f6b28ec843777eab212425166038542e638a43e1da510f4ab4b]
```

Container is started, but seems like selenoid doesn't not detect IP address of a started container.

**Comment by vgrigoruk** [comment]
Also, could you please confirm that "NetworkMode" is a correct property for a docker daemon when launching a container (as for "docker run" the flag is called "--network").

**Comment by vania-pooh** [comment]
@vgrigoruk ok, let me test this again.

**Comment by vania-pooh** [comment]
@vgrigoruk applied one more fix. This time it should work. Please check.

**Comment by vgrigoruk** [comment]
@vania-pooh works like a charm, thank you!

**Comment by vania-pooh** [comment]
Closing then.

**Comment by seanmaxwell** [comment]
@vania-pooh Where should I put the `--network network-name` and `-container-network network-name` if I am using the binary to launch selenoid.

**Comment by vania-pooh** [comment]
@seanmaxwell like this:
```
./selenoid -container-netwrork my-network -conf /etc/selenoid/browsers.json ....
```

**Comment by mattiasmgn** [comment]
We are using Selenoid latest. Date is now november 2018. I have 5 selenoid installations on five different computers. On one of them, we see the exact same behaviour: 
2018/11/14 16:32:46 [0] [PROXY_TO] [ac3a247b511b3aaed97ad58962043f19fad90a4adbd85ac3f3144bb757e196e0] [http://:4444/]
2018/11/14 16:32:46 [0] [SESSION_ATTEMPTED] [http://:4444/] [1]
2018/11/14 16:32:46 [0] [SESSION_FAILED] [http://:4444/] [404 Not Found]

We have the same docker-compose file on all computers. 
Any idea why this is failing on only one of them? What can we have missed?

**Comment by vania-pooh** [comment]
@mattiasmgn what is your Docker API version on this failing machine?

**Comment by mattiasmgn** [comment]
$ sudo docker --version
Docker version 18.06.1-ce, build e68fc7a

sudo docker images
EPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
aerokube/selenoid         latest              deee2b640c49        6 months ago        11.1MB

**Comment by mattiasmgn** [comment]
I can also see this when I do a docker run of an image. 
Your Docker API version is 1.38

**Comment by vania-pooh** [comment]
@mattiasmgn yes, because if you do `docker version` you will see the same stuff.

**Comment by mattiasmgn** [comment]
Update: I deleted all docker images on the computer and pulled them again. Now it works. Maybe some of them were out of date or something. I'm not sure, but everything is working now.

**Comment by vania-pooh** [comment]
@mattiasmgn so far as I can see you had 6 months old `aerokube/selenoid:latest`.
