### ISSUE TITLE
'download.prompt_for_download: false' chrome preference doesn't work with Selenoid in Protractor

### ISSUE THREAD

**Issue by viktorgogulenko** [aerokube/selenoid#872]
We just found that by some reason 'download.prompt_for_download: false' preference is working fine on local browser instance in Protractor, but doesn't work on Selenoid (chrome version 79.0). Our chrome settings in Protractor:
`capabilities: {
  shardTestFiles: shardTestFilesCapability,
  maxInstances: 3,
  sequential: false,
  browserName: 'chrome',
  enableVNC: true,
  enableVideo: true,
  chromeOptions: {
    prefs: {
      download: {
        prompt_for_download: false,
        directory_upgrade: true,
        default_directory: downloadsPath
      },
      profile: {
        default_content_settings: {
          popups: 0
        },
        default_content_setting_values: {
          automatic_downloads: 1
        }
      },
      safebrowsing: {
        enabled: false
      },
      plugins: {
        plugins_disabled: false
      }
    }
  }
}`

<img width="951" alt="Screenshot 2020-02-11 at 14 39 05" src="https://user-images.githubusercontent.com/12098350/74241427-4f967d00-4cdc-11ea-8fd4-6ba72828b044.png">

While test run on local browser this download popup is not appearing and test is not failing.
Our local chrome version is: 79.0.3945.130 (Official Build) (64-bit)

This issue is blocking us to run our tests on Selenoid and we will really appreciate for any help from your side. Thanks!

**Comment by vania-pooh** [comment]
@viktorgogulenko could be because ChromeOptions key is now `goog:chromeOptions` so far as I know.

**Comment by viktorgogulenko** [comment]
Thanks @vania-pooh We just updated protractor.conf.js with:
```
capabilities: {
  shardTestFiles: shardTestFilesCapability,
  maxInstances: 3,
  sequential: false,
  browserName: 'chrome',
  enableVNC: true,
  enableVideo: true,
  'goog:chromeOptions': {
    prefs: {
      download: {
        prompt_for_download: false,
        directory_upgrade: true,
        default_directory: downloadsPath
      },
      profile: {
        default_content_settings: {
          popups: 0
        },
        default_content_setting_values: {
          automatic_downloads: 1
        }
      },
      safebrowsing: {
        enabled: false
      },
      plugins: {
        plugins_disabled: false
      }
    }
  }
}
```
and we were expecting that it will resolve an issue, but unfortunately it sill works fine locally and as soon as we are switching to Selenoid - again popup with download action appearing on page and tests are failing :(

**Comment by vania-pooh** [comment]
@viktorgogulenko take a look at the following docs: https://aerokube.com/selenoid/latest/#_downloading_files_in_different_browsers These Java examples could be easily converted to Protractor.

**Comment by viktorgogulenko** [comment]
@vania-pooh 
Let me explain little bit what we want to do:
1. We have a test which is clicking on button on webpage to download Excel report;
2. We have a function which is reading a downloaded file in specific folder:
```
async getDownloadedXlsx(neededCell, expectedValue) {
    const files = await fs.readdir(downloadsFolder);
    const workbook = await xlsx.readFile(`${downloadsFolder}/${files[0]}`);
    const firstSheetName = workbook.SheetNames[0];
    const addressOfCell = neededCell;
    const worksheet = workbook.Sheets[firstSheetName];
    const desiredCell = worksheet[addressOfCell];
    const desiredValue = (desiredCell ? desiredCell.v : undefined);
    expect(desiredValue).toEqual(expectedValue);
  },
```
3. We have a protractor.conf.js file with such Chrome capabilities:
```
capabilities: {
    shardTestFiles: shardTestFilesCapability,
    maxInstances: 3,
    sequential: false,
    browserName: 'chrome',
    enableVNC: true,
    enableVideo: true,
    'goog:chromeOptions': {
      prefs: {
        download: {
          prompt_for_download: false,
          directory_upgrade: true,
          default_directory: `${process.cwd()}/downloads`
        }
      }
    }
  },
```
Is it correct that 'default_directory' folder should be existent on both sides - locally and in Selenoid container? Or Protractor should be able to receive a file from remote Selenoid instance and download it in provided folder? Or Selenoid saves it somewhere in container and we need to get this file from Selenoid container using API call?
Capabilities provided above are valid for local browser. We also tried absolute path - it also works fine for local, but not for Selenoid. Seems we are stuck with this issue. Can't find any examples how guys configured Protractor to download files from Selenoid.

**Comment by viktorgogulenko** [comment]
Ah, as soon as we used path which is available on Selenoid as well (/var/tmp) we are seeing that popup in appearing and file was downloaded from UI perspective. So am I right that we need to download it from Selenoid container to local machine using API call like it mentioned in https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser? Thanks in advance for any help!

**Comment by viktorgogulenko** [comment]
@vania-pooh please close this issue - we found a way how to download a file to local machine from Selenoid container in protractor.

**Comment by vania-pooh** [comment]
Great!

**Comment by nizzel55** [comment]
@viktorgogulenko Care to enlighten us how you solved it?
