### ISSUE TITLE
Changing default port of selenoid-ui to different port

### ISSUE THREAD

**Issue by ratankumarangadi** [aerokube/selenoid#876]
I'm unable to change selenoid-UI port from 8080, it works well with 8080. Below is part of selenoid-ui configuration in docker-compose.yml file.

selenoid-ui:
     image: "aerokube/selenoid-ui"
     network_mode: bridge
     links:
       - selenoid
     ports:
       - "8080:8080"
     command: ["--selenoid-uri", "http://selenoid:4444"]

Is there any way to run it on port other than 8080?

**Comment by vania-pooh** [comment]
@ratankumarangadi just specify a desired port in `ports` section:
```
ports:
- "8081:8080"
```

**Comment by ratankumarangadi** [comment]
@vania-pooh Thank you very much, not sure why it didn't work when I tried it before. Now it started on 8181.
