### ISSUE TITLE
Unable to start selenoid with safari browser

### ISSUE THREAD

**Issue by ratankumarangadi** [aerokube/selenoid#878]
I'm trying to start selenoid docker with safari browser, when I run docker-compose up -d having 

{
    "safari": {
        "default": "latest",
        "versions": {
            "latest": {
                    "image": ["/usr/bin/safaridriver"]
            }
        }
    }
} 

in browsers.json file and then try to open manual session to verify if browser is present. It doesn't open the browser and I checked logs which shows,

2020/03/04 13:03:12 [7] [STARTING_PROCESS] [[/usr/bin/safaridriver --port=42995]]
2020/03/04 13:03:12 [7] [SERVICE_STARTUP_FAILED] [cannot start process [/usr/bin/safaridriver --port=42995]: fork/exec /usr/bin/safaridriver: no such file or directory]

I have added safaridriver in /usr/bin in my host. Is there any thing more to be done to get safari started?

Thanks in advance.

**Comment by vania-pooh** [comment]
@ratankumarangadi Selenoid in that case should be running as a process and not as Docker container.

**Comment by ratankumarangadi** [comment]
@vania-pooh oh okay , so is there no way to make Safari this way? instead of running VM inside container? Sorry I read about the solution of running a VM inside container for Mac and Windows if I am not wrong

**Comment by aandryashin** [comment]
There are no public available images for MacOS and Windows.

ср, 4 мар. 2020 г., 22:07 ratankumarangadi <notifications@github.com>:

**Comment by vania-pooh** [comment]
@ratankumarangadi yes, you are right. Such approach will work but anyway you need to build such images yourself using these instructions: https://github.com/aerokube/windows-images

**Comment by ratankumarangadi** [comment]
Just to follow up , should this work ? https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium#docker Microsoft has pre-built image with microsoft Chromium which is latest edge browser

**Comment by vania-pooh** [comment]
@ratankumarangadi yes, it should.
