### ISSUE TITLE
Start proxy server in Selenoid container

### ISSUE THREAD

**Issue by asolntsev** [aerokube/selenoid#879]
People often want to use proxy server like [BrowserUp](https://github.com/browserup/browserup-proxy)  (former BrowserMobProxy) to intercept requests/responses between browser and server. 

When browser is run inside Selenoid container, the proxy should be also run inside the same container.
I suggest to add BrowserUp proxy to Selenoid containers with Chrome, Firefox and other browsers.

From my tests, I will be able to manage this proxy using its [Rest API](https://github.com/browserup/browserup-proxy#interceptorsRESTapiLP).

**Comment by vania-pooh** [comment]
@asolntsev makes no sense. You can now intercept any HTTP request without proxy using Chrome Devtools Protocol as shown here: https://github.com/aerokube/chrome-developer-tools-protocol-java-example/blob/master/src/test/java/com/aerokube/selenoid/ChromeDevtoolsTest.java#L171-L192

**Comment by asolntsev** [comment]
@vania-pooh 
1. Well, CDP is great, but it only works in Chrome. What about other browsers?
2. It seems to be too complex for most users. I was thinking that it would be great to have such proxy out-of-the-box.

**Comment by asolntsev** [comment]
@vania-pooh I studied CDP a little bit and found that it _doesn't allow to get content_ of the downloaded file. Reading [Selenoid tutorial](https://github.com/aerokube/selenoid/blob/master/docs/file-download.adoc) I see that downloading file is not trivial at all. 

Still, what about the proxy? I can implement a PR, just need to know your opinion.

**Comment by vania-pooh** [comment]
@asolntsev we don't want to overcomplicate things here. Probably could just document how to use a separate proxy container with Selenoid and so it would be simple to use option 2).

**Comment by asolntsev** [comment]
@vania-pooh Running a separate container with proxy server seems to be overcomplicated solution for me. For end user, it's much more simple just to have one container with browser and proxy.

**Comment by aandryashin** [comment]
Usually browser mob is running on test side. I do not see any reason to
pack it within browser container.

вс, 3 мая 2020 г., 19:05 Andrei Solntsev <notifications@github.com>:

**Comment by asolntsev** [comment]
@aandryashin Yes, we also run BrowserUpProxy on test side. The problem is that browser inside container doesn't have access to this proxy (by default). Is there a really easy way to make it accessible?

**Comment by aandryashin** [comment]
Why proxy is not accessible from browser? By default container can access
any external resources. May be you run tests within containers? In that
case you have to start test containers in the same network.

пн, 4 мая 2020 г., 11:11 Andrei Solntsev <notifications@github.com>:

**Comment by asolntsev** [comment]
@aandryashin It's quite often used schema: developer run tests on his machine, while Selenoid container is run on remote server. This server cannot always have access to the developer's machine.

**Comment by aandryashin** [comment]
In that case selenoid can be run locally to. Another way is ssh forwarding
to its local machine. Btw if you wish you can build such image by yourself.
We do not want to pack java to our images.

вт, 2 июн. 2020 г., 00:22 Andrei Solntsev <notifications@github.com>:

**Comment by asolntsev** [comment]
Well, I understand that you don't want to pack Java. But what if we use
another proxy written in Go? Something like
https://github.com/elazarl/goproxy

вт, 2 июн. 2020 г., 20:55 Alexander Andryashin <notifications@github.com>:

**Comment by Kremliovskyi** [comment]
Are there any docs on how to use BrowserUp, BrowserMobProxy with Selenoid ? Whenever I set proxy capability for chrome driver the browser in Selenoid container does not have access to internet. The workaround is to set 'host.docker.internal' for selenium http proxy but it works only for docker for windows and not for docker on linux. 
I use BrowserUp embedded in tests and Selenoid on local machine , same as in Jenkins on linux - both proxy and Selenoid on the same machine.

**Comment by vania-pooh** [comment]
@Kremliovskyi  https://github.com/aerokube/selenoid-container-tests/blob/master/src/test/java/com/aerokube/selenoid/TestProxy.java
