### ISSUE TITLE
Can Selenoid running in AWS EC2 instance for windows instead of using ECS?

### ISSUE THREAD

**Issue by LiPhynd** [aerokube/selenoid#883]
I have two EC2 instances going to setup configure Selenoid1 and Selenoid2 for automation testing. Currently, I am facing the issue to start Selenoid without "Switch to Linux containers.." from Docker. 
Since EC2 is already a virtual machine.  no sure we can set up nested virtualization to get Hyper-V working...
I just want to confirm  Selenoid can be running EC2 instance? if Yes, how to fix below Selenoid image download issue without using Switch to Linux containers...
I do not have any issue with running Selenoid in my laptop

![image](https://user-images.githubusercontent.com/45089149/76797945-fe7b1c80-67a4-11ea-9443-fed5e76c63a7.png)

**Comment by vania-pooh** [comment]
@LiPhynd 
1) Selenoid should always be started in Linux mode. This is an expected behavior. All images are made for Linux.
2) In AWS only *.metal instances support nested virtualization.

**Comment by LiPhynd** [comment]
Thanks @vania-pooh
