### ISSUE TITLE
How to read a downloaded PDF file's content?

### ISSUE THREAD

**Issue by akcasoy** [aerokube/selenoid#884]
I have been trying to read the content of a pdf file. Here is the docu: https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser

In my case, this is a pdf file instead of txt. And I try to read this file's content and write it to a local pdf file with fs.writeFileSync like this:

`fs.writeFileSync('x.pdf', result);`

Does this get API support Accept headers? So i can set in my RequestOptions ('Accept', 'application/pdf') and i get the result. And without this, i think this API gives me the HTML content when i call like this:

http://selenoid-host.example.com:4444/download/f2bcd32b-d932-4cdc-a639-687ab8e4f840/myfile.pdf

Or is there another way to download this file locally, then i can read it with fs and check the content?

**Comment by vania-pooh** [comment]
@akcasoy could you print respective HTTP request and response headers so we could better diagnose? An HTTP server we are using to serve the files (standard Golang file server) is determining MIME type by file extension by reading `/etc/mime.types` file. I checked our browser images for PDF in this file we have:
```
application/pdf					pdf
```

**Comment by akcasoy** [comment]
ok i have achieved it in another way.. nothing to do with selenoid. Thanks though.

For others who may interest in the same problem, this link helped me a lot with "request-promise-native" library:

https://stackoverflow.com/questions/25945714/how-to-download-pdf-file-from-url-in-node-js

**Comment by NahrebetskyiPavel** [comment]
C#
https://stackoverflow.com/a/67078493/14037732
