### ISSUE TITLE
Selenoid doesn't save session logs

### ISSUE THREAD

**Issue by Ray-Barker** [aerokube/selenoid#885]
When I run tests, in UI I can see logs fine, but Selenoid doesn't save them to files.
Selenoid is deployed in Docker swarm, part of the compose file with volumes and command arguments:

> volumes:
>       - "/var/run/docker.sock:/var/run/docker.sock"
>       - "/etc/selenoid/config/:/etc/selenoid/"
>       - "/etc/selenoid/video/:/opt/selenoid/video/"
>       - "/etc/selenoid/logs/:/opt/selenoid/logs/"
>     environment:
>       - OVERRIDE_VIDEO_OUTPUT_DIR=/selenoid/video
>     command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "6", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
> 

Is there anything I've missed?

**Comment by vania-pooh** [comment]
@Ray-Barker either add `-save-all-logs` flag to always save log files (available from release 1.9.0) or use `enableLogs` capability to save log files for any desired sessions.

**Comment by Ray-Barker** [comment]
Great, thanks a lot, that helped!
