### ISSUE TITLE
Prometheus metrics endpoint

### ISSUE THREAD

**Issue by cweagans** [aerokube/selenoid#889]
I'd be really interested in wiring up Selenoid to my existing Prometheus monitoring. Aside from just normal Go instrumentation, it'd be interesting to collect some statistics on number of page loads, etc. that are triggered by clients.

**Comment by vania-pooh** [comment]
@cweagans it is rather easy to add basic metrics like number of sessions, number of used slots and so as they are already present in Selenoid memory. Regarding number of page loads - it more complicated as Selenoid is just a reverse proxy to Docker container and all the magic happens inside container.

**Comment by cweagans** [comment]
Makes sense. If it's too complicated, even the basics would be helpful. Maybe one could "MITM" the connection and do some counting in Selenoid, but maybe that's too much work.

**Comment by eacevedo79** [comment]
i put a basic metrics pr a while back, may be a start https://github.com/aerokube/selenoid/pull/794
