### ISSUE TITLE
How to mark the test result pass or fail

### ISSUE THREAD

**Issue by megolee** [aerokube/selenoid#891]
Is there a way to mark the test result and check it in the ui?

**Comment by vania-pooh** [comment]
@megolee Selenoid is just a Selenium API and does not know whether your test is passing or failing. Marking tests as passed or failed is test framework responsibility.

**Comment by megolee** [comment]
@vania-pooh Thanks for your reply. I know that it's the test framework responsibility to mark the tests result. Can we pass the result to Selenoid and make us easy to tell the test result in Selenoid UI. 

Sometimes we need to search test in Selenoid to confirm what's the script do. Now they does'n have status, and we don't know which one is the correct.

**Comment by vania-pooh** [comment]
@megolee the only feature Selenoid provides is `name` capability. This allows to mark any browser session being executed with custom label (e.g. test case name). https://aerokube.com/selenoid/latest/#_custom_test_name_name
