### ISSUE TITLE
General Slowness running tests

### ISSUE THREAD

**Issue by LordPato** [aerokube/selenoid#899]
Sorry but I don't know where else to ask this.

Running a protractor test locally, it runs perfect, no issues regarding timeouts or slowness.

Running it using Selenoid, it takes huge amount of time to even type text in a textbox.
It looks something related to timing. I enter to the browser container using the UI and VNC, and it looks like its waiting for something before going to the next action (but the elements are all there).
I interacted with the browser, and it's not a browser or container slowness, since I could browser with the page without any issues or delays.

Already checked CPU usage and it's below 5%, also memory usage is fine.

Any ideas on where I can look at to start debugging this?

**Comment by vania-pooh** [comment]
@LordPato check that you have recommended Docker settings first. https://aerokube.com/selenoid/latest/#_recommended_docker_settings Also in case of Mac \ Windows check that Docker VM has sufficient resources (CPU and RAM) in Docker settings.

**Comment by tyama0007** [comment]
Hello!
I have the same problem with slow execution. Locally, it works quickly, and when you run tests in Selenoid, the commands run with a delay.
This slowness appeared after the transition from Selenium 3.141.0 to Selenium 4.0.0-alpha05. Slowness was also noticed on other versions of selenium4. What could be the reason, or how can this be debugged?

**Comment by vania-pooh** [comment]
@tyama0007 possible issue in Selenium Java https://github.com/SeleniumHQ/selenium/issues/8159

**Comment by LordPato** [comment]
Fixed. Needed to fix Docker MAC Address as the physical one.

**Comment by pgonzTest** [comment]
Im having the same problem but with moon v1, does someone have the same issue with moon v1 ?

**Comment by vania-pooh** [comment]
@pgonzTest Moon issues are here: https://github.com/aerokube/moon/issues
