### ISSUE TITLE
ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.

### ISSUE THREAD

**Issue by LordPato** [aerokube/selenoid#905]
By running tests I saw that some of them failed giving
"WebDriverError: Session timed out or not found"
And the browser was in fact, no longer open.

Then I tested them by doing a "docker logs -f" on the browser container to see in which exact
place it failed and I saw the following message the exact moment before it dies:

ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.

Any clues on how to fix it?

I'm using selenoid/vnc_chrome:79.0 in this case.

Thanks!

**Comment by vania-pooh** [comment]
@LordPato not sure about it. Seems to be some Chrome-specific issue.

**Comment by LordPato** [comment]
I tried with version 81.0
Now it shows the following :

[1588100199.174][INFO]: [c40103de17e76a21a3cae0f1ad13d76e] COMMAND Quit {
}
[1588100199.280][INFO]: [c40103de17e76a21a3cae0f1ad13d76e] RESPONSE Quit
