### ISSUE TITLE
requesting help in vnc image for latest browser tags

### ISSUE THREAD

**Issue by vasumadhu** [aerokube/selenoid#910]
Hi Team,
Firstly, thank you so much for the great work on this cool container based selenium environment. This really ease the pain with selenium setup. 

I am struck from running the test against latest browsers. is there a vnc version available for latest chrome/Firefox browsers ? I do see selenoid/vnc images for tags chrome_80.0, etc. but could not see an image for vnc_latest ? 

I am assuming, we need a corresponding version of the selenoid/vnc browser image for the tests to run. Please correct me if I am wrong.

I am trying to start a test with following capabilities:

firefox_capabilities: {
  "browserName": "firefox",
  "version": "latest",
  "enableVNC": True,
  "enableVideo": False,
  "acceptSslCerts": True
}

chrome_capabilities: {
  "browserName": "chrome",
  "version": "latest",
  "enableVNC": True,
  "enableVideo": False
}

Even though I pulled the image for selenoid/chrome:latest, I am seeing below error:

selenium.common.exceptions.WebDriverException: Message: Requested environment is not available

Please help if I am missing something ?

Thanks!

**Comment by vania-pooh** [comment]
@vasumadhu we do not build `latest` tag for VNC images. This error means Selenoid is no aware of browser version you are requesting. Any version should be added to `browsers.json` file.

**Comment by vasumadhu** [comment]
Thanks @vania-pooh for the quick response. 
So, does this mean I would not be able to use the capabilities like the one mentioned below and instead do I need to mention the browser version explicitly ?

chrome_capabilities: {
"browserName": "chrome",
"version": "latest",
"enableVNC": True,
"enableVideo": False
}

**Comment by vasumadhu** [comment]
Update: (Chrome succeeded but Firefox failed)

I was able to successfully run the test for chrome latest image with the following details specified in my browsers.json:

"chrome": {
		"default": "latest",
		"versions": {
			"latest": {
				"image": "selenoid/chrome",
				"port": "4444",
				"tmpfs": {"/tmp":"size=512m"}
			}
		}
	}

However if I tried to use the same method for firefox, I am running into the following error:

2020/05/06 07:41:46 [-] [NEW_REQUEST] [unknown] [x.x.x.x]
2020/05/06 07:41:46 [-] [NEW_REQUEST_ACCEPTED] [unknown] [x.x.x.x]
2020/05/06 07:41:46 [335] [LOCATING_SERVICE] [firefox] [latest]
2020/05/06 07:41:46 [335] [USING_DOCKER] [firefox] [latest]
2020/05/06 07:41:46 [335] [CREATING_CONTAINER] [selenoid/firefox]
2020/05/06 07:41:46 [335] [STARTING_CONTAINER] [selenoid/firefox] [******c**9**57db]
2020/05/06 07:41:47 [335] [CONTAINER_STARTED] [selenoid/firefox] [******c**9**57db] [0.63s]
2020/05/06 07:41:47 [335] [SERVICE_STARTED] [selenoid/firefox] [******c**9**57db] [0.30s]
2020/05/06 07:41:47 [335] [PROXY_TO] [******c**9**57db] [http://172.17.0.6:4444/wd/hub]
2020/05/06 07:41:47 [335] [SESSION_ATTEMPTED] [http://172.17.0.6:4444/wd/hub] [1]
2020/05/06 07:41:47 [335] [SESSION_FAILED] [http://172.17.0.6:4444/wd/hub] [400 Bad Request]
2020/05/06 07:41:47 [335] [REMOVING_CONTAINER] [******c**9**57db]
2020/05/06 07:41:47 [335] [CONTAINER_REMOVED] [******c**9**57db]

I used the following details for firefox in my browsers.json file:

"firefox": {
		"default": "latest",
		"versions": {
			"latest": {
				"image": "selenoid/firefox",
				"port": "4444",
				"path": "/wd/hub",
				"tmpfs": {"/tmp":"size=512m"}
			}
		}
	}

Note: I am not making use of ding model and instead have given access to the host docker.sock of selenoid. So that selenoid creates parallel containers of chrome & firefox instead of child containers.

**Comment by aandryashin** [comment]
Please use numeric versions. Gecko driver does not allow latest as version
number.

ср, 6 мая 2020 г., 11:11 Vasu Madhu <notifications@github.com>:

**Comment by vasumadhu** [comment]
@aandryashin, Thanks for the confirmation. Is there any workaround that can help selenoid understand to pull the last numeric version of Firefox browser image from the hub when we specify latest as the version number ?

**Comment by vania-pooh** [comment]
@vasumadhu currently for latest versions you can use e.g. `selenoid/firefox:latest`. They are the same as VNC.

**Comment by vasumadhu** [comment]
@vania-pooh , Are you referring to the below config values in browsers.json for firefox:latest ?

"firefox": {
"default": "latest",
"versions": {
"latest": {
"image": "selenoid/firefox:latest",
"port": "4444",
"path": "/wd/hub",
"tmpfs": {"/tmp":"size=512m"}
}
}
}

**Comment by vania-pooh** [comment]
@vasumadhu yes, but using `version = latest` will not work for Firefox.

**Comment by vasumadhu** [comment]
@vania-pooh Thanks for the confirmation.

**Comment by ngraf** [comment]
> @vasumadhu currently for latest versions you can use e.g. `selenoid/firefox:latest`. They are the same as VNC.

@vania-pooh , Does this mean I can use feature `enableVNC: true` with `selenoid/firefox:latest` image?

--------

I tried this and it worked! I had access to VNC screen in Selenoid UI
I was very (positively) surprised. 
Because if this is true, I wonder why VNC images are listed in the docs and maintained at all.
I had the same problem like the thread owner, that I missed a "latest" tag for VNC images. But now I have my solution in using non-VNC images that actually provide VNC feature. Still weird to me why this is possible and I am glad to hear the reason why this works form.
