### ISSUE TITLE
Make the docker image usage more robust

### ISSUE THREAD

**Issue by patjae** [aerokube/selenoid#919]
Hello,

This might be a request for a new feature.

We are using selenoid and selenoid-ui as docker containers.
We used cm to identify the image dependencies (e.g. for the configured brwoser sessions, we wanted to use).

Due to some reasons not directly related to selenoid, we want to have some housekeeping in place to delete docker images, not needed anymore.
Of course we run into the problem, that selenoid does not find its images anymore and therefore we have to ensure that certain images are retained.

You will run into these errors:
```
[SERVICE_STARTUP_FAILED] [start video container: create video container: Error response from daemon: No such image: selenoid/video-recorder:latest-release]

[SERVICE_STARTUP_FAILED] [create container: Error response from daemon: No such image: selenoid/vnc_chrome:81.0]
```

I will just list the images to retain, we identified so far (might be helpful for other users):
```
# all vnc images for brwoser sessions, e.g.
docker pull selenoid/vnc_chrome:81.0 
docker pull selenoid/vnc_chrome:80.0 
docker pull selenoid/vnc_firefox:75.0 
docker pull selenoid/vnc_firefox:76.0 
docker pull selenoid/vnc_opera:66.0 
docker pull selenoid/vnc_opera:67.0 
# thevideo-recoreder itself
docker pull selenoid/video-recorder:latest-release
```

It would be nice if selenoid could be a bit more robust, if the images are not available and pull and wait for it. Maybe I did not find the right configuration and this should already work, but it for me it was the same issue, if I try it on a clean setup using bash and cm.

Thanks!

**Comment by vania-pooh** [comment]
@patjae from the docs:
```
Why this is not the part of Selenoid? Well, this is easy to implement, but under heavy load the result can be unpredictable. For example after updating the file and reloading Selenoid it should pull new images. How long will you wait for new sessions then? What to do if Docker Registry is inaccessible? So for maintenance reasons it is easier to delegate such simple logic to external script. 
```
This was not implemented intentionally.
