### ISSUE TITLE
Delete process tree in stopProcess call

### ISSUE THREAD

**Issue by guskovd** [aerokube/selenoid#92]
Reason: In some cases, the driver may not close the browser window. (Iedriver in my case). 

It would be great if selenoid start doing it
According to https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773 this is possible

**Comment by aandryashin** [comment]
Method described in the article works only on unix like systems, we removed implementation of such approach in this commit: 

https://github.com/aerokube/selenoid/commit/ca5f57b7db4fe8d776b986118f72a009d0a4cdab

This is iedriver responsibility to terminate its child processes.

**Comment by guskovd** [comment]
What about implementing a field in a json file, for example:
"destroy": "taskkill.exe" "/pid" "{pid}"

**Comment by guskovd** [comment]
I understand that this is a iedriver issue. But, just as the opening and closing of docker containers on the fly allows you to overlook many problems, I would like to be able to easily solve the problems that arise on windows

**Comment by aandryashin** [comment]
Please try to use this project with selenoid:
https://github.com/kybu/headless-selenium-for-win
It uses virtual desktops for display isolation, and windows job objects for proper cleanup procedure.

**Comment by vania-pooh** [comment]
@guskovd have you seen this https://medium.com/@aandryashin/selenium-on-windows-revisited-1ab8d51ccc06 ?

**Comment by guskovd** [comment]
Thank you for the links. It seems to work.
But unclosed iedriver sessions is just one of the negative scenarios. Something like this can happen with a geckodriver, chromedriver, etc... Temporary files can not be cleaned after the browser is closed and so on. 
Unfortunately, the quality of the browser driver code leaves much to be desired. New versions of drivers come with new problems
I would like to see in selenoid a universal tool with which you can implement the workaround yourself.

**Comment by vania-pooh** [comment]
@guskovd how about using Docker functionality of Selenoid (on Linux)? This covers all except mobile browsers and IE\Edge.

**Comment by guskovd** [comment]
Yes, in our project the automation of Linux browsers is implemented through the docker. But unfortunately, the customer requires FF and Chrome automation on windows. 
For a long time I've been looking for the most clean way to clear traces of browsers. Your project, guys, in my opinion is the closest to what I was looking for.
I have an idea of how this can be implemented through an additional field in json.
I'm newby in golang. But I can try to do pull request

**Comment by vania-pooh** [comment]
@guskovd let's discuss a bit more before you spend your time.

**Comment by guskovd** [comment]
OK, my idea: https://github.com/aerokube/selenoid/issues/92#issuecomment-302958389
in code:
- If such a field exists, we kill the process via pid according to the instructions in it ("taskkil.exe" / "pkill" / "some_script") etc
- If there is no such field, just execute the existing logic

**Comment by guskovd** [comment]
this is my (very dirty) implementation:
https://github.com/guskovd/selenoid/commit/d593be4c3641f5dfc2a2ef280406e4446ab29f91

I also implemented the export of environment variables (SELENOID_PROCESS_PID, SELENOID_PROCESS_PORT) for later use in scripts
(Corresponding to the json fields: "image" and "cleanCmd")

**Comment by vania-pooh** [comment]
How about implementing https://github.com/kybu/headless-selenium-for-win/issues/15 instead?

**Comment by vania-pooh** [comment]
@guskovd what you are trying to do with your new code - is to solve your local issue. However our approach is to keep things as simple as possible. Adding custom process kill command to `browsers.json` is not a good idea because we tend to generate configs automatically by such tools as [cm](http://github.com/aerokube/cm) and this approach makes it a lot more difficult.

**Comment by guskovd** [comment]
It seems to me that my idea is applicable not only to windows. It can be used by those who for some reason do not use the docker.
I agree that my code breaks old behavior. But I do not pretend to pull request. I just wanted to illustrate my idea. 
If we do not want to break anything, do not add new fields to json, the standard way is to add some environment variable. (Should be defined before the start of the selenoid)
(ie SELENOID_CLEANUP_CMD="powershell.exe someScript.ps1")

**Comment by guskovd** [comment]
You see, just killing the driver process in a certain way is also not entirely correct.
I'm talking about the current implementation
If, for example, I want to run the driver through a script:

browsers.json
 
```json    
...
"image": "chromedriver.sh"
...
```

chromedriver.sh

```bash
TEMPDIR="/my/temp/path" /path/to/chromedriver $ *
```

... then after the session is closed, the chromedriver process will remain.

**Comment by guskovd** [comment]
I understand that the process tree closure has already been implemented in your project. But it was removed because of incompatibility with windows.
So why not just give the user the ability to run the driver and clean the context, since he himself wants it?

**Comment by aandryashin** [comment]
We will consider this in the further release.

24 мая 2017 г. 12:00 PM пользователь "guskovd" <notifications@github.com>
написал:

**Comment by guskovd** [comment]
Ok, thanks for the awesome project!

**Comment by vania-pooh** [comment]
Here for the next release we will implement killing the entire process tree for Linux and leave as is for Windows.

**Comment by vania-pooh** [comment]
To not complicate things decided that this would be better to implement as a standalone general-purpose binary and not only in Selenoid.
