### ISSUE TITLE
not able to start selenoid server 

### ISSUE THREAD

**Issue by sunnysachdeva99** [aerokube/selenoid#920]
HI,

I am new to Selenoid and facing issue in starting selenoid server in MAC.
I installed CM in my Douments/Selenoid folder and created docker compose and browser.json

Option 1:- docker-compose : I used below compose but when I do docker-compose up - d, I see that containers is not able to start

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid"
    command: ["-conf", "/Users/admin/Documents/Sephora_Docs/Selenoid/browser.json"]
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/Users/admin/Documents/Sephora_Docs/Selenoid:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"     
 selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

**Browser.json**
{
    "chrome": {
        "default": "81.0",
        "versions": {
            "80.0": {
                "image": "selenoid/chrome:80.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=512m"
                }
            },
            "81.0": {
                "image": "selenoid/chrome:81.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=512m"
                }
            }
        }
    },
    "firefox": {
        "default": "76.0",
        "versions": {
            "75.0": {
                "image": "selenoid/firefox:75.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "76.0": {
                "image": "selenoid/firefox:76.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    },
    "opera": {
        "default": "68.0",
        "versions": {
            "67.0": {
                "image": "selenoid/opera:67.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            },
            "68.0": {
                "image": "selenoid/opera:68.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {
                    "/tmp": "size=128m"
                }
            }
        }
    }
}

OPTION 2:-
./cm selenoid start --browsers-json browser.json

From the above command, I am able to start the selenoid server but I see its not taking browser versions that are mentioned in browser.json, instead I get below json output

{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"74.0":{},"75.0":{}},"firefox":{"67.0":{},"68.0":{}},"opera":{"58.0":{},"60.0":{}}}}

**Comment by vania-pooh** [comment]
@sunnysachdeva99 as I said in https://github.com/aerokube/cm/issues/263 you need to make sure that you have recent CM version to sync from existing file. In order to diagnose what is not working the usual way is to take a look at Docker logs:

```
$ docker logs selenoid
```

**Comment by sunnysachdeva99** [comment]
I am using 1.7.1 version
I also ran below command
./cm selenoid start --browsers 'chrome:81.0'
but still selenoid is showing defaut version


docker logs selenoid says
2020/05/20 05:09:31 [-] [INIT] [Loading configuration files...]
2020/05/20 05:09:31 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/05/20 05:09:31 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/05/20 05:09:31 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2020/05/20 05:09:31 [-] [INIT] [Using Docker API version: 1.40]
2020/05/20 05:09:31 [-] [INIT] [Timezone: UTC]
2020/05/20 05:09:31 [-] [INIT] [Listening on :4444]

why is it picking configuration from /etc/selenoid/browsers.json?

**Comment by vania-pooh** [comment]
@sunnysachdeva99 just because inside Docker container path is hard-coded to `/etc/selenoid/browsers.json` but on the host machine CM is usually storing this file in `~/.aerokube/selenoid/browsers.json` and just mounts this file to container.

**Comment by sunnysachdeva99** [comment]
Sorry for late reply. Do you agree the hard code path is an issue ?

**Comment by vania-pooh** [comment]
@sunnysachdeva99 no, just because Docker binds allow you to mount any external path to `/etc/selenoid/browsers.json`.
