### ISSUE TITLE
Unable to access website in container

### ISSUE THREAD

**Issue by dicksonprof** [aerokube/selenoid#922]
We run selenoid in our docker.

When the browser containers start they are unable to connect to the our application website hosting on another server.

We troubleshoot by running a simple java app container and sh into the container.
We were able curl to the application website.

Would like to seek assistance on how we can troubleshoot the problem.

We are using default docker bridge network docker0

**Comment by vania-pooh** [comment]
@dicksonprof are you setting DNS settings correctly in Docker?

**Comment by dicksonprof** [comment]
we tried with ip address.
Anyway to use selenoid with --network=host?

**Comment by vania-pooh** [comment]
@dicksonprof you can run Selenoid itself with `--network=host` but you can't run browser containers like this just because every container has inside webdriver binary listening on the same port 4444. When using `--net=host` ports will clash and containers will not start.
