### ISSUE TITLE
Timout for not idle session

### ISSUE THREAD

**Issue by FibYar** [aerokube/selenoid#924]
Hello!
Is there a way to set timeout for a not idle session? I manage selenoid server and it's not very easy to fix tests (they are not mine). Some tests can call webdriver in an endless loop. Selenoid thinks that test runs correctly (not idle) and continues to work. Flag timeout set to 5 minutes, max-timeout set to 3 hours. But I see with "docker ps" that chrome containers run 17 hours now.
Can I set some parameters to make selenoid kill **any** session that runs more than specified period of time (even if it is not idle)?

**Comment by vania-pooh** [comment]
@FibYar no, there is no such feature. You have to implement killing your tests yourself.
