### ISSUE TITLE
How to pass user data directory to Chrome?

### ISSUE THREAD

**Issue by rrhartjr** [aerokube/selenoid#925]
I would like to load a custom profile for chrome, but I don't see any options to pass a path into the Chrome containers?

Any ideas how I can accomplish this?

**Comment by vania-pooh** [comment]
@rrhartjr I'm not sure it is possible to set `profile` capability in the same way as for Firefox. Anyway you can at least change Chrome prefs using standard ChromeOptions methods described in its docs. https://chromedriver.chromium.org/capabilities

**Comment by rrhartjr** [comment]
I am creating the WebDriver like this:
```
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--user-data-dir=testProfileDir");
        return new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), chromeOptions);I
```

This is the exception I get:

```
Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot create default profile directory
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
```

I'm guessing it's trying to write inside the container but it can't?

**Comment by vania-pooh** [comment]
@rrhartjr yes, I think that's the reason. Probably you should use absolute path.

**Comment by Anticope12** [comment]
Hi @rrhartjr, I'm wondering have you found a workaround to run to pass user data directory to Chrome?

**Comment by rrhartjr** [comment]
> Hi @rrhartjr, I'm wondering have you found a workaround to run to pass user data directory to Chrome?

Yes, but the user data directory has to be inside the container, so it is not very practical

**Comment by vania-pooh** [comment]
@rrhartjr no, we don't provide this. Only in `browsers.json`.

**Comment by mirisr** [comment]
Does loading a profile --outside of docker-- work for you when you use a remote chrome driver?

Because it seems mine doesn’t even load. It works perfectly when its a local ChromeDriver.
I’m using chrome v102. I’d be interested if yours works and what version you’re using.

**Comment by Anticope12** [comment]
@mirisr ,
Check this one
[
](https://github.com/aerokube/selenoid/issues/1173#issue-1118399423)

It has all the errors I came across and best way to do it

**Comment by Anticope12** [comment]
https://github.com/aerokube/selenoid/issues/1173#issue-1118399423
