### ISSUE TITLE
Session creation is failing with 'Too Many Requests'

### ISSUE THREAD

**Issue by dibyaranjan-pg** [aerokube/selenoid#926]
We are trying to use Selenoid with GGR, and set up one cluster with 50 nodes per selenoid instance. 
VM configuration: 
Selenoid: Latest
GGR: Latest
CPU: 32 core
RAM: 32 GB

Suddenly we are seeing many requests are in pending state. Out of 50, `18`to `20` are consumed and rest are always pending state. 
top command shows, high consumption of IO.  We are also enabling VNC, not sure if it contributes to the network IO.
![image](https://user-images.githubusercontent.com/58494847/83023472-8c09a100-a05f-11ea-8f31-7d606b8ca29f.png)

**Comment by vania-pooh** [comment]
@dibyaranjan-pg this could be too many parallel sessions for 32 cores.

**Comment by vania-pooh** [comment]
@dibyaranjan-pg I mean you could try lowering `-limit` parameter value.

**Comment by dibyaranjan-pg** [comment]
@vania-pooh sure, am trying that now.. I see `pending` numbers decreased when I bring down the  `-limit` to 30.  1 core for 1 container looks too low for me, will try to increase it further cautiously and check. Do you have any suggestion to follow here? What should an ideal number of container 1 core cpu can hold?

**Comment by vania-pooh** [comment]
@dibyaranjan-pg this depends mainly on tested application. So `-limit` can vary from 1 to 1.5-2 browsers per CPU.
