### ISSUE TITLE
How to set chrome profile on selenoid?

### ISSUE THREAD

**Issue by u9O** [aerokube/selenoid#930]
I want to set a chrome profile for my session that are running in my vps on digitalocean, I didn't found anything help full in google, so I am asking this here.
please can anyone help me with that

**Comment by vania-pooh** [comment]
@u9O what exactly do you want to change in profile: e.g. install an extension, change Chrome preferences and so on?

**Comment by u9O** [comment]
I want to use a VPN extension, I know how to install it in the chrome driver browser, but the problem is I need to configur the extension like clicking a button in the extension to make VPN connecting to the server.

I tried to create a chrome profile and configur the extension there after that, set that profile to the to the chrome driver.

basicly what I want is to click the connect button in extension in chrome browser to connect to the VPN.
@vania-pooh

**Comment by vania-pooh** [comment]
@u9O how about using code like this? https://stackoverflow.com/questions/37137951/loading-crx-into-remote-chrome-selenium-python
