### ISSUE TITLE
Issue with Clipboard whilst trying to paste a large amount of characters

### ISSUE THREAD

**Issue by ngalanis930** [aerokube/selenoid#936]
We are currently running Selenoid 1.10.0 with Google Chrome 83.0 to conduct our test.
The specific test requires to paste on the clipboard an amount of approx. 90k characters (json format) but the session seems to hang.
When breaking down the above operation to chunks of 10k characters, then Selenoid is managing to complete the operation but in a really slow manner.
During our tests the only setup that worked out was to use a chunk of 3.8k characters.
The code used to paste the content on the clipboard is:

Keys key = OSUtilities.isOSMac() ? Keys.COMMAND : Keys.LEFT_CONTROL
controller().waitForElement(locator).sendKeys(Keys.chord(key, "v"))

Is there a limitation using the clipboard?
Any suggestions to counter this issue?

**Comment by vania-pooh** [comment]
@ngalanis930 are you using `/clipboard` API in that case?

**Comment by ngalanis930** [comment]
Yes we are using the /clipboard API.
You can reproduce the issue if you fire up a chrome browser and on the clipboard session POST  the json I've attached.
The chrome session is hanging.

[json.txt](https://github.com/aerokube/selenoid/files/4785995/json.txt)

**Comment by vania-pooh** [comment]
@ngalanis930 internally we are using `xsel` tool to paste to clipboard. So probably this could be `xsel` limitation. E.g. https://bbs.archlinux.org/viewtopic.php?id=217604

**Comment by ngalanis930** [comment]
So the xsel version used when a chrome container is fired up is:
`xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>`
Based on the above link you posted, it seems that nothing has changed in xsel for ages.
