### ISSUE TITLE
Default skin for selenoid/chrome-mobile:79.0

### ISSUE THREAD

**Issue by saurabh2k26** [aerokube/selenoid#937]
Hi, 

I am using selenoid/chrome-mobile:79.0 and on taking screenshots on failure, the UI does not seems to be of mobile browser and looks like desktop browser.

What is the default skin/screensize for this image and how can i change it to actually show UI of mobile browser.

**Comment by vania-pooh** [comment]
@saurabh2k26 this UI is Android emulator which is a desktop application. You can change skin with respective capability. https://aerokube.com/selenoid/latest/#_android_skin_skin
