### ISSUE TITLE
Using Selenoid without Docker: Internet Explorer: Getting this Error: InvalidArgumentError: No property named 'capabilities' found in new session request body

### ISSUE THREAD

**Issue by Binayjojo** [aerokube/selenoid#938]
**Captured logs** 

2020/06/18 11:42:48 [-] [INIT] [Loading configuration files...]
2020/06/18 11:42:48 [-] [INIT] [Loaded configuration from ./browsers.json]
2020/06/18 11:42:48 [-] [INIT] [Timezone: Local]
2020/06/18 11:42:48 [-] [INIT] [Listening on :4444]
2020/06/18 11:42:58 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2020/06/18 11:42:58 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2020/06/18 11:42:58 [0] [LOCATING_SERVICE] [internet explorer] [11]
2020/06/18 11:42:58 [0] [USING_DRIVER] [internet explorer] [11]
2020/06/18 11:42:58 [0] [ALLOCATING_PORT]
2020/06/18 11:42:58 [0] [ALLOCATED_PORT] [52132]
2020/06/18 11:42:58 [0] [STARTING_PROCESS] [[c:\selenoid\IEDriverServer.exe --log-level=DEBUG --port=52132]]
I 2020-06-18 11:42:58:901 C:\Projects\webdriver\cpp\webdriver-server\server.cc(87) Starting WebDriver server on port: '52132' on host: ''
I 2020-06-18 11:42:58:901 C:\Projects\webdriver\cpp\iedriver\IEServer.cpp(33) Driver version: 3.150.1.0 (64-bit)
Started InternetExplorerDriver server (64-bit)
3.150.1.0
Listening on port 52132
Log level is set to DEBUG
Only local connections are allowed
2020/06/18 11:42:59 [0] [PROCESS_STARTED] [11980] [0.56s]
2020/06/18 11:42:59 [0] [PROXY_TO] [http://127.0.0.1:52132]
2020/06/18 11:42:59 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:52132] [1]
D 2020-06-18 11:42:59:198 C:\Projects\webdriver\cpp\webdriver-server\server.cc(338) Command: POST /session {"desiredCapabilities":{"browserName":"internet explorer","version":"11","newCommandTimeout":90,"count":1}}
D 2020-06-18 11:42:59:198 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(60) Mutex acquired for session initalization
D 2020-06-18 11:42:59:205 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(116) Releasing session initialization mutex
D 2020-06-18 11:42:59:205 C:\Projects\webdriver\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"11","newCommandTimeout":90,"count":1}} }
D 2020-06-18 11:42:59:206 C:\Projects\webdriver\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"11","newCommandTimeout":90,"count":1}} }
D 2020-06-18 11:42:59:206 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(880) Executing command: newSession
D 2020-06-18 11:42:59:206 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(883) Command execution for newSession
complete
W 2020-06-18 11:42:59:207 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(929) Unable to get current browser
D 2020-06-18 11:42:59:207 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(935) Setting serialized response to {
        "value" :
        {
                "error" : "invalid argument",
                "message" : "No property named 'capabilities' found in new session request body.",
                "stacktrace" : ""
        }
}
D 2020-06-18 11:42:59:208 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(936) Is waiting flag: 0
D 2020-06-18 11:42:59:209 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(157) Executor shutdown successful!
D 2020-06-18 11:42:59:209 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(165) Posting thread shutdown message
D 2020-06-18 11:42:59:209 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(168) Starting wait for thread completion
D 2020-06-18 11:42:59:209 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(793) Shutdown message received
D 2020-06-18 11:42:59:

**Comment by vania-pooh** [comment]
@Binayjojo this is probably because you are sending capabilities in old format whereas new IEDriver versions are fully w3c-compatible.

**Comment by Binayjojo** [comment]
@vania-pooh Thanks for the reply , any pointers to w3c-compatible format.

**Comment by vania-pooh** [comment]
@Binayjojo use recent Selenium client library in your tests.

**Comment by Binayjojo** [comment]
Thanks @vania-pooh , was able to execute after downgrading the IEDriver version. Current framework is running on standalone 3.141.59
