### ISSUE TITLE
Chrome Extensions

### ISSUE THREAD

**Issue by Hamzosb** [aerokube/selenoid#939]
I'm running my script on chrome, it works fine but when i try to add chrome extension, the browser doesn't start

here is my python script :
```
import csv
import time

import pyautogui
from pynput import mouse, keyboard
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

keyboard = keyboard.Controller()
mouse = mouse.Controller()


pyautogui.FAILSAFE = False
opt = Options()
opt.add_argument("--disable-infobars")
opt.add_argument("start-maximized")
opt.add_experimental_option("prefs", {
        "profile.default_content_setting_values.media_stream_mic": 2,
        "profile.default_content_setting_values.media_stream_camera": 2,
        "profile.default_content_setting_values.geolocation": 2,
        "profile.default_content_setting_values.notifications": 2
    })
opt.add_extension(r'C:\Users\SAMSUNG\Dropbox\SB.crx')

capabilities = {
    "browserName": "chrome",
    "enableVNC": True,
    "enableVideo": True
}

driver = webdriver.Remote(
    command_executor="http://selenoid:4444/wd/hub",
    desired_capabilities=capabilities, options=opt)

```

**Comment by vania-pooh** [comment]
@Hamzosb any log messages from Selenoid UI or errors in test could help to diagnose.

**Comment by Hamzosb** [comment]
I've developed my script, and now this is my error : **selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot process extension #1
from unknown error: cannot base64 decode**


capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
         "args": ["disable-infobars", "start-maximized"],
         "extensions": [r'C:\Users\SAMSUNG\Dropbox\SB.crx'],
         "prefs": {
            "profile.default_content_setting_values.media_stream_mic": 2,
            "profile.default_content_setting_values.media_stream_camera": 2,
            "profile.default_content_setting_values.geolocation": 2,
            "profile.default_content_setting_values.notifications": 2
    }
      }}

driver = webdriver.Remote(command_executor="http://Selenoid/wd/hub",
                          desired_capabilities=capabilities)

**Comment by vania-pooh** [comment]
@Hamzosb seems to be https://github.com/SeleniumHQ/selenium/issues/6676.

**Comment by Hamzosb** [comment]
@vania-pooh Exactly, the solution was made by Java
I didn't know how to make it work on Python 

i tried this
file = base64.b64encode(r'C:\Users\SAMSUNG\Dropbox\SB.crx')

capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
         "args": ["disable-infobars", "start-maximized"],
         "extensions": [r'C:\Users\SAMSUNG\Dropbox\SB.crx'].push(file)

**got this error . TypeError: a bytes-like object is required, not 'str'**

**Comment by Hamzosb** [comment]
**i got this error :     file = fs.readFileSync(r'C:\Users\SAMSUNG\Dropbox\SB.crx', { encoding: 'base64' })
AttributeError: module 'fs' has no attribute 'readFileSync'**

When i used fs : 
`file = fs.readFileSync(r'C:\Users\SAMSUNG\Dropbox\SB.crx', { encoding: 'base64' })
`

**Comment by Hamzosb** [comment]
```
file = fs.readFileSync(r'C:\Users\SAMSUNG\Dropbox\SB.crx', { encoding: 'base64' })

capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
         "args": ["disable-infobars", "start-maximized"],
         "extensions": [r'C:\Users\SAMSUNG\Dropbox\SB.crx'].push(file),
         "prefs": {
            "profile.default_content_setting_values.media_stream_mic": 2,
            "profile.default_content_setting_values.media_stream_camera": 2,
            "profile.default_content_setting_values.geolocation": 2,
            "profile.default_content_setting_values.notifications": 2
    }
      }}

driver = webdriver.Remote(command_executor="http://selenoid:4444/wd/hub",
                          desired_capabilities=capabilities)

```

**Comment by Hamzosb** [comment]
I've made a js file to encode the extension : 
**JS File : extension.js**

```
var fs = require('fs');
var Fileen = fs.readFileSync('SB.crx', 'base64')

```

and imported it on my python script : 
**Python file :**

```
import json
from selenium import webdriver
with open('extension.js') as dataFile:
    data = dataFile.read()
    obj = data[data.find('{') : data.rfind('}')+1]
    jsonObj = json.loads(obj)
    print(data)


capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
         "args": ["disable-infobars", "start-maximized"],
         "extensions": [jsonObj],
         "prefs": {
            "profile.default_content_setting_values.media_stream_mic": 2,
            "profile.default_content_setting_values.media_stream_camera": 2,
            "profile.default_content_setting_values.geolocation": 2,
            "profile.default_content_setting_values.notifications": 2
    }
      }}

driver = webdriver.Remote(command_executor="http://selenoid/wd/hub",
                          desired_capabilities=capabilities)

```

I got this error : 
**json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

**Comment by Hamzosb** [comment]
I still got error extension : **TypeError: Object of type bytes is not JSON serializable**


```
from Naked.toolshed.shell import execute_js, muterun_js
import sys
import pyautogui
from pynput import mouse, keyboard
from selenium import webdriver
keyboard = keyboard.Controller()
mouse = mouse.Controller()

pyautogui.FAILSAFE = False

response = muterun_js('extension.js')
if response.exitcode == 0:
    data = response.stdout
else:
  sys.stderr.write(response.stderr)

capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
         "args": ["disable-infobars", "start-maximized"],
         "extensions": [data],
         "prefs": {
            "profile.default_content_setting_values.media_stream_mic": 2,
            "profile.default_content_setting_values.media_stream_camera": 2,
            "profile.default_content_setting_values.geolocation": 2,
            "profile.default_content_setting_values.notifications": 2
    }
      }}

driver = webdriver.Remote(command_executor="http://selenoid:4444/wd/hub",
                          desired_capabilities=capabilities)
print('done')
driver.get('https://www.google.com')
```

**Comment by Hamzosb** [comment]
Extension.js : 

```
fs = require('fs');
File = fs.readFileSync('C:\\Users\\SAMSUNG\\Dropbox\\SB.crx', 'base64');

console.log(File);

```

**Comment by ostap-oleksyn** [comment]
@Hamzosb you need pass a base64 encoded string instead of path to your extension. This should work:
```
import base64

from selenium import webdriver

extension = open(file=r'C:\Users\SAMSUNG\Dropbox\SB.crx', mode="rb").read()
encoded = base64.b64encode(extension).decode('UTF-8')

capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
        "args": ["disable-infobars", "start-maximized"],
        "extensions": [encoded],
        "prefs": {
            "profile.default_content_setting_values.media_stream_mic": 2,
            "profile.default_content_setting_values.media_stream_camera": 2,
            "profile.default_content_setting_values.geolocation": 2,
            "profile.default_content_setting_values.notifications": 2
        }
    }}

driver = webdriver.Remote(command_executor="http://Selenoid/wd/hub",
                          desired_capabilities=capabilities)
```

**Comment by Hamzosb** [comment]
Thank you bro



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
24/06/20
à 10:49:33

Le mer. 24 juin 2020 à 10:09, Ostap Oleksyn <notifications@github.com> a
écrit :

**Comment by vania-pooh** [comment]
@Hamzosb closing then?

**Comment by Hamzosb** [comment]
Yes



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
24/06/20
à 16:17:49

Le mer. 24 juin 2020 à 12:57, Ivan Krutov <notifications@github.com> a
écrit :
