### ISSUE TITLE
Cannot access VNC server

### ISSUE THREAD

**Issue by nebehr** [aerokube/selenoid#94]
I have latest versions selenoid + selenoid-ui installed on the same virtualbox (tried both Centos 7.1.1 and Ubuntu 16.10) with all default settings as specified in the current documentation. However when I try to view VNC session from selenoid-ui, I am getting "Disconnected" message and selenoid container log contains the following lines:

[VNC_ENABLED] [43823227-4cdc-4743-ba8c-965af5da4f09]
[VNC_ERROR] [dial tcp 172.17.0.4:5900: getsockopt: connection refused]

It looks as though selenoid container cannot access browser container's port 5900. Should not browser containers expose port 5900 or perhaps run in "net=host" mode? Or should there be any additional system configuration steps?

**Comment by vania-pooh** [comment]
Did you set `enableVNC=true` capability in tests?

**Comment by nebehr** [comment]
Sure, otherwise there would be no "VNC_ENABLED" and no available VNC sessions in Selenoid UI.

**Comment by vania-pooh** [comment]
Summon @aandryashin.

**Comment by vania-pooh** [comment]
@nebehr got it. This is because you are using container without VNC server inside. By default there is no VNC server. We are currently working to provide VNC containers for all supported browsers. Please try whether it works with [these](https://hub.docker.com/r/selenoid/vnc/tags/) images. Just update images in `browsers.json` and reload Selenoid.

**Comment by nebehr** [comment]
Hmm, this is embarrassing. It works now. :)

**Comment by vania-pooh** [comment]
@nebehr we decided to not include VNC by default because Selenoid is considered to be used in big cluster and VNC is mainly local debug feature. Also VNC makes images bigger. Here is the issue about adding VNC: https://github.com/aerokube/selenoid-images/issues/3
