### ISSUE TITLE
Log from Android emulator in Selenoid

### ISSUE THREAD

**Issue by GunkanjimaQA** [aerokube/selenoid#941]
Didn't find any info or examples on the topic over the internet.
Is there any possibility to get Android emulator log (aka Logcat) when using Selenoid?

**Comment by vania-pooh** [comment]
@GunkanjimaQA Selenoid internally packs Appium to Android images, so everything applicable to Appium will also work in Selenoid.

**Comment by GunkanjimaQA** [comment]
@vania-pooh Thank you for the quick response! I've implemented access to Logcat using Appium instruments. The problem is that access to emulator logs is available through
driver that is being created after installation and running of application (as shown in Appium log snippet below). But I'd like to see earlier stages from the emulator side. I'm facing an issue with slow and unstable installation/run of application when running Selenoid in a cloud. I realize that running Selenoid with nested virtualization/kvm is highly resource consumptive but still on very powerful instances 5-10 min timeout (androidInstallTimeout) is not enough and this is strange. Is it possible to access Logcat directly somehow or maybe you will consider adding Logcat access in a future?


`[ADB] com.genome.app.android.dev was not uninstalled, because it was not present on the device
[ADB] The application at '/Users/eky/psp_qatest/genomemobile/src/test/resources/app/genome-rc.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] The installation of 'application.apk' took 4373ms
[UiAutomator2] Starting UIAutomator2 server 4.5.5
[UiAutomator2] Using UIAutomator2 server from .../apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[AndroidDriver] Screen already unlocked, doing nothing
**[UiAutomator2] Starting 'com.genome.app.android.dev/com.application.ui.MainActivity and waiting for 'com.genome.app.android.dev/com.application.ui.MainActivity'**
[Appium] New AndroidUiautomator2Driver session created successfully, session 35284cf6-183b-48f6-9061-f6cfee9bebcd added to master session list
[HTTP] <-- POST /wd/hub/session 200 14307 ms - 1333
[HTTP] 
июн 23, 2020 10:49:30 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
[HTTP] --> GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd 200 7 ms - 1265
[HTTP] 
[HTTP] --> GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd 200 17 ms - 1265
[HTTP] 
10:49:30.462 [main] INFO  eu.genome.mobile.drivercontroller.AndroidDriverExtended -  
INFO: Driver was created like: AndroidDriverExtended

[HTTP] --> POST /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd/log
[HTTP] {"type":"logcat"}
[HTTP] <-- POST /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd/log 200 71 ms - 1068238
[HTTP] 
**[2020-06-23T10:49:16+0300] [ALL] --------- beginning of system
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.589  1288  1288 I vold    : Vold 3.0 (the awakening) firing up
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.589  1288  1288 V vold    : Detected support for: ext4 vfat
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844  1288  1291 D vold    : Recognized experimental block major ID 253 as virtio-blk (emulator's virtual SD card device)
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844  1288  1291 V vold    : /system/bin/sgdisk
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844  1288  1291 V vold    :     --android-dump
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844  1288  1291 V vold    :     /dev/block/vold/disk:253,64
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.854  1288  1323 D vold    : e4crypt_init_user0`**

**Comment by GunkanjimaQA** [comment]
@vania-pooh Thank you for the quick response! I've implemented access to Logcat using Appium instruments. The problem is that access to emulator logs is available through
driver that is being created after installation and running of application (as shown in Appium log snippet below). But I'd like to see earlier stages from the emulator side. I'm facing an issue with slow and unstable installation/run of application when running Selenoid in a cloud. I realize that running Selenoid with nested virtualization/kvm is highly resource consumptive but still on very powerful instances 5-10 min timeout (androidInstallTimeout) is not enough and this is strange. Is it possible to access Logcat directly somehow or maybe you will consider adding Logcat access in a future?

`[ADB] com.application.app.android.dev was not uninstalled, because it was not present on the device
[ADB] The application at '/Users/application.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] The installation of 'application.apk' took 4373ms
[UiAutomator2] Starting UIAutomator2 server 4.5.5
[UiAutomator2] Using UIAutomator2 server from .../apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[WD Proxy] Got response with unknown status: {"code":"ECONNRESET"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[AndroidDriver] Screen already unlocked, doing nothing
**[UiAutomator2] Starting 'com.application.app.android.dev/com.application.ui.MainActivity and waiting for 'com.application.app.android.dev/com.application.ui.MainActivity'**
[Appium] New AndroidUiautomator2Driver session created successfully, session 35284cf6-183b-48f6-9061-f6cfee9bebcd added to master session list
[HTTP] <-- POST /wd/hub/session 200 14307 ms - 1333
[HTTP]
июн 23, 2020 10:49:30 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
[HTTP] --> GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd 200 7 ms - 1265
[HTTP]
[HTTP] --> GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd
[HTTP] {}
[HTTP] <-- GET /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd 200 17 ms - 1265
[HTTP]
10:49:30.462 [main] INFO com.test.mobile.drivercontroller.AndroidDriverExtended -
INFO: Driver was created like: AndroidDriverExtended

[HTTP] --> POST /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd/log
[HTTP] {"type":"logcat"}
[HTTP] <-- POST /wd/hub/session/35284cf6-183b-48f6-9061-f6cfee9bebcd/log 200 71 ms - 1068238
[HTTP]
**[2020-06-23T10:49:16+0300] [ALL] --------- beginning of system
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.589 1288 1288 I vold : Vold 3.0 (the awakening) firing up
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.589 1288 1288 V vold : Detected support for: ext4 vfat
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844 1288 1291 D vold : Recognized experimental block major ID 253 as virtio-blk (emulator's virtual SD card device)
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844 1288 1291 V vold : /system/bin/sgdisk
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844 1288 1291 V vold : --android-dump
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.844 1288 1291 V vold : /dev/block/vold/disk:253,64
[2020-06-23T10:49:16+0300] [ALL] 06-23 10:27:36.854 1288 1323 D vold : e4crypt_init_user0**`
