### ISSUE TITLE
winappdriver support

### ISSUE THREAD

**Issue by roughsoft** [aerokube/selenoid#942]
selenoid can run winappdriver test suit？as we know winappdriver can run in selenium grid

**Comment by vania-pooh** [comment]
@roughsoft Selenoid is compatible with any webdriver delivering W3C Webdriver protocol (old-school JSON Wire is also supported).

**Comment by roughsoft** [comment]
@vania-pooh ，awesome!
then ,you means solenoid support WinAppDriver !
thank you!

**Comment by vania-pooh** [comment]
@roughsoft did not test myself but should support.
