### ISSUE TITLE
VNC password?

### ISSUE THREAD

**Issue by arnegroskurth** [aerokube/selenoid#944]
I would like to access a running browser instance using Remmina over VNC but it asks me for a password that I do not have. Is that documented somewhere?

```
$ docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                    PORTS                                              NAMES
a2f21a7e92ad        selenoid/vnc_chrome:83.0       "/entrypoint.sh"         15 minutes ago      Up 15 minutes             4444/tcp, 5900/tcp, 7070/tcp, 8080/tcp, 9090/tcp   intelligent_carson
91eb50e7e2ed        aerokube/selenoid-ui:1.10.0    "/selenoid-ui --sele…"   2 hours ago         Up 29 minutes (healthy)   0.0.0.0:8080->8080/tcp                             selenoid-ui
8a70d0ffec4d        aerokube/selenoid:1.10.0       "/usr/bin/selenoid -…"   2 hours ago         Up 29 minutes             0.0.0.0:4444->4444/tcp                             selenoid
```

(I know about the selenoid-UI but I would like to access the container using a standard VNC client)

**Comment by aandryashin** [comment]
Please use word selenoid as passwor.

вт, 30 июн. 2020 г., 18:04 Arne Groskurth <notifications@github.com>:

**Comment by arnegroskurth** [comment]
Thanks.

I think this should be documented here: https://aerokube.com/selenoid/latest/#_live_browser_screen_enablevnc

**Comment by vania-pooh** [comment]
@arnegroskurth this is set here: https://github.com/aerokube/selenoid-images/blob/master/selenium/chrome/entrypoint.sh#L75

**Comment by arnegroskurth** [comment]
@vania-pooh @aandryashin Is there actually a need to set a password at all?

**Comment by vania-pooh** [comment]
@arnegroskurth so far as I can remember this was done because in UI noVNC client we are using was not able to work without password.
