### ISSUE TITLE
How to access DevTools Debugger port on Selenoid Chrome container?

### ISSUE THREAD

**Issue by SeleniumTestAB** [aerokube/selenoid#945]
Hello,

I want to use CDP in order to inject token for authorization, since we can not use proxy for that for selenoid. How can i get access to the Chrome DevTools inside chrome browser in selenoid container? More precisely i need port.

**Comment by SeleniumTestAB** [comment]
Let me clear up a mistake, we are using moon 1.5.1 not a selenoid.

**Comment by SeleniumTestAB** [comment]
Okay, well i tried to use tips provided here:
https://github.com/aerokube/selenoid/issues/918

but i get HandShake error, expecting 101 but found 404.

**Comment by vania-pooh** [comment]
@SeleniumTestAB an example Java project is here: https://github.com/aerokube/chrome-developer-tools-protocol-java-example/

**Comment by SeleniumTestAB** [comment]
@vania-pooh as i said, i did use that example and outcome is listed in previous post. Also for some weird reason moon does accept requests for creating session on host/wd/hub without mentioning port 4444. What can i do ?

**Comment by vania-pooh** [comment]
@SeleniumTestAB euh, this repository contains Selenoid issues. Are we speaking about Selenoid or Moon?

**Comment by SeleniumTestAB** [comment]
@vania-pooh moon and yes i did realize that too... can i somehow export it to moon? Or i need to close it and reopen in moon?

**Comment by SeleniumTestAB** [comment]
@vania-pooh i opened a new issue in moon to clear it up.

https://github.com/aerokube/moon/issues/215

And i am closing this issue.
