### ISSUE TITLE
Launch selenoid servers on multiple docker networks

### ISSUE THREAD

**Issue by godomainz** [aerokube/selenoid#949]
I have 2 docker networks. 
i) selenoid
ii) selenoidjohn

I need to launch 2 selenoid servers from 2 different user accounts. Problem is when I do docker-compose up I always see selenoid from one network. Seems only services belongs to last docker-compose up.

These are my docker-compose.yml files

**FILE A**
version: "3"
networks:
  selenoidjohn:
    external:
      name: selenoidjohn
services:
  selenoid:
    networks:
        selenoidjohn: null
    image: "aerokube/selenoid:latest-release"
    restart: always
    ports:
        - "4445:4444"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "$PWD/selenoidconfig:/etc/selenoid/:ro"
        - $HOME/Projects/videos:/opt/selenoid/video
        - "$PWD/logs:/opt/selenoid/logs"
    environment:
        - OVERRIDE_VIDEO_OUTPUT_DIR=$HOME/Projects/videos
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs","-container-network", "selenoid","-timeout","8h","-service-startup-timeout","10m","-session-attempt-timeout","10m", ]
  selenoid-ui:
      networks:
          selenoidjohn: null
      image: "aerokube/selenoid-ui"
      restart: always
      depends_on:
          - selenoid
      ports:
          - "8082:8080"
      command: ["--selenoid-uri", "http://selenoid:4444"]

**FILE B**
version: "3"
networks:
  selenoid:
    external:
      name: selenoid
services:
  selenoid:
    networks:
        selenoid: null
    image: "aerokube/selenoid:latest-release"
    restart: always
    ports:
        - "4444:4444"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "$PWD/selenoidconfig:/etc/selenoid/:ro"
        - $HOME/Projects/videos:/opt/selenoid/video
        - "$PWD/logs:/opt/selenoid/logs"
    environment:
        - OVERRIDE_VIDEO_OUTPUT_DIR=$HOME/Projects/videos
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs","-container-network", "selenoid"]
  selenoid-ui:
    networks:
        selenoid: null
    image: "aerokube/selenoid-ui"
    restart: always
    depends_on:
        - selenoid
    ports:
        - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

As you can see above only difference is the network name. and these two files belongs to two different users.
How can I have multiple selenoid servers for multiple users ?

**Comment by vania-pooh** [comment]
@godomainz you certainly can. Just use different ports for every Selenoid and Selenoid UI instance and link them correctly. Simply make sure all containers you wish to have are actually running. Probably you have to run `docker-compose` with `-p` flag to use different project names (then container names will differ too).
