### ISSUE TITLE
Is it possible to let a chrome runner always connected to the hub ?

### ISSUE THREAD

**Issue by AlexGrs** [aerokube/selenoid#955]
We have a use case where we would need to run our tests on an already up and running chrome node instead of having a docker launched on the fly when the test begins?  So we basically need to have something close to a classic Selenium Grid where you have the grid and chrome nodes on standby waiting for tests to start.

The reason we need this is we want to perform tests with Web Browser having in the cache the assets when performing the test instead of starting with a fresh browser.

Is there any possibilities with Selenoid to do so? I looked at the doc but nothing really came up after reading it.

**Comment by vania-pooh** [comment]
@AlexGrs Selenoid is always launching a fresh browser container, however nothing prevents you from pinging a running session so it remains alive. Or you could set a big `sessionTimeout` value and reuse the same `session_id` and subsequent tests.

**Comment by AlexGrs** [comment]
Are you aware of any volume we could mount in order to preserve the cache between sessions ? 

I feel this solution of timeout or keeping the session alive a small hack. Would a PR on this would be acceptable for you? If yes if you have some indications of the selenoid way of doing so that would be great.

**Comment by aandryashin** [comment]
Selenoid will always start new container for new session. Even driver
always start browser with clean cache. You can start session with custom
profile with prefilled cache.

ср, 22 июл. 2020 г., 17:26 Alexandre Grais <notifications@github.com>:
