### ISSUE TITLE
Failed when connecting: Connection closed (code: 1000)

### ISSUE THREAD

**Issue by godomainz** [aerokube/selenoid#956]
![selenoid](https://user-images.githubusercontent.com/34884192/88209324-2e18c480-cc70-11ea-8a55-b4828a6a3661.png)

As per above screenshot I'm getting VNC Disconnected.
This is hosted on remote server using docker. This is "Docker in Docker implementation"

this is my docker-compose file

version: "3"
networks:
  selenoid:
    external:
      name: selenoid
services:
  selenoid:
    networks:
        selenoid: null
    image: "aerokube/selenoid:latest-release"
    restart: always
    ports:
        - "4444:4444"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "$PWD/selenoidconfig:/etc/selenoid/:ro"
        - $HOME/Projects/videos:/opt/selenoid/video
        - "$PWD/logs:/opt/selenoid/logs"
    environment:
        - OVERRIDE_VIDEO_OUTPUT_DIR=$HOME/Projects/videos
    command: ["-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs","-container-network", "selenoid","-timeout","8h","-service-startup-timeout","10m","-session-attempt-timeout","10m", ]
  selenoid-ui:
      networks:
          selenoid: null
      image: "aerokube/selenoid-ui"
      restart: always
      depends_on:
          - selenoid
      ports:
          - "8081:8080"
      command: ["--selenoid-uri", "http://selenoid:4444"]

I can't watch video live. But I can watch old videos when I clicked Videos link.
And I can see this console error -->  Failed when connecting: Connection closed (code: 1000) rfb.js:668

I managed to get below error from --> docker-compose logs --follow
`[VNC ERROR] [dial tcp 172.18.0.5:5900: connect: connection refused`

I managed to catch some error outputs as well.
I can see below errors

`95439231.695][INFO]: Waiting for pending navigations...
[1595439231.695][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=355) 907E8B9EDE154FC01AEB8BC2D449BDD9 {
   "expression": "1"
}
[1595439231.695][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=355) 907E8B9EDE154FC01AEB8BC2D449BDD9 {
   "result": {
      "description": "1",
      "type": "number",
      "value": 1
   }
}
[1595439231.695][INFO]: Done waiting for pending navigations. Status: ok
[1595439231.695][INFO]: [5193d46ce8e3cb8ce787f4e283b3e674] RESPONSE ClickElement
 --- x11vnc loop: waiting for: 413

error opening logfile: /home/selenium/x11vnc.log
open: Permission denied

 --- x11vnc loop: sleeping 500 ms ---

 --- x11vnc loop: 8 ---

[1595439232.699][INFO]: [5193d46ce8e3cb8ce787f4e283b3e674] COMMAND ExecuteAsyncScript {
   "args": [ "" ],
   "script": "try { return (function anonymous(\n) {\nfunction getNg1Hooks(selector, injectorPlease) {\n  function tryEl(el) {\n    try {\n      if (!injectorPlease && angular.getTestability) {\n        var $$testabil..."
}
[1595439232.699][DEBUG]: DevTools WebSocket Event: DOM.childNodeCountUpdated 907E8B9EDE154FC01AEB8BC2D449BDD9 {
   "childNodeCount": 15,
   "nodeId": 23
}
[1595439232.699][DEBUG]: DevTools WebSocket Event: DOM.attributeModified 907E8B9EDE154FC01AEB8BC2D449BDD9 {
   "name": "class",
   "nodeId": 23,
   "value": " ng-scope "
}`

**Comment by vania-pooh** [comment]
@godomainz are you using image with `vnc` prefix in `browsers.json`?

**Comment by godomainz** [comment]
@vania-pooh yes. this is my browsers.json

```
        "default": "81.0",
        "versions": {
            "81.0": {
                "image": "selenoid/vnc:chrome_81.0",
                "port": "4444",
                "path": "/",
                "shmSize" : 1068435456
            },
            "80.0": {
                "image": "selenoid/vnc:chrome_80.0",
                "port": "4444",
                "path": "/",
                "shmSize" : 1068435456
            }
        }
    }
}
```

**Comment by vania-pooh** [comment]
@godomainz could also be SELinux issue. If you are running everything under CentOS \ RedHat - try to disable SELinux.
```
error opening logfile: /home/selenium/x11vnc.log
open: Permission denied
```
Because of this permissions issue VNC server does not start.

**Comment by godomainz** [comment]
@vania-pooh I'm running ubuntu 18.04
There is no Selinux installed.
I'm getting below error when I run sestatus command
`-bash: sestatus: command not found`

btw where is this /home/selenium/x11vnc.log mounted (I don't see that folder on my host)?
thats in the docker container right ?
So there shouldn't be any issue for the container right ?

I can see video when I'm running as root for the main docker host.
Should I give permissions for any special folder ?

**Comment by vania-pooh** [comment]
@godomainz this file is being created inside container. Everything inside container is being run as user `selenium`.

**Comment by godomainz** [comment]
@vania-pooh so why there is a permission issue ?
is it mounted to host ?

**Comment by vania-pooh** [comment]
@godomainz File exists only inside container. Possible reasons are explained here: https://github.com/moby/moby/issues/1295#issuecomment-269058662

**Comment by godomainz** [comment]
@vania-pooh thanks for your help. I removed the image. Then pulled it using normal user. I must have pulled the image using root. Now it works.
