### ISSUE TITLE
how to rename video name individually according my setting?

### ISSUE THREAD

**Issue by loudDD** [aerokube/selenoid#958]
I've read below messages:

By default saved video files are named <session-id>.mp4 where <session-id> is a unique identifier of Selenium session. To provide custom video name specify:

Type: string
videoName: "my-cool-video.mp4"

but is there a way to rename the video name as i need ? 
e.g. my test cases name are [ test_google ,test_twitter] , can i rename the video name to test google and another video to test_twitter ?

**Comment by vania-pooh** [comment]
@loudDD you can then use `videoName = test_google.mp4`. Don't get where it the difficulty?

**Comment by loudDD** [comment]
i've tried . just need to add videoName in desiredcap . close it
