### ISSUE TITLE
Potential resource leak on browser container spin up

### ISSUE THREAD

**Issue by nebehr** [aerokube/selenoid#96]
I am observing a resource leak with Firefox containers (both Selenium Server-based and Selenoid-based) which may potentially lead to Selenoid node shutdown.

I have a single virtualbox with latest version of Selenoid, configured with default limit of 5 browsers. I am able to reach this limit with Chrome containers without any issues. However when I try to get 3 or more Firefoxes (tried selenoid/firefox:45.0, selenoid/firefox:53.0 and selenoid/vnc:firefox_53.0 images) the third container gets in a kind of endless loop with log like this:
```
2017/05/25 13:50:25 Loading configuration files...
2017/05/25 13:50:25 Loaded configuration from [/etc/selenoid/browsers.json]
2017/05/25 13:50:25 Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory
2017/05/25 13:50:25 Timezone: UTC
2017/05/25 13:50:25 Listening on :4444
2017/05/25 13:50:25 [NEW_REQUEST]
2017/05/25 13:50:25 [NEW_REQUEST_ACCEPTED]
2017/05/25 13:50:25 [0] [LOCATING_SERVICE] [firefox-53.0]
2017/05/25 13:50:25 [0] [USING_DRIVER] [firefox-53.0]
2017/05/25 13:50:25 [0] [ALLOCATING_PORT]
2017/05/25 13:50:25 [0] [ALLOCATED_PORT] [42260]
2017/05/25 13:50:25 [0] [STARTING_PROCESS] [[/usr/bin/geckodriver --host :: --log debug --port=42260]]
2017/05/25 13:50:26 [0] [PROCESS_STARTED] [28] [242.803186ms]
2017/05/25 13:50:26 [0] [PROXYING_REQUESTS] [http://127.0.0.1:42260]
2017/05/25 13:50:26 [0] [SESSION_ATTEMPTED] [unknown] [http://127.0.0.1:42260] [1]
2017/05/25 13:50:37 [NEW_REQUEST]
2017/05/25 13:50:37 [NEW_REQUEST_ACCEPTED]
2017/05/25 13:50:37 [0] [CLIENT_DISCONNECTED] [unknown]
2017/05/25 13:50:37 [0] [TERMINATING_PROCESS] [28]
2017/05/25 13:50:37 [0] [TERMINATED_PROCESS] [28]
2017/05/25 13:50:37 [1] [LOCATING_SERVICE] [firefox-53.0]
2017/05/25 13:50:37 [1] [USING_DRIVER] [firefox-53.0]
2017/05/25 13:50:37 [1] [ALLOCATING_PORT]
2017/05/25 13:50:37 [1] [ALLOCATED_PORT] [43122]
2017/05/25 13:50:37 [1] [STARTING_PROCESS] [[/usr/bin/geckodriver --host :: --log debug --port=43122]]
2017/05/25 13:50:37 [1] [PROCESS_STARTED] [106] [200.017157ms]
2017/05/25 13:50:37 [1] [PROXYING_REQUESTS] [http://127.0.0.1:43122]
2017/05/25 13:50:37 [1] [SESSION_ATTEMPTED] [unknown] [http://127.0.0.1:43122] [1]
2017/05/25 13:50:46 [1] [CLIENT_DISCONNECTED] [unknown]
2017/05/25 13:50:46 [1] [TERMINATING_PROCESS] [106]
2017/05/25 13:50:46 [1] [TERMINATED_PROCESS] [106]
2017/05/25 13:50:46 [NEW_REQUEST]
...
```
This log is for Selenoid-based image; in Selenium-based one it is slightly different but the main idea is the same. It looks as though Selenoid starts geckodriver (or whatever) and Firefox instance which fails to respond within 10 seconds, abandons them and starts another, and so ad infinitum. `ps -ef` indeed shows a lot of defunct geckodriver processes and a lot of active firefoxes (note that geckodrivers were apparently killed but firefoxes were not). The virtual box quickly becomes unresponsive and stops to serve requests even to "good" containers. When I increase number of CPUs and memory on that box, the issue goes away but really it is still there, just hidden.

I am not sufficiently well versed in Go, but I suspect the timeout in question might be hardcoded somewhere around https://github.com/aerokube/selenoid/blob/master/selenoid.go#L158. Maybe it makes sense to make it configurable or increase it to a more reasonable value? Or maybe get rid of the infinite loop?

**Comment by vania-pooh** [comment]
@nebehr thank you for detailed explanation. Let's then expose this timeout as Selenoid parameter.

**Comment by vania-pooh** [comment]
@nebehr added `-session-attempt-timeout` parameter. Please set it like: `-session-attempt-timeout 30s` and reopen if this does not help.

**Comment by vania-pooh** [comment]
I could also build a binary if needed.
