### ISSUE TITLE
Getting WebDriverError: invalid argument: File not found while doing file upload

### ISSUE THREAD

**Issue by Binayjojo** [aerokube/selenoid#960]
Getting this error while uploading a file .

Chrome version 75

WebDriverError: invalid argument: File not found : /tmp/7d3473e5172f08d5c5c3044812d55d79/test.zip

Function
    async uploadPackage(packageName: string): Promise<void> {
        await browser.setFileDetector(new remote.FileDetector());
        const fpath = path.resolve(`${browser.params.root}/tests/datas/`, test.zip);
        await this.uiPackageButton.sendKeys(fpath);
}

**Comment by vania-pooh** [comment]
@Binayjojo have you seen these examples: https://aerokube.com/selenoid/latest/#_uploading_files_to_browser ? I think your issue seems to be framework-specific.

**Comment by Binayjojo** [comment]
Hi @vania-pooh  ,
Had previously configured via docker compose , was not working .
Now did it via cm it works. Will close the issue .
Thanks for replying.
Regards,
Binay
