### ISSUE TITLE
Error starting containers

### ISSUE THREAD

**Issue by pranav165** [aerokube/selenoid#962]
Occasionaly i get this error when running selenium tests using selenoid

Selenoid start command is - /localocbuilds/agent/work/e2e/tools/cm_linux" selenoid start --quiet --browsers 'chrome' --last-versions 1 --tmpfs 1024 -c "/localocbuilds/agent/work/e2e"/reports --vnc --args "-limit 5"

selenium.common.exceptions.WebDriverException: Message: start container: Error response from daemon: linux runtime spec devices: lstat /dev/dm-8: no such file or directory

**Comment by vania-pooh** [comment]
@pranav165 this is Docker issue, not Selenoid one.

**Comment by pranav165** [comment]
Any workarounds you can suggest ?

**Comment by vania-pooh** [comment]
@pranav165 related issue https://github.com/moby/moby/issues/37456. Probably trying different Docker versions could help.
