### ISSUE TITLE
Selenoid Android issues, probably mines...

### ISSUE THREAD

**Issue by xMagiciaNx** [aerokube/selenoid#965]
Hello and thank you for the excellent framework.
I am trying to run WEB tests on mobile browser but failing hard.

My browsers.json file is:
`{"chrome-mobile": {
    "default": "mobile-79.0",
    "versions": {
      "mobile-79.0": {
        "image": "selenoid/chrome-mobile:79.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  }}`

Then I start selenoid binary and everything is set up.

I am running the tests with:
`mvn  verify  -Dwebdriver.driver=remote -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dcontext=android -Dwebdriver.remote.driver=appium -Dwebdriver.remote.os=ANDROID -Dappium.browserName=chrome  &
`
Then I always get no matching capabilities found error.

Any suggestion? I the information given in this post are vague, please let me know to provide more like stack trace etc.

Ty.

**Comment by xMagiciaNx** [comment]
#Update

Try running again and that time i get 
`(wait: http://127.0.0.1:32771/wd/hub does not respond in 30s (WARNING: The server did not provide any stacktrace information)`

The command i run is this:
`mvn  verify  -Dwebdriver.driver=remote -Dwebdriver.remote.url=http://localhost:4444/wd/hub -Dcontext=android -Dwebdriver.remote.driver=appium -Dappium.browserName=android -Dwebdriver.remote.os=ANDROID &
`
Why selenoid changes the default port? Is it any bug or sth ?

**Comment by vania-pooh** [comment]
@xMagiciaNx need to increase Selenoid timeouts:
```
-service-startup-timeout 2m -session-attempt-timeout 2m
```

**Comment by rajesh9383** [comment]
@vania-pooh I have similar issue can you please help me resolve it

2020/11/23 13:23:56 [-] [NEW_REQUEST] [unknown] [10.72.86.31]
2020/11/23 13:23:56 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.72.86.31]
2020/11/23 13:23:56 [13473] [LOCATING_SERVICE] [chrome] [mobile-86.0]
2020/11/23 13:23:56 [13473] [USING_DOCKER] [chrome] [mobile-86.0]
2020/11/23 13:23:56 [13473] [CREATING_CONTAINER] [selenoid/chrome-mobile:86.0]
2020/11/23 13:23:56 [13473] [STARTING_CONTAINER] [selenoid/chrome-mobile:86.0] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c]
2020/11/23 13:23:56 [13473] [CONTAINER_STARTED] [selenoid/chrome-mobile:86.0] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c] [0.32s]
2020/11/23 13:23:56 [13473] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2020/11/23 13:23:56 [13473] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a]
2020/11/23 13:23:57 [13473] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a] [0.35s]
2020/11/23 13:24:27 [13473] [STOPPING_VIDEO_CONTAINER] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a]
2020/11/23 13:24:27 [13473] [REMOVING_CONTAINER] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a]
2020/11/23 13:24:27 [13473] [FAILED_TO_REMOVE_CONTAINER] [60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a] [Error response from daemon: removal of container 60bbcc1c241fb097dbc0a82dcf7bff4a403fb608ec94b5b0fd1f5bf86905f95a is already in progress]
2020/11/23 13:24:27 [13473] [REMOVING_CONTAINER] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c]
2020/11/23 13:24:27 [13473] [CONTAINER_REMOVED] [c725449b7a6ece37bb811bd4665cadb52fca5df5517fc4432ac58e5dcc3dfb3c]
2020/11/23 13:24:27 [13473] [SERVICE_STARTUP_FAILED] [wait: http://172.18.0.4:4444/wd/hub does not respond in 30s]
2020/11/23 13:25:44 [-] [NEW_REQUEST] [unknown] [10.72.86.31]
2020/11/23 13:25:44 [-] [NEW_REQUEST_ACCEPTED] [unknown] [10.72.86.31]
2020/11/23 13:25:44 [13496] [LOCATING_SERVICE] [chrome] [mobile-86.0]
2020/11/23 13:25:44 [13496] [USING_DOCKER] [chrome] [mobile-86.0]
2020/11/23 13:25:44 [13496] [CREATING_CONTAINER] [selenoid/chrome-mobile:86.0]
2020/11/23 13:25:44 [13496] [STARTING_CONTAINER] [selenoid/chrome-mobile:86.0] [ad638a1639b279fe7f5653a16f97bf2f3ae0cfa352443b3192e4740be10db85e]
2020/11/23 13:25:44 [13496] [CONTAINER_STARTED] [selenoid/chrome-mobile:86.0] [ad638a1639b279fe7f5653a16f97bf2f3ae0cfa352443b3192e4740be10db85e] [0.32s]


Here is my config file
My browser.json file
{
"android": {
"default": "10.0",
"versions": {
"10.0": {
"image": "selenoid/android:10.0",
"port": "4444",
"path": "/wd/hub"
}
}
},
"chrome": {
"default": "mobile-86.0",
"versions": {
"mobile-86.0": {
"image": "selenoid/chrome-mobile:86.0",
"port": "4444",
"path": "/wd/hub"
}
}
}
}

**Comment by vania-pooh** [comment]
@rajesh9383 see my previous comment above.
