### ISSUE TITLE
Selenoid: Adding proxy to android emulator 

### ISSUE THREAD

**Issue by shj941013** [aerokube/selenoid#968]
Hello,

I am currently running Selenoid and trying to run Android Emulator. I am unable to get to any-sites as the emulator doesn't have proxy nor can I add them.

After some searches later I found out the ability to set emulator -http-proxy flag has been implemented: 
github.com/aerokube/selenoid-images/issues/167

Would I be able to get some example of how this -http-proxy flag could be set?

Should this be done on the test files? browsers.json?

I am currently running python tests and trying to set proxy this way 

```
capabilities = DesiredCapabilities.CHROME

proxy = Proxy()
proxy.proxy_type = ProxyType.MANUAL

proxy.http_proxy = "*proxy*"
proxy.socks_proxy = "*proxy*"
proxy.ssl_proxy = "*proxy*"

proxy.add_to_capabilities(capabilities)

capabilities["-http-proxy"] = "*proxy*"
```

**Comment by vania-pooh** [comment]
@shj941013 currently you have to set it via EMULATOR_ARGS environment variable using `env` capability or respective `browsers.json` section. https://github.com/aerokube/selenoid-images/blob/master/selenium/android/entrypoint.sh#L6

**Comment by shj941013** [comment]
@vania-pooh Thank you for the response! 

so if I set the EMULATOR_ARGS environment variable on the machine that i'm running Selenoid, is should take that value?

how would I be able to set it up on browsers.json? would it look something like this?

{
    "android": {
        "default": "6.0",
        "versions": {
            "6.0": {
                "image": "selenoid/android:6.0",
                "port": "4444",
                "path": "/wd/hub"
                "EMULATOR_ARGS": "-http-proxy: *proxy*"
            }
        }
    }
}

**Comment by vania-pooh** [comment]
@shj941013 using `env` as shown here: https://aerokube.com/selenoid/latest/#_other_optional_fields

**Comment by shj941013** [comment]
ah okay! so I have tried in this manners but it seems that it would not take the proxy either ways...

```
{
    "android": {
        "default": "6.0",
        "versions": {
            "6.0": {
                "image": "selenoid/android:6.0",
                "port": "4444",
                "path": "/wd/hub",
                "env": ["EMULATOR_ARGS=*proxy*"]
            }
        }
    }
}
```
```
{
    "android": {
        "default": "6.0",
        "versions": {
            "6.0": {
                "image": "selenoid/android:6.0",
                "port": "4444",
                "path": "/wd/hub",
                "env": ["http-proxy=*proxy*"]
            }
        }
    }
}
```

is this right..? Thank you in advance!

**Comment by vania-pooh** [comment]
@shj941013 I think should be something like this:
```
{
    "android": {
        "default": "6.0",
        "versions": {
            "6.0": {
                "image": "selenoid/android:6.0",
                "port": "4444",
                "path": "/wd/hub",
                "env": ["EMULATOR_ARGS=-http-proxy=*proxy*"]
            }
        }
    }
}
```

**Comment by shj941013** [comment]
Yes this worked!! thank you! Closing the issue!
