### ISSUE TITLE
Error related to docker registry 

### ISSUE THREAD

**Issue by pranav165** [aerokube/selenoid#969]
Getting following error  
x Docker Registry is not available: Get "https://registry.hub.docker.com/v2/": dial tcp 54.163.168.30:443: i/o timeout
[11:05:27]x Docker registry client not initialized

start command - "${current_dir}/tools/cm_linux" selenoid start --browsers 'chrome' --last-versions 1 --tmpfs 1024 -c "${current_dir}"/reports --vnc --args "-limit $(containers)"

**Comment by vania-pooh** [comment]
@pranav165 seems to be firewall-related issue. Check that you have direct Internet access in your corporate network.

**Comment by pranav165** [comment]
Got resolved by itself after like 30 minutes , looks like some issue at docker hub side  as no changes were done related to firewall

**Comment by vania-pooh** [comment]
@pranav165 ok, closing then.
