### ISSUE TITLE
the system may crash because of the number of node

### ISSUE THREAD

**Issue by loudDD** [aerokube/selenoid#973]
when I set the node number to be 20, the system may crash like my test case may stop because of invalid session id, so I want to know the CPU and memory that one node needs theoretically with and without video recording.
e.g.: my machine parameters:
16x 64G

**Comment by vania-pooh** [comment]
@loudDD approximately 1 CPU and 1 GB RAM per parallel browser. With video recording you have to multiply this by 2.
