### ISSUE TITLE
SESSION_FAILED - 500 Internal Server Error

### ISSUE THREAD

**Issue by edelGaspar** [aerokube/selenoid#974]
Hi,

Please help,
I try to test on firefox, but I can't create the sessions.

I start the application as follows:
selenoid
`./cm selenoid configure --vnc --browsers "firefox" --browsers-json /home/qa/selenoid/config/browsers.json  --tmpfs 128 && ./cm selenoid start --port 4444 --args "-limit 5 -service-startup-timeout 120s -session-attempt-timeout 120s -session-delete-timeout 120s -timeout 120s"`

selenoid-ui
`docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui --selenoid-uri http://172.18.0.1:4444`

My browsers.json configuration file:
`{
    "firefox": {
        "default": "54.0",
        "versions": {
            "54.0": {
                "image": "selenoid/vnc:firefox_54.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "56.0": {
                "image": "selenoid/vnc:firefox_56.0",
                "port": "4444",
                "path": "/wd/hub"
            }

        }
    }
}`

Logs selenoid:
`2020/08/20 06:42:02 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2020/08/20 06:42:02 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2020/08/20 06:42:02 [25] [LOCATING_SERVICE] [firefox] [54.0]
2020/08/20 06:42:02 [25] [USING_DOCKER] [firefox] [54.0]
2020/08/20 06:42:02 [25] [CREATING_CONTAINER] [selenoid/vnc:firefox_54.0]
2020/08/20 06:42:02 [25] [STARTING_CONTAINER] [selenoid/vnc:firefox_54.0] [e365eeb0c3bbe67ee0cd1a669fde9a2383e00d52c4de751024826f63cf65770f]
2020/08/20 06:42:02 [25] [CONTAINER_STARTED] [selenoid/vnc:firefox_54.0] [e365eeb0c3bbe67ee0cd1a669fde9a2383e00d52c4de751024826f63cf65770f] [0.75s]
2020/08/20 06:42:03 [25] [SERVICE_STARTED] [selenoid/vnc:firefox_54.0] [e365eeb0c3bbe67ee0cd1a669fde9a2383e00d52c4de751024826f63cf65770f] [0.21s]
2020/08/20 06:42:03 [25] [PROXY_TO] [e365eeb0c3bbe67ee0cd1a669fde9a2383e00d52c4de751024826f63cf65770f] [http://172.18.0.3:4444/wd/hub]
2020/08/20 06:42:03 [25] [SESSION_ATTEMPTED] [http://172.18.0.3:4444/wd/hub] [1]
2020/08/20 06:42:06 [25] [SESSION_FAILED] [http://172.18.0.3:4444/wd/hub] [500 Internal Server Error]
2020/08/20 06:42:06 [25] [REMOVING_CONTAINER] [e365eeb0c3bbe67ee0cd1a669fde9a2383e00d52c4de751024826f63cf65770f]
2020/08/20 06:42:06 [25] [CONTAINER_REMOVED] [e365eeb0c3bbe67ee0cd1a669fde9a2383e00d52c4de751024826f63cf65770f]
`

thanks in advance

**Comment by vania-pooh** [comment]
@edelGaspar are you getting any error message in tests output?

**Comment by edelGaspar** [comment]
I haven't run any tests yet. I would like to create a session selenoid-ui and I get that error. My objective is to install selenium_ide-2.9.1-fx.xpi in firefox 54, modify the docker image to be able to lift several containers and run tests in parallel.

**Comment by vania-pooh** [comment]
@edelGaspar ok, then open browser console and copy error message there when creating a new session.

**Comment by edelGaspar** [comment]
Response POST http://localhost:8080/wd/hub/session

`XHRPOSThttp://localhost:8080/wd/hub/session
[HTTP/1.1 500 Internal Server Error 7435ms]

    	
    value	Object { error: "session not created", message: "TypeError: Given browserVersion [object String] \"54.0\", but current version is [object String] \"54.0.1\"", stacktrace: "stack backtrace:\n 0: 0x57af6d - backtrace::backtrace::trace::h59229d13f6a8837d\n 1: 0x57b0c2 - backtrace::capture::Backtrace::new::h23089c033eded8f0\n 2: 0x4472fc - webdriver::error::WebDriverError::new::h0b226f62ff19e120\n 3: 0x455bb8 - geckodriver::marionette::MarionetteSession::response::hcd41032e9ef5a928\n 4: 0x46ace4 - geckodriver::marionette::MarionetteConnection::send_command::hd7b113ec7d281909\n 5: 0x426e5f - <webdriver::serve…8\n 8: 0x41c003 - <F as alloc::boxed::FnBox<A>>::call_box::hd6ceeda495c4fa0e\n 9: 0x5d68d4 - alloc::boxed::{{impl}}::call_once<(),()>\n at /checkout/src/liballoc/boxed.rs:650\n - std::sys_common::thread::start_thread\n at /checkout/src/libstd/sys_common/thread.rs:21\n - std::sys::imp::thread::{{impl}}::new::thread_start\n at /checkout/src/libstd/sys/unix/thread.rs:84" }
    error	"session not created"
    message	"TypeError: Given browserVersion [object String] \"54.0\", but current version is [object String] \"54.0.1\""
    stacktrace	"stack backtrace:\n 0: 0x57af6d - backtrace::backtrace::trace::h59229d13f6a8837d\n 1: 0x57b0c2 - backtrace::capture::Backtrace::new::h23089c033eded8f0\n 2: 0x4472fc - webdriver::error::WebDriverError::new::h0b226f62ff19e120\n 3: 0x455bb8 - geckodriver::marionette::MarionetteSession::response::hcd41032e9ef5a928\n 4: 0x46ace4 - geckodriver::marionette::MarionetteConnection::send_command::hd7b113ec7d281909\n 5: 0x426e5f - <webdriver::serve…8\n 8: 0x41c003 - <F as alloc::boxed::FnBox<A>>::call_box::hd6ceeda495c4fa0e\n 9: 0x5d68d4 - alloc::boxed::{{impl}}::call_once<(),()>\n at /checkout/src/liballoc/boxed.rs:650\n - std::sys_common::thread::start_thread\n at /checkout/src/libstd/sys_common/thread.rs:21\n - std::sys::imp::thread::{{impl}}::new::thread_start\n at /checkout/src/libstd/sys/unix/thread.rs:84"`

Can't start session manually 
Object { message: "ajax error 500", name: "AjaxError", xhr: XMLHttpRequest, request: {…}, status: 500, responseType: "json", response: {…}, stack: "" }
index.js:219:28

**Comment by edelGaspar** [comment]
**message	"TypeError: Given browserVersion [object String] \"54.0\", but current version is [object String] \"54.0.1\""**

Is there something wrong with the configuration of the file browsers.json ?

These are my browsers: 
![image](https://user-images.githubusercontent.com/3612191/90804771-ab277000-e2e8-11ea-8227-02b814cb42af.png)

**Comment by vania-pooh** [comment]
@edelGaspar hmm, this is because Geckodriver is matching version exactly. Changing to 54.0.1 in browsers.json should fix the issue. We'll think how to fix this on our side too.

**Comment by edelGaspar** [comment]
@vania-pooh , the workaround does not work

When I use 54.0.1 i get the error:  "Requested environment is not available"
`{
    "firefox": {
        "default": "54.0.1",
        "versions": {
            "54.0.1": {
                "image": "selenoid/vnc:firefox_54.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "57": {
                "image": "selenoid/vnc:firefox_57.0",
                "port": "4444",
                "path": "/wd/hub"
            }

        }
    }
}`

some other alternative solution ?

**Comment by amit-chaudhary4** [comment]
I also cannot create sessions manually. Also, when I try to execute my tests, the 4-5 containers for browsers are created and then they are recreated every few seconds.

2022/10/14 11:49:29 [919] [CONTAINER_STARTED] [selenoid/chrome:104.0] [2aa75c8ef56ac2e172a3c190cd96fdf19303888333872ca7dcd83f8b0307f9c5] [0.48s]
2022/10/14 11:49:30 [906] [SESSION_FAILED] [http://172.18.0.5:4444/] [500 Internal Server Error]
2022/10/14 11:49:30 [906] [REMOVING_CONTAINER] [737c99aa5e42dbcc0b1e12ff3aa9fbe86f850828102e2667bea23870fb551284]
2022/10/14 11:49:30 [910] [SESSION_FAILED] [http://172.18.0.8:4444/] [500 Internal Server Error]
2022/10/14 11:49:30 [910] [REMOVING_CONTAINER] [45844d8e952efc3c884ebf6cddcad972a927dda639db7b2d71b649f72d94f3e0]
2022/10/14 11:49:30 [906] [CONTAINER_REMOVED] [737c99aa5e42dbcc0b1e12ff3aa9fbe86f850828102e2667bea23870fb551284]
2022/10/14 11:49:30 [910] [CONTAINER_REMOVED] [45844d8e952efc3c884ebf6cddcad972a927dda639db7b2d71b649f72d94f3e0]
2022/10/14 11:49:30 [907] [SESSION_FAILED] [http://172.18.0.7:4444/] [500 Internal Server Error]
2022/10/14 11:49:30 [907] [REMOVING_CONTAINER] [3204b802ccda7397f3f37d7a42d1ef23e9512fc79d3c951ce54f0982e9b4e899]
2022/10/14 11:49:30 [907] [CONTAINER_REMOVED] [3204b802ccda7397f3f37d7a42d1ef23e9512fc79d3c951ce54f0982e9b4e899]
2022/10/14 11:49:31 [909] [SESSION_FAILED] [http://172.18.0.9:4444/] [500 Internal Server Error]
2022/10/14 11:49:31 [909] [REMOVING_CONTAINER] [7a7b2a079e617037df6b35390ba81c6cd49e2fc1e6dfad96cf65e13b87fc4dae]
2022/10/14 11:49:31 [909] [CONTAINER_REMOVED] [7a7b2a079e617037df6b35390ba81c6cd49e2fc1e6dfad96cf65e13b87fc4dae]
2022/10/14 11:49:33 [919] [SERVICE_STARTED] [selenoid/chrome:104.0] [2aa75c8ef56ac2e172a3c190cd96fdf19303888333872ca7dcd83f8b0307f9c5] [3.57s]
2022/10/14 11:49:33 [919] [PROXY_TO] [2aa75c8ef56ac2e172a3c190cd96fdf19303888333872ca7dcd83f8b0307f9c5] [http://172.18.0.6:4444/]
2022/10/14 11:49:33 [919] [SESSION_ATTEMPTED] [http://172.18.0.6:4444/] [1]
2022/10/14 11:49:33 [918] [SERVICE_STARTED] [selenoid/chrome:104.0] [58062e14261ed75837a198726eff895cd839d01ea3588bed84649437e24f4ee3] [3.83s]
2022/10/14 11:49:33 [918] [PROXY_TO] [58062e14261ed75837a198726eff895cd839d01ea3588bed84649437e24f4ee3] [http://172.18.0.10:4444/]
2022/10/14 11:49:33 [918] [SESSION_ATTEMPTED] [http://172.18.0.10:4444/] [1]
2022/10/14 11:49:33 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2022/10/14 11:49:33 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2022/10/14 11:49:33 [922] [LOCATING_SERVICE] [chrome] []
2022/10/14 11:49:33 [-] [DEFAULT_VERSION] [Using default version: 104.0]
2022/10/14 11:49:33 [922] [USING_DOCKER] [chrome] [104.0]
2022/10/14 11:49:33 [922] [CREATING_CONTAINER] [selenoid/chrome:104.0]
2022/10/14 11:49:33 [922] [STARTING_CONTAINER] [selenoid/chrome:104.0] [19316bee4d16e02ea9491dd05620a094d57c7dc8cc68a023bb3d79ab0d2c565b]
2022/10/14 11:49:34 [922] [CONTAINER_STARTED] [selenoid/chrome:104.0] [19316bee4d16e02ea9491dd05620a094d57c7dc8cc68a023bb3d79ab0d2c565b] [0.34s]
