### ISSUE TITLE
how to establish the node running in different machine?

### ISSUE THREAD

**Issue by loudDD** [aerokube/selenoid#982]
i have 3 machines that could run docker selenoid , how can i use the same hub to run test cases in all these 3 machine's node ?

**Comment by loudDD** [comment]
is selenoid support distributed deployment ?

**Comment by vania-pooh** [comment]
@loudDD yes, we have a separate project called Ggr to deliver this. https://github.com/aerokube/ggr

**Comment by loudDD** [comment]
3Q so much
