### ISSUE TITLE
Page crash (Aw, Snap!) issues on chrome 85.0 with video enabled

### ISSUE THREAD

**Issue by dparadisZentelia** [aerokube/selenoid#983]
My tests start fail with the new Chrome 85 with video enabled.
No problem with the Chrome 84.

Seems to be a resource issue, because when I disabled the video, all works fine.

My test open the login page and after the login, a slow loading start and finish with a chrome crash.
Aw, Snap!
Something went wrong while displaying this webpage.
Error code: 9

<img width="509" alt="Screen Shot 2020-09-03 at 8 48 01 AM" src="https://user-images.githubusercontent.com/64043074/92117989-e5524080-edc3-11ea-888f-f796a51dedcd.png">

UnhandledException: OpenQA.Selenium.WebDriverException : unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed

2 ways to workaround the problem:
- force version 84.
- disable the video

I can't provide the same test, because the web apps is not available on the Internet.
But I can share this simple test setup:

```
 [Test]
        [Description("To reproduce Chrome crash problem with video")]
        public void TestCrashChrome85WithVideo()
        {
            ChromeOptions options = new ChromeOptions();
            options.AcceptInsecureCertificates = true;
            options.SetLoggingPreference(LogType.Browser, LogLevel.Severe);
            options.LeaveBrowserRunning = true;
            options.AddAdditionalCapability("screenResolution", "1920x1080x24", true);
            options.AddAdditionalCapability("enableVNC", true, true);
            options.AddAdditionalCapability("name", Context.GetTestName(), true);
            
            //comment this line to disable video
            options.AddAdditionalCapability("enableVideo", true, true);

            options.AddAdditionalCapability("videoName",Context.GetSelenoidVideoName(), true);
            options.AddAdditionalCapability("requireWindowFocus", true, true); 
            var caps2 = options.ToCapabilities();
            driver = new RemoteWebDriver(new Uri(Context.GetSelenoidUrl()),caps2);

            driver.Navigate().GoToUrl("https://www.speedtest.net/");
            driver.findElement().Click(By.XPath("//a[contains(@aria-label,'start speed test')]"));

            string uploadSpeed = "";
            int count = 0;
            while(uploadSpeed.Length < 2)
            {
                uploadSpeed = driver.FindElement(By.XPath("//span[contains(@class,'upload-speed')]")).Text;
                Thread.Sleep(1000);
                count++;
                Log.Debug("Speed (" + count+ "): [" + uploadSpeed + "]");
                if (count > 60)
                {
                    break;
                }
            } 
        }
```

**Comment by vania-pooh** [comment]
@dparadisZentelia take a look at memory consumption. When system is running out of memory kernel starts to kill the most consuming processes.

**Comment by vania-pooh** [comment]
@dparadisZentelia under Linux commands like `free -h`.

**Comment by dparadisZentelia** [comment]
```
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.2G        155M        148M        464M        111M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.2G        121M        184M        492M         74M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G        112M        194M        456M         41M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G        114M        202M        449M         36M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G        106M        199M        440M         25M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G         85M        235M        459M         31M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G         90M        235M        450M         31M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G         85M        237M        455M         28M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G         85M        239M        457M         27M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G         85M        242M        452M         24M
Swap:          1.0G        1.0G          0B
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.3G        108M        242M        494M         32M
Swap:          1.0G        1.0G          0B

-----After the browser crash ----

selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        3.2G        149M        100M        477M        143M
```

**Comment by dparadisZentelia** [comment]
I change docker config to use more swap and more memory.
Before: 1GB of swap and 4GB of memory
Now: 2GB of swap and 5GB of memory

Now the test can run with Chrome 85 and the video. 

selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.8G        180M        174M        910M        660M
Swap:          2.0G         87M        1.9G
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.8G        156M        197M        934M        626M
Swap:          2.0G         87M        1.9G
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.7G        141M        226M        961M        564M
Swap:          2.0G         88M        1.9G
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.8G        116M        238M        972M        526M
Swap:          2.0G         89M        1.9G
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.8G        143M        257M        920M        420M
Swap:          2.0G        119M        1.9G
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.8G        136M        247M        911M        414M
Swap:          2.0G        119M        1.9G
selenium@localhost:/$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4.8G        3.8G        174M        235M        905M        458M
Swap:          2.0G        118M        1.9G

**Comment by dparadisZentelia** [comment]
Base on my last comment, I close the issue.
