### ISSUE TITLE
Firefox 80 failing after a couple minutes in parallel

### ISSUE THREAD

**Issue by jacattau** [aerokube/selenoid#985]
I've been testing out Selenoid to see if it would be a good solution for us and I was super impressed when Chrome was so fast and worked incredibly well.  However I am not able to run tests effectively in Firefox.  I run 5 tests in parallel (which for a 6 core machine should be no problem and there were no problems with Chrome) and after just a few minutes I get random failures but they all have 1 of 2 errors.  

The main error is: org.openqa.selenium.NoSuchSessionException: Tried to run command without establishing a connection
This error will usually happen after 1 or 2 tests pass in a class.

Less rarely I see this error: NoSuchWindowException: Browsing context has been discarded

My guess is Firefox is probably crashing, but I'm unsure why.  

Here is my browsers.json
`{
    "chrome": {
        "default": "85.0",
        "versions": {
            "85.0": {
                "image": "selenoid/chrome:85.0",
                "port": "4444",
                "path": "/",
                "tmpfs": {"/tmp": "size=512m", "/var": "size=128m"},
                "shmSize" : 2147483648
            }
        }
    },
    "firefox": {
        "default": "80.0",
        "versions": {
            "80.0": {
                "image": "selenoid/firefox:80.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {"/tmp": "size=512m", "/var": "size=128m"},
                "shmSize" : 2147483648
            }
        }
    }
}
`

I start selenoid with this command:
`HTTP_PROXY=proxy.company.com:8080 HTTPS_PROXY=proxy.company.com:8080 ./cm selenoid start --args "-limit 10" --shm-size 2000`

I am unsure of what else to try.  Is anyone else having this issue?

Let me know what else I can provide.  This is what I get from running "docker logs selenoid":
`[2020/09/04 15:46:35 [-] [INIT] [Loading configuration files...]
2020/09/04 15:46:35 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/09/04 15:46:35 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/09/04 15:46:35 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2020/09/04 15:46:35 [-] [INIT] [Using Docker API version: 1.40]
2020/09/04 15:46:35 [-] [INIT] [Timezone: UTC]
2020/09/04 15:46:35 [-] [INIT] [Listening on :4444]
2020/09/04 15:50:16 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [1] [LOCATING_SERVICE] [firefox] []
2020/09/04 15:50:16 [0] [LOCATING_SERVICE] [firefox] []
2020/09/04 15:50:16 [-] [DEFAULT_VERSION] [Using default version: 80.0]
2020/09/04 15:50:16 [-] [DEFAULT_VERSION] [Using default version: 80.0]
2020/09/04 15:50:16 [1] [USING_DOCKER] [firefox] [80.0]
2020/09/04 15:50:16 [0] [USING_DOCKER] [firefox] [80.0]
2020/09/04 15:50:16 [0] [CREATING_CONTAINER] [selenoid/firefox:80.0]
2020/09/04 15:50:16 [1] [CREATING_CONTAINER] [selenoid/firefox:80.0]
2020/09/04 15:50:16 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [2] [LOCATING_SERVICE] [firefox] []
2020/09/04 15:50:16 [-] [DEFAULT_VERSION] [Using default version: 80.0]
2020/09/04 15:50:16 [2] [USING_DOCKER] [firefox] [80.0]
2020/09/04 15:50:16 [2] [CREATING_CONTAINER] [selenoid/firefox:80.0]
2020/09/04 15:50:16 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [3] [LOCATING_SERVICE] [firefox] []
2020/09/04 15:50:16 [-] [DEFAULT_VERSION] [Using default version: 80.0]
2020/09/04 15:50:16 [3] [USING_DOCKER] [firefox] [80.0]
2020/09/04 15:50:16 [3] [CREATING_CONTAINER] [selenoid/firefox:80.0]
2020/09/04 15:50:16 [0] [STARTING_CONTAINER] [selenoid/firefox:80.0] [c5dc9643c8a7d52fc17105f98d177b7c48af0d021612c36917111d4c11a13f9a]
2020/09/04 15:50:16 [1] [STARTING_CONTAINER] [selenoid/firefox:80.0] [5e354dabcb5a60e53664e14ebc6c752fefc33ed9429c780f07690b3b417b082b]
2020/09/04 15:50:16 [2] [STARTING_CONTAINER] [selenoid/firefox:80.0] [f61efae793d25677f57487bc53b0334602d0f8c83775f755d67dff5337200f8d]
2020/09/04 15:50:16 [3] [STARTING_CONTAINER] [selenoid/firefox:80.0] [a86ae6b1d0e4797fafa50d167d43f62a4f771c745f03dd23b05513cb7146c7f2]
2020/09/04 15:50:16 [-] [NEW_REQUEST] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.18.0.1]
2020/09/04 15:50:16 [4] [LOCATING_SERVICE] [firefox] []
2020/09/04 15:50:16 [-] [DEFAULT_VERSION] [Using default version: 80.0]
2020/09/04 15:50:16 [4] [USING_DOCKER] [firefox] [80.0]
2020/09/04 15:50:16 [4] [CREATING_CONTAINER] [selenoid/firefox:80.0]
2020/09/04 15:50:16 [4] [STARTING_CONTAINER] [selenoid/firefox:80.0] [96e3579c37d4b92c4d3c192c3a09291963e89b4781020887d1c83fcdc9eacfcf]
2020/09/04 15:50:17 [1] [CONTAINER_STARTED] [selenoid/firefox:80.0] [5e354dabcb5a60e53664e14ebc6c752fefc33ed9429c780f07690b3b417b082b] [0.81s]
2020/09/04 15:50:17 [0] [CONTAINER_STARTED] [selenoid/firefox:80.0] [c5dc9643c8a7d52fc17105f98d177b7c48af0d021612c36917111d4c11a13f9a] [0.84s]
2020/09/04 15:50:17 [2] [CONTAINER_STARTED] [selenoid/firefox:80.0] [f61efae793d25677f57487bc53b0334602d0f8c83775f755d67dff5337200f8d] [0.87s]
2020/09/04 15:50:17 [4] [CONTAINER_STARTED] [selenoid/firefox:80.0] [96e3579c37d4b92c4d3c192c3a09291963e89b4781020887d1c83fcdc9eacfcf] [0.75s]
2020/09/04 15:50:17 [3] [CONTAINER_STARTED] [selenoid/firefox:80.0] [a86ae6b1d0e4797fafa50d167d43f62a4f771c745f03dd23b05513cb7146c7f2] [0.98s]
2020/09/04 15:50:20 [4] [SERVICE_STARTED] [selenoid/firefox:80.0] [96e3579c37d4b92c4d3c192c3a09291963e89b4781020887d1c83fcdc9eacfcf] [2.83s]
2020/09/04 15:50:20 [4] [PROXY_TO] [96e3579c37d4b92c4d3c192c3a09291963e89b4781020887d1c83fcdc9eacfcf] [http://172.18.0.7:4444/wd/hub]
2020/09/04 15:50:20 [4] [SESSION_ATTEMPTED] [http://172.18.0.7:4444/wd/hub] [1]
2020/09/04 15:50:20 [3] [SERVICE_STARTED] [selenoid/firefox:80.0] [a86ae6b1d0e4797fafa50d167d43f62a4f771c745f03dd23b05513cb7146c7f2] [2.81s]
2020/09/04 15:50:20 [3] [PROXY_TO] [a86ae6b1d0e4797fafa50d167d43f62a4f771c745f03dd23b05513cb7146c7f2] [http://172.18.0.6:4444/wd/hub]
2020/09/04 15:50:20 [3] [SESSION_ATTEMPTED] [http://172.18.0.6:4444/wd/hub] [1]
2020/09/04 15:50:20 [2] [SERVICE_STARTED] [selenoid/firefox:80.0] [f61efae793d25677f57487bc53b0334602d0f8c83775f755d67dff5337200f8d] [2.97s]
2020/09/04 15:50:20 [2] [PROXY_TO] [f61efae793d25677f57487bc53b0334602d0f8c83775f755d67dff5337200f8d] [http://172.18.0.5:4444/wd/hub]
2020/09/04 15:50:20 [2] [SESSION_ATTEMPTED] [http://172.18.0.5:4444/wd/hub] [1]
2020/09/04 15:50:20 [0] [SERVICE_STARTED] [selenoid/firefox:80.0] [c5dc9643c8a7d52fc17105f98d177b7c48af0d021612c36917111d4c11a13f9a] [3.01s]
2020/09/04 15:50:20 [0] [PROXY_TO] [c5dc9643c8a7d52fc17105f98d177b7c48af0d021612c36917111d4c11a13f9a] [http://172.18.0.3:4444/wd/hub]
2020/09/04 15:50:20 [0] [SESSION_ATTEMPTED] [http://172.18.0.3:4444/wd/hub] [1]
2020/09/04 15:50:20 [1] [SERVICE_STARTED] [selenoid/firefox:80.0] [5e354dabcb5a60e53664e14ebc6c752fefc33ed9429c780f07690b3b417b082b] [3.07s]
2020/09/04 15:50:20 [1] [PROXY_TO] [5e354dabcb5a60e53664e14ebc6c752fefc33ed9429c780f07690b3b417b082b] [http://172.18.0.4:4444/wd/hub]
2020/09/04 15:50:20 [1] [SESSION_ATTEMPTED] [http://172.18.0.4:4444/wd/hub] [1]
2020/09/04 15:50:26 [3] [SESSION_CREATED] [e2d933ec-34ab-419a-9a41-cbefaa0ba9b4] [1] [9.89s]
2020/09/04 15:50:26 [2] [SESSION_CREATED] [3838cabf-6541-40f2-bd42-dba12aa2d5dc] [1] [9.90s]
2020/09/04 15:50:26 [0] [SESSION_CREATED] [b347acd1-cf49-4898-8602-6e2232c911d8] [1] [9.94s]
2020/09/04 15:50:26 [4] [SESSION_CREATED] [e3669da3-4b97-492e-8fb9-f7d327fa24f4] [1] [9.79s]
2020/09/04 15:50:26 [1] [SESSION_CREATED] [bb5b0298-09e3-4a91-b4f6-f389ef0e0b94] [1] [10.03s]
2020/09/04 15:54:29 [7832] [SESSION_DELETED] [b347acd1-cf49-4898-8602-6e2232c911d8]
2020/09/04 15:54:29 [7835] [SESSION_DELETED] [e3669da3-4b97-492e-8fb9-f7d327fa24f4]
2020/09/04 15:54:29 [7837] [SESSION_DELETED] [3838cabf-6541-40f2-bd42-dba12aa2d5dc]
2020/09/04 15:54:29 [7836] [SESSION_DELETED] [e2d933ec-34ab-419a-9a41-cbefaa0ba9b4]
2020/09/04 15:54:29 [7838] [SESSION_DELETED] [bb5b0298-09e3-4a91-b4f6-f389ef0e0b94]
2020/09/04 15:54:30 [3] [REMOVING_CONTAINER] [a86ae6b1d0e4797fafa50d167d43f62a4f771c745f03dd23b05513cb7146c7f2]
2020/09/04 15:54:30 [2] [REMOVING_CONTAINER] [f61efae793d25677f57487bc53b0334602d0f8c83775f755d67dff5337200f8d]
2020/09/04 15:54:32 [3] [CONTAINER_REMOVED] [a86ae6b1d0e4797fafa50d167d43f62a4f771c745f03dd23b05513cb7146c7f2]
2020/09/04 15:54:32 [2] [CONTAINER_REMOVED] [f61efae793d25677f57487bc53b0334602d0f8c83775f755d67dff5337200f8d]
2020/09/04 15:54:34 [0] [REMOVING_CONTAINER] [c5dc9643c8a7d52fc17105f98d177b7c48af0d021612c36917111d4c11a13f9a]
2020/09/04 15:54:34 [4] [REMOVING_CONTAINER] [96e3579c37d4b92c4d3c192c3a09291963e89b4781020887d1c83fcdc9eacfcf]
2020/09/04 15:54:35 [0] [CONTAINER_REMOVED] [c5dc9643c8a7d52fc17105f98d177b7c48af0d021612c36917111d4c11a13f9a]
2020/09/04 15:54:35 [4] [CONTAINER_REMOVED] [96e3579c37d4b92c4d3c192c3a09291963e89b4781020887d1c83fcdc9eacfcf]
2020/09/04 15:54:35 [1] [REMOVING_CONTAINER] [5e354dabcb5a60e53664e14ebc6c752fefc33ed9429c780f07690b3b417b082b]
2020/09/04 15:54:35 [1] [CONTAINER_REMOVED] [5e354dabcb5a60e53664e14ebc6c752fefc33ed9429c780f07690b3b417b082b]
`

**Comment by vania-pooh** [comment]
@jacattau I would take a look at memory consumption first.

**Comment by jacattau** [comment]
@vania-pooh maybe I am missing it but I am not seeing what command to run to check this.  Could you point me in the right direction?  If i do see that i don't have sufficient memory how would I go about adding more?  I set the shmSize to 2gb already.

**Comment by vania-pooh** [comment]
@jacattau I mean using commands like `free` and `top`.

**Comment by jacattau** [comment]
I wasn't getting `free` to work but I did get `top` to work even though it wasn't showing me much in the way of memory usage.  I used `docker stats` and that got me some usage in real time.

I upped the memory from 2gb to 4gb but that only seemed to help a little.  From the point my tests started failing here was the usage statistics:

CONTAINER ID        NAME                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
5ef51bfc985e        selenoid               8.55%               7.445MiB / 3.848GiB   0.19%               361MB / 377MB       0B / 0B             19
0d09bf806e4c        focused_wescoff        0.29%               29.5MiB / 3.848GiB    0.75%               26.2MB / 5.51MB     0B / 0B             49
c87fb79d137d        gifted_chandrasekhar   75.79%              727.8MiB / 3.848GiB   18.47%              22.6MB / 4.6MB      0B / 0B             202
506747aff18c        modest_cohen           142.32%             725.6MiB / 3.848GiB   18.42%              19.1MB / 4.46MB     0B / 0B             201
b8a84da8cba6        xenodochial_liskov     68.34%              852.8MiB / 3.848GiB   21.64%              19.2MB / 3.95MB     0B / 0B             202
dc616d60aaed        gracious_engelbart     67.33%              718.3MiB / 3.848GiB   18.23%              17.3MB / 3.85MB     0B / 0B             200

So it looks like even though upping the memory to 4gb shouldn't have made a difference from 2gb.  However, it did work better with 4gb but I am still seeing this issue.  Right now it's about 24 failures out of 600 tests.  I am running on a 6 core machine so it should 100% be able to handle 5 parallel sessions right?

I do not think I have video recording running unless I am misunderstanding the documentation.  Do I need to do anything to disable video?  From what I understand it's disabled unless I set the capability to true.

**Comment by vania-pooh** [comment]
@jacattau could you attach a log of failed session here (it will be automatically saved when `enableLog` capability is set)? Video recording is turned off by default.

**Comment by jacattau** [comment]
Hi @vania-pooh I will try to get that to you, but I think there might actually be an issue with Firefox 80.0 itself.  I noticed they quickly released version 80.0.1 with this release notes: https://www.mozilla.org/en-US/firefox/80.0.1/releasenotes/

I started running tests on Firefox 79 (I didn't see a selenoid image for 80.0.1) and so far it seems to be working but I haven't finished a single regression suite yet. I will hammer 79 pretty hard and see if I can reproduce.

**Comment by vania-pooh** [comment]
@jacattau they are doing hotfix releases almost for every stable release. But if your theory confirms - let's rebuild and image with 80.0.1 then.

**Comment by jacattau** [comment]
@vania-pooh i do think there is an issue with 80.  I've been having success with 79 outside of the issue in #713  although i am seeing this on Chrome as well.  At this point #713 might be the only thing keeping me from adopting selenoid right now.
