### ISSUE TITLE
MS Edge in selenoid hub

### ISSUE THREAD

**Issue by al7dckh5gb** [aerokube/selenoid#986]
Hello guys.

I came to a problem today, which is related to MS EDGE with chromium. When selenoid hub is started, I am able to run the first test (with ms edge browser) once - it opens the browser, but not for the second time, it ends up with timeout - org.openqa.selenium.WebDriverException: cannot create session MicrosoftEdge-85.0 on any hosts after 1 attempt(s) (WARNING: The server did not provide any stacktrace information)

In selenoid logs at my selenoid hub -> 2020/09/07 16:30:10 [-] [NEW_REQUEST] [unknown] [MY_IP]
In ggr logs -> 2020/09/07 14:30:11 [17] [0.00s] [SESSION_ATTEMPTED] [test] [172.17.0.1] [MicrosoftEdge-85.0]

I am using MS EDGE 85.0.564.44 64-bit
MsEdgeDriver: 85.0.564.44 on port 9515
SELENOID_ID run as Administrator
Internet Explorer Driver server version 3.9.0.0 (had 3.150.0.0 before, I updated it)

I don't know, if this has something to do with this issue, but in SELENOID_IE server I can see this:
DevTools listening on ws://127.0.0.1:49704/devtools/browser/someid
ERROR: edge_auth_errors.cc(374). EDGE_IDENTITY: Get default OS account failed: Error: Primary Error: kImplicitSignInFailure, secondary error: kAccountProviderFetchError.
ERROR: device_event_log_impl.cc(208). Bluetooth: bluetooth_adapter_winrt.cc: 1074 Getting default adapter failed.

Thank you for your help :)

**Comment by vania-pooh** [comment]
@al7dckh5gb at least old Edge (EdgeHTML) was able to run only 1 copy in parallel.

**Comment by al7dckh5gb** [comment]
@vania-pooh I am not trying to run tests in parallel. But sequential. First test ends, second starts, but second is not able to create session.

**Comment by vania-pooh** [comment]
@al7dckh5gb what is your Selenoid server `-limit` parameter value? Couldn't it be that your request simply goes to Selenoid queue?

**Comment by al7dckh5gb** [comment]
My limit is 1.

After first test, url:8888/status has: "pending":0,"queued":0,"total":1,"used":1... browser is opened & closed (that's fine)
After second test, URL:8888/status has: "pending":0,"queued":1,"total":1,"used":1}... why? I am the only one who uses this, so there can't be anyone else.

**Comment by vania-pooh** [comment]
@al7dckh5gb are you closing session with `driver.quit()`?

**Comment by al7dckh5gb** [comment]
Yes, I forgot.. 🥇 Sorry.. I used java code from selenoid-ui, but I totally forgot about driver.quit(); Thank you!
