### ISSUE TITLE
Immediately when i run command selenoid/android:7.1 or any container crashes VM is hanged

### ISSUE THREAD

**Issue by vikramnagaraju31** [aerokube/selenoid#988]
@vania-pooh 
Am running below command on ubuntu VM on MAC enabled with nested virtualisation enabled, once i run my virtual machine is hanged also container crashes, can you please help me on this if am missing something.
docker run -d --name emulator-test -e ENABLE_VNC=true -e SKIN=WXGA800 --privileged -p 5900:5900 -p 8888:4444 selenoid/android:7.1

**Comment by vania-pooh** [comment]
@vikramnagaraju31 probably have try to rebuild image yourself if you are seeing segfaults in logs.

**Comment by vikramnagaraju31** [comment]
@vania-pooh 
Thank for the response..
Am getting below error when i run the container, device seems to be offline also i have enabled nested virtualization. 

kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

Error Logs
qemu-system-i386: warning: TSC frequency mismatch between VM (1995379 kHz) and host (2304000 kHz), and TSC scaling unavailable
qemu-system-i386: warning: TSC frequency mismatch between VM (1995379 kHz) and host (2304000 kHz), and TSC scaling unavailable
KVM: entry failed, hardware error 0x80000021

If you're running a guest on an Intel machine without unrestricted mode
support, the failure can be most likely due to the guest entering an invalid
state for Intel VT. For example, the guest maybe running in big real mode
which is not supported on less recent Intel processors.

* daemon started successfully
error: device offline
/entrypoint.sh: line 55:    54 Segmentation fault      (core dumped) ANDROID_AVD_HOME=/root/.android/avd DISPLAY=":$DISPLAY" /opt/android-sdk-linux/emulator/emulator ${EMULATOR_ARGS} -writable-system -no-boot-anim -no-audio -no-jni -avd android6.0-1 -sdcard /sdcard.img -skin "$SKIN" -skindir /opt/android-sdk-linux/platforms/android-23/skins/ -verbose -gpu swiftshader_indirect -ranchu -qemu -enable-kvm
error: no devices/emulators found
error: no devices/emulators found
error: no devices/emulators found

**Comment by TimurNurlygayanov** [comment]
My setup:
Ubuntu 20.04 TLS
```
uname -a
Linux xwzard 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

```
CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz


The same issue I have with android 10 emulator - the container starts and then immediately crashing, and I see the following errors in logs:

```
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
Waiting X server...
* daemon not running; starting now at tcp:5037

 --- x11vnc loop: 1 ---

* daemon started successfully
adb: no devices/emulators found
 --- x11vnc loop: waiting for: 99

PORT=5900
emulator: WARNING: System image is writable
host doesn't support requested feature: CPUID.80000001H:ECX.abm [bit 5]
host doesn't support requested feature: CPUID.80000001H:ECX.abm [bit 5]
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
WARNING. Using fallback path for the emulator registration directory.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

qemu-system-x86_64: warning: TSC frequency mismatch between VM (1995379 kHz) and host (3292519 kHz), and TSC scaling unavailable
qemu-system-x86_64: warning: TSC frequency mismatch between VM (1995379 kHz) and host (3292519 kHz), and TSC scaling unavailable
adb: device offline
```

**Comment by vania-pooh** [comment]
@vikramnagaraju31 I would try to rebuild the image under the same machine. Could be because of different VM memory snapshot format.
