### ISSUE TITLE
Creating my images for Android with Specific Android Version

### ISSUE THREAD

**Issue by shj941013** [aerokube/selenoid#989]
Hello,

I am trying to create an image using the guideline here: https://github.com/aerokube/selenoid-images

and had some questions regarding to it. When creating android images, how can I specify to create it for version 11.0?

I don't see image creation for chrome-mobile, how can I create for these?

**Comment by vania-pooh** [comment]
@shj941013 all these questions are asked in this interactive script: https://github.com/aerokube/selenoid-images/blob/master/selenium/automate_android.sh
