### ISSUE TITLE
Using Official MS EDGE Docker image

### ISSUE THREAD

**Issue by inluxc** [aerokube/selenoid#990]
Is there a way we can use Microsoft Edge Browser Docker image to run tests with Selenoid?

https://hub.docker.com/_/microsoft-msedge-msedgedriver

**Comment by vania-pooh** [comment]
@inluxc take a look at these instructions: https://github.com/aerokube/windows-images

**Comment by chrischjh** [comment]
@inluxc It seems that the MS Edge docker image is Windows docker image instead of Linux docker image, Selenoid could only work with Linux docker image

**Comment by vania-pooh** [comment]
@chrischjh probably, but so far as I know in Windows Docker images it is impossible to start applications with graphical interface.

**Comment by chrischjh** [comment]
Edge coming to Linux: https://www.omgubuntu.co.uk/2020/09/microsoft-edge-linux-preview-october

**Comment by vania-pooh** [comment]
@chrischjh yeah, we'll build an official image then.

**Comment by mcahornsirup** [comment]
Edge should be available via the packet manager or directly via the dev channel https://www.microsoftedgeinsider.com/de-de/download I'am really looking forward for the new docker image!

**Comment by vania-pooh** [comment]
@mcahornsirup not yet for Linux.

**Comment by mcahornsirup** [comment]
> @mcahornsirup not yet for Linux.
Yes, not yet, but very, very soon : )

**Comment by mcahornsirup** [comment]
Progress: https://www.microsoftedgeinsider.com/en-us/download/?platform=linux-deb

**Comment by vania-pooh** [comment]
@mcahornsirup closing in favor to aerokube/images#302.
