### ISSUE TITLE
no such file or directory when saving Videos

### ISSUE THREAD

**Issue by pradipyogi59** [aerokube/selenoid#992]
System is : Docker desktop 2.3.0.5 (48029)
Windows 10

Images are : 
aerokube/selenoid-ui latest
aerokube/selenoid 1.10.0
selenoid/video-recorder latest-release
selenoid/chrome 84.0

Command i run :   docker run  -d --name pradip -p 4444:4444 
-v //var/run/docker.sock:/var/run/docker.sock 
-v /c/Users/pradipkumar.yogi/selenoid/config/:/etc/selenoid/:ro 
-v /c/Users/pradipkumar.yogi/selenoid/video/:/opt/selenoid/video/ 
-e OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/pradipkumar.yogi/selenoid/video/ aerokube/selenoid:1.10.0

Also tried with yaml file : 

version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.10.0"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/c/Users/pradipkumar.yogi/selenoid/config/:/etc/selenoid/" 
      - "/c/Users/pradipkumar.yogi/selenoid/video/:/opt/selenoid/video"
      - "//var/run/docker.sock:/var/run/docker.sock"  
      
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/pradipkumar.yogi/selenoid/video/"
    command: ["-limit", "10","-video-output-dir",
 "/opt/selenoid/video"]
      
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.1"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"] 

Logs : 
2020/09/23 11:37:25 [-] [INIT] [Loading configuration files...]
2020/09/23 11:37:25 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/09/23 11:37:25 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/09/23 11:37:25 [-] [INIT] [Your Docker API version is 1.40]
2020/09/23 11:37:25 [-] [INIT] [Timezone: UTC]
2020/09/23 11:37:25 [-] [INIT] [Listening on :4444]
2020/09/23 11:37:47 [-] [NEW_REQUEST] [unknown] [172.17.0.1]
2020/09/23 11:37:47 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.17.0.1]
2020/09/23 11:37:47 [0] [LOCATING_SERVICE] [chrome] [85.0]
2020/09/23 11:37:47 [0] [USING_DOCKER] [chrome] [85.0]
2020/09/23 11:37:47 [0] [CREATING_CONTAINER] [selenoid/chrome:85.0]
2020/09/23 11:37:47 [0] [STARTING_CONTAINER] [selenoid/chrome:85.0] [66eea2b97725c5e42b56d32068a318d2acb9ebd94f353a863d2e5a03b55aeedb]
2020/09/23 11:37:48 [0] [CONTAINER_STARTED] [selenoid/chrome:85.0] [66eea2b97725c5e42b56d32068a318d2acb9ebd94f353a863d2e5a03b55aeedb] [0.34s]
2020/09/23 11:37:48 [0] [CREATING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release]
2020/09/23 11:37:48 [0] [STARTING_VIDEO_CONTAINER] [selenoid/video-recorder:latest-release] [3d5f06b84e6cf703aeba4e60ee5c92be2681fdfb8de6ff7859f69f2ecc1be904]
2020/09/23 11:37:48 [0] [VIDEO_CONTAINER_STARTED] [selenoid/video-recorder:latest-release] [3d5f06b84e6cf703aeba4e60ee5c92be2681fdfb8de6ff7859f69f2ecc1be904] [0.45s]
2020/09/23 11:37:48 [0] [SERVICE_STARTED] [selenoid/chrome:85.0] [66eea2b97725c5e42b56d32068a318d2acb9ebd94f353a863d2e5a03b55aeedb] [0.00s]
2020/09/23 11:37:48 [0] [PROXY_TO] [66eea2b97725c5e42b56d32068a318d2acb9ebd94f353a863d2e5a03b55aeedb] [http://172.17.0.4:4444/]
2020/09/23 11:37:48 [0] [SESSION_ATTEMPTED] [http://172.17.0.4:4444/] [1]
2020/09/23 11:37:49 [0] [SESSION_CREATED] [4dd701dfec4f2040cb7b6e33e04c234d] [1] [1.14s]
2020/09/23 11:38:15 [75] [SESSION_DELETED] [4dd701dfec4f2040cb7b6e33e04c234d]
2020/09/23 11:38:15 [0] [STOPPING_VIDEO_CONTAINER] [3d5f06b84e6cf703aeba4e60ee5c92be2681fdfb8de6ff7859f69f2ecc1be904]
2020/09/23 11:38:16 [0] [REMOVING_CONTAINER] [3d5f06b84e6cf703aeba4e60ee5c92be2681fdfb8de6ff7859f69f2ecc1be904]
2020/09/23 11:38:16 [0] [FAILED_TO_REMOVE_CONTAINER] [3d5f06b84e6cf703aeba4e60ee5c92be2681fdfb8de6ff7859f69f2ecc1be904] [Error response from daemon: removal of container 3d5f06b84e6cf703aeba4e60ee5c92be2681fdfb8de6ff7859f69f2ecc1be904 is already in progress]
2020/09/23 11:38:16 [0] [REMOVING_CONTAINER] [66eea2b97725c5e42b56d32068a318d2acb9ebd94f353a863d2e5a03b55aeedb]
2020/09/23 11:38:17 [0] [CONTAINER_REMOVED] [66eea2b97725c5e42b56d32068a318d2acb9ebd94f353a863d2e5a03b55aeedb]
2020/09/23 11:38:17 [0] [VIDEO_ERROR] [Failed to rename /opt/selenoid/video/selenoidf3855e8da4237051c949f89211cdef4f.mp4 to /opt/selenoid/video/4dd701dfec4f2040cb7b6e33e04c234d.mp4: rename /opt/selenoid/video/selenoidf3855e8da4237051c949f89211cdef4f.mp4 /opt/selenoid/video/4dd701dfec4f2040cb7b6e33e04c234d.mp4: no such file or directory]

Also docker container inspect data :

  "Mounts": [
            {
                "Type": "bind",
                "Source": "/run/desktop/mnt/host/c/Users/pradipkumar.yogi/selenoid/video",
                "Destination": "/opt/selenoid/video",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/run/desktop/mnt/host/c/Users/pradipkumar.yogi/selenoid/config",
                "Destination": "/etc/selenoid",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "8edb86ae3a94",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4444/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/pradipkumar.yogi/selenoid/video/",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "aerokube/selenoid:1.10.0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/selenoid",
                "-listen",
                ":4444",
                "-conf",
                "/etc/selenoid/browsers.json",
                "-video-output-dir",
                "/opt/selenoid/video/"
            ],
            "OnBuild": null,
            "Labels": {}
        },

Please help not able to generate videos.

**Comment by vania-pooh** [comment]
@pradipyogi59 probably you should try to use the same source path in `OVERRIDE_VIDEO_OUTPUT_DIR` variable:
```
"Source": "/run/desktop/mnt/host/c/Users/pradipkumar.yogi/selenoid/video"
```

**Comment by pradipyogi59** [comment]
Like this :
OVERRIDE_VIDEO_OUTPUT_DIR="Source": "/run/desktop/mnt/host/c/Users/pradipkumar.yogi/selenoid/video"
