### ISSUE TITLE
Can we use selenoid with https url instead of http for running tests?

### ISSUE THREAD

**Issue by Minion0313** [aerokube/selenoid#993]
Hi @vania-pooh @lanwen 
appreciate your help in advance
we are trying to move to AWS cloud, there only secured protocols are allowed
Can we use https instead of http url for selenoid (running the tests)? like the below:
**https://examplehost.hub.com:4444/wd/hub instead of http://examplehost.hub.com:4444/wd/hub???**

**Comment by vania-pooh** [comment]
@Minion0313 you can by using some reverse-proxy server like Nginx. Selenoid intentionally has no built-in TLS support.

**Comment by DicksengA** [comment]
@vania-pooh 
will i be able to connect the ggr instances to selenoid nginx with self-sign certificate?
We are trying to run ggr on prem in openshift and selenoid in AWS, and Azure.
The connection from ggr instances to selenoid have to be secured.

**Comment by vania-pooh** [comment]
@DicksengA you should be able to do this but will need to add respective root CA authority to Ggr [image](https://github.com/aerokube/ggr/blob/master/Dockerfile). It's based on Alpine, so see respective documentation on how to do this.
