### ISSUE TITLE
chrome container won't start after volume configs to enable file upload are in place

### ISSUE THREAD

**Issue by jeremiasalmeida** [aerokube/selenoid#997]
### Changes done to get upload file working:
- Created a volume (`docker volume create selenoid_tmp`)
- Configured `selenoid` to mount `/tmp` to `selenoid_tmp`
- Configured browsers to mount `/tmp` to `selenoid_tmp`
- Started `selenoid` with `-enable-file-upload ` CLI flag

After aforementioned changes are put in place only the first chrome container will spawn all other will fail with `Waiting for Xserver`. I believe this behavior is related with XServer files that are in `/tmp` for the chrome container.

Maybe I am missing something as it seems to me that this issue  would be expected as sharing whole `/tmp` folder between all browser containers seems highly prone to errors.

##### chrome selenium `/tmp`  content
```bash
selenium@localhost:/tmp$ ls -lah
total 32K
drwxrwxrwt  1 root     root 4.0K Sep 30 10:53 .
drwxr-xr-x  1 root     root 4.0K Sep 30 10:53 ..
drwxrwxrwt  2 selenium root 4.0K Sep 30 10:53 .X11-unix
-r--r--r--  1 selenium root   11 Sep 30 10:53 .X99-lock
drwx------  2 selenium root 4.0K Sep 30 10:53 .com.google.Chrome.HQwG2p
drwx------ 18 selenium root 4.0K Sep 30 10:53 .com.google.Chrome.oXbsFN
drwx------  2 selenium root 4.0K Sep 30 10:53 .com.google.Chrome.okRjse
drwx------  2 selenium root 4.0K Sep 30 10:53 xvfb-run.uDRW2u
```

### Versions
selenoid:1.10.0
selenoid/chrome:85.0
##### docker
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Configuration
`docker-compose.yaml`
```
version: '3'
services:
  selenoid:
    networks:
      - selenoid-net
    image: aerokube/selenoid:1.10.0
    container_name: selenoid
    volumes:
      - "/root/selenoid:/etc/selenoid"
      - "/root/selenoid/video:/opt/selenoid/video"
      - "/root/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "selenoid_tmp:/tmp"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json",
              "-video-output-dir", "/opt/selenoid/video",
              "-log-output-dir", "/opt/selenoid/logs",
              "-enable-file-upload",
              "-limit", "10",
              "-retry-count", "5",
              "-container-network", "selenoid-net"]
    ports:
      - "4444:4444"

  selenoid-ui:
    networks:
      - selenoid-net
    image: aerokube/selenoid-ui:1.10.0
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    command: ["-selenoid-uri", "http://localhost:4444"]

networks:
  selenoid-net:
    external:
      name: selenoid-net

volumes:
  selenoid_tmp:
    external:
      name: selenoid_tmp
```
--------
`browsers.json`
```
{
  "chrome": {
    "default": "85.0",
    "versions": {
      "85.0": {
        "image": "selenoid/chrome:85.0",
        "port": "4444",
        "volumes": ["selenoid_tmp:/tmp"],
        "cpu": "2.5",,
        "shmSize" : 2147482548,
        "path": "/"
      }
    }
  },

  "android": {
    "default": "10.0",
    "versions": {
      "10.0": {
        "image": "selenoid/android:10.0",
        "port": "4444",
        "path": "/"
      }
    }
  }
}
```

**Comment by vania-pooh** [comment]
@jeremiasalmeida you are expected to use built-in file upload feature instead of mounting volumes. https://aerokube.com/selenoid/latest/#_uploading_files_to_browser

**Comment by jeremiasalmeida** [comment]
@vania-pooh that is being used already, however the file would not be available in the `chrome` container and rather in `selenoid` container, so by thread https://github.com/aerokube/selenoid/issues/561 I figured that this volume configurations would be necessary

**Comment by vania-pooh** [comment]
@jeremiasalmeida using regular file upload feature will upload to browser container.

**Comment by jeremiasalmeida** [comment]
> @jeremiasalmeida using regular file upload feature will upload to browser container.

That is not what have happened, with `-enable-file-upload` when using [selenium.webdriver.remote.weblement.send_keys](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.0/py/selenium/webdriver/remote/webelement.py#L447) the uploaded file would be found at `selenoid` container rather than in browser container.

- execute `docker exec -it selenoid /bin/sh`
- In selenoid container `cd /tmp` 
- A new folder will appear (in my case `844709bd0432ace738ac7059c9f2c10c `)
- This is the result of a `ls -lah` in `/tmp/844709bd0432ace738ac7059c9f2c10c `
```bash
/tmp# ls -lah /tmp/844709bd0432ace738ac7059c9f2c10c 
total 12
drwxr-xr-x    2 root     root        4.0K Oct  1 11:05 .
drwxr-xr-x    3 root     root        4.0K Oct  1 11:05 ..
-rw-r--r--    1 root     root          40 Oct  1 11:05 text-qa-file.txt
```

If by using the aforementioned function ([selenium.webdriver.remote.weblement.send_keys](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.0/py/selenium/webdriver/remote/webelement.py#L447)) the file be available in chrome I can only see two option **1)** This is a bug; or **2)** I am missing some configuration.

I would say **2** is more likely than **1)**, so what could it be that is missing/wrong?

**Comment by vania-pooh** [comment]
@jeremiasalmeida This flag is only needed for browsers where respective /file API is not implemented (e.g. in Geckodriver). In the majority of situations you never need to use it. We mainly use it when embedding Selenoid to Firefox images.
